name = "Kronwerke Season 2"
author = "Kronwerke"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e876e887e310b441fc70051ec0c441b46fc0ac35912995e1416adee076b908f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
