name = "Kronwerke Season 2"
author = "Kronwerke"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99e4e458f174989599e8b9b4ecf778ccd24c4182e7bcf24a1864be6b49f911c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
