name = "Kronwerke Season 2"
author = "Kronwerke"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "736dde3958d1cf22cf45189f42a278fe3cae6848a85c40815c8f695123391c1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
