"""Applied Energistics 2 in stage 3: meteorites, charged certus (imbuement or energizing orb),
certus growth, the inscriber and processors, the first ME network, cells up to 16k, the
controller and channels, buses, P2P, wireless terminals and autocrafting, plus the parts of
Extended AE and Applied Flux that are open in stage 3. Recipes follow
kubejs/server_scripts/kronwerke/ae2.js. 64k and up, quantum, spatial, MEGA and Advanced AE
are stage 4 and only mentioned."""
from ftbq import (chapter, quest, task_item, reward_item, reward_table, reward_xp, banner)

C = "ae2"

quests = [
    # ---- Meteoriten und Certus ---------------------------------------------
    quest("welcome", 0, 1, "&b&lApplied Energistics 2",
          subtitle="Ein Lager, das mitdenkt.",
          description=[
              "&bApplied Energistics 2&r (kurz AE2) speichert Gegenstände nicht in Truhen, sondern als Daten auf &6Speicherzellen&r. Ein Netz aus Kabeln verbindet die Zellen mit Konsolen, Bussen und Maschinen. Du suchst alles an einer Stelle, und später baut das Netz Dinge sogar selbst.",
              "",
              "&eWas in Stufe 3 offen ist:&r Zellen bis &616k&r, der Controller, Kanäle, Busse, P2P-Tunnel, drahtlose Konsolen und das ganze Autocrafting. Dazu die Teile von &6Extended AE&r, die ohne die großen Ex-Maschinen auskommen, &6Applied Flux&r bis 16k und &6Applied Mekanistics&r.",
              "",
              "&cWas noch wartet:&r 64k- und 256k-Zellen, die Quantenbrücke, Raumspeicher (Spatial IO), &6MEGA Cells&r, &6Advanced AE&r und die Ex-Maschinen von Extended AE kommen in Stufe 4.",
              "",
              "&eErster Schritt:&r Bau ein &6Ladegerät&r (Eisen und Kupfer) und leg einen normalen &6Kompass&r hinein. Strom bekommt das Ladegerät über Kabel oben oder unten, oder du setzt eine &6Holzkurbel&r darauf und drehst von Hand. Heraus kommt ein &6Meteoritenkompass&r, der zum nächsten Meteoriten zeigt.",
          ],
          tasks=[task_item("ae2:meteorite_compass", 1)],
          rewards=[reward_item("ae2:certus_quartz_crystal", 8), reward_table("s3_common")],
          icon="ae2:controller", size=2.0, shape="hexagon"),

    quest("meteorite", 2.5, 0, "&7Meteoriten",
          subtitle="Löcher in der Landschaft mit Schatz in der Mitte.",
          description=[
              "Meteoriten sind große Krater aus &6Himmelsstein&r. Grab dich bis in die Mitte durch. Unterwegs findest du &6Certusquarz-Cluster&r, Knospen und &6Certusquarzknospenblöcke&r in verschiedenen Stufen.",
              "",
              "Ganz innen liegt der &6Mysteriöse Würfel&r. Bau ihn ab, dann bekommst du alle vier Pressen: &6Siliziumdruck&r, &6Logikdruck&r, &6Kalkulationsdruck&r und &6Konstruktionsdruck&r. Mehr brauchst du nie, denn die Gravurmaschine kann Pressen kopieren: Presse oben, &6Eisenblock&r in die Mitte.",
              "",
              "&cAchtung:&r Einen &6Makellosen Certusquarzknospenblock&r nie abbauen. Selbst mit Behutsamkeit wird er dabei zu einem unreinen Block, und makellos bekommst du ihn nicht zurück. Lass ihn stehen und ernte dort.",
              "",
              "Nimm auch einen Stapel Himmelsstein mit. Im Ofen geschmolzen wird er zum &6Himmelssteinblock&r, und den braucht der ME-Controller.",
          ],
          tasks=[task_item("ae2:certus_quartz_crystal", 16), task_item("ae2:sky_stone_block", 16),
                 task_item("ae2:silicon_press", 1), task_item("ae2:logic_processor_press", 1),
                 task_item("ae2:calculation_processor_press", 1), task_item("ae2:engineering_processor_press", 1)],
          rewards=[reward_item("minecraft:iron_block", 2), reward_xp(10)],
          deps=["welcome"], icon="ae2:mysterious_cube"),

    quest("charged", 2.5, 2, "&e&lGeladener Certusquarz",
          subtitle="Erst ein Magier, später ein Kraftwerk.",
          description=[
              "Fast alles in AE2 braucht irgendwann &6Geladenen Certusquarz&r. Auf Kronwerke lädt das Ladegerät keinen Certus mehr, und auch die Abkürzungen anderer Mods sind weg. Es gibt genau zwei Wege.",
              "",
              "&eRezept auf Kronwerke, Weg 1:&r die &6Imbuement-Kammer&r von Ars Nouveau. Leg einen &6Certusquarzkristall&r hinein und stell zwei Sockel daneben, einen mit &6Redstone-Staub&r und einen mit &6Glowstone-Staub&r. Für &d2 000 Quelle&r wird daraus ein geladener Kristall. Langsam, aber jeder Magier kann es von Anfang an.",
              "",
              "&eRezept auf Kronwerke, Weg 2:&r der &6Energizing Orb&r von Powah. Ein Certusquarzkristall und ein Redstone ergeben für &d20 000 FE&r gleich &ezwei&r geladene Kristalle. Der Orb selbst braucht auf Kronwerke einen Manadiamanten von Botania.",
              "",
              "Das Starterpaket von Stufe 3 enthält acht geladene Kristalle. Spar sie für Fluix und die ersten Knospenblöcke.",
          ],
          tasks=[task_item("ae2:charged_certus_quartz_crystal", 8)],
          rewards=[reward_item("minecraft:glowstone_dust", 16), reward_item("minecraft:redstone", 16), reward_xp(5)],
          deps=["welcome"], icon="ae2:charged_certus_quartz_crystal", size=1.5, shape="hexagon"),

    quest("fluix", 5, 2, "&5Fluix",
          subtitle="Alles ins Wasser werfen.",
          description=[
              "&6Fluixkristalle&r entstehen im Wasser. Wirf einen &6Geladenen Certusquarzkristall&r, ein &6Redstone&r und einen &6Netherquarz&r zusammen in Wasser, nach ein paar Sekunden liegen dort &ezwei Fluixkristalle&r.",
              "",
              "Derselbe Trick vermehrt auch Certus: Ein geladener Kristall und ein &6Certusquarzstaub&r im Wasser ergeben zwei normale Certusquarzkristalle.",
              "",
              "Fluix steckt in Kabeln, Kernen, dem Controller und dem Wachstumsbeschleuniger. Vier Kristalle ergeben einen &6Fluixblock&r, und die Gravurmaschine mahlt Kristalle zu &6Fluixstaub&r.",
              "",
              "&eTipp:&r Netherquarz brauchst du in Mengen. Ein Ausflug in den Nether mit einer Glück-Spitzhacke spart später viel Laufen.",
          ],
          tasks=[task_item("ae2:fluix_crystal", 16)],
          rewards=[reward_item("minecraft:quartz", 32)],
          deps=["charged"]),

    quest("growth", 7.5, 2.5, "&aCertus züchten",
          subtitle="Wie Amethyst, nur schneller.",
          description=[
              "An &6Certusquarzknospenblöcken&r wachsen Knospen, die zu Clustern werden. Ein fertiger Cluster gibt vier Kristalle (Glück hilft), eine halbe Knospe nur einen Staub.",
              "",
              "&eKnospenblöcke selbst machen:&r Wirf einen &6Certusquarzblock&r mit einem geladenen Kristall ins Wasser, dann wird daraus ein beschädigter Knospenblock. Jeder weitere geladene Kristall hebt ihn eine Stufe höher, bis zum unreinen Block. Jedes Mal, wenn eine Knospe wächst, kann der Block eine Stufe verlieren. Makellos ist nur, was du im Meteoriten findest.",
              "",
              "Ohne Hilfe wachsen Knospen sehr langsam. Der &6Wachstumsbeschleuniger&r neben dem Knospenblock macht es um ein Vielfaches schneller. Er nimmt FE oder AE oben und unten an, für den Anfang reicht auch eine Holzkurbel.",
          ],
          tasks=[task_item("ae2:growth_accelerator", 2)],
          rewards=[reward_item("ae2:charged_certus_quartz_crystal", 4), reward_xp(5)],
          deps=["fluix"], icon="ae2:flawed_budding_quartz"),

    # ---- Prozessoren -----------------------------------------------------------
    quest("inscriber", 5, 0, "&7Gravurmaschine",
          subtitle="Pressen, mahlen, drucken.",
          description=[
              "Die &6Gravurmaschine&r (Inscriber) ist die wichtigste Maschine von AE2. Sie druckt mit den Pressen Schaltkreise und mahlt Kristalle zu Staub: Certus zu Certusquarzstaub, Enderperlen zu Enderstaub, Himmelsstein zu Himmelsstaub.",
              "",
              "&eSo liest du das Fenster:&r Oben und unten liegen die Pressen oder die Zusatzteile, in der Mitte das Material. Im seitlichen Modus füllen Rohre von oben den oberen Platz, von unten den unteren und von der Seite die Mitte. Ergebnisse holst du seitlich heraus.",
              "",
              "Sie braucht Strom (FE oder AE). Ein Kabel von deinem Mekanism- oder Powah-Netz genügt. Mit einer &6Beschleunigungskarte&r arbeitet sie schneller.",
          ],
          tasks=[task_item("ae2:inscriber", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 16), reward_xp(5)],
          deps=["meteorite"]),

    quest("silicon", 7.5, 0, "&8Gedrucktes Silizium",
          subtitle="Das Bauteil, auf das der Server wartet.",
          description=[
              "Mahl Certusquarzkristalle in der Gravurmaschine zu &6Certusquarzstaub&r und schmilz den Staub im Ofen zu &6Silizium&r. Silizium unter dem &6Siliziumdruck&r ergibt &6Gedrucktes Silizium&r.",
              "",
              "Gedrucktes Silizium steckt in jedem Prozessor. Und es ist der Grund, warum Mekanism auf AE2 gewartet hat:",
              "",
              "&eRezept auf Kronwerke:&r Der &6Fortgeschrittene Steuerschaltkreis&r von Mekanism ist ein Einfacher Steuerschaltkreis, zwei Infundierte Legierungen und ein &6Gedrucktes Silizium&r an der Werkbank. Einen anderen Weg gibt es nicht.",
              "",
              "&eKronwerke:&r Das Ziel von Stufe 3, &e\"Der Ofen schläft nie\"&r, verlangt &e250 Fortgeschrittene Steuerschaltkreise&r am Obelisken. Jede Gravurmaschine, die Silizium druckt, bringt den Server näher an Stufe 4.",
          ],
          tasks=[task_item("ae2:printed_silicon", 16)],
          rewards=[reward_item("mekanism:alloy_infused", 8), reward_xp(5)],
          deps=["inscriber"], icon="ae2:printed_silicon"),

    quest("processors", 10, 1, "&b&lProzessoren",
          subtitle="Logik, Kalkulation, Konstruktion.",
          description=[
              "Ein Prozessor entsteht in zwei Schritten. Erst druckst du den Schaltkreis: &6Goldbarren&r unter dem Logikdruck, &6Certusquarzkristall&r unter dem Kalkulationsdruck, &6Diamant&r unter dem Konstruktionsdruck.",
              "",
              "Dann presst du ihn fertig: gedruckter Schaltkreis oben, &6Redstone&r in die Mitte, &6Gedrucktes Silizium&r unten.",
              "",
              "&eWofür:&r Logikprozessoren für Zellen, Konsolen und Kerne. Kalkulationsprozessoren für größere Zellen, Karten und den Zugangspunkt. Konstruktionsprozessoren für das ME-Laufwerk, den Controller und P2P-Tunnel.",
              "",
              "&eKronwerke:&r Der Meilenstein &6Stahlkern&r für Stufe 3 braucht zwei Konstruktionsprozessoren pro Stück. Acht Stahlkerne will der Obelisk sehen.",
          ],
          tasks=[task_item("ae2:logic_processor", 8), task_item("ae2:calculation_processor", 8),
                 task_item("ae2:engineering_processor", 8)],
          rewards=[reward_item("minecraft:diamond", 4), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["silicon"], icon="ae2:engineering_processor", size=2.0, shape="gear"),

    # ---- Das ME-Netz -----------------------------------------------------------
    quest("network", 12.5, 1, "&b&lDas erste ME-Netz",
          subtitle="Laufwerk, Strom, Konsole.",
          description=[
              "Für ein einfaches Netz brauchst du drei Dinge: ein &6ME-Laufwerk&r für die Zellen, einen &6Energieakzeptor&r für den Strom und eine &6ME-Konsole&r zum Hineinschauen.",
              "",
              "&eRezept auf Kronwerke:&r Das ME-Laufwerk braucht zwei &6Fortgeschrittene Steuerschaltkreise&r von Mekanism an Stelle der zwei Fluix-Glaskabel: Eisen in die Ecken, Konstruktionsprozessoren oben und unten, Schaltkreise links und rechts.",
              "",
              "&eAufbau:&r Laufwerk hinstellen, Energieakzeptor daneben, Kabel dran, Konsole auf das Kabel. Der Akzeptor wandelt &d2 FE in 1 AE&r um. Ein bis zehn Zellen ins Laufwerk, fertig.",
              "",
              "&eTipp:&r Stell gleich eine &6Energiezelle&r dazu. Ohne Puffer kann das Netz beim Einlagern großer Mengen kurz den Strom verlieren und neu starten.",
              "",
              "Ohne Controller ist das Netz ad hoc und verträgt höchstens &e8 Geräte&r, die einen Kanal brauchen. Mehr dazu beim Controller.",
          ],
          tasks=[task_item("ae2:drive", 1), task_item("ae2:energy_acceptor", 1), task_item("ae2:terminal", 1)],
          rewards=[reward_item("ae2:fluix_covered_cable", 16), reward_table("s3_common"), reward_xp(10)],
          deps=["processors"], icon="ae2:drive", size=1.75, shape="hexagon"),

    quest("cell_1k", 15, 2.2, "&7Die erste Speicherzelle",
          subtitle="Bytes und Typen.",
          description=[
              "Eine Zelle ist ein &6ME-Speichergehäuse&r mit einer &6Speicherkomponente&r darin. Die 1k-Komponente ist ein Logikprozessor mit Certus und Redstone drumherum.",
              "",
              "&eSo rechnet eine Zelle:&r Jede Zelle fasst höchstens &e63 Typen&r, also verschiedene Gegenstände. Jeder Typ kostet vorab ein paar Bytes, danach brauchen je acht Gegenstände ein Byte. Eine 1k-Zelle fasst rund 8 000 Stück, wenn nur eine Sorte drin ist, und etwa 4 000, wenn alle 63 Typen belegt sind.",
              "",
              "Lager also keine kaputten Werkzeuge und Rüstungen aus der Mobfarm ein. Jedes Teil mit eigener Haltbarkeit oder Verzauberung ist ein eigener Typ.",
              "",
              "Ist eine Zelle leer, kannst du sie mit Schleichen und Rechtsklick wieder in Gehäuse und Komponente zerlegen.",
          ],
          tasks=[task_item("ae2:item_storage_cell_1k", 2)],
          rewards=[reward_item("ae2:item_cell_housing", 2), reward_xp(5)],
          deps=["network"], icon="ae2:item_storage_cell_1k"),

    quest("cell_16k", 17.5, 2.2, "&b16k-Zellen",
          subtitle="Das Größte, was Stufe 3 hergibt.",
          description=[
              "Drei 1k-Komponenten, ein Kalkulationsprozessor, Quarzglas und Redstone ergeben eine &64k-Komponente&r. Drei 4k-Komponenten mit Glowstone statt Redstone ergeben eine &616k-Komponente&r.",
              "",
              "Eine volle Zelle lässt sich aufrüsten: Zelle und größere Komponente an die Werkbank, der Inhalt bleibt, die kleine Komponente bekommst du zurück.",
              "",
              "Größer ist nicht immer besser. Jede Zelle hat 63 Typen, egal wie groß. Für viele Sorten in kleinen Mengen sind mehrere 1k- oder 4k-Zellen günstiger, für wenige Sorten in großen Mengen nimm 16k.",
              "",
              "Flüssigkeitszellen funktionieren genauso, und mit &6Applied Mekanistics&r gibt es Zellen für Mekanism-Chemikalien.",
              "",
              "&cAusblick:&r 64k-Komponenten brauchen auf Kronwerke einen &6Himmelsbarren&r von Nature's Aura und öffnen in Stufe 4, 256k einen Draconiumbarren.",
          ],
          tasks=[task_item("ae2:item_storage_cell_4k", 1), task_item("ae2:item_storage_cell_16k", 1)],
          rewards=[reward_item("minecraft:glowstone_dust", 16), reward_table("s3_uncommon")],
          deps=["cell_1k"], icon="ae2:item_storage_cell_16k"),

    quest("controller", 15, 0, "&5&lME-Controller",
          subtitle="Netze brauchen ein Ritual.",
          description=[
              "Der &6ME-Controller&r macht aus einem kleinen Netz ein großes. Jede seiner Seiten gibt &e32 Kanäle&r aus.",
              "",
              "&eRezept auf Kronwerke:&r Himmelssteinblöcke in die Ecken und unten in die Mitte, ein &6Spirit Attuned Gem&r von Occultism oben in die Mitte, Fluixkristalle links, rechts und unten, ein Konstruktionsprozessor ins Zentrum. Das Juwel machst du aus Lapis im Geisterfeuer, wie im Kapitel Occultism beschrieben.",
              "",
              "&eRegeln:&r Pro Netz gibt es nur einen Controller, er darf aber aus mehreren Blöcken bestehen. Alle Blöcke müssen sich berühren, das Ganze passt in 7 x 7 x 7, und in höchstens einer Richtung dürfen zwei Blöcke nebeneinander liegen. Wird ein Block rot, stimmt etwas nicht.",
              "",
              "Ein Rechtsklick auf den Controller zeigt dir Strom und Geräte im Netz. Er braucht &d6 AE/t&r pro Block.",
          ],
          tasks=[task_item("ae2:controller", 1)],
          rewards=[reward_item("ae2:fluix_crystal", 16), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["network"], icon="ae2:controller", size=1.75, shape="gear"),

    quest("channels", 17.5, 0, "&eKanäle",
          subtitle="Acht pro Kabel, zweiunddreißig pro dichtem Kabel.",
          description=[
              "Fast jedes Gerät im Netz braucht einen &eKanal&r: Laufwerk, Konsole, Busse, Schnittstellen. Ein normales Kabel trägt &e8 Kanäle&r, ein dichtes Kabel &e32&r.",
              "",
              "Kanäle nehmen vom Controller aus den kürzesten Weg, erst über dichte Kabel, dann über normale. Bau dein Netz wie einen Baum: dichte Kabel als Äste, normale Kabel als Zweige, höchstens acht Geräte pro Zweig.",
              "",
              "&6Schlaue Kabel&r zeigen mit Leuchtstreifen, wie viele Kanäle durch sie laufen. &eRezept auf Kronwerke:&r vier verdeckte Kabel in die Ecken, Redstone oben und unten, Glowstone links und rechts, eine &6Elektronenröhre&r von Create in die Mitte. Das gibt vier Stück, für alle Farben gleich.",
              "",
              "&cAchtung:&r Kabelfarben haben nichts mit Kanälen zu tun. Sie sorgen nur dafür, dass sich zwei Kabel verschiedener Farbe nicht verbinden.",
          ],
          tasks=[task_item("ae2:fluix_smart_cable", 16)],
          rewards=[reward_item("create:electron_tube", 8), reward_xp(5)],
          deps=["controller"], icon="ae2:fluix_smart_cable"),

    quest("buses", 20, 2.8, "&6Busse",
          subtitle="Rein, raus, und Kisten mitbenutzen.",
          description=[
              "Busse sitzen auf Kabeln und schauen auf einen Block.",
              "",
              "Der &6ME-Importbus&r zieht Gegenstände aus dem Inventar vor sich ins Netz. Der &6ME-Exportbus&r schiebt eingestellte Gegenstände hinaus. Zusammen automatisieren sie einen Ofen: Export oben hinein, Import unten heraus.",
              "",
              "Der &6ME-Speicherbus&r macht eine Truhe, eine Schublade oder eine Tonne zum Teil des Netzes. Ein Speicherbus an einer großen Schubladenwand ist oft besser als eine Zelle, weil Schubladen keine Typen zählen.",
              "",
              "Mit &6Karten&r rüstest du Busse auf: Beschleunigungskarte für mehr Tempo, Kapazitätskarte für mehr Filterplätze, Fertigungskarte, damit ein Exportbus fehlende Teile bestellt.",
          ],
          tasks=[task_item("ae2:import_bus", 1), task_item("ae2:export_bus", 1), task_item("ae2:storage_bus", 1)],
          rewards=[reward_item("minecraft:piston", 8), reward_xp(5)],
          deps=["channels"], icon="ae2:storage_bus"),

    quest("p2p", 20, -0.8, "&dP2P-Tunnel",
          subtitle="Ein Kanal, viele Kanäle.",
          description=[
              "Ein &6ME P2P-Tunnel&r verbindet zwei Stellen wie ein Portal. Er wird aus Eisen, einem Konstruktionsprozessor und Fluix gebaut.",
              "",
              "&eUmstellen:&r Rechtsklick mit einem Kabel macht einen ME-Tunnel, mit Truhe oder Trichter einen Gegenstandstunnel, mit Eimer einen Flüssigkeitstunnel, mit einem geladenen Akku einen Energietunnel, mit Redstone-Bauteilen einen Redstone-Tunnel.",
              "",
              "&eVerbinden:&r Schleich-Rechtsklick mit einer &6Speicherkarte&r auf den Eingang, dann Rechtsklick auf jeden Ausgang. Ein Eingang kann viele Ausgänge haben.",
              "",
              "Der Klassiker: Ein ME-Tunnel braucht selbst nur einen Kanal, trägt aber alle 32 Kanäle des dichten Kabels, an dem er sitzt. So bringst du hunderte Kanäle durch ein einziges dünnes Kabel quer durch die Basis.",
              "",
              "&cAchtung:&r Energietunnel kosten etwa 2,5 Prozent des Stroms, der durch sie fließt.",
          ],
          tasks=[task_item("ae2:me_p2p_tunnel", 2), task_item("ae2:memory_card", 1)],
          rewards=[reward_item("ae2:engineering_processor", 2), reward_xp(5)],
          deps=["channels"], icon="ae2:me_p2p_tunnel"),

    quest("wireless", 20, 1.0, "&bDrahtlos",
          subtitle="Das Lager in der Tasche.",
          description=[
              "Der &6Drahtlose ME-Zugangspunkt&r sitzt am Netz und braucht einen Kanal. Mit &6Drahtlosverstärkern&r darin wird seine Reichweite größer, aber auch sein Stromverbrauch.",
              "",
              "Die &6Drahtlose Fertigungskonsole&r ist eine Fertigungskonsole mit Empfänger und einer Dichten Energiezelle. Zum Verbinden legst du sie in den Platz oben rechts im Zugangspunkt. Aufladen kannst du sie im Ladegerät.",
              "",
              "&eTipp:&r Mit &6AE2 Wireless Terminals&r kannst du mehrere drahtlose Konsolen zur &6Drahtlosen Universalkonsole&r zusammenlegen. Die &6Magnetkarte&r darin zieht Gegenstände in der Nähe direkt ins Netz.",
          ],
          tasks=[task_item("ae2:wireless_access_point", 1), task_item("ae2:wireless_crafting_terminal", 1)],
          rewards=[reward_item("ae2:dense_energy_cell", 1), reward_xp(10)],
          deps=["channels"], icon="ae2:wireless_crafting_terminal"),

    # ---- Autocrafting ----------------------------------------------------------
    quest("autocraft", 17.5, 7, "&a&lAutocrafting",
          subtitle="Schablonen, Provider, Assembler.",
          description=[
              "Autocrafting braucht drei Dinge: &6Schablonen&r, die ein Rezept speichern, einen &6ME Schablonen-Provider&r, der die Zutaten verschickt, und einen Ort, an dem gecraftet wird.",
              "",
              "In der &6ME-Schablonenkonsole&r schreibst du Rezepte auf &6Leere Schablonen&r. Werkbankrezepte gehen in einen &6Molekularassembler&r direkt neben dem Provider. Für Maschinen (Ofen, Gravurmaschine, Mekanism) schreibst du eine Verarbeitungsschablone, der Provider schickt die Zutaten in die Maschine, und das Ergebnis muss zurück ins Netz, zum Beispiel über den Provider selbst oder einen Importbus.",
              "",
              "&eRezept auf Kronwerke:&r Der Molekularassembler braucht zwei &6Präzisionsgetriebe&r an Stelle von Annihilations- und Formationskern. Der Schablonen-Provider bekommt ein Präzisionsgetriebe in die Mitte. Autocrafting gibt es hier nur mit Create.",
          ],
          tasks=[task_item("ae2:pattern_encoding_terminal", 1), task_item("ae2:blank_pattern", 8),
                 task_item("ae2:pattern_provider", 1), task_item("ae2:molecular_assembler", 1)],
          rewards=[reward_item("create:precision_mechanism", 2), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["cell_16k"], icon="ae2:molecular_assembler", size=1.75, shape="gear"),

    quest("cpu", 20, 7, "&7Fertigungs-CPU",
          subtitle="Wer plant den Auftrag?",
          description=[
              "Jeder Auftrag braucht eine &eFertigungs-CPU&r. Das ist ein Multiblock aus &6Fertigungseinheiten&r, der als volles Rechteck ohne Lücken gebaut wird.",
              "",
              "Mindestens ein &6Fertigungsspeicher&r muss drin sein, er hält die Zwischenprodukte. Größere Aufträge brauchen mehr Speicher. &6Fertigungs-Prozessoreinheiten&r machen die CPU schneller, ein &6Fertigungsmonitor&r zeigt, woran sie gerade arbeitet.",
              "",
              "Eine CPU erledigt einen Auftrag zur Zeit. Willst du zwei Dinge gleichzeitig bestellen, bau zwei CPUs.",
              "",
              "&eBestellen:&r In der Konsole auf etwas klicken, das eine Schablone hat. Hast du es schon auf Lager, nimm die Mausrad-Taste.",
          ],
          tasks=[task_item("ae2:1k_crafting_storage", 1), task_item("ae2:crafting_accelerator", 1)],
          rewards=[reward_item("ae2:crafting_unit", 2), reward_xp(5)],
          deps=["autocraft"], icon="ae2:1k_crafting_storage"),

    quest("factory", 22.75, 8, "&6&lDie Schaltkreisfabrik",
          subtitle="Der Ofen schläft nie, die Gravurmaschine auch nicht.",
          description=[
              "Jetzt fügt sich alles zusammen. Bau eine Straße, die &6Fortgeschrittene Steuerschaltkreise&r ohne deine Hände macht.",
              "",
              "&eSo geht es:&r Eine Gravurmaschine mit Siliziumdruck bekommt Silizium über eine Verarbeitungsschablone. Eine Infusionsanlage macht Infundierte Legierung, eine zweite Einfache Steuerschaltkreise aus Elektronenröhren. Eine Werkbankschablone im Molekularassembler setzt alles zusammen. Mit einem Exportbus und einer Fertigungskarte hältst du einen Vorrat, oder du bestellst von Hand.",
              "",
              "Wer Silizium in großen Mengen braucht, schaut sich den &6Circuit Slicer&r von Extended AE an. Er schneidet einen ganzen Siliziumblock in neun gedruckte Siliziumplatten.",
              "",
              "&eKronwerke:&r &e\"Der Ofen schläft nie\"&r will &e250 Fortgeschrittene Steuerschaltkreise&r, &e4 000 Stahlbarren&r und &e8 Stahlkerne&r auf der Technikseite. In jedem Stahlkern stecken ein Fortgeschrittener Schaltkreis und zwei Konstruktionsprozessoren. Stell eine Kiste neben den Obelisken und häng deine Fabrik daran.",
          ],
          tasks=[task_item("mekanism:advanced_control_circuit", 64), task_item("ae2:engineering_processor", 16)],
          rewards=[reward_table("s3_rare"), reward_item("ae2:cell_component_16k", 1), reward_xp(25)],
          deps=["cpu"], icon="mekanism:advanced_control_circuit", size=2.5, shape="gear"),

    # ---- Extended AE ---------------------------------------------------------
    quest("entro", 5, 6.5, "&3Entro Crystal",
          subtitle="Fluix mit Enderstaub.",
          description=[
              "&6Extended AE&r baut auf einem neuen Kristall auf: &6Entro&r. Am Anfang steht der &6Entro Seed&r, gemischt aus Sand, drei Enderstaub, zwei Redstone, zwei Glowstone und einem Himmelsstaub. Enderstaub und Himmelsstaub mahlt die Gravurmaschine aus Enderperlen und Himmelsstein.",
              "",
              "Rechtsklick mit dem Samen auf einen &6Fluixblock&r macht daraus einen &6Budding Fully Entroized Fluix&r. Darauf wachsen Entro-Knospen wie bei Certus, ein Wachstumsbeschleuniger hilft auch hier. Anders als ein makelloser Certus-Knospenblock verbraucht sich dieser Block immer und wird am Ende zum Certusquarzblock, im Schnitt nach etwa zehn Kristallen.",
              "",
              "Abgebaute Knospenblöcke geben immer einen &6Entro Dust&r. Entro Dust und ein &6Fluixkristall&r im Wasser ergeben einen weiteren Entro Crystal. Entro Dust mit einem Goldbarren und Lapis im Wasser ergibt einen &6Entro Infused Ingot&r.",
          ],
          tasks=[task_item("extendedae:entro_crystal", 16)],
          rewards=[reward_item("minecraft:ender_pearl", 8), reward_xp(5)],
          deps=["fluix"], icon="extendedae:entro_crystal"),

    quest("crystal_assembler", 5, 8.7, "&3Crystal Assembler",
          subtitle="Rezepte, die nicht auf die Werkbank passen.",
          description=[
              "Der &6Extended Machine Frame&r (vier Entro Infused Ingots, Kupfer, Eisen, Quarzglas) ist die Grundlage für alle Maschinen von Extended AE. Die erste davon ist der &6Crystal Assembler&r: Rahmen, Fertigungskonsole, zwei Logikprozessoren, zwei Glaskabel und ein Himmelssteintank.",
              "",
              "Er ersetzt das Werfen ins Wasser: Aus je vier geladenen Certus, Redstone und Netherquarz mit etwas Wasser aus einem Rohr macht er acht Fluix. Außerdem baut er die anderen Maschinen der Mod. &cAchtung:&r Die Seite mit dem Bildschirm verbindet sich nicht mit dem Netz.",
              "",
              "&eWas in Stufe 3 offen ist:&r der &6Crystal Fixer&r, der Certus-Knospenblöcke repariert und mit geladenem Certus sogar zu makellosen Blöcken aufwerten kann, der &6Circuit Slicer&r, &6ME Tag Storage Bus&r und &6ME Mod Storage Bus&r (filtern nach Tag oder Mod), der &6ME Threshold Level Emitter&r, der &6Pattern Modifier&r und die &6ME Void Cell&r.",
              "",
              "&cAusblick:&r Die Ex-Maschinen (erweiterter Provider, erweitertes Laufwerk, Assembler-Matrix) und die drahtlosen Verbinder öffnen in Stufe 4.",
          ],
          tasks=[task_item("extendedae:machine_frame", 1), task_item("extendedae:crystal_assembler", 1)],
          rewards=[reward_item("ae2:fluix_block", 4), reward_table("s3_common"), reward_xp(10)],
          deps=["entro"], icon="extendedae:crystal_assembler"),

    quest("circuit_cutter", 7.5, 8.7, "&3Circuit Slicer",
          subtitle="Neun Platten aus einem Block.",
          description=[
              "Der &6Circuit Slicer&r entsteht im Crystal Assembler aus einem Maschinenrahmen, acht Konstruktionsprozessoren, allen vier AE2-Pressen, einer &6Inscriber Concurrent Press&r und einer Steinsäge. Die Concurrent Press macht ebenfalls der Crystal Assembler, aus drei Enderaugen, vier Entro Crystals und einem Siliziumdruck.",
              "",
              "Er schneidet ganze Blöcke in gedruckte Schaltkreise: ein &6Siliziumblock&r gibt neun gedruckte Silizium, ein Goldblock neun Logikschaltkreise, ein Diamantblock neun Konstruktionsschaltkreise, ein Certusquarzblock vier Kalkulationsschaltkreise.",
              "",
              "Für das Schaltkreisziel des Servers ist das die schnellste Siliziumquelle, die Stufe 3 hat.",
          ],
          tasks=[task_item("extendedae:circuit_cutter", 1)],
          rewards=[reward_item("minecraft:gold_block", 2), reward_xp(10)],
          deps=["crystal_assembler"], optional=True),

    # ---- Applied Flux ----------------------------------------------------------
    quest("flux_crystal", 10, 6.5, "&cRedstone-Kristalle",
          subtitle="Strom braucht einen eigenen Prozessor.",
          description=[
              "&6Applied Flux&r speichert FE in ME-Zellen. Dafür braucht es zwei neue Materialien.",
              "",
              "&eRedstone-Kristall:&r Ein &6Redstone-Block&r, ein Fluixkristall und ein Glowstone-Staub zusammen ins Wasser ergeben zwei Redstone-Kristalle. Im &6Ladegerät&r werden sie zu &6Geladenen Redstone-Kristallen&r.",
              "",
              "&eEnergieprozessor:&r Ein Eisenblock im Ladegerät wird zum &6Energiedruck&r. Damit druckst du geladene Redstone-Kristalle zu Energieschaltkreisen und presst sie wie die anderen Prozessoren mit Redstone und Gedrucktem Silizium fertig.",
          ],
          tasks=[task_item("appflux:charged_redstone", 8), task_item("appflux:energy_processor", 4)],
          rewards=[reward_item("minecraft:redstone_block", 8), reward_xp(5)],
          deps=["processors"], icon="appflux:energy_processor"),

    quest("flux_cell", 10, 8.7, "&c&lStrom in Zellen",
          subtitle="Ein Akku, der ins Laufwerk passt.",
          description=[
              "Die &6ME FE-Speicherzelle&r sitzt im Laufwerk wie jede andere Zelle. Das Gehäuse braucht &6gehärtetes Isolierharz&r: Wassereimer, zwei Kakteen, Knochenmehl, Silizium, Schleimball und Glowstone ergeben Harz, das du im Ofen härtest. Die Komponente ist ein Logikprozessor mit Redstone-Kristallen und Certusquarzstaub.",
              "",
              "Pro Byte passen &d1 048 576 FE&r in eine Zelle, schon die 1k-Zelle schluckt also rund eine Milliarde FE. In der Konsole erscheint der Strom als grüne Flüssigkeit.",
              "",
              "Der &6Flux Accessor&r ist die Steckdose: Generatoren schieben über Kabel Strom hinein, und er gibt Strom an Maschinen daneben ab. Die &6Induktionskarte&r macht dasselbe aus einer ME-Schnittstelle oder einem Schablonen-Provider.",
              "",
              "&eKronwerke:&r Der gespeicherte Strom versorgt nicht das ME-Netz selbst, dafür bleibt der Energieakzeptor zuständig. Importbusse nehmen keinen Strom an. Zellen bis 16k sind in Stufe 3 offen, größere ab Stufe 4.",
          ],
          tasks=[task_item("appflux:fe_1k_cell", 1), task_item("appflux:flux_accessor", 1)],
          rewards=[reward_item("ae2:energy_cell", 1), reward_table("s3_common"), reward_xp(10)],
          deps=["flux_crystal"], icon="appflux:fe_1k_cell"),
]

images = [
    banner("ae2/title", "Applied Energistics 2", 10, -5, height=1.75, kind="title", colour="water"),
    banner("ae2/certus", "Meteoriten und Certus", 3.3, -2.7, height=0.9, colour="water"),
    banner("ae2/processors", "Prozessoren", 9.6, -2.7, height=0.9, colour="brass"),
    banner("ae2/network", "Das ME-Netz", 17.5, -2.7, height=0.9, colour="water"),
    banner("ae2/autocrafting", "Autocrafting", 21.2, 5, height=0.9, colour="brass"),
    banner("ae2/extended", "Extended AE", 2.2, 4.6, height=0.9, colour="water"),
    banner("ae2/flux", "Applied Flux", 12.6, 4.6, height=0.9, colour="brass"),
]

chapter(C, "Applied Energistics 2", "ae2:controller", "tech", quests, shape="square", order=17, stage=3,
        subtitle=["Stufe 3: Meteoriten, Prozessoren, das ME-Netz bis 16k und Autocrafting."], images=images)
