"""Apotheosis in stage 1: affix loot and the rarities (common, uncommon and a little rare now,
epic in stage 3 and mythic in stage 4 with the world tiers Summit and Pinnacle), the world tiers
Haven and Frontier, gems, gem dust, the salvaging and gem cutting tables, gem-fused slate and the
sigils, the simple reforging table, Apothic Enchanting (eterna, quanta, arcana, seashelves,
infusion, the library), Apothic Spawners (silk touch, spawner chains and runes; with Apotheosis
installed the item modifiers of Apothic Spawners are disabled) and the Apothic Attributes screen.
Numbers come from the data in the jars (rarities, purity_weights, tier_augments, recipes)."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_advancement, reward_item,
                  reward_table, reward_xp, banner, img)

C = "apotheosis"


quests = [
    # ---- Affixe und Seltenheiten -------------------------------------------
    quest("welcome", 0, 1, "&6&lFinde Beute mit Affix",
          subtitle="Kein Schwert gleicht dem anderen.",
          description=[
              "Töte Monster oder öffne Kisten in Bauwerken, bis du ein Werkzeug, eine Waffe oder ein Rüstungsteil mit &6Affixen&r in der Hand hältst. Etwa jedes dritte Ausrüstungsstück aus einer Kiste trägt welche.",
              "",
              "Affixe sind Boni wie bei Verzauberungen: mehr Schaden, Lebensraub, schnelleres Abbauen, mehr Rüstung, Glück. Was ein Teil kann, steht im Tooltip. Apotheosis hat keine deutschen Namen, darum stehen die Begriffe hier auf Englisch.",
              "",
              "&cAchtung:&r Bis du einmal eine Weltstufe aktiviert hast, heißen die Teile &9Unidentified&r und zeigen nichts an. Drück &eStrg+T&r und aktiviere &eHaven&r, dann liest du alles.",
              "",
              "Ein &6Buch&r und ein &6Goldbarren&r ergeben das &6Chronicle of Shadows&r, das Handbuch zu allem in diesem Kapitel.",
          ],
          tasks=[task_advancement("apotheosis:progression/haven", "Ein Affix-Item aufheben")],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          icon="minecraft:iron_sword", size=2.0, shape="hexagon"),

    quest("rarities", 2.5, 0, "&7Lern die Seltenheiten",
          subtitle="Die Farbe des Namens sagt, was drinsteckt.",
          description=[
              "&7Common&r: ein Attributbonus, mit 25 Prozent Chance ein zweiter.",
              "&aUncommon&r: zwei Attributboni, zur Hälfte ein Effekt dazu, bis zu ein Sockel.",
              "&9Rare&r: zwei Attributboni, ein Effekt (35 Prozent für einen zweiten), bis zu zwei Sockel, und es nutzt sich 10 bis 25 Prozent langsamer ab.",
              "",
              "&5Epic&r hat drei Attribute, einen Effekt und immer eine &6Fähigkeit&r mit Abklingzeit. &6Mythic&r hat vier Attribute, zwei Effekte und eine Fähigkeit, selten sogar Unzerstörbarkeit.",
              "",
              "&eKronwerke:&r Common, Uncommon und ein wenig Rare gibt es in Stufe 1. &5Epic&r kommt in Stufe 3, &6Mythic&r in Stufe 4, mit den Weltstufen Summit und Pinnacle.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["welcome"], icon="minecraft:name_tag"),

    quest("tiers", 2.5, 2, "&eAktiviere die Weltstufe Haven",
          subtitle="Strg+T öffnet das Menü.",
          description=[
              "Drück &eStrg+T&r (Taste &eOpen World Tier Select&r in den Steuerungseinstellungen), wähl &6Haven&r und klick &eActivate&r. Erst dann zeigen deine Affix-Items, was sie können.",
              "",
              "Eine &6Weltstufe&r gilt nur für dich. Sie legt fest, wie stark Monster in deiner Nähe sind und wie gut die Beute ausfällt. In Haven fällt &7Common&r zu 60 Prozent, &aUncommon&r zu 36 und &9Rare&r zu 4 Prozent.",
              "",
              "Fünf Stufen gibt es: Haven, Frontier, Ascent, Summit und Pinnacle. Jede muss erst freigeschaltet und dann hier aktiviert werden. Der Knopf &eDetailed Info&r zeigt für jede Stufe die Chancen und die Boni.",
          ],
          tasks=[task_checkmark("Haven ist aktiv")],
          rewards=[reward_xp(3)],
          deps=["welcome"], icon="minecraft:compass"),

    quest("frontier", 5, 1, "&a&lRüste dich voll aus: Frontier",
          subtitle="Vier Rüstungsteile und eine Waffe mit Affix.",
          description=[
              "Trag ein Affix-Item an &6Kopf, Brust, Beinen und Füßen&r und halte eine Affix-Waffe in der Hand. Die Seltenheit ist egal, Common reicht. Das schaltet &6Frontier&r frei, aktivieren musst du es dann mit &eStrg+T&r.",
              "",
              "In Frontier fällt &aUncommon&r zu 60 Prozent, &9Rare&r zu 10, Common nur noch zu 29. Du bekommst &e20 Prozent mehr Glück&r und &e35 Prozent mehr Erfahrung&r, Monster bekommen 4 Rüstungspunkte dazu, und &cApothic Invader&r tauchen auf.",
              "",
              "&eTipp:&r Frontier hebt auch das Limit deines Zaubertischs von Stufe 30 auf &e45&r. Der Abschnitt Apothic Enchanting baut darauf auf.",
          ],
          tasks=[task_advancement("apotheosis:progression/frontier", "Frontier freischalten")],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["rarities", "tiers"], icon="minecraft:iron_chestplate", size=1.5, shape="diamond"),

    quest("invaders", 7.5, 1, "&cInvader und Eliten",
          subtitle="Ein Lichtstrahl am Himmel heißt: Beute.",
          description=[
              "Ab Frontier ersetzt ein &cApothic Invader&r hin und wieder ein normales Monster. Ein lautes Geräusch, eine Meldung im Chat und ein Lichtstrahl zeigen dir, wo er steht. Sein Name und die Farbe seines Umrisses verraten die Seltenheit.",
              "",
              "Jeder Invader trägt genau ein Affix-Item seiner Seltenheit, mit stärkeren Affixen als üblich, und lässt es beim Tod &egarantiert&r fallen. Es trägt dann seinen Namen vorneweg. Edelsteine lässt er häufiger fallen als andere Monster.",
              "",
              "&6Eliten&r sind benannte, verstärkte Monster ohne Lichtstrahl. Sie tauchen überall auf und können ebenfalls Affix-Items fallen lassen. Tief unter der Erde stehen &cKäfige&r mit einem gefangenen Invader und Kisten drumherum, der Käfig öffnet sich, wenn du näher kommst.",
          ],
          tasks=[task_checkmark("Einen Invader besiegt")],
          rewards=[reward_table("s1_common"), reward_xp(10)],
          deps=["frontier"], icon="minecraft:beacon", optional=True),

    # ---- Edelsteine -------------------------------------------------------------
    quest("gem", 0, 7, "&d&lFinde einen Edelstein",
          subtitle="Vier Prozent bei jedem Monster.",
          description=[
              "Jedes Monster, das du selbst tötest, lässt mit &e4 Prozent&r einen &dEdelstein&r fallen (Tötungen durch Maschinen nur 0,5 Prozent). Edelsteine liegen auch in Kisten, und Invader haben sie öfter dabei.",
              "",
              "Einen Edelstein setzt du am &6Schmiedetisch&r ein: Item links, Edelstein rechts. Oder du nimmst ihn im Inventar auf und klickst ihn mit Rechtsklick auf das Item. Der Tooltip sagt unter &eFits In&r, wo er passt, und was er in jedem Itemtyp bewirkt.",
              "",
              "&eReinheit:&r &7Cracked&r, Chipped, Flawed, Normal, Flawless, &6Perfect&r. In Haven fallen 55 Prozent Cracked, 41 Chipped und 4 Flawed. Höhere Reinheiten kommen mit den höheren Weltstufen, oder du schleifst sie selbst.",
          ],
          tasks=[task_item("apotheosis:gem", 1)],
          rewards=[reward_item("apotheosis:gem_dust", 2), reward_xp(5)],
          deps=["welcome"], icon="apotheosis:gem", size=1.5),

    quest("gem_dust", 2.5, 7, "&7Zerbrich einen Edelstein",
          subtitle="Ein Amboss, ein Edelstein, Staub.",
          description=[
              "Wirf einen Edelstein, den du nicht brauchst, auf den Boden und lass einen &6Amboss&r darauf fallen. Übrig bleibt &6Gem Dust&r.",
              "",
              "Gem Dust steckt in jedem Tisch und jedem Siegel dieses Kapitels, und das Schleifen von Edelsteinen frisst ihn stapelweise. Ein Cracked-Stein gibt ein bis zwei Staub, ein Flawed-Stein zwei bis vier.",
              "",
              "Der Amboss ist nur für den Anfang. Sobald der Salvaging Table steht, zerlegst du Edelsteine dort.",
          ],
          tasks=[task_item("apotheosis:gem_dust", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(3)],
          deps=["gem"]),

    quest("salvaging", 5, 7, "&6&lBau einen Salvaging Table",
          subtitle="Aus Beute werden Materialien.",
          description=[
              "&eRezept auf Kronwerke:&r oben drei &6Kupferbleche&r, in der Mitte &6Eisenspitzhacke&r, &6Schmiedetisch&r und &6Eisenaxt&r, unten zwei &6Gem Dust&r mit einem &6Lavaeimer&r dazwischen.",
              "",
              "Leg Affix-Items hinein, die du nicht trägst. Jedes gibt ein bis vier &6Seltenheitsmaterialien&r seiner Stufe. Edelsteine werden zu Gem Dust, und normale Ausrüstung gibt einen Teil ihres Metalls zurück: eine Eisenrüstung ein bis drei Eisenbarren, eine Diamantrüstung ein bis drei Diamanten.",
              "",
              img("apotheosis:textures/blocks/salvaging_table_front.png", 32, 32),
          ],
          tasks=[task_item("apotheosis:salvaging_table", 1)],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["gem_dust"], icon="apotheosis:salvaging_table", size=1.5, shape="hexagon"),

    quest("materials", 7.5, 6, "&7Zerlege Common und Uncommon",
          subtitle="Scrap Metal und Timeworn Fabric.",
          description=[
              "Zerleg acht &7Common&r-Items zu &6Mysterious Scrap Metal&r und ein paar &aUncommon&r-Items zu &6Timeworn Fabric&r.",
              "",
              "&9Rare&r gibt &6Luminous Crystal Shard&r. &5Epic&r gibt &6Arcane Sands&r (Stufe 3), &6Mythic&r gibt &6Godforged Pearl&r (Stufe 4).",
              "",
              "Die Materialien brauchst du zum Schleifen von Edelsteinen und zum Umschmieden. Heb alles auf, was du findest, auch das Common-Zeug: Scrap Metal geht beim Schleifen in Stapeln weg.",
          ],
          tasks=[task_item("apotheosis:mysterious_scrap_metal", 8), task_item("apotheosis:timeworn_fabric", 3)],
          rewards=[reward_item("apotheosis:gem_dust", 4), reward_xp(5)],
          deps=["salvaging"], icon="apotheosis:mysterious_scrap_metal"),

    quest("gem_cutting", 7.5, 8, "&dBau einen Gem Cutting Table",
          subtitle="Zwei Steine werden einer, aber ein besserer.",
          description=[
              "&eRezept:&r eine &6Schere&r zwischen zwei &6Glatten Steinen&r, darunter Bretter mit einem &6Gem Dust&r in der Mitte, unten links und rechts noch je ein Brett.",
              "",
              "Zum Schleifen legst du den Edelstein in die Mitte, einen &ezweiten Edelstein gleicher Reinheit&r dazu, links Gem Dust und rechts Material. &7Cracked&r zu Chipped kostet 1 Gem Dust und 3 Scrap Metal oder 1 Timeworn Fabric. Chipped zu Flawed kostet 3 Gem Dust und 9 Scrap Metal, 3 Fabric oder 1 Crystal Shard.",
              "",
              "Flawed zu Normal kostet schon 5 Gem Dust und 27 Scrap Metal, 9 Fabric, 3 Shards oder 1 Arcane Sands. Darüber brauchst du Material aus Stufe 3 und 4. JEI zeigt jeden Schritt.",
          ],
          tasks=[task_item("apotheosis:gem_cutting_table", 1)],
          rewards=[reward_item("apotheosis:gem_dust", 4), reward_table("s1_common")],
          deps=["materials"], icon="apotheosis:gem_cutting_table"),

    # ---- Siegel und Umschmieden -----------------------------------------------
    quest("slate", 12.5, 1, "&8Mach Gem-Fused Slate",
          subtitle="Der Rohstoff aller Siegel.",
          description=[
              "Acht &6Tiefenschiefer&r um einen &6Gem Dust&r ergeben acht &6Gem-Fused Slate&r.",
              "",
              "Jedes Siegel in diesem Abschnitt und jede Spawner-Rune im Abschnitt Apothic Spawners wird daraus gebaut. Tiefenschiefer hast du unterhalb von Y 0 mehr als genug, der Gem Dust ist der Engpass.",
          ],
          tasks=[task_item("apotheosis:gem_fused_slate", 8)],
          rewards=[reward_item("apotheosis:gem_dust", 2), reward_xp(3)],
          deps=["salvaging"], icon="apotheosis:gem_fused_slate"),

    quest("socketing", 15, 0, "&dSigil of Socketing",
          subtitle="Ein Sockel mehr, bis zu zwei.",
          description=[
              "Oben &6Gem Dust&r, &6Schwarzpulver&r, Gem Dust, in der Mitte drei &6Gem-Fused Slate&r, unten Gem Dust, &6Amethystscherbe&r, Gem Dust. Das ergibt drei &6Sigils of Socketing&r.",
              "",
              "Ein Siegel mit einem Item am &6Schmiedetisch&r gibt dem Item einen Sockel dazu, höchstens zwei pro Item auf diesem Weg. So bekommt auch ein Teil ohne Sockel Platz für einen Edelstein.",
              "",
              "&eSigil of Unnaming:&r drei Slate, drei &6Feuerstein&r, drei Slate ergeben sechs. Am Schmiedetisch nimmt es dem Item den Affix-Namen und den Namen eines Invaders wieder weg.",
          ],
          tasks=[task_item("apotheosis:sigil_of_socketing", 3)],
          rewards=[reward_item("minecraft:amethyst_shard", 8), reward_xp(5)],
          deps=["slate"], icon="apotheosis:sigil_of_socketing"),

    quest("rebirth", 15, 2, "&dSigil of Rebirth",
          subtitle="Der Brennstoff zum Umschmieden.",
          description=[
              "Drei &6Gem-Fused Slate&r oben und unten, drei &6Gem Dust&r in der Mitte ergeben sechs &6Sigils of Rebirth&r.",
              "",
              "Der Reforging Table verbraucht sie: &aUncommon&r kostet 1 Siegel je Umschmieden, &9Rare&r 2. Common geht ohne.",
          ],
          tasks=[task_item("apotheosis:sigil_of_rebirth", 6)],
          rewards=[reward_item("apotheosis:gem_dust", 3), reward_xp(5)],
          deps=["slate"], icon="apotheosis:sigil_of_rebirth"),

    quest("reforge_table", 17.5, 1, "&6&lBau einen Simple Reforging Table",
          subtitle="Neu würfeln, bis es passt.",
          description=[
              "&eRezept auf Kronwerke:&r ein &6Quelljuwel&r von Ars Nouveau oben, in der Mitte ein &6Zaubertisch&r zwischen zwei &6Gem Dust&r, unten drei &6Glatte Steine&r.",
              "",
              "&eSo geht es:&r Item in die Mitte, oben links Seltenheitsmaterial der Stufe, die das Item bekommen soll, unten rechts Sigils of Rebirth. Wie am Zaubertisch siehst du drei Angebote, keines ist besser als das andere. Auch Items ohne Affixe lassen sich umschmieden, so oft du willst.",
              "",
              "&eKosten:&r &7Common&r 2 Level und 1 Scrap Metal. &aUncommon&r 5 Level, 2 Fabric, 1 Siegel. &9Rare&r 15 Level, 2 Crystal Shards, 2 Siegel. Das zweite und dritte Angebot verlangen das Doppelte und Dreifache an Levelanforderung und Material, ziehen aber nur ein, zwei oder drei Level ab.",
              "",
              "Der einfache Tisch schafft Items bis &9Rare&r. Für Epic und Mythic brauchst du den großen Reforging Table, siehe nächste Quest.",
          ],
          tasks=[task_item("apotheosis:simple_reforging_table", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["rebirth"], icon="apotheosis:simple_reforging_table", size=1.5, shape="hexagon"),

    quest("outlook", 20, 1, "&5Was später kommt",
          subtitle="Withdrawal, Reforging Table, Augmenting.",
          description=[
              "&eStufe 2:&r Das &6Sigil of Withdrawal&r (Slate, eine &6Lohenrute&r, zwei Enderperlen, ein Lavaeimer, Gem Dust, ergibt vier) holt am Schmiedetisch alle Edelsteine wieder heraus, Item und Steine bleiben heil. Die &6Gem Case&r (Glas, Basalt, Gem Cutting Table, &6Endertruhe&r) lagert 32 000 Edelsteine je Sorte und schleift sie direkt im Inventar.",
              "",
              "&eStufe 3:&r Der große &6Reforging Table&r ist der einfache Tisch mit einem &6Netheritbarren&r, zwei &6Arcane Sands&r und drei Netherziegeln. Nur er schmiedet &5Epic&r (30 Level, 2 Arcane Sands, 4 Siegel) und &6Mythic&r (50 Level, 3 Godforged Pearls, 5 Siegel).",
              "",
              "&eStufe 4:&r Der &6Augmenting Table&r (Netherstern, zwei &6Godforged Pearls&r, Zaubertisch, polierter Schwarzstein) verbessert einen einzelnen Affix um 25 Prozent für 2 &6Sigils of Enhancement&r und 225 Level, oder würfelt ihn für 1 Siegel und 175 Level neu, ohne die anderen anzurühren.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["reforge_table"], icon="apotheosis:sigil_of_withdrawal", optional=True),

    # ---- Apothic Enchanting ------------------------------------------------------
    quest("ench_table", 0, 13, "&b&lSchau in den Zaubertisch",
          subtitle="Vier Werte statt einem.",
          description=[
              "Stell einen &6Zaubertisch&r auf und fahr mit der Maus über die Balken. Apothic Enchanting rechnet mit vier Werten: &bEterna&r ist das Levelmaximum (ein Bücherregal gibt 2, fünfzehn ergeben Stufe 30). &dQuanta&r ist der Zufall nach oben und unten, &5Arcana&r macht seltene Verzauberungen häufiger und bringt ab 25 Prozent immer zwei, ab 75 immer drei Verzauberungen.",
              "",
              "&eClues&r sind die Zeilen in der Vorschau, eine hat jeder Tisch. Leg ein Item hinein und klick das &eFragezeichen&r oben rechts: Dort siehst du für jeden Slot, welche Verzauberungen mit welcher Chance drin sind.",
              "",
              "&cWeltstufe:&r Dein Eterna ist durch die Weltstufe gedeckelt. Haven 30, Frontier 45, Ascent 60, Summit 75 (Wither, Stufe 2), Pinnacle 100 (Drache, Stufe 4). Der Tisch sagt dir im Tooltip, wenn das Limit greift.",
              "",
              "Levelkosten sind bei Apotheosis fair: Du zahlst immer so viel Erfahrung, als hättest du genau die verlangten Level, egal wie viele du gerade hast.",
          ],
          tasks=[task_item("minecraft:enchanting_table", 1)],
          rewards=[reward_item("minecraft:lapis_lazuli", 16), reward_xp(5)],
          deps=["welcome"], icon="minecraft:enchanting_table", size=1.5),

    quest("shelves", 2.5, 12, "&6Stell fünfzehn Regale auf",
          subtitle="Jedes Bücherregal zählt, aus welchem Mod auch immer.",
          description=[
              "Stell &e15 Bücherregale&r um den Zaubertisch, ein Block Abstand, wie immer. Jedes gibt &b2 Eterna&r, mehr als 30 bringen Bücherregale dieser Art aber nicht.",
              "",
              "Es muss kein Eichenregal sein: Alles, was Minecraft als Bücherregal zählt, gilt auch hier. Das &6Skyroot-Bücherregal&r aus dem Aether, das &6Wisewood-Regal&r von Iron's Spells, die Regale aus allen Hölzern von Productive Trees und die Varianten von Chipped bringen ebenfalls 2 Eterna.",
              "",
              "&eQuanta:&r Jeder &6Schädel&r (Skelett, Zombie, Creeper) in einem Regalplatz gibt 5 Prozent Quanta dazu. Der Tisch startet bei 15 Prozent. Viel Quanta heißt: mal deutlich besser, mal deutlich schlechter als dein Level.",
          ],
          tasks=[task_item("minecraft:bookshelf", 15)],
          rewards=[reward_item("minecraft:book", 8), reward_xp(5)],
          deps=["ench_table"], icon="minecraft:bookshelf"),

    quest("scrap_tome", 2.5, 14, "&7Tome of Scrapping",
          subtitle="Verzauberungen retten, bevor das Werkzeug bricht.",
          description=[
              "Acht &6Bücher&r um einen &6Amboss&r ergeben acht &6Tomes of Scrapping&r.",
              "",
              "Leg ein Tome mit einem verzauberten Item in den Amboss: Das Item wird zerstört, du bekommst ein Buch mit der &eHälfte&r seiner Verzauberungen (aufgerundet, zufällig gewählt). Gut für Beute mit Verzauberungen, die du nicht tragen willst.",
              "",
              "Per Infusion wird daraus später das &6Tome of Superior Scrapping&r (alle Verzauberungen, Eterna 45) und das &6Tome of Extraction&r (alle Verzauberungen, Item bleibt heil, Eterna 60).",
          ],
          tasks=[task_item("apothic_enchanting:scrap_tome", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 8)],
          deps=["ench_table"], icon="apothic_enchanting:scrap_tome", optional=True),

    quest("seashelf", 5, 12, "&3Bau fünf Seashelves",
          subtitle="Das Meer hebt den Tisch auf 45.",
          description=[
              "&eRezept:&r drei &6Prismarinziegel&r oben und unten, in der Mitte eine &6Wasserflasche&r, ein &6Bücherregal&r und ein &6Kugelfisch&r.",
              "",
              "Ein &6Seashelf&r gibt &b3 Eterna&r (bis maximal 45) und &53 Prozent Arcana&r. Fünf davon zu deinen fünfzehn Bücherregalen ergeben Eterna 45 und Arcana 15. Prismarin holst du aus einem Ozeanmonument, Kugelfische angelst du im Ozean.",
              "",
              "Die Alternative aus dem Nether, das &6Hellshelf&r (Netherziegel, Lohenrute, Regenerationstrank, Bücherregal), kommt in Stufe 2.",
          ],
          tasks=[task_item("apothic_enchanting:seashelf", 5)],
          rewards=[reward_item("minecraft:prismarine_shard", 16), reward_xp(5)],
          deps=["shelves"], icon="apothic_enchanting:seashelf"),

    quest("first_infusion", 5, 14, "&eDeine erste Infusion",
          subtitle="Eine Karotte wird golden.",
          description=[
              "Stell &egenau 10 Bücherregale&r an den Tisch (Eterna 20, nicht mehr), leg eine &6Karotte&r in den Zaubertisch. Der dritte Slot leuchtet: Klick ihn, es kostet 3 Lapis und Erfahrung, und heraus kommt eine &6Goldene Karotte&r.",
              "",
              "So funktioniert &6Infusion&r: Ein Rezept verlangt bestimmte Werte für Eterna, Quanta und Arcana, manchmal mit Obergrenze. Stimmen sie, wird das Item im dritten Slot verwandelt. Die Karotte will Eterna genau 20 und Quanta zwischen 10 und 30, die 15 Prozent des leeren Tischs reichen.",
              "",
              "Alle Infusionsrezepte stehen in JEI unter dem Zaubertisch. Honigflaschen werden ab Eterna 20 zu Erfahrungsflaschen, bei Eterna 60 zu acht Stück.",
          ],
          tasks=[task_checkmark("Infundiert")],
          rewards=[reward_item("minecraft:golden_carrot", 8), reward_xp(5)],
          deps=["shelves"], icon="minecraft:golden_carrot"),

    quest("infused_seashelf", 7.5, 13, "&3&lInfundiere ein Seashelf",
          subtitle="Eterna 45 verlangt Frontier.",
          description=[
              "Leg ein &6Seashelf&r in den Zaubertisch, wenn der Tisch &bEterna 45&r, &dQuanta 15&r und &5Arcana 10&r hat. Fünfzehn Bücherregale, fünf Seashelves und der Grundwert des Tischs reichen genau. Heraus kommt ein &6Infused Seashelf&r.",
              "",
              "Das klappt nur, wenn deine Weltstufe &aFrontier&r aktiv ist. In Haven deckelt die Weltstufe dich bei 30, und das Rezept bleibt dunkel.",
              "",
              "Ein Infused Seashelf gibt &b5 Eterna&r (bis 60) und 5 Prozent Arcana. Sechs davon zu den Bücherregalen heben den Tisch auf Eterna 60, nutzbar ab Weltstufe &aAscent&r (Uncommon-Set und ein besiegter Invader).",
          ],
          tasks=[task_item("apothic_enchanting:infused_seashelf", 1)],
          rewards=[reward_table("s1_uncommon"), reward_item("minecraft:lapis_lazuli", 32), reward_xp(10)],
          deps=["seashelf", "first_infusion", "frontier"], icon="apothic_enchanting:infused_seashelf", size=1.5, shape="diamond"),

    quest("library", 10, 13, "&5Die Verzauberungsbibliothek",
          subtitle="Kommt in Stufe 2, lohnt sich jetzt zu kennen.",
          description=[
              "Die &6Enchantment Library&r braucht vier &6Endertruhen&r, vier infundierte Regale und einen Zaubertisch. Endertruhen brauchen Lohenstaub, also wartet sie auf den Nether in &eStufe 2&r. Sammel bis dahin verzauberte Bücher.",
              "",
              "In die Bibliothek wirfst du verzauberte Bücher, jede Verzauberung wird als Punkte gespeichert. Ein Klick holt eine Stufe heraus, Shift-Klick so viele wie möglich, und das Buch dazu entsteht von selbst. Sie merkt sich die höchste Stufe, die je hineinkam, und gibt höchstens Stufe 16 (XVI) aus.",
              "",
              "&eWeiter hinauf:&r Deepshelves (Eterna 70) brauchen Infusion bei Eterna 60, Sculkshelves (80) den Warden, Endshelves (90) Drachenatem aus Stufe 4. Die &6Library of Alexandria&r mit Stufe 31 entsteht per Infusion bei Eterna 100, also in Pinnacle.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_item("minecraft:book", 16)],
          deps=["infused_seashelf"], icon="apothic_enchanting:library", optional=True),

    # ---- Apothic Spawners ---------------------------------------------------------
    quest("spawner", 12.5, 7, "&2&lHol dir einen Spawner",
          subtitle="Behutsamkeit nimmt ihn mit.",
          description=[
              "Bau einen &6Monsterspawner&r mit einer Spitzhacke mit &6Behutsamkeit&r ab. Das kostet die Spitzhacke &e100 Haltbarkeit&r, aber du bekommst den Spawner samt Monster als Item.",
              "",
              "Halte &eShift&r über dem Spawner-Item, dann siehst du seine Werte: Min und Max Spawn Delay (200 und 800 Ticks), Spawn Count (4), Max Entities (6), Activation Range (16) und Spawn Range (4). Genau diese Werte veränderst du mit Runen.",
              "",
              "Spawner findest du in Verliesen, Minen und in den &6Rogue Spawners&r von Apotheosis, die frei in Höhlen stehen und oft eine Kiste dabei haben.",
          ],
          tasks=[task_item("minecraft:spawner", 1)],
          rewards=[reward_table("s1_common"), reward_xp(10)],
          deps=["welcome"], icon="minecraft:spawner", size=1.5),

    quest("rune", 15, 7, "&8Schmiede Spawner-Runen",
          subtitle="Erst sprengen, dann schmieden.",
          description=[
              "Spreng einen Spawner, den du nicht brauchst, mit &6TNT&r. Er fängt an zu zittern und detoniert ein paar Sekunden später selbst, dabei fallen das gespeicherte Monster und &e48 bis 64 Spawner Chains&r heraus.",
              "",
              "Zwei &6Gem Dust&r um ein &6Gem-Fused Slate&r oben, zwei Chains um ein Slate in der Mitte, drei Chains unten ergeben zwei leere &6Spawner Runes&r. Jede fertige Rune wird aus einer leeren gebaut.",
              "",
              "&cAchtung:&r Mit Apotheosis sind die Gegenstände von Apothic Spawners (Zucker, Uhr, fermentiertes Spinnenauge) als Spawner-Upgrade abgeschaltet. Auf Kronwerke geht alles über Runen.",
          ],
          tasks=[task_item("apotheosis:spawner_rune", 2)],
          rewards=[reward_item("minecraft:tnt", 4), reward_xp(5)],
          deps=["spawner", "slate"], icon="apotheosis:spawner_rune"),

    quest("frontier_rune", 17.5, 6, "&aFrontiersman's Rune",
          subtitle="Die Grundwerte in einem Schlag.",
          description=[
              "Vier &6Timeworn Fabric&r in die Ecken, oben und unten je eine &6Uhr&r, links und rechts je ein &6Feuerstein&r, in der Mitte eine leere &6Spawner Rune&r.",
              "",
              "Rechtsklick mit der Rune auf einen Spawner setzt die Grundwerte auf einmal: Delay &e150 bis 600&r Ticks, &e7&r Monster pro Spawn, &e12&r Monster erlaubt, Aktivierung bis &e24&r Blöcke. Vorher waren es 200 bis 800, 4, 6 und 16.",
              "",
              "Die nächste Stufe, das &6Wayfarer's Rune&r (Ascent), will Luminous Crystal Shards, ein Spawn-Ei, ein Sigil of Socketing und &6Netherquarz&r, also Stufe 2. Summit und Pinnacle brauchen eine infundierte Rune bei Eterna 70.",
          ],
          tasks=[task_item("apotheosis:frontier_spawner_upgrade_rune", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["rune", "materials"], icon="apotheosis:frontier_spawner_upgrade_rune"),

    quest("stat_runes", 17.5, 8, "&2Verändere einen Spawner",
          subtitle="Eine Rune je Wert.",
          description=[
              "Halte eine Rune in der Hand und &eRechtsklick&r auf den Spawner. Jede Rune ist eine leere Spawner Rune mit vier gleichen Gegenständen drumherum:",
              "",
              "&6Kolben&r: Spawn Range +2 (bis 32). &6Komparatoren&r: läuft nur mit Redstone-Signal. &6Wolle&r: die Monster sind stumm. &6Lagerfeuer&r: die Monster brennen. &6Schildkröteneier&r: nur Babys. &6Tropfstein&r: die Monster starten mit 16 Prozent weniger Leben (bis 20 Prozent). &6Seelenlaternen&r: ignoriert Licht, Stufe 2.",
              "",
              "Mit &6Netherquarz&r in der Nebenhand (ab Stufe 2) kehrst du eine Rune um, der Quarz bleibt. &eInfundierte Runen&r (Eterna 70) bringen No AI, Ignores Players, Ignores Conditions und Echoing, mehr Beute pro Monster. JEI zeigt unter dem Spawner jede Rune.",
          ],
          tasks=[task_advancement("apothic_spawners:modifier", "Einen Spawner mit einer Rune verändern")],
          rewards=[reward_item("minecraft:piston", 4), reward_item("minecraft:comparator", 4), reward_xp(10)],
          deps=["rune"], icon="apotheosis:redstone_control_spawner_rune"),

    quest("capturing", 20, 7, "&aCapturing",
          subtitle="Spawn-Eier von Monstern.",
          description=[
              "Die Verzauberung &6Capturing&r (bis Stufe III, für Schwerter) lässt Monster mit &e0,5 Prozent je Stufe&r ihr Spawn-Ei fallen. Bosse und manche Monster sind davon ausgenommen.",
              "",
              "Mit einem Spawn-Ei stellst du einen Spawner auf ein anderes Monster um: Rechtsklick mit dem Ei auf den Spawner, fertig. Zombie-Spawner aus dem Verlies, Skelette drin.",
          ],
          tasks=[task_checkmark("Ein Spawn-Ei bekommen")],
          rewards=[reward_item("minecraft:experience_bottle", 8)],
          deps=["spawner"], icon="minecraft:zombie_spawn_egg", optional=True),

    # ---- Attribute -------------------------------------------------------------------
    quest("attributes", 12.5, 13, "&e&lÖffne die Attribut-Anzeige",
          subtitle="Was dein Charakter wirklich kann.",
          description=[
              "Öffne dein Inventar und klick den Knopf &eShow Attributes&r oben rechts. Die Liste zeigt jedes Attribut mit seinem aktuellen Wert. &eHide Unchanged&r blendet alles aus, was noch auf dem Grundwert steht. Mit &eShift&r über einem Eintrag siehst du Basis, Minimum, Maximum und jeden einzelnen Modifikator mit seiner Quelle.",
              "",
              "Apothic Attributes bringt die Werte mit, auf denen die Affixe arbeiten: &6Crit Chance&r und &6Crit Damage&r, &6Life Steal&r (Teil des Schadens heilt dich) und &6Overheal&r (Teil des Schadens wird Absorption, auch bei vollem Leben), &6Armor Pierce&r und &6Armor Shred&r gegen Rüstung, &6Mining Speed&r, &6Dodge Chance&r, &6Draw Speed&r, &6Experience Gained&r, &6Cooldown Reduction&r.",
              "",
              "&eKronwerke:&r Ein paar Teile mit Mining Speed machen den Unterschied, wenn der Obelisk 20 000 Bruchstein will.",
          ],
          tasks=[task_checkmark("Anzeige geöffnet")],
          rewards=[reward_xp(5)],
          deps=["welcome"], icon="minecraft:iron_boots", size=1.5),

    quest("compare", 15, 13, "&eVergleiche und verlinke",
          subtitle="Zwei Tasten, die jeder Sammler braucht.",
          description=[
              "Halte die Taste &eCompare Hovered Equipment&r (Steuerungseinstellungen unter Apotheosis) über einem Item im Inventar, und neben dem Tooltip erscheint das Teil, das du gerade trägst. So siehst du sofort, ob der Fund besser ist.",
              "",
              "Mit &eLink Hovered Item to Chat&r schickst du ein Item in den Chat, alle 5 Sekunden eines. Jeder im Chat kann mit der Maus darauf zeigen und den vollen Tooltip lesen. Praktisch zum Tauschen und zum Angeben.",
              "",
              "&eGlück:&r Das Attribut &6Luck&r verschiebt bei jedem Fund die Gewichte zu besseren Seltenheiten und Reinheiten. Frontier gibt 20 Prozent, Glückstränke und Affixe mit Luck zählen auch. &eDetailed Info&r im Weltstufen-Menü rechnet dein Glück schon ein, mit Shift siehst du die Grundwerte.",
          ],
          tasks=[task_checkmark("Ausprobiert")],
          rewards=[reward_xp(5)],
          deps=["attributes"], icon="minecraft:spyglass"),

    quest("final", 18, 13, "&9&lZerlege ein Rare-Item",
          subtitle="Der Abschluss von Stufe 1 bei Apotheosis.",
          description=[
              "Finde ein &9Rare&r-Item, das du nicht brauchst, und zerleg es im &6Salvaging Table&r zu einem &6Luminous Crystal Shard&r. Oder schmiede dir eins: 15 Level, zwei Shards, zwei Siegel, aber dann hast du die Shards ja schon.",
              "",
              "Damit hast du alles gesehen, was Apotheosis in Stufe 1 hergibt: Frontier aktiv, ein Set mit Affixen, Edelsteine in den Sockeln, einen Zaubertisch auf 45 und einen Spawner nach deinem Geschmack.",
              "",
              "&eAusblick:&r Mit dem Nether in Stufe 2 kommen Hellshelves, das Sigil of Withdrawal, die Gem Case und mit dem Wither die Weltstufe Summit. &5Epic&r ist für Stufe 3 gedacht, &6Mythic&r und Pinnacle für Stufe 4, nach dem Drachen.",
          ],
          tasks=[task_item("apotheosis:luminous_crystal_shard", 1)],
          rewards=[reward_table("s1_rare"), reward_item("apotheosis:gem_dust", 8), reward_xp(15)],
          deps=["frontier", "reforge_table", "infused_seashelf", "stat_runes", "compare"],
          icon="apotheosis:luminous_crystal_shard", size=2.5, shape="gear"),
]

images = [
    banner("apotheosis/title", "Apotheosis", 10, -4.6, height=1.8, kind="title", colour="brass"),
    banner("apotheosis/affixe", "Affixe und Seltenheiten", 3.5, -1.8, height=0.9, colour="brass"),
    banner("apotheosis/siegel", "Siegel und Umschmieden", 16.3, -1.8, height=0.9, colour="stone"),
    banner("apotheosis/edelsteine", "Edelsteine", 3.5, 4.6, height=0.9, colour="magic"),
    banner("apotheosis/spawner", "Apothic Spawners", 16.3, 4.6, height=0.9, colour="nature"),
    banner("apotheosis/enchanting", "Apothic Enchanting", 5, 10.6, height=0.9, colour="water"),
    banner("apotheosis/attribute", "Apothic Attributes", 15.3, 10.6, height=0.9, colour="brass"),
]

chapter(C, "Apotheosis", "apotheosis:salvaging_table", "storage", quests, shape="circle", order=49, stage=1,
        subtitle=["Stufe 1. Affixe, Edelsteine, Siegel, Umschmieden, Zaubertisch und Spawner."], images=images)
