"""Ars Nouveau in stage 1: the first source gem in short steps (amethyst, archwood, imbuement
chamber, source jar, volcanic sourcelink), the novice spell book and the first spell, mana and
the Quellgeborene origin, the scribe's table, every tier 1 glyph (Ars Nouveau, Ars Elemental's
spark, terrain and filters, Ars Technica's Pack) in checklist quests, the apparatus and the
essences, the enchanter's gear, the helpers (Starbuncle, Drygmy, Whirlisprig, Alakarkinos) and
the stage 1 addons (Ars Creo wheel, Ars Additions wand and charms, Ars Elemental pouch, lesser
foci, Siren and Flashjack). Source gems are the magic half of the stage 1 goal.
Numbers come from the Ars jars (recipes, lang guide pages) and config/ars_nouveau*.toml.
Everything with the brazier, relays and tier 2 glyphs is in ars_apprentice.py."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table,
                  reward_xp, banner, img, item_texture)

C = "ars_nouveau"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


def head(name, text, left, y, height=0.9, kind="section", colour="magic"):
    """A banner whose left edge sits at x = left."""
    b = banner(f"{C}/{name}", text, 0, y, height=height, kind=kind, colour=colour)
    b["x"] = round(left + b["width"] / 2, 2)
    return b


LEARN = "Die Quest zählt, sobald die Glyphe im Inventar liegt. Erst danach mit Rechtsklick lernen."

quests = [
    # ---- Der erste Zauber ---------------------------------------------------------
    quest("welcome", 0, 1.5, "&d&lLies das Notizbuch",
          subtitle="Dein Handbuch für die ganze Mod.",
          description=[
              "Das &6Abgenutzte Notizbuch&r liegt beim ersten Login in deinem Inventar. Verloren? &6Buch&r und &6Lapislazuli&r formlos an der Werkbank.",
              "",
              "&dArs Nouveau&r baut Zauber aus &dGlyphen&r wie Sätze aus Wörtern. Die Energie heißt &dQuelle&r (Source), aus ihr entstehen &6Quelljuwelen&r. Die braucht der Server: &e800 Quelljuwelen&r und &e12 Quellschlusssteine&r sind die Magie-Säule von &6Stufe 1&r.",
              "",
              "Dieses Kapitel hat zwei Wege, die du parallel gehst: oben das &dZauberbuch&r, darunter das &6erste Quelljuwel&r.",
          ],
          tasks=[task_item("ars_nouveau:worn_notebook", 1)],
          rewards=[reward_item("minecraft:lapis_lazuli", 8), reward_table("s1_common")],
          icon="ars_nouveau:worn_notebook", size=2.0, shape="hexagon"),

    quest("book", 2.75, 1.5, "&dBau das Anfänger-Zauberbuch",
          subtitle="Vier Eisenwerkzeuge werden zu einem Buch.",
          description=[
              "Formlos: &6Buch&r (oder das Notizbuch), &6Eisenschwert&r, &6Eisenspitzhacke&r, &6Eisenaxt&r, &6Eisenschaufel&r.",
              "",
              "Im &6Zauberbuch für Anfänger&r stecken schon fünf Glyphen: &dProjektil&r, &dBerühren&r und &dSelbst&r als Formen, &dBrechen&r und &dSchaden&r als Effekte. Es kann nur Glyphen der &eStufe 1&r benutzen.",
              "",
              "&eKronwerke:&r Wer die Rolle &dArkanist&r wählt, startet schon mit diesem Buch.",
          ],
          tasks=[task_item("ars_nouveau:novice_spell_book", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 6), reward_xp(3)],
          deps=["welcome"], icon="ars_nouveau:novice_spell_book", size=1.25),

    quest("first_spell", 5.25, 1.5, "&dWirk deinen ersten Zauber",
          subtitle="Projektil, Brechen. Klick, und der Block ist weg.",
          description=[
              "Buch in die Hand, &eC&r drücken. Klick &dProjektil&r, dann &dBrechen&r, gib einen Namen ein, speichern. Rechtsklick wirkt den Zauber.",
              "",
              "Das Buch hat zehn Plätze. Mit &eV&r öffnest du das Auswahlrad. Bau dir gleich einen zweiten: &eProjektil, Schaden&r für den Kampf.",
              "",
              "&cAchtung:&r Brechen ohne Verstärkung schafft nur Blöcke mittlerer Härte. Für Erze kommt bald &dVerstärken&r dahinter.",
          ],
          tasks=[task_checkmark("Zauber gewirkt")],
          rewards=[reward_item("minecraft:experience_bottle", 4), reward_table("s1_common")],
          deps=["book"], icon="ars_nouveau:glyph_projectile", size=1.5, shape="diamond"),

    quest("mana", 7.75, 0.5, "&dBehalte den Manabalken im Blick",
          subtitle="Jeder Zauber kostet Mana, jede Glyphe gibt welches.",
          description=[
              "Der blaue Balken unten links ist dein Mana. Ein Zauber kostet die Summe seiner Glyphen, es lädt sich von selbst wieder auf.",
              "",
              "&eDie Zahlen auf dem Server:&r Grundwert &e100 Mana&r, &e5 pro Sekunde&r zurück. Jede gelernte Glyphe gibt &e+15&r Maximum und &e+0,33&r pro Sekunde. Jede Buchstufe gibt &e+50&r und &e+1&r pro Sekunde.",
              "",
              "Die Verzauberung &dMana-Boost&r bringt &e+25&r pro Stufe, &dMana-Regeneration&r &e+2&r pro Sekunde und Stufe. Glyphen lernen lohnt sich also doppelt.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["first_spell"], icon="minecraft:lapis_lazuli"),

    quest("origin", 7.75, 2.5, "&dWähl die Quellgeborene",
          subtitle="Neo Origins: 50 Mana mehr, ein Herz weniger.",
          description=[
              "Die Herkunft &dQuellgeborene&r gibt &e+50&r maximales Mana in Ars Nouveau und &e+50&r in Iron's Spells. Dafür hast du &cein Herz weniger&r und trägst keine Eisen-, Gold-, Diamant- oder Netheritrüstung.",
              "",
              "Die Magierroben aus Stufe 3 zählen nicht als schwere Rüstung. Leder bis dahin, dann Roben.",
              "",
              "Die Rolle &dArkanist&r passt dazu: &e+1&r Mana pro Sekunde, Tränke wirken 25 Prozent länger. Gewählt wird beim ersten Login, später nur noch mit dem Orb.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["first_spell"], icon="ars_nouveau:source_gem", optional=True),

    quest("spell_theory", 10.25, 1.5, "&dLerne den Aufbau eines Zaubers",
          subtitle="Form, Effekt, Verstärkung.",
          description=[
              "Erst genau eine &aForm&r (wie), dann &aEffekte&r (was), hinter jedem Glied &aVerstärkungen&r (wie stark). Gelesen wird von links nach rechts.",
              "",
              "&dProjektil&r schießt eine Kugel, &dBerühren&r wirkt direkt vor dir, &dSelbst&r auf dich. Eine Verstärkung ändert immer das Glied direkt links von ihr.",
              "",
              "Mehrere Effekte wirken nacheinander am selben Ziel. &eProjektil, Brechen, Artikelabholung&r baut ab und legt die Beute in dein Inventar.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["mana"], icon="ars_nouveau:blank_glyph"),

    quest("scribes_table", 12.75, 1.5, "&aBau den Tisch des Schreibers",
          subtitle="Hier entstehen neue Glyphen.",
          description=[
              "Oben &e3 Archwood-Stufen&r, Mitte links und rechts je ein &6Goldnugget&r, unten links und rechts je ein &6Archwood-Stamm&r.",
              "",
              "Klick den Tisch mit dem Zauberbuch an, wähl eine Glyphe, drück &eAuswählen&r und wirf die angezeigten Zutaten mit &eQ&r auf den Tisch. Er zieht sie auch aus Truhen daneben.",
              "",
              "Jede Glyphe kostet dazu Erfahrung: Stufe 1 &e27 Punkte&r, Stufe 2 &e55&r, Stufe 3 &e160&r. Die fertige Glyphe fällt als Item heraus, Rechtsklick lernt sie für immer.",
          ],
          tasks=[task_item("ars_nouveau:scribes_table", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 8), reward_xp(3)],
          deps=["spell_theory", "archwood"], icon="ars_nouveau:scribes_table", size=1.5, shape="square"),

    # ---- Das erste Quelljuwel --------------------------------------------------------
    quest("amethyst", 0, 5.5, "&6Sammle Amethyst",
          subtitle="Der Rohstoff für jedes Quelljuwel.",
          description=[
              "Amethyst wächst in &eGeoden&r unter der Erde: eine Kugel aus Glattem Basalt und Kalzit, innen lila. Bau die ausgewachsenen Cluster ab.",
              "",
              "&6Knospender Amethyst&r lässt sich nicht mitnehmen. Merk dir die Geode, die Knospen wachsen immer wieder nach.",
              "",
              "Lapislazuli geht auch: die Kammer macht aus einem Stück ebenfalls ein Quelljuwel.",
          ],
          tasks=[task_item("minecraft:amethyst_shard", 8)],
          rewards=[reward_item("minecraft:amethyst_shard", 4), reward_xp(2)],
          deps=["welcome"], icon="minecraft:amethyst_shard"),

    quest("archwood", 2.5, 5.5, "&6Fäll Archwood",
          subtitle="Bunte Wälder, aus denen alles gebaut wird.",
          description=[
              "&6Archwood&r wächst in eigenen Wäldern mit roten, blauen, grünen und violetten Blättern. Jeder Stamm ergibt &e4 Archwood-Planken&r, die Farbe ist dabei egal.",
              "",
              "Pflanz ein paar Setzlinge zu Hause ein. Kammer, Glas, Tisch und Podeste brauchen alle Archwood.",
              "",
              "&eTipp:&r In denselben Wäldern leben die &dSternbunkel&r und wachsen die &6Quellbeeren&r.",
          ],
          tasks=[task_item("ars_nouveau:archwood_planks", 32)],
          rewards=[reward_item("minecraft:gold_nugget", 9), reward_xp(2)],
          deps=["welcome"], icon="ars_nouveau:green_archwood_log"),

    quest("archwood_colors", 2.5, 7.5, "&6Sammle alle vier Setzlinge",
          subtitle="Jede Farbe hat ihre Aufgabe.",
          description=[
              "Ein Setzling jeder Farbe: rot, blau, grün, violett.",
              "",
              "&cFlammend&r (rot) brennt im Vulkanischen Quelllink am besten. Die Ritualtafeln ab Stufe 2 brauchen Stämme in der passenden Farbe: &aBlühend&r (grün) für Natur, &bKaskadierend&r (blau) für Wasser und Wetter, &5Ärgerlich&r (violett) für Bindung und Suche.",
              "",
              "Ein kleiner Garten mit allen vier spart dir später viele Wege.",
          ],
          tasks=[task_item("ars_nouveau:red_archwood_sapling", 1), task_item("ars_nouveau:blue_archwood_sapling", 1),
                 task_item("ars_nouveau:green_archwood_sapling", 1), task_item("ars_nouveau:purple_archwood_sapling", 1)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["archwood"], icon="ars_nouveau:red_archwood_sapling", optional=True),

    quest("imbuement", 5, 5.5, "&a&lBau eine Imbuement-Kammer",
          subtitle="Der einzige Weg zu Quelljuwelen.",
          description=[
              "&e6 Archwood-Planken&r im Kreis, &e2 Goldbarren&r oben und unten in der Mitte, die Mitte bleibt frei.",
              "",
              "Rechtsklick mit Amethyst legt ihn hinein. Die Kammer sammelt ganz langsam Quelle von allein, oder schnell aus einem &6Quellglas&r, das höchstens &e2 Blöcke&r entfernt steht.",
          ],
          tasks=[task_item("ars_nouveau:imbuement_chamber", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 2), reward_xp(3)],
          deps=["archwood"], icon="ars_nouveau:imbuement_chamber", size=1.5, shape="square"),

    quest("first_gem", 7.5, 5.5, "&d&lMach dein erstes Quelljuwel",
          subtitle="Ein Amethystsplitter, 500 Quelle, ein Juwel.",
          description=[
              "Leg einen &6Amethystsplitter&r oder &6Lapislazuli&r in die Kammer und warte. Bei &d500 Quelle&r ist das &6Quelljuwel&r fertig, Rechtsklick nimmt es heraus.",
              "",
              pic("ars_nouveau:source_gem"),
              "",
              "Ohne Glas dauert das erste Juwel ein paar Minuten. Nutz die Zeit für die nächsten Teile: ein Quellglas und einen Quelllink.",
          ],
          tasks=[task_item("ars_nouveau:source_gem", 1)],
          rewards=[reward_item("minecraft:amethyst_shard", 8), reward_xp(4)],
          deps=["imbuement", "amethyst"], icon="ars_nouveau:source_gem", size=1.25, shape="diamond"),

    quest("source_jar", 10, 5.5, "&aBau ein Quellglas",
          subtitle="Der Speicher für deine Quelle.",
          description=[
              "Oben und unten je &e3 Archwood-Stufen&r, an den Seiten der Mitte je ein &6Glas&r.",
              "",
              "Ein &6Quellglas&r hält &d10 000 Quelle&r. Quelllinks füllen Gläser bis &e5 Blöcke&r weit, Kammer und Apparat ziehen aus Gläsern in der Nähe. Abgebaut behält es seinen Inhalt.",
              "",
              "Ein Komparator daneben gibt ein Signal nach Füllstand.",
          ],
          tasks=[task_item("ars_nouveau:source_jar", 1)],
          rewards=[reward_item("minecraft:glass", 8), reward_xp(4)],
          deps=["first_gem"], icon="ars_nouveau:source_jar"),

    quest("volcanic", 12.5, 5.5, "&aBau einen Vulkanischen Quelllink",
          subtitle="Holz rein, Quelle raus.",
          description=[
              "Oben und unten je ein &6Quelljuwel&r, links und rechts je ein &6Goldbarren&r, ein &6Lavaeimer&r in die Mitte.",
              "",
              "Der Link verbrennt alles, was brennt, und füllt damit das nächste Glas. &6Archwood-Stämme&r geben einen Bonus, &cFlammendes Archwood&r den größten.",
              "",
              "&cAchtung:&r Er wird heiß. Stein daneben wird mit der Zeit zu Magma und dann zu Lava.",
          ],
          tasks=[task_item("ars_nouveau:volcanic_sourcelink", 1)],
          rewards=[reward_item("ars_nouveau:red_archwood_log", 8), reward_xp(5)],
          deps=["source_jar"], icon="ars_nouveau:volcanic_sourcelink"),

    quest("fill_jar", 15, 5.5, "&dFüll dein erstes Glas",
          subtitle="Stämme auf den Boden, der Balken steigt.",
          description=[
              "Stell Glas und Link höchstens &e5 Blöcke&r auseinander, die Kammer höchstens &e2 Blöcke&r neben das Glas. Wirf Stämme neben den Link.",
              "",
              "Wenn sich das Glas sichtbar füllt und die Kammer schneller arbeitet, steht deine erste Quelle. Ab jetzt ist Amethyst der einzige Engpass.",
              "",
              "&eTipp:&r Eine kleine Archwood-Baumfarm neben dem Link ist die einfachste Dauerquelle der ersten Tage.",
          ],
          tasks=[task_checkmark("Glas füllt sich, Kammer läuft")],
          rewards=[reward_item("ars_nouveau:red_archwood_log", 16), reward_xp(5)],
          deps=["volcanic"], icon="ars_nouveau:source_jar"),

    quest("source_gems", 17.5, 5.5, "&d&lMach 16 Quelljuwelen",
          subtitle="Die Währung der Magie.",
          description=[
              "Lass die Kammer am Glas laufen, bis du &e16 Quelljuwelen&r hast. Ein &6Amethystblock&r wird für &d2 000 Quelle&r direkt zum &6Quelljuwelblock&r.",
              "",
              "Juwelen stecken in Quellstein, Podesten, Apparat, allen Links und jedem Schmuckstück. Was übrig ist, gehört in den &eObelisken&r an der Spawn.",
          ],
          tasks=[task_item("ars_nouveau:source_gem", 16)],
          rewards=[reward_item("minecraft:amethyst_shard", 16), reward_table("s1_common")],
          deps=["fill_jar"], icon="ars_nouveau:source_gem", size=1.25),

    quest("chamber_auto", 20, 5.5, "&aAutomatisiere die Kammer",
          subtitle="Trichter oben, Trichter unten, und du gehst schlafen.",
          description=[
              "Ein &6Trichter&r über der Kammer füllt Amethyst nach, ein Trichter darunter holt die fertigen Juwelen in eine Truhe.",
              "",
              "Mehrere Kammern um ein Glas herum, jede mit eigenem Trichterpaar, vervielfachen die Ausbeute. Später trägt ein Sternbunkel alles in eine Truhe.",
          ],
          tasks=[task_item("ars_nouveau:imbuement_chamber", 3), task_item("minecraft:hopper", 2)],
          rewards=[reward_item("minecraft:hopper", 2), reward_table("s1_uncommon")],
          deps=["source_gems"], icon="minecraft:hopper"),

    quest("dowsing", 0, 7.5, "&6Bau eine Wünschelrute",
          subtitle="Knospenden Amethyst durch Wände sehen.",
          description=[
              "Oben ein &6Goldbarren&r, unten links und rechts je eine &6Archwood-Planke&r.",
              "",
              "Benutzt zeigt sie dir eine Weile &6Knospenden Amethyst&r durch Stein und lässt magische Wesen im Umkreis von &e75 Blöcken&r leuchten. Sie hat nur eine begrenzte Zahl an Nutzungen.",
          ],
          tasks=[task_item("ars_nouveau:dowsing_rod", 1)],
          rewards=[reward_item("minecraft:amethyst_shard", 8)],
          deps=["amethyst"], icon="ars_nouveau:dowsing_rod", optional=True),

    quest("sourceberry", 10, 7.5, "&6Pflanz Quellbeeren an",
          subtitle="Essen, das Mana zurückgibt.",
          description=[
              "&6Quellbeeren&r wachsen wild in Taiga und Archwood-Wäldern. Pflanz sie zu Hause an wie Süßbeeren.",
              "",
              "Gegessen geben sie Mana-Regeneration. Als &6Quellbeerkuchen&r oder &6Quellbeerbrötchen&r sind sie das beste Futter für den Myzel-Link, und Sternbunkel ernten reife Büsche von selbst.",
          ],
          tasks=[task_item("ars_nouveau:sourceberry_bush", 8)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["source_jar"], icon="ars_nouveau:sourceberry_bush", optional=True),

    quest("agronomic", 12.5, 7.5, "&aBau einen Agronomischen Quelllink",
          subtitle="Wachsende Pflanzen erzeugen Quelle.",
          description=[
              "Wie der Vulkanische, aber &6Weizen&r statt Lavaeimer in der Mitte.",
              "",
              "Jede Pflanze und jeder Baum, der im Umkreis von &e15 Blöcken&r wächst, bringt Quelle. Magebloom, Quellbeeren und Archwood-Setzlinge bringen extra.",
              "",
              "&cAchtung:&r Knochenmehl zählt nicht, die Pflanzen müssen von selbst wachsen.",
          ],
          tasks=[task_item("ars_nouveau:agronomic_sourcelink", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16)],
          deps=["volcanic"], icon="ars_nouveau:agronomic_sourcelink", optional=True),

    quest("mycelial", 15, 7.5, "&aBau einen Myzel-Quelllink",
          subtitle="Essen wird zu Quelle.",
          description=[
              "Wie der Vulkanische, aber &6Pilzsuppe&r in der Mitte.",
              "",
              "Er verzehrt Essen in der Nähe oder auf Podesten daneben, nahrhaftes Essen gibt mehr, Quellbeer-Essen viel mehr. Den Boden im 3x3 unter sich macht er zu Myzel und lässt Pilze wachsen.",
          ],
          tasks=[task_item("ars_nouveau:mycelial_sourcelink", 1)],
          rewards=[reward_item("minecraft:mushroom_stew", 2)],
          deps=["agronomic"], icon="ars_nouveau:mycelial_sourcelink", optional=True),

    quest("vitalic", 17.5, 7.5, "&aBau einen Vitalic-Quelllink",
          subtitle="Tierzucht und Tod bringen Quelle.",
          description=[
              "Wie der Vulkanische, aber &6Glitzernde Melonenscheibe&r in der Mitte.",
              "",
              "Er erzeugt Quelle, wenn in der Nähe Tiere gezüchtet werden oder Wesen sterben, dazu ein wenig von allein für jedes Tierbaby. Die Babys wachsen schneller. Neben einer Tierfarm arbeitet er nebenbei mit.",
          ],
          tasks=[task_item("ars_nouveau:vitalic_sourcelink", 1)],
          rewards=[reward_item("minecraft:wheat", 16)],
          deps=["mycelial"], icon="ars_nouveau:vitalic_sourcelink", optional=True),

    # ---- Die ersten Glyphen -------------------------------------------------------------
    quest("glyph_light", 0, 10.5, "&dLern Magielicht beschwören",
          subtitle="Nie wieder Fackeln schleppen.",
          description=[
              "Am Tisch: &6Laterne&r und &6Fackel&r. " + LEARN,
              "",
              "&eProjektil, Magielicht beschwören&r setzt ein dauerhaftes Licht an die Wand. Mit &dVerstärken&r leuchtet es wie Glowstone. &eSelbst, Magielicht&r gibt dir Nachtsicht.",
          ],
          tasks=[task_item("ars_nouveau:glyph_light", 1)],
          rewards=[reward_item("minecraft:torch", 16), reward_xp(2)],
          deps=["scribes_table"], icon="ars_nouveau:glyph_light"),

    quest("glyph_amplify", 0, 12.5, "&dLern Verstärken",
          subtitle="Mehr Kraft für das Glied links davon.",
          description=[
              "Am Tisch: eine &6Diamantspitzhacke&r.",
              "",
              "Hinter &dSchaden&r mehr Schaden, hinter &dBrechen&r eine Abbaustufe mehr, hinter Magieblock bleibt der Block stehen. Mehrfach setzen geht, jede kostet extra Mana.",
              "",
              "&eTipp:&r Zwei Abbauzauber: billig für Stein, verstärkt für Erze.",
          ],
          tasks=[task_item("ars_nouveau:glyph_amplify", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 4), reward_xp(3)],
          deps=["scribes_table"], icon="ars_nouveau:glyph_amplify"),

    quest("glyph_pickup", 2.5, 10.5, "&dLern Artikelabholung",
          subtitle="Die Beute landet gleich im Inventar.",
          description=[
              "Am Tisch: zwei &6Trichter&r.",
              "",
              "Sammelt alle Items am Zielort ein. Setz sie &ehinter&r den Effekt: &eProjektil, Brechen, Artikelabholung&r. Mit AOE (Stufe 2) wird der Radius größer.",
          ],
          tasks=[task_item("ars_nouveau:glyph_pickup", 1)],
          rewards=[reward_item("minecraft:hopper", 1), reward_xp(3)],
          deps=["glyph_light", "glyph_amplify"], icon="ars_nouveau:glyph_pickup"),

    quest("glyph_phantom_block", 2.5, 12.5, "&dLern Magieblock beschwören",
          subtitle="Eine Brücke aus dem Nichts.",
          description=[
              "Am Tisch: &e8 Glas&r.",
              "",
              "Setzt einen leuchtenden Block, der nach kurzer Zeit verschwindet. Mit &dVerstärken&r bleibt er, &dZerstreuen&r löst ihn auf. &eProjektil, Magieblock&r baut Stufen an jede Wand.",
          ],
          tasks=[task_item("ars_nouveau:glyph_phantom_block", 1)],
          rewards=[reward_item("minecraft:glass", 8), reward_xp(3)],
          deps=["glyph_light", "glyph_amplify"], icon="ars_nouveau:glyph_phantom_block"),

    quest("beginner_spells", 5, 11.5, "&d&lFüll dein Zauberbuch",
          subtitle="Zehn Plätze, sechs gute Ideen.",
          description=[
              "&eBergbau:&r Projektil, Brechen, Verstärken, Artikelabholung. &eLicht:&r Projektil, Magielicht. &eBrücke:&r Projektil, Magieblock.",
              "&eNahkampf:&r Berühren, Schaden, Verstärken, Verstärken. &eFernkampf:&r Projektil, Schaden, Verstärken. &eFeld:&r Berühren, Ernte.",
              "",
              "Tut ein Zauber nicht, was er soll, schau zuerst auf die Reihenfolge der Verstärkungen.",
          ],
          tasks=[task_checkmark("Fünf Zauber gespeichert")],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["glyph_pickup", "glyph_phantom_block"], icon="ars_nouveau:novice_spell_book", size=1.5, shape="diamond"),

    quest("glyphs_simple", 7.5, 10.5, "&dLern die Werkzeug-Glyphen",
          subtitle="Checkliste Stufe 1: ohne Essenzen.",
          description=[
              "&dHandwerk&r (Werkbank): öffnet überall ein Craftingfenster.",
              "&dZiehen&r (Angel): zieht das Ziel zu dir.",
              "&dEmpfindlich&r (Gerüst, Mohn, Wassereimer): Formen treffen auch Gras, Flüssigkeiten und Luft.",
              "&dUnter den Füßen&r (Eisenstiefel, Holzdruckplatte): Form, trifft den Block unter dir.",
              "&dPantomime&r (8 Glas): Form, trifft den nächsten Block in deiner Blickrichtung.",
              "&dZurücksetzen&r (Zielscheibe): der Rest des Zaubers trifft wieder das ursprüngliche Ziel.",
              "",
              LEARN,
          ],
          tasks=[task_item("ars_nouveau:glyph_craft", 1), task_item("ars_nouveau:glyph_pull", 1),
                 task_item("ars_nouveau:glyph_sensitive", 1), task_item("ars_nouveau:glyph_underfoot", 1),
                 task_item("ars_nouveau:glyph_pantomime", 1), task_item("ars_nouveau:reset", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 6), reward_xp(3)],
          deps=["beginner_spells"], icon="ars_nouveau:glyph_craft"),

    quest("glyphs_wild", 7.5, 12.5, "&dLern Feuer, Ross und Zufall",
          subtitle="Checkliste Stufe 1: drei für unterwegs.",
          description=[
              "&dEntzünden&r (Feuerzeug, 3 Kohle): setzt Blöcke und Wesen in Brand. Mit Empfindlich nur Wesen.",
              "&dRoss beschwören&r (4 Leder): ein gesatteltes Pferd für ein paar Minuten.",
              "&dZufall&r (2 rosa Teppiche): mischt Blöcke aus der Hotbar bei Block platzieren und Austausch.",
          ],
          tasks=[task_item("ars_nouveau:glyph_ignite", 1), task_item("ars_nouveau:glyph_summon_steed", 1),
                 task_item("ars_nouveau:glyph_randomize", 1)],
          rewards=[reward_item("minecraft:leather", 8), reward_xp(3)],
          deps=["beginner_spells"], icon="ars_nouveau:glyph_ignite"),

    # ---- Apparat und Essenzen -------------------------------------------------------
    quest("sourcestone", 0, 16.5, "&6Mach Quellstein",
          subtitle="Stein mit einem Juwel darin.",
          description=[
              "&e8 Stein&r (jede Sorte) um &e1 Quelljuwel&r ergeben &e8 Quellstein&r.",
              "",
              "Grundlage für Podeste, Arkanen Kern und Apparat. Am Steinmetz gibt es viele Varianten zum Bauen, mit Ars Additions auch Türen, Knöpfe und Mauern.",
          ],
          tasks=[task_item("ars_nouveau:sourcestone", 16)],
          rewards=[reward_item("minecraft:gold_ingot", 2), reward_xp(3)],
          deps=["source_gems"], icon="ars_nouveau:sourcestone"),

    quest("pedestals", 2.5, 16.5, "&aBau Arkane Podeste",
          subtitle="Kleine Tische für Zutaten.",
          description=[
              "Oben Quellstein, &6Quelljuwel&r, Quellstein. Darunter zweimal Goldnugget, Quellstein, Goldnugget.",
              "",
              "Rechtsklick legt ein Item ab, leere Hand nimmt es zurück. Der Apparat braucht bis zu &e8&r davon, die Kammer für Essenzen &e3&r.",
          ],
          tasks=[task_item("ars_nouveau:arcane_pedestal", 4)],
          rewards=[reward_item("minecraft:gold_nugget", 18), reward_xp(3)],
          deps=["sourcestone"], icon="ars_nouveau:arcane_pedestal"),

    quest("arcane_core", 5, 16.5, "&aBau einen Arkanen Kern",
          subtitle="Der Sockel für den Apparat.",
          description=[
              "Oben und unten je &e3 Quellstein&r, in der Mitte Goldbarren, &6Quelljuwel&r, Goldbarren.",
              "",
              "Der Kern allein tut nichts. Auf ihn kommt im nächsten Schritt der Apparat.",
          ],
          tasks=[task_item("ars_nouveau:arcane_core", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 3), reward_xp(4)],
          deps=["pedestals"], icon="ars_nouveau:arcane_core"),

    quest("apparatus", 7.5, 16.5, "&a&lBau den Bezaubernden Apparat",
          subtitle="Der Werktisch der Magier.",
          description=[
              "Ecken &6Goldnuggets&r, oben und unten Mitte &6Quellstein&r, Mitte Goldbarren, &6Diamant&r, Goldbarren. Stell ihn auf den Arkanen Kern.",
              "",
              "Nebenzutaten auf Podeste im Umkreis von &e3 Blöcken&r, dann mit der Hauptzutat auf den Apparat klicken. Quelle zieht er aus Gläsern in der Nähe.",
              "",
              "Er verzaubert auch Werkzeuge und Rüstung direkt, bis hin zu Mana-Boost und Mana-Regeneration. JEI zeigt alle Rezepte.",
          ],
          tasks=[task_item("ars_nouveau:enchanting_apparatus", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(8)],
          deps=["arcane_core"], icon="ars_nouveau:enchanting_apparatus", size=1.75, shape="square"),

    quest("magebloom", 10.25, 16.5, "&6Zieh Magebloom",
          subtitle="Der Stoff, aus dem Magier sind.",
          description=[
              "Im Apparat: beliebige &6Samen&r in die Mitte, &e4 Quelljuwelen&r auf die Podeste. Heraus kommt &6Mageblütensamen&r für Ackerland.",
              "",
              "Eine Blüte ergibt formlos &e4 Magieblütenfasern&r. Die brauchst du für Pergament, Runenkreide, Fäden, Roben und den Trinkets Pouch.",
          ],
          tasks=[task_item("ars_nouveau:magebloom_fiber", 16)],
          rewards=[reward_item("minecraft:bone_meal", 16), reward_xp(3)],
          deps=["apparatus"], icon="ars_nouveau:magebloom"),

    quest("parchment", 12.75, 16.5, "&6Beschreib ein Pergament",
          subtitle="Ein Zauber zum Mitnehmen.",
          description=[
              "&6Leeres Pergament&r: &e1 Papier&r umgeben von &e8 Magieblütenfasern&r. Leg es auf den Tisch des Schreibers, wähl den Zauber im Buch und klick schleichend auf den Tisch.",
              "",
              "Pergamente füttern ab Stufe 2 die Zaubertürme. Formlos mit einer Truhe wird ein leeres zur &6Gegenstandsrolle: Erlauben&r, mit Bruchstein zu &6Verweigern&r. Beides sind Filter für Sternbunkel.",
          ],
          tasks=[task_item("ars_nouveau:spell_parchment", 1)],
          rewards=[reward_item("minecraft:paper", 8), reward_xp(3)],
          deps=["magebloom"], icon="ars_nouveau:spell_parchment"),

    quest("trinkets", 15.25, 16.5, "&6Schmied einen Ring des Potenzials",
          subtitle="Der Anfang jedes Schmuckstücks.",
          description=[
              "&e8 Eisennuggets&r um &e1 Quelljuwel&r. Mit nur 4 Nuggets im Kreuz entsteht das &6Langweilige Schmuckstück&r, die Basis für Amulette.",
              "",
              "Der Ring ist selbst nur ein Rohling. Im Apparat wird er zum &6Ring des geringeren Rabatts&r (4 Diamanten, 2 Enderperlen, 2 Quelljuwelen), der jeden Zauber billiger macht, oder zum &6Ring des Springens&r.",
          ],
          tasks=[task_item("ars_nouveau:ring_of_potential", 1)],
          rewards=[reward_item("minecraft:iron_nugget", 16), reward_xp(3)],
          deps=["apparatus"], icon="ars_nouveau:ring_of_potential"),

    quest("amulet", 17.75, 16.5, "&6Schmied ein Mana-Amulett",
          subtitle="Mehr Mana oder schneller zurück.",
          description=[
              "Langweiliges Schmuckstück in den Apparat. &e3 Diamanten, 5 Quelljuwelen&r ergeben das &6Amulett des Mana-Boosts&r, &e2 Diamanten, 2 Goldbarren, 4 Quelljuwelen&r das &6Amulett der Manaregeneration&r.",
              "",
              "Nur ein Amulett passt in den Curio-Platz. Für lange Bergbauzauber ist mehr Mana meist besser.",
          ],
          tasks=[task_item("ars_nouveau:amulet_of_mana_boost", 1)],
          rewards=[reward_item("minecraft:diamond", 2), reward_xp(5)],
          deps=["trinkets"], icon="ars_nouveau:amulet_of_mana_boost", optional=True),

    quest("earth_essence", 0, 19.5, "&dMach Erdessenz",
          subtitle="Die Kammer kann mehr als Juwelen.",
          description=[
              "Drei &6Podeste&r höchstens &e1 Block&r neben die Kammer: &6Eisenbarren&r, &6Samen&r, &6Erde&r. Ein Quelljuwel hinein, &d2 000 Quelle&r, fertig.",
              "",
              pic("ars_nouveau:earth_essence"),
              "",
              "Die Podest-Items bleiben liegen. Jede Essenz verbraucht nur das Juwel.",
          ],
          tasks=[task_item("ars_nouveau:earth_essence", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 4), reward_xp(4)],
          deps=["pedestals"], icon="ars_nouveau:earth_essence"),

    quest("manipulation_essence", 2.5, 19.5, "&dMach Manipulationsessenz",
          subtitle="Knopf, Redstone, Uhr.",
          description=[
              "Auf die Podeste: &6Steinknopf&r, &6Redstone&r, &6Uhr&r. Quelljuwel in die Kammer, &d2 000 Quelle&r.",
              "",
              "Die vielseitigste Essenz: Block platzieren, Interagieren, Drehen, Verzögerung, die Runenkreide und später viele Relais und Rituale.",
          ],
          tasks=[task_item("ars_nouveau:manipulation_essence", 2)],
          rewards=[reward_item("minecraft:redstone", 8), reward_xp(4)],
          deps=["earth_essence"], icon="ars_nouveau:manipulation_essence"),

    quest("essences_more", 5, 19.5, "&dMach Wasser, Feuer und Abschwörung",
          subtitle="Checkliste: drei Essenzen ohne Monster.",
          description=[
              "&bWasser:&r Wassereimer, Schneeblock, Seetang.",
              "&cFeuer:&r Feuerzeug, Fackel, Schwarzpulver.",
              "&5Abschwörung:&r Fermentiertes Spinnenauge, Zucker, Milcheimer.",
              "",
              "&eTipp:&r Stell zwei, drei Kammern mit festen Podest-Sätzen auf, dann tauschst du nur das Juwel.",
          ],
          tasks=[task_item("ars_nouveau:water_essence", 1), task_item("ars_nouveau:fire_essence", 1),
                 task_item("ars_nouveau:abjuration_essence", 1)],
          rewards=[reward_item("minecraft:amethyst_shard", 16), reward_xp(5)],
          deps=["manipulation_essence"], icon="ars_nouveau:water_essence"),

    quest("wilden", 7.5, 19.5, "&cJag die Wilden",
          subtitle="Horn, Flügel, Stachel.",
          description=[
              "&cJäger&r und &cPirscher&r leben nachts um Wilden-Baue in Wäldern, &cVerteidiger&r nur in kalten Biomen. Bring Rüstung mit.",
              "",
              "Der Jäger lässt &6Wilden-Hörner&r fallen, der Pirscher &6Flügel&r, der Verteidiger &6Stacheln&r. Flügel stecken in Luftessenz und Sprung, Hörner in Beschwörungsessenz und im Drygmy.",
          ],
          tasks=[task_item("ars_nouveau:wilden_horn", 1), task_item("ars_nouveau:wilden_wing", 1),
                 task_item("ars_nouveau:wilden_spike", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["essences_more"], icon="ars_nouveau:wilden_horn"),

    quest("essences_wild", 10, 19.5, "&dMach Luft- und Beschwörungsessenz",
          subtitle="Checkliste: die zwei Essenzen mit Wilden-Teilen.",
          description=[
              "&fLuft:&r Feder, &6Wilden-Flügel&r, Pfeil.",
              "&dBeschwörung:&r &6Wilden-Horn&r, &6Sternbunkel-Scherben&r, Buch.",
              "",
              "Damit hast du alle sieben Essenzen von Ars Nouveau. Die achte, &6Anima&r von Ars Elemental, braucht einen Witherskelettschädel und kommt mit Stufe 2.",
          ],
          tasks=[task_item("ars_nouveau:air_essence", 1), task_item("ars_nouveau:conjuration_essence", 1)],
          rewards=[reward_item("minecraft:feather", 8), reward_xp(5)],
          deps=["wilden", "starbuncle_token"], icon="ars_nouveau:air_essence"),

    # ---- Glyphen mit Essenzen ---------------------------------------------------------
    quest("glyph_harvest", 0, 22.5, "&dLern Ernte",
          subtitle="Felder abernten, ohne neu zu pflanzen.",
          description=[
              "Am Tisch: &6Erdessenz&r und &6Eisenhacke&r.",
              "",
              "&eBerühren, Ernte&r erntet reife Pflanzen und lässt sie stehen. Mit AOE (Stufe 2) ein ganzes Beet.",
          ],
          tasks=[task_item("ars_nouveau:glyph_harvest", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16), reward_xp(3)],
          deps=["earth_essence", "scribes_table"], icon="ars_nouveau:glyph_harvest"),

    quest("glyphs_earth", 0, 24.5, "&dLern die Erd- und Wasser-Glyphen",
          subtitle="Checkliste Stufe 1: Natur.",
          description=[
              "&dFällen&r (Erdessenz, Diamantaxt): erntet ganze Bäume, Pilze und Kakteen.",
              "&dSchlinge&r (Erdessenz, 4 Spinnweben): das Ziel kann sich nicht bewegen.",
              "&dEinfrieren&r (Wasseressenz, 2 Schneeblöcke): friert Wasser und Lava, verlangsamt Wesen.",
              "&dBlase&r (Wasseressenz, 3 Federn, Wassereimer, Boot): Wesen schweben in einer Blase hoch.",
          ],
          tasks=[task_item("ars_nouveau:glyph_fell", 1), task_item("ars_nouveau:glyph_snare", 1),
                 task_item("ars_nouveau:glyph_freeze", 1), task_item("ars_nouveau:glyph_bubble", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 8), reward_xp(4)],
          deps=["glyph_harvest", "essences_more"], icon="ars_nouveau:glyph_fell"),

    quest("glyphs_manip", 2.5, 22.5, "&dLern die Manipulations-Glyphen",
          subtitle="Checkliste Stufe 1: Blöcke bewegen und schalten.",
          description=[
              "Alle mit &6Manipulationsessenz&r:",
              "&dBlock platzieren&r (Werfer): setzt Blöcke aus der Hotbar. &dWerfen&r (Spender): legt ein Item ab oder in ein Inventar. &dInteragieren&r (Hebel, Druckplatte, Knopf): Rechtsklick aus der Ferne.",
              "&dDrehen&r (nur die Essenz): dreht Blöcke. &dVerzögerung&r (Verstärker, Uhr): alles rechts davon wirkt später.",
          ],
          tasks=[task_item("ars_nouveau:glyph_place_block", 1), task_item("ars_nouveau:glyph_toss", 1),
                 task_item("ars_nouveau:glyph_interact", 1), task_item("ars_nouveau:glyph_rotate", 1),
                 task_item("ars_nouveau:glyph_delay", 1)],
          rewards=[reward_item("minecraft:redstone", 16), reward_xp(4)],
          deps=["manipulation_essence"], icon="ars_nouveau:glyph_place_block"),

    quest("glyphs_manip2", 2.5, 24.5, "&dLern Schneiden, Verdampfen, Signal und Rune",
          subtitle="Checkliste Stufe 1: Manipulation, zweiter Teil.",
          description=[
              "&dSchneiden&r (Essenz, Schere, Eisenschwert): wirkt wie eine Schere, kostet nichts.",
              "&dVerdampfen&r (Essenz, 3 Schwämme): entfernt Flüssigkeiten in einem Bereich.",
              "&dRedstone-Signal&r (Essenz, 3 Redstoneblöcke): kurzes Signal am Ziel.",
              "&dRune&r (Essenz, Runenkreide, Haken): legt eine Falle, die ihren Zauber auf alles wirkt, was darüber läuft. Runenkreide: Manipulationsessenz, Knochenmehl, Magieblütenfaser.",
          ],
          tasks=[task_item("ars_nouveau:glyph_cut", 1), task_item("ars_nouveau:glyph_evaporate", 1),
                 task_item("ars_nouveau:glyph_redstone_signal", 1), task_item("ars_nouveau:glyph_rune", 1)],
          rewards=[reward_item("minecraft:redstone_block", 1), reward_xp(4)],
          deps=["glyphs_manip", "magebloom"], icon="ars_nouveau:glyph_rune"),

    quest("glyph_pack", 2.5, 26.5, "&dLern Pack",
          subtitle="Ars Technica: Items packen per Zauber.",
          description=[
              "Am Tisch: &6Manipulationsessenz&r, &6Werkbank&r, &6Truhe&r, &6Eisenblock&r.",
              "",
              "Packt gleiche Items am Boden in ihr 2x2-Rezept, etwa Schneebälle zu Schnee. Die einzige Glyphe von Ars Technica, die schon in Stufe 1 offen ist. Der Rest kommt mit Messing in Stufe 2.",
          ],
          tasks=[task_item("ars_technica:glyph_pack", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 4), reward_xp(3)],
          deps=["glyphs_manip"], icon="ars_technica:glyph_pack", optional=True),

    quest("glyph_dispel", 5, 22.5, "&dLern Zerstreuen",
          subtitle="Weg mit allen Effekten.",
          description=[
              "Am Tisch: &5Abschwörungsessenz&r und &e3 Milcheimer&r.",
              "",
              "Entfernt alle Trankeffekte vom Ziel und schickt beschworene Helfer in ihren Charme zurück. Auf eine &6Hexe&r mit höchstens halber Gesundheit gibt es &6Wixie-Scherben&r für Stufe 2.",
          ],
          tasks=[task_item("ars_nouveau:glyph_dispel", 1)],
          rewards=[reward_item("minecraft:milk_bucket", 1), reward_xp(3)],
          deps=["essences_more"], icon="ars_nouveau:glyph_dispel", section="glyphen2"),

    quest("glyph_leap", 7.5, 22.5, "&dLern Sprung",
          subtitle="Weiter als jedes Pferd.",
          description=[
              "Am Tisch: &fLuftessenz&r und &e3 Wilden-Flügel&r.",
              "",
              "&eSelbst, Sprung&r schleudert dich nach vorn, Verstärken weiter. &cKein Schutz vor Fallschaden.&r",
          ],
          tasks=[task_item("ars_nouveau:glyph_leap", 1)],
          rewards=[reward_item("minecraft:feather", 8), reward_xp(3)],
          deps=["essences_wild"], icon="ars_nouveau:glyph_leap"),

    quest("glyphs_air", 7.5, 24.5, "&dLern die Luft-Glyphen",
          subtitle="Checkliste Stufe 1: Luft, Abprallen, Farbe.",
          description=[
              "&dRückschlag&r (Luftessenz, 3 Kolben): stößt das Ziel ein Stück weg.",
              "&dStart&r (Luftessenz, 3 Hasenfelle): wirft das Ziel in die Luft.",
              "&dWindstoß&r (Luftessenz, 4 Windkugeln): eine Windkugel am Zielort.",
              "&dPrallen&r (Abschwörungsessenz, 3 Schleimbälle): wer fällt, springt wieder hoch.",
              "&dWololo&r (Abschwörungsessenz, 3 Farbstoffe): färbt Wesen und Blöcke in deiner Zauberfarbe.",
          ],
          tasks=[task_item("ars_nouveau:glyph_gust", 1), task_item("ars_nouveau:glyph_launch", 1),
                 task_item("ars_nouveau:glyph_wind_burst", 1), task_item("ars_nouveau:glyph_bounce", 1),
                 task_item("ars_nouveau:wololo", 1)],
          rewards=[reward_item("minecraft:slime_ball", 4), reward_xp(4)],
          deps=["glyph_leap"], icon="ars_nouveau:glyph_launch"),

    quest("glyphs_conj", 10, 22.5, "&dLern Wölfe und Taschenspielerei",
          subtitle="Checkliste Stufe 1: Beschwörung.",
          description=[
              "&dWölfe beschwören&r (Beschwörungsessenz, 3 Knochen, 4 Wilden-Flügel): zwei Wölfe kämpfen eine Weile mit dir.",
              "&dTaschenspielerei&r (Beschwörungsessenz): ein unsichtbarer Block, der Partikel deiner Zauberfarbe sprüht.",
              "",
              "Beschwörungen geben dir &eBeschwörungskrankheit&r. Bis sie vorbei ist, geht keine zweite.",
          ],
          tasks=[task_item("ars_nouveau:glyph_summon_wolves", 1), task_item("ars_nouveau:glyph_prestidigitation", 1)],
          rewards=[reward_item("minecraft:bone", 8), reward_xp(4)],
          deps=["essences_wild"], icon="ars_nouveau:glyph_summon_wolves"),

    quest("glyphs_elemental", 10, 24.5, "&dLern Funke, Gelände und die Filter",
          subtitle="Ars Elemental: die Glyphen der Stufe 1.",
          description=[
              "&dFunke&r (Luftessenz, Wolle, Eisengitter): Schaden mit Schock, mehr gegen nasse Ziele.",
              "&dGelände beschwören&r (Erdessenz, Erde): setzt Erde, mit Verstärken Bruchstein.",
              "&dFilter&r (Gegenstandsrolle plus ein Item): Untot (Verrottetes Fleisch), Beschworen (Knochen), Luft (Phantomhaut), Wasser (Fisch), Insekt (Spinnenauge). Mit der Verweigern-Rolle gibt es jeden auch umgekehrt.",
          ],
          tasks=[task_item("ars_elemental:glyph_spark", 1), task_item("ars_elemental:glyph_conjure_terrain", 1),
                 task_item("ars_elemental:glyph_undead_filter", 1)],
          rewards=[reward_item("minecraft:iron_bars", 4), reward_xp(4)],
          deps=["glyphs_conj", "parchment"], icon="ars_elemental:glyph_spark", optional=True),

    # ---- Ausrüstung des Verzauberers -------------------------------------------------
    quest("wand", 0, 30, "&6Bau einen Zauberstab",
          subtitle="Ein Zauber, sofort und weit.",
          description=[
              "Im Apparat: &6Archwood-Stamm&r in die Mitte, &e4 Quelljuwelen&r, &e2 Goldbarren&r, &fLuftessenz&r, &6Manipulationsessenz&r auf die Podeste.",
              "",
              "Der &6Zauberstab&r wirkt immer &eProjektil, Beschleunigen&r und dann den Zauber, den du am Tisch ohne eigene Form einschreibst. So umgehst du die Grenze von zehn Glyphen.",
          ],
          tasks=[task_item("ars_nouveau:wand", 1)],
          rewards=[reward_item("ars_nouveau:source_gem", 4), reward_xp(4)],
          deps=["essences_wild", "apparatus"], icon="ars_nouveau:wand"),

    quest("gear_sword", 2.5, 30, "&6Verzaubere Schwert und Schild",
          subtitle="Ein Zauber auf jedem Treffer.",
          description=[
              "&6Schwert des Zauberers&r: Diamantschwert mit Diamant, 2 Goldblöcken, 2 Quelljuwelblöcken. &6Schild des Zauberers&r: Schild mit 2 Goldblöcken, 2 Quelljuwelblöcken.",
              "",
              "Das Schwert wirkt seinen eingeschriebenen Zauber (ohne Form, etwa &eEntzünden, Verstärken&r) bei jedem Treffer. Der Schild gibt beim Blocken Mana-Regeneration und Zauberschaden und repariert sich mit Mana.",
          ],
          tasks=[task_item("ars_nouveau:enchanters_sword", 1), task_item("ars_nouveau:enchanters_shield", 1)],
          rewards=[reward_item("minecraft:gold_block", 1), reward_xp(5)],
          deps=["wand"], icon="ars_nouveau:enchanters_sword", optional=True),

    quest("gear_bow", 5, 30, "&6Verzaubere einen Bogen",
          subtitle="Pfeile, die zaubern.",
          description=[
              "&6Bogen des Zauberers&r: Bogen mit Quelljuwelblock, Goldblock, Manipulationsessenz. Die Armbrust des Zauberers genauso.",
              "",
              "Reicht dein Mana, wird jeder Pfeil zum Zauberpfeil mit dem eingeschriebenen Zauber. In der Kammer machst du &6Verstärkungspfeile&r (Verstärken, Durchschlag, Teilen) für mehr Wirkung.",
          ],
          tasks=[task_item("ars_nouveau:spell_bow", 1)],
          rewards=[reward_item("minecraft:arrow", 32), reward_xp(4)],
          deps=["wand"], icon="ars_nouveau:spell_bow", optional=True),

    quest("gear_tools", 7.5, 30, "&6Bau Handschuh, Angel und Spiegel",
          subtitle="Checkliste: drei Werkzeuge mit eingebautem Zauber.",
          description=[
              "&6Handschuh des Zauberers&r (Leder, Diamant, 2 Goldblöcke, 2 Quelljuwelblöcke): baut bis Diamanthärte ab, zaubert mit Rabatt.",
              "&6Angel des Zauberers&r (Angel, 2 Goldblöcke, 2 Quelljuwelblöcke): wirkt den Zauber auf alles am Haken.",
              "&6Spiegel des Zauberers&r (Quelljuwelblock, 2 Glas, 2 Manipulationsessenzen, 2 Archwood-Stämme, 2 Gold): wirkt einen Selbst-Zauber billiger und länger.",
          ],
          tasks=[task_item("ars_nouveau:enchanters_gauntlet", 1), task_item("ars_nouveau:enchanters_fishing_rod", 1),
                 task_item("ars_nouveau:enchanters_mirror", 1)],
          rewards=[reward_item("ars_nouveau:source_gem_block", 1), reward_xp(5)],
          deps=["wand"], icon="ars_nouveau:enchanters_gauntlet", optional=True),

    quest("gear_belts", 10, 30, "&6Schmied Gürtel, Krone und Ring",
          subtitle="Checkliste: Schmuck für die Reise.",
          description=[
              "&6Gürtel der Levitation&r (Mundaner Gürtel, 4 Gold, 3 Federn, Luftessenz): in der Luft schleichen lässt dich steigen.",
              "&6Ring des Springens&r (Ring des Potenzials, 3 Wilden-Flügel, Luftessenz): Sprünge in der Luft, jeder kostet &e30 Mana&r.",
              "&6Krone des Alchemisten&r (Goldhelm, 3 Glasflaschen): Tränke aus dem Inventar sofort trinken.",
              "Den Mundanen Gürtel machst du aus 3 Leder und einem Quelljuwel.",
          ],
          tasks=[task_item("ars_nouveau:belt_of_levitation", 1), task_item("ars_nouveau:jump_ring", 1),
                 task_item("ars_nouveau:alchemists_crown", 1)],
          rewards=[reward_item("minecraft:feather", 16), reward_xp(5)],
          deps=["wand", "trinkets"], icon="ars_nouveau:belt_of_levitation", optional=True),

    # ---- Helfer -------------------------------------------------------------------------
    quest("dominion_wand", 0, 34, "&6Bau den Dominion-Zauberstab",
          subtitle="Damit sagst du Helfern, was sie tun sollen.",
          description=[
              "Im Apparat: &6Stock&r in die Mitte, &e2 Quelljuwelen&r und &e1 Goldbarren&r auf die Podeste.",
              "",
              pic("ars_nouveau:dominion_wand"),
              "",
              "Erst die Quelle anklicken, dann das Ziel. Schleichend auf einen Helfer setzt ihn zurück.",
          ],
          tasks=[task_item("ars_nouveau:dominion_wand", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 2), reward_xp(3)],
          deps=["apparatus"], icon="ars_nouveau:dominion_wand"),

    quest("starbuncle_token", 0, 36, "&6Füttere einen Sternbunkel",
          subtitle="Ein Goldnugget gegen einen Freund.",
          description=[
              "Halt ein &6Goldnugget&r in der Hand, dann flieht der wilde Sternbunkel nicht. Wirf es ihm hin, er verschwindet und lässt &6Sternbunkel-Scherben&r zurück.",
              "",
              "Sternbunkel leben in bewaldeten Gegenden, oft in Archwood-Wäldern.",
          ],
          tasks=[task_item("ars_nouveau:starbuncle_shards", 1)],
          rewards=[reward_item("minecraft:gold_nugget", 18)],
          deps=["archwood"], icon="ars_nouveau:starbuncle_shards"),

    quest("starbuncle_charm", 2.5, 35, "&d&lRuf deinen eigenen Sternbunkel",
          subtitle="Ein Lieferdienst auf vier Pfoten.",
          description=[
              "Im Apparat: &6Sternbunkel-Scherben&r in die Mitte, &e4 Goldbarren&r auf die Podeste. Den &6Charme&r auf den Boden, und er erscheint.",
              "",
              pic("ars_nouveau:starbuncle_charm"),
              "",
              "Er sammelt Items vom Boden, erntet Quellbeeren und trägt Items von Truhe zu Truhe. Ohne Quelle, ohne Futter. Ein zweiter Charme auf denselben Sternbunkel stapelt ihn: er trägt dann mehrere Stapel.",
          ],
          tasks=[task_item("ars_nouveau:starbuncle_charm", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(8)],
          deps=["dominion_wand", "starbuncle_token"], icon="ars_nouveau:starbuncle_charm", size=1.5, shape="diamond"),

    quest("starbuncle_work", 5, 35, "&dRichte den Sternbunkel ein",
          subtitle="Von der Kammer in die Truhe.",
          description=[
              "&eAbholen:&r mit dem Dominion-Zauberstab erst die Kammer, dann den Sternbunkel. &eAbliefern:&r erst den Sternbunkel, dann die Truhe.",
              "",
              "Er nimmt beliebig viele Quellen und Ziele. Eine &6Gegenstandsrolle&r in seiner Hand oder in einem Rahmen an der Truhe filtert, was er anfasst.",
              "",
              "&eTipp:&r Lass ihn die Juwelen aus allen Kammern in eine Truhe tragen, die bringst du gesammelt zum Obelisken.",
          ],
          tasks=[task_checkmark("Sternbunkel eingerichtet")],
          rewards=[reward_item("minecraft:chest", 2), reward_xp(5)],
          deps=["starbuncle_charm"], icon="ars_nouveau:allow_scroll"),

    quest("drygmy", 7.5, 34, "&6Ruf einen Drygmy",
          subtitle="Beute, ohne dass jemand stirbt.",
          description=[
              "Wirf ein &6Wilden-Horn&r neben einen wilden &dDrygmy&r, er gibt dir &6Drygmy-Scherben&r. Im Apparat mit Fisch, Weizen, Apfel, Karotte, Samen und &e3 Quelljuwelen&r wird daraus der Charme.",
              "",
              "Charme auf &6Bemoosten Bruchstein&r: er wird zum &6Drygmy-Henge&r. Truhe und Quellglas daneben, und der Drygmy erzeugt die Beute der Wesen im Umkreis von &e10 Blöcken&r. Jeder Durchgang kostet &d1 000 Quelle&r, jede Tierart mehr bringt &e2&r Items extra.",
          ],
          tasks=[task_item("ars_nouveau:drygmy_charm", 1)],
          rewards=[reward_item("minecraft:mossy_cobblestone", 4), reward_xp(5)],
          deps=["starbuncle_charm", "wilden"], icon="ars_nouveau:drygmy_charm", optional=True),

    quest("whirlisprig", 7.5, 36, "&6Ruf einen Wirbelzweig",
          subtitle="Ein Naturgeist als Gärtner.",
          description=[
              "Lass einen Baum neben einem wilden &dWirbelzweig&r wachsen, er gibt Scherben. Im Apparat mit Quelljuwel, Mageblütensamen, Magebloom, Diamant, Eichen-, Fichten- und Birkensetzling und Weizensamen wird der Charme daraus.",
              "",
              "Charme auf eine Blume, Truhe direkt daneben, Quelle in der Nähe. Er erzeugt Holz, Feldfrüchte, Samen und Blumen aus allem, was im Umkreis von &e10 Blöcken&r wächst. Vielfalt macht ihn glücklich.",
          ],
          tasks=[task_item("ars_nouveau:whirlisprig_charm", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 8), reward_xp(5)],
          deps=["starbuncle_charm", "magebloom"], icon="ars_nouveau:whirlisprig_charm", optional=True),

    quest("alakarkinos", 10, 35, "&6Ruf einen Alakarkinos",
          subtitle="Ein Krebs, der Sand siebt.",
          description=[
              "Gib einem Alakarkinos am Strand eine &6Töpferscherbe&r, er gibt dir einen Token. Im Apparat mit &6Pinsel&r und &e3 Töpferscherben&r wird daraus der Charme.",
              "",
              "Mit dem Dominion-Zauberstab an eine Truhe binden, Sand oder Kies in 3 Blöcken Umkreis, Quelle daneben. Er siebt die Blöcke und legt Funde aus Archäologie-Beute in die Truhe.",
          ],
          tasks=[task_item("ars_nouveau:alakarkinos_charm", 1)],
          rewards=[reward_item("minecraft:brush", 1), reward_xp(5)],
          deps=["starbuncle_charm"], icon="ars_nouveau:alakarkinos_charm", optional=True),

    # ---- Erweiterungen -------------------------------------------------------------------
    quest("starbuncle_wheel", 0, 40, "&6Bau ein Sternbunkel-Rad",
          subtitle="Ars Creo: Rotationskraft aus einem Hamsterrad.",
          description=[
              "Formlos: &6Sternbunkel-Charme&r und &6Wasserrad&r von Create.",
              "",
              "Im Rad rennt ein Sternbunkel und treibt deine Create-Maschinen an, ganz ohne Wasser. Gut für die erste Andesit-Straße mitten in der Basis.",
          ],
          tasks=[task_item("ars_creo:starbuncle_wheel", 1)],
          rewards=[reward_item("create:andesite_alloy", 8), reward_xp(5)],
          deps=["starbuncle_charm"], icon="ars_creo:starbuncle_wheel", optional=True, section="erweiterungen"),

    quest("advanced_wand", 2.5, 40, "&6Bau den Advanced Dominion Wand",
          subtitle="Ars Additions: viele Verbindungen auf einmal.",
          description=[
              "Im Apparat: &6Dominion-Zauberstab&r, dazu &6Amethystblock&r und &e2 Goldbarren&r.",
              "",
              "Im Auswahlrad stellst du Reihenfolge und Mehrfach-Modus ein. Im Mehrfach-Modus verbindet schleichender Rechtsklick alle zusammenhängenden Blöcke, praktisch für zehn Kammern auf einmal.",
          ],
          tasks=[task_item("ars_additions:advanced_dominion_wand", 1)],
          rewards=[reward_item("minecraft:amethyst_block", 2)],
          deps=["dominion_wand"], icon="ars_additions:advanced_dominion_wand", optional=True, section="erweiterungen"),

    quest("curio_bag", 5, 40, "&6Näh einen Trinkets Pouch",
          subtitle="Ars Elemental: Ordnung für Schmuck und Charmes.",
          description=[
              "Eine &6Truhe&r umgeben von &e8 Magieblütenfasern&r.",
              "",
              "Hält Ringe, Amulette, Charmes und Scherben. Öffnet per Taste aus Hotbar oder Curio-Platz. Mit Lohenstaub wird er ab Stufe 2 zur größeren Spellcaster Bag.",
          ],
          tasks=[task_item("ars_elemental:curio_bag", 1)],
          rewards=[reward_xp(4)],
          deps=["magebloom"], icon="ars_elemental:curio_bag", optional=True, section="erweiterungen"),

    quest("lesser_focus", 7.5, 40, "&6Schleif einen Kleinen Fokus",
          subtitle="Ars Elemental: eine Schule wird stärker.",
          description=[
              "In der Kammer: &6Amethystsplitter&r hinein, &e3 Essenzen&r eines Elements und &e3 Goldbarren&r auf die Podeste, &d5 000 Quelle&r.",
              "",
              "Als Curio verstärkt und verbilligt der Fokus die Glyphen seiner Schule, schwächt aber die anderen Elemente. Der große Fokus kommt mit dem Wilden-Tribut in Stufe 3.",
          ],
          tasks=[task_item("ars_elemental:lesser_earth_focus", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 3), reward_xp(5)],
          deps=["earth_essence"], icon="ars_elemental:lesser_earth_focus", optional=True, section="erweiterungen"),

    quest("charm_water", 10, 40, "&6Füll die ersten Charms",
          subtitle="Ars Additions: Schutz zum Umhängen.",
          description=[
              "Alle im Apparat mit einer &6Glasflasche&r in der Mitte:",
              "&6Charm of Ocean's Breath&r (Kugelfisch, Tintenbeutel, Seetang): Luft unter Wasser.",
              "&6Charm of Featherlight&r (Feder, Phantomhaut): ab 3 Blöcken Fallhöhe sanfter Fall.",
              "&6Charm of Darkvision&r (Laterne, Fackel): Nachtsicht im Dunkeln.",
              "Leere Charms lädt die Imbuement-Kammer mit Quelle wieder auf.",
          ],
          tasks=[task_item("ars_additions:water_breathing_charm", 1), task_item("ars_additions:fall_prevention_charm", 1),
                 task_item("ars_additions:night_vision_charm", 1)],
          rewards=[reward_item("minecraft:glass_bottle", 8), reward_xp(4)],
          deps=["apparatus"], icon="ars_additions:water_breathing_charm", optional=True),

    quest("siren", 12.5, 40, "&6Ruf eine Sirene",
          subtitle="Ars Elemental: ein Angelplatz, der sich selbst befischt.",
          description=[
              "Gib einer wilden &dSirene&r in warmen Meeren eine &6Seegurke&r, sie lässt Token fallen. Im Apparat mit Prismarinsplitter, 3 Fischen und &e3 Quelljuwelen&r wird der Charme daraus.",
              "",
              "Charme auf &6Prismarin&r: es wird zum &6Sirenen-Schrein&r. Er erzeugt langsam Angelbeute gegen Quelle, mehr mit vielen Wassertieren und Pflanzen drumherum.",
          ],
          tasks=[task_item("ars_elemental:siren_charm", 1)],
          rewards=[reward_item("minecraft:prismarine_shard", 8), reward_xp(5)],
          deps=["apparatus"], icon="ars_elemental:siren_charm", optional=True, section="erweiterungen"),

    quest("flashjack", 15, 40, "&6Ruf einen Flashjack",
          subtitle="Ars Elemental: ein Späher für die Basis.",
          description=[
              "Gib einem wilden &dFlashjack&r (Archwood-Wälder, hohe Gipfel) eine &6Flashpine&r. Im Apparat: Token, &e2 Luftessenzen&r, &e2 Goldbarren&r.",
              "",
              "Der Flashjack späht in seinem Revier, markiert Gegner und kann Zaubertürme kapern, um auf sie zu schießen. Flashpine wächst am &6Blitzenden Archwood&r: ein beliebiger Archwood-Setzling mit Luftessenz.",
          ],
          tasks=[task_item("ars_elemental:flashjack_charm", 1)],
          rewards=[reward_item("ars_elemental:yellow_archwood_sapling", 2), reward_xp(5)],
          deps=["essences_wild"], icon="ars_elemental:flashjack_charm", optional=True, section="erweiterungen"),

    # ---- Neu: Nebenquests -------------------------------------------------------------
    quest("berry_food", 11, 7.5, "&6Back Quellbeerkuchen",
          subtitle="Essen mit Mana-Regeneration.",
          description=[
              "&6Quellbeerkuchen&r: formlos &6Ei&r, &6Zucker&r, &6Magebloom&r und &e3 Quellbeeren&r. &6Quellbeerbrötchen&r: formlos &e3 Weizen&r und &e1 Quellbeere&r.",
              "",
              "Wie die Beeren selbst geben beide beim Essen Mana-Regeneration. Vor einem langen Bergbauzauber ein Kuchen, und der Balken füllt sich schneller.",
              "",
              "&eTipp:&r Für den Myzel-Quelllink ist Quellbeer-Essen das beste Futter.",
          ],
          tasks=[task_item("ars_nouveau:source_berry_pie", 2), task_item("ars_nouveau:source_berry_roll", 4)],
          rewards=[reward_item("minecraft:sugar", 8), reward_xp(3)],
          deps=["sourceberry", "magebloom"], icon="ars_nouveau:source_berry_pie", optional=True),

    quest("potion_flask", 5, 20.5, "&6Füll eine Trankflasche",
          subtitle="Acht Schlucke in einer Flasche.",
          description=[
              "Im Apparat: &6Glasflasche&r in die Mitte, &e2 Abschwörungsessenzen&r, &6Quelljuwelblock&r und &6Goldblock&r auf die Podeste.",
              "",
              "Die &6Trankflasche&r hält &d8 Ladungen&r eines Tranks. Gefüllt wird formlos: Flasche und Trank zusammen an die Werkbank. Ab Stufe 2 füllt sie auch ein Trankglas.",
              "",
              "Zwei Abwandlungen im Apparat: mit &e8 Abschwörungsessenzen&r die Flasche &dVerstärken&r (eine Trankstufe mehr, halbe Dauer), mit &e8 Manipulationsessenzen&r &dZeit verlängern&r (&e50 Prozent&r länger).",
          ],
          tasks=[task_item("ars_nouveau:potion_flask", 1)],
          rewards=[reward_item("minecraft:glass_bottle", 8), reward_xp(4)],
          deps=["essences_more"], icon="ars_nouveau:potion_flask", optional=True),

    quest("void_jar", 12.75, 18, "&6Bau ein Glas der Leere",
          subtitle="Bruchstein, der nie im Inventar ankommt.",
          description=[
              "Im Apparat: &6Glasflasche&r in die Mitte, &6Lavaeimer&r, &6Eimer&r, &6Gegenstandsrolle: Erlauben&r und &6Enderperle&r auf die Podeste.",
              "",
              "Liegt das Glas in der &eHotbar&r, vernichtet es beim Aufsammeln die Items auf seiner Liste und gibt dir dafür ein wenig Mana. Schleichend benutzt schaltet es an und aus.",
              "",
              "Items fügst du hinzu, indem du das Glas mit dem Item in der Zweithand benutzt, oder das Glas auf den Tisch des Schreibers legst und das Item daraufklickst.",
          ],
          tasks=[task_item("ars_nouveau:void_jar", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 2), reward_xp(4)],
          deps=["parchment"], icon="ars_nouveau:void_jar", optional=True),

    quest("xp_jar", 15.25, 18, "&6Bau ein Jar of Miner's Wisdom",
          subtitle="Ars Additions: Abfall wird zu Erfahrung.",
          description=[
              "Im Apparat: &6Glasflasche&r in die Mitte, &6Gegenstandsrolle: Erlauben&r, &6Ofen&r, &6Bruchstein&r, &6Kohle&r und &6Lapislazuli&r auf die Podeste.",
              "",
              "Funktioniert wie das Glas der Leere: In der Hotbar vernichtet es die Items auf seiner Liste beim Aufsammeln. Statt Mana gibt es dafür ein wenig &dErfahrung&r.",
              "",
              "&eTipp:&r Bruchstein und Tuffstein auf die Liste, und jeder Bergbauzauber füllt nebenbei den Erfahrungsbalken für den Tisch des Schreibers.",
          ],
          tasks=[task_item("ars_additions:xp_jar", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 4), reward_xp(4)],
          deps=["void_jar"], icon="ars_additions:xp_jar", optional=True),

    quest("codex", 12.75, 19.5, "&6Teil dein Wissen mit dem Kodex",
          subtitle="Glyphen für Freunde, ohne Zutaten.",
          description=[
              "&6Kommentierter Kodex&r: formlos &6Leeres Pergament&r und &6Leder&r.",
              "",
              "Benutz den Kodex, und er schreibt alle Glyphen auf, die du kennst. Das kostet &dErfahrung&r für jede Glyphe. Erneut benutzt bringt er die Liste auf den neuesten Stand.",
              "",
              "Ein anderer Spieler benutzt den Kodex und lernt damit alle Glyphen daraus, die ihm fehlen. Der Kodex wird dabei verbraucht. Ideal für ein Team, in dem einer die Glyphen sammelt.",
          ],
          tasks=[task_item("ars_nouveau:annotated_codex", 1)],
          rewards=[reward_item("minecraft:leather", 4), reward_xp(5)],
          deps=["parchment"], icon="ars_nouveau:annotated_codex", optional=True),

    quest("ring_discount", 15.25, 19.5, "&6Schmied einen Ring des geringeren Rabatts",
          subtitle="Jeder Zauber wird billiger.",
          description=[
              "Im Apparat: &6Ring des Potenzials&r in die Mitte, &e4 Diamanten&r, &e2 Enderperlen&r und &e2 Quelljuwelen&r auf die Podeste.",
              "",
              "Der Ring senkt die Kosten jedes Zaubers und gibt dazu ein wenig mehr Mana und Regeneration.",
              "",
              "Später wird er im Apparat zum &6Ring des größeren Rabatts&r.",
          ],
          tasks=[task_item("ars_nouveau:ring_of_lesser_discount", 1)],
          rewards=[reward_item("minecraft:diamond", 1), reward_table("s1_common")],
          deps=["trinkets"], icon="ars_nouveau:ring_of_lesser_discount"),

    quest("scrying", 7.5, 18, "&6Späh mit dem Hellseher-Kristall",
          subtitle="Eine Kamera für die Basis.",
          description=[
              "&6Hellseher-Kristall&r: formlos &6Enderauge&r und &6Quelljuwel&r. Rechtsklick auf den gesetzten Kristall, und du schaust durch ihn hindurch.",
              "",
              "Ein &6Leeres Pergament&r auf den Kristall gibt eine &6Schriftrolle des Sehers&r mit seinem Ort. Benenn sie am Amboss, dann findest du sie leichter wieder.",
              "",
              "Der &6Seher-Oculus&r (Apparat: Enderauge in die Mitte, Beobachter, Fernrohr, Quelljuwelblock, Diamant) öffnet jeden Kristall, dessen Schriftrolle auf einem Podest daneben liegt. Der Kristall muss dafür geladen sein.",
          ],
          tasks=[task_item("ars_nouveau:scryers_crystal", 1), task_item("ars_nouveau:scryers_oculus", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 2), reward_xp(5)],
          deps=["apparatus"], icon="ars_nouveau:scryers_oculus", optional=True),

    quest("shapers_focus", 5, 24.5, "&6Bau den Fokus der Blockformung",
          subtitle="Wurfgeschosse aus Blöcken.",
          description=[
              "Im Apparat: &6Manipulationsessenz&r in die Mitte, &6Goldbarren&r, &6Kolben&r, &6Schleimblock&r und &6Diamant&r auf die Podeste. Getragen wird er als Curio.",
              "",
              "Mit dem Fokus läuft der Rest des Zaubers auf jedem Block weiter, den ein Effekt erschafft, verändert oder bewegt. &eEinfrieren, Brechen&r friert Wasser ein und baut das Eis gleich ab.",
              "",
              "Bewegte Blöcke verletzen, wen sie treffen. Probier &eProjektil, Magieblock beschwören, Start, Verzögerung, Rückschlag&r: der Block fliegt in deine Blickrichtung.",
          ],
          tasks=[task_item("ars_nouveau:shapers_focus", 1)],
          rewards=[reward_item("minecraft:slime_ball", 4), reward_xp(5)],
          deps=["glyphs_manip"], icon="ars_nouveau:shapers_focus", optional=True),

    quest("filter_scrolls", 5, 37, "&dFilter deine Helfer",
          subtitle="Erlauben, Verweigern, Nachahmen.",
          description=[
              "&6Gegenstandsrolle: Verweigern&r: formlos Leeres Pergament und Bruchstein. &6Mimik-Schriftrolle&r: formlos Gegenstandsrolle: Erlauben und Truhe.",
              "",
              "Items schreibst du ein, indem du die Rolle auf den Tisch des Schreibers legst und schleichend Items daraufklickst. Mit Erlauben nimmt der Sternbunkel nur diese Items, mit Verweigern alles außer diesen.",
              "",
              "Die Mimik-Schriftrolle kommt in einen Rahmen an einer Truhe: dann landen dort nur Items, die schon in der Truhe liegen. So sortiert ein Sternbunkel ein ganzes Lager.",
          ],
          tasks=[task_item("ars_nouveau:deny_scroll", 1), task_item("ars_nouveau:mimic_scroll", 1)],
          rewards=[reward_item("minecraft:item_frame", 4), reward_xp(4)],
          deps=["starbuncle_work"], icon="ars_nouveau:mimic_scroll", optional=True),

    quest("snowstride", 12.5, 41.5, "&6Füll den Charm of Snowstride",
          subtitle="Ars Additions: über Pulverschnee laufen.",
          description=[
              "Im Apparat: &6Glasflasche&r in die Mitte, &6Lederstiefel&r und &6Pulverschneeeimer&r auf die Podeste.",
              "",
              "Mit dem Charm trägt dich Pulverschnee, statt dass du darin versinkst. In verschneiten Bergen und Hainen spart das viel Ärger.",
              "",
              "Wie die anderen Charms lädt ihn die Imbuement-Kammer wieder auf, wenn er leer ist.",
          ],
          tasks=[task_item("ars_additions:powdered_snow_walk_charm", 1)],
          rewards=[reward_item("minecraft:leather", 4), reward_xp(3)],
          deps=["charm_water"], icon="ars_additions:powdered_snow_walk_charm", optional=True),

    # ---- Stufenziel ----------------------------------------------------------------------
    quest("obelisk", 31, 5.5, "&dBring Juwelen zum Obelisken",
          subtitle="Die magische Hälfte von Stufe 1.",
          description=[
              "Rechtsklick mit Juwelen auf den &eObelisken&r an der Spawn, schleichend gibst du alles Passende ab. Eine Truhe daneben wird dein Zulieferer, unterwegs hilft &e/kw deposit&r.",
              "",
              "Die Magie-Säule: &e800 Quelljuwelen&r (angepasst an die Spielerzahl) und &e12 Quellschlusssteine&r. Ein Schlussstein zählt so viel wie gut 60 Juwelen: &e4 Quelljuwelblöcke&r, Quellglas, 2 Manadiamanten aus Botania, Andesitlegierung, Gold Leaf aus Nature's Aura. Rezept im Kapitel &6Hier geht's los&r.",
              "",
              "Behalt einen Vorrat: ab Stufe 2 braucht jeder &6Lohenbrenner&r zwei Quelljuwelen.",
          ],
          tasks=[task_item("ars_nouveau:source_gem", 64)],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["chamber_auto"], icon="ars_nouveau:source_gem", size=1.5, shape="hexagon"),

    quest("mage", 31, 9, "&d&lWerde ein echter Magier",
          subtitle="Quelle fließt, der Apparat steht, der Server wartet.",
          description=[
              "Leg einen Vorrat von &e8 Quelljuwelblöcken&r an.",
              "",
              "Quelllinks füllen Gläser, Kammern machen Juwelen, ein Sternbunkel sammelt ein. Mit &6Stufe 2&r öffnen das &6Zauberbuch des Magiers&r, die Relais, das Ritual-Kohlenbecken und die Zaubertürme. Weiter im Kapitel &dArs Nouveau: Magier&r.",
          ],
          tasks=[task_item("ars_nouveau:source_gem_block", 8)],
          rewards=[reward_table("s1_rare"), reward_xp(15)],
          deps=["obelisk", "starbuncle_work", "beginner_spells", "apparatus"], icon="ars_nouveau:source_gem_block",
          size=2.5, shape="gear"),
]

images = [
    banner("ars_nouveau/title", "Ars Nouveau", 11, -2.4, height=1.8, kind="title", colour="magic"),
    head("grundlagen", "Der erste Zauber", 0, -0.6),
    head("quelle", "Das erste Quelljuwel", 5, 4.0),
    head("glyphen", "Die ersten Glyphen", 0, 9.0),
    head("apparat", "Apparat und Essenzen", 0, 15.0),
    head("glyphen2", "Glyphen mit Essenzen", 0, 21.3),
    head("ausruestung", "Ausrüstung des Verzauberers", 0, 28.5),
    head("helfer", "Helfer", 0, 32.5),
    head("erweiterungen", "Erweiterungen", 0, 38.5),
    banner("ars_nouveau/ziel", "Stufenziel", 31, 3.6, height=0.9, colour="magic"),
]

chapter(C, "Ars Nouveau", "ars_nouveau:novice_spell_book", "magic", quests, shape="circle", order=2,
        subtitle=["Vom ersten Quelljuwel zur ersten Ars-Basis."], images=images)
