"""Ars Nouveau in stage 1: the notebook, archwood, the novice spell book and its glyphs, Source
from the imbuement chamber and the sourcelinks, the enchanting apparatus with its essences, the
Starbuncle and the other small helpers, and the addons whose items are open (Ars Creo, Ars
Additions, Ars Elemental, Ars Technica). Source Gems are the magic half of the stage 1 goal.
The Mage's Spell Book (tier 2 glyphs), relays, the ritual brazier, turrets and warp scrolls are
locked until stage 2 (stage2.json) and live in ars_apprentice.py; tier 3 in stage 3."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table,
                  reward_xp, banner, img, item_texture)

C = "ars_nouveau"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Erste Schritte -----------------------------------------------------
    quest("welcome", 0, 0, "&dArs Nouveau",
          subtitle="Zauber, die du selbst zusammensetzt.",
          description=[
              "Willkommen bei &dArs Nouveau&r! Hier lernst du keine fertigen Zauber, sondern baust sie dir selbst aus &dGlyphen&r zusammen, wie Wörter in einem Satz. Ein Zauber kann eine Spitzhacke ersetzen, eine Fackel, eine Brücke oder ein Schwert.",
              "",
              "Die Energie der Mod heißt &dQuelle&r (Source). Mit ihr laufen alle Ars-Blöcke, und aus ihr entstehen die &6Quelljuwelen&r (Source Gems). Genau die braucht der Server: &e1 500 Quelljuwelen&r sind die magische Hälfte des Ziels von &6Stufe 1&r am Obelisken.",
              "",
              pic("ars_nouveau:worn_notebook"),
              "",
              "Dein Handbuch ist das &6Abgenutzte Notizbuch&r (Tattered Tome). Du bekommst es hier als Belohnung, craften kannst du es jederzeit aus einem Buch und Lapislazuli. Liegt es im Inventar, zeigt dir die linke &eStrg&r-Taste über einem Ars-Block den passenden Eintrag.",
              "",
              "Dieses Kapitel führt dich vom ersten Zauberbuch bis zur Quelljuwel-Farm und zu den kleinen Helfern. Alles mit Stufe 2 und höher (Relais, Rituale, Glyphen der zweiten Stufe) zeigt dir sein Tooltip als gesperrt an und kommt später dran.",
          ],
          tasks=[task_checkmark("Auf geht's")],
          rewards=[reward_item("ars_nouveau:worn_notebook", 1), reward_table("s1_common")],
          icon="ars_nouveau:novice_spell_book", size=2.0, shape="hexagon"),

    quest("book", 2.5, -0.9, "&dZauberbuch für Anfänger",
          subtitle="Vier Eisenwerkzeuge für ein Buch voller Möglichkeiten.",
          description=[
              "Das &6Zauberbuch für Anfänger&r (Novice Spell Book) craftest du formlos aus einem &6Buch&r und je einem &6Eisenschwert&r, einer &6Eisenspitzhacke&r, einer &6Eisenaxt&r und einer &6Eisenschaufel&r. Klingt teuer, aber das Buch ersetzt später genau diese Werkzeuge.",
              "",
              "Im Buch stecken schon deine ersten fünf Glyphen: &dProjektil&r, &dBerühren&r und &dSelbst&r als Formen, dazu &dBrechen&r und &dSchaden&r als Effekte. Damit kannst du sofort Blöcke abbauen und kämpfen.",
              "",
              "Das Anfängerbuch kann nur Glyphen der &eStufe 1&r benutzen. Das &6Zauberbuch des Magiers&r für Stufe 2 öffnet erst mit &6Stufe 2&r des Servers, deine gelernten Glyphen nimmst du dann beim Aufwerten mit.",
          ],
          tasks=[task_item("ars_nouveau:novice_spell_book", 1)],
          rewards=[reward_item("minecraft:lapis_lazuli", 16), reward_xp(5)],
          deps=["welcome"], icon="ars_nouveau:novice_spell_book", size=1.25),

    quest("archwood", 2.5, 1.2, "&6Archwood",
          subtitle="Bunte Wälder, aus denen alles gebaut wird.",
          description=[
              "&6Archwood&r-Bäume wachsen in eigenen Wäldern mit roten, blauen, grünen und violetten Blättern, die du schon von weitem siehst. Fast jeder Ars-Block braucht ihr Holz: der Tisch des Schreibers, die Imbuement-Kammer, das Quellglas.",
              "",
              "Für Bretter ist die Farbe egal, jede Sorte ergibt &6Archwood-Planken&r. Fäll ein paar Bäume, pflanz die Setzlinge zu Hause wieder ein und leg dir einen Vorrat an.",
              "",
              "&eTipp:&r In Archwood-Wäldern leben auch die &dSternbunkel&r (Starbuncles), kleine goldgierige Wesen. Merk dir den Ort, dazu kommen wir weiter unten.",
          ],
          tasks=[task_item("ars_nouveau:archwood_planks", 32)],
          rewards=[reward_item("minecraft:gold_nugget", 18), reward_xp(3)],
          deps=["welcome"], icon="ars_nouveau:green_archwood_log"),

    quest("archwood_colors", 2.5, 3.0, "&6Vier Farben Archwood",
          subtitle="Jede Farbe hat ihre eigene Aufgabe.",
          description=[
              "Die vier Sorten sehen nicht nur anders aus, sie werden später für verschiedene Dinge gebraucht:",
              "",
              "&cFlammend&r (rot): der beste Brennstoff für den &6Vulkanischen Quelllink&r.",
              "&bKaskadierend&r (blau): Rituale rund um Wasser und Wetter.",
              "&aBlühend&r (grün): Rituale für Ernte und Wachstum.",
              "&5Ärgerlich&r (violett): Rituale für Suche und Bindung.",
              "",
              "Rituale gibt es zwar erst ab &6Stufe 2&r, aber ein kleiner Garten mit allen vier Sorten spart dir dann viel Lauferei. Sammle von jeder Farbe einen Setzling.",
          ],
          tasks=[task_item("ars_nouveau:red_archwood_sapling", 1), task_item("ars_nouveau:blue_archwood_sapling", 1),
                 task_item("ars_nouveau:green_archwood_sapling", 1), task_item("ars_nouveau:purple_archwood_sapling", 1)],
          rewards=[reward_item("minecraft:bone_meal", 32)],
          deps=["archwood"], icon="ars_nouveau:red_archwood_sapling", optional=True),

    quest("mana", 4.5, -0.9, "&dMana",
          subtitle="Der blaue Balken unten links.",
          description=[
              "Sobald du ein Zauberbuch trägst, siehst du unten links deinen &dManabalken&r. Jeder Zauber kostet Mana, und zwar die Summe aller Glyphen, aus denen er besteht. Ein langer Zauber mit vielen Verstärkungen ist also teurer als ein kurzer.",
              "",
              "Mana lädt sich von selbst wieder auf. Wie viel du maximal hast und wie schnell es zurückkommt, hängt von mehreren Dingen ab:",
              "",
              "&e1.&r Jede Glyphe, die du lernst, erhöht beide Werte ein kleines Stück.",
              "&e2.&r Ein besseres Zauberbuch hebt beide deutlich an.",
              "&e3.&r Schmuck wie der &6Ring des Potenzials&r und die Amulette aus dem Apparat helfen weiter.",
              "",
              "&eTipp:&r Glyphen zu lernen lohnt sich also doppelt, auch welche, die du selten benutzt.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["book"], icon="minecraft:lapis_lazuli"),

    quest("spell_theory", 6.5, -0.9, "&dAufbau eines Zaubers",
          subtitle="Form, Effekt, Verstärkung.",
          description=[
              "Jeder Zauber ist eine Reihe von Glyphen, die von links nach rechts gelesen wird:",
              "",
              "&aForm&r (immer zuerst, genau eine): wie der Zauber gewirkt wird. &dProjektil&r schießt eine Kugel, &dBerühren&r wirkt auf den Block oder das Wesen direkt vor dir, &dSelbst&r wirkt auf dich.",
              "",
              "&aEffekt&r (einer oder mehrere): was passiert. &dBrechen&r baut ab, &dSchaden&r verletzt, später kommen Licht, Ernte, Sprung und viele mehr dazu.",
              "",
              "&aVerstärkung&r (Augment, hinter einer Form oder einem Effekt): verändert das Glied links davon. &dVerstärken&r macht den Effekt stärker, auf Stufe 2 kommen Fläche, Dauer und Durchschlag dazu.",
              "",
              "Mehrere Effekte hintereinander wirken nacheinander am selben Ziel. So wird aus &eProjektil, Brechen, Artikel aufheben&r ein Zauber, der abbaut und die Beute direkt in dein Inventar legt.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["mana"], icon="ars_nouveau:blank_glyph"),

    quest("first_spell", 8.5, -0.9, "&dDein erster Zauber",
          subtitle="C drücken, Glyphen klicken, benennen, fertig.",
          description=[
              "Nimm das Zauberbuch in die Hand und drück &eC&r. Links siehst du deine Glyphen, oben die Zeile für den Zauber. Klick &dProjektil&r und dann &dBrechen&r an, gib dem Zauber einen Namen und speichere ihn.",
              "",
              "Mit Rechtsklick wirkst du den gerade gewählten Zauber. Das Buch hat zehn Plätze: mit &eV&r öffnest du das Auswahlrad, mit &eX&r und &eZ&r blätterst du vor und zurück. Auf der zweiten Seite des Buchs kannst du Farbe und Partikel deines Zaubers einstellen.",
              "",
              "&eTipp:&r Bau dir gleich zwei Zauber, einen zum Abbauen (Projektil, Brechen) und einen für den Kampf (Projektil, Schaden). Beide funktionieren sofort und kosten kaum Mana.",
              "",
              "&cAchtung:&r Brechen ohne Verstärkung schafft nur Blöcke mittlerer Härte. Für härtere Erze brauchst du die Glyphe &dVerstärken&r dahinter.",
          ],
          tasks=[task_checkmark("Zauber gewirkt")],
          rewards=[reward_item("minecraft:experience_bottle", 8), reward_table("s1_common")],
          deps=["spell_theory"], icon="ars_nouveau:glyph_projectile", size=1.5, shape="diamond"),

    # ---- Glyphen ---------------------------------------------------------------
    quest("scribes_table", 10.8, 0, "&aTisch des Schreibers",
          subtitle="Hier entstehen neue Glyphen.",
          description=[
              "Der &6Tisch des Schreibers&r (Scribe's Table) braucht oben &e3 Archwood-Stufen&r, in der Mitte links und rechts &e2 Goldnuggets&r und unten links und rechts &e2 Archwood-Stämme&r. Er ist zwei Blöcke breit.",
              "",
              "Klick den Tisch mit deinem Zauberbuch an. Es öffnet sich eine Liste aller Glyphen, die dein Buch lernen kann. Wähl eine aus und drück &eAuswählen&r. Über dem Tisch schweben dann die Zutaten, die er haben will: wirf sie mit &eQ&r auf den Tisch. Er zieht auch Zutaten aus Truhen direkt daneben.",
              "",
              "Jede Glyphe kostet zusätzlich Erfahrung: Stufe 1 kostet &e27 Erfahrungspunkte&r, das sind knapp &e3 Level&r. Stufe 2 kostet 55 Punkte, Stufe 3 sogar 160.",
              "",
              "Die fertige Glyphe fällt als Item heraus. Rechtsklick damit, und du hast sie für immer gelernt.",
          ],
          tasks=[task_item("ars_nouveau:scribes_table", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 16)],
          deps=["first_spell", "archwood"], icon="ars_nouveau:scribes_table", size=1.5, shape="square"),

    quest("glyph_light", 12.8, -1, "&dMagielicht beschwören",
          subtitle="Nie wieder Fackeln schleppen.",
          description=[
              "Deine erste eigene Glyphe braucht nur eine &6Laterne&r und eine &6Fackel&r. &dMagielicht beschwören&r (Conjure Magelight) setzt ein schwebendes Licht an die Stelle, die der Zauber trifft.",
              "",
              "&eProjektil, Magielicht beschwören&r ist der klassische Höhlenzauber: ein Klick an die Wand, und der Gang ist hell. Mit &eSelbst, Magielicht beschwören&r bekommst du kurz Nachtsicht.",
              "",
              "&eTipp:&r Das Licht bleibt dauerhaft stehen, mit &dVerstärken&r leuchtet es so hell wie Glowstone. Zauber es in Minen großzügig an die Decke, dann spawnen dort keine Monster mehr.",
          ],
          tasks=[task_item("ars_nouveau:glyph_light", 1)],
          rewards=[reward_item("minecraft:torch", 32), reward_xp(3)],
          deps=["scribes_table"], icon="ars_nouveau:glyph_light"),

    quest("glyph_amplify", 12.8, 1, "&dVerstärken",
          subtitle="Mehr Kraft für den Effekt links davon.",
          description=[
              "&dVerstärken&r (Amplify) ist die wichtigste Verstärkung der ersten Stufe. Du bezahlst sie mit einer &6Diamantspitzhacke&r, es lohnt sich.",
              "",
              "Hinter &dSchaden&r macht jedes Verstärken mehr Schaden. Hinter &dBrechen&r hebt jedes Verstärken die Abbaustufe um eins, für sehr harte Blöcke wie Obsidian brauchst du mehrere. Hinter &dMagielicht&r wird das Licht heller, hinter &dMagieblock&r bleibt der Block für immer stehen. Du kannst eine Verstärkung mehrmals hintereinander setzen.",
              "",
              "&cAchtung:&r Jede Verstärkung kostet zusätzlich Mana. Mach dir lieber zwei Abbauzauber, einen billigen für Stein und einen verstärkten für Erze.",
          ],
          tasks=[task_item("ars_nouveau:glyph_amplify", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(3)],
          deps=["scribes_table"], icon="ars_nouveau:glyph_amplify"),

    quest("glyph_pickup", 14.8, -1, "&dArtikelabholung",
          subtitle="Die Beute landet gleich im Inventar.",
          description=[
              "&dArtikelabholung&r (Item Pickup) kostet nur zwei &6Trichter&r. Der Effekt sammelt alle Items am Zielort ein und legt sie dir ins Inventar.",
              "",
              "Setz die Glyphe &ehinter&r den Effekt, der die Items erzeugt: &eProjektil, Brechen, Artikelabholung&r baut ab und sammelt ein. Steht sie davor, gibt es noch nichts einzusammeln.",
              "",
              "&eTipp:&r Das spart beim Graben in Schluchten oder unter Wasser viel Ärger, weil nichts mehr davonrollt oder in Lava fällt.",
          ],
          tasks=[task_item("ars_nouveau:glyph_pickup", 1)],
          rewards=[reward_item("minecraft:hopper", 1), reward_xp(3)],
          deps=["glyph_light", "glyph_amplify"], icon="ars_nouveau:glyph_pickup"),

    quest("glyph_phantom_block", 14.8, 1, "&dMagieblock beschwören",
          subtitle="Eine Brücke aus dem Nichts.",
          description=[
              "&dMagieblock beschwören&r (Conjure Mageblock) braucht acht &6Glasblöcke&r. Der Zauber setzt einen leuchtenden Block an die getroffene Stelle, der nach kurzer Zeit wieder verschwindet. Mit &dVerstärken&r dahinter bleibt er dauerhaft stehen, Zerstreuen löst ihn sofort auf.",
              "",
              "&eProjektil, Magieblock beschwören&r baut dir eine Stufe an jede Wand, &eBerühren, Magieblock beschwören&r setzt einen Block direkt vor dir. So kommst du über Schluchten, aus Löchern heraus und an hohe Erze.",
              "",
              "&eTipp:&r Magieblöcke leuchten in der Farbe, die du deinem Zauber im Buch gibst. Such dir eine eigene Farbe aus, dann erkennen andere deine Brücken.",
          ],
          tasks=[task_item("ars_nouveau:glyph_phantom_block", 1)],
          rewards=[reward_item("minecraft:glass", 16), reward_xp(3)],
          deps=["glyph_light", "glyph_amplify"], icon="ars_nouveau:glyph_phantom_block"),

    quest("beginner_spells", 16.8, 0, "&dZauber für jeden Tag",
          subtitle="Ein Buch voller nützlicher Sprüche.",
          description=[
              "Mit den ersten Glyphen lassen sich schon richtig gute Zauber bauen. Ein paar Ideen für deine zehn Plätze:",
              "",
              "&eBergbau:&r Projektil, Brechen, Verstärken, Artikelabholung.",
              "&eHöhlenlicht:&r Projektil, Magielicht beschwören.",
              "&eBrückenbau:&r Projektil, Magieblock beschwören.",
              "&eNahkampf:&r Berühren, Schaden, Verstärken, Verstärken.",
              "&eFernkampf:&r Projektil, Schaden, Verstärken.",
              "&eFeldarbeit:&r Berühren, Ernte (sobald du die Glyphe hast).",
              "",
              "Die Reihenfolge zählt: eine Verstärkung wirkt immer auf das Glied direkt links von ihr. Wenn ein Zauber nicht tut, was er soll, schau zuerst dort.",
              "",
              "Mit &6Stufe 2&r kommen Fläche (AOE), Durchschlag und Glück dazu. Dann wird aus dem Bergbauzauber ein Tunnelbohrer.",
          ],
          tasks=[task_checkmark("Zauberbuch gefüllt")],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["glyph_pickup", "glyph_phantom_block"], icon="ars_nouveau:novice_spell_book", size=1.5, shape="diamond"),

    # ---- Quelle ----------------------------------------------------------------
    quest("imbuement", 0.5, 6.5, "&aImbuement-Kammer",
          subtitle="Der einzige Weg zu Quelljuwelen.",
          description=[
              "Die &6Imbuement-Kammer&r ist das Herz jeder Ars-Basis. Du craftest sie aus &e6 Archwood-Planken&r und &e2 Goldbarren&r (Gold oben und unten in der Mitte, die Mitte bleibt leer).",
              "",
              "Leg ein &6Amethystsplitter&r oder ein &6Lapislazuli&r hinein, und die Kammer tränkt es mit Quelle, bis ein &6Quelljuwel&r daraus wird. Das kostet &d500 Quelle&r pro Juwel. Ein &6Amethystblock&r wird für &d2 000 Quelle&r direkt zu einem Quelljuwelblock.",
              "",
              "Allein sammelt die Kammer ihre Quelle nur sehr langsam. Steht ein gefülltes &6Quellglas&r höchstens &ezwei Blöcke&r entfernt, zieht sie die Quelle daraus und arbeitet viel schneller.",
              "",
              "&eTipp:&r Die Kammer ist ein normales Inventar. Ein Trichter darunter holt die fertigen Juwelen heraus, einer darüber füllt Amethyst nach. So läuft sie ohne dich.",
          ],
          tasks=[task_item("ars_nouveau:imbuement_chamber", 1)],
          rewards=[reward_item("minecraft:amethyst_shard", 32), reward_item("minecraft:gold_ingot", 4)],
          deps=["archwood"], icon="ars_nouveau:imbuement_chamber", size=1.75, shape="square"),

    quest("source_gems", 2.7, 6.5, "&dQuelljuwelen",
          subtitle="Die Währung der Magie.",
          description=[
              "&6Quelljuwelen&r (Source Gems) stecken in fast jedem Ars-Rezept: in Quellstein, im Apparat, in allen Quelllinks und in jedem Schmuckstück.",
              "",
              pic("ars_nouveau:source_gem"),
              "",
              "Amethyst findest du in &eGeoden&r unter der Erde, auch reichlich in der Bergbau-Dimension. Nimm die Cluster mit, und wenn du eine Spitzhacke mit Behutsamkeit hast, kannst du Amethystblöcke mitnehmen. &6Knospender Amethyst&r lässt sich nicht bewegen, aber du kannst neben einer Geode eine kleine Außenstelle bauen.",
              "",
              "Juwelen, die du nicht selbst brauchst, gehören in den &eObelisken&r an der Spawn: &e1 500&r braucht der ganze Server für Stufe 2. Das ist die magische Hälfte des Ziels.",
          ],
          tasks=[task_item("ars_nouveau:source_gem", 16)],
          rewards=[reward_item("minecraft:amethyst_shard", 16), reward_table("s1_common")],
          deps=["imbuement"], icon="ars_nouveau:source_gem"),

    quest("source_jar", 4.7, 6.5, "&aQuellglas",
          subtitle="Der Speicher für deine Quelle.",
          description=[
              "Ein &6Quellglas&r (Source Jar) wird aus &e6 Archwood-Stufen&r und &e2 Glas&r gecraftet und hält bis zu &d10 000 Quelle&r. Quelllinks füllen die Gläser in ihrer Nähe, Maschinen wie die Imbuement-Kammer und der Apparat bedienen sich daraus.",
              "",
              "Du siehst am Füllstand, wie viel drin ist. Ein Komparator daneben gibt ein Redstone-Signal passend zur Füllung, gut für eine kleine Anzeige.",
              "",
              "Quelle bewegen kannst du auf Stufe 1 nur, indem du ein Glas abbaust und woanders hinstellst, es behält seinen Inhalt. Die &6Quellrelais&r für längere Strecken kommen mit &6Stufe 2&r.",
              "",
              "&eTipp:&r Bau Gläser, Quelllinks und Kammern eng zusammen. Quelllinks füllen Gläser bis &efünf Blöcke&r weit, die Kammer greift nur zwei Blöcke weit.",
          ],
          tasks=[task_item("ars_nouveau:source_jar", 2)],
          rewards=[reward_item("minecraft:glass", 16)],
          deps=["source_gems"], icon="ars_nouveau:source_jar"),

    quest("volcanic", 6.7, 5.6, "&aVulkanischer Quelllink",
          subtitle="Holz rein, Quelle raus.",
          description=[
              "Der &6Vulkanische Quelllink&r entsteht aus &e2 Quelljuwelen&r, &e2 Goldbarren&r und einem &6Lavaeimer&r. Er verbrennt alles, was brennt, und macht daraus Quelle für die Gläser in der Nähe.",
              "",
              "Wirf Brennstoff daneben auf den Boden oder leg ihn auf &6Arkane Podeste&r daneben. Archwood-Stämme geben einen Bonus, &cFlammendes Archwood&r den größten. Eine kleine Archwood-Baumfarm macht ihn zur zuverlässigsten Quelle am Anfang.",
              "",
              "&cAchtung:&r Der Link wird heiß. Stein um ihn herum wird mit der Zeit zu Magmablock und dann zu Lava. Stell ihn nicht mitten in dein Holzhaus.",
          ],
          tasks=[task_item("ars_nouveau:volcanic_sourcelink", 1)],
          rewards=[reward_item("ars_nouveau:red_archwood_log", 16)],
          deps=["source_jar"], icon="ars_nouveau:volcanic_sourcelink"),

    quest("agronomic", 6.7, 7.4, "&aAgronomischer Quellenlink",
          subtitle="Wachsende Pflanzen erzeugen Quelle.",
          description=[
              "Gleiches Rezept wie der vulkanische, nur mit &6Weizen&r statt Lava. Jede Pflanze und jeder Baum, der im Umkreis von &e15 Blöcken&r wächst, bringt Quelle.",
              "",
              "Magische Pflanzen geben mehr: Magieblüten, Quellbeeren und Archwood-Setzlinge. Ein Beet aus Mageblooms neben einer Archwood-Baumschule ist eine gute, ruhige Quelle.",
              "",
              "&cAchtung:&r Knochenmehl zählt nicht. Die Pflanzen müssen von selbst wachsen.",
          ],
          tasks=[task_item("ars_nouveau:agronomic_sourcelink", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 32)],
          deps=["source_jar"], icon="ars_nouveau:agronomic_sourcelink", optional=True),

    quest("mycelial", 8.7, 5.6, "&aMyzel-Quellenlink",
          subtitle="Essen wird zu Quelle.",
          description=[
              "Mit einer &6Pilzsuppe&r in der Mitte des Rezepts wird der Link zum &6Myzel-Quellenlink&r. Er verzehrt Nahrung in der Nähe und macht daraus Quelle, nahrhaftes Essen gibt mehr, Quellbeeren-Gerichte besonders viel.",
              "",
              "Er verwandelt Gras und Erde unter sich in Myzel und lässt Pilze sprießen. Wie der vulkanische nimmt er Items auch von Podesten daneben.",
              "",
              "&eTipp:&r Mit einer Farm aus Farmer's Delight daneben hast du hier eine sehr bequeme Quelle.",
          ],
          tasks=[task_item("ars_nouveau:mycelial_sourcelink", 1)],
          rewards=[reward_item("minecraft:mushroom_stew", 4)],
          deps=["volcanic"], icon="ars_nouveau:mycelial_sourcelink", optional=True),

    quest("vitalic", 8.7, 7.4, "&aVitalic Sourcelink",
          subtitle="Leben und Tod bringen Quelle.",
          description=[
              "Mit einer &6Glitzernden Melonenscheibe&r im Rezept entsteht der &6Vitalic Sourcelink&r. Er erzeugt Quelle, wenn in der Nähe Tiere gezüchtet werden oder Wesen sterben, und dazu ein wenig von allein, solange Tierbabys in der Nähe sind. Die lässt er außerdem schneller wachsen.",
              "",
              "&eTipp:&r Neben einer Kuh- oder Hühnerfarm, die du ohnehin betreibst, arbeitet er ganz nebenbei mit.",
          ],
          tasks=[task_item("ars_nouveau:vitalic_sourcelink", 1)],
          rewards=[reward_item("minecraft:wheat", 16)],
          deps=["agronomic"], icon="ars_nouveau:vitalic_sourcelink", optional=True),

    quest("dowsing", 2.7, 8.5, "&6Wünschelrute",
          subtitle="Amethyst durch Wände sehen.",
          description=[
              "Die &6Wünschelrute&r craftest du aus einem &6Goldbarren&r und zwei &6Archwood-Planken&r. Benutzt du sie, siehst du für eine Weile magische Wesen in der Nähe und Amethyst durch Stein hindurch.",
              "",
              "Genau das Richtige vor einer Tour in die Bergbau-Dimension: du findest Geoden, ohne blind zu graben. Jede Nutzung kostet etwas Haltbarkeit.",
          ],
          tasks=[task_item("ars_nouveau:dowsing_rod", 1)],
          rewards=[reward_item("minecraft:amethyst_shard", 16)],
          deps=["source_gems"], icon="ars_nouveau:dowsing_rod", optional=True),

    quest("sourceberry", 4.7, 8.5, "&6Quellbeere",
          subtitle="Süß, blau und voller Magie.",
          description=[
              "&6Quellbeeren&r wachsen wild an Büschen in Archwood-Wäldern. Pflanz sie zu Hause an, sie wachsen wie Süßbeeren.",
              "",
              "Gegessen geben sie dir kurz schnellere Mana-Regeneration. Als Kuchen oder Brötchen verarbeitet sind sie der beste Brennstoff für den Myzel-Quellenlink, und neben dem Agronomischen Link zählen sie als magische Pflanze. Sternbunkel ernten reife Büsche übrigens von selbst.",
          ],
          tasks=[task_item("ars_nouveau:sourceberry_bush", 8)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["source_jar"], icon="ars_nouveau:sourceberry_bush", optional=True),

    # ---- Apparat und Essenzen --------------------------------------------------
    quest("sourcestone", 11, 6.5, "&6Quellstein",
          subtitle="Stein mit einem Juwel darin.",
          description=[
              "&e8 Stein&r (jede Sorte) um &e1 Quelljuwel&r ergeben &e8 Quellstein&r (Sourcestone). Er ist die Grundlage für Podeste, den Arkanen Kern und den Apparat.",
              "",
              "Quellstein gibt es in vielen Varianten für den Steinmetz: glatt, gemustert, vergoldet, als Mosaik oder Korbgeflecht. Ein Magierturm aus Quellstein sieht einfach richtig aus.",
          ],
          tasks=[task_item("ars_nouveau:sourcestone", 16)],
          rewards=[reward_item("minecraft:gold_ingot", 8)],
          deps=["source_jar"], icon="ars_nouveau:sourcestone"),

    quest("pedestals", 13, 6.5, "&aArkane Podeste",
          subtitle="Kleine Tische für Zutaten.",
          description=[
              "Ein &6Arkanes Podest&r entsteht aus &e4 Quellstein&r, &e1 Quelljuwel&r und &e4 Goldnuggets&r. Du brauchst davon einige: für den Apparat, für Essenzen an der Imbuement-Kammer und später für Rituale.",
              "",
              "Rechtsklick legt ein Item auf das Podest, Rechtsklick mit leerer Hand nimmt es wieder herunter. Es liegt dort nur, es wird nicht verbraucht, bis ein Rezept startet.",
              "",
              "&eTipp:&r Bau gleich acht. Die großen Apparat-Rezepte brauchen bis zu acht Zutaten gleichzeitig.",
          ],
          tasks=[task_item("ars_nouveau:arcane_pedestal", 4)],
          rewards=[reward_item("minecraft:gold_nugget", 27)],
          deps=["sourcestone"], icon="ars_nouveau:arcane_pedestal"),

    quest("apparatus", 15.2, 6.5, "&aBezaubernder Apparat",
          subtitle="Der Werktisch der Magier.",
          description=[
              "Der &6Bezaubernde Apparat&r (Enchanting Apparatus) ist ein kleiner Aufbau aus drei Teilen:",
              "",
              "&e1.&r Unten ein &6Arkaner Kern&r (6 Quellstein, 2 Goldbarren, 1 Quelljuwel).",
              "&e2.&r Direkt darauf der &6Apparat&r selbst (Quellstein, Gold, Goldnuggets und ein Diamant).",
              "&e3.&r Im Umkreis von &edrei Blöcken&r deine &6Arkanen Podeste&r.",
              "",
              "Leg die Nebenzutaten auf die Podeste und klick dann mit der Hauptzutat auf den Apparat. Er zieht die Quelle aus Gläsern in der Nähe, die Podeste leeren sich und das Ergebnis schwebt über dem Apparat.",
              "",
              "Hier entstehen Dominion-Zauberstab, Sternbunkel-Charme, Magieblütensamen, Amulette und Ringe. Der Apparat kann außerdem Werkzeuge direkt verzaubern, ganz ohne Zaubertisch: JEI zeigt dir die Rezepte.",
          ],
          tasks=[task_item("ars_nouveau:enchanting_apparatus", 1), task_item("ars_nouveau:arcane_core", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["pedestals"], icon="ars_nouveau:enchanting_apparatus", size=1.75, shape="square"),

    quest("earth_essence", 13, 8.6, "&dErdessenz",
          subtitle="Die Kammer kann mehr als Juwelen.",
          description=[
              "Stell &6Arkane Podeste&r direkt neben die &6Imbuement-Kammer&r (im Umkreis von einem Block) und leg ein Quelljuwel in die Kammer. Liegen die richtigen Zutaten auf den Podesten, wird aus dem Juwel eine &dEssenz&r.",
              "",
              pic("ars_nouveau:earth_essence"),
              "",
              "Für die &6Erdessenz&r brauchst du auf den Podesten einen &6Eisenbarren&r, &6Samen&r und &6Erde&r. Die Podest-Items werden dabei nicht verbraucht, du kannst also Essenz um Essenz herstellen. Jede kostet &d2 000 Quelle&r.",
              "",
              "Erdessenz steckt in Glyphen wie &dErnte&r und &dFällen&r und in vielen Ritualen.",
          ],
          tasks=[task_item("ars_nouveau:earth_essence", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 8)],
          deps=["pedestals", "imbuement"], icon="ars_nouveau:earth_essence"),

    quest("manipulation_essence", 15.2, 8.6, "&dManipulationsessenz",
          subtitle="Knopf, Redstone, Uhr.",
          description=[
              "Die &6Manipulationsessenz&r entsteht genauso in der Imbuement-Kammer, mit einem &6Steinknopf&r, &6Redstone&r und einer &6Uhr&r auf den Podesten.",
              "",
              "Sie ist die vielseitigste Essenz: Glyphen wie &dBlock platzieren&r, &dInteragieren&r, &dDrehen&r und &dVerzögerung&r brauchen sie, dazu die &6Runenkreide&r und später viele Relais und Rituale.",
              "",
              "&eTipp:&r Auf ein Juwel in der Kammer mit Manipulationsessenz auf dem Podest lassen sich auch Blöcke umwandeln, etwa Stein in Diorit oder Andesit. JEI zeigt dir alle Varianten.",
          ],
          tasks=[task_item("ars_nouveau:manipulation_essence", 2)],
          rewards=[reward_item("minecraft:redstone", 16)],
          deps=["pedestals", "imbuement"], icon="ars_nouveau:manipulation_essence"),

    quest("essences_more", 17.2, 8.6, "&dDrei weitere Essenzen",
          subtitle="Wasser, Feuer und Abschwörung.",
          description=[
              "Auf dieselbe Weise entstehen die anderen Essenzen, jeweils mit drei Zutaten auf den Podesten:",
              "",
              "&bWasseressenz&r: Wassereimer, Schneeblock, Seetang.",
              "&cFeueressenz&r: Feuerzeug, Fackel, Schwarzpulver.",
              "&5Abschwörungsessenz&r: fermentiertes Spinnenauge, Zucker, Milcheimer.",
              "",
              "Dazu kommen noch die &fLuftessenz&r (Feder, Pfeil und ein Wilden-Flügel) und die &dBeschwörungsessenz&r (Buch, Wilden-Horn und Sternbunkel-Scherben). Für die beiden musst du erst einen Wilden erlegen.",
              "",
              "&eTipp:&r Stell zwei, drei Kammern mit festen Podest-Sätzen auf, dann tauschst du nur noch das Juwel.",
          ],
          tasks=[task_item("ars_nouveau:water_essence", 1), task_item("ars_nouveau:fire_essence", 1),
                 task_item("ars_nouveau:abjuration_essence", 1)],
          rewards=[reward_item("minecraft:amethyst_shard", 24), reward_xp(5)],
          deps=["earth_essence"], icon="ars_nouveau:water_essence", optional=True),

    quest("wilden", 19.2, 8.6, "&cDie Wilden",
          subtitle="Horn, Flügel, Stachel.",
          description=[
              "Die &cWilden&r sind die Monster von Ars Nouveau: der Jäger, der Pirscher und der Wächter. Sie tauchen in Wäldern und Bergen auf und sind stärker als ein Zombie, also geh nicht ohne Rüstung los.",
              "",
              "Sie lassen &6Wilden-Horn&r, &6Wilden-Flügel&r und &6Wilden-Stachel&r fallen. Der Flügel steckt in der Luftessenz und der Glyphe &dSprung&r, das Horn in der Beschwörungsessenz und hilft dir, einen Drygmy anzulocken, der Stachel wird auf Stufe 2 für &dDurchschlag&r gebraucht.",
          ],
          tasks=[task_item("ars_nouveau:wilden_horn", 1), task_item("ars_nouveau:wilden_wing", 1),
                 task_item("ars_nouveau:wilden_spike", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["earth_essence"], icon="ars_nouveau:wilden_horn", optional=True),

    quest("magebloom", 17.2, 5.6, "&6Magieblüte",
          subtitle="Der Stoff, aus dem Magier sind.",
          description=[
              "Leg einen beliebigen &6Samen&r in den Apparat und &e4 Quelljuwelen&r auf die Podeste, dann bekommst du &6Mageblütensamen&r. Gepflanzt wachsen sie auf Ackerland zu &6Magebloom&r heran.",
              "",
              "Aus einer Blüte craftest du eine &6Magieblütenfaser&r. Die Faser brauchst du für Pergament, Runenkreide, Betten für Sternbunkel und den Trinkets-Beutel. Die Magierroben aus Faser öffnen mit Stufe 3.",
              "",
              "&eTipp:&r Mageblooms neben einem &6Agronomischen Quellenlink&r bringen beim Wachsen extra viel Quelle.",
          ],
          tasks=[task_item("ars_nouveau:magebloom_fiber", 8)],
          rewards=[reward_item("minecraft:bone_meal", 32)],
          deps=["apparatus"], icon="ars_nouveau:magebloom"),

    quest("parchment", 19.2, 5.6, "&6Zauberpergament",
          subtitle="Ein Zauber zum Mitnehmen.",
          description=[
              "Ein &6Leeres Pergament&r craftest du aus &e1 Papier&r und &e8 Magieblütenfasern&r. Leg es auf den Tisch des Schreibers, wähl im Zauberbuch den Zauber, den du kopieren willst, und klick den Tisch schleichend mit dem Buch an. Schon ist das Pergament beschrieben.",
              "",
              "Beschriebene Pergamente brauchst du für &6Zaubertürme&r und &6Runen&r. Mit der Glyphe &dRune&r und &6Runenkreide&r zeichnest du Fallen auf den Boden, die ihren Zauber auf alles wirken, was darüber läuft.",
          ],
          tasks=[task_item("ars_nouveau:spell_parchment", 1)],
          rewards=[reward_item("minecraft:paper", 16), reward_xp(3)],
          deps=["magebloom"], icon="ars_nouveau:spell_parchment", optional=True),

    quest("trinkets", 19.2, 7.1, "&6Ring des Potenzials",
          subtitle="Mehr Mana am Finger.",
          description=[
              "Der &6Ring des Potenzials&r ist schlicht: &e8 Eisennuggets&r um &e1 Quelljuwel&r. Als Curio getragen erhöht er dein maximales Mana ein Stück.",
              "",
              "Aus demselben Rezept, nur mit Nuggets im Kreuz, entsteht das &6Langweilige Schmuckstück&r (Dull Trinket). Das ist die Basis für die Amulette aus dem Apparat.",
          ],
          tasks=[task_item("ars_nouveau:ring_of_potential", 1)],
          rewards=[reward_item("minecraft:iron_nugget", 16), reward_xp(3)],
          deps=["apparatus"], icon="ars_nouveau:ring_of_potential"),

    quest("amulet", 21.2, 7.1, "&6Amulett des Mana-Boosts",
          subtitle="Noch mehr Mana, oder schneller zurück.",
          description=[
              "Leg das &6Langweilige Schmuckstück&r in den Apparat. Mit &e3 Diamanten&r und &e5 Quelljuwelen&r auf den Podesten wird daraus das &6Amulett des Mana-Boosts&r, mit &e2 Diamanten, 2 Goldbarren und 4 Quelljuwelen&r das &6Amulett der Manaregeneration&r.",
              "",
              "Du kannst nur ein Amulett tragen, entscheide also, ob du lieber mehr Mana oder schnellere Regeneration willst. Für lange Bergbau-Zauber ist mehr Mana meist besser.",
              "",
              "Wer Ender-Perlen übrig hat, macht aus dem Ring des Potenzials im Apparat den &6Ring des geringeren Rabatts&r: der senkt die Kosten jedes Zaubers.",
          ],
          tasks=[task_item("ars_nouveau:amulet_of_mana_boost", 1)],
          rewards=[reward_item("minecraft:diamond", 2), reward_xp(5)],
          deps=["trinkets"], icon="ars_nouveau:amulet_of_mana_boost", optional=True),

    quest("glyph_harvest", 13, 10.6, "&dErnte",
          subtitle="Ein ganzes Feld mit einem Klick.",
          description=[
              "Die Glyphe &dErnte&r kostet eine &6Erdessenz&r und eine &6Eisenhacke&r. Sie erntet reife Pflanzen und lässt unreife stehen.",
              "",
              "&eBerühren, Ernte&r erntet die Pflanze vor dir. Richtig stark wird sie mit der Flächen-Verstärkung (AOE) auf Stufe 2, dann erntest du ein ganzes Feld auf einmal. Bis dahin hilft &dArtikelabholung&r dahinter beim Einsammeln.",
          ],
          tasks=[task_item("ars_nouveau:glyph_harvest", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 32), reward_xp(3)],
          deps=["earth_essence", "scribes_table"], icon="ars_nouveau:glyph_harvest"),

    quest("glyph_leap", 15.2, 10.6, "&dSprung",
          subtitle="Weiter als jedes Pferd.",
          description=[
              "&dSprung&r (Leap) braucht eine &fLuftessenz&r und drei &6Wilden-Flügel&r. Mit &eSelbst, Sprung&r schleudert es dich in Blickrichtung nach vorne, mit Verstärken noch weiter.",
              "",
              "&cAchtung:&r Der Zauber schützt dich nicht vor Fallschaden. Plan die Landung, oder hab einen Wassereimer dabei.",
          ],
          tasks=[task_item("ars_nouveau:glyph_leap", 1)],
          rewards=[reward_item("minecraft:feather", 16), reward_xp(3)],
          deps=["wilden"], icon="ars_nouveau:glyph_leap", optional=True),

    quest("glyph_dispel", 17.2, 10.6, "&dZerstreuen",
          subtitle="Weg mit allen Effekten.",
          description=[
              "&dZerstreuen&r (Dispel) kostet eine &5Abschwörungsessenz&r und drei &6Milcheimer&r. Es entfernt Tränkeffekte vom Ziel, mit Selbst also Gift und Verlangsamung von dir.",
              "",
              "Außerdem schickt es beschworene Helfer zurück in ihren Charme, und ein Zerstreuen auf eine angeschlagene &6Hexe&r (unter halber Gesundheit) bringt dir die Scherben für einen &6Wixie&r. Den Wixie-Charme kannst du ab Stufe 2 bauen, weil er einen Braustand braucht.",
          ],
          tasks=[task_item("ars_nouveau:glyph_dispel", 1)],
          rewards=[reward_item("minecraft:milk_bucket", 1), reward_xp(3)],
          deps=["essences_more"], icon="ars_nouveau:glyph_dispel", optional=True),

    # ---- Helfer ----------------------------------------------------------------
    quest("dominion_wand", 1, 14.5, "&6Dominion-Zauberstab",
          subtitle="Damit sagst du deinen Helfern, was sie tun sollen.",
          description=[
              "Der &6Dominion-Zauberstab&r entsteht im Apparat: ein &6Stock&r in die Mitte, &e2 Quelljuwelen&r und &e1 Goldbarren&r auf die Podeste.",
              "",
              pic("ars_nouveau:dominion_wand"),
              "",
              "Mit ihm verbindest du Dinge: einen Sternbunkel mit seinen Truhen, einen Drygmy mit seinem Zuhause und ab Stufe 2 die Quellrelais untereinander. Grundregel: erst klickst du die Quelle an, dann das Ziel. Schleichend auf einen Helfer geklickt löscht seine Verbindungen.",
          ],
          tasks=[task_item("ars_nouveau:dominion_wand", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 4)],
          deps=["apparatus"], icon="ars_nouveau:dominion_wand"),

    quest("starbuncle_token", 1, 16.5, "&6Sternbunkel-Scherben",
          subtitle="Ein Goldnugget gegen einen Freund.",
          description=[
              "Wilde &dSternbunkel&r (Starbuncles) leben in bewaldeten Gegenden und sind ganz wild auf Gold. Normalerweise laufen sie weg, aber wenn du ein &6Goldnugget&r in der Hand hältst, lassen sie dich heran.",
              "",
              "Wirf ihm ein Nugget hin. Der Sternbunkel schnappt es sich, verschwindet und lässt &6Sternbunkel-Scherben&r (Starbuncle Token) zurück. Mehr Nuggets, mehr Scherben.",
          ],
          tasks=[task_item("ars_nouveau:starbuncle_shards", 1)],
          rewards=[reward_item("minecraft:gold_nugget", 32)],
          deps=["apparatus"], icon="ars_nouveau:starbuncle_shards"),

    quest("starbuncle_charm", 3.3, 15.5, "&dSternbunkel-Charme",
          subtitle="Ein kleiner Lieferdienst auf vier Pfoten.",
          description=[
              "Leg die &6Sternbunkel-Scherben&r in den Apparat und &e4 Goldbarren&r auf die Podeste. Heraus kommt der &6Sternbunkel-Charme&r. Rechtsklick auf den Boden, und dein eigener Sternbunkel erscheint.",
              "",
              pic("ars_nouveau:starbuncle_charm"),
              "",
              "Ein zahmer Sternbunkel sammelt herumliegende Items ein, erntet reife Quellbeeren und trägt Items von Truhe zu Truhe. Er braucht keine Quelle und kein Futter.",
              "",
              "Stirbt er oder triffst du ihn mit Zerstreuen, bekommst du den Charme zurück. Mehrere Charmes auf denselben Sternbunkel stapeln ihn: er trägt dann mehrere Stapel auf einmal.",
          ],
          tasks=[task_item("ars_nouveau:starbuncle_charm", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["dominion_wand", "starbuncle_token"], icon="ars_nouveau:starbuncle_charm", size=1.5, shape="diamond"),

    quest("starbuncle_work", 5.5, 15.5, "&dSternbunkel bei der Arbeit",
          subtitle="Von der Kammer in die Truhe.",
          description=[
              "So richtest du ihn mit dem &6Dominion-Zauberstab&r ein:",
              "",
              "&eAbholen:&r erst die Truhe (oder Imbuement-Kammer) anklicken, dann den Sternbunkel.",
              "&eAbliefern:&r erst den Sternbunkel anklicken, dann die Zieltruhe.",
              "",
              "Er kann aus beliebig vielen Inventaren holen und in beliebig viele liefern. Schaust du ihn an, zeigt er dir, wie viele es sind. Mit einer &6Gegenstandsrolle: Erlauben&r in der Hand des Sternbunkels oder einem Rahmen an der Truhe legst du fest, welche Items er anfasst.",
              "",
              "&eTipp:&r Lass ihn die Quelljuwelen aus all deinen Kammern in eine Truhe tragen. Die bringst du dann gesammelt zum Obelisken.",
          ],
          tasks=[task_checkmark("Sternbunkel eingerichtet")],
          rewards=[reward_item("minecraft:chest", 4), reward_xp(5)],
          deps=["starbuncle_charm"], icon="ars_nouveau:allow_scroll"),

    quest("drygmy", 7.7, 14.5, "&6Drygmy-Charme",
          subtitle="Beute, ohne dass jemand stirbt.",
          description=[
              "Der seltene &dDrygmy&r streift um Tiere herum. Wirf ein &6Wilden-Horn&r in seine Nähe, dann lässt er dir einen &6Drygmy-Scherben&r da. Im Apparat mit Fisch, Weizen, Apfel, Karotte, Samen und drei Quelljuwelen wird daraus der Charme.",
              "",
              "Benutz den Charme auf einem Block &6Bemooster Bruchstein&r: er wird zum &6Drygmy Henge&r. Der Drygmy erzeugt dann die Beute der Tiere und Monster in seiner Nähe, als hätte er sie erlegt, ohne ihnen zu schaden. Er braucht eine Truhe und ein Quellglas neben dem Henge.",
              "",
              "Je mehr verschiedene Tierarten in seinem Revier (zehn Blöcke) leben, desto glücklicher und fleißiger ist er.",
          ],
          tasks=[task_item("ars_nouveau:drygmy_charm", 1)],
          rewards=[reward_item("minecraft:mossy_cobblestone", 4), reward_xp(5)],
          deps=["starbuncle_charm", "wilden"], icon="ars_nouveau:drygmy_charm", optional=True),

    quest("whirlisprig", 7.7, 16.5, "&6Wirbelzweig-Charme",
          subtitle="Ein Naturgeist als Gärtner.",
          description=[
              "Wilde &dWirbelzweige&r (Whirlisprigs) leben in Wäldern. Lässt du in ihrer Nähe einen Baum wachsen, geben sie dir Scherben. Im Apparat mit Quelljuwel, Magieblütensamen, Magebloom, Diamant, drei Setzlingen und Weizensamen wird daraus der Charme.",
              "",
              "Benutz den Charme auf einer Blume. Der Wirbelzweig produziert dann Holz, Feldfrüchte, Samen und Blumen, je nachdem, was in seinem Revier wächst. Er braucht Quelle in der Nähe und eine Truhe direkt neben seiner Blume.",
              "",
              "&eTipp:&r Er mag Vielfalt. Zu viel von einem Block macht ihn nicht glücklicher.",
          ],
          tasks=[task_item("ars_nouveau:whirlisprig_charm", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 8), reward_xp(5)],
          deps=["starbuncle_charm", "magebloom"], icon="ars_nouveau:whirlisprig_charm", optional=True),

    # ---- Erweiterungen ---------------------------------------------------------
    quest("starbuncle_wheel", 12.5, 14.5, "&6Starbuncle Wheel",
          subtitle="Ars Creo: ein Sternbunkel im Hamsterrad.",
          description=[
              "Mit &bArs Creo&r treffen sich Ars und Create. Crafte einen &6Sternbunkel-Charme&r mit einem &6Wasserrad&r von Create, und du bekommst das &6Starbuncle Wheel&r.",
              "",
              "Darin rennt ein Sternbunkel und erzeugt &dRotationskraft&r für deine Create-Maschinen, ganz ohne Wasser. Ein &6Goldblock&r vor dem Rad spornt ihn an und erhöht die Drehzahl.",
              "",
              "Ars Creo lässt außerdem Zaubertürme auf Create-Kontraptionen arbeiten und Quellgläser über ein Display Link anzeigen. Das wird mit Stufe 2 richtig interessant.",
          ],
          tasks=[task_item("ars_creo:starbuncle_wheel", 1)],
          rewards=[reward_item("minecraft:gold_block", 1), reward_xp(5)],
          deps=["starbuncle_charm"], icon="ars_creo:starbuncle_wheel", optional=True),

    quest("advanced_wand", 12.5, 16.5, "&6Advanced Dominion Wand",
          subtitle="Ars Additions: viele Verbindungen auf einmal.",
          description=[
              "&bArs Additions&r bringt den &6Advanced Dominion Wand&r: dein Dominion-Zauberstab im Apparat mit einem &6Amethystblock&r und zwei &6Goldbarren&r.",
              "",
              "Im Auswahlrad stellst du die Reihenfolge der Verbindung ein und ob er einen oder viele Blöcke auf einmal verbindet. Im Mehrfach-Modus verbindet schleichender Rechtsklick gleich alle zusammenhängenden Blöcke. Praktisch, wenn ein Sternbunkel aus zehn Kammern holen soll.",
          ],
          tasks=[task_item("ars_additions:advanced_dominion_wand", 1)],
          rewards=[reward_item("minecraft:amethyst_block", 2)],
          deps=["dominion_wand"], icon="ars_additions:advanced_dominion_wand", optional=True),

    quest("curio_bag", 14.5, 14.5, "&6Trinkets Pouch",
          subtitle="Ars Elemental: Ordnung für Schmuckstücke.",
          description=[
              "&bArs Elemental&r erweitert Ars um die vier Elemente. Das erste nützliche Stück ist der &6Trinkets Pouch&r: eine &6Truhe&r umgeben von &e8 Magieblütenfasern&r.",
              "",
              "Im Beutel lagerst du Ringe, Amulette, Charmes und Scherben, ohne dass sie dein Inventar verstopfen. Er öffnet sich per Taste, wenn er in der Hotbar oder einem Curio-Platz steckt.",
          ],
          tasks=[task_item("ars_elemental:curio_bag", 1)],
          rewards=[reward_xp(5)],
          deps=["magebloom"], icon="ars_elemental:curio_bag", optional=True),

    quest("lesser_focus", 14.5, 16.5, "&6Lesser Focus of Earth",
          subtitle="Ars Elemental: ein Fokus für deine Schule.",
          description=[
              "Die kleinen Foki von &bArs Elemental&r entstehen in der &6Imbuement-Kammer&r: ein &6Amethystsplitter&r hinein, &e3 Essenzen&r eines Elements und &e3 Goldbarren&r auf die Podeste, dazu &d5 000 Quelle&r.",
              "",
              "Als Curio getragen stärkt ein Fokus die Zauber seiner Schule, also Erde, Feuer, Wasser oder Luft. Such dir das Element, das du am meisten zauberst. Die großen Foki kommen erst viel später.",
          ],
          tasks=[task_item("ars_elemental:lesser_earth_focus", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 6), reward_xp(5)],
          deps=["earth_essence"], icon="ars_elemental:lesser_earth_focus", optional=True),

    quest("glyph_pack", 16.5, 14.5, "&dPack",
          subtitle="Ars Technica: Items packen per Zauber.",
          description=[
              "&bArs Technica&r verbindet Ars mit Create. Die meisten Teile brauchen Messing und öffnen mit Stufe 2, aber die Glyphe &dPack&r ist schon jetzt eine Glyphe der ersten Stufe: &6Manipulationsessenz&r, &6Werkbank&r, &6Truhe&r und ein &6Eisenblock&r.",
              "",
              "Sie packt gleiche Items am Ziel in ihre 2x2-Form, also Nuggets zu Barren oder Schnee zu Blöcken. Mit Verstärken wird daraus ein 3x3-Rezept. Die Schwester-Glyphe &dCarve&r schnitzt Stein und Holz zu Treppen.",
          ],
          tasks=[task_item("ars_technica:glyph_pack", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 9), reward_xp(3)],
          deps=["manipulation_essence"], icon="ars_technica:glyph_pack", optional=True),

    quest("charm_water", 16.5, 16.5, "&6Charm of Ocean's Breath",
          subtitle="Ars Additions: Schutzzauber zum Umhängen.",
          description=[
              "&bArs Additions&r bringt aufladbare &6Charms&r. Für den &6Charm of Ocean's Breath&r legst du eine &6Glasflasche&r in den Apparat und &6Kugelfisch&r, &6Tintenbeutel&r und &6Seetang&r auf die Podeste.",
              "",
              "Als Curio getragen lässt er dich weiteratmen, wenn unter Wasser die Luft ausgeht. Jeder Charm hat nur eine bestimmte Zahl an Ladungen. Leer legst du ihn in die &6Imbuement-Kammer&r, dort lädt er sich mit Quelle wieder auf.",
              "",
              "Andere Charms fangen Stürze ab (Phantomhaut und Feder) oder machen dich feuerfest. Schau in JEI, was du dir leisten kannst.",
          ],
          tasks=[task_item("ars_additions:water_breathing_charm", 1)],
          rewards=[reward_item("minecraft:kelp", 16), reward_xp(3)],
          deps=["apparatus"], icon="ars_additions:water_breathing_charm", optional=True),

    # ---- Stufenziel ------------------------------------------------------------
    quest("obelisk", 24, 5.5, "&dJuwelen für den Obelisken",
          subtitle="Die magische Hälfte von Stufe 1.",
          description=[
              "Das Ziel von &6Stufe 1&r hat zwei Säulen: Technik (Andesitlegierung) und Magie. Die Magie-Säule sind &e1 500 Quelljuwelen&r, angepasst an die Zahl der aktiven Spieler.",
              "",
              "Rechtsklick mit einem Stapel Juwelen auf den &eObelisken&r an der Spawn gibt ihn ab, schleichend gibst du alles Passende auf einmal ab. Eine Truhe, die du neben den Obelisken stellst, wird zu deinem Zulieferer: was du hineinfüllst, zählt für dich. Unterwegs hilft &e/kw deposit&r.",
              "",
              "Bring hier einen Stapel zusammen. Behalte aber einen Vorrat: ab &6Stufe 2&r braucht jeder &6Lohenbrenner&r von Create zwei Quelljuwelen, und die Techniker werden bei dir anklopfen.",
          ],
          tasks=[task_item("ars_nouveau:source_gem", 64)],
          rewards=[reward_table("s1_rare"), reward_xp(10)],
          deps=["apparatus", "volcanic"], icon="ars_nouveau:source_gem", size=1.5, shape="hexagon"),

    quest("mage", 24, 8.3, "&dEin echter Magier",
          subtitle="Quelle fließt, der Apparat steht, der Server wartet.",
          description=[
              "Du hast Quelllinks, die Gläser füllen, Kammern, die Juwelen machen, einen Apparat und einen Sternbunkel, der alles einsammelt. Das ist eine vollständige Ars-Basis der ersten Stufe.",
              "",
              "Lege dir einen Vorrat in &6Quelljuwelblöcken&r an. Mit &6Stufe 2&r öffnen das &6Zauberbuch des Magiers&r, die &6Quellrelais&r, das &6Ritual-Kohlenbecken&r und die Zaubertürme, und alle wollen Juwelen. Dann geht es im Kapitel &dArs Nouveau: Magier&r weiter.",
          ],
          tasks=[task_item("ars_nouveau:source_gem_block", 8)],
          rewards=[reward_table("s1_rare"), reward_xp(15)],
          deps=["obelisk", "starbuncle_charm", "beginner_spells"], icon="ars_nouveau:source_gem_block",
          size=2.5, shape="gear"),
]

images = [
    banner("ars_nouveau/title", "Ars Nouveau", 9.5, -4.6, height=1.8, kind="title", colour="magic"),
    banner("ars_nouveau/grundlagen", "Erste Schritte", 4.5, -2.6, height=0.9, colour="magic"),
    banner("ars_nouveau/glyphen", "Glyphen", 14.8, -2.6, height=0.9, colour="magic"),
    banner("ars_nouveau/quelle", "Quelle", 4.5, 4.3, height=0.9, colour="magic"),
    banner("ars_nouveau/apparat", "Apparat und Essenzen", 16.2, 4.3, height=0.9, colour="magic"),
    banner("ars_nouveau/helfer", "Helfer", 4.3, 12.6, height=0.9, colour="magic"),
    banner("ars_nouveau/erweiterungen", "Erweiterungen", 14.5, 12.6, height=0.9, colour="magic"),
    banner("ars_nouveau/ziel", "Stufenziel", 24, 3.6, height=0.9, colour="magic"),
]

chapter(C, "Ars Nouveau", "ars_nouveau:novice_spell_book", "magic", quests, shape="circle", order=2,
        subtitle=["Glyphen, Quelle und die ersten Helfer."], images=images)
