"""Productive Bees in stage 2: wild nests and solitary bees, the advanced beehive and its expansion
box, honey treats, the Nether bees (crystalline, glowing, magmatic), breeding and the breeding
chamber, the centrifuge (plain and Mekanism powered), bottler, upgrades, genes and the incubator
that turns a type gene into a spawn egg, and a checklist of the resource bees whose produce is open
in stage 2. Productive Metalworks (the foundry, casts and the alloy bees it casts) is one short
section. Everything that needs the End (ender, diamond, gems, draconic) is only mentioned.
Numbers follow the jar recipes and config/productivebees-server.toml."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "bees"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Erste Bienen ---------------------------------------------------------
    quest("hive", 0, 1, "&e&lBau einen Fortgeschrittenen Bienenstock",
          subtitle="Ein Stock mit Fenster, in den du hineinschauen kannst.",
          description=[
              "&eRezept:&r oben drei Eichenbretter, in der Mitte &6Honigwabe&r, &6Bienenstock&r (oder Bienennest), Honigwabe, unten &6Lagerfeuer&r, Eichenbrett, &6Schere&r. Honigwaben und Honigflaschen holst du vorher mit einer Schere und Flaschen an einem wilden Bienennest.",
              "",
              img("productivebees:textures/block/advanced_beehive/oak_beehive_front.png", 32, 32),
              "",
              "Der &6Fortgeschrittene Bienenstock&r (Advanced Beehive) hat ein Fenster: Rechtsklick zeigt dir, welche drei Bienen drin wohnen und was sie produziert haben. Er braucht kein Lagerfeuer zum Ernten, und du kannst ihn mit den Bienen darin abbauen und mitnehmen, ganz ohne Behutsamkeit.",
              "",
              "Nur in diesem Stock machen die besonderen Bienen dieses Kapitels ihre &6Ressourcenwaben&r. Eine Biene bleibt nach jedem Ausflug etwa &e4 Minuten&r im Stock, dann liegt eine Wabe im Fenster.",
              "",
              "&eKronwerke:&r Productive Bees ist ab Stufe 2 offen. Bienen für Erze, Redstone, Stahl und Manastahl gibt es jetzt schon, die Edelstein- und Enderbienen kommen in Stufe 4 mit dem End.",
          ],
          tasks=[task_item("productivebees:advanced_oak_beehive", 1)],
          rewards=[reward_item("productivebees:bee_cage", 4), reward_table("s2_common"), reward_xp(5)],
          icon="productivebees:advanced_oak_beehive", size=2.0, shape="hexagon"),

    quest("cage", 2.5, 0, "&6Fang Bienen in Käfige",
          subtitle="Rechtsklick auf die Biene, Rechtsklick auf den Boden.",
          description=[
              "&eRezept:&r Brett, &6Honigflasche&r, Brett in einer Reihe ergeben &e4 Bienenkäfige&r. Rechtsklick auf eine Biene fängt sie, Rechtsklick auf den Boden lässt sie wieder frei.",
              "",
              "Setzt du die Biene schleichend auf einen Stock oder ein Nest, wird das ihr Zuhause. Setzt du sie auf einen passenden Blumenblock, merkt sie sich den als Blume.",
              "",
              "Nimm immer ein paar leere Käfige mit. Jede Biene in diesem Kapitel beginnt damit, dass du sie irgendwo in der Welt einfängst.",
          ],
          tasks=[task_item("productivebees:bee_cage", 4)],
          rewards=[reward_item("minecraft:honey_bottle", 4), reward_xp(3)],
          deps=["hive"], icon="productivebees:bee_cage"),

    quest("nests", 2.5, 2.6, "&2Finde oder bau ein Wildnest",
          subtitle="In jedem Nest wohnt eine einzelne Wildbiene.",
          description=[
              "&eRezept:&r &6Holzschwert&r und &6Eichenstamm&r formlos ergeben ein &6Eichennest&r. Genauso gehen Erde, Sand, Kies, Schnee oder Zuckerrohr mit dem Holzschwert, Stein braucht ein Eisenschwert. Oder du hebst ein Nest in der Welt einfach ab, die Biene bleibt drin.",
              "",
              "Wildnester hängen an Baumstämmen und liegen in Grober Erde, Sand, Kies und Zuckerrohr. In jedem wohnt eine &eSolitärbiene&r: &6Carpenter Bees&r in Holznestern, &6Ashy Mining&r, &6Chocolate Mining&r und &6Leafcutter Bee&r in Erdnestern, &6Mason&r und &6Digger Bee&r im Steinnest.",
              "Dazu die &6Reed Bee&r im Zuckerrohr, die &6Resin Bee&r in Fichten, die &6Blue Banded Bee&r in Akazie, Kirsche und Schwarzeiche, die &6Sweat Bee&r im Schnee und die &6Slimy Bee&r im Sumpf.",
              "",
              "Ein leeres Nest lockt neue Bienen an: Rechtsklick mit einem &6Honey Treat&r, und nach etwa &e20 Minuten&r zieht eine neue ein. Nest mit sich selbst craften leert es. Zwei Kuckucksbienen legen in fremde Nester: die &6Nomad Bee&r in Nester der Ashy Mining Bee, die &6Neon Cuckoo Bee&r in die der Blue Banded Bee, höchstens zweimal pro Nest.",
              "",
              "&eTipp:&r Der &6Nestfinder&r (Nest Locator, Goldklumpen, Eisengitter und Notenblock) zeigt nach Shift-Rechtsklick auf einen Nestblock alle Nester dieser Art im Umkreis von 100 Blöcken.",
          ],
          tasks=[task_item("productivebees:oak_wood_nest", 1)],
          rewards=[reward_item("productivebees:honey_treat", 4), reward_xp(5)],
          deps=["hive"], icon="productivebees:oak_wood_nest"),

    quest("treat", 5, 0, "&6Mach Honey Treats",
          subtitle="Das Leckerli für alles, was summt.",
          description=[
              "&eRezept:&r &6Honigwabe&r und &6Honigflasche&r formlos ergeben einen &6Honey Treat&r. Ein Honigblock mit vier Waben ergibt gleich vier.",
              "",
              pic("productivebees:honey_treat"),
              "",
              "Rechtsklick mit dem Treat auf eine wütende Biene beruhigt sie, auf ein Bienenkind lässt es schneller wachsen, auf ein leeres Nest lockt es eine neue Biene. Später trägt der Treat auch &eGene&r von einer Biene zur anderen.",
              "",
              "Mit einer Angel wird daraus der &6Treat on a Stick&r, mit dem du eine gesattelte &6Bumble Bee&r aus den Ebenen lenkst.",
          ],
          tasks=[task_item("productivebees:honey_treat", 4)],
          rewards=[reward_item("minecraft:honeycomb", 8), reward_xp(3)],
          deps=["cage"], icon="productivebees:honey_treat"),

    quest("expansion", 5, 2, "&6Häng eine Erweiterungsbox an",
          subtitle="Fünf Bienen statt drei, und Platz für Upgrades.",
          description=[
              "&eRezept:&r acht &6Eichenbretter&r um eine &6Honigwabe&r ergeben eine &6Erweiterungsbox&r (Expansion Box). Stell sie direkt neben oder auf den Fortgeschrittenen Bienenstock, eine Box pro Stock.",
              "",
              "Der Stock fasst dann &e5 Bienen&r statt 3, und in der Box sind die Plätze für &6Upgrades&r. Stock und Box gibt es in jeder Holzart.",
              "",
              "&eTipp:&r Mit einem Stock in der Hand schlägst du Bienen, die zu lange drin bleiben, aus dem Stock heraus. Der Fortschritt der Wabe geht dabei verloren.",
          ],
          tasks=[task_item("productivebees:expansion_box_oak", 1)],
          rewards=[reward_item("minecraft:honeycomb", 8), reward_table("s2_common")],
          deps=["hive"], icon="productivebees:expansion_box_oak"),

    quest("upgrades", 7.5, 0.4, "&bBau ein Upgrade",
          subtitle="Schneller, filternd, ohne Flugverkehr.",
          description=[
              "&eRezept Upgrade-Basis:&r vier Stöcke in die Ecken, drei &6Smaragde&r, ein &6Diamant&r unten, ein &6Honey Treat&r in die Mitte. Jedes Upgrade ist diese Basis plus vier &6Honigwabenblöcke&r und das, was es besonders macht.",
              "",
              "&eZeit-Upgrade:&r vier Uhren. Jede Biene bleibt &e15 Prozent&r kürzer im Stock, in der Zentrifuge und im Inkubator geht alles schneller. Mehrere stapeln sich.",
              "&eFilter-Upgrade:&r Komparator, Redstone, Buch und Feder. Rechtsklick auf eine Biene trägt sie ein, nur die darf dann in den Stock.",
              "&eReichweite:&r vier Eisenblöcke, für Farmer-, Collector- und Hoarder-Bienen einen Block mehr Arbeitsfläche, Standard sind 4.",
              "&eSimulator:&r erst ein Anti-Teleport-Upgrade (vier Enderperlen), dann drei Lohenruten und eine Enderperle. Die Bienen fliegen nicht mehr aus, der Ausflug wird nur berechnet. Die Blume muss dann direkt unter dem Stockeingang stehen. Gut für den Server.",
              "",
              "&cDas Produktivitäts-Upgrade&r braucht Drachenstaub einer Draconic Bee und kommt mit dem End in Stufe 4.",
          ],
          tasks=[task_item("productivelib:upgrade_base", 1)],
          rewards=[reward_item("minecraft:emerald", 3), reward_xp(5)],
          deps=["expansion"], icon="productivelib:upgrade_time", optional=True, section="first"),

    quest("nether_bees", 7.5, 2.6, "&cHol Bienen aus dem Nether",
          subtitle="Quarz, Glowstone und Magma haben eigene Bienen.",
          description=[
              "&eRezept:&r &6Eisenschwert&r und &6Netherquarzerz&r ergeben ein &6Quarznest&r. Stell es im &cNether&r auf und klick mit &6Netherquarz&r darauf, dann zieht eine &6Crystalline Bee&r ein. Oder du hebst ein Quarznest ab, das du im Nether findest.",
              "",
              "Drei Nethernester brauchst du für fast alles weitere. &6Quarznest&r: Crystalline Bee, gelockt mit Netherquarz. &6Glowstonenest&r (Holzschwert und Glowstone): Glowing Bee, gelockt mit Glowstonestaub. &6Netherziegelnest&r (Eisenschwert und Netherziegel): Magmatic Bee, gelockt mit Magmacreme, zu finden in Festungen. Das &6Seelensandnest&r gibt mit einer Ghast-Träne eine Ghostly Bee.",
              "",
              "Die Crystalline Bee ist der &eElternteil aller Erzbienen&r. Fang zwei oder drei, du brauchst sie ständig.",
              "",
              "&cVorsicht:&r Magmatic Bees verwandeln Bruchstein in ihrer Nähe in Lava. Bau ihr Gehege aus etwas anderem.",
          ],
          tasks=[task_item("productivebees:nether_quartz_nest", 1)],
          rewards=[reward_item("minecraft:quartz", 16), reward_table("s2_common"), reward_xp(5)],
          deps=["nests"], icon="productivebees:nether_quartz_nest", size=1.5, section="first"),

    # ---- Zentrifuge und Honig ------------------------------------------------
    quest("centrifuge", 10.5, 1, "&7&lBau eine Zentrifuge",
          subtitle="Aus Waben werden Rohstoffe, Honig und Wachs.",
          description=[
              "&eRezept auf Kronwerke:&r sieben &6Eisenbarren&r um einen &6Mahlstein&r von Create, oben in der Mitte bleibt frei. Wirf Waben hinein oder leg sie ins Fenster, nach &e15 Sekunden&r kommt heraus, was die Biene gesammelt hat, dazu &6Wachs&r.",
              "",
              pic("productivebees:centrifuge"),
              "",
              "Normale &6Honigwaben&r geben 100 mB &6Honig&r und ein Wachs. Honig sammelt sich im Tank (10 Eimer), fließt in jeden Tank daneben und lässt sich mit Rohren abpumpen. Gegenstände, die du auf die Zentrifuge wirfst, saugt sie von selbst ein.",
              "",
              "Zwei Wachs und ein Faden ergeben eine Kerze, neun Wachs einen Wachsblock. Vier gleiche Ressourcenwaben lassen sich zu einem &6Wabenblock&r pressen, der auch in die Zentrifuge passt.",
          ],
          tasks=[task_item("productivebees:centrifuge", 1)],
          rewards=[reward_item("productivebees:wax", 8), reward_table("s2_common"), reward_xp(5)],
          deps=["hive"], icon="productivebees:centrifuge", size=1.75, shape="hexagon"),

    quest("powered", 13, 0, "&dBau eine Stromzentrifuge",
          subtitle="Dreimal so schnell, mit Mekanism-Schaltkreisen.",
          description=[
              "&eRezept:&r eine &6Zentrifuge&r in die Mitte, oben und unten je ein &6Einfacher Steuerschaltkreis&r von Mekanism, links und rechts Eisenbarren, Redstone in die Ecken.",
              "",
              "Die &6Stromzentrifuge&r (Powered Centrifuge) braucht &d10 FE/t&r und schafft eine Wabe in &e5 Sekunden&r statt 15. Ein Wärmegenerator daneben reicht.",
              "",
              "&eStabilitäts-Upgrade:&r Upgrade-Basis, vier Enderperlen und vier Honigwaben. In der Zentrifuge hebt es die Chance aller unsicheren Ausgaben um &e15 Prozent&r, aus 40 Prozent Roheisen werden 55.",
              "",
              "&cDie Heiße Zentrifuge&r, die aus Lohenwaben ganze Lohenruten macht, braucht ein Drachenei und kommt in Stufe 4.",
          ],
          tasks=[task_item("productivebees:powered_centrifuge", 1)],
          rewards=[reward_item("mekanism:basic_control_circuit", 2), reward_xp(5)],
          deps=["centrifuge"], icon="productivebees:powered_centrifuge"),

    quest("bottler", 13, 2, "&6Fülle Honig ab",
          subtitle="Flaschen, Treats und Strom aus Honig.",
          description=[
              "&eRezept:&r eine &6Glatte Steinstufe&r oben, &6Glas&r in der Mitte, sonst sieben &6Eisenbarren&r. Stell den &6Abfüller&r (Bottler) direkt neben die Zentrifuge, dann fließt der Honig von selbst hinein.",
              "",
              "Je &e250 mB Honig&r machen aus einer Glasflasche eine &6Honigflasche&r und aus einer Honigwabe einen &6Honey Treat&r. Vier Honigflaschen und ein Eimer ergeben einen &6Honigeimer&r.",
              "",
              "&eHoniggenerator:&r Honigeimer, Ofen und sieben Eisenbarren. Er verbrennt &e2 mB Honig pro Tick&r für &d60 FE/t&r, ein Eimer ist also 30 000 FE. Honig kommt per Rohr, Flasche, Eimer oder Honigblock hinein.",
              "",
              "&eTipp:&r Eine &6Futterplatte&r (Feeding Slab) mit Honig geflutet gibt den Bienen darauf Regeneration.",
          ],
          tasks=[task_item("productivebees:bottler", 1)],
          rewards=[reward_item("minecraft:glass_bottle", 8), reward_xp(5)],
          deps=["centrifuge"], icon="productivebees:bottler"),

    # ---- Gene -----------------------------------------------------------------
    quest("genes", 18.5, 1, "&dQuetsche Gene aus einer Biene",
          subtitle="Flaschen rein, Biene drauf, Hebel ziehen.",
          description=[
              "Leg leere &6Glasflaschen&r in den &6Abfüller&r, setz einen &6Kolben&r darüber, der nach unten drückt, und stell eine Biene dazwischen. Hebel ziehen, und du hältst &6Gequetschtes Bienenmaterial&r (Squashed Bee Material) in der Hand. Die Biene ist danach weg.",
              "",
              pic("productivebees:gene"),
              "",
              "Wirf die Flasche in eine &6Zentrifuge&r. Heraus kommen &6Genproben&r: eines für den &eTyp&r der Biene (etwa Eisenbiene, im Schnitt 33 Prozent Reinheit) und welche für ihre Eigenschaften.",
              "",
              "&eOhne Verlust:&r Das &6Gen-Sampler-Upgrade&r (Basis, vier Wabenblöcke, zwei Diamantschwerter, zwei Honigflaschen) in der Erweiterungsbox nimmt bei jedem Besuch mit 5 Prozent Chance eine Probe, ohne der Biene zu schaden.",
          ],
          tasks=[task_item("productivebees:gene_bottle", 1), task_item("productivebees:gene", 1)],
          rewards=[reward_item("minecraft:glass_bottle", 8), reward_table("s2_common"), reward_xp(5)],
          deps=["bottler"], icon="productivebees:gene"),

    quest("gene_treat", 21, 1, "&dÜbertrage ein Gen",
          subtitle="Treat plus Gen, verfüttern, hoffen.",
          description=[
              "Leg einen &6Honey Treat&r und eine oder mehrere gleiche &6Genproben&r in die Werkbank. Füttere den Treat einer Biene, und sie übernimmt die Eigenschaft mit der Chance, die der Treat als &eReinheit&r zeigt.",
              "",
              "Zwei gleiche Gene zusammen in der Werkbank ergeben ein reineres. Der &6Gen-Indexer&r (Eisen, Komparator, Werkbank) macht das mit einem Redstone-Signal für eine ganze Kiste voller Proben.",
              "",
              "&eEigenschaften:&r Produktivität (Normal, Mittel, Hoch, Sehr Hoch: mehr Waben pro Ausflug), Wetter (Keins, Regen, Jedes), Verhalten (Tag, Nacht, Tag und Nacht), Ausdauer und Gemüt. Eine Biene, die du bei Regen oder nachts an eine Leine hängst, kann die passende Toleranz von selbst lernen, nimmt dabei aber manchmal Schaden.",
          ],
          tasks=[task_checkmark("Ein Gen übertragen")],
          rewards=[reward_item("productivebees:honey_treat", 8), reward_xp(5)],
          deps=["genes"], icon="productivebees:honey_treat"),

    quest("incubator", 23.5, 1, "&d&lBrüte ein Spawn-Ei aus",
          subtitle="Aus einem Typ-Gen wird ein Ei dieser Biene.",
          description=[
              "&eRezept:&r &6Tageslichtsensor&r oben, &6Heuballen&r in der Mitte, sieben &6Eisenbarren&r. Der &6BaBee-Inkubator&r braucht &d10 FE/t&r.",
              "",
              pic("productivebees:spawn_egg"),
              "",
              "Leg ein &6Ei&r und einen Honey Treat mit dem &eTyp-Gen&r einer Biene hinein. Nach &e3 Minuten&r hältst du ein &6Spawn-Ei&r genau dieser Biene. Nur das Typ-Gen zählt, andere Gene auf dem Treat gehen verloren.",
              "",
              "Das ist die Brücke zu den anderen Mods: Ein Ei der Eisenbiene wird im &aManabecken&r mit 10 000 Mana zum Ei der &6Manastahlbiene&r, auf dem &aNatural Altar&r mit 15 000 Aura zum Ei der &6Infused-Iron-Biene&r, in der &6Gießerei&r mit flüssigem Stahl zum Ei der &6Stahlbiene&r. Was es alles gibt, zeigt JEI beim Spawn-Ei.",
              "",
              "&eNebenbei:&r Ein Bienenkind im Käfig wächst im Inkubator mit 20 Honey Treats in 3 Minuten aus.",
          ],
          tasks=[task_item("productivebees:incubator", 1)],
          rewards=[reward_item("minecraft:egg", 16), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["gene_treat"], icon="productivebees:incubator", size=1.75, shape="diamond"),

    # ---- Zucht ----------------------------------------------------------------
    quest("breeding", 2.5, 7, "&a&lZüchte deine erste Biene",
          subtitle="Zwei Eltern, Blumen, ein Kind mit neuem Beruf.",
          description=[
              "Fang eine &6Yellow Carpenter Bee&r und eine &6Green Carpenter Bee&r aus Holznestern, lass sie zusammen frei und gib beiden eine &6Blume&r. Das Kind ist eine &6Lumber Bee&r, die Stämme in der Nähe anknabbert und Holz im Stock ablegt.",
              "",
              "So geht jede Zucht: Zwei Bienen verschiedener Art, beide gefüttert, und das Kind ist das, was JEI unter &eBee Breeding&r für dieses Paar zeigt. Kinder wachsen von selbst, mit Honey Treats schneller.",
              "",
              "&eWeitere Berufe:&r &6Quarry Bee&r (Chocolate Mining und Digger Bee) sammelt Steinsplitter, &6Rancher Bee&r (Lumber und Sweat Bee) melkt und schert, &6Farmer Bee&r (Lumber und Rancher) erntet Felder, &6CuBee&r (Farmer und Rancher) bringt Tiere in Stimmung. Eine normale Biene mit einem &6Trichter&r gefüttert wird zur &6Collector Bee&r, die Gegenstände vom Boden in den Stock trägt.",
              "",
              "&eTipp:&r Das &6BaBee-Upgrade&r (Basis, vier Wabenblöcke, vier Blumen) in der Erweiterungsbox lässt die Bienen im Stock mit 5 Prozent Chance pro Besuch von selbst Nachwuchs machen.",
          ],
          tasks=[task_checkmark("Lumber Bee gezüchtet")],
          rewards=[reward_item("minecraft:oak_log", 32), reward_table("s2_common"), reward_xp(5)],
          deps=["nests"], icon="productivebees:spawn_egg_lumber_bee", size=1.75, shape="hexagon"),

    quest("feeder", 0, 8.6, "&aStell eine Futterplatte auf",
          subtitle="Drei Blumen auf einem Block.",
          description=[
              "&eRezept:&r eine &6Glatte Steinstufe&r über einer &6Truhe&r. Die &6Futterplatte&r (Feeding Slab) hält drei Blöcke, die für die Bienen als Blume zählen, zum Beispiel einen Eisenblock, einen Quarzblock und eine Blume.",
              "",
              "Lumber- und Quarry-Bienen, die von der Platte fressen, produzieren aus einem zufälligen Block darin. Vor einem Stock mit Simulator-Upgrade ist die Platte der einzige Weg, drei verschiedene Bienen zu versorgen.",
          ],
          tasks=[task_item("productivebees:feeder", 1)],
          rewards=[reward_item("minecraft:smooth_stone_slab", 4), reward_xp(3)],
          deps=["breeding"], icon="productivebees:feeder"),

    quest("breeding_chamber", 5, 8.6, "&aBau eine Zuchtkammer",
          subtitle="Züchten ohne Gehege.",
          description=[
              "&eRezept:&r ein &6Rosenstrauch&r oben, ein &6BaBee-Upgrade&r in der Mitte, sieben &6Eisenbarren&r. Die &6Zuchtkammer&r braucht &d50 FE/t&r.",
              "",
              "Leg beide Eltern im Käfig hinein, dazu ihre Futterblumen und leere Käfige. Nach &e5 Minuten&r liegt das Kind im Käfig bereit. Zeit-Upgrades verkürzen das Warten.",
              "",
              "Damit läuft eine Zucht sauber nebenbei, ohne dass Bienen davonfliegen oder im Gehege verloren gehen.",
          ],
          tasks=[task_item("productivebees:breeding_chamber", 1)],
          rewards=[reward_item("productivebees:bee_cage", 8), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["breeding"], icon="productivebees:breeding_chamber"),

    # ---- Ressourcenbienen (Checkliste) ----------------------------------------
    quest("c_crystalline", 8.5, 7, "&fHalte eine Crystalline Bee",
          subtitle="Netherquarz aus Waben.",
          description=["&6Quarznest&r im Nether, gelockt mit Netherquarz. Blume: Quarzblock oder Quarzerz. Wabe gibt mit 50 Prozent 1 bis 3 &6Netherquarz&r."],
          tasks=[task_checkmark("Crystalline Bee im Stock")],
          rewards=[reward_item("minecraft:quartz", 8)],
          deps=["nether_bees"], icon="minecraft:quartz"),

    quest("c_iron", 10.5, 7, "&7Züchte die Eisenbiene",
          subtitle="Roheisen aus Waben.",
          description=["&6Crystalline Bee&r und &6Ashy Mining Bee&r. Blume: Eisenblock, Eisenerz, Eisengitter oder Trichter. Wabe gibt mit 40 Prozent &6Roheisen&r. Die Eisenbiene ist Elternteil von Zink, Osmium, Blei, Nickel, Silber und Stahl."],
          tasks=[task_checkmark("Eisenbiene gezüchtet")],
          rewards=[reward_item("minecraft:raw_iron", 16), reward_xp(3)],
          deps=["c_crystalline"], icon="minecraft:raw_iron"),

    quest("c_copper", 12.5, 7, "&6Züchte die Kupferbiene",
          subtitle="Rohkupfer aus Waben.",
          description=["&6Crystalline Bee&r und &6Ashy Mining Bee&r, dasselbe Paar wie bei Eisen, aus dem auch die Zinn- und Aluminiumbiene kommen. Blume: Kupferblock oder Kupfererz. Wabe gibt mit 40 Prozent &6Rohkupfer&r."],
          tasks=[task_checkmark("Kupferbiene gezüchtet")],
          rewards=[reward_item("minecraft:raw_copper", 16), reward_xp(3)],
          deps=["c_iron"], icon="minecraft:raw_copper"),

    quest("c_gold", 14.5, 7, "&eZüchte die Goldbiene",
          subtitle="Rohgold aus Waben.",
          description=["&6Crystalline Bee&r und &6Mason Bee&r, oder ein &6Nethergoldnest&r (Diamantschwert und Nethergolderz) im Nether, gelockt mit einem Goldbarren. Blume: Goldblock, Golderz oder Vergoldeter Schwarzstein. Wabe gibt mit 40 Prozent &6Rohgold&r."],
          tasks=[task_checkmark("Goldbiene gezüchtet")],
          rewards=[reward_item("minecraft:raw_gold", 8), reward_xp(3)],
          deps=["c_copper"], icon="minecraft:raw_gold"),

    quest("c_zinc", 16.5, 7, "&7Züchte die Zinkbiene",
          subtitle="Rohzink für Messing.",
          description=["&6Eisenbiene&r und &6Sweat Bee&r (Schneenest), dasselbe Paar gibt auch die Nickelbiene. Blume: &6Zinkblock&r. Wabe gibt mit 40 Prozent &6Rohzink&r für den Messingmixer."],
          tasks=[task_checkmark("Zinkbiene gezüchtet")],
          rewards=[reward_item("create:raw_zinc", 12), reward_xp(3)],
          deps=["c_gold"], icon="create:raw_zinc"),

    quest("c_osmium", 18.5, 7, "&bZüchte die Osmiumbiene",
          subtitle="Rohosmium für Mekanism.",
          description=["&6Eisenbiene&r und &6Neon Cuckoo Bee&r (aus Nestern der Blue Banded Bee). Blume: &6Osmiumblock&r. Wabe gibt mit 40 Prozent &6Rohosmium&r. Mit einer Glowing Bee gepaart wird daraus die Biene für Raffiniertes Glowstone."],
          tasks=[task_checkmark("Osmiumbiene gezüchtet")],
          rewards=[reward_item("mekanism:raw_osmium", 12), reward_xp(3)],
          deps=["c_zinc"], icon="mekanism:raw_osmium"),

    quest("c_steel", 20.5, 7, "&8Gieße die Stahlbiene",
          subtitle="Sieben bis zwölf Stahlklumpen pro Wabe.",
          description=["Spawn-Ei der &6Eisenbiene&r oder der &6Kohlebiene&r in den Gießtisch, &e810 mB flüssiger Stahl&r darüber. Blume: &6Stahlblock&r. Jede Wabe gibt sicher 7 bis 12 &6Stahlklumpen&r, also etwa einen Barren. &eKronwerke:&r Stahl ist das Massenziel von Stufe 3."],
          tasks=[task_checkmark("Stahlbiene gegossen")],
          rewards=[reward_item("mekanism:ingot_steel", 16), reward_table("s2_uncommon"), reward_xp(5)],
          deps=["alloy_bees"], icon="mekanism:ingot_steel"),

    quest("c_glowing", 8.5, 8.6, "&eHalte eine Glowing Bee",
          subtitle="Glowstonestaub, jede Wabe.",
          description=["&6Glowstonenest&r im Nether, gelockt mit Glowstonestaub. Blume: Glowstone, Shroomlight oder Redstonelampe. Wabe gibt sicher einen &6Glowstonestaub&r. Die Biene leuchtet und blendet."],
          tasks=[task_checkmark("Glowing Bee im Stock")],
          rewards=[reward_item("minecraft:glowstone_dust", 16)],
          deps=["c_crystalline"], icon="minecraft:glowstone_dust"),

    quest("c_redstone", 10.5, 8.6, "&cZüchte die Redstonebiene",
          subtitle="Redstone aus Waben.",
          description=["&6Glowing Bee&r und &6Chocolate Mining Bee&r (Erdnest). Blume: Redstoneblock, Redstoneerz, Redstonefackel oder Redstonelampe. Wabe gibt mit 50 Prozent 1 bis 2 &6Redstone&r. Sie entkommt gern, ein Stock mit Filter hilft."],
          tasks=[task_checkmark("Redstonebiene gezüchtet")],
          rewards=[reward_item("minecraft:redstone", 32), reward_xp(3)],
          deps=["c_glowing"], icon="minecraft:redstone"),

    quest("c_lapis", 12.5, 8.6, "&9Züchte die Lapisbiene",
          subtitle="Lapislazuli aus Waben.",
          description=["&6Redstonebiene&r und &6Blue Banded Bee&r. Blume: &6Lapislazuliblock&r. Wabe gibt mit 50 Prozent &6Lapislazuli&r. Mit einer Skeletal Bee gepaart wird daraus die Dye Bee, die Farbstoff aus Blumen sammelt."],
          tasks=[task_checkmark("Lapisbiene gezüchtet")],
          rewards=[reward_item("minecraft:lapis_lazuli", 32), reward_xp(3)],
          deps=["c_redstone"], icon="minecraft:lapis_lazuli"),

    quest("c_magmatic", 8.5, 10.2, "&6Halte eine Magmatic Bee",
          subtitle="Magmacreme, und Lava aus Bruchstein.",
          description=["&6Netherziegelnest&r in Netherfestungen, gelockt mit Magmacreme. Blume: Magmablock, Feuer oder Netherwarze. Wabe gibt mit 30 Prozent &6Magmacreme&r. Mit einem Lavaeimer gefüttert wird sie zur Lava Bee."],
          tasks=[task_checkmark("Magmatic Bee im Stock")],
          rewards=[reward_item("minecraft:magma_cream", 8)],
          deps=["c_glowing"], icon="minecraft:magma_cream"),

    quest("c_coal", 10.5, 10.2, "&8Züchte die Kohlebiene",
          subtitle="Kohle aus Waben.",
          description=["&6Magmatic Bee&r und &6Leafcutter Bee&r (Erdnest). Blume: &6Kohleblock&r. Wabe gibt mit 60 Prozent &6Kohle&r. Mit der Magmatic Bee gepaart wird daraus die Schwefelbiene, mit einer CreeBee die Salpeterbiene."],
          tasks=[task_checkmark("Kohlebiene gezüchtet")],
          rewards=[reward_item("minecraft:coal", 32), reward_xp(3)],
          deps=["c_magmatic"], icon="minecraft:coal"),

    quest("c_blazing", 12.5, 10.2, "&cZüchte die BlazBee",
          subtitle="Lohenstaub ohne Festung.",
          description=["&6Magmatic Bee&r und &6Nomad Bee&r (aus Nestern der Ashy Mining Bee). Blume: Magmablock oder Feuer. Wabe gibt mit 30 Prozent &6Lohenstaub&r. Feuerfest, wehrt sich mit Feuer. &eKronwerke:&r Lohenstaub heizt den Messingmixer."],
          tasks=[task_checkmark("BlazBee gezüchtet")],
          rewards=[reward_item("minecraft:blaze_powder", 8), reward_xp(3)],
          deps=["c_coal"], icon="minecraft:blaze_powder"),

    quest("c_manasteel", 23.5, 7, "&bVerwandle ein Ei zur Manastahlbiene",
          subtitle="Manastahlklumpen aus Waben.",
          description=["Spawn-Ei der &6Eisenbiene&r in ein &aManabecken&r werfen, &d10 000 Mana&r. Blume: &6Manastahlblock&r. Wabe gibt mit 60 Prozent 1 bis 2 &6Manastahlklumpen&r. Diese Bienen vermehren sich nicht untereinander. Auf der Terraplatte wird ihr Ei mit Manadiamant und Manaperle für 500 000 Mana zur Terrastahlbiene."],
          tasks=[task_checkmark("Manastahlbiene ausgebrütet")],
          rewards=[reward_item("botania:manasteel_ingot", 4), reward_xp(5)],
          deps=["incubator"], icon="botania:manasteel_ingot", section="magic"),

    quest("c_infused_iron", 23.5, 8.6, "&aVerwandle ein Ei zur Infused-Iron-Biene",
          subtitle="Infused Iron, fast jede Wabe.",
          description=["Spawn-Ei der &6Eisenbiene&r auf den &aNatural Altar&r von Nature's Aura, &d15 000 Aura&r. Blume: &6Infused-Iron-Block&r. Wabe gibt mit 80 Prozent &6Infused Iron&r. Ein Goldbienen-Ei wird dort für 3 000 Aura zur Tainted-Gold-Biene."],
          tasks=[task_checkmark("Infused-Iron-Biene ausgebrütet")],
          rewards=[reward_item("naturesaura:infused_iron", 8), reward_xp(5)],
          deps=["incubator"], icon="naturesaura:infused_iron", section="magic"),

    # ---- Productive Metalworks ------------------------------------------------
    quest("foundry", 15.5, 13.5, "&6&lBau die Gießerei",
          subtitle="Ein Schmelzofen aus Schamott, befeuert mit Lava.",
          description=[
              "&eRezept:&r fünf &6Tonklumpen&r und vier &6Sand&r im Schachbrett ergeben vier &6Schamott&r (Fire Clay), gebrannt im Ofen zu &6Schamottsteinen&r. Acht Schamottsteine um einen &6Schmelzofen&r ergeben den &6Gießerei-Controller&r, um Glas den &6Tank&r, als leerer Ring den &6Abfluss&r. Drei Kupferbarren, Kupfer, Eimer, Kupfer, drei Schamottsteine ergeben eine &6Flüssig-Heizspule&r.",
              "",
              pic("productivemetalworks:fire_brick"),
              "",
              "&eBauen:&r Der Boden besteht ganz aus &6Heizspulen&r, die Wände aus Schamottsteinblöcken (vier Steine ergeben vier) oder Fenstern, darin Controller, Tank und mindestens ein Abfluss. Mindestens 3 mal 3 und zwei hoch, innen ein Luftblock, die Ecken dürfen fehlen. &6Lava&r in den Tank, dann heizt sie mit 1 500 Grad.",
              "",
              "&eSchmelzen:&r Gegenstände über den Controller oder von oben hineinwerfen. Ein Barren gibt 90 mB, ein Rohes Erz 180 mB, ein &6Erzblock 270 mB&r, also drei Barren. Kohle wird zu 100 mB Kohlenstoff, eine Honigwabe zu Honig und Wachs. Zwei Flüssigkeiten zusammen legieren von selbst, 90 mB Eisen und 100 mB Kohlenstoff werden zu 90 mB &6Stahl&r.",
              "",
              "&eKronwerke:&r Messing legiert die Gießerei nicht, das macht nur der Mixer. Stahl aus der Gießerei zählt später für das Ziel von Stufe 3.",
          ],
          tasks=[task_item("productivemetalworks:black_foundry_controller", 1),
                 task_item("productivemetalworks:black_foundry_tank", 1),
                 task_item("productivemetalworks:black_foundry_drain", 1),
                 task_item("productivemetalworks:liquid_heating_coil", 4)],
          rewards=[reward_item("productivemetalworks:fire_brick", 32), reward_table("s2_uncommon"), reward_xp(10)],
          icon="productivemetalworks:black_foundry_controller", size=2.0, shape="gear"),

    quest("casting", 18, 13.5, "&6Gieße Barren",
          subtitle="Hahn, Gießtisch, Gussform.",
          description=[
              "&eRezept:&r zwei Schamottsteine und einer darunter ergeben den &6Hahn&r, der an den Abfluss kommt. Sieben Schamottsteine als Tisch mit Beinen ergeben den &6Gießtisch&r, als Wanne das &6Gießbecken&r.",
              "",
              pic("productivemetalworks:ingot_cast"),
              "",
              "&eGussform:&r Leg einen beliebigen Barren auf den Gießtisch und gieß &e360 mB Stahl&r darüber, heraus kommt eine &6Barrenform&r. Dann reichen &e90 mB&r Metall pro Barren. Ohne Form gießt das Becken für 810 mB einen ganzen Block.",
              "",
              "Rechtsklick auf den Hahn gießt, ein Redstone-Takt gießt automatisch, und statt des Hahns tut es jedes Flüssigkeitsrohr. Den fertigen Barren nimmst du mit Rechtsklick, einem Trichter oder einem Rohr.",
          ],
          tasks=[task_item("productivemetalworks:casting_table", 1), task_item("productivemetalworks:ingot_cast", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 16), reward_xp(5)],
          deps=["foundry"], icon="productivemetalworks:ingot_cast"),

    quest("alloy_bees", 20.5, 13.5, "&8&lGieße eine Legierungsbiene",
          subtitle="Ein Spawn-Ei im Gießtisch, Metall darüber.",
          description=[
              "Leg das &6Spawn-Ei einer Eisenbiene&r auf den &6Gießtisch&r und gieß &e810 mB flüssigen Stahl&r darüber. Das Ei wird zum Spawn-Ei der &6Stahlbiene&r. Das ist auf diesem Server der einzige Weg zu Legierungsbienen, züchten lassen sie sich nicht.",
              "",
              "&eSo geht jede Legierung:&r Ei eines Grundmetalls plus 810 mB (neun Barren) der Legierung. Kupfer- oder Zinnbiene mit &6Bronze&r, Eisen- oder Nickelbiene mit &6Invar&r, Kupfer- oder Nickelbiene mit &6Konstantan&r, Gold- oder Silberbiene mit &6Elektrum&r, Kupfer- oder Zinkbiene mit eingeschmolzenem &6Messing&r.",
              "",
              "Legierungsbienen brauchen einen Block ihrer Legierung als Blume und geben pro Wabe sicher &e4 bis 6 Klumpen&r, die Stahlbiene sogar 7 bis 12.",
              "",
              "&eKronwerke:&r Ein Stock voller Stahlbienen an einer Stromzentrifuge liefert Stahl für das Ziel von Stufe 3, ohne Erz und ohne Infusionsanlage. Eine Kiste neben dem Obelisken nimmt die Barren an.",
          ],
          tasks=[task_checkmark("Legierungsbiene gegossen")],
          rewards=[reward_table("s2_rare"), reward_item("mekanism:ingot_steel", 16), reward_xp(20)],
          deps=["casting", "incubator"], icon="productivebees:spawn_egg_configurable_bee", size=2.5, shape="gear"),

    quest("outlook", 23, 13.5, "&dWas später kommt",
          subtitle="Bienen für Stufe 3 und 4.",
          description=[
              "&eStufe 3:&r Osmium- und Obsidianbiene (Lavabiene mit Water Bee aus dem Fluss) ergeben die Biene für &6Raffiniertes Obsidian&r. Das Ei der Infused-Iron-Biene wird am Opfertisch zur Biene für &6Himmelsbarren&r, das Manastahl-Ei im Elfenportal zum Ei der &6Elementiumbiene&r.",
              "Nomad und Reed Bee ergeben die &6Siliziumbiene&r für AE2, Crystalline und Neon Cuckoo die &6Menrilbiene&r, und Powah macht aus Eisen- und Goldbienen die Biene für &6Energetisierten Stahl&r.",
              "",
              "&eStufe 4:&r Im End leben die &6Ender Bee&r im Endsteinnest und die &6Draconic Bee&r in Obsidiansäulen. Von der Ender Bee stammen Diamant-, Smaragd-, Erfahrungs- und alle Edelsteinbienen ab, aus der Diamantbiene werden die &6Arkanen Bienen&r von Ars Nouveau und die Netheritbiene. Die Draconic Bee liefert den Drachenstaub für das Produktivitäts-Upgrade, und ein Drachenei wird zur Heißen Zentrifuge.",
              "",
              "Alles, was du bis dahin züchtest, bleibt. Eine gute Eisen- und Crystalline-Linie ist der Anfang jeder dieser Bienen.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["alloy_bees"], icon="productivebees:spawn_egg_configurable_bee", optional=True),

    # ---- neue Quests: Erste Bienen ---------------------------------------------------
    quest("nest_locator", 2.5, 3.6, "&2Bau einen Nestfinder",
          subtitle="Er zeigt dir, wo die nächste Biene wohnt.",
          description=[
              "&eRezept:&r Goldklumpen, &6Eisengitter&r, Goldklumpen oben, Goldklumpen, &6Notenblock&r, Goldklumpen in der Mitte, drei Goldklumpen unten.",
              "",
              "Shift-Rechtsklick auf einen Block, aus dem die gesuchte Nestart besteht, stimmt den &6Nestfinder&r darauf ein. Rechtsklick sucht dann die Umgebung ab und sagt dir, wie viele Meter es in welche Richtung bis zum nächsten Nest sind.",
              "",
              "Damit findest du Quarznester im Nether und seltene Holznester, ohne den Wald abzuholzen.",
          ],
          tasks=[task_item("productivebees:nest_locator", 1)],
          rewards=[reward_item("minecraft:gold_nugget", 9), reward_xp(3)],
          deps=["nests"], icon="productivebees:nest_locator"),

    quest("bee_helmet", 0, 3.4, "&eSetz einen Bienennest-Helm auf",
          subtitle="Wütende Bienen lassen dich in Ruhe.",
          description=[
              "Ein &6Bienennest&r und ein &6Diamanthelm&r formlos ergeben den &6Bienennest-Helm&r.",
              "",
              "Mit ihm auf dem Kopf greifen dich wütende Bienen nicht an. Wirst du getroffen, schlüpft mit &e30 Prozent&r Chance eine &6KamikazBee&r heraus und stürzt sich auf den Angreifer.",
              "",
              "&eTipp:&r Praktisch beim Umsetzen von Nestern und beim Arbeiten am vollen Bienenhaus.",
          ],
          tasks=[task_item("productivebees:bee_nest_diamond_helmet", 1)],
          rewards=[reward_item("minecraft:honeycomb", 8), reward_xp(5)],
          deps=["nests"], icon="productivebees:bee_nest_diamond_helmet", optional=True),

    quest("bumble", 7.5, -0.6, "&eReite eine Bumble Bee",
          subtitle="Eine Biene, groß genug für einen Sattel.",
          description=[
              "Die &6Bumble Bee&r lebt in den &eEbenen&r und ist groß genug zum Reiten. Ein Bumble-Bee-Nest lockt sie dort an.",
              "",
              "Leg ihr einen &6Sattel&r auf und nimm den &6Treat on a Stick&r in die Hand (Angel und Honey Treat formlos). Damit lenkst du sie im Gleitflug, Rechtsklick gibt einen Schub. Ist der Treat aufgebraucht, machst du ihn mit einem neuen Honey Treat wieder fertig.",
          ],
          tasks=[task_item("productivebees:treat_on_a_stick", 1), task_checkmark("Auf einer Bumble Bee geritten")],
          rewards=[reward_item("minecraft:saddle", 1), reward_xp(5)],
          deps=["treat"], icon="productivebees:treat_on_a_stick", optional=True),

    quest("time_upgrade", 9.5, 0.0, "&bBau ein Zeit-Upgrade",
          subtitle="Kürzere Pausen im Stock.",
          description=[
              "&eRezept:&r die &6Upgrade-Basis&r in die Mitte, vier &6Uhren&r an die Seiten, vier &6Honigwabenblöcke&r in die Ecken.",
              "",
              "In der Erweiterungsbox bleiben die Bienen kürzer im Stock, also gibt es mehr Waben pro Stunde. Mehrere Upgrades stapeln sich. Dasselbe Upgrade beschleunigt auch Zentrifuge, Inkubator und Zuchtkammer, und im Honiggenerator bringt es mehr Strom bei mehr Verbrauch.",
          ],
          tasks=[task_item("productivelib:upgrade_time", 1)],
          rewards=[reward_item("minecraft:clock", 2), reward_xp(5)],
          deps=["upgrades"], icon="productivelib:upgrade_time", section="first"),

    quest("simulator", 9.5, 1.4, "&bLass die Bienen zu Hause",
          subtitle="Simulator-Upgrade: Ausflüge nur noch gerechnet.",
          description=[
              "Erst das &6Anti-Teleport-Upgrade&r: Upgrade-Basis, vier &6Enderperlen&r an den Seiten, vier Honigwabenblöcke in den Ecken. Dann dieses in die Mitte, eine Enderperle oben, drei &6Lohenruten&r links, rechts und unten, Honigwabenblöcke in die Ecken: das &6Simulator-Upgrade&r.",
              "",
              "Die Bienen fliegen nicht mehr aus, der Ausflug wird nur berechnet. Die Blume muss dann direkt unter dem Stockeingang stehen, die Futterplatte versorgt drei Sorten auf einmal.",
              "",
              "&eKronwerke:&r Hunderte fliegender Bienen kosten den Server Leistung. Ein Bienenhaus mit Simulatoren ist leise, sauber und schnell.",
          ],
          tasks=[task_item("productivelib:upgrade_simulator", 1)],
          rewards=[reward_item("minecraft:blaze_rod", 2), reward_table("s2_common"), reward_xp(5)],
          deps=["upgrades"], icon="productivelib:upgrade_simulator", section="first"),

    # ---- neue Quests: Zentrifuge und Honig ---------------------------------------------
    quest("honey_generator", 15.5, 2.2, "&6Mach Strom aus Honig",
          subtitle="60 FE/t aus dem, was die Bienen ohnehin liefern.",
          description=[
              "&eRezept:&r Eisenbarren, &6Honigeimer&r, Eisenbarren oben, Eisenbarren, &6Ofen&r, Eisenbarren in der Mitte, drei Eisenbarren unten. Den Honigeimer machst du aus vier Honigflaschen und einem Eimer oder aus einem Honigblock und einem Eimer.",
              "",
              "Der &6Honiggenerator&r verbrennt &e2 mB Honig pro Tick&r und gibt dafür &d60 FE/t&r. Stell ihn an den Tank der Zentrifuge oder füll ihn per Rohr, Flasche, Eimer oder Honigblock.",
              "",
              "Ein Zeit-Upgrade hebt die Leistung bei mehr Verbrauch, ein Produktivitäts-Upgrade senkt den Verbrauch. Damit laufen Stromzentrifuge und Inkubator aus dem eigenen Bienenhaus.",
          ],
          tasks=[task_item("productivebees:honey_generator", 1)],
          rewards=[reward_item("minecraft:honey_bottle", 8), reward_table("s2_common"), reward_xp(5)],
          deps=["bottler"], icon="productivebees:honey_generator"),

    # ---- neue Quests: Gene -------------------------------------------------------------
    quest("gene_indexer", 21, 2.6, "&dSortier Gene mit dem Indexer",
          subtitle="Eine Kiste voller Proben, ein Signal.",
          description=[
              "&eRezept:&r Eisenbarren, &6Komparator&r, Eisenbarren oben, Eisenbarren, &6Werkbank&r, Eisenbarren in der Mitte, drei Eisenbarren unten.",
              "",
              "Der &6Gen-Indexer&r nimmt Genproben auf und führt mit einem Redstonesignal gleiche Gene zusammen, bis daraus reinere werden. So musst du nicht jede Probe einzeln in der Werkbank kombinieren.",
          ],
          tasks=[task_item("productivebees:gene_indexer", 1)],
          rewards=[reward_item("minecraft:comparator", 2), reward_xp(5)],
          deps=["gene_treat"], icon="productivebees:gene_indexer", optional=True),

    # ---- neue Quests: Zucht --------------------------------------------------------------
    quest("catcher", 2.5, 9.6, "&aStell einen Fänger auf",
          subtitle="Bienen fangen sich von selbst.",
          description=[
              "&eRezept:&r Eisenbarren, &6Erde&r, Eisenbarren oben, Eisenbarren, &6Werfer&r, Eisenbarren in der Mitte, drei Eisenbarren unten.",
              "",
              "Der &6Fänger&r (Catcher) steckt Bienen in seiner Umgebung in leere Käfige, die du ihm gibst. Mit Upgrades steuerst du ihn: Reichweite für mehr Fläche, Filter für bestimmte Arten, &6BaBee&r nur für Bienenkinder, &6AdultBee&r nur für erwachsene.",
              "",
              "&eTipp:&r Neben einem Zuchtgehege mit BaBee-Upgrade sammelt er den Nachwuchs ein, bevor er davonfliegt.",
          ],
          tasks=[task_item("productivebees:catcher", 1)],
          rewards=[reward_item("productivebees:bee_cage", 8), reward_xp(5)],
          deps=["breeding"], icon="productivebees:catcher", optional=True),
]

images = [
    banner("bees/title", "Productive Bees", 12, -4.6, height=1.75, kind="title", colour="nature"),
    banner("bees/first", "Erste Bienen", 3.75, -2.2, height=0.9, colour="nature"),
    banner("bees/centrifuge", "Zentrifuge und Honig", 12.5, -2.2, height=0.9, colour="brass"),
    banner("bees/genes", "Gene", 21, -2.2, height=0.9, colour="magic"),
    banner("bees/breeding", "Zucht", 2.5, 5, height=0.9, colour="nature"),
    banner("bees/resources", "Ressourcenbienen", 14.5, 5, height=0.9, colour="brass"),
    banner("bees/magic", "Magiebienen", 23.5, 5, height=0.9, colour="magic"),
    banner("bees/metalworks", "Productive Metalworks", 19, 11.6, height=0.9, colour="fire"),
]

chapter(C, "Productive Bees", "productivebees:advanced_oak_beehive", "world", quests, shape="circle", order=46, stage=2,
        subtitle=["Stufe 2. Wildnester, der Fortgeschrittene Bienenstock, Zucht, Zentrifuge, Gene und die Gießerei von Productive Metalworks."],
        images=images)
