"""Botania in stage 2: manasteel, mana pearls, the runic altar and its runes, the flowers that
need runes, the terrestrial agglomeration plate (two Create brass casings on Kronwerke, see
kubejs/server_scripts/tech_and_magic.js), terrasteel and the elven gateway. Elementium, pixie
dust and dreamwood stay locked until stage 3 (stage3.json)."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table,
                  reward_xp, banner, img, item_texture)

C = "botania_runes"


def block_img(name, size=32):
    """A flower or block picture from Botania's block textures."""
    return img(f"botania:textures/block/{name}.png", size, size)


quests = [
    # ---- Manastahl --------------------------------------------------------
    quest("welcome", 0, 0, "&bManastahl",
          subtitle="Stufe 2 ist offen. Eisen, getränkt in Mana.",
          description=[
              "Mit &6Stufe 2 (Messingwerk)&r zeigt das Manabecken, was es wirklich kann. Wirf einen &6Eisenbarren&r in ein Becken, und für &d3 000 Mana&r kommt er als &bManastahlbarren&r zurück. Ein Eisenblock wird für 27 000 Mana direkt zum Manastahlblock.",
              "",
              img(item_texture("botania:manasteel_ingot"), 32, 32),
              "",
              "Manastahl ist das Metall für alles, was jetzt kommt: Runen, Manatafel, Linsen, Pylonen, Werkzeuge und die Grundzutat von Terrastahl.",
              "",
              "&6Das Ziel am Obelisken:&r Für Stufe 3 will der Obelisk auf der Magieseite &e1 500 Manaperlen&r und &e100 Terrastahlbarren&r (die Zahlen passen sich der Spielerzahl an). Beides kommt aus diesem Kapitel. Zusammen sind das über &d60 Millionen Mana&r, also baut jetzt Blumen, so viele ihr könnt.",
              "",
              "&eTipp:&r Mekanik-Spieler brauchen deinen Manastahl ebenfalls, dazu gleich mehr.",
          ],
          tasks=[task_item("botania:manasteel_ingot", 8)],
          rewards=[reward_item("minecraft:iron_ingot", 16), reward_table("s2_common")],
          icon="botania:manasteel_ingot", size=2.0, shape="hexagon"),

    quest("mana_pearl", 2.7, -1.1, "&bManaperle",
          subtitle="Eine Enderperle, die glüht.",
          description=[
              "Eine &6Enderperle&r im Becken wird für &d6 000 Mana&r zur &bManaperle&r.",
              "",
              img(item_texture("botania:mana_pearl"), 32, 32),
              "",
              "Du brauchst sie für die &6Rune des Manas&r, die &6Manatafel&r und für jeden einzelnen &6Terrastahlbarren&r. Und der Obelisk will &e1 500&r Stück für das Stufe-2-Ziel. Das sind allein &d9 Millionen Mana&r, neun randvolle Becken.",
              "",
              "&eWoher die Perlen kommen:&r",
              "&e1.&r Endermen in der Oberwelt, nachts auf großen Ebenen.",
              "&e2.&r Der &cNether&r ist jetzt offen: Im &5Wirrwald&r wimmelt es von Endermen.",
              "&e3.&r Piglins tauschen gegen Gold gelegentlich Enderperlen ein.",
              "",
              "&eTipp:&r Ein &6Tolldorn&r auf einer Plattform im Wirrwald ist eine sehr faule Endermanfarm.",
          ],
          tasks=[task_item("botania:mana_pearl", 8)],
          rewards=[reward_item("minecraft:ender_pearl", 8)],
          deps=["welcome"], icon="botania:mana_pearl"),

    quest("mana_quartz", 2.7, 1.1, "&bManaquarz",
          subtitle="Nether-Quarz, blau gefärbt.",
          description=[
              "&6Netherquarz&r gibt es erst jetzt, mit dem Nether. Im Becken wird er für nur &d250 Mana&r zu &bManaquarz&r.",
              "",
              "Vier Manaquarz im Quadrat ergeben einen &6Manaquarzblock&r. Einen davon brauchst du für die &aTerrestrische Agglomerationsplatte&r, und jede der sieben Sündenrunen braucht einen Manaquarz.",
              "",
              "Den Rest kannst du verbauen: Manaquarzblöcke, Säulen und Ziegel sehen neben Lebestein hervorragend aus.",
          ],
          tasks=[task_item("botania:mana_quartz", 16)],
          rewards=[reward_item("minecraft:quartz", 16)],
          deps=["welcome"], icon="botania:mana_quartz"),

    quest("mana_tablet", 5, -1.1, "&bManatafel",
          subtitle="Ein halbes Manabecken in der Tasche.",
          description=[
              "Die &bManatafel&r craftest du aus &e8 Lebestein&r um einen &eManadiamanten&r oder eine &eManaperle&r. Sie speichert bis zu &d500 000 Mana&r.",
              "",
              "Wirf sie in ein Becken, um sie zu laden. Schleich-Rechtsklick mit dem Stab des Waldes auf das Becken dreht die Richtung um, dann entlädt die Tafel sich ins Becken. So transportierst du Mana ohne Verbreiter.",
              "",
              "Liegt die Tafel irgendwo in deinem Inventar, ziehen Manastahl-Werkzeuge, der Lebeholzbogen und viele Ruten ihr Mana daraus. Eine auf dem Boden liegende Tafel verschwindet übrigens nie.",
          ],
          tasks=[task_item("botania:mana_tablet", 1)],
          rewards=[reward_item("botania:livingrock", 16), reward_xp(5)],
          deps=["mana_pearl"], icon="botania:mana_tablet"),

    quest("band_of_mana", 7.2, -1.1, "&6Manaband",
          subtitle="Die Tafel als Ring.",
          description=[
              "Setz eine &6Manatafel&r mit &e4 Manastahlbarren&r zu einem Ring zusammen, und du bekommst das &6Manaband&r. Es funktioniert genau wie die Tafel, sitzt aber in einem Schmuckplatz statt im Inventar.",
              "",
              "Mit einem Terrastahlbarren lässt es sich später zum &6Größeren Manaband&r aufwerten, das rund 2 Millionen Mana hält.",
          ],
          tasks=[task_item("botania:band_of_mana", 1)],
          rewards=[reward_item("botania:manasteel_ingot", 4)],
          deps=["mana_tablet"], optional=True),

    quest("manasteel_gear", 5, 1.1, "&6Manastahl-Ausrüstung",
          subtitle="Werkzeug, das sich selbst repariert.",
          description=[
              "Aus Manastahl und &6Lebeholzzweigen&r baust du Werkzeuge und aus Manastahl allein eine Rüstung, mit denselben Mustern wie bei Eisen.",
              "",
              "Sie sind etwa so stark wie Eisen, halten aber länger, lassen sich besser verzaubern und &ereparieren sich selbst&r mit Mana aus einer Tafel oder einem Manaband in deinem Inventar.",
              "",
              "&eKleine Extras:&r Rechtsklick mit der Manastahl-Spitzhacke setzt eine Fackel aus deinem Inventar, die Axt pflanzt einen Setzling.",
          ],
          tasks=[task_item("botania:manasteel_pickaxe", 1)],
          rewards=[reward_item("botania:manasteel_ingot", 4)],
          deps=["welcome"], optional=True),

    quest("mekanism_tie", 7.2, 1.1, "Manastahl für Ingenieure",
          subtitle="Auf Kronwerke braucht Mekanism deine Blumen.",
          description=[
              "Auf Kronwerke hängen Technik und Magie zusammen. Die erste Mekanism-Maschine, der &aMetallurgische Infusionierer&r, braucht hier &e2 Manastahlbarren&r in der unteren Reihe statt zwei Eisenbarren.",
              "",
              "Das neue Rezept: oben Eisen, Ofen, Eisen; in der Mitte Redstone, Osmiumbarren, Redstone; unten Manastahl, Ofen, Manastahl.",
              "",
              "Ohne Infusionierer gibt es keinen Stahl, keine Schaltkreise und keine Mekanism-Maschinen. Wenn du Manastahl übrig hast, sprich mit den Technikern auf dem Server. Umgekehrt brauchst du bald Messing von ihnen, siehe Terrastahl.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["welcome"], icon="mekanism:metallurgic_infuser"),

    quest("mana_lens", 7.2, 3.3, "&6Manalinse",
          subtitle="Mach aus einem Manastoß ein Werkzeug.",
          description=[
              "Die einfache &6Manalinse&r besteht aus &e4 Manastahlbarren&r um einen Block &eGlas&r. Mit Rechtsklick setzt du sie in einen Verbreiter ein. Allein tut sie nichts, aber sie ist die Grundlage für viele Spezial-Linsen.",
              "",
              "Ein paar Beispiele: &eGeschwindigkeit&r (schneller, weniger Last), &eStärke&r (doppelt so viel Mana pro Stoß), &eWiderstand&r und &eEffizienz&r (weniger Verlust auf langen Wegen), &eBohrer&r (baut Blöcke ab), &eAbprall&r, &eSchaden&r. Zwei Linsen lassen sich mit einem Schleimball kombinieren.",
              "",
              "&eTipp:&r Für Linsen, die kein Mana abliefern sollen, nimm einen Impuls-Manaverbreiter. JEI zeigt alle Linsenrezepte.",
          ],
          tasks=[task_item("botania:mana_lens", 1)],
          rewards=[reward_item("minecraft:glass", 16)],
          deps=["mekanism_tie"], optional=True),

    # ---- Runen ------------------------------------------------------------
    quest("runic_altar", 10.5, 0, "&aRunenaltar",
          subtitle="Hier entstehen die Runen.",
          description=[
              "Der &aRunenaltar&r ist das Herz dieser Stufe. Rezept: &e5 Lebestein&r und ein &eManadiamant&r oder eine &eManaperle&r.",
              "",
              block_img("runic_altar_top"),
              "",
              "So stellst du eine Rune her:",
              "&e1.&r Leg die Zutaten auf den Altar, per Rechtsklick oder einfach draufwerfen.",
              "&e2.&r Richte einen Verbreiter mit gefülltem Becken dahinter auf den Altar. Der Stab zeigt dir, wie viel Mana noch fehlt.",
              "&e3.&r Ist genug Mana drin, wirf einen &6Lebestein&r darauf.",
              "&e4.&r Rechtsklick mit dem &aStab des Waldes&r, und die Rune springt heraus.",
              "",
              "Runen, die in einem Rezept stehen, sind &eKatalysatoren&r: Du bekommst sie nach dem Craften zurück. Ein Rechtsklick mit leerer Hand holt dieselben Zutaten noch einmal aus deinem Inventar. Ein Komparator gibt Stärke 1, solange der Altar Mana aufnimmt, und Stärke 2, wenn er fertig ist.",
              "",
              "Es gibt 16 Runen: vier Elemente, vier Jahreszeiten, sieben Sünden und die Rune des Manas.",
          ],
          tasks=[task_item("botania:runic_altar", 1)],
          rewards=[reward_item("botania:livingrock", 32), reward_table("s2_common")],
          deps=["welcome"], icon="botania:runic_altar", size=2.0, shape="square"),

    quest("rune_water", 13, -1.1, "&9Rune des Wassers",
          subtitle="Das erste Element.",
          description=[
              "Zutaten: &eManapuder&r, &eManastahlbarren&r, &eKnochenmehl&r, &eZuckerrohr&r und eine &eAngel&r. Kostet &d5 200 Mana&r und ergibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_water"), 32, 32),
              "",
              "Wasser steckt in der Terraplatte, in den Runen des Frühlings und des Winters, in der Narglibbe und in der Freihut.",
          ],
          tasks=[task_item("botania:rune_of_water", 2)],
          rewards=[reward_item("minecraft:sugar_cane", 16)],
          deps=["runic_altar"], icon="botania:rune_of_water"),

    quest("rune_fire", 15, -1.1, "&cRune des Feuers",
          subtitle="Ein Hauch Nether.",
          description=[
              "Zutaten: &eManapuder&r, &eManastahlbarren&r, &eNetherziegel&r, &eSchwarzpulver&r und &eKohle&r oder Holzkohle. Kostet &d5 200 Mana&r und ergibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_fire"), 32, 32),
              "",
              "Den Netherziegel brennst du aus Netherrack, das jetzt mit dem Nether erreichbar ist. Feuer brauchst du für die Terraplatte, die Thermalilie, die Gourmaryllis und die Exoflamme.",
          ],
          tasks=[task_item("botania:rune_of_fire", 2)],
          rewards=[reward_item("minecraft:gunpowder", 8)],
          deps=["runic_altar"], icon="botania:rune_of_fire"),

    quest("rune_earth", 13, 1.1, "&6Rune der Erde",
          subtitle="Stein, Schlamm und Pilz.",
          description=[
              "Zutaten: &eManapuder&r, &eManastahlbarren&r, &eStein&r, &eSchlamm&r und ein &ebrauner oder roter Pilz&r. Kostet &d5 200 Mana&r und ergibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_earth"), 32, 32),
              "",
              "&6Schlamm&r entsteht, wenn du eine Wasserflasche auf Erde leerst. Erde brauchst du für die Terraplatte, die Thermalilie, die Helitonie, die Rannawurzel und die Wirrbeere.",
          ],
          tasks=[task_item("botania:rune_of_earth", 2)],
          rewards=[reward_item("minecraft:mud", 8)],
          deps=["runic_altar"], icon="botania:rune_of_earth"),

    quest("rune_air", 15, 1.1, "&fRune der Luft",
          subtitle="Leicht wie eine Feder.",
          description=[
              "Zutaten: &eManapuder&r, &eManastahlbarren&r, ein beliebiger &eTeppich&r, eine &eFeder&r und ein &eFaden&r. Kostet &d5 200 Mana&r und ergibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_air"), 32, 32),
              "",
              "Luft brauchst du für die Terraplatte, die Trichtermalve, die Wirrbeere, die Freihut und die Rute der Lüfte, mit der du dich in die Luft schleuderst.",
          ],
          tasks=[task_item("botania:rune_of_air", 2)],
          rewards=[reward_item("minecraft:feather", 16)],
          deps=["runic_altar"], icon="botania:rune_of_air"),

    quest("rune_mana", 10.5, 2.7, "&dRune des Manas",
          subtitle="Reines Mana, in Stein gefasst.",
          description=[
              "Die &dRune des Manas&r steht außerhalb der Elemente: &e5 Manastahlbarren&r und &e1 Manaperle&r auf dem Altar, &d8 000 Mana&r.",
              "",
              img(item_texture("botania:rune_of_mana"), 32, 32),
              "",
              "Sie gehört in die &aTerrestrische Agglomerationsplatte&r, in die &6Rosa Arcana&r und in die &6Botanische Brauerei&r. Heb dir also mindestens zwei auf.",
          ],
          tasks=[task_item("botania:rune_of_mana", 1)],
          rewards=[reward_item("botania:mana_pearl", 2)],
          deps=["runic_altar", "mana_pearl"], icon="botania:rune_of_mana"),

    quest("rune_spring", 17.5, -1.1, "&aRune des Frühlings",
          subtitle="Wasser und Feuer ergeben Wachstum.",
          description=[
              "Zutaten: &e3 Setzlinge&r und &e1 Weizen&r, dazu die &eRunen des Wassers und des Feuers&r als Katalysatoren, die du zurückbekommst. Kostet &d8 000 Mana&r.",
              "",
              "Frühling steckt im &6Jaded-Amarant&r und in der &6Agrarnelke&r, außerdem im Terrastahlhelm.",
          ],
          tasks=[task_item("botania:rune_of_spring", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 8)],
          deps=["rune_water", "rune_fire"], icon="botania:rune_of_spring"),

    quest("rune_summer", 19.7, -1.1, "&eRune des Sommers",
          subtitle="Erde und Luft ergeben Wärme.",
          description=[
              "Zutaten: &e2 Sand&r, &e1 Schleimball&r und &e1 Melonenscheibe&r, dazu die &eRunen der Erde und der Luft&r als Katalysatoren. Kostet &d8 000 Mana&r.",
              "",
              "Sommer brauchst du für die &6Gourmaryllis&r, die &6Narglibbe&r, die &6Exoflamme&r und den Terrastahlharnisch.",
          ],
          tasks=[task_item("botania:rune_of_summer", 1)],
          rewards=[reward_item("minecraft:slime_ball", 4)],
          deps=["rune_earth", "rune_air"], icon="botania:rune_of_summer"),

    quest("rune_autumn", 17.5, 1.1, "&6Rune des Herbstes",
          subtitle="Feuer und Luft ergeben fallendes Laub.",
          description=[
              "Zutaten: &e3 Laubblöcke&r und &e1 Spinnenauge&r, dazu die &eRunen des Feuers und der Luft&r als Katalysatoren. Kostet &d8 000 Mana&r.",
              "",
              "Herbst steckt in einigen Funktionsblumen, in der Sündenrune der Trägheit und in der Terrastahlhose.",
          ],
          tasks=[task_item("botania:rune_of_autumn", 1)],
          rewards=[reward_item("minecraft:spider_eye", 4)],
          deps=["rune_fire", "rune_air"], optional=True, icon="botania:rune_of_autumn"),

    quest("rune_winter", 19.7, 1.1, "&bRune des Winters",
          subtitle="Wasser und Erde ergeben Frost.",
          description=[
              "Zutaten: &e2 Schneeblöcke&r, &e1 Wolle&r und ein ganzer &eKuchen&r, dazu die &eRunen des Wassers und der Erde&r als Katalysatoren. Kostet &d8 000 Mana&r.",
              "",
              "Winter ist Katalysator für drei der sieben Sündenrunen, darunter die Völlerei für den Mampftau, und steckt in den Terrastahlstiefeln.",
          ],
          tasks=[task_item("botania:rune_of_winter", 1)],
          rewards=[reward_item("minecraft:snow_block", 8)],
          deps=["rune_water", "rune_earth"], icon="botania:rune_of_winter"),

    quest("sin_runes", 22, 0, "&5Die Sündenrunen",
          subtitle="Sieben Runen für die mächtigsten Blumen.",
          description=[
              "Jede der sieben Sündenrunen kostet &e2 Manadiamanten&r und &e1 Manaquarz&r, dazu &d12 000 Mana&r und zwei Runen als Katalysatoren:",
              "",
              "&eWollust:&r Sommer und Luft. &eVöllerei:&r Winter und Feuer. &eGier:&r Frühling und Wasser. &eTrägheit:&r Herbst und Luft. &eZorn:&r Winter und Erde. &eNeid:&r Winter und Wasser. &eHochmut:&r Sommer und Feuer.",
              "",
              "In dieser Stufe brauchst du vor allem die &6Rune der Völlerei&r für den &6Mampftau&r. Die anderen gehören in Blumen und Geräte, die zum Teil erst mit Stufe 3 öffnen, zum Beispiel Orechid und Kekimurus.",
              "",
              "&cAchtung:&r Jede Sündenrune frisst zwei Manadiamanten. Die fehlen dir später beim Terrastahl, also nur bauen, was du auch benutzt.",
          ],
          tasks=[task_item("botania:rune_of_gluttony", 1)],
          rewards=[reward_item("botania:mana_diamond", 2), reward_table("s2_uncommon")],
          deps=["rune_winter"], optional=True, icon="botania:rune_of_gluttony"),

    quest("brewery", 13, 3.3, "&6Botanische Brauerei",
          subtitle="Tränke mit Mana statt Braustand.",
          description=[
              "Die &6Botanische Brauerei&r entsteht aus &e6 Lebestein&r, einem &eBraustand&r, der &eRune des Manas&r und einem &eManastahlblock&r.",
              "",
              "Leg eine &6Managlasphiole&r hinein (3 Managlas in V-Form ergeben 3 Phiolen), dann die Zutaten des Gebräus, und richte einen Verbreiter auf die Brauerei. Das fertige Gebräu springt dir direkt ins Inventar. Eine Phiole reicht für mehrere Schlucke.",
              "",
              "Gebräue sind stärkere Tränke mit festen Rezepten, zum Beispiel Geschwindigkeit II, Stärke II oder Eile II. Die Lexica listet alle.",
          ],
          tasks=[task_item("botania:botanical_brewery", 1)],
          rewards=[reward_item("minecraft:nether_wart", 8), reward_xp(5)],
          deps=["rune_mana"], optional=True, icon="botania:botanical_brewery"),

    # ---- Neue Blumen ------------------------------------------------------
    quest("thermalily", 0, 6.5, "&6Thermalilie",
          subtitle="Lava rein, sehr viel Mana raus.",
          description=[
              "Die &6Thermalilie&r ist die Lava-Schwester der Hydroangea: &e1 rotes&r und &e2 orange&r Blütenblätter, &eRune der Erde&r, &eRune des Feuers&r.",
              "",
              block_img("thermalily"),
              "",
              "Sie trinkt &cLava&r neben sich auf ihrer eigenen Höhe. Ein einziger Block reicht ihr für etwa &e30 Sekunden&r, in denen sie sehr viel Mana erzeugt. Danach kühlt sie ab, und diese Pause dauert zufällig zwischen &e20 Sekunden und 5 Minuten&r. Ein Komparator zeigt dir die letzte Pause: 20 Sekunden pro Stufe.",
              "",
              "&cAchtung:&r Lava, die sie während der Pause berührt, schluckt sie ohne Mana und startet die Pause neu. Gib ihr Lava also nur, wenn sie bereit ist.",
              "",
              "&eTipp:&r Mit Create wird sie voll automatisch: Ein &aSchlauchflaschenzug&r über einem riesigen Lavasee im Nether liefert endlos Lava, und ein offenes Rohrende setzt die Lava als Block neben die Blume.",
          ],
          tasks=[task_item("botania:thermalily", 1)],
          rewards=[reward_item("minecraft:lava_bucket", 1), reward_item("botania:orange_mystical_petal", 4)],
          deps=["rune_earth", "rune_fire"], icon="botania:thermalily", size=1.5, shape="square"),

    quest("gourmaryllis", 2.2, 6.5, "&6Gourmaryllis",
          subtitle="Ein Feinschmecker unter den Blumen.",
          description=[
              "Die &6Gourmaryllis&r braucht &e2 hellgraue&r, &e2 gelbe&r und &e1 rotes&r Blütenblatt, die &eRune des Feuers&r und die &eRune des Sommers&r.",
              "",
              "Sie frisst Essen, das in ihrer Nähe liegt, und verdaut immer nur ein Stück auf einmal. Wie lange das dauert und wie viel Mana es bringt, hängt am Nährwert: Ein Steak braucht vier Sekunden, ein Apfel zwei. Größere Mahlzeiten bringen mehr Mana, auch pro Sekunde.",
              "",
              "&eWichtig:&r Sie liebt &eAbwechslung&r. Immer dasselbe Essen bringt immer weniger. Viele verschiedene Gerichte bringen richtig viel.",
              "",
              "&eTipp:&r Farmer's Delight hat Dutzende Gerichte. Eine Küche, die per Create-Förderband reihum verschiedene Mahlzeiten vor die Blume legt, ist eine der stärksten Manaquellen dieser Stufe.",
          ],
          tasks=[task_item("botania:gourmaryllis", 1)],
          rewards=[reward_item("minecraft:cooked_beef", 16)],
          deps=["rune_summer", "rune_fire"], icon="botania:gourmaryllis"),

    quest("munchdew", 4.4, 6.5, "&6Mampftau",
          subtitle="Frisst ganze Baumkronen.",
          description=[
              "Der &6Mampftau&r braucht &e2 hellgrüne&r, &e2 rote&r und &e1 grünes&r Blütenblatt und die &5Rune der Völlerei&r.",
              "",
              "Er frisst alle &6Laubblöcke&r in seiner Umgebung und macht daraus eine ordentliche Menge Mana. Die Blätter lassen dabei nichts fallen, keine Setzlinge, keine Äpfel.",
              "",
              "Hat er alles in Reichweite gefressen, legt er eine Verdauungspause von etwa einer Minute ein.",
              "",
              "&eTipp:&r Pflanz ihn zwischen Bäume, die ständig nachwachsen: Setzlinge, Knochenmehl aus einem Werfer oder eine Agrarnelke daneben.",
          ],
          tasks=[task_item("botania:munchdew", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 16)],
          deps=["sin_runes"], optional=True, icon="botania:munchdew"),

    quest("rosa_arcana", 6.6, 6.5, "&6Rosa Arcana",
          subtitle="Erfahrung wird zu Mana.",
          description=[
              "Die &6Rosa Arcana&r braucht &e2 rosa&r, &e2 violette&r und &e1 hellgrünes&r Blütenblatt und die &dRune des Manas&r.",
              "",
              "Sie saugt &eErfahrungspunkte&r von Spielern in ihrer Nähe ab und macht daraus Mana. Sie nimmt auch Erfahrungskugeln auf dem Boden und zieht verzauberten Gegenständen ihre Verzauberungen heraus.",
              "",
              "&eTipp:&r Neben dem Ausgang einer Mob-Farm oder einer Tolldorn-Falle landet jede Erfahrungskugel direkt in deinem Becken. Und die vielen schlechten Verzauberungsbücher aus der Angel sind hier plötzlich Brennstoff.",
          ],
          tasks=[task_item("botania:rosa_arcana", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 8)],
          deps=["rune_mana"], icon="botania:rosa_arcana"),

    quest("narslimmus", 8.8, 6.5, "&6Narglibbe",
          subtitle="Schleim aus Schleimchunks.",
          description=[
              "Die &6Narglibbe&r braucht &e2 hellgrüne&r, &e2 grüne&r und &e1 schwarzes&r Blütenblatt, die &eRune des Sommers&r und die &eRune des Wassers&r.",
              "",
              "Sie fängt &aSchleime&r, die in einem &eSchleimchunk&r natürlich spawnen, und macht aus ihnen Mana. Je größer der Schleim, desto mehr.",
              "",
              "&eTipp:&r Such einen Schleimchunk (dort spawnen Schleime unterhalb von Höhe 40 auch fern von Sümpfen), bau darin eine flache Halle und pflanz die Narglibbe mitten hinein. Sie arbeitet dann Tag und Nacht, solange der Chunk geladen ist.",
          ],
          tasks=[task_item("botania:narslimmus", 1)],
          rewards=[reward_item("minecraft:slime_ball", 8)],
          deps=["rune_summer", "rune_water"], optional=True, icon="botania:narslimmus"),

    quest("jaded_amaranthus", 0, 8.8, "&6Jaded-Amarant",
          subtitle="Nie wieder Blumen suchen.",
          description=[
              "Der &6Jaded-Amarant&r braucht je &e1 violettes&r, &ehellgrünes&r und &egrünes&r Blütenblatt, die &eRune des Frühlings&r und eine &6Redstone-Wurzel&r.",
              "",
              "Versorgt aus einem Becken lässt er auf Gras in seiner Nähe ständig neue &6Mystische Blumen&r wachsen, in allen Farben.",
              "",
              "&eTipp:&r Kombiniere ihn mit einer Trichtermalve und einer Truhe, dann sammelt sich ein endloser Vorrat Blumen von selbst. Schluss mit dem Suchen nach der einen fehlenden Farbe.",
          ],
          tasks=[task_item("botania:jaded_amaranthus", 1)],
          rewards=[reward_item("botania:floral_fertilizer", 8)],
          deps=["rune_spring"], icon="botania:jaded_amaranthus"),

    quest("agricarnation", 2.2, 8.8, "&6Agrarnelke",
          subtitle="Ein Dünger, der nie ausgeht.",
          description=[
              "Die &6Agrarnelke&r braucht &e2 hellgrüne&r, &e1 grünes&r und &e1 gelbes&r Blütenblatt, die &eRune des Frühlings&r und eine &6Redstone-Wurzel&r.",
              "",
              "Sie verwandelt Mana in einen stetigen Wachstumsschub: Pflanzen in ihrer Nähe wachsen deutlich schneller. Felder, Zuckerrohr, Bäume, Mystische Blumen.",
              "",
              "&eTipp:&r Unter einer Create-Erntemaschine oder neben deiner Baumfarm verdoppelt sie grob den Ertrag, ohne einen Krümel Knochenmehl.",
          ],
          tasks=[task_item("botania:agricarnation", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16)],
          deps=["rune_spring"], icon="botania:agricarnation"),

    quest("hopperhock", 4.4, 8.8, "&6Trichtermalve",
          subtitle="Sammelt alles vom Boden auf.",
          description=[
              "Die &6Trichtermalve&r braucht &e2 graue&r und &e2 hellgraue&r Blütenblätter, die &eRune der Luft&r und eine &6Redstone-Wurzel&r.",
              "",
              "Sie sammelt Gegenstände in ihrer Umgebung ein und steckt sie in ein angrenzendes Inventar, etwa eine Truhe. Mana braucht sie nicht, aber mit Mana aus einem Becken wird ihre Reichweite größer.",
              "",
              "&eFiltern:&r Häng einen Rahmen mit einem Gegenstand an die Truhe, dann nimmt diese Truhe nur diesen Gegenstand. Truhen ohne Rahmen nehmen alles, beschriftete haben Vorrang.",
          ],
          tasks=[task_item("botania:hopperhock", 1)],
          rewards=[reward_item("minecraft:chest", 4)],
          deps=["rune_air"], icon="botania:hopperhock"),

    quest("rannuncarpus", 6.6, 8.8, "&6Rannawurzel",
          subtitle="Setzt Blöcke, wo sie hingehören.",
          description=[
              "Die &6Rannawurzel&r braucht &e2 orange&r und &e1 gelbes&r Blütenblatt, die &eRune der Erde&r und eine &6Redstone-Wurzel&r.",
              "",
              "Sie hebt platzierbare Gegenstände vom Boden auf und setzt sie in einem großen Umkreis als Blöcke. Aber nur auf einer bestimmten Blocksorte: Die legst du direkt unter den Boden, auf dem die Blume steht.",
              "",
              "&eTipp:&r Zusammen mit dem Reinen Gänseblümchen ergibt sie eine Lebestein-Fabrik: Steine landen auf dem Boden, die Rannawurzel setzt sie um die Gänseblümchen, fertiger Lebestein wird abgebaut und eingesammelt.",
          ],
          tasks=[task_item("botania:rannuncarpus", 1)],
          rewards=[reward_item("botania:livingrock", 16)],
          deps=["rune_earth"], optional=True, icon="botania:rannuncarpus"),

    quest("clayconia", 8.8, 8.8, "&6Helitonie",
          subtitle="Aus Sand wird Ton.",
          description=[
              "Die &6Helitonie&r braucht &e2 hellgraue&r, &e1 graues&r und &e1 türkises&r Blütenblatt und die &eRune der Erde&r.",
              "",
              "Sie befeuchtet &6Sand&r in ihrer Nähe und verwandelt ihn in Tonklumpen. Das kostet ein wenig Mana, aber nicht viel.",
              "",
              "Ton brauchst du für Ziegel, Blumentöpfe und bei Create für einige Bauteile. Mit einer Trichtermalve daneben landet er gleich in der Truhe.",
          ],
          tasks=[task_item("botania:clayconia", 1)],
          rewards=[reward_item("minecraft:sand", 32)],
          deps=["rune_earth"], optional=True, icon="botania:clayconia"),

    quest("exoflame", 11, 8.8, "&6Exoflamme",
          subtitle="Heizt Öfen mit Mana.",
          description=[
              "Die &6Exoflamme&r ist das Gegenstück zur Endoflamme: &e2 rote&r, &e1 graues&r und &e1 hellgraues&r Blütenblatt, die &eRune des Feuers&r und die &eRune des Sommers&r.",
              "",
              "Statt Brennstoff zu verbrennen, verbraucht sie Mana und heizt damit alle &6Öfen&r in ihrer Nähe. Die brennen dann ohne Kohle und schneller als normal.",
              "",
              "&eTipp:&r Eine Reihe Öfen um eine Exoflamme ist eine Schmelzerei ohne Brennstofflager.",
          ],
          tasks=[task_item("botania:exoflame", 1)],
          rewards=[reward_item("minecraft:furnace", 4)],
          deps=["rune_summer"], optional=True, icon="botania:exoflame"),

    quest("wards", 11, 6.5, "&6Wirrbeere und Freihut",
          subtitle="Zäune aus Magie.",
          description=[
              "Zwei Blumen, die Tiere und Monster an einer unsichtbaren Kreislinie festhalten, beide für ein wenig Mana:",
              "",
              "&6Wirrbeere&r (&e2 türkis, 1 grau, 1 hellgrau&r, Runen der Luft und der Erde): Hält alles in ihrem Kreis &edrin&r. Ideal für Weiden ohne Zaun.",
              "&6Freihut&r (&e2 rosa, 1 violett, 1 hellgrau&r, Runen des Wassers und der Luft): Hält alles &edraußen&r. Eine Freihut mitten in der Basis und kein Creeper kommt mehr hinein.",
          ],
          tasks=[task_item("botania:tangleberrie", 1), task_item("botania:jiyuulia", 1)],
          rewards=[reward_table("s2_common")],
          deps=["rune_air"], optional=True, icon="botania:jiyuulia"),

    # ---- Terrastahl -------------------------------------------------------
    quest("brass_casing", 15, 6.5, "&6Messing vom Ingenieur",
          subtitle="Terrastahl braucht auf Kronwerke die Technik.",
          description=[
              "Auf Kronwerke ist die &aTerrestrische Agglomerationsplatte&r an Create gekoppelt. Im Originalrezept liegen oben drei Lapislazuliblöcke, hier sind es &eein Lapisblock zwischen zwei Create-Messinggehäusen&r.",
              "",
              img("create:textures/block/brass_casing.png", 32, 32),
              "",
              "Ein &6Messinggehäuse&r entsteht, wenn du einen &6Messingbarren&r auf einen &6entrindeten Stamm&r oder entrindetes Holz anwendest (Rechtsklick oder per Create-Aufträger). Messing wiederum kommt aus dem Create-Mixer mit Lodernder Brennkammer, und die braucht auf Kronwerke zwei Quellsteine aus Ars Nouveau.",
              "",
              "Magie braucht Technik, Technik braucht Magie. Wenn du selbst keine Messinglinie hast, tausch mit jemandem, der eine hat: dein Manastahl gegen ihr Messing.",
          ],
          tasks=[task_item("create:brass_casing", 2)],
          rewards=[reward_item("create:brass_ingot", 4)],
          deps=["welcome"], icon="create:brass_casing"),

    quest("plate", 17.5, 6.5, "&aTerrestrische Agglomerationsplatte",
          subtitle="Die Schmiede für Terrastahl.",
          description=[
              "Das Rezept der &aTerraplatte&r auf Kronwerke:",
              "&eOben:&r Messinggehäuse, Lapislazuliblock, Messinggehäuse.",
              "&eMitte:&r Rune des Wassers, Manaquarzblock, Rune des Feuers.",
              "&eUnten:&r Rune der Erde, Rune des Manas, Rune der Luft.",
              "",
              "Die Runen sind hier ausnahmsweise &ckeine Katalysatoren&r, sie werden verbraucht. Plan also je eine Elementarrune und eine Rune des Manas nur für die Platte ein.",
              "",
              "Die Platte allein tut nichts. Sie muss auf einem Muster aus Lapis und Lebestein stehen, das zeigt die nächste Aufgabe.",
          ],
          tasks=[task_item("botania:terrestrial_agglomeration_plate", 1)],
          rewards=[reward_item("minecraft:lapis_block", 4), reward_table("s2_uncommon")],
          deps=["brass_casing", "rune_mana", "mana_quartz", "rune_water", "rune_fire", "rune_earth", "rune_air"],
          icon="botania:terrestrial_agglomeration_plate", size=2.0, shape="square"),

    quest("plate_base", 17.5, 9.2, "Das Fundament",
          subtitle="Ein Schachbrett aus Lapis und Lebestein.",
          description=[
              "Unter der Platte liegt ein 3x3-Feld:",
              "&eMitte und die vier Ecken:&r &6Lebestein&r (oder Schimmerstein).",
              "&eDie vier Kanten dazwischen:&r &9Lapislazuliblöcke&r.",
              "",
              "Die Platte steht direkt auf dem mittleren Lebestein. Auf der Terrastahl-Seite der Lexica kannst du das Muster als Vorschau in die Welt projizieren und Block für Block nachbauen.",
          ],
          tasks=[task_item("minecraft:lapis_block", 4), task_item("botania:livingrock", 5)],
          rewards=[reward_xp(5)],
          deps=["plate"], icon="minecraft:lapis_block"),

    quest("mana_spark", 15, 8.8, "&6Manafunke",
          subtitle="Mana ohne Strahl.",
          description=[
              "Ein &6Manafunke&r entsteht aus &e2 Blütenblättern&r, &e2 Lohenstaub&r und &e1 Goldklumpen&r. Lohenstaub gibt es jetzt, mit den Lohen im Nether.",
              "",
              "Setz einen Funken auf ein Manabecken und einen auf die Terraplatte. Dann zieht die Platte ihr Mana direkt und auf Abruf aus dem Becken, ohne Verbreiter und ohne Verlust. Mehrere Funken auf mehreren Becken beschleunigen die Herstellung.",
              "",
              "Schleich-Rechtsklick mit dem Stab entfernt einen Funken, ein normaler Rechtsklick zeigt, mit wem er verbunden ist. Funken verschiedener Farbe (mit Farbstoff gefärbt) reden nicht miteinander.",
          ],
          tasks=[task_item("botania:mana_spark", 2)],
          rewards=[reward_item("minecraft:blaze_powder", 4)],
          deps=["plate"], optional=True),

    quest("terrasteel", 20.5, 6.5, "&aTerrastahl",
          subtitle="Das stärkste Metall dieser Stufe.",
          description=[
              "Wirf je einen &6Manastahlbarren&r, eine &6Manaperle&r und einen &6Manadiamanten&r auf die fertige Platte. Dann beginnt sie, Mana zu ziehen, bis &d500 000 Mana&r drin sind: ein halbes, volles Manabecken für einen einzigen Barren.",
              "",
              img(item_texture("botania:terrasteel_ingot"), 32, 32),
              "",
              "&cAchtung:&r Hebst du während der Herstellung eine Zutat auf, bricht der Vorgang ab und &calles Mana ist verloren&r.",
              "",
              "Verbreiter, die auf die Platte zielen, funktionieren, Manafunken sind schneller. Neun Terrastahlklumpen ergeben einen Barren, neun Barren einen Block.",
              "",
              "Terrastahl brauchst du für das Elfenportal (als Klumpen), für Terraklinge und Terrastahlrüstung, und &e100 Barren&r für den Obelisken.",
          ],
          tasks=[task_item("botania:terrasteel_ingot", 2)],
          rewards=[reward_item("botania:mana_diamond", 2), reward_table("s2_uncommon")],
          deps=["plate_base"], icon="botania:terrasteel_ingot", size=2.5, shape="diamond"),

    quest("terra_gear", 20.5, 9.4, "&aTerraklinge und Terrastahlrüstung",
          subtitle="Netherit-Klasse, mit Mana repariert.",
          description=[
              "Die &aTerraklinge&r (2 Terrastahlbarren und ein Lebeholzzweig) ist so stark wie ein Netheritschwert und feuert beim Schlagen manchmal einen Strahl, der genauso viel Schaden macht wie ein Treffer.",
              "",
              "Die &aTerrastahlrüstung&r entsteht aus der Manastahlrüstung, Terrastahlbarren, Lebeholzzweigen und einer Jahreszeitenrune pro Teil. Sie kommt an Netherit heran und repariert sich wie Manastahl mit Mana.",
              "",
              "&cBedenke:&r Jeder Barren hier fehlt dem Obelisken. Rüste zuerst die Leute aus, die für den Server kämpfen.",
          ],
          tasks=[task_item("botania:terra_blade", 1)],
          rewards=[reward_xp(10)],
          deps=["terrasteel"], optional=True, icon="botania:terra_blade"),

    # ---- Alfheim ----------------------------------------------------------
    quest("glimmering", 14, 13.8, "&6Schimmerndes Lebeholz",
          subtitle="Lebeholz, das leuchtet.",
          description=[
              "Ein &6Lebeholzstamm&r und ein &6Glowstonestaub&r ergeben formlos einen &6Schimmernden Lebeholzstamm&r. Glowstone findest du jetzt im Nether an den Decken.",
              "",
              "Das Elfenportal braucht &e3 davon&r und dazu &e8 normale Lebeholzstämme&r. Welche Variante (Stamm, Holz, entrindet) du nimmst, ist egal.",
          ],
          tasks=[task_item("botania:glimmering_livingwood_log", 3)],
          rewards=[reward_item("minecraft:glowstone_dust", 8)],
          deps=["terrasteel"], icon="botania:glimmering_livingwood_log"),

    quest("mana_pylon", 16.3, 13.8, "&6Manapylon",
          subtitle="Ein Kristall, der Energie aus der Erde zieht.",
          description=[
              "Der &6Manapylon&r entsteht aus &e2 Goldbarren&r, &e2 Manastahlbarren&r und &e1 Manadiamanten&r.",
              "",
              "Neben einem Zaubertisch wirkt er wie viele Bücherregale: Schon &e2 Pylonen&r reichen für Stufe 30. Vor allem ist er aber die Basis für den &6Naturapylon&r.",
          ],
          tasks=[task_item("botania:mana_pylon", 2)],
          rewards=[reward_item("minecraft:gold_ingot", 8)],
          deps=["terrasteel"], icon="botania:mana_pylon"),

    quest("natura_pylon", 18.6, 13.8, "&aNaturapylon",
          subtitle="Er zapft die Becken für das Portal an.",
          description=[
              "Ein Manapylon, &e3 Terrastahlklumpen&r und ein &eEnderauge&r ergeben einen &aNaturapylon&r. Du brauchst mindestens &e2&r.",
              "",
              "Jeder Naturapylon steht &edirekt auf einem Manabecken&r. Beide Becken müssen im Umkreis von &e5 Blöcken&r um das Portal-Herzstück stehen (ein Würfel von 11x11x11). Das Portal zieht sein Mana gleichmäßig aus allen Becken mit Pylon.",
          ],
          tasks=[task_item("botania:natura_pylon", 2)],
          rewards=[reward_item("minecraft:ender_eye", 2)],
          deps=["mana_pylon"], icon="botania:natura_pylon"),

    quest("gateway_core", 21, 13.8, "&aElfenportal-Herzstück",
          subtitle="Das Tor nach Alfheim.",
          description=[
              "Das &aElfenportal-Herzstück&r entsteht aus &e6 Lebeholzstämmen&r und &e3 Terrastahlklumpen&r.",
              "",
              "So baust du das Portal, von vorne gesehen, 5 Blöcke breit und 5 hoch:",
              "&eUnten Mitte:&r das Herzstück, links und rechts davon je ein liegender Lebeholzstamm.",
              "&eOben:&r dieselbe Reihe, aber mit einem schimmernden Stamm in der Mitte.",
              "&eLinks und rechts:&r je drei stehende Stämme übereinander, der mittlere schimmernd.",
              "Innen bleibt ein 3x3-Feld Luft. Die Ecken bleiben frei.",
              "",
              "Dazu zwei Manabecken mit Naturapylonen darauf in der Nähe, und alle Becken gut gefüllt.",
          ],
          tasks=[task_item("botania:elven_gateway_core", 1)],
          rewards=[reward_item("botania:livingwood_log", 16), reward_table("s2_uncommon")],
          deps=["glimmering", "natura_pylon"], icon="botania:elven_gateway_core", size=1.75, shape="square"),

    quest("portal_open", 23.5, 13.8, "Das Tor öffnet sich",
          subtitle="Alfheim ist nicht mehr ganz so fern.",
          description=[
              "Rechtsklick mit dem &aStab des Waldes&r auf das Herzstück. Stimmt der Aufbau, leuchten die Pylonen auf und das Portal öffnet sich. Das kostet einmalig &d200 000 Mana&r aus den Becken mit Naturapylon.",
              "",
              "Durch das Portal passen nur Gegenstände, keine Spieler. Wirf etwas hinein, und die Elfen schicken dir ihre Gegenleistung zurück. Jeder Tausch kostet &d500 Mana&r. Läuft eines der Becken leer, schließt sich das Portal wieder.",
              "",
              "&eTipp:&r Stell ein Verbreiter-Netz auf, das die Portalbecken ständig nachfüllt, dann bleibt das Tor offen.",
          ],
          tasks=[task_checkmark("Portal geöffnet")],
          rewards=[reward_xp(10)],
          deps=["gateway_core"], icon="botania:natura_pylon", size=1.5),

    quest("elven_lexicon", 23.5, 16, "Wissen der Elfen",
          subtitle="Lass die Elfen dein Buch lesen.",
          description=[
              "Die Lexica weiß über Alfheim fast nichts, das Wissen der Elfen ist verloren. Aber vielleicht, wenn die Elfen einen Blick hineinwerfen könnten ...",
              "",
              "Wirf deine &6Lexica Botania&r ins offene Portal. Du bekommst sie mit dem &eWissen der Elfen&r zurück, und ein ganzer neuer Bereich im Buch wird lesbar.",
              "",
              "&eKleines Geheimnis:&r Wirf auch mal ein &6Brot&r hinein.",
          ],
          tasks=[task_checkmark("Lexica zurückbekommen")],
          rewards=[reward_item("minecraft:bread", 8)],
          deps=["portal_open"], optional=True, icon="botania:lexica_botania"),

    quest("elven_trade", 26, 13.8, "&aHandel mit Alfheim",
          subtitle="Was die Elfen jetzt schon tauschen.",
          description=[
              "Die Elfen tauschen gern Dinge aus ihrer Welt. In Stufe 2 kannst du davon schon benutzen:",
              "",
              "&6Managlas&r wird zu &6Elfenglas&r, fast unsichtbarem Glas mit wechselndem Muster.",
              "&6Netherquarz&r wird zu &6Elfenquarz&r, grünlichem Bauquarz.",
              "&6Manadiamant&r wird zu &6Drachenstein&r, dem Edelstein der Elfen.",
              "",
              "&cNoch gesperrt:&r Manastahl zu &6Elementium&r, Manaperlen zu &6Feenstaub&r und Lebeholz zu &6Traumholz&r gehören zu &6Stufe 3 (Stahlwerk)&r. Du kannst sie tragen, aber noch nicht benutzen. Das Elementium-Ziel von Stufe 3 wird genau hier gefarmt.",
          ],
          tasks=[task_item("botania:alfglass", 8), task_item("botania:elven_quartz", 8)],
          rewards=[reward_item("minecraft:quartz", 16), reward_table("s2_uncommon")],
          deps=["portal_open"], icon="botania:elven_quartz"),

    quest("dragonstone", 26, 16, "&dDrachenstein",
          subtitle="Der Edelstein der Elfen.",
          description=[
              "Ein &6Manadiamant&r ins Portal ergibt einen &dDrachenstein&r. Er steckt später in einigen der stärksten Geräte, etwa im Kristallbogen, in der Rute des Bifröst oder im Gaia-Manaverbreiter.",
              "",
              "Neun Drachensteine ergeben einen Drachensteinblock, einen hübschen Baublock. Aber jeder Diamant, den du hier eintauschst, fehlt beim Terrastahl.",
          ],
          tasks=[task_item("botania:dragonstone", 1)],
          rewards=[reward_item("minecraft:diamond", 1)],
          deps=["elven_trade"], optional=True),

    # ---- Fuer den Obelisken -----------------------------------------------
    quest("pearl_factory", 24.5, 6.5, "&bPerlen am Fließband",
          subtitle="Tausendfünfhundert Perlen wollen verdient sein.",
          description=[
              "Das Ziel: &e1 500 Manaperlen&r für den Obelisken, das sind &d9 000 000 Mana&r und 1 500 Enderperlen. Das schafft niemand allein, aber zu dreißig ist es gut machbar.",
              "",
              "&eSo wird daraus eine Fabrik:&r",
              "&e1.&r Eine Endermanfarm im Wirrwald oder in der Oberwelt, mit Tolldorn oder Schwert.",
              "&e2.&r Ein Trichter oder ein Create-Förderband wirft die Perlen in ein Becken, das von vielen Blumen gespeist wird.",
              "&e3.&r Eine Trichtermalve am Beckenrand fischt die fertigen Manaperlen wieder heraus und steckt sie in eine Truhe.",
              "",
              "Eine Truhe neben dem Obelisken, die du selbst gestellt hast, wird zu deinem Zulieferer: Alle zwei Sekunden holt der Obelisk heraus, was er brauchen kann.",
          ],
          tasks=[task_item("botania:mana_pearl", 64)],
          rewards=[reward_item("minecraft:ender_pearl", 16), reward_table("s2_uncommon")],
          deps=["terrasteel", "mana_pearl"], icon="botania:mana_pearl"),

    quest("terra_line", 27, 6.5, "&aTerrastahl in Serie",
          subtitle="Hundert Barren, jeder ein halbes Becken.",
          description=[
              "Das zweite Magieziel: &e100 Terrastahlbarren&r. Jeder braucht &d500 000 Mana&r plus je einen Manastahlbarren, eine Manaperle und einen Manadiamanten. Zusammen gut &d52 Millionen Mana&r, 100 Eisen, 100 Enderperlen und &e100 Diamanten&r.",
              "",
              "&eWas hilft:&r",
              "&e1.&r Viele Becken, jedes mit einem Manafunken, rund um die Platte.",
              "&e2.&r Mehrere Terraplatten, denn Messinggehäuse sind jetzt kein Problem mehr.",
              "&e3.&r Starke Blumen: Thermalilien an Lava, Gourmaryllis mit wechselndem Essen, Rosa Arcana an der Mob-Farm, Mampftau an der Baumfarm.",
              "",
              "&cAchtung:&r Nichts aufheben, solange die Platte arbeitet.",
          ],
          tasks=[task_item("botania:terrasteel_ingot", 8)],
          rewards=[reward_item("botania:mana_diamond", 4), reward_table("s2_uncommon")],
          deps=["terrasteel"], icon="botania:terrasteel_ingot"),

    quest("obelisk", 25.7, 9.2, "&dMagie für den Obelisken",
          subtitle="Das Messingwerk wartet auf seine Blumen.",
          description=[
              "Bring deine Manaperlen und deinen Terrastahl zum &6Obelisken&r an der Spawn. Rechtsklick legt den Stapel in deiner Hand ab, Schleich-Rechtsklick alles, was passt. Oder stell eine Truhe daneben und füll sie per Förderband.",
              "",
              "Die Technikseite braucht Messing und Präzisionsmechanismen, die Magieseite deine Perlen und deinen Terrastahl. Erst wenn beide voll sind, öffnet &6Stufe 3&r, und zwar mit einem gemeinsamen Event im Stream.",
              "",
              "Danach wartet in Alfheim das Elementium.",
          ],
          tasks=[task_checkmark("Abgeliefert")],
          rewards=[reward_table("s2_rare"), reward_xp(15)],
          deps=["pearl_factory", "terra_line"], icon="botania:terrasteel_block", size=2.0, shape="gear"),
]

images = [
    banner("botania_runes/title", "Botania: Runen", 13, -5.2, height=1.8, kind="title", colour="magic"),
    banner("botania_runes/manastahl", "Manastahl", 4.2, -2.7, height=0.9, colour="magic"),
    banner("botania_runes/runen", "Runen", 16.3, -2.7, height=0.9, colour="magic"),
    banner("botania_runes/blumen", "Neue Blumen", 5.5, 4.7, height=0.9, colour="nature"),
    banner("botania_runes/terrastahl", "Terrastahl", 18, 4.3, height=0.9, colour="nature"),
    banner("botania_runes/alfheim", "Alfheim", 20, 12.1, height=0.9, colour="magic"),
    banner("botania_runes/obelisk", "Für den Obelisken", 26, 4.3, height=0.9, colour="magic"),
]

chapter(C, "Botania: Runen", "botania:rune_of_mana", "magic", quests, shape="circle", order=11, stage=2,
        subtitle=["Stufe 2. Manastahl, Runen, Terrastahl und das Tor nach Alfheim."], images=images)
