"""Botania in stage 1: petals, the Pure Daisy, living blocks, the Petal Apothecary, the two open
generating flowers, spreaders, pools, mana infusion and the functional flowers without runes.
Manasteel, mana pearls, the mana tablet and the runic altar are locked until stage 2
(stage2.json) and live in botania_runes.py. manasteel_prep collects the stage 1 inputs of the
Nature's Aura manasteel ritual (kubejs/server_scripts/kronwerke/magic.js)."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table,
                  reward_xp, banner, img, item_texture)

C = "botania"


def block_img(name, size=32):
    """A flower or block picture from Botania's block textures."""
    return img(f"botania:textures/block/{name}.png", size, size)


quests = [
    # ---- Erste Blueten ----------------------------------------------------
    quest("welcome", 0, 0, "&aLexica Botania",
          subtitle="Ein Buch, ein Setzling und ein ganzer Garten voller Magie.",
          description=[
              "Willkommen bei &aBotania&r! Auf den ersten Blick ist das ein Blumenmod, im Kern ist es aber Technik aus Pflanzen: Besondere Blumen erzeugen &dMana&r, &6Manaverbreiter&r schießen es als Strahl durch die Luft, &6Manabecken&r speichern es und verwandeln Gegenstände, die du hineinwirfst, in bessere.",
              "",
              "Das Handbuch zu allem ist die &6Lexica Botania&r. Du craftest sie formlos aus einem &6Buch&r und einem beliebigen &6Setzling&r.",
              "",
              img(item_texture("botania:lexica_botania"), 32, 32),
              "",
              "&eTipp:&r Schleich und klick mit der Lexica auf einen Botania-Block, dann springt sie direkt zum passenden Eintrag. Einträge in &oKursivschrift&r sind die Grundlagen, lies die zuerst.",
              "",
              "Auf Kronwerke führt dich dieses Kapitel bis zum &6Manabecken&r und zur &6Manainfusion&r. Runenaltar, Manastahl und Terrastahl öffnen mit &6Stufe 2&r, sobald der Obelisk an der Spawn gefüllt ist. Dann geht es im Kapitel &aBotania: Runen&r weiter.",
          ],
          tasks=[task_item("botania:lexica_botania", 1)],
          rewards=[reward_item("minecraft:bone_meal", 16), reward_table("s1_common")],
          icon="botania:lexica_botania", size=2.0, shape="hexagon"),

    quest("petals", 2.5, 0, "&6Mystische Blumen",
          subtitle="Sechzehn Farben, die es nur hier gibt.",
          description=[
              "In fast allen Grasbiomen wachsen kleine Flecken &6Mystischer Blumen&r. Du erkennst sie am schwachen Leuchten und an den Funken, die um sie herum aufsteigen. Es gibt sie in allen &e16 Farben&r.",
              "",
              "Eine Blume ergibt im Crafting-Feld &e2 Blütenblätter&r, eine hohe Mystische Blume sogar &e4&r. Fast jedes Rezept in Botania ist eine Liste von Blütenblättern, also nimm von jeder Farbe mit, was du findest. Weiß brauchst du sofort, Braun, Rot und Hellgrau kurz danach für die Endoflamme.",
              "",
              img(item_texture("botania:white_mystical_petal"), 32, 32),
              "",
              "&eTipp:&r Setz ein Blütenblatt mit Rechtsklick auf Gras, dann wird es &evergraben&r. Knochenmehl darauf lässt eine hohe Blume in genau dieser Farbe wachsen. So vermehrst du eine seltene Farbe gezielt.",
              "",
              "&cAchtung:&r Blütenblätter lassen sich auch zu Farbstoff verarbeiten. Pass auf, dass du nicht versehentlich die Farben verbrauchst, die dir für eine Blume fehlen.",
          ],
          tasks=[task_item("botania:white_mystical_petal", 8, title="Weiße Blütenblätter")],
          rewards=[reward_item("minecraft:bone_meal", 32)],
          deps=["welcome"], icon="botania:white_mystical_petal"),

    quest("fertilizer", 2.5, 2.2, "&6Blumendünger",
          subtitle="Wenn die Wiese leer gepflückt ist.",
          description=[
              "&6Blumendünger&r craftest du formlos aus &e1 Knochenmehl&r und &e4 beliebigen Farbstoffen&r. Blütenblätter werden im Crafting-Feld direkt zu Farbstoff, du kannst also Petalen der Farben nehmen, die du gerade übrig hast.",
              "",
              "Rechtsklick mit dem Dünger auf Gras lässt ringsum ein paar neue &6Mystische Blumen&r in zufälligen Farben sprießen. Auf manchen Böden wachsen stattdessen oder zusätzlich &6Schimmernde Pilze&r.",
              "",
              "&eTipp:&r Leg dir neben der Basis ein kleines Blumenbeet an und dünge es regelmäßig. Dann erntest du Nachschub vor der Haustür, statt jedes Mal durch die Welt zu laufen.",
          ],
          tasks=[task_item("botania:floral_fertilizer", 4)],
          rewards=[reward_item("minecraft:bone_meal", 32)],
          deps=["petals"], optional=True),

    quest("pouch", 4.5, 2.2, "&6Blumenbeutel",
          subtitle="Sechzehn Farben, ein Inventarplatz.",
          description=[
              "Der &6Blumenbeutel&r entsteht aus &e5 Wolle&r und &e1 Blütenblatt&r. Er hält von jeder Farbe einen Stapel &6Mystischer Blumen&r und hoher Mystischer Blumen und sammelt neue Blumen automatisch ein, solange er irgendwo in deinem Inventar liegt.",
              "",
              "Hältst du den Beutel in der Haupthand, sammelt er nichts ein. Schleich und klick mit ihm auf eine Truhe, dann leert er seinen ganzen Inhalt hinein.",
              "",
              "Später kannst du ihn mit &6Manapuder&r zum &6Blütenblattbeutel&r aufwerten, der Blumen gleich in Blütenblätter zerlegt.",
          ],
          tasks=[task_item("botania:flower_pouch", 1)],
          rewards=[reward_xp(3)],
          deps=["petals"], optional=True),

    quest("apothecary", 5, 0, "&aBlütenapotheke",
          subtitle="Hier werden besondere Blumen gebraut.",
          description=[
              "Die &aBlütenapotheke&r ist deine erste Botania-Maschine. Rezept: &e6 Bruchstein&r und &e1 Blütenblatt&r in beliebiger Farbe.",
              "",
              "So benutzt du sie:",
              "&e1.&r Stell sie hin und füll sie mit &bWasser&r: Rechtsklick mit einem Wassereimer oder den Eimer einfach hineinwerfen.",
              "&e2.&r Wirf die Blütenblätter des Rezepts hinein (Taste Q, während du daraufschaust). Sie schwimmen sichtbar im Wasser.",
              "&e3.&r Wirf zum Schluss einen &6Samen&r hinein, zum Beispiel Weizensamen. Dann springt die fertige Blume heraus und das Wasser ist verbraucht.",
              "",
              "Ein Rechtsklick mit leerer Hand nimmt das zuletzt eingeworfene Teil wieder heraus. Welche Blume welche Blätter braucht, zeigen dir die Lexica und JEI.",
              "",
              "&eTipp:&r Bis zu 20 Sekunden nach einer fertigen Blume holt ein Rechtsklick mit leerer Hand, nachdem du Wasser nachgefüllt hast, dieselben Zutaten noch einmal aus deinem Inventar. So baust du mehrere gleiche Blumen in Sekunden.",
              "",
              "&cAchtung:&r Mit &cLava&r gefüllt wird die Apotheke zum Verbrennungsofen und vernichtet alles, was hineinfällt.",
          ],
          tasks=[task_item("botania:petal_apothecary", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16), reward_item("minecraft:water_bucket", 1)],
          deps=["petals"], icon="botania:petal_apothecary", size=1.5, shape="square"),

    quest("pure_daisy", 7.5, 0, "&aReines Gänseblümchen",
          subtitle="Die wichtigste Blume, die du je pflanzen wirst.",
          description=[
              "Das &aReine Gänseblümchen&r braucht nur &e4 weiße Blütenblätter&r in der Apotheke, und ohne es geht in Botania nichts.",
              "",
              block_img("pure_daisy"),
              "",
              "Pflanz es auf Gras oder Erde und stell Blöcke auf die &e8 Felder rundherum&r, auf derselben Höhe wie die Blume. Nach etwa einer Minute hat es alle acht gleichzeitig verwandelt:",
              "&6Stein&r wird zu &6Lebestein&r, jeder &6Holzstamm&r wird zu einem &6Lebeholzstamm&r.",
              "",
              "Es kann noch mehr: Netherrack wird zu Bruchstein, Seelensand zu Sand, Eis zu Packeis und Packeis zu Blaueis, ein Tropfsteinblock zu Calcit, eine Wasserquelle zu Schnee.",
              "",
              "&cAchtung:&r Es muss &cStein&r sein, kein Bruchstein. Brenn Bruchstein im Ofen oder bau mit Behutsamkeit ab.",
              "",
              "&eTipp:&r Bau gleich zwei oder drei Gänseblümchen, du brauchst Unmengen von beidem. Ein Create-Ventilator, der durch Lava bläst, brennt Bruchstein am Fließband zu Stein. Mit einer Spitzhacke in der einen und Stein in der anderen Hand tauschst du die fertigen acht Blöcke in wenigen Sekunden aus.",
          ],
          tasks=[task_item("botania:pure_daisy", 1)],
          rewards=[reward_item("minecraft:stone", 32), reward_item("minecraft:oak_log", 16)],
          deps=["apothecary"], icon="botania:pure_daisy", size=2.0, shape="hexagon"),

    quest("livingwood", 10, -1.2, "&6Lebeholz",
          subtitle="Holz, das Mana leiten kann.",
          description=[
              "Jeder Stamm, den das Gänseblümchen berührt, wird zum &6Lebeholzstamm&r. Daraus baust du alles, was Mana bewegt: den &6Manaverbreiter&r (6 Stämme), den &6Lebeholzzweig&r für den Stab des Waldes und die &6Lebeholzbretter&r für die Offene Kiste.",
              "",
              "Vier Stämme ergeben im Quadrat drei Blöcke &6Lebeholz&r, das rundum Rinde zeigt. Für das Elfenportal in Stufe 3 brauchst du später acht Lebeholzstämme und drei schimmernde Varianten, und zwei &6Lebeholzzweige&r stecken in jedem Ritual für Manastahl. Leg also ruhig einen Vorrat an.",
              "",
              "&eTipp:&r Jede Holzsorte funktioniert, auch Stämme aus dem Nether oder aus anderen Mods.",
          ],
          tasks=[task_item("botania:livingwood_log", 16)],
          rewards=[reward_item("minecraft:oak_log", 32)],
          deps=["pure_daisy"], icon="botania:livingwood_log"),

    quest("livingrock", 10, 1.2, "&6Lebestein",
          subtitle="Der Stein, aus dem Becken und Altäre sind.",
          description=[
              "Stein neben dem Gänseblümchen wird zu &6Lebestein&r. Du brauchst ihn in rauen Mengen: &e5&r für jedes &6Manabecken&r, &e4&r für den &6Runenaltar&r in Stufe 2 (dazu ein Messingbarren), &e8&r für jede &6Manatafel&r und noch mehr unter der Terrestrischen Agglomerationsplatte.",
              "",
              "&eTipp:&r Stell die acht Steine um die Blume, geh eine Minute etwas anderes erledigen und tausch dann alle acht auf einmal aus. Mehrere Gänseblümchen nebeneinander, jedes mit eigenem Ring, vervielfachen die Ausbeute.",
          ],
          tasks=[task_item("botania:livingrock", 32)],
          rewards=[reward_item("minecraft:stone", 64), reward_table("s1_common")],
          deps=["pure_daisy"], icon="botania:livingrock"),

    quest("wand", 12.5, 0, "&aStab des Waldes",
          subtitle="Verbindet, dreht und misst alles in Botania.",
          description=[
              "Der &aStab des Waldes&r ist dein wichtigstes Werkzeug. Du brauchst zuerst &6Lebeholzzweige&r (2 Lebeholzstämme diagonal ergeben einen Zweig), dann legst du &e3 Zweige&r und &e2 Blütenblätter&r schräg ins Crafting-Feld. Die Farben der Blätter bestimmen die Farbe des Stabs.",
              "",
              img(item_texture("botania:wand_of_the_forest"), 32, 32),
              "",
              "Der Stab hat zwei Modi, die du mit Schleich-Rechtsklick in die Luft wechselst:",
              "&eBindemodus:&r Schleich-Rechtsklick auf einen Verbreiter oder eine Blume wählt ihn aus, ein zweiter Schleich-Rechtsklick auf ein Ziel verbindet beide.",
              "&eFunktionsmodus:&r Schleich-Rechtsklick dreht Blöcke, zum Beispiel einen Verbreiter, in Richtung der angeklickten Seite.",
              "",
              "Wenn du den Stab in der Hand hältst und auf einen Verbreiter, ein Becken oder eine Blume schaust, siehst du deren &dMana&r. Verbreiter zeigen dann außerdem ihren Zielstrahl.",
          ],
          tasks=[task_item("botania:wand_of_the_forest", 1)],
          rewards=[reward_item("botania:livingwood_log", 8), reward_xp(5)],
          deps=["livingwood"], icon="botania:wand_of_the_forest", size=1.5, shape="square"),

    quest("deco", 12.5, 2.4, "Bauen mit Lebestein",
          subtitle="Magie darf auch gut aussehen.",
          description=[
              "Lebestein und Lebeholz sind nicht nur Rohstoffe. Im Crafting-Feld oder am Steinschneider werden daraus &6Polierter Lebestein&r, &6Lebesteinziegel&r, bemooste Ziegel, Stufen, Treppen, Mauern und Lebeholzbretter.",
              "",
              "Ein Garten aus hellem Lebestein mit schimmernden Blumen dazwischen ist schnell das schönste Gebäude auf dem Server. Gebaut wird auf Kronwerke nie gesperrt, also leg los.",
          ],
          tasks=[task_item("botania:livingrock_bricks", 16)],
          rewards=[reward_item("botania:livingrock", 16)],
          deps=["livingrock"], optional=True),

    # ---- Mana erzeugen ----------------------------------------------------
    quest("gen_intro", 0, 6.5, "Erzeugende Blumen",
          subtitle="Mana kommt aus Blumen, nicht aus Kabeln.",
          description=[
              "&aErzeugende Blumen&r machen aus etwas, das du ihnen gibst, &dMana&r: aus Brennstoff, Wasser, später aus Lava, Blättern, Essen oder Erfahrung.",
              "",
              "Jede dieser Blumen hat einen kleinen Puffer. Sie gibt ihr Mana an den nächsten &6Manaverbreiter&r in höchstens &e6 Blöcken&r Entfernung ab. Beim Pflanzen verbindet sie sich von selbst mit dem nächsten Verbreiter, mit dem Stab des Waldes im Bindemodus kannst du sie umhängen.",
              "",
              "In &6Stufe 1&r sind genau zwei davon offen, denn alle anderen brauchen Runen aus dem Runenaltar:",
              "&6Endoflamme&r: verbrennt Brennstoff. Dein Arbeitspferd.",
              "&6Hydroangea&r: trinkt stehendes Wasser. Günstig, aber sie verwelkt.",
              "",
              "Mit Stufe 2 kommen Thermalilie, Mampftau, Gourmaryllis, Narglibbe und Rosa Arcana dazu, die deutlich mehr Mana liefern.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["wand"], icon="botania:endoflame"),

    quest("endoflame", 2.5, 6.5, "&6Endoflamme",
          subtitle="Kohle rein, Mana raus.",
          description=[
              "Die &6Endoflamme&r ist die erste echte Manaquelle. Rezept in der Apotheke: &e2 braune&r, &e1 rotes&r und &e1 hellgraues&r Blütenblatt.",
              "",
              block_img("endoflame"),
              "",
              "Sie saugt brennbare Gegenstände auf, die in bis zu &e3 Blöcken&r Entfernung auf dem Boden liegen, immer einen nach dem anderen. Jedes Stück brennt halb so lange wie in einem Ofen und liefert dabei &d3 Mana pro Tick&r. Ein Stück &6Kohle&r oder &6Holzkohle&r bringt so rund &d2 400 Mana&r in 40 Sekunden, danach macht sie zwei Sekunden Pause.",
              "",
              "&cWas nicht geht:&r Brennstoff, der im Ofen etwas zurücklässt (ein Lavaeimer hinterlässt einen Eimer), frisst sie nicht. Und ist ihr kleiner Puffer von 300 Mana voll, weil kein Verbreiter abholt, nimmt sie nichts Neues mehr an.",
              "",
              "&eTipp:&r Holz, Kohle aus der Mine oder Holzkohle aus einer Baumfarm: alles funktioniert. Eine Kohle verbrennt gleichmäßig, ein Kohleblock verschwendet nichts, dauert aber entsprechend lange.",
          ],
          tasks=[task_item("botania:endoflame", 1)],
          rewards=[reward_item("minecraft:coal", 32)],
          deps=["gen_intro"], icon="botania:endoflame", size=1.5, shape="square"),

    quest("hydroangeas", 2.5, 8.7, "&6Hydroangea",
          subtitle="Trinkt Wasser und macht daraus Mana.",
          description=[
              "Die &6Hydroangea&r braucht &e2 blaue&r und &e2 türkise&r Blütenblätter. Sie trinkt &bstehende Wasserquellen&r in einem 3x3-Feld um sich herum, auf ihrer eigenen Höhe.",
              "",
              block_img("hydroangeas"),
              "",
              "So baust du sie: Pflanz sie in die Mitte und füll die acht Felder rundherum mit Wasser. Weil jede Quelle Nachbarquellen hat, fließt ein getrunkener Block sofort nach, und die Blume trinkt ohne Ende.",
              "",
              "Jeder Wasserblock bringt nur ein wenig Mana. Bei &bRegen&r arbeitet sie doppelt so schnell. Nach rund &c72 000 Ticks&r (etwa eine Stunde Spielzeit, drei Minecraft-Tage) &cverwelkt&r sie.",
              "",
              "Sie ist ein guter Anfang, wenn du gerade keine Kohle hast. Für eine dauerhafte Farm nimm Endoflammen.",
          ],
          tasks=[task_item("botania:hydroangeas", 1)],
          rewards=[reward_item("minecraft:water_bucket", 1), reward_item("botania:blue_mystical_petal", 4)],
          deps=["gen_intro"], optional=True),

    quest("spreader", 5, 6.5, "&aManaverbreiter",
          subtitle="Schießt Mana von A nach B.",
          description=[
              "Der &aManaverbreiter&r holt das Mana aus deinen Blumen und schießt es als &dManastoß&r zu seinem Ziel. Rezept: &e6 Lebeholzstämme&r, &e1 Kupferbarren&r und &e1 Blütenblatt&r.",
              "",
              "&e1.&r Stell ihn höchstens 6 Blöcke von deinen erzeugenden Blumen entfernt auf. Neu gepflanzte Blumen binden sich von selbst an den nächsten Verbreiter.",
              "&e2.&r Nimm den Stab des Waldes im Bindemodus, schleich-klick auf den Verbreiter und dann auf das Ziel, zum Beispiel ein Manabecken.",
              "&e3.&r Solange das Ziel Mana aufnehmen kann, feuert der Verbreiter. Ein neuer Stoß startet erst, wenn der letzte angekommen ist.",
              "",
              "Stöße verlieren nach einer Weile Mana. Wenn du den Stab hältst, zeigen Funken im Zielstrahl, wo der Verlust beginnt. Halte die Wege also kurz.",
              "",
              "&eTipp:&r Ein Redstone-Signal hält den Verbreiter an. Rechtsklick mit Wolle gibt ihm eine Hülle, die das Geräusch dämpft, sehr angenehm bei vielen Verbreitern.",
          ],
          tasks=[task_item("botania:mana_spreader", 1)],
          rewards=[reward_item("botania:livingwood_log", 8), reward_item("minecraft:copper_ingot", 4)],
          deps=["endoflame"], icon="botania:mana_spreader", size=1.75, shape="square"),

    quest("open_crate", 5, 8.7, "&6Offene Kiste",
          subtitle="Die Endoflamme füttert sich selbst.",
          description=[
              "Die &6Offene Kiste&r ist eine Kiste mit einem Loch im Boden: &e7 Lebeholzbretter&r in U-Form. Alles, was ein Trichter hineinschiebt, fällt direkt darunter auf den Boden.",
              "",
              "Stell sie zwei Blöcke über den Boden neben deine Endoflammen und häng eine Truhe mit Kohle und einen Trichter darüber. Schon brennt die Farm, ohne dass du daneben stehen musst.",
              "",
              "&cAchtung:&r Items auf dem Boden verschwinden nach fünf Minuten. Wirf nicht mehr ab, als die Blumen fressen. Eine Druckplatte unter der Abwurfstelle, die den Trichter sperrt, solange noch Kohle daliegt, löst das Problem.",
              "",
              "&eTipp:&r Ein Create-Förderband, das über dem Blumenbeet endet, wirft Kohle ebenfalls ab. Mit einem Andesit-Trichter am Band holst du sie aus einem Lager.",
          ],
          tasks=[task_item("botania:open_crate", 1)],
          rewards=[reward_item("minecraft:hopper", 1), reward_item("minecraft:coal", 16)],
          deps=["spreader"], optional=True),

    # ---- Mana speichern ---------------------------------------------------
    quest("pool", 9, 6.5, "&aManabecken",
          subtitle="Eine Million Mana an einem Ort.",
          description=[
              "Das &aManabecken&r speichert &dMana&r: bis zu &d1 000 000&r. Es besteht nur aus &e5 Lebestein&r in U-Form.",
              "",
              "Richte deinen Verbreiter mit dem Stab auf das Becken, und die Blumen füllen es. Der Stab zeigt dir den Füllstand, ein Komparator daneben gibt ihn als Redstone-Signal aus.",
              "",
              "Was das Becken kann:",
              "&eManainfusion:&r Wirf einen passenden Gegenstand hinein, und wenn genug Mana da ist, verwandelt er sich. Glas wird zu Managlas, ein Diamant zum Manadiamanten.",
              "&eFunktionsblumen versorgen:&r Blumen, die Mana verbrauchen, zapfen das nächste Becken in bis zu 10 Blöcken an.",
              "&eWeiterleiten:&r Ein Verbreiter direkt neben dem Becken füllt sich daraus und kann das Mana weiterschießen.",
              "",
              "&eTipp:&r Ein Rechtsklick mit einem Blütenblatt färbt das Becken ein, ein Tonklumpen wäscht die Farbe wieder ab. Praktisch, wenn mehrere Becken nebeneinander stehen.",
              "",
              "Alles Mana, das du jetzt sammelst, bleibt im Becken. In Stufe 2 brauchst du sehr, sehr viel davon.",
          ],
          tasks=[task_item("botania:mana_pool", 1)],
          rewards=[reward_item("botania:livingrock", 16), reward_table("s1_uncommon")],
          deps=["spreader"], icon="botania:mana_pool", size=2.5, shape="hexagon"),

    quest("diluted_pool", 9, 9.3, "&6Verdünntes Manabecken",
          subtitle="Klein, billig und schnell voll.",
          description=[
              "Aus &e5 Lebesteinstufen&r baust du ein &6Verdünntes Manabecken&r. Es speichert nur &d10 000 Mana&r, ein Hundertstel eines normalen Beckens.",
              "",
              "Es taugt als kleiner Puffer neben einer einzelnen Funktionsblume oder für billige Infusionen wie Managlas. Weil es so schnell voll ist, siehst du daran auch gut, ob eine Blume überhaupt arbeitet.",
              "",
              "&cAchtung:&r Wenn irgendwo im Buch oder in der Lexica von einem &6Manabecken&r die Rede ist, ist das große gemeint. Ein Manadiamant (10 000 Mana) leert ein verdünntes Becken auf einen Schlag.",
          ],
          tasks=[task_item("botania:diluted_mana_pool", 1)],
          rewards=[reward_xp(3)],
          deps=["pool"], optional=True),

    quest("manastar", 11.5, 7.7, "&6Manastern",
          subtitle="Gewinn oder Verlust? Er sagt es dir.",
          description=[
              "Der &6Manastern&r ist eine Messblume aus je einem &ehellblauen&r, &egrünen&r, &eroten&r und &etürkisen&r Blütenblatt.",
              "",
              "Pflanz ihn direkt neben ein Manabecken. Leuchtet er &cRot&r, verliert das Becken Mana, leuchtet er &bBlau&r, kommt mehr hinein als heraus. Er aktualisiert sich alle paar Sekunden.",
              "",
              "&eTipp:&r Der Stab des Waldes zeigt bei einem großen Becken den Balken nur sehr grob. Der Manastern verrät dir sofort, ob deine Farm mit deinem Verbrauch mithält.",
          ],
          tasks=[task_item("botania:manastar", 1)],
          rewards=[reward_item("botania:light_blue_mystical_petal", 4), reward_xp(3)],
          deps=["pool"], icon="botania:manastar"),

    quest("pulse_spreader", 11.5, 5.4, "&6Impuls-Manaverbreiter",
          subtitle="Feuert nur, wenn du es sagst.",
          description=[
              "Ein Manaverbreiter plus &e1 Redstone&r ergibt den &6Impuls-Manaverbreiter&r. Er feuert bei jedem &eRedstone-Impuls&r einen Stoß, ganz egal, ob er ein Ziel hat.",
              "",
              "Jetzt ist das vor allem ein Spielzeug. Mit den &6Manalinsen&r aus Stufe 2 wird er zum Werkzeug: Linsen können Blöcke abbauen, Gegenstände schieben oder Mobs treffen.",
          ],
          tasks=[task_item("botania:pulse_mana_spreader", 1)],
          rewards=[reward_item("minecraft:redstone", 16)],
          deps=["pool"], optional=True),

    quest("turntable", 13.7, 5.4, "&6Verbreiter-Drehscheibe",
          subtitle="Ein Verbreiter, der sich im Kreis dreht.",
          description=[
              "Die &6Verbreiter-Drehscheibe&r entsteht aus &e8 Lebeholzstämmen&r um einen &eKlebrigen Kolben&r. Ein Verbreiter direkt darüber dreht sich langsam im Kreis und verteilt seine Stöße reihum.",
              "",
              "Ein Redstone-Signal hält die Scheibe an. Rechtsklick mit dem Stab des Waldes ändert die Geschwindigkeit, Schleich-Rechtsklick die Drehrichtung.",
          ],
          tasks=[task_item("botania:spreader_turntable", 1)],
          rewards=[reward_xp(3)],
          deps=["pulse_spreader"], optional=True),

    # ---- Mana-Infusion ----------------------------------------------------
    quest("managlass", 0, 13.5, "&6Managlas",
          subtitle="Deine erste Infusion.",
          description=[
              "Zeit, das Becken zu benutzen. Wirf farbloses &6Glas&r hinein: Jeder Block kostet nur &d150 Mana&r und kommt als &6Managlas&r zurück, klar und nahtlos.",
              "",
              "So funktioniert jede &eManainfusion&r: Gegenstand ins Becken werfen, und solange genug Mana für ein Stück da ist, wird es verwandelt. Ein ganzer Stapel wird Stück für Stück umgewandelt, bis Stapel oder Mana alle sind.",
              "",
              "Managlas brauchst du für Phiolen in der Botanischen Brauerei und später als Tauschware beim Elfenportal, das mit Stufe 3 öffnet.",
              "",
              "&eTipp:&r JEI zeigt dir unter dem Manabecken alle Infusionen mit ihrem Manapreis.",
          ],
          tasks=[task_item("botania:managlass", 8)],
          rewards=[reward_item("minecraft:glass", 32)],
          deps=["pool"], icon="botania:managlass", size=1.5, shape="square"),

    quest("mana_powder", 2.5, 13.5, "&6Manapuder",
          subtitle="Staub, der nach Magie riecht.",
          description=[
              "&6Manapuder&r entsteht, wenn du &eFarbstoff&r (400 Mana) oder &eSchwarzpulver&r, &eRedstone&r oder &eZucker&r (je 500 Mana) ins Becken wirfst.",
              "",
              "In Stufe 1 brauchst du es für den &6Blütenblattbeutel&r. In Stufe 2 steckt in jeder der vier Elementarrunen ein Manapuder. Übrige Blütenblätter werden im Crafting-Feld zu Farbstoff, und Farbstoff wird im Becken zu Puder: So verwertest du Farben, die du gerade nicht brauchst.",
              "",
              "&eTipp:&r Leg jetzt schon zwei Dutzend zur Seite. Der Runenaltar frisst in den ersten Stunden von Stufe 2 viel davon.",
          ],
          tasks=[task_item("botania:mana_powder", 16)],
          rewards=[reward_item("minecraft:sugar_cane", 16)],
          deps=["managlass"]),

    quest("mana_string", 2.5, 15.7, "&6Manainfundierter Faden",
          subtitle="Faden, der Magie trägt.",
          description=[
              "Ein normaler &6Faden&r im Becken wird für &d1 250 Mana&r zum &6Manainfundierten Faden&r.",
              "",
              "Daraus entstehen der &6Lebeholzbogen&r und &6Managewebestoff&r (vier Fäden im Quadrat), das Tuch für Botanias Magierrüstung. Spinnen aus einer Spinnenfarm liefern genug Nachschub.",
          ],
          tasks=[task_item("botania:mana_string", 8)],
          rewards=[reward_item("minecraft:string", 16)],
          deps=["mana_powder"], optional=True),

    quest("livingwood_bow", 4.7, 15.7, "&6Lebeholzbogen",
          subtitle="Ein Bogen aus lebendem Holz.",
          description=[
              "Der &6Lebeholzbogen&r entsteht aus &e3 Lebeholzzweigen&r und &e3 Manainfundierten Fäden&r. Er ist ein solider Bogen für den Anfang.",
              "",
              "Er hält länger als ein normaler Bogen und repariert sich wie die Manastahl-Ausrüstung mit Mana aus deinem Inventar, sobald du ab Stufe 2 eine &6Manatafel&r bei dir trägst.",
          ],
          tasks=[task_item("botania:livingwood_bow", 1)],
          rewards=[reward_item("minecraft:arrow", 32)],
          deps=["mana_string"], optional=True),

    quest("mana_diamond", 5, 13.5, "&bManadiamant",
          subtitle="Ein Diamant voller Mana.",
          description=[
              "Ein &6Diamant&r im Becken wird für &d10 000 Mana&r zum &bManadiamanten&r. Neun davon ergeben einen Manadiamantblock, den du auch direkt aus einem Diamantblock infundieren kannst (90 000 Mana).",
              "",
              "Wofür du ihn brauchst:",
              "&e1.&r Den &6Quellschlussstein&r, den Magie-Meilenstein von Stufe 1: zwei Manadiamanten pro Stein.",
              "&e2.&r Das &aRitual des Waldes&r, das in Stufe 2 den ersten &6Manastahl&r macht: einer pro Ritual.",
              "&e3.&r Den &6Runenaltar&r in Stufe 2 (oder stattdessen eine Manaperle) und später den &6Manapylon&r.",
              "&e4.&r Jeden einzelnen &6Terrastahlbarren&r: einer pro Barren.",
              "",
              "&cDenk voraus:&r Das Stufe-2-Ziel am Obelisken will &e50 Terrastahlbarren&r und &e8 Runenkerne&r mit noch einmal je einem Barren darin. Das sind rund 60 Manadiamanten, also 60 Diamanten, nur für den Obelisken. Jeder Diamant, den du jetzt nicht für Werkzeug verbrauchst, hilft später dem ganzen Server.",
          ],
          tasks=[task_item("botania:mana_diamond", 2)],
          rewards=[reward_item("minecraft:diamond", 2), reward_table("s1_uncommon")],
          deps=["managlass"], icon="botania:mana_diamond", size=1.5, shape="diamond"),

    quest("pasture_seeds", 0, 15.7, "&6Weidesamen",
          subtitle="Gras, wo du es haben willst.",
          description=[
              "Ein Büschel &6Kurzes Gras&r wird im Becken für &d2 500 Mana&r zu &6Weidesamen&r. Rechtsklick damit auf Erde, per Hand oder aus einem Werfer, lässt in der Umgebung Gras wachsen.",
              "",
              "Praktisch, wenn du ein Blumenbeet oder eine Tierweide auf nackter Erde anlegen willst. Mystische Blumen wachsen durch Blumendünger nur auf Gras.",
          ],
          tasks=[task_item("botania:pasture_seeds", 4)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["managlass"], optional=True),

    quest("tiny_potato", 7.2, 15.7, "&6Winzige Kartoffel",
          subtitle="Sie glaubt an dich.",
          description=[
              "Eine ganz normale &6Kartoffel&r im Becken wird für genau &d1 337 Mana&r zur &6Winzigen Kartoffel&r.",
              "",
              "Sie tut nichts. Außer, dass sie an dich glaubt. Streichel sie mit Rechtsklick, dann hüpft sie vor Freude. Im Amboss kannst du ihr einen Namen geben, und sie hält Gegenstände, die du ihr in die Hand drückst. Jeder Botaniker braucht eine.",
          ],
          tasks=[task_item("botania:tiny_potato", 1)],
          rewards=[reward_item("minecraft:baked_potato", 8)],
          deps=["mana_diamond"], optional=True),

    # ---- Funktionsblumen --------------------------------------------------
    quest("func_intro", 11.5, 13.5, "Funktionsblumen",
          subtitle="Blumen, die Mana verbrauchen und dafür arbeiten.",
          description=[
              "&aFunktionsblumen&r sind das Gegenstück zu den erzeugenden Blumen: Sie ziehen &dMana&r aus einem &6Manabecken&r und erledigen dafür eine Aufgabe.",
              "",
              "Jede verbindet sich beim Pflanzen mit dem nächsten Becken in bis zu &e10 Blöcken&r. Mit dem Stab des Waldes im Bindemodus hängst du sie um. Ein Verbreiter kann sie &cnicht&r direkt versorgen, es muss immer ein Becken sein.",
              "",
              "Viele Funktionsblumen brauchen eine &6Redstone-Wurzel&r im Rezept. Solche Blumen kannst du mit einem Redstone-Signal abschalten.",
              "",
              "In Stufe 1 sind die Blumen ohne Runen offen: &6Tolldorn&r, &6Schreckdorn&r, &6Spulegnolie&r und &6Bergamute&r. Die großen Helfer wie Trichtermalve, Agrarnelke oder Jaded-Amarant brauchen Runen und kommen in Stufe 2.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["pool"], icon="botania:bellethorne"),

    quest("redstone_root", 13.7, 13.5, "&6Redstone-Wurzel",
          subtitle="Der Schalter für deine Blumen.",
          description=[
              "Die &6Redstone-Wurzel&r craftest du formlos aus &e1 Redstone&r und &e1 Farn&r oder &e1 Kurzem Gras&r.",
              "",
              "Sie steckt in fast jeder Funktionsblume. Eine Blume mit Wurzel im Rezept hört auf zu arbeiten, solange sie ein Redstone-Signal bekommt. So baust du Blumen mit Hebel, Zeitschalter oder Tageslichtsensor.",
              "",
              "&eTipp:&r Gras und Farne bekommst du mit einer Schere. Ein kleiner Vorrat Wurzeln spart dir später viele Wege.",
          ],
          tasks=[task_item("botania:redstone_root", 4)],
          rewards=[reward_item("minecraft:redstone", 16)],
          deps=["func_intro"], icon="botania:redstone_root"),

    quest("bellethorne", 16, 12.4, "&6Tolldorn",
          subtitle="Eine Blume mit Stacheln und schlechter Laune.",
          description=[
              "Der &6Tolldorn&r braucht &e3 rote&r und &e2 türkise&r Blütenblätter und eine &6Redstone-Wurzel&r.",
              "",
              block_img("bellethorne"),
              "",
              "Er verwandelt Mana in Schaden und verletzt ständig &calle Lebewesen&r in seiner Nähe, nur Spieler nicht. Unter einem Mob-Spawner oder am Ende eines Mob-Turms wird er zur Tötungsmaschine, die keine Waffe verschleißt.",
              "",
              "&cAchtung:&r Er unterscheidet nicht zwischen Zombie, Dorfbewohner, Pferd und Haustier. Pflanz ihn nie in die Nähe von Tieren, die dir lieb sind, oder schalte ihn per Redstone ab.",
          ],
          tasks=[task_item("botania:bellethorne", 1)],
          rewards=[reward_item("botania:red_mystical_petal", 4), reward_xp(3)],
          deps=["redstone_root"], icon="botania:bellethorne"),

    quest("dreadthorne", 16, 14.6, "&6Schreckdorn",
          subtitle="Für Viehzüchter mit wenig Zeit.",
          description=[
              "Der &6Schreckdorn&r ist der wählerische Bruder des Tolldorns: &e3 schwarze&r und &e2 türkise&r Blütenblätter und eine &6Redstone-Wurzel&r.",
              "",
              "Er verletzt nur &eausgewachsene Tiere&r. Jungtiere lässt er in Ruhe. Stell ihn in dein Kuh- oder Hühnergehege, dann bleiben die Kälber am Leben, und die großen Tiere liefern Fleisch und Leder, ohne dass du zuschlagen musst.",
              "",
              "&eTipp:&r Kombiniert mit einem Trichter unter dem Gehege und einer Fütterungsanlage aus Farming for Blockheads oder Create läuft die ganze Tierfarm allein.",
          ],
          tasks=[task_item("botania:dreadthorne", 1)],
          rewards=[reward_item("botania:black_mystical_petal", 4), reward_xp(3)],
          deps=["redstone_root"], optional=True),

    quest("bergamute", 13.7, 15.7, "&6Bergamute",
          subtitle="Endlich Ruhe in der Fabrik.",
          description=[
              "Die &6Bergamute&r entsteht aus &e1 orangefarbenen&r und &e2 grünen&r Blütenblättern und einer &6Redstone-Wurzel&r.",
              "",
              "Sie schluckt Schall: Alle Geräusche in ihrer Nähe sind nur noch halb so laut, und mehrere Bergamuten nebeneinander verstärken den Effekt. Sie braucht dafür kein Mana aus einem Becken.",
              "",
              "&eTipp:&r Perfekt für laute Tierfarmen, Create-Hallen voller Mahlwerke oder eine Reihe feuernder Verbreiter. Deine Zuschauer im Stream werden es dir danken.",
          ],
          tasks=[task_item("botania:bergamute", 1)],
          rewards=[reward_item("botania:green_mystical_petal", 4), reward_xp(3)],
          deps=["redstone_root"], optional=True),

    quest("solegnolia", 11.5, 15.7, "&6Spulegnolie",
          subtitle="Eine Zone ohne Magnet.",
          description=[
              "Die &6Spulegnolie&r braucht &e2 braune&r, &e1 rotes&r und &e1 blaues&r Blütenblatt und eine &6Redstone-Wurzel&r. Sie verbraucht kein Mana.",
              "",
              "In ihrer Nähe funktioniert der &6Ring der Magnetisierung&r nicht: Gegenstände dort werden nicht angezogen, und wer den Ring trägt, zieht dort nichts an. Den Ring gibt es ab Stufe 2 aus Manastahl.",
              "",
              "Pflanz sie neben deine Endoflammen, dann klaut dir der eigene Ring nicht mehr die Kohle vor der Blume weg.",
          ],
          tasks=[task_item("botania:solegnolia", 1)],
          rewards=[reward_xp(3)],
          deps=["redstone_root"], optional=True),

    # ---- Abschluss --------------------------------------------------------
    quest("farm", 18.5, 6.5, "&aEine echte Manafarm",
          subtitle="Mana, das fließt, während du etwas anderes tust.",
          description=[
              "Jetzt wird es ernst. Bau eine Farm, die ohne dich läuft: mindestens &e4 Endoflammen&r, zwei &6Manaverbreiter&r und ein volles &6Manabecken&r, gefüttert über eine Offene Kiste oder ein Create-Förderband.",
              "",
              "Ein paar Zahlen, damit du planen kannst: Eine Endoflamme mit Kohle liefert rund &d60 Mana pro Sekunde&r. Ein volles Becken (&d1 000 000&r) braucht damit über vier Stunden, mit zehn Endoflammen etwa eine halbe Stunde und gut 400 Kohle.",
              "",
              "&eTipp:&r Eine Baumfarm mit Create-Säge und ein Ofen für Holzkohle liefern Brennstoff ohne Mine. Stell den Manastern ans Becken, dann siehst du sofort, ob die Farm mithält.",
              "",
              "Jeder Tropfen, den du jetzt speicherst, bleibt im Becken. Wenn Stufe 2 öffnet, wird er zu Manastahl, Manaperlen und Terrastahl.",
          ],
          tasks=[task_item("botania:endoflame", 4), task_item("botania:mana_spreader", 2),
                 task_item("botania:mana_pool", 1)],
          rewards=[reward_table("s1_rare"), reward_xp(10)],
          deps=["pool", "manastar"], icon="botania:mana_spreader", size=2.0, shape="gear"),

    quest("manasteel_prep", 21, 8.7, "&bVorbereitung: Manastahl",
          subtitle="Das Ritual des Waldes, schon jetzt geplant.",
          description=[
              "Auf Kronwerke wird &6Manastahl&r nicht mehr aus einem Eisenbarren im Becken gemacht, ein Eisenbarren bleibt dort einfach liegen. Der erste Manastahl kommt aus einem Ritual von &aNature's Aura&r, und die Zutaten dafür kannst du schon in Stufe 1 sammeln.",
              "",
              "&eDas Ritual des Waldes:&r Leg &6Gold Powder&r (aus Gold Leaf zerrieben) im Muster aus dem Buch von Nature's Aura auf den Boden, stell &6Wooden Stands&r (Gold Leaf auf einem Stamm) darum und lege auf sie die Zutaten:",
              "&e4&r &6Infused Iron&r vom Natural Altar, &e2&r &6Lebeholzzweige&r, &e1&r &bManadiamant&r und &e1&r &6Gold Leaf&r.",
              "Dann pflanzt du einen &6Eichensetzling&r in die Mitte und lässt ihn wachsen, mit Knochenmehl oder mit Geduld. Der Baum verschlingt die Zutaten, und heraus kommen &e4 Manastahlbarren&r.",
              "",
              "&eDer Weg für große Mengen:&r Ist Stufe 2 offen, wirfst du &6Infused Iron&r statt Eisen in ein Manabecken. Für &d3 000 Mana&r wird jedes Stück zu einem Manastahlbarren. Ein Natural Altar, der Eisen veredelt, und ein Becken dahinter sind eine kleine Manastahl-Fabrik.",
              "",
              "Manastahl selbst ist bis Stufe 2 &cgesperrt&r. Aber wer jetzt Infused Iron, Zweige und Manadiamanten bereitlegt, hat am ersten Abend von Stufe 2 seine Runen.",
          ],
          tasks=[task_item("naturesaura:infused_iron", 4), task_item("botania:livingwood_twig", 2),
                 task_item("botania:mana_diamond", 1), task_item("naturesaura:gold_leaf", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 4), reward_table("s1_uncommon"), reward_xp(5)],
          deps=["farm"], icon="naturesaura:infused_iron", optional=True),

    quest("outlook", 21, 6.5, "Ausblick: Stufe 2",
          subtitle="Was hinter dem Obelisken wartet.",
          description=[
              "Mit &6Stufe 2 (Messingwerk)&r öffnet Botania richtig. Dann geht es im Kapitel &aBotania: Runen&r weiter:",
              "",
              "&6Manastahl&r: zuerst aus dem Ritual des Waldes von Nature's Aura (vier Barren pro Ritual), in Mengen aus &6Infused Iron&r im Becken für 3 000 Mana. Ein Eisenbarren im Becken tut nichts mehr.",
              "&6Manaperle&r: eine Enderperle im Becken, 6 000 Mana. Aber nur, wenn unter dem Becken ein &6Messinggehäuse&r aus Create steht.",
              "&6Manatafel&r: ein Manabecken zum Mitnehmen.",
              "&aRunenaltar&r: Runen der Elemente, Jahreszeiten und Sünden, und damit neue, viel stärkere Blumen. Auf Kronwerke steckt ein Messingbarren darin.",
              "&aTerrestrische Agglomerationsplatte&r: Terrastahl. Auf Kronwerke braucht sie zwei Messinggehäuse aus Create.",
              "",
              "Manastahl, Manaperlen und die Manatafel sind bis dahin &cgesperrt&r. Du kannst sie tragen, aber noch nicht benutzen, der Tooltip sagt dir, ab welcher Stufe. Das Elfenportal und der Handel mit Alfheim folgen erst mit Stufe 3.",
              "",
              "Das Obelisk-Ziel von Stufe 2 will &e600 Manaperlen&r, &e50 Terrastahlbarren&r und &e8 Runenkerne&r. Das sind zusammen rund &d30 Millionen Mana&r. Fangt früh an, Becken zu füllen.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["farm"], icon="botania:mana_pool"),

]

images = [
    banner("botania/title", "Botania", 9, -5.2, height=1.8, kind="title", colour="nature"),
    banner("botania/blueten", "Erste Blüten", 3.5, -2.6, height=0.9, colour="nature"),
    banner("botania/erzeugen", "Mana erzeugen", 2.5, 4.6, height=0.9, colour="nature"),
    banner("botania/speichern", "Mana speichern", 11.3, 3.9, height=0.9, colour="magic"),
    banner("botania/infusion", "Manainfusion", 3.5, 11.7, height=0.9, colour="magic"),
    banner("botania/funktion", "Funktionsblumen", 13.7, 11.2, height=0.9, colour="nature"),
    banner("botania/farm", "Die Farm", 19.7, 4.6, height=0.9, colour="magic"),
]

chapter(C, "Botania", "botania:pure_daisy", "magic", quests, shape="circle", order=3,
        subtitle=["Blumen, Mana und das erste Manabecken."], images=images)
