"""Botania in stage 2: manasteel (Nature's Aura tree ritual, then infused iron in the pool), mana
pearls (brass casing under the pool), the runic altar (with a brass ingot) and all sixteen runes,
the generating flowers that need runes with their numbers from the flower classes, a checklist of
the functional flowers and the baubles of this stage, the terrestrial agglomeration plate (two
Create brass casings), terrasteel and the Runenkern milestone. See
kubejs/server_scripts/kronwerke/magic.js and tech_and_magic.js. The elven gateway, elementium,
pixie dust and dreamwood are stage 3 (alfheim.py), the Gaia baubles stage 4 (gaia.py)."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table,
                  reward_xp, banner, img, item_texture)

C = "botania_runes"


def block_img(name, size=32):
    """A flower or block picture from Botania's block textures."""
    return img(f"botania:textures/block/{name}.png", size, size)


def sin_rune(name, x, y, rune, title, cats, uses, deps):
    """One of the seven sin runes: 2 mana diamonds, 1 mana quartz, 12 000 mana, two catalysts."""
    return quest(name, x, y, title,
                 subtitle=f"Katalysatoren: {cats}.",
                 description=[
                     f"&e2 Manadiamanten&r und &e1 Manaquarz&r auf den Altar, dazu die Runen {cats} als Katalysatoren. &d12 000 Mana&r.",
                     "",
                     f"&eWofür:&r {uses}",
                 ],
                 tasks=[task_item(f"botania:{rune}", 1)],
                 rewards=[reward_item("botania:mana_quartz", 4), reward_xp(4)],
                 deps=deps, optional=True, icon=f"botania:{rune}")


quests = [
    # ---- Manastahl --------------------------------------------------------
    quest("welcome", 0, 0, "&bÖffne das Messingwerk",
          subtitle="Stufe 2 ist offen, jetzt zeigt Botania, was es kann.",
          description=[
              "Mit &6Stufe 2 (Messingwerk)&r öffnen Manastahl, Manaperlen, der Runenaltar mit sechzehn Runen, sechzehn neue Funktionsblumen, fünf neue Manablumen und am Ende Terrastahl.",
              "",
              "Auf Kronwerke hängt das an Create: Manaperlen nur mit Messinggehäuse unter dem Becken, Messing im Runenaltar und in der Terraplatte. Umgekehrt braucht Mekanism deinen Manastahl und Create deine Feuerrunen.",
              "",
              "&eKronwerke:&r Das Obelisk-Ziel will &e600 Manaperlen&r, &e50 Terrastahlbarren&r und &e8 Runenkerne&r, zusammen über &d30 Millionen Mana&r. Das Elfenportal kommt in Stufe 3.",
          ],
          tasks=[task_checkmark("Los geht's")],
          rewards=[reward_item("botania:livingrock", 16), reward_table("s2_common")],
          icon="botania:rune_of_mana", size=2.0, shape="hexagon"),

    quest("ritual", 2.4, -1.2, "&aWirk das Ritual des Waldes",
          subtitle="Der erste Manastahl wächst an einem Baum.",
          description=[
              "&eRezept auf Kronwerke:&r &e4 Infused Iron&r, &e2 Lebeholzzweige&r, &e1 Manadiamant&r, &e1 Gold Leaf&r auf Wooden Stands um einen &6Eichensetzling&r. Lass ihn wachsen, dann liegen &e4 Manastahlbarren&r in der Mitte.",
              "",
              "Das Muster aus &6Gold Powder&r (ein Gold Leaf gibt zwei) zeigt das Buch von Nature's Aura als Vorschau. Ein &6Wooden Stand&r ist ein Gold Leaf auf einem Stamm.",
              "",
              "&cHäufige Fehler:&r anderer Setzling als Eiche, fehlende Zutat, Lücke im Muster. Dann wächst nur ein Baum.",
          ],
          tasks=[task_item("botania:manasteel_ingot", 4)],
          rewards=[reward_item("naturesaura:gold_leaf", 2), reward_xp(5)],
          deps=["welcome"], icon="naturesaura:wood_stand", size=1.5, shape="square"),

    quest("infused_pool", 2.4, 1.2, "&bInfundiere Manastahl im Becken",
          subtitle="Der Weg für große Mengen.",
          description=[
              "&eRezept auf Kronwerke:&r &6Infused Iron&r ins Manabecken, &d3 000 Mana&r pro Barren. Ein Eisenbarren bleibt im Becken liegen.",
              "",
              img(item_texture("botania:manasteel_ingot"), 32, 32),
              "",
              "Infused Iron kommt vom &aNatural Altar&r (15 000 Aura pro Barren). Trichter auf den Altar, Förderband zum Becken, und die Manastahl-Fabrik läuft. Manastahlblöcke gibt es nur noch aus neun Barren.",
          ],
          tasks=[task_item("botania:manasteel_ingot", 16)],
          rewards=[reward_item("minecraft:iron_ingot", 16), reward_table("s2_common")],
          deps=["welcome"], icon="botania:manasteel_ingot", size=1.5, shape="square"),

    quest("brass_casing", 4.8, -1.2, "&6Hol dir Messinggehäuse",
          subtitle="Perlen, Runen und Terrastahl brauchen die Technik.",
          description=[
              "Einen &6Messingbarren&r per Rechtsklick auf &6entrindetes Holz&r anwenden, das gibt ein &6Messinggehäuse&r. Messing macht der Create-Mixer über einem Lohenbrenner.",
              "",
              img("create:textures/block/brass_casing.png", 32, 32),
              "",
              "Du brauchst ein Gehäuse unter dem Perlenbecken, einen Barren im Runenaltar und zwei Gehäuse in der Terraplatte. Ohne eigene Messinglinie: tausch Manastahl oder Feuerrunen bei den Ingenieuren.",
          ],
          tasks=[task_item("create:brass_casing", 3), task_item("create:brass_ingot", 1)],
          rewards=[reward_item("create:brass_ingot", 4)],
          deps=["welcome"], icon="create:brass_casing"),

    quest("mana_pearl", 7.2, -1.2, "&bInfundiere Manaperlen",
          subtitle="Eine Enderperle auf Messing gebettet.",
          description=[
              "&eRezept auf Kronwerke:&r &6Enderperle&r ins Becken, &d6 000 Mana&r, aber nur mit einem &6Messinggehäuse&r direkt &eunter dem Becken&r. Ohne Gehäuse bleibt die Perle liegen.",
              "",
              img(item_texture("botania:mana_pearl"), 32, 32),
              "",
              "Andere Infusionen laufen im selben Becken normal weiter. Enderperlen gibt es im Wirrwald im Nether, von Endermen nachts auf Ebenen und von Piglins im Tausch gegen Gold.",
          ],
          tasks=[task_item("botania:mana_pearl", 8)],
          rewards=[reward_item("minecraft:ender_pearl", 8)],
          deps=["brass_casing"], icon="botania:mana_pearl"),

    quest("alchemy", 7.2, -3.3, "&6Bau einen Alchemiekatalysator",
          subtitle="Das Becken lernt Verwandlung.",
          description=[
              "&e4 Lebestein&r, &e2 Goldbarren&r, &e2 Braustände&r und &e1 Manaperle&r. Unter einem Manabecken lässt er das Becken Dinge umwandeln statt infundieren.",
              "",
              "JEI zeigt alle Rezepte unter dem Katalysator. Eine Funktionsblume ins Becken mit Katalysator geworfen wird für etwas Mana kleiner: gleiche Wirkung, kleinerer Bereich.",
              "",
              "In Stufe 3 wird er zum Zauberkatalysator, siehe &aBotania: Alfheim&r.",
          ],
          tasks=[task_item("botania:alchemy_catalyst", 1)],
          rewards=[reward_item("minecraft:brewing_stand", 1), reward_xp(4)],
          deps=["mana_pearl"], optional=True, icon="botania:alchemy_catalyst"),

    quest("mana_quartz", 4.8, 1.2, "&bInfundiere Manaquarz",
          subtitle="Netherquarz, blau gefärbt.",
          description=[
              "&6Netherquarz&r ins Becken, &d250 Mana&r pro Stück. Vier ergeben einen &6Manaquarzblock&r.",
              "",
              "Ein Block steckt in der Terraplatte, ein Quarz in jeder der sieben Sündenrunen. Der Rest ist ein schöner Baustein neben Lebestein.",
          ],
          tasks=[task_item("botania:mana_quartz", 16)],
          rewards=[reward_item("minecraft:quartz", 16)],
          deps=["welcome"], icon="botania:mana_quartz"),

    quest("mana_tablet", 7.2, 1.2, "&bCrafte eine Manatafel",
          subtitle="Ein halbes Becken in der Tasche.",
          description=[
              "&e8 Lebestein&r um einen &eManadiamanten&r oder eine &eManaperle&r. Speichert &d500 000 Mana&r.",
              "",
              "Ins Becken werfen lädt sie, Schleich-Rechtsklick mit dem Stab aufs Becken dreht die Richtung. In deinem Inventar versorgt sie Manastahl-Werkzeuge, Bogen und Robe.",
          ],
          tasks=[task_item("botania:mana_tablet", 1)],
          rewards=[reward_item("botania:livingrock", 16), reward_xp(5)],
          deps=["mana_pearl"], icon="botania:mana_tablet"),

    quest("band_of_mana", 7.2, 3.3, "&6Trag das Manaband",
          subtitle="Die Tafel als Ring.",
          description=[
              "&e1 Manatafel&r und &e4 Manastahlbarren&r. Wirkt wie die Tafel, sitzt aber im Ringplatz statt im Inventar.",
              "",
              "Mit einem Terrastahlbarren wird es zum Größeren Manaband mit etwa viermal so viel Platz. Alle anderen Schmuckstücke dieser Stufe stehen unten im Abschnitt &eSchmuck&r.",
          ],
          tasks=[task_item("botania:band_of_mana", 1)],
          rewards=[reward_item("botania:manasteel_ingot", 4)],
          deps=["mana_tablet"], optional=True),

    quest("manasteel_gear", 2.4, 3.3, "&6Schmied Manastahl-Werkzeug",
          subtitle="Werkzeug, das sich selbst repariert.",
          description=[
              "Manastahl und &6Lebeholzzweige&r, Muster wie bei Eisen. Die Rüstung aus Manastahl allein.",
              "",
              "Etwa so stark wie Eisen, hält länger, verzaubert sich besser und &erepariert sich&r mit Mana aus Tafel oder Manaband. Rechtsklick mit der Spitzhacke setzt eine Fackel, mit der Axt einen Setzling.",
          ],
          tasks=[task_item("botania:manasteel_pickaxe", 1)],
          rewards=[reward_item("botania:manasteel_ingot", 4)],
          deps=["infused_pool"], optional=True),

    quest("mekanism_tie", 4.8, 3.3, "&7Liefer Manastahl an die Ingenieure",
          subtitle="Mekanism braucht deine Blumen.",
          description=[
              "&eRezept auf Kronwerke:&r Der &aMetallurgische Infusionierer&r hat unten Manastahl, Ofen, Manastahl statt Eisen. Oben Eisen, Ofen, Eisen, Mitte Redstone, Osmium, Redstone.",
              "",
              "Ohne Infusionierer kein Stahl und keine Schaltkreise. Tausch Manastahl gegen Messing, siehe Kapitel &5Mekanism&r.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["infused_pool"], icon="mekanism:metallurgic_infuser"),

    quest("mana_lens", 0, 2.9, "&6Schleif eine Manalinse",
          subtitle="Mach aus einem Manastoß ein Werkzeug.",
          description=[
              "&e4 Manastahlbarren&r um einen Block &eGlas&r. Rechtsklick setzt sie in einen Verbreiter. Allein färbt sie nur den Stoß, sie ist die Basis aller Speziallinsen.",
              "",
              "&eGeschwindigkeit&r, &eStärke&r (doppeltes Mana pro Stoß), &eWiderstand&r und &eEffizienz&r (weniger Verlust), &eBote&r und viele mehr. Zwei Linsen verbindet ein Schleimball. Alle Rezepte in JEI.",
          ],
          tasks=[task_item("botania:mana_lens", 1)],
          rewards=[reward_item("minecraft:glass", 16)],
          deps=["infused_pool"], optional=True),

    # ---- Runen ------------------------------------------------------------
    quest("runic_altar", 10.5, 0, "&aBau den Runenaltar",
          subtitle="Hier entstehen die Runen.",
          description=[
              "&eRezept auf Kronwerke:&r oben Lebestein, &6Messingbarren&r, Lebestein, unten Lebestein, &eManadiamant&r oder &eManaperle&r, Lebestein.",
              "",
              block_img("runic_altar_top"),
              "",
              "Zutaten drauflegen, Verbreiter mit vollem Becken auf den Altar richten, ist das Mana drin, einen &6Lebestein&r drauf, dann Rechtsklick mit dem Stab. Runen im Rezept sind Katalysatoren und kommen zurück.",
              "",
              "&eTipp:&r Rechtsklick mit leerer Hand legt dieselben Zutaten noch einmal auf. Komparator: Stärke 1 beim Laden, 2 wenn fertig.",
          ],
          tasks=[task_item("botania:runic_altar", 1)],
          rewards=[reward_item("botania:livingrock", 32), reward_table("s2_common")],
          deps=["welcome"], icon="botania:runic_altar", size=2.0, shape="square"),

    quest("rune_water", 13, -1.1, "&9Mach die Rune des Wassers",
          subtitle="Das erste Element.",
          description=[
              "&eManapuder&r, &eManastahlbarren&r, &eKnochenmehl&r, &eZuckerrohr&r, &eAngel&r. &d5 200 Mana&r, gibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_water"), 32, 32),
              "",
              "Steckt in Terraplatte, Runenkern, Narglibbe, Freihut und ist Katalysator für Frühling und Winter.",
          ],
          tasks=[task_item("botania:rune_of_water", 2)],
          rewards=[reward_item("minecraft:sugar_cane", 16)],
          deps=["runic_altar"], icon="botania:rune_of_water"),

    quest("rune_fire", 15, -1.1, "&cMach die Rune des Feuers",
          subtitle="Ein Hauch Nether.",
          description=[
              "&eManapuder&r, &eManastahlbarren&r, &eNetherziegel&r, &eSchwarzpulver&r, &eKohle&r oder Holzkohle. &d5 200 Mana&r, gibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_fire"), 32, 32),
              "",
              "Für Terraplatte, Runenkern, Thermalilie, Gourmaryllis, Exoflamme. Die Ingenieure brauchen eine pro &6Messingherz&r: ein guter Tausch gegen Gehäuse.",
          ],
          tasks=[task_item("botania:rune_of_fire", 2)],
          rewards=[reward_item("minecraft:gunpowder", 8)],
          deps=["runic_altar"], icon="botania:rune_of_fire"),

    quest("rune_earth", 13, 1.1, "&6Mach die Rune der Erde",
          subtitle="Stein, Schlamm und Pilz.",
          description=[
              "&eManapuder&r, &eManastahlbarren&r, &eStein&r, &eSchlamm&r, &ebrauner oder roter Pilz&r. &d5 200 Mana&r, gibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_earth"), 32, 32),
              "",
              "&6Schlamm&r: Wasserflasche auf Erde leeren. Für Terraplatte, Runenkern, Thermalilie, Helitonie, Rannawurzel, Wirrbeere.",
          ],
          tasks=[task_item("botania:rune_of_earth", 2)],
          rewards=[reward_item("minecraft:mud", 8)],
          deps=["runic_altar"], icon="botania:rune_of_earth"),

    quest("rune_air", 15, 1.1, "&fMach die Rune der Luft",
          subtitle="Leicht wie eine Feder.",
          description=[
              "&eManapuder&r, &eManastahlbarren&r, ein &eTeppich&r, eine &eFeder&r, ein &eFaden&r. &d5 200 Mana&r, gibt &e2 Runen&r.",
              "",
              img(item_texture("botania:rune_of_air"), 32, 32),
              "",
              "Für Terraplatte, Runenkern, Trichtermalve, Ostermühle, Wirrbeere, Freihut und mehrere Schmuckstücke.",
          ],
          tasks=[task_item("botania:rune_of_air", 2)],
          rewards=[reward_item("minecraft:feather", 16)],
          deps=["runic_altar"], icon="botania:rune_of_air"),

    quest("rune_mana", 10.5, 2.7, "&dMach die Rune des Manas",
          subtitle="Reines Mana, in Stein gefasst.",
          description=[
              "&e5 Manastahlbarren&r und &e1 Manaperle&r. &d8 000 Mana&r.",
              "",
              img(item_texture("botania:rune_of_mana"), 32, 32),
              "",
              "Für Terraplatte, Rosa Arcana, Botanische Brauerei und das Auraband. Heb mindestens zwei auf.",
          ],
          tasks=[task_item("botania:rune_of_mana", 1)],
          rewards=[reward_item("botania:mana_pearl", 2)],
          deps=["runic_altar", "mana_pearl"], icon="botania:rune_of_mana"),

    quest("rune_spring", 17.5, -1.1, "&aMach die Rune des Frühlings",
          subtitle="Wasser und Feuer ergeben Wachstum.",
          description=[
              "&e3 Setzlinge&r, &e1 Weizen&r, Katalysatoren Wasser und Feuer. &d8 000 Mana&r.",
              "",
              "Für Jaded-Amarant, Agrarnelke, Engelsblüte, den Zauber der Gütigen Göttin und den Terrastahlhelm.",
          ],
          tasks=[task_item("botania:rune_of_spring", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 8)],
          deps=["rune_water", "rune_fire"], icon="botania:rune_of_spring"),

    quest("rune_summer", 19.7, -1.1, "&eMach die Rune des Sommers",
          subtitle="Erde und Luft ergeben Wärme.",
          description=[
              "&e2 Sand&r, &e1 Schleimball&r, &e1 Melonenscheibe&r, Katalysatoren Erde und Luft. &d8 000 Mana&r.",
              "",
              "Für Gourmaryllis, Narglibbe, Exoflamme, den Pyroklastanhänger und den Terrastahlharnisch.",
          ],
          tasks=[task_item("botania:rune_of_summer", 1)],
          rewards=[reward_item("minecraft:slime_ball", 4)],
          deps=["rune_earth", "rune_air"], icon="botania:rune_of_summer"),

    quest("rune_autumn", 17.5, 1.1, "&6Mach die Rune des Herbstes",
          subtitle="Feuer und Luft ergeben fallendes Laub.",
          description=[
              "&e3 Laubblöcke&r, &e1 Spinnenauge&r, Katalysatoren Feuer und Luft. &d8 000 Mana&r.",
              "",
              "Für Tigerauge, Cyazinthe, das Zirrus-Amulett, die Rune der Trägheit und die Terrastahlhose.",
          ],
          tasks=[task_item("botania:rune_of_autumn", 1)],
          rewards=[reward_item("minecraft:spider_eye", 4)],
          deps=["rune_fire", "rune_air"], optional=True, icon="botania:rune_of_autumn"),

    quest("rune_winter", 19.7, 1.1, "&bMach die Rune des Winters",
          subtitle="Wasser und Erde ergeben Frost.",
          description=[
              "&e2 Schneeblöcke&r, &e1 Wolle&r, &e1 Kuchen&r, Katalysatoren Wasser und Erde. &d8 000 Mana&r.",
              "",
              "Katalysator für Völlerei, Zorn und Neid, dazu Schneeflockanhänger und Terrastahlstiefel.",
          ],
          tasks=[task_item("botania:rune_of_winter", 1)],
          rewards=[reward_item("minecraft:snow_block", 8)],
          deps=["rune_water", "rune_earth"], icon="botania:rune_of_winter"),

    quest("sin_runes", 22, 0, "&5Mach die Rune der Völlerei",
          subtitle="Die erste der sieben Sündenrunen.",
          description=[
              "&e2 Manadiamanten&r, &e1 Manaquarz&r, Katalysatoren Winter und Feuer. &d12 000 Mana&r. Jede Sündenrune kostet dasselbe, nur die Katalysatoren wechseln.",
              "",
              "Völlerei brauchst du für den &6Mampftau&r, in Stufe 3 für Kekimurus und Beutanie.",
              "",
              "&cAchtung:&r Jede Sündenrune frisst zwei Manadiamanten, die dem Terrastahl fehlen. Bau nur, was du benutzt.",
          ],
          tasks=[task_item("botania:rune_of_gluttony", 1)],
          rewards=[reward_item("botania:mana_diamond", 2), reward_table("s2_uncommon")],
          deps=["rune_winter"], optional=True, icon="botania:rune_of_gluttony"),

    sin_rune("rune_lust", 24.5, -1.8, "rune_of_lust", "&5Mach die Rune der Wollust", "Sommer und Luft",
             "Pollidisie und Vinculotos.", ["sin_runes"]),
    sin_rune("rune_greed", 26.7, -1.8, "rune_of_greed", "&5Mach die Rune der Gier", "Frühling und Wasser",
             "die Erchidee in Stufe 3.", ["rune_lust"]),
    sin_rune("rune_sloth", 24.5, 0, "rune_of_sloth", "&5Mach die Rune der Trägheit", "Herbst und Luft",
             "Vinculotos, in Stufe 3 die Beutanie.", ["sin_runes"]),
    sin_rune("rune_wrath", 26.7, 0, "rune_of_wrath", "&5Mach die Rune des Zorns", "Winter und Erde",
             "Entropinnyum und Friedenstraum in Stufe 3, Shulk Mein Nicht in Stufe 4.", ["rune_sloth"]),
    sin_rune("rune_envy", 24.5, 1.8, "rune_of_envy", "&5Mach die Rune des Neids", "Winter und Wasser",
             "Spektrantheme und Beutanie in Stufe 3, Shulk Mein Nicht in Stufe 4.", ["sin_runes"]),
    sin_rune("rune_pride", 26.7, 1.8, "rune_of_pride", "&5Mach die Rune des Hochmuts", "Sommer und Feuer",
             "Erchidee, Rafflorsie und Ring der großen Reichweite in Stufe 3, Zauber der Diva in Stufe 4.", ["rune_envy"]),

    quest("brewery", 13, 3.3, "&6Bau die Botanische Brauerei",
          subtitle="Tränke mit Mana statt Braustand.",
          description=[
              "&e6 Lebestein&r, &e1 Braustand&r, &e1 Rune des Manas&r, &e1 Manastahlblock&r.",
              "",
              "Leg eine &6Managlasphiole&r hinein (3 Managlas in V-Form ergeben 3), dann die Zutaten, und richte einen Verbreiter darauf. Gebräue haben feste Rezepte und mehrere Schlucke pro Phiole, die Lexica listet alle.",
          ],
          tasks=[task_item("botania:botanical_brewery", 1)],
          rewards=[reward_item("minecraft:nether_wart", 8), reward_xp(5)],
          deps=["rune_mana"], optional=True, icon="botania:botanical_brewery"),

    # ---- Neue Blumen: erzeugend -------------------------------------------
    quest("gen_table", -2.4, 6.5, "&aVergleich alle Manablumen",
          subtitle="Was jede erzeugende Blume pro Stück bringt.",
          description=[
              "&6Endoflamme&r: Brennstoff, 1 200 pro Kohle. &6Hydroangea&r: Wasser, 13 pro Block.",
              "&6Thermalilie&r: Lava, 27 000 pro Block, dann 5 Minuten Pause.",
              "&6Gourmaryllis&r: Essen, Nährwert mal Nährwert mal 70, Steak 4 480, mit Abwechslung bis 1,8fach.",
              "&6Mampftau&r: Laub, 160 pro Block, 80 Sekunden Pause, wenn alles gefressen ist.",
              "&6Narglibbe&r: Schleime aus Schleimchunks, 2 400, 4 800 oder 19 200 je Größe.",
              "&6Rosa Arcana&r: Erfahrung, 50 pro Punkt.",
              "&6Entropinnyum&r (Stufe 3): TNT, 6 500 pro Explosion. &6Kekimurus&r (Stufe 3): Kuchen, 1 800 pro Stück.",
              "&6Spektrole&r (Stufe 3): Wolle in der gewünschten Farbe, 1 200. &6Rafflorsie&r (Stufe 3): Blumen, 2 000 bis über 600 000 je Abwechslung.",
              "&6Lebenzahn&r (Stufe 4): Zellblöcke, bis 6 000 pro Zelle. &6Shulk Mein Nicht&r (Stufe 4): 75 000 pro Shulker-Treffer.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["thermalily"], icon="botania:thermalily"),

    quest("thermalily", 0, 6.5, "&6Pflanz eine Thermalilie",
          subtitle="Lava rein, sehr viel Mana raus.",
          description=[
              "Apotheke: &e1 rotes&r, &e2 orange&r Blütenblätter, Runen der &eErde&r und des &eFeuers&r. Sie trinkt Lava neben sich auf ihrer Höhe.",
              "",
              block_img("thermalily"),
              "",
              "Ein Lavablock gibt &e30 Sekunden&r lang 45 Mana pro Tick, also &d27 000 Mana&r. Danach kühlt sie &e5 Minuten&r ab. Lava, die sie in der Pause berührt, schluckt sie ohne Mana und startet die Pause neu.",
              "",
              "&eTipp:&r Ein Create-Schlauchflaschenzug über einem Lavasee im Nether liefert endlos Lava, ein offenes Rohrende setzt sie als Block neben die Blume. Gib nur alle 5 Minuten einen Block.",
          ],
          tasks=[task_item("botania:thermalily", 1)],
          rewards=[reward_item("minecraft:lava_bucket", 1), reward_item("botania:orange_mystical_petal", 4)],
          deps=["rune_earth", "rune_fire"], icon="botania:thermalily", size=1.5, shape="square"),

    quest("gourmaryllis", 2.2, 6.5, "&6Pflanz eine Gourmaryllis",
          subtitle="Ein Feinschmecker unter den Blumen.",
          description=[
              "Apotheke: &e2 hellgraue&r, &e2 gelbe&r, &e1 rotes&r Blütenblatt, Runen des &eFeuers&r und des &eSommers&r.",
              "",
              "Sie frisst Essen direkt neben sich, eins nach dem anderen. Mana: &dNährwert mal Nährwert mal 70&r, ein Steak (8) gibt 4 480 nach 4 Sekunden. Immer dasselbe Essen bringt immer weniger, bis zu sieben verschiedene hintereinander bis 1,8fach.",
              "",
              "&eTipp:&r Farmer's Delight hat Dutzende Gerichte, siehe Kapitel &aKochen&r. Ein Förderband, das reihum verschiedene Mahlzeiten ablegt, ist eine der stärksten Quellen dieser Stufe.",
          ],
          tasks=[task_item("botania:gourmaryllis", 1)],
          rewards=[reward_item("minecraft:cooked_beef", 16)],
          deps=["rune_summer", "rune_fire"], icon="botania:gourmaryllis"),

    quest("munchdew", 4.4, 6.5, "&6Pflanz einen Mampftau",
          subtitle="Frisst ganze Baumkronen.",
          description=[
              "Apotheke: &e2 hellgrüne&r, &e2 rote&r, &e1 grünes&r Blütenblatt, &5Rune der Völlerei&r.",
              "",
              "Frisst Laub in 8 Blöcken Umkreis, &d160 Mana pro Block&r, ohne Setzlinge oder Äpfel. Ist alles weg, macht er 80 Sekunden Pause.",
              "",
              "&eTipp:&r Zwischen Bäume, die ständig nachwachsen, mit Agrarnelke oder Knochenmehl aus dem Werfer.",
          ],
          tasks=[task_item("botania:munchdew", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 16)],
          deps=["sin_runes"], optional=True, icon="botania:munchdew"),

    quest("rosa_arcana", 6.6, 6.5, "&6Pflanz eine Rosa Arcana",
          subtitle="Erfahrung wird zu Mana.",
          description=[
              "Apotheke: &e2 rosa&r, &e2 violette&r, &e1 hellgrünes&r Blütenblatt, &dRune des Manas&r.",
              "",
              "Saugt Erfahrung von Spielern direkt daneben, frisst Erfahrungskugeln und zieht verzauberten Gegenständen am Boden die Verzauberungen heraus. &d50 Mana pro Erfahrungspunkt&r.",
              "",
              "&eTipp:&r Am Ausgang einer Mob-Farm, schlechte Bücher aus der Angel sind hier Brennstoff.",
          ],
          tasks=[task_item("botania:rosa_arcana", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 8)],
          deps=["rune_mana"], icon="botania:rosa_arcana"),

    quest("narslimmus", 8.8, 6.5, "&6Pflanz eine Narglibbe",
          subtitle="Schleim aus Schleimchunks.",
          description=[
              "Apotheke: &e2 hellgrüne&r, &e2 grüne&r, &e1 schwarzes&r Blütenblatt, Runen des &eSommers&r und des &eWassers&r.",
              "",
              "Fängt Schleime, die in einem &eSchleimchunk&r natürlich spawnen. Klein &d2 400&r, mittel &d4 800&r, groß &d19 200 Mana&r.",
              "",
              "&eTipp:&r Flache Halle unter Höhe 40 in einem Schleimchunk, Blume mittendrin. Läuft, solange der Chunk geladen ist.",
          ],
          tasks=[task_item("botania:narslimmus", 1)],
          rewards=[reward_item("minecraft:slime_ball", 8)],
          deps=["rune_summer", "rune_water"], optional=True, icon="botania:narslimmus"),

    quest("wards", 11, 6.5, "&6Zieh Zäune aus Magie",
          subtitle="Wirrbeere hält drin, Freihut hält draußen.",
          description=[
              "&6Wirrbeere&r: &e2 türkis, 1 grau, 1 hellgrau&r, Runen der Luft und der Erde. Hält Tiere und Monster in ihrem Kreis.",
              "&6Freihut&r: &e2 rosa, 1 violett, 1 hellgrau&r, Runen des Wassers und der Luft. Hält sie draußen.",
              "",
              "Beide brauchen nur wenig Mana. Eine Freihut mitten in der Basis, und kein Creeper kommt herein.",
          ],
          tasks=[task_item("botania:tangleberrie", 1), task_item("botania:jiyuulia", 1)],
          rewards=[reward_table("s2_common")],
          deps=["rune_air"], optional=True, icon="botania:jiyuulia"),

    # ---- Neue Blumen: Funktion --------------------------------------------
    quest("jaded_amaranthus", 0, 8.8, "&6Pflanz einen Jaded-Amarant",
          subtitle="Nie wieder Blumen suchen.",
          description=[
              "Apotheke: je &e1 violettes, hellgrünes, grünes&r Blütenblatt, &eRune des Frühlings&r, &6Redstone-Wurzel&r.",
              "",
              "Lässt mit Mana auf Erde in seiner Nähe ständig neue Mystische Blumen in allen Farben wachsen. Mit Trichtermalve und Truhe sammelt sich der Vorrat von selbst.",
          ],
          tasks=[task_item("botania:jaded_amaranthus", 1)],
          rewards=[reward_item("botania:floral_fertilizer", 8)],
          deps=["rune_spring"], icon="botania:jaded_amaranthus"),

    quest("agricarnation", 2.2, 8.8, "&6Pflanz eine Agrarnelke",
          subtitle="Dünger, der nie ausgeht.",
          description=[
              "Apotheke: &e2 hellgrüne&r, &e1 grünes&r, &e1 gelbes&r Blütenblatt, &eRune des Frühlings&r, &6Redstone-Wurzel&r.",
              "",
              "Pflanzen in ihrer Nähe wachsen mit Mana deutlich schneller: Felder, Zuckerrohr, Bäume, Blumen. Unter einer Create-Erntemaschine spart sie jedes Knochenmehl.",
          ],
          tasks=[task_item("botania:agricarnation", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16)],
          deps=["rune_spring"], icon="botania:agricarnation"),

    quest("hopperhock", 4.4, 8.8, "&6Pflanz eine Trichtermalve",
          subtitle="Sammelt alles vom Boden auf.",
          description=[
              "Apotheke: &e2 graue&r, &e2 hellgraue&r Blütenblätter, &eRune der Luft&r, &6Redstone-Wurzel&r.",
              "",
              "Sammelt Items in der Umgebung in ein angrenzendes Inventar. Mana ist freiwillig und vergrößert die Reichweite. Ein Rahmen mit Item an einer Truhe filtert, beschriftete Truhen haben Vorrang.",
          ],
          tasks=[task_item("botania:hopperhock", 1)],
          rewards=[reward_item("minecraft:chest", 4)],
          deps=["rune_air"], icon="botania:hopperhock"),

    quest("rannuncarpus", 6.6, 8.8, "&6Pflanz eine Rannawurzel",
          subtitle="Setzt Blöcke, wo sie hingehören.",
          description=[
              "Apotheke: &e2 orange&r, &e1 gelbes&r Blütenblatt, &eRune der Erde&r, &6Redstone-Wurzel&r.",
              "",
              "Hebt platzierbare Items auf und setzt sie im Umkreis als Blöcke, aber nur auf die Blocksorte, die direkt unter ihrem eigenen Boden liegt. Mit Gänseblümchen wird daraus eine Lebestein-Fabrik.",
          ],
          tasks=[task_item("botania:rannuncarpus", 1)],
          rewards=[reward_item("botania:livingrock", 16)],
          deps=["rune_earth"], optional=True, icon="botania:rannuncarpus"),

    quest("clayconia", 8.8, 8.8, "&6Pflanz eine Helitonie",
          subtitle="Aus Sand wird Ton.",
          description=[
              "Apotheke: &e2 hellgraue&r, &e1 graues&r, &e1 türkises&r Blütenblatt, &eRune der Erde&r.",
              "",
              "Verwandelt Sand in der Nähe für etwas Mana in Tonklumpen. Mit Trichtermalve daneben landet er gleich in der Truhe.",
          ],
          tasks=[task_item("botania:clayconia", 1)],
          rewards=[reward_item("minecraft:sand", 32)],
          deps=["rune_earth"], optional=True, icon="botania:clayconia"),

    quest("exoflame", 11, 8.8, "&6Pflanz eine Exoflamme",
          subtitle="Heizt Öfen mit Mana.",
          description=[
              "Apotheke: &e2 rote&r, &e1 graues&r, &e1 hellgraues&r Blütenblatt, Runen des &eFeuers&r und des &eSommers&r.",
              "",
              "Alle Öfen in ihrer Nähe brennen mit Mana, ohne Kohle und schneller als normal. Eine Reihe Öfen um eine Exoflamme ist eine Schmelzerei ohne Brennstofflager.",
          ],
          tasks=[task_item("botania:exoflame", 1)],
          rewards=[reward_item("minecraft:furnace", 4)],
          deps=["rune_summer"], optional=True, icon="botania:exoflame"),

    quest("func_protect", 0, 11, "&6Schütz die Basis mit Blumen",
          subtitle="Drei Wächter, eine Zeile pro Blume.",
          description=[
              "&6Tigerauge&r (gelb, braun, orange, hellgrün, Rune des Herbstes): Creeper explodieren nicht und fliehen vor Spielern.",
              "&6Engelsblüte&r (2 weiß, 2 gelb, 1 orange, Rune des Frühlings): Regeneration für Spieler und zahme Tiere.",
              "&6Medumone&r (2 braun, 2 grau, Rune der Erde, Redstone-Wurzel): hält alle Wesen außer Spielern an Ort und Stelle fest.",
          ],
          tasks=[task_item("botania:tigerseye", 1), task_item("botania:fallen_kanade", 1),
                 task_item("botania:medumone", 1)],
          rewards=[reward_item("minecraft:golden_apple", 1), reward_xp(5)],
          deps=["jaded_amaranthus"], optional=True, icon="botania:tigerseye"),

    quest("func_move", 2.2, 11, "&6Beweg Items und füttere Tiere",
          subtitle="Zwei Helfer für Farmen.",
          description=[
              "&6Ostermühle&r (2 weiß, braun, gelb, Rune der Luft, Redstone-Wurzel): schiebt Items vor sich her. Schleich-Rechtsklick mit dem Stab dreht sie.",
              "&6Pollidisie&r (2 rot, 2 rosa, 1 orange, Runen der Wollust und des Feuers): füttert Tiere mit Futter vom Boden. Mit dem Stab im Funktionsmodus wählst du Alte, Junge oder alle.",
          ],
          tasks=[task_item("botania:daffomill", 1), task_item("botania:pollidisiac", 1)],
          rewards=[reward_item("minecraft:wheat", 32), reward_xp(5)],
          deps=["agricarnation"], optional=True, icon="botania:pollidisiac"),

    quest("func_mobs", 4.4, 11, "&6Verwandle Stein und jage Mobs",
          subtitle="Drei Blumen mit Spezialwirkung.",
          description=[
              "&6Tagemorphes&r (grau, gelb, grün, rot, Runen der Erde und des Feuers, Redstone-Wurzel): macht Stein zu acht Sorten Metamorphem Stein, je nach Biom.",
              "&6Cyazinthe&r (2 violett, 2 magenta, 1 grün, Runen des Wassers und des Herbstes, Redstone-Wurzel): vergiftet Mobs, bis ein Schlag reicht.",
              "&6Vinculotos&r (2 schwarz, 2 violett, 1 grün, Runen des Wassers, der Trägheit und der Wollust, Redstone-Wurzel): Endermen in weitem Umkreis teleportieren zu ihr.",
          ],
          tasks=[task_item("botania:marimorphosis", 1), task_item("botania:hyacidus", 1),
                 task_item("botania:vinculotus", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 8), reward_xp(5)],
          deps=["hopperhock"], optional=True, icon="botania:vinculotus"),

    # ---- Schmuck ----------------------------------------------------------
    quest("baubles_rings", 7.7, 13.5, "&6Schmied Manastahl-Ringe",
          subtitle="Sechs Ringe, eine Zeile pro Ring.",
          description=[
              "&6Auraband&r (Rune des Manas, 4 Manastahl): erzeugt langsam Mana für Tafeln im Inventar.",
              "&6Ring der Magnetisierung&r (Magnetisierungslinse, 4 Manastahl): zieht Items an, nicht beim Schleichen.",
              "&6Ring der Geschickten Bewegung&r (Smaragd, Rune der Luft, 4 Manastahl): Doppeltippen weicht aus.",
              "&6Ring des Erdmantels&r (Rune der Erde, Goldspitzhacke, 4 Manastahl): Eile, harter Stein bricht wie normaler.",
              "&6Ring der Korrektur&r (Ton, 4 Manastahl): nimmt immer das richtige Werkzeug.",
              "&6Ring der Ozeane&r (Rune des Wassers, Kugelfisch, Kabeljau, Herz des Meeres, 4 Manastahl): unter Wasser atmen und schnell schwimmen.",
          ],
          tasks=[task_item("botania:band_of_aura", 1), task_item("botania:ring_of_magnetization", 1),
                 task_item("botania:ring_of_dexterous_motion", 1), task_item("botania:ring_of_the_mantle", 1),
                 task_item("botania:ring_of_correction", 1), task_item("botania:ring_of_chordata", 1)],
          rewards=[reward_item("botania:manasteel_ingot", 8), reward_table("s2_uncommon")],
          deps=["band_of_mana"], optional=True, icon="botania:ring_of_magnetization"),

    quest("baubles_greater", 7.7, 15.6, "&aVeredle drei Ringe mit Terrastahl",
          subtitle="Ein Barren macht jeden Ring größer.",
          description=[
              "Ring plus &e1 Terrastahlbarren&r an der Werkbank:",
              "&6Größeres Manaband&r: etwa viermal so viel Mana. &6Größeres Auraband&r: erzeugt deutlich schneller. &6Größerer Ring der Magnetisierung&r: größere Reichweite.",
              "",
              "Jeder Barren hier fehlt dem Obelisken. Erst nach dem Ziel.",
          ],
          tasks=[task_item("botania:greater_band_of_mana", 1), task_item("botania:greater_band_of_aura", 1),
                 task_item("botania:greater_ring_of_magnetization", 1)],
          rewards=[reward_item("botania:mana_pearl", 4), reward_xp(8)],
          deps=["baubles_rings", "terrasteel"], optional=True, icon="botania:greater_band_of_mana"),

    quest("baubles_amulets", 10.1, 13.5, "&6Trag Amulette",
          subtitle="Vier Anhänger für den Halsplatz.",
          description=[
              "&6Zirrus-Amulett&r (Runen Herbst und Luft, 4 Manafaden, Manastahl): Doppelsprung ohne Fallschaden.",
              "&6Schneeflockanhänger&r (Runen Winter und Wasser, 4 Manafaden, Manastahl): friert Wasser unter dir.",
              "&6Pyroklastanhänger&r (Runen Sommer und Feuer, 4 Manafaden, Manastahl): löscht dich, sobald kein Feuer mehr da ist.",
              "&6Verdorbenes-Blut-Anhänger&r (4 Prismarin, Ghast-Träne, Manadiamant): speichert ein Gebräu und wirkt es dauerhaft.",
          ],
          tasks=[task_item("botania:cirrus_amulet", 1), task_item("botania:snowflake_pendant", 1),
                 task_item("botania:pyroclast_pendant", 1), task_item("botania:tainted_blood_pendant", 1)],
          rewards=[reward_item("botania:mana_string", 8), reward_xp(5)],
          deps=["baubles_rings"], optional=True, icon="botania:cirrus_amulet"),

    quest("baubles_belts", 12.5, 13.5, "&6Schnall Gürtel um",
          subtitle="Drei Gürtel für Tempo und Stand.",
          description=[
              "&6Schärpe des Reisenden&r (Runen Erde und Luft, 4 Leder, Manastahl): schneller, höher springen, Stufen hochlaufen.",
              "&6Schärpe des Ebenenläufers&r (Schärpe des Reisenden, Karte, 2 Weidesamen, Zucker): wird immer schneller, je länger du rennst.",
              "&6Tektonikgürtel&r (Runen Feuer und Erde, 4 Leder, Manastahl): kein Rückstoß mehr.",
          ],
          tasks=[task_item("botania:sojournors_sash", 1), task_item("botania:planestriders_sash", 1),
                 task_item("botania:tectonic_girdle", 1)],
          rewards=[reward_item("minecraft:leather", 16), reward_xp(5)],
          deps=["baubles_amulets"], optional=True, icon="botania:sojournors_sash"),

    quest("baubles_charms", 14.9, 13.5, "&6Sammle Talismane und Umhänge",
          subtitle="Sechs Stücke für Kopf, Körper und Talisman.",
          description=[
              "&6Manaseher-Monokel&r (Managlas, 3 Goldklumpen, Manastahl): zeigt Manastöße durch Wände und Bereiche von Blumen.",
              "&6Winziger Planet&r (4 Lebestein, 4 Stein, Manaperle): zieht Manastöße in eine Umlaufbahn um dich.",
              "&6Zauber der Gütigen Göttin&r (2 rosa, Runen Wasser und Frühling, Manadiamant): Explosionen zerstören keine Blöcke.",
              "&6Der Betrachter&r (5 Eisen, Enderauge, Smaragd): lässt das gehaltene Item in Truhen und Mobs leuchten.",
              "&6Drittes Auge&r (4 Goldkarotten, Rune der Erde, 2 Quarzblöcke, Enderauge, Manadiamant): Mobs leuchten durch Wände.",
              "&6Unsichtbarkeitsmantel&r (2 Prismarin, 2 Wolle, 4 Managlas, Manaperle): macht dich unsichtbar.",
          ],
          tasks=[task_item("botania:manaseer_monocle", 1), task_item("botania:tiny_planet", 1),
                 task_item("botania:benevolent_goddess_charm", 1), task_item("botania:the_spectator", 1),
                 task_item("botania:third_eye", 1), task_item("botania:invisibility_cloak", 1)],
          rewards=[reward_item("botania:mana_diamond", 2), reward_table("s2_uncommon")],
          deps=["baubles_belts"], optional=True, icon="botania:third_eye"),

    # ---- Terrastahl -------------------------------------------------------
    quest("plate", 17.5, 6.5, "&aBau die Terrestrische Agglomerationsplatte",
          subtitle="Die Schmiede für Terrastahl.",
          description=[
              "&eRezept auf Kronwerke:&r oben Messinggehäuse, Lapisblock, Messinggehäuse. Mitte Rune des Wassers, Manaquarzblock, Rune des Feuers. Unten Rune der Erde, Rune des Manas, Rune der Luft.",
              "",
              "Die Runen werden hier &cverbraucht&r. Plan je eine Elementarrune und eine Rune des Manas nur für die Platte ein.",
          ],
          tasks=[task_item("botania:terrestrial_agglomeration_plate", 1)],
          rewards=[reward_item("minecraft:lapis_block", 4), reward_table("s2_uncommon")],
          deps=["brass_casing", "rune_mana", "mana_quartz", "rune_water", "rune_fire", "rune_earth", "rune_air"],
          icon="botania:terrestrial_agglomeration_plate", size=2.0, shape="square"),

    quest("plate_base", 17.5, 9.2, "&7Leg das Fundament",
          subtitle="Ein Schachbrett aus Lapis und Lebestein.",
          description=[
              "3x3 unter der Platte: &6Lebestein&r in der Mitte und den vier Ecken, &9Lapisblöcke&r auf den vier Kanten. Die Platte steht auf dem mittleren Lebestein.",
              "",
              "Die Lexica projiziert das Muster auf der Terrastahl-Seite als Vorschau in die Welt.",
          ],
          tasks=[task_item("minecraft:lapis_block", 4), task_item("botania:livingrock", 5)],
          rewards=[reward_xp(5)],
          deps=["plate"], icon="minecraft:lapis_block"),

    quest("mana_spark", 15, 8.8, "&6Setz Manafunken",
          subtitle="Mana ohne Strahl und ohne Verlust.",
          description=[
              "&e2 Blütenblätter&r, &e2 Lohenstaub&r, &e1 Goldklumpen&r. Ein Funke auf ein Becken, einer auf die Platte, und die Platte zieht ihr Mana direkt.",
              "",
              "Mehrere Becken mit Funken beschleunigen. Schleich-Rechtsklick mit dem Stab entfernt einen Funken, gefärbte Funken bilden getrennte Netze.",
          ],
          tasks=[task_item("botania:mana_spark", 2)],
          rewards=[reward_item("minecraft:blaze_powder", 4)],
          deps=["plate"], optional=True),

    quest("terrasteel", 20.5, 6.5, "&a&lSchmied Terrastahl",
          subtitle="Ein halbes Becken für einen Barren.",
          description=[
              "Je einen &6Manastahlbarren&r, eine &6Manaperle&r und einen &6Manadiamanten&r auf die fertige Platte werfen. Sie zieht &d500 000 Mana&r, dann liegt ein &aTerrastahlbarren&r da.",
              "",
              img(item_texture("botania:terrasteel_ingot"), 32, 32),
              "",
              "&cAchtung:&r Hebst du eine Zutat auf, bricht es ab und &calles Mana ist weg&r.",
              "",
              "Terrastahl brauchst du für Terraklinge und Rüstung, einen pro Runenkern, 50 für den Obelisken und in Stufe 3 als Klumpen für Portal und Naturapylonen.",
          ],
          tasks=[task_item("botania:terrasteel_ingot", 2)],
          rewards=[reward_item("botania:mana_diamond", 2), reward_table("s2_uncommon")],
          deps=["plate_base"], icon="botania:terrasteel_ingot", size=2.5, shape="diamond"),

    quest("terra_gear", 20.5, 9.4, "&aSchmied die Terraklinge",
          subtitle="Netherit-Klasse, mit Mana repariert.",
          description=[
              "&e2 Terrastahlbarren&r und &e1 Lebeholzzweig&r. So stark wie ein Netheritschwert, feuert beim Schlagen einen Strahl mit gleichem Schaden.",
              "",
              "Die Terrastahlrüstung entsteht aus Manastahlrüstung, Terrastahl, Zweigen und einer Jahreszeitenrune pro Teil. Jeder Barren hier fehlt dem Obelisken.",
          ],
          tasks=[task_item("botania:terra_blade", 1)],
          rewards=[reward_xp(10)],
          deps=["terrasteel"], optional=True, icon="botania:terra_blade"),

    # ---- Fuer den Obelisken -----------------------------------------------
    quest("pearl_factory", 23.5, 6.5, "&bBau eine Perlenfabrik",
          subtitle="Sechshundert Perlen wollen verdient sein.",
          description=[
              "Endermanfarm, Förderband zu einem Becken mit &6Messinggehäuse&r darunter, Trichtermalve am Beckenrand, Truhe. Fertig.",
              "",
              "600 Perlen sind &d3,6 Millionen Mana&r und 600 Enderperlen. Eine Truhe, die du neben den Obelisken stellst, liefert alle zwei Sekunden für dich ab.",
          ],
          tasks=[task_item("botania:mana_pearl", 64)],
          rewards=[reward_item("minecraft:ender_pearl", 16), reward_table("s2_uncommon")],
          deps=["terrasteel", "mana_pearl"], icon="botania:mana_pearl"),

    quest("terra_line", 26, 6.5, "&aSchmied Terrastahl in Serie",
          subtitle="Fünfzig Barren, jeder ein halbes Becken.",
          description=[
              "50 Barren sind gut &d25 Millionen Mana&r, 50 Manastahl, 50 Perlen und 50 Diamanten.",
              "",
              "&eWas hilft:&r viele Becken mit Manafunken um die Platte, mehrere Platten, Thermalilien an Lava, Gourmaryllis mit wechselndem Essen, Rosa Arcana an der Mob-Farm. Nichts aufheben, solange die Platte arbeitet.",
          ],
          tasks=[task_item("botania:terrasteel_ingot", 8)],
          rewards=[reward_item("botania:mana_diamond", 4), reward_table("s2_uncommon")],
          deps=["terrasteel"], icon="botania:terrasteel_ingot"),

    quest("rune_core", 23.5, 9.3, "&dCrafte einen Runenkern",
          subtitle="Der Meilenstein der Magie in Stufe 2.",
          description=[
              "Oben &9Rune des Wassers&r, &bManaperle&r, &fRune der Luft&r. Mitte &6Messingblech&r, &aTerrastahlbarren&r, &6Messingblech&r. Unten &cRune des Feuers&r, &bManaperle&r, &6Rune der Erde&r.",
              "",
              img("kronwerke:textures/item/rune_core.png", 32, 32),
              "",
              "Die Runen werden verbraucht. Messingbleche presst die Mechanische Presse von Create.",
              "",
              "&eKronwerke:&r Der Obelisk will &e8 Runenkerne&r, feste Zahl, jeder zählt wie 150 Perlen. Herstellen geht erst in Stufe 2, abgeben nur, solange das Stufenziel aktiv ist.",
          ],
          tasks=[task_item("kronwerke:rune_core", 1)],
          rewards=[reward_table("s2_uncommon"), reward_xp(10)],
          deps=["terrasteel"], icon="kronwerke:rune_core", size=1.75, shape="gear"),

    quest("obelisk", 26, 9.3, "&d&lBring die Magie zum Obelisken",
          subtitle="Das Messingwerk wartet auf seine Blumen.",
          description=[
              "Gib &e600 Manaperlen&r, &e50 Terrastahlbarren&r und &e8 Runenkerne&r am Obelisken ab. Rechtsklick legt den Stapel ab, Schleich-Rechtsklick alles, oder eine Truhe daneben.",
              "",
              "Sind Technik und Magie voll, öffnet &6Stufe 3 (Stahlwerk)&r mit einem Event im Stream, und mit ihr das Elfenportal, siehe &aBotania: Alfheim&r.",
              "",
              "&eVorbereiten:&r Schimmerndes Lebeholz (Stamm und Glowstonestaub), zwei Manapylonen (2 Gold, 2 Manastahl, 1 Manadiamant), zwei Naturapylonen und volle Becken. Das Portal will 200 000 Mana zum Öffnen.",
          ],
          tasks=[task_checkmark("Abgeliefert")],
          rewards=[reward_table("s2_rare"), reward_xp(15)],
          deps=["pearl_factory", "terra_line", "rune_core"], icon="botania:terrasteel_block", size=2.0, shape="gear"),

]

images = [
    banner("botania_runes/title", "Botania: Runen", 13, -5.2, height=1.8, kind="title", colour="magic"),
    banner("botania_runes/manastahl", "Manastahl", 2.6, -2.9, height=0.9, colour="magic"),
    banner("botania_runes/runen", "Runen", 16.3, -2.7, height=0.9, colour="magic"),
    banner("botania_runes/suenden", "Sündenrunen", 25.6, -3.3, height=0.9, colour="magic"),
    banner("botania_runes/blumen", "Neue Blumen", 5.5, 4.7, height=0.9, colour="nature"),
    banner("botania_runes/schmuck", "Schmuck", 11.3, 12.0, height=0.9, colour="brass"),
    banner("botania_runes/terrastahl", "Terrastahl", 18, 4.3, height=0.9, colour="nature"),
    banner("botania_runes/obelisk", "Für den Obelisken", 24.8, 4.3, height=0.9, colour="magic"),
]

chapter(C, "Botania: Runen", "botania:rune_of_mana", "magic", quests, shape="circle", order=11, stage=2,
        subtitle=["Stufe 2. Manastahl, Runen, Terrastahl und der Runenkern."], images=images)
