"""Create in stage 1 (Steinwerk): from the first andesite to an andesite alloy line for the obelisk.

Everything here is open on day one: andesite machines, water wheels and windmills, press,
millstone, mixer without heat, fans, belts, funnels, the Create 6 package logistics, pipes and
the first contraptions. Brass, the blaze burner, deployers, crafters and trains are stage 2
(create_brass.py and create_trains.py)."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "create"


def head(name, text, left, y, height=0.9, kind="section", colour="brass"):
    """A banner whose left edge sits at x = left."""
    b = banner(f"{C}/{name}", text, 0, y, height=height, kind=kind, colour=colour)
    b["x"] = round(left + b["width"] / 2, 2)
    return b


# Two columns of sections. Column A starts at x 0, column B at x 17.
A, B = 0, 17

quests = [
    # ---- Grundlagen -------------------------------------------------------
    quest("welcome", A, 2.5, "&6&lCreate",
          subtitle="Drehbewegung statt Strom: willkommen in der Werkstatt.",
          description=[
              "Create ist die Technik-Mod, mit der auf Kronwerke alles anfängt. Statt Strom erzeugst du hier &dRotation&r: Wasserräder, Windmühlen oder eine Handkurbel drehen Wellen und Zahnräder, und die treiben Maschinen an, die mahlen, pressen, mischen, sägen, bohren und sogar ganze Bauwerke bewegen.",
              "",
              "Dieses Kapitel gehört zu &6Stufe 1, dem Steinwerk&r. Alles hier funktioniert ab dem ersten Tag: Andesit, Wasserräder, Presse, Mixer ohne Hitze, Förderbänder, Lüfter, Rohre, das Paketsystem und die ersten Kontraptionen. &6Messing&r, der &6Lohenbrenner&r, Einsatzgeräte, mechanische Handwerkseinheiten und Züge öffnen erst mit &6Stufe 2, dem Messingwerk&r. Gesperrte Items kannst du schon tragen, aber nicht benutzen; der Tooltip sagt dir, ab welcher Stufe sie gehen.",
              "",
              "&eDer wichtigste Trick überhaupt:&r Halte über einem Create-Block im Inventar oder in JEI die Taste &eW&r gedrückt. Dann öffnet sich die &6Ponder&r-Ansicht, eine kleine animierte Anleitung, die dir Schritt für Schritt zeigt, wie der Block funktioniert. Sie erklärt vieles besser als jeder Text.",
              "",
              "Am Ende dieses Kapitels steht eine Fabrik, die das Obelisk-Ziel des Servers mit &6Andesitlegierung&r und &6Bruchstein&r füttert.",
          ],
          tasks=[task_checkmark("Los geht's")],
          rewards=[reward_item("create:andesite_alloy", 8), reward_table("s1_common")],
          icon="create:large_cogwheel", size=2.0, shape="hexagon"),

    quest("andesite", A + 2.5, 1.75, "&6Andesit",
          subtitle="Der graue Stein, auf dem alles aufbaut.",
          description=[
              "&6Andesit&r ist der Grundstoff fast jeder Create-Maschine der ersten Stufe. Du findest ihn in großen Adern im Stein unter der Oberfläche, oft direkt neben Granit und Diorit. Mit einer normalen Spitzhacke abgebaut bleibt er Andesit.",
              "",
              "Sammle großzügig: du brauchst ihn zu Hunderten, und das Obelisk-Ziel dieser Stufe will am Ende tausende Legierungen daraus sehen.",
              "",
              "&6Tipp:&r Später kann die &6Mechanische Presse&r über einem &6Becken&r aus zwei &6Feuerstein&r, einem &6Kies&r und etwas &bLava&r neuen Andesit verdichten. Damit wird Andesit erneuerbar, und du musst nicht ewig graben.",
          ],
          tasks=[task_item("minecraft:andesite", 64)],
          rewards=[reward_item("minecraft:iron_nugget", 18), reward_xp(2)],
          deps=["welcome"]),

    quest("zinc", A + 2.5, 3.75, "&6Zink",
          subtitle="Das zweite Metall von Create.",
          description=[
              "&6Zinkerz&r gibt es in der Oberwelt, im normalen Stein und weiter unten als &6Tiefenschiefer-Zinkerz&r. Abgebaut bekommst du &6Rohzink&r, das du im Ofen zu &6Zinkbarren&r schmilzt. Ein Barren ergibt neun &6Zinkklumpen&r.",
              "",
              "In Stufe 1 brauchst du Zink vor allem für eines: statt Eisenklumpen darfst du auch Zinkklumpen in die &6Andesitlegierung&r stecken. Das schont dein Eisen, das du für Bleche, Eimer und Werkzeug brauchst.",
              "",
              "Behalte Zink trotzdem im Blick. In &6Stufe 2&r wird daraus zusammen mit Kupfer &6Messing&r, und das Obelisk-Ziel dort verlangt tausende Messingbarren. Wer jetzt eine Kiste Rohzink hortet, hat später einen Vorsprung.",
              img(item_texture("create:raw_zinc"), 32, 32),
          ],
          tasks=[task_item("create:raw_zinc", 16)],
          rewards=[reward_item("create:zinc_ingot", 4), reward_xp(3)],
          deps=["welcome"]),

    quest("andesite_alloy", A + 5, 2.75, "&6Andesitlegierung",
          subtitle="Das Herz jeder Maschine dieser Stufe.",
          description=[
              "Lege im Handwerksraster zwei &6Andesit&r und zwei &6Eisenklumpen&r schräg gegenüber, oder Zinkklumpen statt Eisen. Heraus kommt eine &6Andesitlegierung&r.",
              img(item_texture("create:andesite_alloy"), 32, 32),
              "Von Hand ist das teuer: zwei Andesit pro Legierung. Sobald du einen &6Mechanischen Mixer&r hast, mischt er aus einem Andesit und einem Klumpen eine Legierung, also doppelt so sparsam und ganz ohne dich.",
              "",
              "Aus Legierung entstehen Wellen, Zahnräder, Gehäuse, Schleusen und fast alles andere in diesem Kapitel. Außerdem ist sie der &6Technik-Pfeiler&r des Obelisk-Ziels von Stufe 1: bei 30 Spielern will der Obelisk 3 000 Stück sehen. Jede Legierung, die du übrig hast, ist dort gut aufgehoben.",
          ],
          tasks=[task_item("create:andesite_alloy", 32)],
          rewards=[reward_item("minecraft:iron_nugget", 32), reward_table("s1_common")],
          deps=["andesite"], icon="create:andesite_alloy", size=1.75, shape="gear"),

    quest("casing", A + 7.5, 1.75, "&6Andesitgehäuse",
          subtitle="Rinde ab, Legierung drauf.",
          description=[
              "Entrinde einen Stamm mit der Axt und setz ihn als Block ab. Rechtsklicke ihn dann mit einer &6Andesitlegierung&r in der Hand: der Block wird zum &6Andesitgehäuse&r. Mit entrindetem Holz geht es genauso.",
              "",
              "Gehäuse sind das Gerüst fast aller Maschinen: Mahlstein, Presse, Mixer, Lüfter, Getriebe, Kolben und Depot haben eines im Rezept. Ein Stapel Stämme im Vorrat und du machst zehn Gehäuse in einem Rutsch.",
              "",
              "&6Tipp:&r Rechtsklickst du mit einem Gehäuse auf eine liegende Welle, wird sie ummantelt. Das sieht ordentlicher aus und schützt vor versehentlichem Abbauen.",
          ],
          tasks=[task_item("create:andesite_casing", 8)],
          rewards=[reward_item("minecraft:oak_log", 16), reward_xp(2)],
          deps=["andesite_alloy"]),

    quest("shaft", A + 7.5, 3.75, "&6Welle",
          subtitle="Die einfachste Leitung für Drehbewegung.",
          description=[
              "Zwei &6Andesitlegierungen&r übereinander ergeben acht &6Wellen&r. Eine Welle gibt Rotation in gerader Linie weiter, so weit du willst, ohne dabei Drehzahl oder Kraft zu verlieren.",
              "",
              "Wellen drehen nur entlang ihrer eigenen Achse. Um eine Ecke kommst du mit Zahnrädern oder einem Getriebe. Mit dem &6Schraubenschlüssel&r kannst du eine gesetzte Welle später drehen, ohne sie abzubauen.",
          ],
          tasks=[task_item("create:shaft", 16)],
          rewards=[reward_item("create:andesite_alloy", 4), reward_xp(2)],
          deps=["andesite_alloy"]),

    quest("cogwheel", A + 10, 3.75, "&6Zahnräder",
          subtitle="Klein, groß und immer im Eingriff.",
          description=[
              "Ein &6Zahnrad&r ist eine Welle mit einem Brett, ein &6Großes Zahnrad&r eine Welle mit zwei Brettern, oder ein kleines Zahnrad mit einem weiteren Brett.",
              "",
              "Zwei kleine Zahnräder nebeneinander greifen ineinander und geben die Drehung seitwärts weiter, dabei kehrt sich die Richtung um. Ein großes und ein kleines Zahnrad greifen schräg versetzt ineinander, und zwei Zahnräder im rechten Winkel zueinander leiten die Drehung um die Ecke.",
              "",
              "Das ist der wichtigste Hebel für die Drehzahl: treibt ein großes Zahnrad ein kleines an, verdoppelt sie sich. Treibt ein kleines ein großes an, halbiert sie sich. Mehr Drehzahl heißt schnellere Maschinen, aber auch mehr Belastung. Mehr dazu im Abschnitt Energie.",
          ],
          tasks=[task_item("create:cogwheel", 8), task_item("create:large_cogwheel", 4)],
          rewards=[reward_item("create:cogwheel", 4), reward_xp(3)],
          deps=["shaft"]),

    # ---- Energie ----------------------------------------------------------
    quest("hand_crank", A, 9, "&6Handkurbel",
          subtitle="Muskelkraft für den Anfang.",
          description=[
              "Drei Bretter und eine &6Andesitlegierung&r ergeben eine &6Handkurbel&r. Solange du sie mit gedrückter rechter Maustaste festhältst, liefert sie &d32 RPM&r und &d256 SU&r Belastbarkeit.",
              "",
              "Das reicht, um einen Mahlstein kurz laufen zu lassen oder eine Kontraption zu testen. Auf Dauer ist sie nichts, denn Kurbeln macht hungrig. Aber sie zeigt dir schnell, ob dein Aufbau überhaupt funktioniert, bevor du ein Wasserrad baust.",
          ],
          tasks=[task_item("create:hand_crank", 1)],
          rewards=[reward_item("minecraft:bread", 6), reward_xp(2)],
          deps=["andesite_alloy"]),

    quest("water_wheel", A + 2.5, 9, "&6Wasserrad",
          subtitle="Deine erste echte Kraftquelle.",
          description=[
              "Das &6Wasserrad&r besteht aus acht Brettern um eine Welle. Setz es so, dass &bfließendes Wasser&r an seinen Schaufeln vorbeiläuft, am besten von oben auf eine Seite. Stehendes Wasser dreht nichts, und Wasser an weiteren Seiten bringt keine zusätzliche Kraft.",
              "",
              "Ein Wasserrad liefert &d8 RPM&r und &d256 SU&r Belastbarkeit (Stress Units). Mehrere Wasserräder auf derselben Welle addieren ihre Belastbarkeit, nicht die Drehzahl. Vier oder fünf Räder in einer Reihe an einem Bach sind ein solider Start.",
              "",
              "&6Tipp:&r Die Holzsorte ist nur Optik. Rechtsklickst du ein gesetztes Rad mit Brettern einer anderen Holzart, bekommt es deren Aussehen.",
              "",
              "&cHäufiger Fehler:&r Das Wasser fließt unter dem Rad durch statt über die Schaufeln. Mit der Ponder-Ansicht (&eW&r) siehst du, wie es richtig aussieht.",
          ],
          tasks=[task_item("create:water_wheel", 4)],
          rewards=[reward_item("minecraft:water_bucket", 1), reward_table("s1_common")],
          deps=["shaft"], icon="create:water_wheel", size=1.75, shape="gear"),

    quest("large_water_wheel", A + 5, 8, "&6Großes Wasserrad",
          subtitle="Langsamer, aber viel kräftiger.",
          description=[
              "Das &6Große Wasserrad&r ist 3 x 3 Blöcke groß und entsteht aus einem Wasserrad und acht Brettern. Es dreht sich nur mit &d4 RPM&r, bietet dafür aber &d512 SU&r Belastbarkeit.",
              "",
              "Mit Zahnrädern holst du die Drehzahl zurück: ein großes Zahnrad, das ein kleines antreibt, macht aus 4 RPM 8 RPM, noch eine Stufe macht 16. Die Belastbarkeit ändert sich durchs Übersetzen nicht, aber jede Maschine verbraucht bei höherer Drehzahl mehr davon.",
          ],
          tasks=[task_item("create:large_water_wheel", 1)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["water_wheel"]),

    quest("windmill", A + 5, 10, "&6Windmühle",
          subtitle="Segel im Wind, ganz ohne Wasser.",
          description=[
              "Ein &6Windmühlenlager&r (Holzstufe, Stein, Welle) und mindestens &6acht Windmühlen-Segel&r ergeben eine Windmühle. Das Lager nimmt den Block vor seiner Vorderseite mit. Baue dort dein Windrad aus Segeln (Wolle, Stöcke, Legierung) und verbinde alles mit &6Sekundenkleber&r zu einem Bauwerk. Ein Rechtsklick aufs Lager, und das Ganze dreht sich; die Drehrichtung stellst du am Wertefeld ein.",
              "",
              "Je acht Segel bringen &d1 RPM&r, und jedes RPM trägt &d512 SU&r. Eine große Mühle mit 32 Segeln läuft also mit 4 RPM und trägt 2 048 SU, mehr als acht Wasserräder zusammen.",
              "",
              "Sie braucht Platz: rund um die Segel darf nichts im Weg stehen. Einfärben kannst du die Segel mit Farbstoff.",
          ],
          tasks=[task_item("create:windmill_bearing", 1), task_item("create:white_sail", 8)],
          rewards=[reward_item("minecraft:white_wool", 16), reward_xp(3)],
          deps=["water_wheel"]),

    quest("stress", A + 7.5, 9, "&dDrehzahl und Belastung",
          subtitle="RPM und SU, einmal richtig erklärt.",
          description=[
              "Jedes Netz aus Wellen und Zahnrädern hat zwei Werte: die &dDrehzahl&r in RPM und die &dBelastbarkeit&r in SU. Quellen wie Wasserräder liefern Belastbarkeit, Maschinen verbrauchen sie.",
              "",
              "Wie viel eine Maschine verbraucht, hängt von ihrer Drehzahl ab: ihr Grundwert wird mit der RPM malgenommen. Die &6Mechanische Presse&r kostet 8 SU pro RPM, also 256 SU bei 32 RPM. Mahlstein, Mixer, Säge, Bohrer und Pumpe kosten 4 SU pro RPM, ein Lüfter 2. Wellen, Zahnräder, Getriebe und Förderbänder kosten nichts.",
              "",
              "Verbrauchen die Maschinen mehr, als die Quellen liefern, ist das Netz &cüberlastet&r: alles bleibt stehen. Dann hilft nur mehr Quelle, weniger Drehzahl oder ein zweites, getrenntes Netz.",
              "",
              "Ab &d30 RPM&r gilt eine Drehzahl als mittel, ab &d100 RPM&r als schnell, das Maximum sind 256 RPM. Schneller heißt: die Maschine arbeitet schneller.",
              "",
              "&6Tipp:&r Ein &6Tachometer&r (Kompass auf Andesitgehäuse) zeigt die Drehzahl an seiner Stelle, im Handwerksraster umgewandelt wird er zum &6Stressmesser&r, der die freie Belastbarkeit des ganzen Netzes anzeigt. Beide geben auch ein Redstone-Signal aus.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(5)],
          deps=["water_wheel"], icon="create:stressometer", shape="diamond"),

    quest("gearbox", A + 10, 8, "&6Getriebe",
          subtitle="Rotation in alle Richtungen.",
          description=[
              "Ein &6Getriebe&r ist ein Andesitgehäuse mit vier Zahnrädern drumherum. Es nimmt Rotation an einer Seite an und gibt sie an alle anderen weiter, auch um 90 Grad um die Ecke. Die gegenüberliegende Seite dreht sich dabei andersherum.",
              "",
              "Das &6Vertikale Getriebe&r ist dasselbe Teil, nur liegend. Im Handwerksraster wandelst du das eine ins andere um.",
              "",
              "Getriebe sind der einfachste Weg, eine lange Antriebswelle auf mehrere Maschinenreihen zu verteilen.",
          ],
          tasks=[task_item("create:gearbox", 2)],
          rewards=[reward_item("create:andesite_casing", 4), reward_xp(2)],
          deps=["cogwheel", "casing"]),

    quest("clutch_gearshift", A + 10, 10, "&6Kupplung und Gangschaltung",
          subtitle="Mit Redstone an, aus und rückwärts.",
          description=[
              "Eine &6Kupplung&r (Andesitgehäuse, Welle, Redstone) trennt die Welle, solange sie ein &cRedstone-Signal&r bekommt. Alles dahinter bleibt stehen, alles davor läuft weiter.",
              "",
              "Eine &6Gangschaltung&r (Andesitgehäuse, Zahnrad, Redstone) kehrt stattdessen die Drehrichtung um, solange sie ein Signal bekommt. Damit lässt du Kolben, Flaschenzüge oder Förderbänder mit einem Hebel vor und zurück fahren.",
              "",
              "Ein &6Ummantelter Kettenriemen&r (Andesitgehäuse und drei Eisen- oder Zinkklumpen) überträgt Rotation zwischen Kettenriemen, die direkt aneinander liegen, auch um die Ecke und ohne sichtbare Zahnräder.",
          ],
          tasks=[task_item("create:clutch", 1), task_item("create:gearshift", 1)],
          rewards=[reward_item("minecraft:redstone", 16), reward_xp(3)],
          deps=["gearbox"]),

    # ---- Verarbeitung -------------------------------------------------------
    quest("millstone", A, 16, "&6Mahlstein",
          subtitle="Deine erste Maschine.",
          description=[
              "Der &6Mahlstein&r (Zahnrad, Andesitgehäuse, Stein) wird von der Seite oder von oben über Zahnräder angetrieben. Wirf Items oben hinein, oder lass sie aus einem Schacht hineinfallen, und er mahlt sie.",
              "",
              "Nützlich für den Anfang: &6Weizen&r zu &6Weizenmehl&r, &6Bruchstein&r zu &6Kies&r, &6Kies&r zu &6Feuerstein&r, Blumen zu doppelt so viel Farbstoff, Knochen zu Knochenmehl. Alle Rezepte zeigt JEI unter dem Mahlstein.",
              "",
              "Das Ergebnis holst du mit Rechtsklick heraus, oder eine &6Andesitschleuse&r an seiner Seite zieht es automatisch ab. Er kostet 4 SU pro RPM und ist bei wenig Drehzahl gemütlich langsam.",
              "",
              "Die großen Brüder, die &6Mahlwerkräder&r mit Bonus-Erzen, kommen in Stufe 2.",
          ],
          tasks=[task_item("create:millstone", 1)],
          rewards=[reward_item("minecraft:wheat", 16), reward_table("s1_common")],
          deps=["water_wheel"]),

    quest("press", A + 2.5, 17, "&6Mechanische Presse",
          subtitle="Aus Barren werden Bleche.",
          description=[
              "Die &6Mechanische Presse&r (Welle, Andesitgehäuse, Eisenblock) bekommt Rotation von oben oder von der Seite. Setz sie zwei Blöcke über ein &6Depot&r oder ein Förderband, also mit einem Block Luft dazwischen: dort fährt ihr Stempel hinunter. Das Depot baust du aus einer Legierung und einem Andesitgehäuse.",
              "",
              "Leg einen &6Eisenbarren&r aufs Depot (Rechtsklick), und die Presse stampft ihn zum &6Eisenblech&r. Über einem laufenden Förderband presst sie alles, was darunter durchfährt, ohne dass du etwas tun musst.",
              img(item_texture("create:iron_sheet"), 32, 32),
              "Bleche brauchst du ab jetzt ständig. Die Presse kostet &d8 SU pro RPM&r, bei 32 RPM also 256 SU. Das ist genau ein Wasserrad, plane lieber zwei ein.",
          ],
          tasks=[task_item("create:mechanical_press", 1), task_item("create:depot", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["water_wheel"], icon="create:mechanical_press", size=2.0, shape="gear"),

    quest("sheets", A + 5, 17, "&6Bleche",
          subtitle="Eisen, Kupfer, Gold: alles wird flach.",
          description=[
              "Presse ein paar &6Eisenbleche&r, &6Kupferbleche&r und &6Goldbleche&r. Eisenblech steckt in Propeller, Rührstab, Schacht und Sekundenkleber, Kupferblech in Flüssigkeitsrohren und Tanks, Goldblech in Ingenieursbrille, Schraubenschlüssel und Gewichtetem Werfer.",
              "",
              "&6Tipp:&r Über einem &6Becken&r statt einem Depot &everdichtet&r die Presse: neun Barren zu einem Block, oder zwei Feuerstein, ein Kies und etwas Lava zu neuem Andesit. Welche Verdichtungsrezepte es gibt, zeigt JEI.",
          ],
          tasks=[task_item("create:iron_sheet", 16), task_item("create:copper_sheet", 8), task_item("create:golden_sheet", 4)],
          rewards=[reward_item("minecraft:copper_ingot", 16), reward_xp(3)],
          deps=["press"]),

    quest("goggles", A + 7.5, 15, "&6Ingenieursbrille",
          subtitle="Sieh, was deine Maschinen denken.",
          description=[
              "Faden, zwei Glas und ein &6Goldblech&r. Setz die &6Ingenieursbrille&r auf und schau auf eine Welle, eine Quelle oder eine Maschine: ein Einblendfenster zeigt Drehzahl, Belastbarkeit, Verbrauch, Tankinhalte und vieles mehr.",
              img(item_texture("create:goggles"), 32, 32),
              "Ohne Brille baust du blind. Mit ihr siehst du sofort, warum eine Anlage stillsteht.",
              "",
              "&6Tipp:&r Du musst dich nicht zwischen Helm und Brille entscheiden. Kombinierst du die Brille im Handwerksraster mit einem Helm, sitzt sie fest darauf, und der Helm schützt weiter.",
          ],
          tasks=[task_item("create:goggles", 1)],
          rewards=[reward_xp(5)],
          deps=["sheets"]),

    quest("wrench", A + 7.5, 17, "&6Schraubenschlüssel",
          subtitle="Drehen, umbauen, einsammeln.",
          description=[
              "Mit dem &6Schraubenschlüssel&r (Goldbleche, Zahnrad, Stock) drehst du Create-Blöcke per Rechtsklick, ohne sie abzubauen. Schleichen und Rechtsklick hebt einen Create-Block sofort auf, ganz ohne Spitzhacke.",
              img(item_texture("create:wrench"), 32, 32),
              "Du brauchst ihn auch, um Schleusen umzupolen, Kontraptionen auszurichten und Züge zu justieren. Gehört in jede Hotbar.",
          ],
          tasks=[task_item("create:wrench", 1)],
          rewards=[reward_xp(3)],
          deps=["sheets"]),

    quest("fan", A + 5, 19, "&6Ummantelter Lüfter",
          subtitle="Wind, der wäscht, schmilzt und räuchert.",
          description=[
              "Ein &6Propeller&r (Eisenbleche um eine Legierung), ein Andesitgehäuse und eine Welle ergeben den &6Ummantelten Lüfter&r. Je nach Drehrichtung bläst er Luft weg oder saugt sie an, bis zu 20 Blöcke weit, und schiebt dabei Items und Mobs mit.",
              "",
              "Richtig stark wird er mit einem Block direkt vor der Öffnung. Items, die durch den Luftstrom fliegen oder davor auf einem Förderband liegen, werden verarbeitet:",
              "&bWasser&r davor: &eWaschen&r. Kies gibt Feuerstein und Eisenklumpen, Sand gibt Ton, roter Sand Goldklumpen, Mehl wird zu Teig.",
              "&cLava&r davor: &eSchmelzen&r wie im Ofen, zum Beispiel Rohzink zu Zinkbarren oder Sand zu Glas.",
              "&6Feuer&r davor: &eRäuchern&r, also Essen garen wie im Räucherofen.",
              "",
              "Für das &eHeimsuchen&r mit Seelenfeuer brauchst du Seelensand aus dem Nether, und der öffnet erst mit Stufe 2.",
          ],
          tasks=[task_item("create:encased_fan", 1)],
          rewards=[reward_item("minecraft:gravel", 32), reward_table("s1_common")],
          deps=["sheets"], icon="create:encased_fan", size=1.5),

    quest("washing", A + 7.5, 19, "&6Kieswäsche",
          subtitle="Eisen aus Kies, ganz nebenbei.",
          description=[
              "Lass einen Lüfter durch einen Wasserblock blasen und schick &6Kies&r durch den Strom, am besten auf einem Förderband. Jeder Kies gibt mit etwas Glück &6Feuerstein&r und &6Eisenklumpen&r.",
              "",
              "Mit einem &6Mahlstein&r davor, der &6Bruchstein&r zu Kies mahlt, hast du eine kleine Kette: Bruchstein rein, Eisenklumpen raus. Genau die Klumpen, die in die Andesitlegierung gehören.",
              "",
              "Der Ertrag ist bescheiden (etwa jeder achte Kies gibt einen Klumpen), aber er kostet nur Bruchstein, und den liefert ein Bohrer am Bruchsteingenerator ohne Ende. Der Feuerstein wandert in die Presse und wird zu neuem Andesit.",
          ],
          tasks=[task_item("minecraft:iron_nugget", 64)],
          rewards=[reward_item("minecraft:gravel", 64), reward_xp(5)],
          deps=["fan", "millstone"]),

    quest("mixer", A + 10, 16, "&6Mechanischer Mixer",
          subtitle="Rühren statt kneten.",
          description=[
              "Der &6Mechanische Mixer&r (Zahnrad, Andesitgehäuse, Rührstab aus Eisenblechen und Legierung) arbeitet über einem &6Becken&r (fünf Legierungen). Setz ihn zwei Blöcke über das Becken, mit einem Block Luft dazwischen, und treib ihn an.",
              "",
              "Leg die Zutaten ins Becken, von Hand, per Schacht oder per Schleuse, und er rührt los. Das Ergebnis bleibt im Becken, bis eine &6Andesitschleuse&r an der Beckenseite es herausholt.",
              "",
              "Ohne Hitze kann der Mixer in Stufe 1 schon eine Menge: &6Andesitlegierung&r aus einem Andesit und einem Klumpen, &6Teig&r aus Mehl und Wasser, &6Zellstoff&r für Karton, Schlamm, und viele formlose Handwerksrezepte ganz automatisch.",
              "",
              "Rezepte mit dem Hinweis &cErhitzt&r oder &cÜberhitzt&r in JEI brauchen einen &6Lohenbrenner&r unter dem Becken. Der kommt mit Stufe 2, und auf diesem Server braucht sein Gehäuse zwei &dQuelljuwelen&r aus Ars Nouveau. Messing wird genau so gemischt.",
          ],
          tasks=[task_item("create:mechanical_mixer", 1), task_item("create:basin", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["sheets"], icon="create:mechanical_mixer", size=2.0, shape="gear"),

    quest("alloy_mixing", A + 12.5, 16, "&6Legierung vom Band",
          subtitle="Doppelte Ausbeute, null Handarbeit.",
          description=[
              "Im Mixer ergibt ein &6Andesit&r und ein &6Eisen-&r oder &6Zinkklumpen&r eine &6Andesitlegierung&r. Das ist halb so viel Andesit wie in der Werkbank.",
              "",
              "So baust du es: eine Kiste Andesit und eine Kiste Klumpen, je eine &6Andesitschleuse&r daran, die auf ein Förderband zum Becken legen. Der Mixer darüber, eine Schleuse an der Beckenseite, die die Legierung in eine Ausgabekiste fallen lässt.",
              "",
              "&cStockt es?&r Meistens fehlt eine Zutat: halte beide Kisten gefüllt. Oder das Becken ist mit fertiger Legierung voll, weil die Ausgabeschleuse falsch herum sitzt.",
          ],
          tasks=[task_item("create:andesite_alloy", 256)],
          rewards=[reward_item("minecraft:andesite", 64), reward_table("s1_uncommon")],
          deps=["mixer"]),

    quest("saw", A + 10, 19, "&6Mechanische Säge",
          subtitle="Holz und Stein im Takt.",
          description=[
              "Die &6Mechanische Säge&r (Eisenbleche, Eisenbarren, Andesitgehäuse) hat zwei Einsatzarten. Nach oben zeigend verarbeitet sie Items, die auf ihr landen oder auf einem Förderband durch sie hindurch laufen: Stämme werden zu mehr Brettern als in der Werkbank, und sie kann alles, was der Steinschneider kann.",
              "",
              "Gibt es mehrere Ergebnisse, wählst du mit einem &6Listenfilter&r (Eisenklumpen und Wolle) im Filterfeld der Säge, welches sie liefern soll.",
              "",
              "Seitlich an einer Kontraption gesetzt fällt sie ganze Bäume, dazu mehr bei den Kontraptionen. Und nebenbei: aus einer Legierung sägt sie sechs Wellen, das ist sogar ergiebiger als die Werkbank.",
          ],
          tasks=[task_item("create:mechanical_saw", 1)],
          rewards=[reward_item("minecraft:oak_log", 32), reward_xp(3)],
          deps=["sheets"]),

    # ---- Item-Logistik ------------------------------------------------------
    quest("belt", A, 25, "&6Förderband",
          subtitle="Items und Rotation auf einer Spur.",
          description=[
              "Sechs &6getrockneter Seetang&r ergeben ein &6Förderband&r. Seetang trocknest du im Ofen, im Räucherofen oder vor einem Lüfter mit Feuer.",
              img(item_texture("create:belt_connector"), 32, 32),
              "Setz zwei Wellen mit bis zu 20 Blöcken Abstand parallel zueinander, rechtsklicke mit dem Förderband erst die eine, dann die andere. Das Band spannt sich dazwischen, waagerecht oder schräg im 45-Grad-Winkel. Egal wie lang: ein Band kostet ein Förderband-Item.",
              "",
              "Das Band trägt Items, Mobs und Spieler, und es gibt die Rotation von einer Welle an die andere weiter. Über dem Band arbeiten &6Presse&r und &6Säge&r im Vorbeifahren, seitlich wäscht, schmilzt oder räuchert ein &6Lüfter&r.",
              "",
              "&6Tipp:&r Mit einem Andesitgehäuse in der Hand rechtsklickst du ein Band, um es zu ummanteln.",
          ],
          tasks=[task_item("create:belt_connector", 4)],
          rewards=[reward_item("minecraft:dried_kelp_block", 4), reward_xp(3)],
          deps=["press"], icon="create:belt_connector", size=1.75, shape="gear"),

    quest("chute", A + 2.5, 24, "&6Schacht",
          subtitle="Items fallen, wohin sie sollen.",
          description=[
              "Zwei Eisenbleche und ein Eisenbarren ergeben vier &6Schächte&r. Ein Schacht leitet Items senkrecht nach unten, schneller als ein Trichter, und zieht sie aus Kisten, Mahlsteinen oder Becken darüber.",
              "",
              "Mit einem &6Lüfter&r darunter oder darüber schiebst du Items im Schacht sogar nach oben. Setz einen Schacht ans Ende eines Förderbands, und die Items fallen sauber in eine Kiste oder auf ein Depot.",
              "",
              "Für weite Sprünge gibt es den &6Gewichteten Werfer&r (Goldblech, Depot, Zahnrad): er schleudert Items bis zu 32 Blöcke weit auf ein Ziel, das du vor dem Absetzen mit ihm anklickst. Praktisch über Schluchten, und er wirft auch Spieler, wenn du dich traust.",
          ],
          tasks=[task_item("create:chute", 4)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(2)],
          deps=["belt"]),

    quest("funnel", A + 2.5, 26, "&6Andesitschleuse",
          subtitle="Rein ins Band, raus aus der Kiste.",
          description=[
              "Eine Legierung und ein getrockneter Seetang ergeben zwei &6Andesitschleusen&r. Eine Schleuse sitzt an einer Kiste, einem Depot, einem Becken oder am Ende eines Bands. Sie zieht Items aus dem Block, an dem sie hängt, oder schiebt Items hinein, je nachdem, wie herum du sie setzt. Mit dem Schraubenschlüssel polst du sie um.",
              "",
              "Beim Herausziehen nimmt die Andesitschleuse immer ein einzelnes Item auf einmal, und ein &cRedstone-Signal&r hält sie an. Ganze Stapel, Filter und genaue Stückzahlen kann erst die Messingschleuse aus Stufe 2.",
              "",
              "Der &6Andesittunnel&r ist ihr Partner auf dem Band: oben auf ein Förderband gesetzt, zweigt er von durchlaufenden Stapeln einzelne Items auf Bänder oder Schleusen daneben ab. So versorgst du mehrere Maschinen aus einer Zuleitung.",
          ],
          tasks=[task_item("create:andesite_funnel", 4)],
          rewards=[reward_item("minecraft:dried_kelp", 16), reward_xp(2)],
          deps=["belt"]),

    quest("vault", A + 5, 26, "&6Gegenstandstresor",
          subtitle="Viel Platz auf wenig Raum.",
          description=[
              "Ein &6Gegenstandstresor&r (Eisenbleche und ein Fass) fasst &620 Stapel pro Block&r. Setzt du mehrere zusammen, verschmelzen sie zu einem großen Tresor, bis zu drei Blöcke breit und hoch und mehrere Blöcke lang.",
              "",
              "Tresore haben keine Oberfläche zum Öffnen. Du füllst und leerst sie mit Schleusen, Schächten, Förderbändern oder dem Paketsystem. Genau dafür sind sie da: als Puffer zwischen zwei Anlagen oder als großes Lager für eine ganze Produktion.",
          ],
          tasks=[task_item("create:item_vault", 4)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["funnel"]),

    quest("packager", A + 7.5, 25, "&6Verpacker und Karton",
          subtitle="Items verschicken wie per Post.",
          description=[
              "Das Paketsystem von Create beginnt mit &6Karton&r. Vier Zuckerrohr, Bambus oder Setzlinge mit etwas &bWasser&r im Mixer ergeben &6Zellstoff&r, die Presse macht daraus &6Karton&r, vier Karton sind ein &6Kartonblock&r.",
              img(item_texture("create:cardboard"), 32, 32),
              "Der &6Verpacker&r (Kartonblock, Eisenbarren, Redstone) kommt an eine Kiste, ein Fass oder einen Tresor. Bekommt er ein &cRedstone-Signal&r, packt er den Inhalt in ein &6Paket&r. Gibst du ihm umgekehrt ein Paket, packt er es wieder aus, zurück ins Lager.",
              "",
              "Ein &6Schild&r mit einem Namen am Verpacker gibt allen seinen Paketen eine &eAdresse&r. Über Adressen weiß der Rest des Systems, wohin ein Paket soll.",
          ],
          tasks=[task_item("create:cardboard", 8), task_item("create:packager", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["vault", "mixer"], icon="create:packager", size=1.5),

    quest("frogport", A + 10, 24, "&6Kettenförderer und Frosch",
          subtitle="Pakete auf die Reise schicken.",
          description=[
              "Der &6Kettenförderer&r (großes Zahnrad und Andesitgehäuse) sitzt auf einer angetriebenen Welle. Verbinde zwei davon, indem du mit &6Ketten&r in der Hand erst den einen und dann den anderen rechtsklickst. Pakete fahren dann an der Kette entlang, auch über weite Strecken.",
              "",
              "Der &6Frosch-Anschluss für Pakete&r (Tresor, Schleimball, Legierung) setzt Pakete auf die Kette und fängt sie wieder ab. Klick mit ihm in der Hand auf die Kette oder einen Verpacker und setz ihn höchstens 5 Blöcke daneben ab. Gib ihm eine Adresse: er schnappt sich jedes Paket, das dorthin will.",
              "",
              "So entsteht ein kleines Postnetz zwischen deinen Werkstätten, und Nachbarn können sich darüber gegenseitig beliefern.",
          ],
          tasks=[task_item("create:chain_conveyor", 2), task_item("create:package_frogport", 2)],
          rewards=[reward_item("minecraft:chain", 16), reward_xp(3)],
          deps=["packager"]),

    quest("stock", A + 10, 26, "&6Lagernetz und Lagerticker",
          subtitle="Ein Lager, das auf Zuruf liefert.",
          description=[
              "Der &6Sender&r (Kupferbleche, Blitzableiter, Redstone) ist die Funkeinheit. Mit einem Tresor wird daraus eine &6Lagerverbindung&r. Setz sie auf einen Verpacker, und das Lager dahinter gehört zu einem &eLagernetz&r. Weitere Lagerverbindungen stimmst du auf dasselbe Netz ab, indem du mit der neuen eine alte rechtsklickst, bevor du sie setzt.",
              "",
              "Der &6Lagerticker&r (Lagerverbindung, Glas, Goldbarren) ist die Theke. Er gehört ins selbe Netz und neben einen Verkäufer: einen Mob, der auf einem &6Sitz&r (Wolle und Holzstufe) sitzt. Klickst du den Verkäufer an, siehst du alles, was im Netz liegt, und kannst bestellen. Die Verpacker packen deine Bestellung und schicken sie an die Adresse, die du angibst.",
              "",
              "Ein &6Redstone-Anfrager&r (Lagerverbindung, Redstone, Eisen) speichert eine feste Bestellung und löst sie bei jedem Redstone-Impuls aus: Knopf drücken, Fackeln kommen.",
              "",
              "Das alles läuft schon in Stufe 1, ganz ohne Strom.",
          ],
          tasks=[task_item("create:stock_link", 2), task_item("create:stock_ticker", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["packager"], icon="create:stock_ticker", size=1.5),

    quest("shop", A + 12.5, 26, "&6Tischdecken und Läden",
          subtitle="Handel zwischen Spielern, ganz ohne Chat.",
          description=[
              "Eine &6Tischdecke&r (Wolle und Legierung, oder eine Legierung im Steinschneider für die Andesit-Variante) wird zur Ladentheke. Klick mit ihr den Verkäufer an deinem Lagerticker an und stell sie dann auf. Leg darauf, was du verkaufen willst, und stell den Preis darunter ein.",
              "",
              "Andere Spieler wählen am Tisch ihre Ware, bekommen eine &6Einkaufsliste&r und bezahlen beim Verkäufer. Dein Lagernetz packt die Ware und schickt sie los, die Bezahlung landet in deinem Lager.",
              "",
              "Ein Marktplatz am Spawn, auf dem jeder seine Überschüsse anbietet, bringt den ganzen Server schneller voran.",
          ],
          tasks=[task_item("create:andesite_table_cloth", 2)],
          rewards=[reward_item("minecraft:emerald", 4), reward_xp(3)],
          deps=["stock"], optional=True),

    quest("redstone_link", A + 12.5, 24, "&6Redstone-Verbindung",
          subtitle="Kabellos schalten.",
          description=[
              "Ein &6Sender&r auf einem Andesitgehäuse ergibt zwei &6Redstone-Verbindungen&r. Sie funken ein Redstone-Signal bis zu 256 Blöcke weit. Beide bekommen dieselben zwei Items in ihre Frequenzfelder, dann gehören sie zusammen.",
              "",
              "Schleichen und Rechtsklick mit leerer Hand schaltet zwischen Senden und Empfangen um. So steuerst du eine Kupplung am anderen Ende der Basis mit einem Hebel neben der Tür.",
          ],
          tasks=[task_item("create:redstone_link", 2)],
          rewards=[reward_item("minecraft:redstone", 16), reward_xp(2)],
          deps=["stock"], optional=True),

    # ---- Fluide -----------------------------------------------------------
    quest("copper_casing", B, 2.5, "&6Kupferrahmen",
          subtitle="Das Gehäuse für alles Flüssige.",
          description=[
              "Wie beim Andesitgehäuse: rechtsklicke einen gesetzten, entrindeten Stamm mit einem &6Kupferbarren&r. Der &6Kupferrahmen&r steckt in Ausguss, Abfluss, Schlauchrolle und portabler Flüssigkeitsschnittstelle.",
              "",
              "Kupfer ist in dieser Stufe überhaupt wichtig: Rohre, Tanks und Tauchausrüstung schlucken es stapelweise, und in Stufe 2 wird es zur Hälfte jedes Messingbarrens.",
          ],
          tasks=[task_item("create:copper_casing", 4)],
          rewards=[reward_item("minecraft:copper_ingot", 16), reward_xp(2)],
          deps=["sheets"]),

    quest("pipes", B + 2.5, 1.75, "&6Flüssigkeitsrohre",
          subtitle="Wasser dahin, wo du es brauchst.",
          description=[
              "Zwei Kupferbleche und ein Kupferbarren ergeben vier &6Flüssigkeitsrohre&r. Rohre verbinden sich von selbst mit allem, was Flüssigkeiten hält: Tanks, Becken, Ausgüsse und die Maschinen anderer Mods.",
              "",
              "Rohre allein bewegen nichts. Erst eine &6Mechanische Pumpe&r drückt die Flüssigkeit hindurch, bis zu 16 Blöcke weit in jede Richtung.",
              "",
              "Ein offenes Rohrende in Wasser oder Lava saugt die Flüssigkeit aus der Welt. Mit dem Schraubenschlüssel öffnest oder schließt du Rohrenden, und ein &6Flüssigkeitsventil&r (Rohr und Eisenblech) sperrt eine Leitung, sobald du es mit Rotation zudrehst.",
          ],
          tasks=[task_item("create:fluid_pipe", 16)],
          rewards=[reward_item("minecraft:copper_ingot", 8), reward_xp(2)],
          deps=["copper_casing"]),

    quest("pump", B + 5, 2.75, "&6Mechanische Pumpe",
          subtitle="Der Motor im Rohrnetz.",
          description=[
              "Zahnrad und Rohr ergeben die &6Mechanische Pumpe&r. Setz sie in eine Rohrleitung und treib sie an. Der Pfeil zeigt die Förderrichtung; kehrst du die Drehrichtung um, pumpt sie rückwärts.",
              "",
              "Je höher die Drehzahl, desto mehr fließt. Die Pumpe kostet 4 SU pro RPM. Ein offenes Rohrende in einem Gewässer mit Nachfluss liefert &bWasser&r ohne Ende.",
              "",
              "&cHäufiger Fehler:&r Zwei Pumpen in derselben Leitung, die gegeneinander arbeiten. Mit der Ingenieursbrille siehst du die Richtung.",
          ],
          tasks=[task_item("create:mechanical_pump", 1)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["pipes"], icon="create:mechanical_pump", size=1.5),

    quest("tank", B + 7.5, 1.75, "&6Flüssigkeitstank",
          subtitle="Acht Eimer pro Block.",
          description=[
              "Ein &6Flüssigkeitstank&r (Kupferbleche und ein Fass) fasst &b8 Eimer&r pro Block. Über- und nebeneinander gesetzte Tanks verschmelzen zu einem großen, bis zu drei Blöcke breit und viele Blöcke hoch.",
              "",
              "Mit der Ingenieursbrille siehst du Füllstand und Inhalt. Ein Tank ist auch das Herz des &6Dampfkessels&r, der in Stufe 2 mit Lohenbrennern und Dampfmaschinen richtig viel Kraft liefert.",
              "",
              "&6Tipp:&r Die &6Schlauchrolle&r (Kupferrahmen, getrockneter Seetangblock, Kupferblech) saugt Flüssigkeit bis zu 128 Blöcke weit aus der Welt oder füllt ein Gebiet damit. Ein Gewässer mit mehr als 10 000 Blöcken gilt dabei als unendlich und wird nie leerer.",
          ],
          tasks=[task_item("create:fluid_tank", 4)],
          rewards=[reward_table("s1_common"), reward_xp(2)],
          deps=["pump"]),

    quest("spout", B + 7.5, 3.75, "&6Ausguss und Abfluss",
          subtitle="Flüssigkeit in Items hinein und wieder heraus.",
          description=[
              "Der &6Ausguss&r (Kupferrahmen und getrockneter Seetang) sitzt über einem Depot oder Förderband und befüllt, was darunter liegt: Eimer, Flaschen und alle Rezepte der Kategorie &eBefüllen&r in JEI. Er braucht keine Rotation, nur Flüssigkeit per Rohr.",
              "",
              "Der &6Abfluss&r (Kupferrahmen und Eisengitter) ist das Gegenstück: Items, die darauf landen, werden geleert. Ein Wassereimer wird zum leeren Eimer, das Wasser fließt per Rohr in deinen Tank. Andere Items lässt er einfach durch wie ein kurzes Stück Band.",
              "",
              "In Stufe 2 füllt der Ausguss &bLava&r in Lohenkuchen und in die Obsidianbleche für Zugteile.",
          ],
          tasks=[task_item("create:spout", 1), task_item("create:item_drain", 1)],
          rewards=[reward_item("minecraft:glass_bottle", 16), reward_xp(3)],
          deps=["pump"]),

    quest("diving", B + 2.5, 3.75, "&6Tauchausrüstung",
          subtitle="Luft zum Mitnehmen.",
          description=[
              "Der &6Kupfer-Rückentank&r (Kupferblock, Kupferbarren, Legierung, Welle) füllt sich mit Druckluft, wenn du ihn aufstellst und mit Rotation antreibst. Mit &6Kupfer-Tauchhelm&r und &6Kupfer-Tauchstiefeln&r dazu atmest du unter Wasser aus dem Tank und sinkst schnell zum Grund.",
              img(item_texture("create:copper_diving_helmet"), 32, 32),
              "Die Druckluft treibt später auch Werkzeuge an. Der &6Jetpack&r aus dem Addon Create Jetpack baut sogar direkt auf dem Rückentank auf, braucht aber Elytren und kommt deshalb erst mit dem Ende in Stufe 4.",
          ],
          tasks=[task_item("create:copper_backtank", 1), task_item("create:copper_diving_helmet", 1),
                 task_item("create:copper_diving_boots", 1)],
          rewards=[reward_xp(5)],
          deps=["copper_casing"], optional=True),

    # ---- Kontraptionen --------------------------------------------------------
    quest("bearing", B, 9, "&6Mechanisches Lager",
          subtitle="Dreh ganze Bauwerke.",
          description=[
              "Das &6Mechanische Lager&r (Holzstufe, Andesitgehäuse, Welle) dreht die Blöcke an seiner Vorderseite um seine Achse. Rechtsklicke es, und die angehängten Blöcke werden zu einer &eKontraption&r, einem beweglichen Bauwerk.",
              "",
              "Kontraptionen sind das Besondere an Create: Bohrer, Sägen und Erntemaschinen daran arbeiten während der Bewegung. Ein Lager mit Sägen im Kreis ist eine Baumfarm, ein Lager mit Bohrern ein Tunnelbohrer. Bis zu 2 048 Blöcke kann eine Kontraption mitnehmen.",
              "",
              "Nochmal rechtsklicken hält sie an und setzt die Blöcke wieder fest in die Welt.",
          ],
          tasks=[task_item("create:mechanical_bearing", 1)],
          rewards=[reward_xp(3)],
          deps=["gearbox"]),

    quest("glue", B + 2.5, 8, "&6Sekundenkleber",
          subtitle="Was zusammengehört, bleibt zusammen.",
          description=[
              "Eine Kontraption nimmt nur Blöcke mit, die fest an ihr hängen. Mit &6Sekundenkleber&r (Schleimbälle, Eisenblech, Eisenklumpen) ziehst du einen Rahmen um alles, was zusammengehört: Klick auf die eine Ecke, dann auf die gegenüberliegende. Alles darin ist verklebt.",
              img(item_texture("create:super_glue"), 32, 32),
              "Der Block direkt vor einem Lager oder Kolben gehört immer dazu, alles weitere braucht Kleber. Für richtig große Kontraptionen gibt es &6Schub-&r und &6Drehgerüste&r (Stämme und Legierung): eine mit Schleimball bestrichene Seite nimmt alle Blöcke in bis zu 16 Blöcken Reichweite mit.",
          ],
          tasks=[task_item("create:super_glue", 1)],
          rewards=[reward_item("minecraft:slime_ball", 4), reward_xp(2)],
          deps=["bearing"]),

    quest("piston", B + 2.5, 10, "&6Mechanischer Kolben",
          subtitle="Schieben, so weit du willst.",
          description=[
              "Der &6Mechanische Kolben&r (Holzstufe, Andesitgehäuse, Kolbenverlängerungsstange) schiebt Blöcke, solange er Rotation bekommt. Hinter ihm sitzen &6Kolbenverlängerungsstangen&r (Bretter und Legierung, acht Stück), je eine pro Block Hub, bis zu 64.",
              "",
              "Zurück fährt er, wenn sich die Drehrichtung umkehrt, am einfachsten mit einer &6Gangschaltung&r und einem Hebel. Die klebrige Version (Schleimball dazu) nimmt den Block davor auch beim Zurückfahren mit.",
          ],
          tasks=[task_item("create:mechanical_piston", 1), task_item("create:piston_extension_pole", 8)],
          rewards=[reward_xp(3)],
          deps=["bearing"]),

    quest("rope_pulley", B + 5, 8, "&6Flaschenzug",
          subtitle="Rauf und runter.",
          description=[
              "Der &6Flaschenzug&r (Andesitgehäuse, Wolle, Eisenblech) lässt ein Seil bis zu 384 Blöcke tief hinab und hebt oder senkt alles, was unten daran klebt. Ein Lastenaufzug, eine Plattform für den Bergbau oder ein Bohrturm, der sich Schicht für Schicht nach unten frisst.",
              "",
              "Die Drehrichtung bestimmt, ob es hoch oder runter geht. Einen bequemen Personenaufzug mit Stockwerken bekommst du in Stufe 2 mit der Aufzug-Seilrolle aus Messing.",
          ],
          tasks=[task_item("create:rope_pulley", 1)],
          rewards=[reward_xp(3)],
          deps=["glue"]),

    quest("gantry", B + 5, 10, "&6Portalkran",
          subtitle="Fahren entlang einer Schiene.",
          description=[
              "Die &6Portalkranachse&r (Legierung und Redstone) ist die Schiene, der &6Portalkranwagen&r (Holzstufe, Andesitgehäuse, Zahnrad) fährt darauf. Drehst du die Achse, fährt der Wagen mit allem, was an ihm klebt. Achsen am Wagen quer dazu ergeben eine zweite Fahrtrichtung.",
              "",
              "Perfekt für Bohrer, die eine Fläche Schicht für Schicht abtragen, oder für Erntemaschinen, die über ein Feld fahren.",
          ],
          tasks=[task_item("create:gantry_shaft", 8), task_item("create:gantry_carriage", 1)],
          rewards=[reward_xp(3)],
          deps=["piston"], optional=True),

    quest("drill", B + 7.5, 9, "&6Mechanischer Bohrer",
          subtitle="Baut ab, was vor ihm liegt.",
          description=[
              "Der &6Mechanische Bohrer&r (Legierung, Eisenbarren, Andesitgehäuse) baut den Block vor seiner Spitze ab, solange er sich dreht. Die Beute fällt als Item heraus oder landet, an einer Kontraption, in angeklebten Kisten.",
              "",
              "Fest aufgestellt ist er das Herz eines &eBruchsteingenerators&r. An einem Kolben, Lager oder Portalkran wird er zur Tunnelbohrmaschine.",
              "",
              "Er kostet 4 SU pro RPM und bohrt bei höherer Drehzahl deutlich schneller.",
          ],
          tasks=[task_item("create:mechanical_drill", 1)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["glue"], icon="create:mechanical_drill", size=1.5),

    quest("cobble_gen", B + 10, 9, "&6Bruchsteingenerator",
          subtitle="Stein ohne Ende für den Obelisken.",
          description=[
              "Lava und Wasser so nebeneinander, dass zwischen ihnen Bruchstein entsteht, und davor ein &6Mechanischer Bohrer&r: jedes Mal, wenn der Bohrer den Stein abbaut, bildet sich sofort ein neuer. Mehrere Generatoren an einer Welle vervielfachen das.",
              "",
              "Eine Schleuse oder ein Förderband sammelt die Steine ein. Das ist die ehrliche Antwort auf den &6Stein-Pfeiler&r des Obelisk-Ziels: bei 30 Spielern will der Obelisk 40 000 Bruchstein.",
              "",
              "Mit Mahlstein und Kieswäsche dahinter wird aus demselben Bruchstein noch Kies, Feuerstein und Eisenklumpen für deine Legierung.",
              "",
              "&6Tipp:&r Eine Kiste oder ein Fass, das du direkt neben den Obelisken stellst, wird zu deinem &eEinspeiser&r. Der Obelisk holt sich alle zwei Sekunden, was er gebrauchen kann, und schreibt es dir gut. Ein Band vom Generator bis dorthin, und du zahlst im Schlaf ein.",
          ],
          tasks=[task_item("minecraft:cobblestone", 1024)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["drill"], icon="minecraft:cobblestone", size=2.0, shape="gear"),

    quest("harvester", B + 7.5, 11, "&6Erntemaschine und Pflug",
          subtitle="Felder, die sich selbst bestellen.",
          description=[
              "Die &6Mechanische Erntemaschine&r erntet reife Pflanzen, an denen ihre Kontraption vorbeifährt, und lässt sie stehen, damit sie nachwachsen. Der &6Mechanische Pflug&r macht Erde zu Ackerboden und räumt Gras und Kleinkram aus dem Weg.",
              "",
              "Klebe beide an einen Portalkran, einen Kolben oder ein Lager, das langsam über dein Feld fährt. Die Ernte landet in Kisten auf der Kontraption oder fällt zu Boden, wo eine Schleuse sie aufsammelt.",
          ],
          tasks=[task_item("create:mechanical_harvester", 2), task_item("create:mechanical_plough", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 32), reward_xp(3)],
          deps=["drill"], optional=True),

    quest("psi", B + 10, 11.5, "&6Portable Lagerschnittstelle",
          subtitle="Umladen im Vorbeifahren.",
          description=[
              "Eine Kontraption mit angeklebter Kiste sammelt, was ihre Bohrer und Erntemaschinen abbauen. Aber wie kommt es wieder heraus? Mit zwei &6Portablen Lagerschnittstellen&r (Andesitgehäuse und Schacht): eine sitzt auf der Kontraption, eine fest in der Welt.",
              "",
              "Fährt die Kontraption vorbei und die beiden stehen sich mit ein bis zwei Blöcken Abstand gegenüber, hält sie kurz an und tauscht die Items aus. Eine Schleuse an der festen Schnittstelle zieht sie ab.",
              "",
              "Genau so werden in Stufe 2 auch Güterzüge be- und entladen.",
          ],
          tasks=[task_item("create:portable_storage_interface", 2)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["drill"]),

    # ---- Das Ziel -------------------------------------------------------------
    quest("factory", B + 2.5, 17.5, "&6&lDie Andesit-Fabrik",
          subtitle="Das Steinwerk läuft von allein.",
          description=[
              "Zeit, alles zusammenzusetzen. Andesit, abgebaut oder aus Feuerstein verdichtet, und Klumpen aus der Kieswäsche oder aus Zink laufen auf Förderbändern zu einem Mixer, der daraus &6Andesitlegierung&r macht. Wasserräder oder eine Windmühle treiben alles an, eine Schleuse lädt das Ergebnis ab.",
              "",
              "Das Obelisk-Ziel von Stufe 1 will im Technik-Pfeiler &63 000 Andesitlegierungen&r, gerechnet für 30 aktive Spieler; bei mehr oder weniger Spielern passt sich die Zahl beim Öffnen der Stufe an. Von Hand schafft das niemand, mit ein paar laufenden Linien schon.",
              "",
              "&eSo zahlst du ein:&r Halte die Legierung in der Hand und rechtsklicke den Obelisken am Spawn. Schleichen und Rechtsklick gibt alles Passende aus deinem Inventar auf einmal ab. Noch bequemer ist ein &eEinspeiser&r: eine Kiste oder ein Fass, das du selbst direkt neben den Obelisken stellst. Was deine Anlage dort hineinschiebt, zieht der Obelisk alle zwei Sekunden ein und schreibt es dir gut. &e/kw deposit&r geht zur Not auch.",
              "",
              "Mit &e/kw goals&r siehst du, wie weit der Server schon ist.",
          ],
          tasks=[task_item("create:andesite_alloy", 512)],
          rewards=[reward_table("s1_rare"), reward_xp(10)],
          deps=["alloy_mixing", "cobble_gen"], icon="create:andesite_alloy", size=2.5, shape="gear"),

    quest("outlook", B + 6, 17.5, "&6Ausblick: Messingwerk",
          subtitle="Was als Nächstes kommt, und was du jetzt schon tun kannst.",
          description=[
              "Wenn das Obelisk-Ziel voll ist, öffnet sich mit einem Event auf allen Streams &6Stufe 2, das Messingwerk&r, und mit ihr der Nether. Create bekommt dann seine zweite Hälfte: Messing, Einsatzgeräte, mechanische Handwerkseinheiten, Präzisionsgetriebe, Dampfmaschinen und Züge. Die Kapitel &6Create: Messing&r und &6Create: Züge&r warten schon.",
              "",
              "Der Schlüssel zu Messing ist der &6Lohenbrenner&r, denn nur mit Hitze mischt der Mixer Kupfer und Zink zu Messing. Auf Kronwerke braucht sein leeres Gehäuse neben Eisenblechen und Netherrack &dzwei Quelljuwelen&r aus Ars Nouveau. Technik kommt hier nicht ohne Magie aus.",
              "",
              "Was du jetzt schon tun kannst: &6Zink&r und &6Kupfer&r horten, &6Eisenbleche&r vorpressen und dich mit den Magiern des Servers anfreunden. Oder gleich selbst eine &aImbuement-Kammer&r bauen: Quelljuwelen braucht der Obelisk ohnehin für den Magie-Pfeiler dieser Stufe.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("ars_nouveau:source_gem", 2), reward_xp(5)],
          deps=["factory"], icon="create:zinc_ingot", shape="diamond"),
]

images = [
    head("title", "Create", A + 7, -3, height=1.8, kind="title"),
    head("stage", "Stufe 1: Steinwerk", A + 7.2, -1.7, height=0.55, kind="note", colour="stone"),
    head("basics", "Grundlagen", A - 0.6, 0.2),
    head("power", "Energie", A - 0.6, 6.8),
    head("processing", "Verarbeitung", A - 0.6, 13.3),
    head("logistics", "Item-Logistik", A - 0.6, 22),
    head("fluids", "Fluide", B - 0.6, 0.2),
    head("contraptions", "Kontraptionen", B - 0.6, 6.5),
    head("goal", "Das Ziel", B - 0.6, 14.8),
]
# centre the title over the whole canvas
images[0]["x"] = 13.5
images[1]["x"] = 13.5

chapter(C, "Create", "create:large_cogwheel", "tech", quests, shape="gear", order=1,
        subtitle=["Rotation, Förderbänder und die ersten Maschinen des Steinwerks."], images=images)
