"""Just Dire Things in stage 2: Primogel and Blazebloom goo, ferricore and blazegold, the coal
tiers, the tools with their smithing table upgrades and the key bindings, ferricore armor, the
blazegold template, the simple machines (generator, breaker, placer, dropper, sensor, clicker,
item collector, fuel generator, swapper), the pocket generator and the portal gun. Numbers come
from the mod's recipes, loot tables, data maps and justdirethings-server.toml. Celestigem is
stage 3, eclipse alloy, time crystals, the paradox machine and the portal gun V2 are stage 4 and
are only mentioned. The mod has no German lang file, so item names stay English."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "dire_things"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Das Goo ----------------------------------------------------------------
    quest("goo", 0, 0, "&a&lMisch das erste Goo",
          subtitle="Ein lebender Block, der Eisen in Ferricore verwandelt.",
          description=[
              "&eRezept:&r vier &6Tonklumpen&r in die Ecken, oben und unten je ein &6Zucker&r, links und rechts je ein &6Verrottetes Fleisch&r, &6Erde&r in die Mitte. Das ergibt einen Block &6Primogel Goo&r.",
              "",
              "&aJust Dire Things&r dreht sich um dieses Goo. Es frisst Blöcke, die du daneben stellst, und lässt etwas Besseres zurück: aus Eisen wird &6Ferricore&r, aus Gold &6Blazegold&r. Daraus baust du Werkzeuge mit Fähigkeiten, einfache Maschinen ohne Strom und eine Portalkanone.",
              "",
              "Frisch gesetzt ist das Goo noch tot und grau. &eRechtsklick mit Zucker oder Verrottetem Fleisch&r weckt es auf, dann wabert es sichtbar.",
              "",
              "&eTipp:&r Ein Goo-Block und ein Buch ergeben an der Werkbank das Handbuch des Mods, mit jedem Rezept und jeder Fähigkeit.",
              "",
              "&eWas in Stufe 2 offen ist:&r Primogel und Blazebloom Goo, Ferricore und Blazegold, alle einfachen Maschinen, der Taschengenerator und die Portalkanone. &cCelestigem kommt in Stufe 3, Eclipse Alloy und die Zeitkristalle in Stufe 4.&r",
          ],
          tasks=[task_item("justdirethings:gooblock_tier1", 1)],
          rewards=[reward_item("minecraft:sugar", 16), reward_table("s2_common")],
          icon="justdirethings:gooblock_tier1", size=2.0, shape="hexagon"),

    quest("ferricore_raw", 2.5, -1, "&7Füttere das Goo mit Eisen",
          subtitle="Ein Eisenblock wird zu Raw Ferricore.",
          description=[
              "Stell einen &6Eisenblock&r direkt neben das aktive Goo. Nach &e2 Minuten&r ist er ein &6Raw Ferricore Block&r. Abbauen, und du bekommst &63 bis 4 Raw Ferricore&r.",
              "",
              "Neun Eisen für drei bis vier Ferricore klingt teuer, aber das Goo arbeitet an allen sechs Seiten gleichzeitig, und du musst nur Blöcke setzen und abbauen. Behutsamkeit gibt den ganzen Block zurück, Glück bringt nichts extra.",
              "",
              "Nach jedem fertigen Block stirbt das Goo mit &e10 Prozent&r Wahrscheinlichkeit. Dann ist es wieder grau und will Zucker oder Verrottetes Fleisch. Was es gerade umwandelt, bringt es trotzdem zu Ende.",
          ],
          tasks=[task_item("justdirethings:raw_ferricore", 8)],
          rewards=[reward_item("minecraft:iron_ingot", 32), reward_xp(3)],
          deps=["goo"], icon="justdirethings:raw_ferricore"),

    quest("ferricore_ingot", 5, -1, "&7Schmilz Ferricore",
          subtitle="Das Metall für alles in diesem Kapitel.",
          description=[
              "&6Raw Ferricore&r im Ofen oder Schmelzofen ergibt einen &6Ferricore Ingot&r, 10 Sekunden im Ofen, 5 im Schmelzofen. Neun Barren ergeben einen Block und zurück.",
              "",
              "Ferricore steckt in jedem Werkzeug, jeder Rüstung, jedem Upgrade und jeder einfachen Maschine des Mods. Für den Anfang reichen 32 Barren: eine Spitzhacke, vier leere Upgrades und ein Generator.",
              "",
              pic("justdirethings:ferricore_ingot"),
          ],
          tasks=[task_item("justdirethings:ferricore_ingot", 16)],
          rewards=[reward_item("justdirethings:ferricore_ingot", 8), reward_table("s2_common")],
          deps=["ferricore_raw"], icon="justdirethings:ferricore_ingot"),

    quest("primal_coal", 2.5, 1, "&8Mach Primal Coal",
          subtitle="Kohle, die dreimal so lange brennt.",
          description=[
              "Stell einen &6Kohleblock&r oder einen Block aus neun Holzkohle neben das Goo. Nach 2 Minuten ist er ein &6Raw Primal Coal&r Block und gibt beim Abbau &63 bis 4 Primal Coal&r.",
              "",
              "Ein Stück &6Primal Coal&r brennt &e4 800 Ticks&r, dreimal so lange wie Kohle (1 600), und zwar in jedem Ofen. Im Generator und im Taschengenerator zählt es außerdem doppelt: schnellerer Brand, mehr FE pro Tick.",
              "",
              "Neun Stück ergeben einen &6Primal Coal Block&r mit 48 000 Ticks. Den brauchst du für die nächste Kohlestufe.",
          ],
          tasks=[task_item("justdirethings:coal_t1", 8)],
          rewards=[reward_item("minecraft:coal_block", 4), reward_xp(3)],
          deps=["goo"], icon="justdirethings:coal_t1"),

    quest("goo2", 5, 1, "&6Mach Blazebloom Goo",
          subtitle="Das Goo lernt den Nether.",
          description=[
              "&eRezept:&r ein &6Primogel Goo&r in die Mitte, vier &6Lohenstaub&r in die Ecken, oben und unten &6Redstone&r, links und rechts &6Netherwarze&r.",
              "",
              "&6Blazebloom Goo&r kann alles, was Primogel kann, nur schneller, und dazu Goldblöcke und Primal Coal Blöcke verwandeln. Geweckt wird es mit &6Netherwarze&r oder &6Lohenstaub&r, Zucker reicht hier nicht mehr.",
              "",
              "&eTipp:&r Bau dir mehrere Goo-Blöcke. Jeder arbeitet an sechs Seiten, und ein Dutzend in einer Reihe ist schon eine kleine Fabrik.",
          ],
          tasks=[task_item("justdirethings:gooblock_tier2", 1)],
          rewards=[reward_item("minecraft:blaze_powder", 8), reward_table("s2_common"), reward_xp(5)],
          deps=["primal_coal"], icon="justdirethings:gooblock_tier2"),

    quest("blazegold", 7.5, 1, "&6&lMach Blazegold",
          subtitle="Ein Metall, das sich in Lava repariert.",
          description=[
              "Stell einen &6Goldblock&r neben aktives &6Blazebloom Goo&r. Nach 2 Minuten ist er ein &6Raw Blazegold Block&r, der &63 bis 4 Raw Blazegold&r abwirft. Schmilz es zu &6Blazegold Ingots&r.",
              "",
              pic("justdirethings:blazegold_ingot"),
              "",
              "Blazegold ist die zweite Werkzeugstufe: Blöcke wie Diamant, &e1 440&r Haltbarkeit, Abbaugeschwindigkeit 12. Und es hat &eLava Repair&r: Wirf ein beschädigtes Blazegold-Werkzeug in eine Lavaquelle, und es kommt voll repariert wieder heraus.",
              "",
              "Aus Blazegold baust du den Brennstoffgenerator, den Tauscher, die Portalkanone und ein paar Helfer wie den Blazejet Wand und das Totem of Death Recall.",
          ],
          tasks=[task_item("justdirethings:blazegold_ingot", 8)],
          rewards=[reward_item("minecraft:gold_ingot", 16), reward_table("s2_uncommon"), reward_xp(5)],
          deps=["goo2"], icon="justdirethings:blazegold_ingot", size=1.5, shape="hexagon"),

    quest("blaze_ember", 7.5, 2.75, "&cMach Blaze Ember",
          subtitle="Die zweite Kohlestufe.",
          description=[
              "Stell einen &6Primal Coal Block&r (neun Primal Coal) neben Blazebloom Goo. Nach 2 Minuten wirft der fertige Block &63 bis 4 Blaze Ember&r ab.",
              "",
              "&6Blaze Ember&r brennt &e14 400 Ticks&r, neunmal so lange wie Kohle, und zählt in den Generatoren vierfach. Ein Stück liefert im einfachen Generator &e216 000 FE&r. Außerdem ist es der Rohstoff für den flüssigen Brennstoff des Brennstoffgenerators.",
          ],
          tasks=[task_item("justdirethings:coal_t2", 4)],
          rewards=[reward_item("justdirethings:coal_t1", 16)],
          deps=["goo2", "primal_coal"], icon="justdirethings:coal_t2", optional=True),

    # ---- Werkzeug und Upgrades ------------------------------------------------
    quest("pickaxe", 10.5, -1, "&7Schmiede eine Ferricore-Spitzhacke",
          subtitle="Besser als Eisen, und bereit für Upgrades.",
          description=[
              "Drei &6Ferricore Ingots&r oben, zwei Stöcke darunter, wie jede Spitzhacke. Axt, Schaufel, Hacke, Schwert und Bogen gehen genauso.",
              "",
              "Ferricore-Werkzeug hält &e500&r Schläge (Eisen 250), baut mit Geschwindigkeit 7 statt 6 und schafft dieselben Blöcke wie Eisen, also kein Obsidian. Verzaubern lässt es sich einen Hauch besser als Eisen.",
              "",
              "Das Besondere kommt mit den &6Upgrades&r im nächsten Schritt: Erzadern auf einen Schlag, Erzsuche, Baumfällen und mehr. Halt &eShift&r über dem Werkzeug, dann zeigt der Tooltip, welche Upgrades hineinpassen.",
          ],
          tasks=[task_item("justdirethings:ferricore_pickaxe", 1)],
          rewards=[reward_item("justdirethings:ferricore_ingot", 6), reward_xp(3)],
          deps=["ferricore_ingot"]),

    quest("upgrade_blank", 13, -1, "&eMach leere Upgrades",
          subtitle="Der Rohling für jede Fähigkeit.",
          description=[
              "Vier &6Ferricore Ingots&r in Rautenform (oben, unten, links, rechts) ergeben ein &6Blank Upgrade&r. Jede Fähigkeit braucht einen Rohling plus zwei bis vier passende Zutaten.",
              "",
              "Eingebaut wird am &6Schmiedetisch&r: Werkzeug in den mittleren Slot, Upgrade rechts daneben, der Vorlagen-Slot bleibt leer. Das Upgrade wird verbraucht und sitzt danach fest im Werkzeug.",
              "",
              "Mach gleich vier: zwei für die Spitzhacke, je eines für Axt und Schwert.",
          ],
          tasks=[task_item("justdirethings:upgrade_blank", 4)],
          rewards=[reward_item("justdirethings:ferricore_ingot", 8)],
          deps=["pickaxe"], icon="justdirethings:upgrade_blank"),

    quest("oreminer", 15.5, -3, "&bBau den Ore Miner ein",
          subtitle="Eine Ader auf einen Schlag.",
          description=[
              "Zwei &6Eisenspitzhacken&r links und rechts von einem &6Blank Upgrade&r ergeben das &6Ore Miner&r Upgrade. Am Schmiedetisch in die Ferricore-Spitzhacke.",
              "",
              "&eOre Miner&r ist passiv: Baust du ein Erz ab, bricht die Spitzhacke alle zusammenhängenden Erze der Ader gleich mit, bis zu &e64 Blöcke&r mit Ferricore, 128 mit Blazegold. Jeder Block kostet normal Haltbarkeit.",
              "",
              "Eine Osmiumader im Gebirge liegt damit nach einem Schlag im Inventar. Ausschalten geht jederzeit mit einem Klick auf das Symbol in den Tool Settings.",
          ],
          tasks=[task_item("justdirethings:upgrade_oreminer", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 12), reward_xp(5)],
          deps=["upgrade_blank"], icon="justdirethings:upgrade_oreminer"),

    quest("orescanner", 15.5, -1.5, "&bBau den Ore Scanner ein",
          subtitle="Erze durch die Wand sehen.",
          description=[
              "Zwei &6Amethystscherben&r links und rechts, &6Redstone&r oben und unten um ein &6Blank Upgrade&r ergeben den &6Ore Scanner&r.",
              "",
              "Das ist eine aktive Fähigkeit: Auslösen, und alle Erze in der Nähe leuchten ein paar Sekunden als Partikel durch den Stein hindurch. Welches Erz es ist, siehst du nicht, aber wo du graben musst.",
              "",
              "Womit du sie auslöst, Rechtsklick, Linksklick oder eine eigene Taste, legst du im nächsten Schritt fest.",
          ],
          tasks=[task_item("justdirethings:upgrade_orescanner", 1)],
          rewards=[reward_item("minecraft:amethyst_shard", 8), reward_xp(3)],
          deps=["upgrade_blank"], icon="justdirethings:upgrade_orescanner"),

    quest("keys", 18, -2.25, "&eLeg die Tasten fest",
          subtitle="Shift-Rechtsklick, V und eigene Tasten.",
          description=[
              "&eShift + Rechtsklick&r mit dem Werkzeug in der Hand öffnet die &6Tool Settings&r. Dort steht jede eingebaute Fähigkeit als Symbol: &eLinksklick&r schaltet sie an oder aus, &eRechtsklick&r öffnet ihre Einstellungen.",
              "",
              "In den Einstellungen wählst du, womit eine aktive Fähigkeit auslöst: Rechtsklick, Linksklick oder eine eigene Taste (&eSet Binding&r). Bei passiven Fähigkeiten schaltet die Taste sie um. Mit &eActivate from Inventory&r geht das sogar, wenn das Werkzeug nur im Inventar liegt.",
              "",
              "&eV&r schaltet alle Fähigkeiten des Werkzeugs in der Hand auf einmal aus und wieder an. Eine Taste zum Öffnen der Tool Settings ist ab Werk nicht belegt, du findest sie in den Steuerungsoptionen unter Just Dire Things.",
              "",
              "Rüstung hat kein eigenes Fenster: Öffne die Tool Settings irgendeines Werkzeugs und klick dort auf das Rüstungsteil.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(5)],
          deps=["oreminer", "orescanner"], icon="justdirethings:ferricore_pickaxe"),

    quest("axe", 15.5, 0, "&2Fäll Bäume mit einem Schlag",
          subtitle="Ferricore-Axt mit Tree Feller.",
          description=[
              "Zwei &6Ferricore Ingots&r und zwei Stöcke ergeben die &6Ferricore Axe&r. Das &6Tree Feller&r Upgrade sind zwei &6Diamantäxte&r links und rechts von einem Blank Upgrade.",
              "",
              "Tree Feller ist passiv: Ein Stamm abgebaut, und alle verbundenen Stämme fallen mit, bis zu 64 Blöcke. Der Schlag dauert dafür etwas länger als bei einem einzelnen Block.",
              "",
              "Dazu passt &6Leaf Breaker&r (zwei Laubblöcke um einen Rohling): Rechtsklick auf Laub, und alles verbundene Laub ist weg.",
          ],
          tasks=[task_item("justdirethings:ferricore_axe", 1), task_item("justdirethings:upgrade_treefeller", 1)],
          rewards=[reward_item("minecraft:diamond", 2), reward_item("minecraft:oak_log", 32), reward_xp(3)],
          deps=["upgrade_blank"], icon="justdirethings:ferricore_axe"),

    quest("shovel", 15.5, 1.5, "&eGrab ohne fallenden Kies",
          subtitle="Schaufel und Hacke aus Ferricore.",
          description=[
              "Ein &6Ferricore Ingot&r auf zwei Stöcken ergibt die &6Ferricore Shovel&r. &6Sky Sweeper&r (zwei Kies links und rechts, Sand oben und unten um einen Rohling) baut mit dem Kies oder Sand gleich die ganze Säule darüber ab.",
              "",
              "&6Lawn Mower&r (zwei Grasbüschel um einen Rohling) ist aktiv: auslösen, und alles Gras und alle Blumen in der Nähe fallen als Items zu Boden.",
              "",
              "Die &6Ferricore Hoe&r (zwei Barren, zwei Stöcke) macht aus Erde &6Primogel Soil&r: Ackerland, das niemand zertrampelt und auf dem Pflanzen ein wenig schneller wachsen. Die Blazegold-Hacke macht &6Blazebloom Soil&r, das reife Pflanzen von selbst erntet.",
          ],
          tasks=[task_item("justdirethings:ferricore_shovel", 1)],
          rewards=[reward_item("justdirethings:ferricore_ingot", 4), reward_xp(3)],
          deps=["upgrade_blank"], icon="justdirethings:ferricore_shovel"),

    quest("sword_bow", 15.5, 3, "&cSpür Monster auf",
          subtitle="Schwert mit Mob Scanner, Bogen mit Trankkanister.",
          description=[
              "Zwei &6Ferricore Ingots&r über einem Stock ergeben das &6Ferricore Sword&r, einen halben Punkt härter als Eisen. Das &6Mob Scanner&r Upgrade sind zwei &6Amethystscherben&r und zwei &6Spinnenaugen&r um einen Rohling.",
              "",
              "Mob Scanner ist aktiv: auslösen, und alle Monster in der Nähe leuchten durch Wände. Gut vor dem Abstieg in eine Höhle oder beim Suchen des letzten Mobs im Keller.",
              "",
              "Der &6Ferricore Bow&r (drei Fäden, drei Barren) hat in den Tool Settings einen Slot für einen &6Potion Canister&r (vier Barren um eine Glasflasche). Füll den Kanister mit Tränken, bau das &6Potion Arrow&r Upgrade ein (zwei Glasflaschen, vier Netherwarzen um einen Rohling), und jeder Pfeil trägt den Trankeffekt.",
          ],
          tasks=[task_item("justdirethings:ferricore_sword", 1), task_item("justdirethings:upgrade_mobscanner", 1)],
          rewards=[reward_item("minecraft:arrow", 32), reward_xp(3)],
          deps=["upgrade_blank"], icon="justdirethings:ferricore_sword"),

    quest("armor", 15.5, 4.5, "&7Schmiede Ferricore-Rüstung",
          subtitle="Schneller laufen, höher springen, Blöcke hochsteigen.",
          description=[
              "Ferricore-Rüstung craftest du wie Eisenrüstung aus 5, 8, 7 und 4 &6Ferricore Ingots&r. Sie schützt ein wenig besser als Eisen und nimmt Upgrades am Schmiedetisch, genau wie die Werkzeuge.",
              "",
              "&eStiefel:&r &6Step Assist&r (vier Leitern um einen Rohling) steigt ganze Blöcke ohne Sprung hoch, &6Jump Boost&r (zwei Kolben) springt höher. &eHose:&r &6Walk Speed&r (zwei Zucker, zwei Karotten) und &6Run Speed&r (zwei Zucker, zwei Kartoffeln).",
              "",
              "&eBrust:&r &6Invulnerability&r (zwei Diamantbrustpanzer, zwei Schilde) macht dich per Taste ein paar Sekunden unverwundbar, danach lange Abklingzeit und etwas Haltbarkeit. &eHelm:&r &6Mind Fog&r (zwei Fermentierte Spinnenaugen, zwei Lapis), Monster bemerken dich erst später.",
              "",
              "Höhere Rüstungsstufen erlauben mehr Tempo und höhere Sprünge, mit Schieberegler in den Einstellungen.",
          ],
          tasks=[task_item("justdirethings:ferricore_boots", 1), task_item("justdirethings:upgrade_stepheight", 1)],
          rewards=[reward_item("justdirethings:ferricore_ingot", 8), reward_table("s2_common"), reward_xp(5)],
          deps=["upgrade_blank"], icon="justdirethings:ferricore_chestplate"),

    quest("template", 18, 3.75, "&6&lSteig auf Blazegold um",
          subtitle="Werkzeug aufrüsten, Upgrades behalten.",
          description=[
              "Fünf &6Blazegold Ingots&r um ein &6Blank Upgrade&r (beide oberen Ecken, links und rechts daneben, unten Mitte) ergeben die &6Blazegold Upgrade Template&r. Eine Vorlage und zwei Blazegold-Barren ergeben zwei Vorlagen.",
              "",
              pic("justdirethings:template_blazegold"),
              "",
              "Am &6Schmiedetisch&r: Vorlage links, Ferricore-Werkzeug oder -Rüstung in die Mitte, ein &6Blazegold Ingot&r rechts. Heraus kommt das Blazegold-Stück &emit allen eingebauten Upgrades&r.",
              "",
              "Blazegold öffnet neue Upgrades: &6Hammer&r (zwei Diamantspitzhacken) baut 3x3, &6Auto Smelter&r (zwei Schmelzöfen, zwei Lohenruten) schmilzt Erze beim Abbau, &6Auto Smoker&r (zwei Räucheröfen, zwei Lohenruten) brät Mob-Drops. Beide kosten etwas Haltbarkeit.",
              "",
              "Für die Rüstung: &6Cauterize Wounds&r heilt per Rechtsklick, &6Extinguish&r löscht dich, &6Ground Stomp&r stößt Gegner weg, &6Stupefy&r lässt sie dich vergessen, &6Swim Speed&r schwimmt schneller. Der Bogen bekommt &6Splash&r für Trankwolken beim Aufprall.",
          ],
          tasks=[task_item("justdirethings:template_blazegold", 1), task_item("justdirethings:blazegold_pickaxe", 1)],
          rewards=[reward_item("justdirethings:blazegold_ingot", 4), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["sword_bow", "armor"], icon="justdirethings:template_blazegold", size=1.5, shape="diamond"),

    # ---- Maschinen --------------------------------------------------------------
    quest("generator", 0, 7.5, "&6&lBau den einfachen Generator",
          subtitle="Strom aus Kohle, 1 000 FE pro Tick.",
          description=[
              "&eRezept auf Kronwerke:&r vier &6Ferricore Ingots&r in die Ecken, ein &6Einfacher Steuerschaltkreis&r von Mekanism in die Mitte, &6Kohle&r links und rechts, &6Redstone&r oben und unten.",
              "",
              "Der &6Simple Coal Generator&r frisst alles, was im Ofen brennt, und macht &e15 FE pro Brenntick&r, viermal so schnell wie ein Ofen. Eine Kohle gibt &e24 000 FE&r in 20 Sekunden (60 FE/t), ein &6Primal Coal&r 72 000 FE bei 120 FE/t, ein &6Blaze Ember&r 216 000 FE bei 240 FE/t.",
              "",
              "Er speichert bis zu 1 Million FE und gibt an alle Nachbarn bis zu &e1 000 FE/t&r ab. Ein Universalkabel von Mekanism oder ein Energierohr von Pipez holt den Strom ab.",
              "",
              "&eKronwerke:&r Eine Mekanism-Grundmaschine braucht etwa 20 FE/t. Ein Generator mit Primal Coal versorgt also Anreicherungskammer und Schmelzer zusammen, mit viel weniger Nachlegen als der Wärmegenerator.",
          ],
          tasks=[task_item("justdirethings:generatort1", 1)],
          rewards=[reward_item("justdirethings:coal_t1", 16), reward_table("s2_common"), reward_xp(5)],
          deps=["ferricore_ingot"], icon="justdirethings:generatort1", size=1.5, shape="hexagon"),

    quest("pocket_gen", 2.5, 10, "&eBau den Taschengenerator",
          subtitle="Ein Kraftwerk im Inventar.",
          description=[
              "&eRezept:&r vier &6Ferricore Ingots&r in die Ecken, ein &6Ofen&r in die Mitte, &6Kohle&r links und rechts, &6Redstoneblöcke&r oben und unten.",
              "",
              pic("justdirethings:pocket_generator"),
              "",
              "Rechtsklick öffnet den &6Pocket Generator&r. Leg Kohle, Primal Coal oder Blaze Ember hinein (gleiche Werte wie beim großen Generator), und er lädt alles in deinem Inventar, was FE speichert, mit bis zu &e5 000 FE/t&r. Er selbst fasst 1 Million FE.",
              "",
              "Das ist die Stromquelle für die Portalkanone, aber genauso für ein Energietablett von Mekanism oder jeden anderen Gegenstand, der FE speichert.",
              "",
              "&eTipp:&r Der &6Fuel Canister&r (vier Barren um eine Kohle) schluckt bis zu 10 Millionen Brennticks, alles außer Lavaeimern, und passt in Öfen, Generator und Taschengenerator. Ein Ofen zieht daraus nur, was er braucht, statt eine ganze Kohle für ein Erz zu verheizen. Zurück bekommst du den Brennstoff nicht.",
          ],
          tasks=[task_item("justdirethings:pocket_generator", 1)],
          rewards=[reward_item("justdirethings:coal_t1", 16), reward_xp(5)],
          deps=["generator"], icon="justdirethings:pocket_generator"),

    quest("breaker", 2.5, 7.5, "&7Bau den Blockbrecher",
          subtitle="Deine erste Maschine, ganz ohne Strom.",
          description=[
              "&eRezept:&r vier &6Ferricore Ingots&r in die Ecken, ein &6Beobachter&r in die Mitte, ein &6Diamant&r oben, &6Redstone&r unten, &6Lapis&r links und rechts.",
              "",
              "Der &6Simple Block Breaker&r baut den Block direkt vor sich ab, aber nur mit einem &eWerkzeug im Slot&r. Das Werkzeug verliert Haltbarkeit wie in deiner Hand. Eine Ferricore-Spitzhacke mit Ore Miner bricht so ganze Adern.",
              "",
              "&eSo liest du jede einfache Maschine:&r Der &6Redstone&r-Knopf steht auf Ignoriert (läuft immer), Niedrig (läuft ohne Signal), Hoch (läuft mit Signal) oder Puls (eine Aktion pro Puls). &6Speed (ticks)&r sagt, wie oft sie arbeitet: 20 ist einmal pro Sekunde, 1 ist jeden Tick und macht Lag.",
              "",
              "Einfache Maschinen brauchen keinen Strom und treffen nur den Block vor sich. Die &cfortgeschrittenen&r Versionen mit Bereich und Filter brauchen Celestigem und kommen in &6Stufe 3&r.",
          ],
          tasks=[task_item("justdirethings:blockbreakert1", 1)],
          rewards=[reward_item("justdirethings:ferricore_ingot", 4), reward_table("s2_common")],
          deps=["ferricore_ingot"], icon="justdirethings:blockbreakert1"),

    quest("placer", 5, 7.5, "&7Bau den Blocksetzer",
          subtitle="Brecher und Setzer, das Paar für jede Straße.",
          description=[
              "&eRezept:&r wie der Brecher, nur mit einem &6Werfer&r (Dispenser) statt des Beobachters in der Mitte.",
              "",
              "Der &6Simple Block Placer&r setzt den Block aus seinem Inventar vor sich hin. Mit dem Richtungsknopf legst du fest, wie herum er ihn setzt, zum Beispiel Fackeln an eine Wand.",
              "",
              "&eSo beginnt eine Goo-Straße:&r Der Setzer stellt Eisenblöcke neben das Goo, ein Trichter füllt ihn nach, und ein Brecher auf Redstone Hoch wartet auf den fertigen Raw Ferricore Block. Wer ihm das Signal gibt, steht beim Sensor.",
          ],
          tasks=[task_item("justdirethings:blockplacert1", 1)],
          rewards=[reward_item("minecraft:iron_block", 2), reward_xp(3)],
          deps=["breaker"], icon="justdirethings:blockplacert1"),

    quest("dropper", 7.5, 7.5, "&7Bau den Spender",
          subtitle="Items in die Welt werfen, auch in Stapeln.",
          description=[
              "&eRezept:&r vier &6Ferricore Ingots&r in die Ecken, ein &6Spender&r (Dropper) in die Mitte, &6Redstone&r oben und unten, &6Lapis&r links und rechts.",
              "",
              "Der &6Simple Dropper&r wirft Items aus seinem Inventar in die Richtung, die du einstellst, standardmäßig nach unten. Der Zahlenknopf legt fest, wie viele auf einmal fliegen (1 bis 64), der &ePickup Delay&r, wie lange niemand sie aufheben kann.",
              "",
              "&eKronwerke:&r Ein Spender über einem &6Manabecken&r wirft Enderperlen hinein, und das Becken macht &6Manaperlen&r daraus, eines der Obelisk-Ziele dieser Stufe. In Stufe 3 füttert er genauso das Elfenportal.",
          ],
          tasks=[task_item("justdirethings:droppert1", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 4), reward_xp(3)],
          deps=["placer"], icon="justdirethings:droppert1"),

    quest("sensor", 10, 7.5, "&cBau den Sensor",
          subtitle="Redstone, sobald etwas da ist.",
          description=[
              "&eRezept:&r vier &6Ferricore Ingots&r in die Ecken, ein &6Beobachter&r in die Mitte, ein &6Enderauge&r oben, &6Redstone&r unten, &6Lapis&r links und rechts.",
              "",
              "Der &6Simple Sensor&r prüft den Block vor sich und gibt ein Redstone-Signal, wenn seine Bedingung passt. Der Ziel-Knopf wechselt zwischen Blöcken, Luft, Monstern, Tieren, Erwachsenen, Kindern, Spielern, allen Lebewesen und Items. Ein Filterslot grenzt ein, auf &eAllow List&r stellen, wenn du einen bestimmten Block suchst.",
              "",
              "&eFür die Goo-Straße:&r Leg einen &6Raw Ferricore Block&r in den Filter, stell auf Allow List und richte den Sensor auf den Block neben dem Goo. Sobald er fertig ist, schaltet der Sensor den Brecher ein. Rechtsklick auf den Filterslot filtert sogar nach Blockzustand, etwa Tür offen oder zu.",
          ],
          tasks=[task_item("justdirethings:sensort1", 1)],
          rewards=[reward_item("minecraft:redstone", 32), reward_xp(5)],
          deps=["dropper"], icon="justdirethings:sensort1"),

    quest("clicker", 12.5, 7.5, "&cBau den Klicker",
          subtitle="Rechtsklick, Linksklick, Festhalten, automatisch.",
          description=[
              "&eRezept:&r vier &6Ferricore Ingots&r in die Ecken, ein &6Werfer&r in die Mitte, ein &6Enderauge&r oben, &6Redstone&r unten, &6Lapis&r links und rechts.",
              "",
              "Der &6Simple Clicker&r klickt wie ein Spieler auf das, was vor ihm ist, mit dem Item aus seinem Slot oder mit leerer Hand. Knöpfe für Rechts-, Links- oder Halteklick, Schleichen, Ziel (Block, Luft, Monster, Tiere, Erwachsene, Kinder, Spieler) und Richtung. &eShow Fake Player&r zeigt, wohin er klickt.",
              "",
              "&eFür die Goo-Straße:&r Ein Klicker mit &6Zucker&r im Slot, Ziel Block, auf das Goo gerichtet, weckt es wieder auf, wenn es stirbt. Mit einer Schere schert er Schafe, mit einem Schwert schlägt er Mobs aus einem Spawner tot.",
          ],
          tasks=[task_item("justdirethings:clickert1", 1)],
          rewards=[reward_item("minecraft:sugar", 32), reward_xp(5)],
          deps=["sensor"], icon="justdirethings:clickert1"),

    quest("collector", 15, 7.5, "&aBau den Item Collector",
          subtitle="Saugt alles auf, was herumliegt.",
          description=[
              "&eRezept:&r drei &6Ferricore Ingots&r unten, zwei &6Trichter&r links und rechts von einer &6Enderperle&r, ein &6Diamant&r oben.",
              "",
              "Der &6Item Collector&r ist die einzige Ferricore-Maschine mit Bereich: Alles, was in seinem Bereich auf dem Boden liegt, saugt er ein und legt es in das Inventar, an dem er hängt. &eRender Area&r zeigt den Bereich, &eRAD&r vergrößert ihn, &eOFF&r verschiebt ihn. Filterslots mit Allow oder Deny List bestimmen, was er nimmt.",
              "",
              "Er gehört ans Ende jeder Goo-Straße, unter den Lawn Mower, neben die Blazebloom-Hacke, die ihre Ernte auf den Boden wirft, oder an einen Mob-Spawner.",
          ],
          tasks=[task_item("justdirethings:itemcollector", 1)],
          rewards=[reward_item("minecraft:hopper", 4), reward_table("s2_uncommon"), reward_xp(5)],
          deps=["clicker"], icon="justdirethings:itemcollector"),

    quest("fluid_gen", 0, 10, "&cBau den Brennstoffgenerator",
          subtitle="Flüssiger Brennstoff, 5 000 FE pro Tick.",
          description=[
              "&eRezept:&r vier &6Blazegold Ingots&r in die Ecken, ein &6Schmelzofen&r in die Mitte, zwei &6Eimer&r links und rechts, &6Redstone&r oben und unten.",
              "",
              "&eSo kommst du an Brennstoff:&r &e1.&r Ein &6Blazegold Ingot&r und eine &6Netherwarze&r ergeben vier &6Polymorphic Catalyst&r. Einen in eine Wasserquelle werfen: &6Polymorphic Fluid&r. &e2.&r Ein &6Blaze Ember&r hinterher: &6Unrefined Blaze Ember Fuel&r. &e3.&r Den Flüssigkeitsblock neben &6Blazebloom Goo&r stehen lassen, nach 2 Minuten ist er &6Blaze Ember Fuel&r.",
              "",
              "Ein Eimer davon (1 000 mB) gibt &e450 000 FE&r, der Generator schiebt bis zu &e5 000 FE/t&r heraus und speichert 5 Millionen. Abfüllen mit Eimer, &6Fluid Canister&r (vier Ferricore um Glas, fasst 8 Eimer) oder dem &6Simple Fluid Collector&r (wie der Brecher, mit Eimer statt Diamant und Werfer statt Beobachter).",
          ],
          tasks=[task_item("justdirethings:generatorfluidt1", 1)],
          rewards=[reward_item("justdirethings:blazegold_ingot", 4), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["generator"], icon="justdirethings:generatorfluidt1"),

    quest("portal_gun", 5, 10, "&dBau die Portalkanone",
          subtitle="Blau rein, orange raus.",
          description=[
              "&eRezept:&r fünf &6Blazegold Ingots&r und ein &6Enderauge&r: Barren oben Mitte und rechts, in der mittleren Reihe links und rechts vom Auge, unten links.",
              "",
              "Die &6Portal Gun&r schießt mit &eLinksklick&r ein blaues und mit &eRechtsklick&r ein oranges Portal an die Wand. Wer durch das eine geht, kommt aus dem anderen, Items genauso. Jeder Schuss kostet &e1 000 FE&r, der Speicher fasst 100 000 FE, geladen wird im Taschengenerator.",
              "",
              "Dazu passt der &6Blazejet Wand&r (ein Blazegold, zwei Ferricore diagonal): Rechtsklick stößt dich in Blickrichtung, und solange er in der Hand ist, nimmst du keinen Fallschaden. Repariert sich in Lava.",
              "",
              "&cAusblick:&r Der &6Voidshift Wand&r, der dich dorthin teleportiert, wohin du schaust, braucht Celestigem und kommt in Stufe 3. Die &6Portal Gun V2&r mit Portalflüssigkeit kommt in Stufe 4.",
          ],
          tasks=[task_item("justdirethings:portalgun", 1)],
          rewards=[reward_item("justdirethings:blazegold_ingot", 4), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["pocket_gen"], icon="justdirethings:portalgun", size=1.5, shape="diamond"),

    quest("swapper", 10, 10, "&dBau den Tauscher",
          subtitle="Zwei Orte, ein Blockwechsel.",
          description=[
              "&eRezept:&r vier &6Blazegold Ingots&r in die Ecken, ein &6Beobachter&r in die Mitte, ein &6Enderauge&r oben, &6Redstone&r unten, &6Lapis&r links und rechts. Dazu den &6Ferricore Wrench&r: vier Barren in Hakenform.",
              "",
              "Stell zwei &6Simple Swapper&r auf, Rechtsklick mit dem Schraubenschlüssel auf den ersten, dann auf den zweiten: verbunden, auch zwischen Dimensionen.",
              "",
              "Ab dann tauschen sie die Blöcke vor sich, Truhen und Maschinen samt Inhalt, oder Lebewesen nach denselben Zielen wie der Klicker. Auf Spieler gestellt ist das dein erster Teleporter, auf Erwachsene ein Tiersortierer, der die Kälber behält.",
              "",
              "Der Schraubenschlüssel dreht außerdem Blöcke.",
          ],
          tasks=[task_item("justdirethings:blockswappert1", 1), task_item("justdirethings:ferricore_wrench", 1)],
          rewards=[reward_item("minecraft:ender_eye", 2), reward_item("justdirethings:blazegold_ingot", 2), reward_xp(5)],
          deps=["sensor"], icon="justdirethings:blockswappert1"),

    # ---- Die Goo-Strasse --------------------------------------------------------
    quest("factory", 17.5, 7.5, "&a&lBau die Goo-Straße",
          subtitle="Ferricore und Blazegold, ohne Hand anzulegen.",
          description=[
              "Zeit, alles zusammenzubauen. Eine &eGoo-Straße&r: der &6Blocksetzer&r stellt Eisenblöcke neben das Goo, der &6Sensor&r (Raw Ferricore Block im Filter, Allow List) schaltet den &6Blockbrecher&r auf Redstone Hoch ein, der &6Item Collector&r sammelt das Raw Ferricore in eine Truhe, und ein &6Klicker&r mit Zucker weckt das Goo wieder.",
              "",
              "Jedes Goo hat sechs Seiten, auf jede passt so ein Satz. Mit Blazebloom Goo und Goldblöcken läuft dieselbe Straße für Blazegold, mit Kohleblöcken für Primal Coal.",
              "",
              "Hinten schmilzt ein Ofen mit Fuel Canister das Raw Ferricore. Wer Pipez oder Mekanism-Transporter hat, verbindet alles ohne Trichter.",
          ],
          tasks=[task_item("justdirethings:ferricore_ingot", 64), task_item("justdirethings:blazegold_ingot", 32)],
          rewards=[reward_table("s2_rare"), reward_item("justdirethings:blazegold_ingot", 8), reward_xp(20)],
          deps=["collector"], icon="justdirethings:ferricore_block", size=2.5, shape="gear"),

    quest("outlook", 20.5, 7.5, "&dAusblick auf Celestigem",
          subtitle="Was Stufe 3 und 4 öffnen.",
          description=[
              "&6Stufe 3:&r &6VoidShimmer Goo&r, geweckt mit Chorusfrucht oder Enderperlen, macht aus Diamantblöcken &6Celestigem&r. Damit kommen die &efortgeschrittenen Maschinen&r mit Bereich und Filter (Brecher, Setzer, Spender, Sensor, Klicker), der &6Energy Transmitter&r für kabellosen Strom, Celestigem-Werkzeug mit 5x5-Hammer und Drops-Teleporter, der Paxel und der Voidshift Wand.",
              "",
              "&6Stufe 4:&r &6Shadowpulse Goo&r (Sculk) macht aus Netheritblöcken &6Eclipse Alloy&r: 7x7-Hammer, Flug, Lavaschutz. Dazu die &6Zeitkristalle&r, die nacheinander in Oberwelt, Nether und End reifen, der &6Time Wand&r, der Blöcke bis zu 256-fach beschleunigt, die &6Paradox Machine&r, die abgebaute Roherz-Blöcke und Mobs aus einem Schnappschuss zurückholt, und die Portal Gun V2.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["factory"], icon="justdirethings:gooblock_tier2", optional=True),
]

images = [
    banner("dire_things/title", "Just Dire Things", 9, -6.5, height=1.75, kind="title", colour="nature"),
    banner("dire_things/goo", "Das Goo", 3.75, -2.7, height=0.9, colour="nature"),
    banner("dire_things/tools", "Werkzeug und Upgrades", 15.5, -4.6, height=0.9, colour="brass"),
    banner("dire_things/machines", "Maschinen", 7.5, 5.5, height=0.9, colour="stone"),
    banner("dire_things/factory", "Die Goo-Straße", 19, 5.5, height=0.9, colour="nature"),
]

chapter(C, "Just Dire Things", "justdirethings:gooblock_tier1", "tech", quests, shape="circle", order=47, stage=2,
        subtitle=["Stufe 2: Goo, Ferricore, Blazegold, Werkzeug-Upgrades und die einfachen Maschinen."], images=images)
