"""Essen und Landwirtschaft: Farmer's Delight, Farming for Blockheads und Aquaculture. Messer,
wilde Pflanzen, der Kochtopf, reichhaltige Erde, Dünger, Tiere, der Markt und die Fischerei."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "food"

quests = [
    quest("welcome", 0, 3, "&6Essen und Landwirtschaft",
          subtitle="Wer gut isst, gräbt länger.",
          description=[
              "Graben, Rennen und Ultimine kosten Hunger, und mit rohem Fleisch und Brot kommst du nicht weit. Dieses Kapitel zeigt dir drei Mods, die das ändern:",
              "",
              "&6Farmer's Delight&r bringt eine echte Küche: neue Pflanzen, ein Schneidebrett, einen Kochtopf und Mahlzeiten, die lange satt machen und dir nützliche Effekte geben.",
              "&6Farming for Blockheads&r hilft dir bei Feldern und Tieren: Dünger, Futtertrog, Hühnernest und ein Markt für Samen und Setzlinge.",
              "&6Aquaculture&r macht aus dem Angeln ein eigenes Hobby mit Dutzenden Fischen, besseren Ruten und Zubehör.",
              "",
              "&eTipp:&r Dank &6AppleSkin&r siehst du im Tooltip jeder Nahrung, wie viel Hunger und Sättigung sie bringt, und an der Hungerleiste, was davon gerade übrig ist.",
          ],
          tasks=[task_checkmark("Ich habe Hunger")],
          rewards=[reward_item("minecraft:bread", 16), reward_table("s1_common")],
          icon="farmersdelight:cooking_pot", size=2.5, shape="hexagon"),

    # ---- Grundlagen -----------------------------------------------------------
    quest("f_knife", 4.5, -7, "&6Feuersteinküchenmesser",
          subtitle="Das wichtigste Werkzeug der Küche.",
          description=[
              img(item_texture("farmersdelight:flint_knife"), 32, 32),
              "",
              "Ein &6Feuerstein&r über einem &6Stock&r ergibt ein &6Feuersteinküchenmesser&r. Später gibt es das Messer auch aus Eisen, Gold und Diamant, die halten länger und schneiden schneller.",
              "",
              "Mit dem Messer schneidest du am Schneidebrett, erntest &6Stroh&r von Gras und Weizen und schneidest Kuchen in Stücke. Tiere, die du mit dem Messer erlegst, lassen öfter besondere Teile fallen, Schweine zum Beispiel &6Schinken&r.",
          ],
          tasks=[task_item("farmersdelight:flint_knife", 1)],
          rewards=[reward_item("minecraft:bread", 8)],
          deps=["welcome"], icon="farmersdelight:flint_knife", size=1.5),

    quest("f_straw", 7, -8, "&6Stroh",
          subtitle="Mit dem Messer durchs hohe Gras.",
          description=[
              img(item_texture("farmersdelight:straw"), 32, 32),
              "",
              "Brich mit dem Messer in der Hand &6Gras&r, &6Weizen&r oder &6Reis&r ab, und du bekommst zusätzlich &6Stroh&r.",
              "",
              "Aus zwei Stroh übereinander werden vier &6Strohseile&r, aus vier Stroh im Quadrat ein &6Leinenstofffetzen&r, und zusammen mit Rinde und Knochenmehl wird Stroh zu &6Organischem Kompost&r. Neun Stroh lassen sich zu einem Strohbündel pressen.",
          ],
          tasks=[task_item("farmersdelight:straw", 16)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["f_knife"], icon="farmersdelight:straw"),

    quest("f_cutting_board", 7, -6, "&6Schneidebrett",
          subtitle="Mehr aus jeder Zutat herausholen.",
          description=[
              "Zwei &6Stöcke&r und vier &6Bretter&r ergeben ein &6Schneidebrett&r. Stell es irgendwo hin, leg mit einem Rechtsklick eine Zutat darauf und klick es dann mit dem passenden Werkzeug an.",
              "",
              "Mit dem &eMesser&r zerteilst du Essen: aus Kohl werden Kohlblätter, aus Rindfleisch Hackfleisch, aus einem Kürbis Kürbisscheiben, aus Reisrispen Reis und Stroh.",
              "Mit der &eAxt&r entrindest du Holzstämme und bekommst &6Baumrinde&r dazu.",
              "",
              "Was genau ein Werkzeug auf dem Brett macht, zeigt dir JEI unter der Kategorie des Schneidebretts.",
          ],
          tasks=[task_item("farmersdelight:cutting_board", 1)],
          rewards=[reward_item("minecraft:beef", 8)],
          deps=["f_knife"], icon="farmersdelight:cutting_board"),

    quest("f_wild", 9, -7, "&aWilde Pflanzen",
          subtitle="Tomaten, Zwiebeln und Kohl wachsen wild.",
          description=[
              "Überall in der Welt wachsen kleine Büschel wilder Pflanzen: &6Wildweißkohl&r und &6Wildrüben&r an der Küste, &6Tomatensträucher&r dort, wo es warm ist, &6Wildzwiebeln&r, &6Wildkarotten&r und &6Wildkartoffeln&r in gemäßigten Gegenden.",
              "",
              "Brich sie ab, dann bekommst du die Frucht oder die Samen. Tomaten pflanzt du über &6Tomatensamen&r, Kohl über &6Weißkohlsamen&r, Zwiebeln setzt du direkt.",
              "",
              "Pflanz alles zu Hause an. Jede Suppe und jede Mahlzeit, die jetzt kommt, braucht Gemüse.",
          ],
          tasks=[task_item("farmersdelight:tomato", 4), task_item("farmersdelight:onion", 4),
                 task_item("farmersdelight:cabbage", 4)],
          rewards=[reward_item("minecraft:bone_meal", 32)],
          deps=["f_straw", "f_cutting_board"], icon="farmersdelight:tomato"),

    quest("f_rice", 11, -8, "&6Reis",
          subtitle="Wächst mit nassen Füßen.",
          description=[
              img(item_texture("farmersdelight:rice"), 32, 32),
              "",
              "&6Wildreis&r wächst im seichten Wasser, oft in Sümpfen und an Flussufern. Reis pflanzt du selbst in Wasser, das genau einen Block tief ist, mit Erde darunter.",
              "",
              "Oben aus der Pflanze wachsen &6Reisrispen&r. Am Schneidebrett werden sie mit dem Messer zu Reis und Stroh.",
          ],
          tasks=[task_item("farmersdelight:rice", 8)],
          rewards=[reward_item("minecraft:water_bucket", 1)],
          deps=["f_wild"], icon="farmersdelight:rice"),

    quest("f_rope", 11, -6, "&6Strohseil",
          subtitle="Tomaten klettern gern.",
          description=[
              "Zwei &6Stroh&r übereinander ergeben vier &6Strohseile&r. Hängst du Seile über eine Tomatenrebe, klettert sie daran hoch und trägt auf der ganzen Höhe Früchte.",
              "",
              "Seile kannst du auch zum Hinabklettern in Schächte benutzen, und vier davon werden zu einem &6Sicherheitsnetz&r, das Stürze abfängt.",
          ],
          tasks=[task_item("farmersdelight:rope", 8)],
          rewards=[reward_item("farmersdelight:tomato_seeds", 4)],
          deps=["f_wild"], icon="farmersdelight:rope", optional=True),

    # ---- Kochen ----------------------------------------------------------------
    quest("f_stove", 4.5, 0, "&6Herd",
          subtitle="Hitze für die ganze Küche.",
          description=[
              "Der &6Herd&r besteht aus drei &6Eisenbarren&r oben, vier &6Ziegelsteinen&r an den Seiten und unten und einem &6Lagerfeuer&r in der Mitte der untersten Reihe.",
              "",
              "Auf ihm brätst du bis zu sechs Stücke gleichzeitig, ganz ohne Brennstoff. Vor allem aber ist er die beste &6Hitzequelle&r für Kochtopf und Bratpfanne.",
              "",
              "Ein Lagerfeuer, Feuer, Lava oder ein Magmablock unter dem Topf gehen auch, der Herd sieht aber schöner aus und brennt dir nicht die Küche ab.",
          ],
          tasks=[task_item("farmersdelight:stove", 1)],
          rewards=[reward_item("minecraft:coal", 8)],
          deps=["welcome"], icon="farmersdelight:stove", size=1.5),

    quest("f_pot", 7, 0, "&6Kochtopf",
          subtitle="Suppen, Eintöpfe und Mahlzeiten.",
          description=[
              img(item_texture("farmersdelight:cooking_pot"), 32, 32),
              "",
              "Rezept: oben zwei &6Ziegel&r mit einer &6Holzschaufel&r dazwischen, in der Mitte zwei &6Eisenbarren&r mit einem &6Wassereimer&r dazwischen, unten drei &6Eisenbarren&r.",
              "",
              "Stell den Topf auf eine &eHitzequelle&r, sonst kocht er nicht. Rechtsklick öffnet ihn: Links kommen bis zu sechs Zutaten hinein, rechts daneben der Behälter, meistens eine &6Schüssel&r. Der Pfeil zeigt, wie weit das Gericht ist.",
              "",
              "Fertige Portionen bleiben im Topf, bis du sie mit dem Behälter herausholst. Du kannst den Topf mit Inhalt abbauen und mitnehmen und ihn später an jeder Hitzequelle wieder aufstellen.",
          ],
          tasks=[task_item("farmersdelight:cooking_pot", 1)],
          rewards=[reward_item("minecraft:bowl", 16)],
          deps=["f_stove"], icon="farmersdelight:cooking_pot", size=1.75, shape="hexagon"),

    quest("f_skillet", 7, 2.4, "&6Bratpfanne",
          subtitle="Braten auf dem Herd oder in der Hand.",
          description=[
              "Vier &6Eisenbarren&r und ein &6Ziegel&r als Griff ergeben die &6Bratpfanne&r. Stell sie auf eine Hitzequelle und leg eine Zutat hinein, dann brät sie das Stück wie ein kleiner Ofen.",
              "",
              "Du kannst sie auch in der Hand benutzen: Halte die Zutat in der anderen Hand und die Pfanne über einer Hitzequelle. Nebenbei ist sie eine ordentliche Schlagwaffe.",
          ],
          tasks=[task_item("farmersdelight:skillet", 1)],
          rewards=[reward_item("minecraft:egg", 8)],
          deps=["f_stove"], icon="farmersdelight:skillet", optional=True),

    quest("f_soup", 9.5, -1, "&6Gemüsesuppe",
          subtitle="Deine erste richtige Mahlzeit.",
          description=[
              img(item_texture("farmersdelight:vegetable_soup"), 32, 32),
              "",
              "Die &6Gemüsesuppe&r ist leicht und macht lange satt: eine &6Karotte&r, eine &6Kartoffel&r, eine &6Rote Bete&r und etwas Grünes wie &6Weißkohl&r oder ein &6Weißkohlblatt&r, dazu eine Schüssel.",
              "",
              "Ein Topf kocht mehrere Portionen nacheinander, wenn du genug Zutaten hineinlegst.",
          ],
          tasks=[task_item("farmersdelight:vegetable_soup", 4)],
          rewards=[reward_table("s1_common")],
          deps=["f_pot", "f_wild"], icon="farmersdelight:vegetable_soup"),

    quest("f_sauce", 9.5, 1, "&6Tomatensauce",
          subtitle="Grundlage für vieles.",
          description=[
              "Zwei &6Tomaten&r im Topf mit einer Schüssel ergeben &6Tomatensauce&r. Allein ist sie nichts Besonderes, aber sie steckt in Nudeln mit Fleischbällchen, in Nudeln mit Hammelkotelett und im Fischeintopf.",
              "",
              "&eTipp:&r Nudeln machst du aus &6Teigball&r: Weizen und Wasser oder Weizen und Ei. Am Schneidebrett wird der Teig mit dem Messer zu &6Rohen Nudeln&r.",
          ],
          tasks=[task_item("farmersdelight:tomato_sauce", 2)],
          rewards=[reward_item("minecraft:wheat", 16)],
          deps=["f_pot", "f_wild"], icon="farmersdelight:tomato_sauce"),

    quest("f_stew", 12, -1, "&6Rindfleischeintopf",
          subtitle="Deftig und wärmend.",
          description=[
              "Rohes &6Rindfleisch&r, eine &6Karotte&r und eine &6Kartoffel&r, dazu eine Schüssel: Das ist der &6Rindfleischeintopf&r.",
              "",
              "Eintöpfe und Suppen sind die Mahlzeiten für lange Tage in der Mine. Sie geben dir den Effekt &dKomfort&r, mehr dazu in der nächsten Quest.",
          ],
          tasks=[task_item("farmersdelight:beef_stew", 2)],
          rewards=[reward_item("minecraft:carrot", 16)],
          deps=["f_soup"], icon="farmersdelight:beef_stew"),

    quest("f_rice_cooked", 12, 1, "&6Gekochter Reis",
          subtitle="Die Beilage zu allem.",
          description=[
              "&6Reis&r im Topf mit einer Schüssel wird zu &6Gekochtem Reis&r. Er steckt in vielen größeren Gerichten, etwa in &6Steak und Kartoffeln&r oder im &6Honigglasierten Schinken&r.",
              "",
              "Mit Ei, Karotte und Zwiebel wird Reis im Topf zu &6Gebratenem Reis&r, einer vollen Mahlzeit.",
          ],
          tasks=[task_item("farmersdelight:cooked_rice", 4)],
          rewards=[reward_item("minecraft:egg", 8)],
          deps=["f_sauce", "f_rice"], icon="farmersdelight:cooked_rice"),

    quest("f_effects", 14.5, 0, "&dGesättigt und Komfort",
          subtitle="Warum gutes Essen mehr kann.",
          description=[
              "Viele Gerichte aus Farmer's Delight geben dir einen von zwei Effekten:",
              "",
              "&dGesättigt&r (Nourishment): Deine Hungerleiste sinkt nicht, solange der Effekt anhält. Nur wenn du dich über die Sättigung heilst, geht sie runter.",
              "&dKomfort&r (Comfort): Du regenerierst Leben, egal wie hungrig du bist.",
              "",
              "Suppen und Eintöpfe geben meist Komfort, große Mahlzeiten meist Gesättigt. Wie lange ein Effekt hält, steht im Tooltip. Mit einer Suppe vor dem Graben und einer Mahlzeit vor der Rückkehr kommst du sehr weit.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["f_stew", "f_rice_cooked"], icon="farmersdelight:fried_rice"),

    quest("f_feast", 17, 0, "&6Backhähnchen",
          subtitle="Ein Festmahl für alle.",
          description=[
              "Manche Gerichte sind &6Festmahle&r: Du stellst sie als Block auf den Tisch, und jeder holt sich mit einer Schüssel eine Portion. Perfekt für eine gemeinsame Basis.",
              "",
              "Das &6Backhähnchen&r besteht aus einem gebratenen Hähnchen, zwei Ofenkartoffeln, zwei Karotten, einer Zwiebel, einem Ei, Brot und einer Schüssel. Ähnlich funktionieren Hirtenkuchen, Honigglasierter Schinken und Gefüllter Kürbis.",
          ],
          tasks=[task_item("farmersdelight:roast_chicken_block", 1)],
          rewards=[reward_table("s1_common")],
          deps=["f_effects"], icon="farmersdelight:roast_chicken_block"),

    quest("f_pie", 17, 2.4, "&6Apfelkuchen",
          subtitle="Für den süßen Zahn.",
          description=[
              "Aus drei &6Weizen&r mit einer &6Milchflasche&r (zwei Weizen daneben, einer darunter) wird eine &6Kuchenkruste&r. Mit Äpfeln, Zucker und Weizen darauf entsteht ein &6Apfelkuchen&r.",
              "",
              "Stell den Kuchen hin und schneide dir mit dem Messer Stücke ab. Eine Milchflasche machst du aus einem Milcheimer und vier Glasflaschen.",
          ],
          tasks=[task_item("farmersdelight:apple_pie", 1)],
          rewards=[reward_item("minecraft:apple", 8)],
          deps=["f_effects"], icon="farmersdelight:apple_pie", optional=True),

    # ---- Anbau -----------------------------------------------------------------
    quest("f_bark", 4.5, 6, "&6Baumrinde",
          subtitle="Holz, Axt, Schneidebrett.",
          description=[
              img(item_texture("farmersdelight:tree_bark"), 32, 32),
              "",
              "Leg einen &6Holzstamm&r auf das Schneidebrett und klick ihn mit einer &6Axt&r an. Du bekommst den entrindeten Stamm zurück und dazu &6Baumrinde&r.",
              "",
              "Rinde ist die Hauptzutat für &6Organischen Kompost&r und lässt sich auch zu Papier verarbeiten.",
          ],
          tasks=[task_item("farmersdelight:tree_bark", 8)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["welcome"], icon="farmersdelight:tree_bark"),

    quest("f_compost", 7, 6, "&6Organischer Kompost",
          subtitle="Erde, Stroh, Rinde, Knochenmehl.",
          description=[
              "&6Organischer Kompost&r entsteht formlos aus einer &6Erde&r, zwei &6Stroh&r, zwei &6Knochenmehl&r und vier &6Baumrinde&r. Statt Rinde gehen auch zwei &6Verrottetes Fleisch&r mit vier Knochenmehl.",
              "",
              "Stell den Kompost als Block hin. Mit der Zeit zersetzt er sich zu &6Reichhaltiger Erde&r.",
          ],
          tasks=[task_item("farmersdelight:organic_compost", 4)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["f_bark"], icon="farmersdelight:organic_compost"),

    quest("f_rich_soil", 9, 6, "&6Reichhaltige Erde",
          subtitle="Hier wächst alles schneller.",
          description=[
              "Kompost wird schneller zu &6Reichhaltiger Erde&r, wenn in der Nähe Pilze, Podsol, Myzel oder weiterer Kompost liegen.",
              "",
              "Pflanzen auf Reichhaltiger Erde wachsen schneller. Bearbeite sie mit der Hacke, dann wird sie zu &6Reichhaltigem Ackerboden&r für Weizen, Gemüse und Reis.",
              "",
              "Pilze, die du darauf setzt, wachsen zu &6Pilzkolonien&r heran, aus denen du immer wieder Pilze erntest.",
          ],
          tasks=[task_item("farmersdelight:rich_soil", 8)],
          rewards=[reward_table("s1_common")],
          deps=["f_compost"], icon="farmersdelight:rich_soil", size=1.5),

    quest("f_colony", 11, 7.5, "&6Pilzkolonie",
          subtitle="Pilze ohne Ende.",
          description=[
              "Setz einen braunen oder roten Pilz auf Reichhaltige Erde, und er wächst zu einer &6Pilzkolonie&r. Eine ausgewachsene Kolonie erntest du mit der &6Schere&r: Sie gibt dir Pilze und wächst danach einfach weiter.",
              "",
              "Pilze brauchst du für Pilzreis, Pilzsuppe, Gemüsenudeln und manche Tränke.",
          ],
          tasks=[task_item("farmersdelight:brown_mushroom_colony", 1)],
          rewards=[reward_item("minecraft:red_mushroom", 8)],
          deps=["f_rich_soil"], icon="farmersdelight:brown_mushroom_colony", optional=True),

    quest("f_fertilizer", 11, 5, "&6Dünger",
          subtitle="Drei Farben, drei Wirkungen.",
          description=[
              "Farming for Blockheads hat drei Dünger. Klick damit auf Ackerboden, und er wird zu &6Gedüngtem Ackerland&r:",
              "",
              "&cRoter Dünger&r lässt Pflanzen schneller wachsen. Drei rote Farbstoffe, zwei Goldnuggets, Weizensamen, drei Knochenmehl.",
              "&aGrüner Dünger&r bringt mehr Ertrag pro Ernte. Drei grüne Farbstoffe, zwei Goldnuggets, Weizensamen, drei Weizen.",
              "&eGelber Dünger&r verhindert, dass das Feld zertrampelt wird. Drei gelbe Farbstoffe, zwei Goldnuggets, Weizensamen, drei Erde.",
              "",
              "Jedes Rezept ergibt vier Dünger.",
          ],
          tasks=[task_item("farmingforblockheads:red_fertilizer", 4)],
          rewards=[reward_item("minecraft:gold_nugget", 8)],
          deps=["f_rich_soil"], icon="farmingforblockheads:red_fertilizer"),

    quest("f_crates", 13, 6, "&6Gemüsekisten",
          subtitle="Ordnung im Vorratsraum.",
          description=[
              "Neun Tomaten, Zwiebeln, Kohlköpfe, Karotten, Kartoffeln oder Rote Beten ergeben eine &6Kiste&r als Block, etwa eine &6Tomatenkiste&r. Aus der Kiste bekommst du die neun Stück jederzeit zurück.",
              "",
              "Das spart Platz in den Truhen und sieht in der Küche richtig gut aus.",
          ],
          tasks=[task_item("farmersdelight:tomato_crate", 1)],
          rewards=[reward_xp(3)],
          deps=["f_fertilizer"], icon="farmersdelight:tomato_crate", optional=True),

    # ---- Tiere und Markt -------------------------------------------------------
    quest("f_trough", 4.5, 12, "&6Futtertrog",
          subtitle="Die Tiere füttern sich selbst.",
          description=[
              "Der &6Futtertrog&r besteht aus Brettern, einem &6Heuballen&r und einer &6Goldenen Karotte&r. Füll ihn mit Futter, etwa Weizen, Karotten oder Samen.",
              "",
              "Tiere in der Nähe, die sich vermehren können, fressen daraus von selbst. Du musst also nicht mehr jede Kuh einzeln füttern, um Nachwuchs zu bekommen.",
              "",
              "&eTipp:&r Leder für Rucksäcke, Fleisch für Eintöpfe und Wolle für Schlafsäcke kommen so ganz nebenbei.",
          ],
          tasks=[task_item("farmingforblockheads:feeding_trough", 1)],
          rewards=[reward_item("minecraft:wheat", 32)],
          deps=["welcome"], icon="farmingforblockheads:feeding_trough", size=1.5),

    quest("f_nest", 7, 11, "&6Hühnernest",
          subtitle="Eier einsammeln lassen.",
          description=[
              "Ein &6Heuballen&r zwischen zwei Brettern ergibt ein &6Hühnernest&r. Hühner in der Nähe legen ihre Eier direkt hinein, statt sie im Gras zu verstreuen.",
              "",
              "Eier brauchst du für Teig, Gebratenen Reis, Spiegeleier, Backhähnchen und Kuchen.",
          ],
          tasks=[task_item("farmingforblockheads:chicken_nest", 1)],
          rewards=[reward_item("minecraft:egg", 8)],
          deps=["f_trough"], icon="farmingforblockheads:chicken_nest"),

    quest("f_market", 7, 13, "&6Markt",
          subtitle="Samen und Setzlinge für Smaragde.",
          description=[
              "Der &6Markt&r besteht aus Brettern und einer &6Roten Wolle&r oben und fünf &6Holzstämmen&r als Gestell. Stell ihn auf, und bald kommt ein Händler vorbei.",
              "",
              "Er verkauft Samen, Setzlinge, Blumen und Dünger, jeweils für einen &6Smaragd&r. Dabei sind auch die wilden Pflanzen und der Reis aus Farmer's Delight, Pilzkolonien und die &dArchwood-Setzlinge&r für Ars Nouveau.",
              "",
              "Praktisch für alles, was bei dir in der Nähe nicht wächst.",
          ],
          tasks=[task_item("farmingforblockheads:market", 1)],
          rewards=[reward_item("minecraft:emerald", 8)],
          deps=["f_trough"], icon="farmingforblockheads:market"),

    quest("f_ham", 9.5, 11, "&6Schinken",
          subtitle="Mit dem Messer auf die Jagd.",
          description=[
              "Schweine, die du mit einem &6Küchenmesser&r erlegst, lassen &6Schinken&r fallen. Im Räucherofen oder auf dem Lagerfeuer wird er zu &6Räucherschinken&r, der Hauptzutat für den Honigglasierten Schinken.",
              "",
              "Am Schneidebrett zerlegst du Schinken in Schweinefleisch und einen Knochen.",
          ],
          tasks=[task_item("farmersdelight:ham", 1)],
          rewards=[reward_item("minecraft:porkchop", 8)],
          deps=["f_nest"], icon="farmersdelight:ham", optional=True),

    quest("f_dog_food", 12, 11, "&6Hundefutter",
          subtitle="Für deinen besten Freund.",
          description=[
              "Verrottetes Fleisch, Knochenmehl, rohes Fleisch und Reis im Topf ergeben &6Hundefutter&r. Füttere es einem gezähmten Wolf, und er bekommt für eine Weile hilfreiche Effekte.",
              "",
              "Die genauen Effekte stehen im Tooltip.",
          ],
          tasks=[task_item("farmersdelight:dog_food", 1)],
          rewards=[reward_item("minecraft:bone", 8)],
          deps=["f_ham"], icon="farmersdelight:dog_food", optional=True),

    quest("f_horse_feed", 9.5, 13, "&6Pferdefutter",
          subtitle="Für schnelle Reisen.",
          description=[
              "Ein &6Heuballen&r (oder ein Reisbündel), zwei &6Äpfel&r und eine &6Goldene Karotte&r ergeben &6Pferdefutter&r. Ein gezähmtes Reittier, das es frisst, bekommt für eine Weile hilfreiche Effekte, die der Tooltip auflistet.",
          ],
          tasks=[task_item("farmersdelight:horse_feed", 1)],
          rewards=[reward_item("minecraft:apple", 8)],
          deps=["f_market"], icon="farmersdelight:horse_feed", optional=True),

    # ---- Fischerei -------------------------------------------------------------
    quest("f_rod", 4.5, 18, "&6Eisen-Angelrute",
          subtitle="Neue Fische, neue Ruten.",
          description=[
              "&6Aquaculture&r bringt Dutzende neue Fische, jeder mit seinem eigenen Lebensraum: Flüsse, Seen, Meere, Sümpfe, Dschungel, warme und kalte Biome.",
              "",
              "Die &6Eisen-Angelrute&r baust du aus zwei &6Eisenbarren&r, zwei &6Fäden&r und einem &6Stock&r. Sie hält länger und lässt sich mit Zubehör ausrüsten.",
              "",
              "Schleichen und Rechtsklick mit der Rute öffnet ihre Plätze für &6Haken&r, &6Köder&r, &6Angelleine&r und &6Schwimmer&r.",
          ],
          tasks=[task_item("aquaculture:iron_fishing_rod", 1)],
          rewards=[reward_item("minecraft:cod", 8)],
          deps=["welcome"], icon="aquaculture:iron_fishing_rod", size=1.5),

    quest("f_hook", 7, 17, "&6Haken",
          subtitle="Der richtige Haken für jeden Fang.",
          description=[
              "Der &6Eisen-Haken&r entsteht aus Eisennuggets und ist die Grundlage für alle anderen. Mit Goldnuggets, Federn, Redstone oder Eisennuggets drumherum wird er zum Gold-, Light-, Redstone- oder Heavy-Haken, zwei Eisen-Haken ergeben einen Double-Haken.",
              "",
              "Jeder Haken ändert etwas am Angeln. Was genau, verrät der Tooltip. Setz den Haken in die Rute ein.",
          ],
          tasks=[task_item("aquaculture:iron_hook", 1)],
          rewards=[reward_item("minecraft:iron_nugget", 16)],
          deps=["f_rod"], icon="aquaculture:iron_hook"),

    quest("f_worm_farm", 7, 19, "&6Wurmfarm",
          subtitle="Köder aus Küchenresten.",
          description=[
              "Die &6Wurmfarm&r baust du aus Zäunen, einem Block &6Erde&r und Brettern. Füll sie mit Pflanzenresten, und mit der Zeit bekommst du &6Würmer&r heraus.",
              "",
              "Würmer sind &6Köder&r: In die Rute eingesetzt beißen die Fische schneller an.",
          ],
          tasks=[task_item("aquaculture:worm_farm", 1)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["f_rod"], icon="aquaculture:worm_farm"),

    quest("f_fillet", 9.5, 18, "&6Filetmesser",
          subtitle="Mehr Essen aus jedem Fisch.",
          description=[
              "Ein &6Eisen-Filetmesser&r aus zwei Eisenbarren und einem Stock zerlegt Fische in der Werkbank zu &6Rohem Fischfilet&r. Große Fische geben mehr Filets.",
              "",
              "Gebraten sind die Filets eine ordentliche Mahlzeit. &6Gräten&r, die du manchmal statt eines Fisches herausziehst, werden in der Werkbank zu Knochenmehl.",
          ],
          tasks=[task_item("aquaculture:iron_fillet_knife", 1), task_item("aquaculture:fish_fillet_raw", 4)],
          rewards=[reward_table("s1_common")],
          deps=["f_hook", "f_worm_farm"], icon="aquaculture:iron_fillet_knife"),

    quest("f_tackle", 12, 17, "&6Angelkiste",
          subtitle="Alles an einem Platz.",
          description=[
              "Die &6Angelkiste&r hält deine Haken, Köder, Leinen und Schwimmer zusammen, und du kannst darin deine Rute ausrüsten. Rezept: eine Truhe, Eisenbarren, ein Eisenblock und oben zwei grüne Farbstoffe, Seetang oder Algen.",
          ],
          tasks=[task_item("aquaculture:tackle_box", 1)],
          rewards=[reward_xp(3)],
          deps=["f_fillet"], icon="aquaculture:tackle_box", optional=True),

    quest("f_sushi", 12, 19, "&6Sushi",
          subtitle="Roh, aber lecker.",
          description=[
              "Ein &6Rohes Fischfilet&r und ein wenig &6Seegras&r ergeben &6Sushi&r. Schnell gemacht und ein netter Snack unterwegs.",
          ],
          tasks=[task_item("aquaculture:sushi", 4)],
          rewards=[reward_xp(3)],
          deps=["f_fillet"], icon="aquaculture:sushi", optional=True),

    quest("f_neptunium", 14.5, 18, "&bNeptunium",
          subtitle="Ein seltener Fang aus der Tiefe.",
          description=[
              "Mit viel Glück ziehst du beim Angeln &bNeptunium&r aus dem Wasser, als Nugget oder in einer Schatzkiste namens &6Neptune's Kopfgeld&r.",
              "",
              "Aus Neptunium-Barren entstehen Werkzeug, Waffen, Rüstung und die beste Angelrute von Aquaculture. Bis du genug zusammen hast, dauert es, aber es lohnt sich.",
          ],
          tasks=[task_item("aquaculture:neptunium_ingot", 1)],
          rewards=[reward_table("s1_uncommon")],
          deps=["f_tackle"], icon="aquaculture:neptunium_ingot", optional=True),

    # ---- Abschluss -------------------------------------------------------------
    quest("f_pantry", 20, 6, "&6Volle Speisekammer",
          subtitle="Kochen für die ganze Basis.",
          description=[
              "Suppe, Eintopf und Gebratener Reis für alle, die mit dir spielen. Mit so einem Vorrat hält jeder Abend in der Mine bis zum Schluss.",
              "",
              "Ab Stufe 2 geht es weiter: Mit Blaze-Brenner, Mechanischem Arm und Deployer aus Create verbindet &6Create Central Kitchen&r die Küche mit deinen Maschinen, dann kocht die Fabrik für dich.",
          ],
          tasks=[task_item("farmersdelight:vegetable_soup", 8), task_item("farmersdelight:beef_stew", 8),
                 task_item("farmersdelight:fried_rice", 8)],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["f_effects", "f_rich_soil", "f_market", "f_fillet"],
          icon="farmersdelight:fried_rice", size=2.5, shape="gear"),
]

images = [
    banner("food/title", "Essen", 0, -2.4, height=1.8, kind="title", colour="nature"),
    banner("food/basics", "Grundlagen", 8.5, -9.6, height=0.9, colour="nature"),
    banner("food/cooking", "Kochen", 10.5, -2.6, height=0.9, colour="fire"),
    banner("food/farming", "Anbau", 9, 3.9, height=0.9, colour="nature"),
    banner("food/animals", "Tiere und Markt", 8, 9.6, height=0.9, colour="brass"),
    banner("food/fishing", "Fischerei", 9, 15.6, height=0.9, colour="water"),
]

chapter(C, "Essen und Landwirtschaft", "farmersdelight:cooking_pot", "world", quests, shape="circle", order=4,
        subtitle=["Messer, Kochtopf, reichhaltige Erde, Tiere und die Fischerei."],
        images=images)
