"""Immersive Engineering in stage 2: the hammer and manual, the coke oven and treated wood,
the alloy kiln, the crude blast furnace and steel, then kinetic power with the windmill and
the first LV wires. The big electric multiblocks come after this chapter."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_advancement, reward_item, reward_table,
                  reward_xp, banner, img)

C = "immersive"


def tex(name):
    """An Immersive Engineering item texture by its file name (they differ from the ids)."""
    return img(f"immersiveengineering:textures/item/{name}.png", 32, 32)


quests = [
    # ---- Grundlagen ----------------------------------------------------------
    quest("welcome", 0, 6.5, "&6&lImmersive Engineering",
          subtitle="Maschinen, durch die man hindurchlaufen kann.",
          description=[
              "&6Immersive Engineering&r baut seine Maschinen als &eMultiblöcke&r: Du stellst die richtigen Blöcke in der richtigen Form auf, schlägst mit dem &6Ingenieurshammer&r darauf, und aus dem Haufen Ziegel wird ein Ofen, eine Presse oder ein Hochofen.",
              "",
              "Dein wichtigstes Werkzeug ist das &6Ingenieurshandbuch&r (ein Buch und ein Hebel). Auf seinen Multiblock-Seiten kannst du jede Struktur drehen und Schicht für Schicht ansehen, dazu steht, welche Blöcke du brauchst.",
              "",
              "&eIn Stufe 2&r führt dich dieses Kapitel vom Koksofen über Behandeltes Holz und den Legierungsofen bis zum Hochofen und zu deinem ersten Stromnetz aus Windmühle und Kupferdraht. Der Hochofen braucht Ziegel aus dem &cNether&r, der seit Stufenbeginn offen ist.",
              "",
              tex("tool_manual"),
          ],
          tasks=[task_item("immersiveengineering:manual", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 16), reward_table("s2_common")],
          icon="immersiveengineering:manual", size=2.0, shape="hexagon"),

    quest("hammer", 2.5, 6.5, "&7Ingenieurshammer",
          subtitle="Der Schlüssel zu jedem Multiblock.",
          description=[
              "Zwei Eisenbarren, ein Faden und zwei Stöcke ergeben den &6Ingenieurshammer&r. Er formt Multiblöcke, stellt Seiten von Kondensatoren ein und macht aus Barren Bleche.",
              "",
              "&eSo formst du einen Multiblock:&r Bau die Struktur genau wie im Handbuch, dann rechtsklick mit dem Hammer auf den Block, den das Handbuch markiert, meist die Mitte einer Seite. Stimmt etwas nicht, passiert einfach nichts. Dann vergleiche Schicht für Schicht.",
              "",
              "Der Hammer hält 100 Anwendungen aus. Bau dir ruhig gleich einen zweiten.",
              "",
              tex("tool_hammer"),
          ],
          tasks=[task_item("immersiveengineering:hammer", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(5)],
          deps=["welcome"], icon="immersiveengineering:hammer", size=1.5),

    quest("plates", 2.5, 9.2, "&7Bleche",
          subtitle="Barren und Hammer, fertig ist das Blech.",
          description=[
              "Leg einen Barren und den &6Ingenieurshammer&r zusammen in die Werkbank, dann bekommst du ein &6Blech&r. Der Hammer bleibt erhalten, verliert aber einen Punkt Haltbarkeit.",
              "",
              "&6Eisenbleche&r brauchst du für die &6Mechanische Eisenkomponente&r, &6Kupferbleche&r für den Kupferdraht und &6Bleibleche&r für den Kondensator. Später übernimmt die Metallpresse diese Arbeit, bis dahin ist Handarbeit angesagt.",
          ],
          tasks=[task_item("immersiveengineering:plate_iron", 4), task_item("immersiveengineering:plate_copper", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_item("minecraft:copper_ingot", 8)],
          deps=["hammer"], icon="immersiveengineering:plate_iron"),

    quest("wirecutter", 0, 9.2, "&7Ingenieurskabelschneider",
          subtitle="Für Draht und für Fehler.",
          description=[
              "Zwei Stöcke und ein Eisenbarren ergeben den &6Kabelschneider&r. Mit einem Kupferblech in der Werkbank schneidet er daraus &6Kupferkabel&r, das Rohmaterial für jede Drahtspule.",
              "",
              "Rechtsklick auf einen Anschluss entfernt alle Drähte, die daran hängen. Falsch gespannte Leitungen bekommst du so schnell wieder weg.",
              "",
              tex("tool_wirecutter"),
          ],
          tasks=[task_item("immersiveengineering:wirecutter", 1)],
          rewards=[reward_item("minecraft:copper_ingot", 8)],
          deps=["welcome"]),

    quest("hemp", 0, 3.8, "&2Industriehanf",
          subtitle="Eine Pflanze mit Nutzen.",
          description=[
              "&6Industriehanfsamen&r fallen gelegentlich, wenn du hohes Gras abbaust. Pflanz sie auf Ackerboden wie Weizen. Die Pflanze wird zwei Blöcke hoch, und der obere Block liefert beim Ernten &6Industriehanffasern&r, während der untere weiterwächst.",
              "",
              "Acht Fasern um einen Stock ergeben &6Robustes Gewebe&r. Daraus werden die &6Windmühlensegel&r, die deine Windmühle deutlich schneller machen, sowie Sprungkissen und Ballons.",
          ],
          tasks=[task_item("immersiveengineering:seed", 4), task_item("immersiveengineering:hemp_fiber", 16)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["welcome"], icon="immersiveengineering:hemp_fiber"),

    quest("ores", 2.5, 3.8, "&7Erze von Immersive Engineering",
          subtitle="Bauxit, Blei, Silber, Nickel, Uran.",
          description=[
              "Immersive Engineering bringt eigene Erze mit. Wo du sie findest:",
              "&6Bauxit&r (wird zu Aluminium) zwischen Y 32 und Y 112.",
              "&6Blei&r zwischen Y -32 und Y 80.",
              "&6Silber&r zwischen Y -48 und Y 32.",
              "&6Nickel&r unterhalb von Y 24, tief unten am häufigsten.",
              "&6Uran&r zwischen Y -64 und Y -16.",
              "",
              "Für diese Stufe zählen vor allem &6Silber&r und &6Nickel&r (für Elektrum und Constantan im Legierungsofen) und &6Blei&r (für den Kondensator). Rohe Erze schmilzt du im Ofen, oder du schickst sie durch die Anreicherungskammer von Mekanism und bekommst mehr heraus.",
          ],
          tasks=[task_item("immersiveengineering:ingot_lead", 4), task_item("immersiveengineering:ingot_silver", 4), task_item("immersiveengineering:ingot_nickel", 4)],
          rewards=[reward_item("minecraft:raw_iron", 16), reward_xp(5)],
          deps=["welcome"], icon="immersiveengineering:raw_silver"),

    # ---- Koks und Kreosot ----------------------------------------------------
    quest("cokebrick", 6, 0, "&6Koksziegel",
          subtitle="Siebenundzwanzig Stück, ein Ofen.",
          description=[
              "Der Koksofen besteht aus &627 Koksziegeln&r. &eRezept:&r vier Ton in die Ecken, vier Ziegel an die Seiten und ein Sandsteinblock in die Mitte, das ergibt drei Koksziegel.",
              "",
              "Für einen ganzen Ofen sind das neun Rezepte: &636 Ton&r, &636 Ziegel&r und &69 Sandstein&r. Ton findest du in Flüssen und Sümpfen, Ziegel brennst du im Ofen aus Ton.",
          ],
          tasks=[task_item("immersiveengineering:cokebrick", 27)],
          rewards=[reward_item("minecraft:clay_ball", 32), reward_item("minecraft:sandstone", 8)],
          deps=["hammer"]),

    quest("coke_oven", 8.5, 0, "&8&lKoksofen",
          subtitle="Reinheit durch Hitze.",
          description=[
              "Stell die 27 Koksziegel als &e3x3x3-Würfel&r auf und schlag mit dem Hammer auf die Mitte einer Seite. Aus dem Würfel wird der &6Koksofen&r.",
              "",
              "Der Ofen verkohlt Brennstoff unter Luftabschluss. &6Kohle&r wird zu &6Koks für Kohle&r, Holzstämme zu Holzkohle, Kohleblöcke zu Koksblöcken. Dabei entsteht &bKreosotöl&r, das sich im Tank des Ofens sammelt.",
              "",
              "Er arbeitet langsam, aber in Chargen: bis zu &e16 Kohle&r oder 8 Stämme auf einmal. Ein Durchgang dauert einige Minuten, deshalb lohnen sich zwei oder drei Öfen nebeneinander.",
              "",
              "&eAutomatisierung:&r Trichter und Förderbänder können Kohle hineinlegen und Koks herausholen. Das Kreosot gibt der Ofen nicht von selbst ab, dafür brauchst du später eine Pumpe oder einen Eimer im Fenster.",
          ],
          tasks=[task_advancement("immersiveengineering:main/mb_cokeoven", "Einen Koksofen formen")],
          rewards=[reward_item("minecraft:coal", 32), reward_table("s2_common"), reward_xp(10)],
          deps=["cokebrick"], icon="immersiveengineering:cokebrick", size=1.75, shape="hexagon"),

    quest("coal_coke", 11, -1, "&8Koks für Kohle",
          subtitle="Heißer als Kohle, und er macht Stahl.",
          description=[
              "&6Koks für Kohle&r, meist einfach Koks genannt, ist reiner Kohlenstoff. Im Ofen brennt er doppelt so lange wie Kohle, und im Hochofen ist er der Brennstoff für &6Stahl&r: Ein Koks reicht für genau einen Stahlbarren.",
              "",
              "Fang früh an, Koks auf Vorrat zu machen. Jede Kohle, die du findest, ist ein künftiger Stahlbarren.",
              "",
              tex("material_coal_coke"),
          ],
          tasks=[task_item("immersiveengineering:coal_coke", 32)],
          rewards=[reward_item("minecraft:coal_block", 8)],
          deps=["coke_oven"]),

    quest("coke_block", 11, -2.8, "&8Koksblock",
          subtitle="Neun Koks, platzsparend.",
          description=[
              "Neun Koks ergeben einen &6Koksblock&r, der auch als Brennstoff zehnmal so lange hält wie ein einzelner Koks. Praktisch für Öfen, die lange unbeaufsichtigt laufen sollen.",
              "",
              "Der Koksofen kann auch direkt Kohleblöcke zu Koksblöcken verarbeiten, das spart dir das Umpacken.",
          ],
          tasks=[task_item("immersiveengineering:coke", 4)],
          rewards=[reward_item("minecraft:coal", 16)],
          deps=["coal_coke"], icon="immersiveengineering:coke", optional=True),

    quest("creosote", 11, 1, "&bKreosotöl",
          subtitle="Das Nebenprodukt, das alles zusammenhält.",
          description=[
              "Im Fenster des Koksofens gibt es einen Platz für einen &6leeren Eimer&r. Leg einen hinein und nimm unten einen &6Kreosotöleimer&r wieder heraus.",
              "",
              "Kreosotöl ist ein Holzschutzmittel. Daraus wird &6Behandeltes Holz&r, und das steckt in fast allem, was dieser Mod baut: Windmühlen, Wasserräder, Werkbänke, Pfosten und Gerüste.",
              "",
              "&eTipp:&r Leer den Tank regelmäßig, damit immer Platz für neues Kreosot ist. Ein Ofen, der ohne Pause läuft, füllt viele Eimer.",
          ],
          tasks=[task_item("immersiveengineering:creosote_bucket", 1)],
          rewards=[reward_item("minecraft:bucket", 2)],
          deps=["coke_oven"]),

    quest("treated_wood", 13.5, 1, "&6Behandeltes Holz",
          subtitle="Bretter, die nicht faulen.",
          description=[
              "Acht beliebige &6Holzbretter&r um einen &6Kreosotöleimer&r ergeben acht &6Behandelte Holzbretter&r. Den Eimer bekommst du leer zurück.",
              "",
              "Ein Eimer reicht also für acht Bretter. Für eine Windmühle, ein paar Pfosten und eine Werkbank brauchst du schnell drei oder vier Eimer, lass den Koksofen also laufen.",
          ],
          tasks=[task_item("immersiveengineering:treated_wood_horizontal", 32)],
          rewards=[reward_item("minecraft:oak_planks", 32)],
          deps=["creosote"], icon="immersiveengineering:treated_wood_horizontal"),

    quest("sticks", 16, 1, "&6Behandelte Stöcke",
          subtitle="Für Pfosten, Blätter und Griffe.",
          description=[
              "Zwei Behandelte Holzbretter übereinander ergeben vier &6Behandelte Stöcke&r.",
              "",
              "Aus ihnen und Behandeltem Holz entstehen die &6Windmühlenblätter&r und die &6Wasserradsegmente&r, außerdem die Holzpfosten, an die du später deine Drahtanschlüsse hängst.",
              "",
              tex("material_stick_treated"),
          ],
          tasks=[task_item("immersiveengineering:stick_treated", 16)],
          rewards=[reward_item("minecraft:stick", 32)],
          deps=["treated_wood"]),

    quest("workbench", 13.5, 2.8, "&6Ingenieurswerkbank",
          subtitle="Eine Werkbank, die nichts vergisst.",
          description=[
              "Drei behandelte Holzstufen, Behandelte Stöcke und eine normale Werkbank ergeben die &6Ingenieurswerkbank&r.",
              "",
              "Sie behält die Zutaten im Raster, wenn du sie schließt, und hat eine kleine Schublade für Bauteile. Ideal für alles, was du immer wieder herstellst, zum Beispiel Bleche oder Drahtspulen.",
          ],
          tasks=[task_item("immersiveengineering:craftingtable", 1)],
          rewards=[reward_item("immersiveengineering:treated_wood_horizontal", 16)],
          deps=["treated_wood"], optional=True),

    # ---- Stahl ---------------------------------------------------------------
    quest("blastbrick", 19, -1, "&cSprengziegel",
          subtitle="Der Nether steckt in jedem Stein.",
          description=[
              "Der Hochofen braucht &627 Sprengziegel&r, und die gibt es nur mit Zutaten aus dem &cNether&r. &eRezept:&r vier &6Netherziegel&r in die Ecken, vier normale &6Ziegel&r an die Seiten und ein &6Magmablock&r in die Mitte, das ergibt drei Sprengziegel.",
              "",
              "Für einen ganzen Hochofen: &636 Netherziegel&r (Netherrack im Ofen schmelzen), &636 Ziegel&r und &69 Magmablöcke&r. Magmablöcke liegen im Nether an Lavaseen und in Basaltdeltas, oder du baust sie aus vier Magmacreme.",
              "",
              "Wie du sicher in den Nether kommst, steht im Nether-Kapitel.",
          ],
          tasks=[task_item("immersiveengineering:blastbrick", 27)],
          rewards=[reward_item("minecraft:magma_block", 4), reward_item("minecraft:brick", 16)],
          deps=["coal_coke"]),

    quest("blast_furnace", 21.5, -1, "&c&lRoh-Hochofen",
          subtitle="Eisen hinein, Stahl heraus.",
          description=[
              "Stell die Sprengziegel wie beim Koksofen als &e3x3x3-Würfel&r auf und schlag mit dem Hammer auf die Mitte einer Seite.",
              "",
              "&eSo läuft er:&r Oben links kommt &6Eisen&r hinein, darunter der Brennstoff. Jeder Stahlbarren braucht &eeine Minute&r und verbrennt dabei &6einen Koks&r. Holzkohle geht auch, brennt aber nur ein Viertel so lange, du brauchst also vier pro Barren.",
              "",
              "Neben dem Stahl entsteht &6Schlacke&r. Nimm sie heraus, sonst läuft der Ausgang voll und der Ofen bleibt stehen.",
              "",
              "&cWichtig:&r Der Roh-Hochofen lässt sich &cnicht automatisieren&r. Trichter und Förderbänder funktionieren hier nicht, alles läuft über das Fenster. Mehrere Öfen nebeneinander sind der einfachste Weg zu mehr Stahl.",
          ],
          tasks=[task_advancement("immersiveengineering:main/mb_blastfurnace", "Einen Roh-Hochofen formen")],
          rewards=[reward_item("immersiveengineering:coal_coke", 16), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["blastbrick"], icon="immersiveengineering:blastbrick", size=1.75, shape="hexagon"),

    quest("steel", 24, -1, "&8&lStahl",
          subtitle="Die ersten Barren.",
          description=[
              "Lass den Hochofen laufen. Ein Barren pro Minute klingt nach wenig, aber ein voller Stapel Eisen und Koks ist in gut einer Stunde fertig, ohne dass du daneben stehen musst.",
              "",
              "Immersive-Stahl und Mekanism-Stahl sind derselbe &6Stahlbarren&r. Du kannst sie in jedem Rezept beider Mods tauschen.",
              "",
              tex("metal_ingot_steel"),
          ],
          tasks=[task_item("immersiveengineering:ingot_steel", 16)],
          rewards=[reward_item("minecraft:iron_ingot", 32)],
          deps=["blast_furnace"], icon="immersiveengineering:ingot_steel", size=1.5),

    quest("slag", 24, 1, "&7Schlacke",
          subtitle="Abfall mit Nutzen.",
          description=[
              "Die &6Schlacke&r aus dem Hochofen ist kein Müll. Im Ofen geschmolzen wird sie zu &6Schlackeglas&r, als Kies zu Baumaterial, und später wird sie ein Bestandteil von Beton und Industriedünger.",
              "",
              "Heb sie in einer Kiste auf, statt sie in die Lava zu werfen.",
          ],
          tasks=[task_item("immersiveengineering:slag", 16)],
          rewards=[reward_xp(5)],
          deps=["steel"], optional=True),

    quest("improved", 21.5, 1.2, "&cVerbesserter Hochofen",
          subtitle="Stahl, der von selbst läuft.",
          description=[
              "Der &6Verbesserte Hochofen&r ist der automatisierbare Bruder des Roh-Hochofens. Er wird aus &627 Verstärkten Sprengziegeln&r gebaut (je ein Sprengziegel und ein Stahlblech), ist vier Blöcke hoch und hat oben einen Trichter für Eisen und Koks.",
              "",
              "Stahl kommt vorne heraus, Schlacke hinten, beides auch direkt in Kisten oder auf Förderbänder. An die Seiten passen bis zu zwei &6Hochofen-Vorwärmer&r, die mit Strom (je 32 Flux pro Tick) heiße Luft einblasen und den Ofen deutlich schneller machen.",
              "",
              "Die genaue Form zeigt dir das Handbuch. Für den Anfang reicht der Ofen auch ohne Vorwärmer.",
          ],
          tasks=[task_item("immersiveengineering:blastbrick_reinforced", 27)],
          rewards=[reward_item("immersiveengineering:ingot_steel", 8), reward_xp(10)],
          deps=["steel"], icon="immersiveengineering:blastbrick_reinforced", optional=True),

    quest("engineer", 27, 0, "&6&lEin echter Ingenieur",
          subtitle="Stahl im Stapel.",
          description=[
              "Das Obelisk-Ziel für &eStufe 3&r verlangt tausende Stahlbarren, und Stahl aus dem Hochofen zählt genauso wie Stahl aus Mekanism. Zwei, drei Hochöfen, die jetzt schon laufen, machen das Ziel später sehr viel entspannter.",
              "",
              "&eTipp:&r Stell eine Kiste neben den Obelisken. Was du hineinlegst oder per Förderband hineinschickst, wird dir gutgeschrieben.",
              "",
              "Wenn du hier angekommen bist, beherrschst du die Grundlagen: Multiblöcke, Koks, Kreosot, Legierungen und Stahl. Weiter geht es im Abschnitt &eWind und Draht&r mit deinem ersten Stromnetz.",
          ],
          tasks=[task_item("immersiveengineering:ingot_steel", 64)],
          rewards=[reward_table("s2_rare"), reward_item("immersiveengineering:coal_coke", 32), reward_xp(20)],
          deps=["steel"], icon="immersiveengineering:storage_steel", size=2.5, shape="gear"),

    quest("steel_tools", 27, 2.6, "&7Stahlwerkzeug",
          subtitle="Robuster als Eisen.",
          description=[
              "Mit Stahl und Behandelten Stöcken baust du &6Stahlwerkzeuge&r, mit Stahlblechen und Behandeltem Holz rund um einen normalen Schild das &6Schwere Schild&r.",
              "",
              "Stahlwerkzeuge halten deutlich länger als Eisen. Für die langen Grabungen nach Nickel und Silber genau das Richtige.",
              "",
              tex("tool_pickaxe_steel"),
          ],
          tasks=[task_item("immersiveengineering:pickaxe_steel", 1)],
          rewards=[reward_item("immersiveengineering:ingot_steel", 4)],
          deps=["engineer"], optional=True),

    # ---- Legierungen ---------------------------------------------------------
    quest("kilnbrick", 6, 6.5, "&6Legierungsziegel",
          subtitle="Acht Stück reichen.",
          description=[
              "Zwei &6Sandsteinblöcke&r und zwei &6Ziegel&r über Kreuz ergeben zwei &6Legierungsziegel&r. Für den Legierungsofen brauchst du nur acht.",
              "",
              "Der Legierungsofen ist klein und billig, und er ist die einfachste Art, zwei Metalle zu verschmelzen.",
          ],
          tasks=[task_item("immersiveengineering:alloybrick", 8)],
          rewards=[reward_item("minecraft:sandstone", 8)],
          deps=["hammer"]),

    quest("kiln", 8.5, 6.5, "&6&lLegierungsofen",
          subtitle="Zwei Metalle, ein Barren.",
          description=[
              "Stell die acht Legierungsziegel als &e2x2x2-Würfel&r auf und schlag mit dem Hammer auf einen der Blöcke.",
              "",
              "Im Fenster legst du die beiden Metalle in die zwei Eingänge und darunter einen &6Brennstoff&r wie Kohle oder Koks. Das Ergebnis erscheint rechts.",
              "",
              "&eWas er kann:&r Kupfer und Zink zu Messing, Gold und Silber zu Elektrum, Kupfer und Nickel zu Constantan, drei Kupfer und ein Zinn zu vier Bronze. Außerdem macht er Isolierglas für spätere Hochspannungsleitungen.",
          ],
          tasks=[task_checkmark("Legierungsofen gebaut und geformt")],
          rewards=[reward_item("minecraft:coal", 32), reward_xp(5)],
          deps=["kilnbrick"], icon="immersiveengineering:alloybrick", size=1.75, shape="hexagon"),

    quest("brass", 11, 6.5, "&6Messing ohne Mixer",
          subtitle="Für das Stufenziel zählt jeder Barren.",
          description=[
              "Ein &6Kupferbarren&r und ein &6Zinkbarren&r ergeben im Legierungsofen &6zwei Messingbarren&r. Das ist dasselbe Messing, das Create im beheizten Mixer macht.",
              "",
              "&eKronwerke:&r Das Obelisk-Ziel dieser Stufe verlangt tausende &6Messingbarren&r. Der Mixer mit Lohenbrenner ist auf Dauer schneller, aber ein paar Legierungsöfen sind eine gute Ergänzung, solange die Create-Straße noch wächst.",
          ],
          tasks=[task_item("create:brass_ingot", 16)],
          rewards=[reward_item("create:zinc_ingot", 16), reward_item("minecraft:copper_ingot", 16)],
          deps=["kiln"], icon="create:brass_ingot"),

    quest("bronze", 13.5, 6.5, "&6Bronze",
          subtitle="Drei Kupfer, ein Zinn.",
          description=[
              "Drei &6Kupferbarren&r und ein &6Zinnbarren&r ergeben im Legierungsofen &6vier Bronzebarren&r. Zinn bringt Mekanism mit, du findest es beim Graben in der Oberwelt.",
              "",
              "Bronze ist der Grundstoff für den Werkzeugsatz aus Mekanism Tools und steckt in einigen Rezepten anderer Mods.",
          ],
          tasks=[task_item("mekanism:ingot_bronze", 8)],
          rewards=[reward_item("minecraft:copper_ingot", 16)],
          deps=["brass"], icon="mekanism:ingot_bronze", optional=True),

    quest("electrum", 11, 4.6, "&eElektrum",
          subtitle="Gold und Silber, ein guter Leiter.",
          description=[
              "Ein &6Goldbarren&r und ein &6Silberbarren&r ergeben zwei &6Elektrumbarren&r.",
              "",
              "Elektrum ist das Metall der Mittelspannung: Aus Elektrumblechen werden die MV-Drähte, die viermal so viel Strom tragen wie Kupfer. Leg dir einen kleinen Vorrat an.",
              "",
              tex("metal_ingot_electrum"),
          ],
          tasks=[task_item("immersiveengineering:ingot_electrum", 4)],
          rewards=[reward_item("minecraft:gold_ingot", 8)],
          deps=["kiln"]),

    quest("constantan", 11, 8.4, "&6Constantan",
          subtitle="Kupfer und Nickel.",
          description=[
              "Ein &6Kupferbarren&r und ein &6Nickelbarren&r ergeben zwei &6Constantanbarren&r.",
              "",
              "Constantan ist ein Thermoelement: Aus ihm wird später der Thermoelektrische Generator, der Strom aus dem Temperaturunterschied zwischen heißen und kalten Blöcken macht.",
              "",
              tex("metal_ingot_constantan"),
          ],
          tasks=[task_item("immersiveengineering:ingot_constantan", 4)],
          rewards=[reward_item("minecraft:copper_ingot", 8)],
          deps=["kiln"]),

    # ---- Wind und Draht ------------------------------------------------------
    quest("component", 6, 12, "&7Mechanische Eisenkomponente",
          subtitle="Zahnräder und Wellen in einem Teil.",
          description=[
              "Vier &6Eisenbleche&r um einen &6Kupferbarren&r ergeben eine &6Mechanische Eisenkomponente&r.",
              "",
              "Sie steckt im Kinetischen Dynamo und in fast jeder größeren Maschine, die noch kommt. Mach gleich ein paar mehr.",
              "",
              tex("material_component_iron"),
          ],
          tasks=[task_item("immersiveengineering:component_iron", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 16)],
          deps=["plates"]),

    quest("wire", 6, 14, "&6Kupferkabel",
          subtitle="Ein Blech, fein geschnitten.",
          description=[
              "Ein &6Kupferblech&r und der &6Kabelschneider&r ergeben ein &6Kupferkabel&r.",
              "",
              "Vier Kupferkabel um einen Stock werden zu vier &6LV-Drahtspulen&r. Das ist der Draht, den du später zwischen deine Anschlüsse spannst.",
              "",
              tex("material_wire_copper"),
          ],
          tasks=[task_item("immersiveengineering:wire_copper", 8)],
          rewards=[reward_item("minecraft:copper_ingot", 16)],
          deps=["wirecutter"]),

    quest("wirecoil", 8.5, 14, "&6LV-Drahtspule",
          subtitle="Niederspannung zum Aufhängen.",
          description=[
              "Vier Kupferkabel um einen Stock ergeben vier &6LV-Drahtspulen&r.",
              "",
              "Mit einer Spule in der Hand klickst du erst auf einen Anschluss, dann auf den nächsten, und der Draht hängt dazwischen. Ein einzelnes Stück darf höchstens &e16 Blöcke&r lang sein, und kein Block darf im Weg sein.",
              "",
              tex("wirecoil_copper"),
          ],
          tasks=[task_item("immersiveengineering:wirecoil_copper", 8)],
          rewards=[reward_item("minecraft:stick", 16)],
          deps=["wire"]),

    quest("coil_lv", 11, 14, "&6Kupferspulenblock",
          subtitle="Das Innere des Generators.",
          description=[
              "Acht &6LV-Drahtspulen&r um einen &6Eisenbarren&r ergeben einen &6Kupferspulenblock&r.",
              "",
              "Er ist das Herz des &6Kinetischen Dynamos&r, der Drehung in Strom verwandelt.",
          ],
          tasks=[task_item("immersiveengineering:coil_lv", 1)],
          rewards=[reward_item("immersiveengineering:wirecoil_copper", 4)],
          deps=["wirecoil"]),

    quest("dynamo", 13.5, 13, "&e&lKinetischer Dynamo",
          subtitle="Drehung wird zu Strom.",
          description=[
              "Zwei Redstone, eine Mechanische Eisenkomponente, zwei Eisenbarren und der Kupferspulenblock ergeben den &6Kinetischen Dynamo&r.",
              "",
              "Der Dynamo nimmt nur die Drehung einer &6Windmühle&r oder eines &6Wasserrads&r von Immersive Engineering an. Wellen und Wasserräder von Create kann er nicht nutzen.",
              "",
              "&eReihenfolge:&r Stell &ezuerst den Dynamo&r auf und setz die Windmühle oder das Wasserrad danach direkt an seine Wellenseite. Anders herum verbinden sie sich nicht.",
              "",
              "Wie viel Strom herauskommt, hängt allein davon ab, wie schnell sich die Windmühle oder das Rad dreht. Den Strom holst du zum Beispiel über einen LV-Anschluss direkt auf dem Dynamo ab.",
          ],
          tasks=[task_item("immersiveengineering:dynamo", 1)],
          rewards=[reward_item("minecraft:redstone", 16), reward_table("s2_common")],
          deps=["component", "coil_lv"], icon="immersiveengineering:dynamo", size=1.5, shape="hexagon"),

    quest("windmill", 16, 13, "&b&lWindmühle",
          subtitle="Strom aus der Luft.",
          description=[
              "Ein &6Windmühlenblatt&r entsteht aus drei Behandelten Holzbrettern und vier Behandelten Stöcken. Acht Blätter um einen Eisenbarren ergeben die &6Windmühle&r.",
              "",
              "&eAufstellen:&r Setz die Windmühle an die Wellenseite des Dynamos. Sie ist riesig und dreht sich nur, wenn vor ihr viel freier Raum ist. Jeder Block im Weg bremst sie stark. Hoch oben an einem Turm oder über dem Meer läuft sie am besten, bei Regen und Gewitter sogar schneller.",
              "",
              "&eTipp:&r Mit &6Windmühlensegeln&r (siehe Nebenquest) dreht sie sich deutlich schneller und liefert mehr Strom.",
              "",
              tex("material_windmill_blade"),
          ],
          tasks=[task_item("immersiveengineering:windmill", 1)],
          rewards=[reward_item("immersiveengineering:treated_wood_horizontal", 16), reward_item("immersiveengineering:stick_treated", 16), reward_xp(10)],
          deps=["dynamo"], icon="immersiveengineering:windmill", size=1.75, shape="gear"),

    quest("sails", 16, 11, "&bWindmühlensegel",
          subtitle="Mehr Fläche, mehr Wind.",
          description=[
              "Sechs Stück &6Robustes Gewebe&r ergeben ein &6Windmühlensegel&r. Rechtsklick mit dem Segel auf die Windmühle spannt es auf ein Blatt.",
              "",
              "Jedes Segel vergrößert die Fläche und damit Drehzahl und Leistung. Hier zahlt sich der Hanf aus den Grundlagen aus.",
              "",
              tex("material_windmill_sail"),
          ],
          tasks=[task_item("immersiveengineering:windmill_sail", 4)],
          rewards=[reward_item("immersiveengineering:hemp_fiber", 16)],
          deps=["windmill"], optional=True),

    quest("watermill", 16, 15.2, "&9Wasserrad",
          subtitle="Gleichmäßig, Tag und Nacht.",
          description=[
              "Vier &6Wasserradsegmente&r (Behandeltes Holz und Behandelte Stöcke) um einen &6Stahlbarren&r ergeben das &6Wasserrad&r von Immersive Engineering.",
              "",
              "Es dreht sich umso schneller, je mehr fließendes Wasser um das Rad herum läuft. Bis zu drei Räder hintereinander können eine gemeinsame Welle antreiben. Anders als die Windmühle hängt es nicht vom Wetter ab.",
              "",
              tex("material_waterwheel_segment"),
          ],
          tasks=[task_item("immersiveengineering:watermill", 1)],
          rewards=[reward_item("immersiveengineering:ingot_steel", 4)],
          deps=["dynamo"], optional=True),

    quest("connectors", 18.5, 13, "&cAnschlüsse und Relais",
          subtitle="Strom an Pfosten, quer durch die Basis.",
          description=[
              "Drei Kupferbarren und vier &6Terrakotta&r ergeben vier &6LV-Kabelanschlüsse&r. Zwei Kupfer und zwei Terrakotta ergeben acht &6LV-Kabelrelais&r.",
              "",
              "&eAnschlüsse&r sitzen auf Maschinen und Generatoren und nehmen Strom auf oder geben ihn ab, jeder bis zu 256 Flux pro Tick. &eRelais&r geben nichts ab, sie sind nur Knotenpunkte, an denen sich Drähte verzweigen.",
              "",
              "&cAchtung:&r Ein Kupferdraht trägt höchstens 2.048 Flux pro Tick. Hängen zu viele Anschlüsse an einem einzigen Draht, brennt er durch. Nicht isolierte Drähte verletzen außerdem jeden, der sie berührt.",
              "",
              "Den Strom von Immersive Engineering kannst du auch in Maschinen anderer Mods einspeisen, er entspricht FE.",
          ],
          tasks=[task_item("immersiveengineering:connector_lv", 4), task_item("immersiveengineering:connector_lv_relay", 4),
                 task_advancement("immersiveengineering:main/connect_wire", "Einen Draht spannen")],
          rewards=[reward_item("minecraft:terracotta", 16), reward_item("immersiveengineering:wirecoil_copper", 8)],
          deps=["windmill"], icon="immersiveengineering:connector_lv"),

    quest("capacitor", 21, 13, "&c&lLV-Kondensator",
          subtitle="Strom für windstille Tage.",
          description=[
              "Der &6LV-Kondensator&r speichert &e100.000 Flux&r und nimmt oder gibt je Seite bis zu 256 Flux pro Tick.",
              "",
              "&eRezept:&r oben zwei Kupferbarren mit einem &6Redstone-Säureeimer&r dazwischen, unten zwei &6Bleibleche&r um einen &6Basic Engineering Block&r. Die Säure mischst du an der Werkbank aus vier Redstone und einem Wassereimer, den Block aus Eisen und Behandeltem Holz.",
              "",
              "&eSeiten einstellen:&r Rechtsklick mit dem Hammer auf eine Seite schaltet zwischen &9blau&r (Eingang), &6orange&r (Ausgang) und aus. Schleichend einstellen ändert die gegenüberliegende Seite.",
              "",
              "Stell ihn zwischen Dynamo und Maschinen, dann laufen deine Maschinen auch, wenn der Wind gerade einschläft.",
          ],
          tasks=[task_item("immersiveengineering:capacitor_lv", 1)],
          rewards=[reward_table("s2_uncommon"), reward_xp(15)],
          deps=["connectors"], icon="immersiveengineering:capacitor_lv", size=1.5, shape="hexagon"),

    quest("voltmeter", 21, 15, "&7Ingenieursvoltmeter",
          subtitle="Wie viel ist noch drin?",
          description=[
              "Ein Kompass, ein Kupferbarren und zwei Stöcke ergeben das &6Voltmeter&r. Rechtsklick auf einen Speicher zeigt dir, wie viel Strom darin ist.",
              "",
              "Schleichend auf zwei Anschlüsse geklickt berechnet es, wie viel Strom auf dem Weg dazwischen verloren geht. Lange Kupferleitungen verlieren nämlich ein wenig pro Strecke.",
              "",
              tex("tool_voltmeter"),
          ],
          tasks=[task_item("immersiveengineering:voltmeter", 1)],
          rewards=[reward_item("minecraft:copper_ingot", 8)],
          deps=["connectors"], optional=True),
]

images = [
    banner("immersive/title", "Immersive Engineering", 13, -5, height=1.5, kind="title", colour="brass"),
    banner("immersive/basics", "Grundlagen", 1.2, 1.8, height=0.9, colour="stone"),
    banner("immersive/coke", "Koks und Kreosot", 7.2, -2.3, height=0.9, colour="brass"),
    banner("immersive/steel", "Stahl", 22.5, -2.8, height=0.9, colour="fire"),
    banner("immersive/alloys", "Legierungen", 8, 3.3, height=0.9, colour="brass"),
    banner("immersive/power", "Wind und Draht", 10, 10.4, height=0.9, colour="water"),
]

chapter(C, "Immersive Engineering", "immersiveengineering:hammer", "tech", quests, shape="square", order=14, stage=2,
        subtitle=["Stufe 2: Koksofen, Behandeltes Holz, Legierungen, Stahl und die ersten Drähte."],
        images=images)
