"""Iron's Spells 'n Spellbooks in stage 1: mana and the first spell books, scrolls and ink from
loot, the inscription table, the scroll forge with the school focuses, blank runestones, the
wandering magician and wizard armour, the school armour, the graybeard staff, the overworld
mages and their structures (pyromancer tower, mountain tower, evoker fort, mangrove hut, ice
spider den, catacombs, Dead King) and a checklist of the common spells per school. On Kronwerke
the ink decides the stage (tools/stages/spec.py): common ink is open, uncommon and rare ink, the
gold spell book, the arcane anvil and upgrade orbs come in stage 2, epic ink in 3, legendary in 4.
Those are only named, never asked for. Facts come from the mod jar (recipes, loot tables, spell
classes, guide book)."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_advancement, task_kill,
                  reward_item, reward_table, reward_xp, banner, img, item_texture)

C = "irons_spells"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Mana und das erste Buch ----------------------------------------------
    quest("welcome", 0, 1, "&5&lIron's Spells 'n Spellbooks",
          subtitle="Zauber, die du findest statt baust.",
          description=[
              "Bau zuerst das &6Flimsy Journal&r: links oben und unten je ein &6Kupferbarren&r, links in der Mitte ein &6Faden&r, rechts zwei Spalten &6Papier&r (6 Stück). Es hat &e5 Zauberplätze&r.",
              "",
              "&5Iron's Spells&r ist der zweite Zaubermod von Kronwerke. Anders als bei Ars Nouveau setzt du hier nichts zusammen: Du findest fertige Zauber als &6Schriftrollen&r in Kisten und bei Magiern und schreibst sie in dein Buch. Dafür gibt es Türme, Festungen und Katakomben mit eigenen Gegnern.",
              "",
              pic("irons_spellbooks:copper_spell_book"),
              "",
              "&eKronwerke:&r Die &6Tinte&r bestimmt die Stufe. Mit &fCommon Ink&r (jetzt) schmiedest du gewöhnliche Zauber. &aUncommon&r und &9Rare Ink&r kommen in Stufe 2, &5Epic Ink&r in Stufe 3, &6Legendary Ink&r in Stufe 4. Gesperrte Tinte kannst du aufheben, aber nicht benutzen.",
          ],
          tasks=[task_item("irons_spellbooks:copper_spell_book", 1)],
          rewards=[reward_item("irons_spellbooks:common_ink", 1), reward_table("s1_common")],
          icon="irons_spellbooks:copper_spell_book", size=2.0, shape="hexagon"),

    quest("equip", 2.5, 0, "&dLeg das Buch an",
          subtitle="Buch in den Slot, R zum Zaubern, V fürs Rad.",
          description=[
              "Öffne dein Inventar und leg das Zauberbuch in den &6Zauberbuch-Slot&r neben der Rüstung (Curios). Zaubern: &eStrg+V&r wirkt den gewählten Zauber, &eR&r gedrückt halten öffnet das Zauberrad, &eAlt + Mausrad&r wechselt den Zauber.",
              "",
              "Dein &bMana&r siehst du als blaue Leiste bei der Hotbar. Du startest mit &e100 Mana&r. Alle halbe Sekunde kommt &e1 Prozent&r deines Maximums zurück, bei 100 Mana also 2 pro Sekunde, eine volle Leiste in 50 Sekunden.",
              "",
              "Mehr Maximum heißt deshalb auch schnellere Regeneration. Rüstung und bessere Bücher bringen Mana, siehe unten. &eKronwerke:&r Die Herkunft &6Quellgeborene&r (Neo Origins) gibt dir von Anfang an &e+50 Mana&r in Iron's Spells und ebenso in Ars Nouveau.",
          ],
          tasks=[task_advancement("irons_spellbooks:irons_spellbooks/spell_book_equip", "Ein Zauberbuch anlegen")],
          rewards=[reward_item("minecraft:paper", 8), reward_xp(5)],
          deps=["welcome"], icon="irons_spellbooks:copper_spell_book"),

    quest("iron_book", 2.5, 2, "&7Binde das Ironbound Tome",
          subtitle="Ketten und Leder, ein Platz mehr.",
          description=[
              "Drei &6Ketten&r in die linke Spalte, rechts oben und unten je zwei &6Leder&r, in der Mitte zwei &6Papier&r. Das &6Ironbound Tome&r hat &e6 Plätze&r. Eine Kette ist Eisenklumpen, Eisenbarren, Eisenklumpen übereinander.",
              "",
              "Zum Umziehen holst du die Rollen am Inscription Table aus dem alten Buch und schreibst sie ins neue.",
              "",
              "&cAusblick:&r Das goldene &6Apprentice's Spell Book&r (8 Plätze, +50 Mana, 15 Prozent kürzere Zauberzeit) braucht Hogskin aus dem Nether und kommt in Stufe 2. Das &6Enchanted Spell Book&r (10 Plätze, +100 Mana) und der &6Ancient Codex&r (12 Plätze, +200 Mana) kommen in Stufe 3, das Dragonskin-Buch in Stufe 4.",
          ],
          tasks=[task_item("irons_spellbooks:iron_spell_book", 1)],
          rewards=[reward_item("minecraft:leather", 8), reward_table("s1_common")],
          deps=["welcome"], icon="irons_spellbooks:iron_spell_book"),

    quest("rotten_book", 5, 2, "&2Finde ein Rotten Spell Book",
          subtitle="Alt, modrig, und besser als alles aus Stufe 1.",
          description=[
              "Durchsuch &6Verliese, Minenschächte, Wüstentempel, Außenposten, Herrenhäuser und Ruinenportale&r. In jeder dieser Kisten liegt mit 1 Prozent Chance ein &6Rotten Spell Book&r, in den Sarkophagen der Katakomben mit 15 Prozent.",
              "",
              pic("irons_spellbooks:rotten_spell_book"),
              "",
              "Es hat &e8 Plätze&r und &e+100 Mana&r, mehr als jedes Buch, das du in Stufe 1 bauen kannst. Dafür nimmst du 15 Prozent mehr Schaden durch Zauber.",
              "",
              "&eTipp:&r Ein Rotten Spell Book, eine Honigflasche, eine Sporenblüte, ein Amethysthaufen, ein Leucht-Tintenbeutel und zwei Arcane Cloth ergeben das &6Druidic Tome&r mit 10 Plätzen und 10 Prozent mehr Naturzauberkraft.",
          ],
          tasks=[task_item("irons_spellbooks:rotten_spell_book", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["iron_book"], icon="irons_spellbooks:rotten_spell_book", optional=True),

    # ---- Schriftrollen und Tinte ------------------------------------------------
    quest("scroll", 7.5, 0, "&eFinde eine Schriftrolle",
          subtitle="Jede Rolle ist ein Zauber mit Stufe.",
          description=[
              "Eine &6Schriftrolle&r trägt einen Zauber mit einer Stufe, wie ein verzaubertes Buch. Rechtsklick wirkt ihn sofort, ohne Mana und ohne Abklingzeit, aber die Rolle ist danach weg. Besser: einschreiben, nächste Quests.",
              "",
              pic("irons_spellbooks:scroll"),
              "",
              "&eWo:&r In Kisten von Verliesen, Minenschächten, Tempeln, Außenposten, Schiffswracks, Ruinenportalen, Herrenhäusern und Dorfkirchen liegt oft eine Rolle. Die &6Bibliothek einer Festung&r hat immer 3 bis 5. Jeder Magier dieses Mods lässt eine fallen, und der Fahrende Händler verkauft welche gegen Smaragde.",
              "",
              "Der Tooltip zeigt Schule, Stufe, Seltenheit, Manakosten und Abklingzeit. Rollen über &fGewöhnlich&r heb auf: Was du jetzt nicht schmieden kannst, ist in Stufe 2 Gold wert.",
          ],
          tasks=[task_item("irons_spellbooks:scroll", 1)],
          rewards=[reward_item("irons_spellbooks:common_ink", 1), reward_xp(3)],
          deps=["equip"], icon="irons_spellbooks:scroll"),

    quest("ink", 7.5, 2, "&fSammle Common Ink",
          subtitle="Aus Kisten, von Magiern oder von der Werkbank.",
          description=[
              "&eRezept auf Kronwerke:&r Eine &6Glasflasche&r, ein &6Tintenbeutel&r und ein &6Quelljuwel&r von Ars Nouveau formlos ergeben eine &6Common Ink&r.",
              "",
              "Sie liegt außerdem in denselben Kisten wie die Rollen (10 Prozent pro Kiste, zwei Versuche), in Festungsbibliotheken fast immer, und jeder &6Magier&r lässt 1 bis 3 Fläschchen fallen. Der Fahrende Händler verkauft sie gegen Smaragde.",
              "",
              pic("irons_spellbooks:common_ink"),
              "",
              "Jeder Zauber hat Stufen, meist 5 bis 10. Die unteren 30 Prozent davon sind &fgewöhnlich&r, dann folgen 25 Prozent &aungewöhnlich&r, 20 Prozent &9selten&r, 15 Prozent &5episch&r und 10 Prozent &6legendär&r. Die Tinte bestimmt, welche Seltenheit du in der Scroll Forge schmieden darfst.",
              "",
              "&eKronwerke:&r Uncommon und Rare Ink (Stufe 2), Epic Ink (Stufe 3) und Legendary Ink (Stufe 4) findest du jetzt schon. Sammle sie in einer Kiste, sie sind später sofort nützlich.",
          ],
          tasks=[task_item("irons_spellbooks:common_ink", 1)],
          rewards=[reward_item("irons_spellbooks:common_ink", 2), reward_item("minecraft:paper", 16)],
          deps=["scroll"], icon="irons_spellbooks:common_ink"),

    quest("inscription", 10, 1, "&6&lBau einen Inscription Table",
          subtitle="Hier kommt die Rolle ins Buch.",
          description=[
              "Ein &6Buch&r oben in die Mitte, darunter drei &6Archwood-Stufen&r aus Ars Nouveau, unten links und in der Mitte je ein &6Holzzaun&r.",
              "",
              "&eSo geht es:&r Rechtsklick auf den Tisch. Links kommt dein &6Zauberbuch&r hinein, daneben die &6Schriftrolle&r. Wähl rechts einen freien Platz und drück &eInscribe&r. Der Zauber ist jetzt im Buch, so oft du willst.",
              "",
              "Klickst du einen belegten Platz an, bekommst du die Rolle zurück und der Platz wird frei. Du verlierst also nie einen Zauber, nur Zeit.",
          ],
          tasks=[task_item("irons_spellbooks:inscription_table", 1)],
          rewards=[reward_item("irons_spellbooks:common_ink", 2), reward_table("s1_common")],
          deps=["scroll"], icon="irons_spellbooks:inscription_table", size=1.75, shape="hexagon"),

    quest("cast", 12.5, 1, "&dWirke deinen ersten Zauber",
          subtitle="Buch an, Zauber wählen, Strg+V.",
          description=[
              "Buch anlegen, mit &eAlt + Mausrad&r oder im Zauberrad (&eR&r halten) den Zauber wählen, &eStrg+V&r drücken. Fertig.",
              "",
              "Der Tooltip jeder Rolle nennt die Art des Zaubers. &eInstant&r wirkt sofort. &eLong Cast&r und &eCharge&r brauchen eine Aufladezeit, in der du Strg+V hältst. Zauber mit &eHold&r in der Beschreibung (Fire Breath, Cone of Cold, Electrocute) laufen, solange du Strg+V hältst, und kosten Mana pro Sekunde.",
              "",
              "&eTipp:&r Vier gewöhnliche Zauber decken alles ab: ein Angriff (Magic Missile, Firebolt, Icicle), eine Flucht (Burning Dash, Volt Strike), ein Schutz (Shield, Oakskin) und eine Heilung (Healing Circle, Blessing of Life).",
          ],
          tasks=[task_checkmark("Ersten Zauber gewirkt")],
          rewards=[reward_item("irons_spellbooks:common_ink", 3), reward_xp(10)],
          deps=["inscription"], icon="irons_spellbooks:scroll"),

    # ---- Schmiede und Schulen ---------------------------------------------------
    quest("scroll_forge", 15.5, 1, "&3&lBau eine Scroll Forge",
          subtitle="Tinte, Papier, Fokus: der Zauber, den du willst.",
          description=[
              "Oben drei &6Polierter Tiefenschiefer&r, in der Mitte links ein &6Weinender Obsidian&r, unten drei weitere (4 insgesamt). Weinenden Obsidian findest du an Ruinenportalen in der Oberwelt.",
              "",
              "&eSo geht es:&r Rechtsklick, dann &6Tinte&r, &6Papier&r und einen &6Fokus&r hinein. Der Fokus bestimmt die Schule, die Tinte die Seltenheit. Rechts erscheinen alle Zauber der Schule, die diese Tinte erlaubt. Einen anklicken, bestätigen, die Rolle hat die niedrigste Stufe dieser Seltenheit.",
              "",
              "Mit Common Ink bekommst du jeden Zauber, dessen niedrigste Stufe gewöhnlich ist. Welche das sind, steht im Abschnitt &eGewöhnliche Zauber&r. Ab Stufe 2 hebt der Arcane Anvil die Rollen dann mit besserer Tinte höher.",
          ],
          tasks=[task_item("irons_spellbooks:scroll_forge", 1)],
          rewards=[reward_item("minecraft:paper", 32), reward_table("s1_uncommon"), reward_xp(10)],
          deps=["cast"], icon="irons_spellbooks:scroll_forge", size=1.75, shape="gear"),

    quest("focuses", 18, 1, "&aSammle die Fokusse",
          subtitle="Ein Gegenstand pro Schule.",
          description=[
              "Jede Schule hat einen Fokus: &6Smaragd&r für Evocation, &6Enderperle&r für Ender, &6Giftige Kartoffel&r für Nature (acht Kartoffeln um eine giftige ergeben vier), &6Divine Pearl&r für Holy (Goldbarren und Amethystscherbe formlos) und &6Frozen Bone&r für Ice.",
              "",
              pic("irons_spellbooks:frozen_bone"),
              "",
              "&6Frozen Bones&r lassen Strays fallen, die Skelette der Schneegebiete, 0 bis 3 pro Stück und mit Plünderung mehr. Im Mountain Tower und im Ice Spider Den liegen auch welche. Eine Frozen Bone ergibt 3 Knochenmehl, also nicht alles verfüttern.",
              "",
              "&6Blood Vial&r für Blood: Stell einen Kessel auf ein Lagerfeuer und setz ein Tier hinein, es wird zu Blut gekocht. &6Bottle o' Lightning&r für Lightning: Rechtsklick mit einer leeren Glasflasche auf einen &egeladenen Creeper&r.",
              "",
              "&cFeuer&r braucht eine &6Lohenrute&r aus dem Nether und kommt in Stufe 2. Feuerrollen aus Kisten kannst du trotzdem schon lesen. &5Eldritch&r braucht Echo-Scherben und ein zusammengesetztes Manuskript, alle seine Zauber sind legendär: Stufe 4.",
          ],
          tasks=[task_item("minecraft:emerald", 1), task_item("minecraft:ender_pearl", 1),
                 task_item("minecraft:poisonous_potato", 1), task_item("irons_spellbooks:divine_pearl", 1),
                 task_item("irons_spellbooks:frozen_bone", 3)],
          rewards=[reward_item("irons_spellbooks:frozen_bone", 5), reward_item("minecraft:emerald", 4), reward_xp(5)],
          deps=["scroll_forge"], icon="irons_spellbooks:divine_pearl"),

    quest("runes", 20.5, 1, "&5Finde einen Blank Runestone",
          subtitle="Acht Fokusse drumherum, eine Rune der Schule.",
          description=[
              "&6Blank Runestones&r gibt es nur als Beute: 4 Prozent in normalen Kisten, 30 Prozent in Festungsbibliotheken, 60 Prozent im Keller des Ice Spider Den. Magier lassen keine fallen, der Archevoker aber zur Hälfte eine fertige Evocation Rune.",
              "",
              pic("irons_spellbooks:blank_rune"),
              "",
              "Acht Fokusse um einen Runenstein ergeben die &6Rune&r der Schule: acht Frozen Bones die Ice Rune, acht Smaragde die Evocation Rune, acht Enderperlen die Ender Rune. Acht &6Arcane Essence&r ergeben die Arcane Rune, acht Kugelfische die Protective Rune, acht Phantomhäute die Recovery Rune.",
              "",
              "Ein &6Shriving Stone&r (Roheisen und Amethystscherbe, formlos) macht aus jeder Rune wieder einen leeren Stein. Runen brauchst du für die Schulrüstung unten und ab Stufe 2 für Upgrade-Kugeln.",
          ],
          tasks=[task_item("irons_spellbooks:blank_rune", 1)],
          rewards=[reward_item("irons_spellbooks:blank_rune", 1), reward_xp(10)],
          deps=["focuses"], icon="irons_spellbooks:blank_rune"),

    quest("anvil", 23, 1, "&cAusblick: Arcane Anvil",
          subtitle="Rollen aufwerten, Rüstung verbessern, Waffen verzaubern.",
          description=[
              "Der &6Arcane Anvil&r (drei Amethystblöcke, ein Diamant, ein Amboss zwischen zwei poliertem Tiefenschiefer) ist auf Kronwerke bis &6Stufe 2&r gesperrt, genau wie Uncommon und Rare Ink.",
              "",
              "&eWas er kann:&r Eine Rolle plus die Tinte der nächsthöheren Seltenheit hebt den Zauber eine Stufe. Ein Zauberbuch oder ein Rüstungsteil plus &6Upgrade Orb&r bekommt bis zu &e3 Upgrades&r (Mana, Abklingzeit, Schutz oder die Zauberkraft einer Schule). Ein Schwert plus Rolle wird zur Zauberwaffe.",
              "",
              "Die Kugeln brauchen &6Mithril&r (Oberwelt unter Y -38, nur mit Netheritspitzhacke) und &6Cinder Essence&r von Ancient Knights im Nether. Die Sorte entsteht aus einer leeren Kugel und acht Runen. Sammle Runen und Mithrilerz also schon jetzt.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["runes"], icon="minecraft:amethyst_block", optional=True),

    # ---- Ruestung und Stab -----------------------------------------------------
    quest("essence", 0, 7, "&d&lSammle Arcane Essence",
          subtitle="Der Rohstoff für alles.",
          description=[
              "&6Arcane Essence&r ist der Rohstoff dieses Mods: Rüstung, Stab, Runen, alles braucht sie. Magier lassen 0 bis 8 fallen, Eisspinnen 4 bis 16, der Tote König 28 bis 45. In Kisten liegen 1 bis 10, in den Türmen oft mehr.",
              "",
              pic("irons_spellbooks:arcane_essence"),
              "",
              "Du brauchst viel: eine Arcane Cloth kostet 8, die Zaubererrobe 64. Leg von Anfang an eine Kiste dafür an.",
              "",
              "&eTipp:&r Acht Essenzen um einen Eisen-, Kupfer- oder Goldbarren ergeben einen &6Arcane Ingot&r. Den brauchst du für Ringe und Zauberwaffen, aber erst später. Erst Rüstung, dann Barren.",
          ],
          tasks=[task_item("irons_spellbooks:arcane_essence", 16)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 16), reward_table("s1_common")],
          deps=["welcome"], icon="irons_spellbooks:arcane_essence", size=1.5, shape="hexagon"),

    quest("wandering", 2.5, 6, "&6Näh die Wanderer-Robe",
          subtitle="Leder und eine Essenz, 25 Mana pro Teil.",
          description=[
              "Ein &6Lederrüstungsteil&r und eine &6Arcane Essence&r formlos ergeben das passende Stück der &6Wandering Magician&r-Rüstung. Vier Essenzen für den ganzen Satz.",
              "",
              pic("irons_spellbooks:wandering_magician_chestplate"),
              "",
              "Jedes Teil gibt &e+25 Mana&r, der Satz also +100, bei Schutz wie Eisenrüstung (2, 6, 5, 2). Die billigste Verdopplung deines Manas, die es gibt.",
              "",
              "&eKronwerke:&r Quellgeborene dürfen sie tragen. Ihr Verbot gilt nur für Eisen-, Gold-, Diamant- und Netheritrüstung.",
          ],
          tasks=[task_item("irons_spellbooks:wandering_magician_chestplate", 1)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 8), reward_item("minecraft:leather", 8)],
          deps=["essence"], icon="irons_spellbooks:wandering_magician_chestplate"),

    quest("staff", 2.5, 8, "&7Schnitz den Graybeard Staff",
          subtitle="Ein Stock, der Zauber wirkt.",
          description=[
              "&6Arcane Essence&r oben, &6Holzschaufel&r in der Mitte, &6Eisenbarren&r unten ergeben den &6Graybeard Staff&r.",
              "",
              pic("irons_spellbooks:graybeard_staff"),
              "",
              "Ein Stab ist ein Zauberwerkzeug: Rechtsklick wirkt deinen aktiven Zauber. Dazu gibt er &e+10 Prozent Zauberkraft&r und &e+25 Prozent Manaregeneration&r, in der Haupthand wie in der Nebenhand.",
              "",
              "Der &6Artificer Cane&r (Karmesinbretter, Gold, Amethyst) braucht Holz aus dem Nether: Stufe 2. Der &6Ice Staff&r setzt sich aus Teilen zusammen, die in der Welt verstreut sind; der Cryomancer weiß mehr.",
          ],
          tasks=[task_item("irons_spellbooks:graybeard_staff", 1)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 4), reward_xp(5)],
          deps=["essence"], icon="irons_spellbooks:graybeard_staff"),

    quest("cloth", 5, 7, "&dWebe Arcane Cloth",
          subtitle="Acht Essenzen um eine Wolle.",
          description=[
              "Acht &6Arcane Essence&r um einen Block &6Wolle&r (jede Farbe) ergeben eine &6Arcane Cloth&r.",
              "",
              pic("irons_spellbooks:magic_cloth"),
              "",
              "Aus dem Stoff entsteht die Zaubererrüstung: 5 für Hut oder Kapuze, 8 für die Robe, 7 für die Hose, 4 für die Schuhe. Ein ganzer Satz sind 24 Stoff, also 192 Essenzen. Fang mit dem Hut an.",
          ],
          tasks=[task_item("irons_spellbooks:magic_cloth", 2)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 16), reward_item("minecraft:white_wool", 8)],
          deps=["essence"], icon="irons_spellbooks:magic_cloth"),

    quest("wizard", 7.5, 7, "&5&lSetz den Zaubererhut auf",
          subtitle="125 Mana und 5 Prozent Zauberkraft pro Teil.",
          description=[
              "Zwei &6Arcane Cloth&r übereinander in der Mitte und drei unten ergeben den &6Wizard Hat&r. Drei oben und zwei darunter links ergeben die &6Wizard Hood&r, dieselben Werte, anderer Look.",
              "",
              img("irons_spellbooks:textures/item/wizard_helmet_hat.png", 32, 32),
              "",
              "Jedes Teil der &6Wizard&r-Rüstung gibt &e+125 Mana&r und &e+5 Prozent Zauberkraft&r, der Satz also +500 Mana und +20 Prozent, bei Schutz wie Diamant (3, 8, 6, 3). Robe, Hose und Schuhe folgen dem Lederrüstungsmuster, nur aus Stoff.",
              "",
              "&eTipp:&r Die Rüstung lässt sich färben wie Leder. Und sie ist die Grundlage für die Schulrüstung in der nächsten Quest.",
          ],
          tasks=[task_item("irons_spellbooks:wizard_hat", 1)],
          rewards=[reward_item("irons_spellbooks:magic_cloth", 4), reward_table("s1_uncommon")],
          deps=["cloth"], icon="irons_spellbooks:wizard_hat", size=1.5, shape="hexagon"),

    quest("school_armor", 10, 7, "&bSchmiede Schulrüstung",
          subtitle="Wizard-Teil, Rune, Essenz.",
          description=[
              "Ein &6Wizard&r-Rüstungsteil, eine &6Rune&r und eine &6Arcane Essence&r formlos (oder am Schmiedetisch mit der Rune als Vorlage) ergeben das Teil der Schule: Ice Rune für den &bCryomancer&r, Evocation Rune für den &aArchevoker&r, Ender Rune für den &5Shadowwalker&r, Holy Rune für den &ePriest&r.",
              "",
              pic("irons_spellbooks:cryomancer_chestplate"),
              "",
              "Jedes Teil gibt &e+125 Mana&r, &e+10 Prozent Zauberkraft seiner Schule&r und &e+5 Prozent allgemein&r, Schutz wie Diamant. Wer eine Schule spielt, trägt vier Teile davon.",
              "",
              "In Stufe 1 gehen Ice, Evocation, Ender, Nature, Lightning, Blood und Holy. Der &cPyromancer&r braucht die Fire Rune aus Lohenruten: Stufe 2. Jedes Teil kostet eine Rune, also acht Fokusse und einen Runenstein.",
          ],
          tasks=[task_checkmark("Ein Teil Schulrüstung geschmiedet")],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["wizard"], icon="irons_spellbooks:cryomancer_chestplate", optional=True),

    # ---- Magier und Tuerme -----------------------------------------------------
    quest("pyromancer", 0, 11, "&c&lStürm den Pyromancer Tower",
          subtitle="Der erste Magier, und der häufigste.",
          description=[
              "Der &6Pyromancer Tower&r steht in Hügeln, Wäldern, Ebenen und Sümpfen. Oben wohnt der &cPyromancer&r und wirft mit Feuerzaubern. Nimm Wasser oder einen Trank der Feuerresistenz mit und bleib in Bewegung.",
              "",
              "&eBeute:&r 0 bis 8 &6Arcane Essence&r, eine &6Schriftrolle&r und 1 bis 3 &6Tinten&r, meist Common oder Uncommon, mit Glück Rare oder Epic. Die Kisten im Turm: Essenz, Papier, Tinte, Rollen und &6Lohenruten&r, die bis Stufe 2 gesperrt sind. Heb sie trotzdem auf.",
              "",
              "&cAchtung:&r Wer eine Kiste in der Nähe eines Magiers plündert, macht ihn wütend. Erst der Magier, dann die Kisten.",
          ],
          tasks=[task_kill("irons_spellbooks:pyromancer", 1)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 8), reward_table("s1_common")],
          deps=["essence"], icon="irons_spellbooks:pyromancer_helmet", size=1.5, shape="hexagon"),

    quest("archevoker", 2.5, 11, "&aNimm das Evoker Fort",
          subtitle="Plünderer, Evoker und ihr Anführer.",
          description=[
              "Das &6Evoker Fort&r steht in Hügeln, Wäldern, Ebenen, Wüsten und Savannen, besetzt mit Plünderern, Evokern und &6Magehunter Vindicators&r. Ganz oben wartet der &aArchevoker&r.",
              "",
              "&eBeute:&r 0 bis 8 &6Arcane Essence&r, eine Rolle, 1 bis 3 Tinten, zu 50 Prozent eine &6Evocation Rune&r (nur wenn du ihn selbst tötest) und mit Glück den &6Grimoire of Evokation&r, ein einzigartiges Buch mit festen Zaubern, das auch normale Evoker fallen lassen können.",
              "",
              "In den Wachtürmen liegen Armbrüste, Pfeile und Ziegenhörner. Für Essenz ist das Fort weniger ergiebig als die Türme, für Runen umso mehr.",
          ],
          tasks=[task_kill("irons_spellbooks:archevoker", 1)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 8), reward_item("minecraft:emerald", 8)],
          deps=["pyromancer"], icon="irons_spellbooks:evocation_rune"),

    quest("catacombs", 5, 11, "&8Steig in die Katakomben",
          subtitle="Unter der Erde, zwischen Y -40 und Y 20.",
          description=[
              "Die &6Katakomben&r liegen unter Hügeln, Wäldern, Ebenen, Sümpfen, Wüsten, Savannen, Taigas, Dschungeln und Tropfsteinhöhlen, also fast überall, zwischen &eY -40 und Y 20&r. Beim Höhlen stößt du irgendwann auf ihre Gänge.",
              "",
              "Drin: &6Catacombs Zombies&r, Skelette und &5Necromancer&r, die Untote rufen. Der Necromancer lässt 0 bis 4 Essenz und manchmal eine Rolle fallen, die Rolle nur, wenn du ihn selbst tötest.",
              "",
              "&eBeute:&r Sarkophage mit 1 bis 2 Rollen, 5 bis 16 Essenz und zu 15 Prozent einem Rotten Spell Book. Mauerkisten mit Rollen, Runensteinen und Ringen. Der &6Wayward Compass&r (Essenz, Eisen, Seelenlaterne) zeigt zu den nächsten Katakomben, die Seelenlaterne gibt es aber erst mit dem Nether in Stufe 2.",
          ],
          tasks=[task_advancement("irons_spellbooks:irons_spellbooks/enter_catacombs", "Die Katakomben betreten")],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["archevoker"], icon="minecraft:skeleton_skull"),

    quest("dead_king", 8, 11, "&4&lWeck den Toten König",
          subtitle="Der Boss der Katakomben.",
          description=[
              "Im Thronsaal der Katakomben sitzt der &6Dead King&r. Ein Rechtsklick oder ein Schlag auf den Leichnam weckt ihn, und dann gibt es kein Zurück. Komm mit Freunden, voller Robe, Heilzaubern und Essen.",
              "",
              "&eBeute:&r &e28 bis 45 Arcane Essence&r (mit Plünderung mehr), für jeden Spieler im Kampf ein &6Bone Key&r, und mit Glück den &6Blood Staff&r oder das &6Necronomicon&r, ein einzigartiges Buch voller dunkler Zauber.",
              "",
              "Der Bone Key öffnet die &6Bone Vaults&r der Katakomben: Ringe, Arcane Cloth, Arcane Ingots, Rollen hoher Stufe, Runensteine, drei Fläschchen seltener Tinte (Rare bis Legendary, für später aufheben), Blood Vials und Splitter seines Phylakteriums, mit denen sich der König später erneut wecken lässt.",
          ],
          tasks=[task_kill("irons_spellbooks:dead_king", 1)],
          rewards=[reward_table("s1_rare"), reward_item("irons_spellbooks:arcane_essence", 32), reward_xp(25)],
          deps=["catacombs"], icon="minecraft:skeleton_skull", size=2.0, shape="gear"),

    quest("cryomancer", 0, 13.5, "&bErklimm den Mountain Tower",
          subtitle="Eis, Amethyst und eine Karte.",
          description=[
              "Der &6Mountain Tower&r steht in Bergen, Schneeebenen, Schneetaigas, Hainen und Eiszapfenbiomen. Oben wohnt der &bCryomancer&r. Seine Eiszauber frieren dich ein, also bleib in Bewegung und bring Heilung mit.",
              "",
              "&eBeute:&r 0 bis 8 &6Arcane Essence&r, eine Rolle, 1 bis 3 Tinten. Die Turmkisten haben Essenz, Papier, Amethystscherben und viele &6Frozen Bones&r, 1 bis 2 Rollen und zu 30 Prozent eine &6Furled Map&r, die dich zu einem Bauwerk führt. Im Eisfass liegen zwei Rollen und oft ein Ring.",
              "",
              "&eTipp:&r Hier bekommst du Frozen Bones für die Ice Rune, ohne Strays zu jagen.",
          ],
          tasks=[task_kill("irons_spellbooks:cryomancer", 1)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 8), reward_item("irons_spellbooks:frozen_bone", 8)],
          deps=["pyromancer"], icon="irons_spellbooks:cryomancer_helmet"),

    quest("ice_spider", 2.5, 13.5, "&bRäum das Ice Spider Den",
          subtitle="Vier bis sechzehn Essenzen pro Spinne.",
          description=[
              "Das &6Ice Spider Den&r liegt in Schnee- und Eisbiomen, aber nicht im Gebirge und nicht im Ozean. Bei Schneewetter patrouillieren &bEisspinnen&r auch draußen. Jede lässt &e4 bis 16 Arcane Essence&r und 2 bis 5 Fäden fallen, manchmal einen &6Icy Fang&r.",
              "",
              "&eBeute:&r Im Keller zu 60 Prozent ein &6Blank Runestone&r und immer 10 bis 30 Essenz, dazu Frozen Bones, Eis, Spinnweben und manchmal ein Ring. Im Turm Rollen und weitere 5 bis 20 Essenz, im Verlies Tinte oder eine Rolle.",
              "",
              "Für Essenz ist kein Ort in Stufe 1 ergiebiger. Nimm Fackeln und einen Schild mit, die Spinnen kommen in Gruppen.",
          ],
          tasks=[task_kill("irons_spellbooks:ice_spider", 3)],
          rewards=[reward_item("irons_spellbooks:arcane_essence", 12), reward_item("minecraft:string", 16)],
          deps=["cryomancer"], icon="irons_spellbooks:icy_fang", optional=True),

    quest("apothecarist", 5, 13.5, "&2Besuch die Mangrove Hut",
          subtitle="Tränke, Elixiere und ein Magier im Sumpf.",
          description=[
              "In Sümpfen und Mangrovensümpfen steht die &6Mangrove Hut&r, die Hütte des &2Apothecarist&r. Er ist ein Magier wie die anderen: 0 bis 8 &6Arcane Essence&r, eine Rolle, 1 bis 3 Tinten.",
              "",
              "&eBeute:&r Sein Versteck hat 15 Mal je 2 Smaragde oder 2 Essenz, 3 bis 5 Tränke oder &6Elixiere&r (Oakskin, Evasion, Invisibility, Greater Healing) und 2 bis 5 &6Netherward Tinctures&r. Die schützen mitgebrachte Hoglins und Piglins vor der Zombifizierung, wichtig ab Stufe 2.",
              "",
              "Der &6Alchemist Cauldron&r, in dem man Elixiere braut und Rollen zu Tinte recycelt, braucht Cinder Essence aus dem Nether: Stufe 2.",
          ],
          tasks=[task_kill("irons_spellbooks:apothecarist", 1)],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["pyromancer"], icon="irons_spellbooks:oakskin_elixir", optional=True),

    # ---- Gewoehnliche Zauber (Checkliste) ------------------------------------------
    quest("schools", 13.5, 7, "&d&lLerne die Schulen kennen",
          subtitle="Neun Schulen, acht davon jetzt.",
          description=[
              "Jeder Zauber gehört zu einer &dSchule&r. Die Schule bestimmt den Fokus in der Scroll Forge, die Rune für die Rüstung und welche Zauberkraft ihn stärker macht.",
              "",
              "&cFeuer&r: Schaden und Brand. &bEis&r: Schaden und Kontrolle. &eBlitz&r: gebündelter Schaden. &fHeilig&r: Heilen und Stärken. &5Ender&r: Arkanes, von Schaden bis Bewegung. &4Blut&r: Schaden, der dich heilt. &aEvocation&r: Illager-Tricks und Beschwörung. &2Natur&r: Gift und Schwächung. &8Eldritch&r: vergessene Magie, erst in Stufe 4.",
              "",
              "Die acht Quests rechts sind eine Checkliste: eine pro Schule, mit allen Zaubern, die du mit Common Ink schmieden kannst, und dem, was in späteren Stufen dazukommt. Hak ab, was du gewirkt hast.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_item("irons_spellbooks:common_ink", 1), reward_xp(5)],
          deps=["cast"], icon="irons_spellbooks:arcane_rune"),

    quest("spells_fire", 15.5, 4.3, "&cWirke einen Feuerzauber",
          subtitle="Firebolt, Fire Breath, Blaze Storm und mehr.",
          description=[
              "&cFeuer&r heißt Schaden und Brand. Gewöhnlich: &6Firebolt&r (kleines Feuergeschoss), &6Fire Breath&r (halten: Feuerkegel), &6Blaze Storm&r (halten: Salve Feuerbälle), &6Burning Dash&r (Sprint nach vorn in Flammen).",
              "&6Flaming Strike&r (Nahkampfhieb, skaliert mit der Waffe), &6Heat Surge&r (Feuerstoß um dich, senkt Rüstung), &6Wall of Fire&r (Feuerwand zwischen Ankerpunkten, hält Geschosse auf).",
              "",
              "Zum Schmieden fehlt in Stufe 1 die Lohenrute. Feuerrollen aus Kisten gehen trotzdem.",
              "",
              "&cStufe 2:&r Magma Bomb, Scorch, Fire Arrow, Fireball, Flaming Barrage. &cStufe 4:&r Raise Hell.",
          ],
          tasks=[task_checkmark("Feuerzauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="minecraft:fire_charge"),

    quest("spells_ice", 18, 4.3, "&bWirke einen Eiszauber",
          subtitle="Icicle, Ray of Frost, Cone of Cold und mehr.",
          description=[
              "&bEis&r heißt Schaden und Kontrolle: Getroffene werden langsam und frieren ein. Gewöhnlich: &6Icicle&r (durchschlagender Eisbolzen), &6Ray of Frost&r (Strahl, friert sofort), &6Cone of Cold&r (halten: Kältekegel), &6Ice Spikes&r (Linie aus Eiskristallen aus dem Boden), &6Frostwave&r (Frostwelle um dich).",
              "",
              "Fokus: Frozen Bone, in Stufe 1 komplett machbar.",
              "",
              "&cStufe 2:&r Ice Tomb, Snowball, Blizzard, Frost Step, Ice Block, Summon Polar Bear. &cStufe 3:&r Frostbite.",
          ],
          tasks=[task_checkmark("Eiszauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="irons_spellbooks:ice_rune"),

    quest("spells_lightning", 20.5, 4.3, "&eWirke einen Blitzzauber",
          subtitle="Ball Lightning, Electrocute, Shockwave, Volt Strike.",
          description=[
              "&eBlitz&r heißt gebündelter Schaden. Gewöhnlich: &6Ball Lightning&r (langsame Blitzkugel, prallt von Blöcken ab), &6Electrocute&r (halten: Stromkegel), &6Shockwave&r (Druckwelle um dich), &6Volt Strike&r (Sprung nach vorn mit Blitzschlag beim Aufprall).",
              "",
              "Fokus: Bottle o' Lightning von einem geladenen Creeper.",
              "",
              "&cStufe 2:&r Chain Lightning, Lightning Lance, Thunderstep, Ascension, Charge, Thunderstorm. &cStufe 3:&r Lightning Bolt.",
          ],
          tasks=[task_checkmark("Blitzzauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="irons_spellbooks:lightning_bottle"),

    quest("spells_holy", 23, 4.3, "&fWirke einen Heiligen Zauber",
          subtitle="Heilen, schützen, stärken.",
          description=[
              "&fHeilig&r heißt Heilung und Unterstützung. Gewöhnlich: &6Wisp&r (Lichtgeschoss, sucht Ziele), &6Guiding Bolt&r (Treffer ziehen Geschosse an), &6Blessing of Life&r (heilt ein Ziel), &6Healing Circle&r (Heilkreis am Boden).",
              "&6Cloud of Regeneration&r (halten: heilt Verbündete um dich), &6Fortify&r (Bonusleben für alle um dich), &6Divine Smite&r (Nahkampfhieb, skaliert mit der Waffe).",
              "",
              "Fokus: Divine Pearl aus Gold und Amethyst. Die Schule für alle, die in der Gruppe spielen.",
              "",
              "&cStufe 2:&r Heal, Sunbeam, Greater Heal. &cStufe 3:&r Cleanse, Haste. &cStufe 4:&r Angel Wings.",
          ],
          tasks=[task_checkmark("Heiligen Zauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="irons_spellbooks:divine_pearl"),

    quest("spells_ender", 15.5, 9.7, "&5Wirke einen Enderzauber",
          subtitle="Magic Missile, Shadow Slash, Dragon's Breath.",
          description=[
              "&5Ender&r ist die arkane Schule, von Schaden bis Bewegung. Gewöhnlich: &6Magic Missile&r (Bolzen aus Arkanmagie, der Klassiker), &6Shadow Slash&r (Sprung mit Hieb, lenkt Geschosse ab), &6Dragon's Breath&r (halten: Drachenatemkegel mit Pfützen).",
              "",
              "Fokus: Enderperle. Die guten Bewegungszauber sitzen eine Stufe höher.",
              "",
              "&cStufe 2:&r Teleport, Portal, Recall, Starfall, Counterspell, Magic Arrow, Summon Swords, Summon Ender Chest, Arcane Shackle, Echoing Strikes. &cStufe 3:&r Evasion, Gravity Fissure. &cStufe 4:&r Black Hole.",
          ],
          tasks=[task_checkmark("Enderzauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="minecraft:ender_pearl"),

    quest("spells_evocation", 18, 9.7, "&aWirke einen Beschwörungszauber",
          subtitle="Fangzähne, Schild, Pferd und Feuerwerk.",
          description=[
              "&aEvocation&r ist die Trickkiste der Illager. Gewöhnlich: &6Fang Strike&r (Linie Fangzähne), &6Fang Ward&r (Fangzahnringe um dich), &6Firecracker&r (Feuerwerk explodiert, wo du hinschaust), &6Shield&r (Schildwand, hält Geschosse und Gegner auf), &6Summon Horse&r (Geisterpferd, nur für dich), &6Throw&r (wirft dein Werkzeug als Waffe).",
              "",
              "Fokus: Smaragd. Die Rune dazu lässt der Archevoker fallen.",
              "",
              "&cStufe 2:&r Arrow Volley, Chain Creeper, Lob Creeper, Gust, Spectral Hammer, Invisibility, Scapegoat, Summon Vex. &cStufe 3:&r Fang Swirl, Slow. &cStufe 4:&r Wololo.",
          ],
          tasks=[task_checkmark("Beschwörungszauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="minecraft:emerald"),

    quest("spells_nature", 20.5, 9.7, "&2Wirke einen Naturzauber",
          subtitle="Gift, Säure und Eichenhaut.",
          description=[
              "&2Natur&r heißt Schwächen und Gift. Gewöhnlich: &6Poison Arrow&r (Giftpfeil mit Giftwolke), &6Poison Spray&r (Giftkegel), &6Acid Spit&r (Säurekugel, senkt Rüstung), &6Oakskin&r (weniger Schaden für eine Weile), &6Gluttony&r (Essen wird zu Mana).",
              "",
              "Fokus: Giftige Kartoffel. Oakskin und Gluttony sind die zwei nützlichsten Zauber für jeden, egal welche Schule.",
              "",
              "&cStufe 2:&r Root, Stomp, Earthquake, Firefly Swarm, Poison Splash, Blight, Aspect of the Spider, Touch Dig.",
          ],
          tasks=[task_checkmark("Naturzauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="minecraft:poisonous_potato"),

    quest("spells_blood", 23, 9.7, "&4Wirke einen Blutzauber",
          subtitle="Ray of Siphoning, und sonst erst Stufe 2.",
          description=[
              "&4Blut&r ist die dunkle Schule: Schaden, der dich stärkt. Gewöhnlich ist nur &6Ray of Siphoning&r (halten: Strahl, der Leben raubt und dich um den vollen Schaden heilt).",
              "",
              "Fokus: Blood Vial aus einem Kessel über dem Lagerfeuer mit einem Tier darin. Der Dead King lässt den &6Blood Staff&r dieser Schule fallen.",
              "",
              "&cStufe 2:&r Blood Needles, Blood Step, Devour, Raise Dead, Wither Skull, Acupuncture, Blood Slash, Heartstop, Sacrifice.",
          ],
          tasks=[task_checkmark("Blutzauber gewirkt")],
          rewards=[reward_xp(3)],
          deps=["schools"], icon="irons_spellbooks:blood_vial"),
]

images = [
    banner("irons_spells/title", "Iron's Spells", 11.5, -4.3, height=1.75, kind="title", colour="magic"),
    banner("irons_spells/buch", "Mana und das erste Buch", 2.5, -1.7, height=0.9, colour="magic"),
    banner("irons_spells/rollen", "Schriftrollen und Tinte", 10, -1.7, height=0.9, colour="magic"),
    banner("irons_spells/schmiede", "Schmiede und Schulen", 19.2, -1.7, height=0.9, colour="water"),
    banner("irons_spells/ruestung", "Rüstung und Stab", 4, 4.4, height=0.9, colour="magic"),
    banner("irons_spells/zauber", "Gewöhnliche Zauber", 19.25, 2.9, height=0.9, colour="fire"),
    banner("irons_spells/magier", "Magier und Türme", 4.5, 9.3, height=0.9, colour="stone"),
]

chapter(C, "Iron's Spells 'n Spellbooks", "irons_spellbooks:copper_spell_book", "magic", quests, shape="circle",
        order=48, stage=1,
        subtitle=["Stufe 1: Schriftrollen, gewöhnliche Tinte, der erste Zauberer und die Magier der Oberwelt."],
        images=images)
