"""Checklist: every way to move and store items, fluids, gases and power in the pack, one
line each (mod, block, rate or capacity, filter, stage). Five sections with a short "Was
wann" summary in front of each. Stage 1 blocks are item tasks, everything later is a
checkmark and names its stage; no task, reward or icon uses a locked item. Numbers come
from the server configs (Mekanism tiers.toml, pipez-server.toml, create-server.toml,
immersiveengineering-server.toml, powah.json5, fluxnetworks-server.toml, itemcollectors,
simplemagnets, rangedpumps, waystones) and the conduit data of Ender IO. Details live in
the mod chapters, which the lines point to."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_dimension, task_advancement, reward_item,
                  reward_table, reward_xp, banner)

C = "list_transport"
MINING_ADV = "kronwerke:minenwelt"
FRAME = "kronwerke:grubenrahmen"

# Column and row spacing of the list rows
X0, DX = 2.6, 2.2


def col(i):
    return round(X0 + DX * i, 2)


quests = [
    quest("welcome", 0, -6.5, "&6&lTransport und Lager",
          subtitle="Was Dinge bewegt und wo sie liegen bleiben.",
          description=[
              "Jede Zeile hier ist ein Weg, &6Gegenstände&r, &bFlüssigkeiten&r, &aGase&r oder &dStrom&r zu bewegen oder zu lagern: Mod, Block, Durchsatz oder Fassung, ob es einen Filter gibt und ab welcher Stufe es geht.",
              "",
              "Hak ab, was du gebaut hast. Stufe-1-Zeilen wollen den Block sehen, spätere Zeilen sind ein Haken, sobald du sie kennst. Die Rezepte und Details stehen in den Modkapiteln, auf die jede Zeile zeigt.",
              "",
              "Vor jedem Abschnitt steht ein &eWas wann&r mit den zwei besten Wahlen pro Stufe. Wer nur das liest, baut nichts Falsches.",
          ],
          tasks=[task_checkmark("Los geht es")],
          rewards=[reward_item("minecraft:hopper", 2), reward_table("s1_common")],
          icon="minecraft:hopper", size=2.0, shape="hexagon"),

    # ---- Gegenstände ---------------------------------------------------------
    quest("items_when", 0, 0, "&6&lWas wann: Gegenstände",
          subtitle="Zwei Wahlen pro Stufe.",
          description=[
              "&eStufe 1:&r &6Förderbänder mit Andesit-Trichtern&r für Maschinenstraßen, &6Schubladen mit Lagerkern und Trichter-Upgrade&r für das Lager. Ein zahmer Sternbunkel ersetzt dazwischen jede Menge Rohre.",
              "",
              "&eStufe 2:&r &6Pipez-Rohre&r, weil sie alles verbinden und nichts kosten, und &6Modular Routers&r, sobald du sortieren willst. Mekanism-Transporter nur innerhalb von Mekanism.",
              "",
              "&eStufe 3:&r &6AE2 oder Refined Storage&r als Lager mit Import- und Exportbussen, und &6XNet&r oder &6LaserIO&r für Maschinen, die nicht am Netz hängen sollen. Ender IO ist die schnellste Einzelleitung.",
              "",
              "&eStufe 4:&r Mekanism-Transporter der Elite- und Ultimativ-Stufe und das QIO-Netz, siehe Kapitel Mekanism.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["welcome"], icon="create:andesite_funnel", size=1.75, shape="hexagon"),

    quest("hopper", col(0), -1.8, "Setz einen Trichter",
          subtitle="Vanilla, Trichter: 2,5 Stück pro Sekunde, kein Filter.",
          description=[
              "&6Vanilla&r, &6Trichter&r: zieht aus dem Block darüber und schiebt in den Block vor der Spitze, &e1 Gegenstand alle 8 Ticks&r, 5 Plätze, kein Filter. &eStufe 1.&r",
              "",
              "Fünf Eisenbarren um eine Truhe. Ein Trichter in eine Kiste, aus der ein anderer Trichter zieht, ist der älteste Zwischenspeicher der Welt. Ein Redstone-Signal hält ihn an.",
          ],
          tasks=[task_item("minecraft:hopper", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 5)],
          deps=["items_when"]),

    quest("minecart", col(1), -1.8, "Lass eine Lore fahren",
          subtitle="Vanilla, Trichterlore: holt von Schienen, was darüber liegt.",
          description=[
              "&6Vanilla&r, &6Trichterlore&r: fährt auf Schienen und zieht unterwegs Gegenstände aus Inventaren über der Schiene und vom Boden, 5 Plätze, kein Filter. Ein Trichter unter einer Schiene leert sie im Vorbeifahren. &eStufe 1.&r",
              "",
              "Trichter auf eine Lore. Die &6Truhenlore&r trägt 27 Plätze. Aktivierungsschienen stoppen das Aufsammeln.",
              "",
              "&eStufe 2:&r Create-Züge mit Gleisen, Bahnhöfen und Portable Storage Interfaces, siehe Kapitel Create: Züge.",
          ],
          tasks=[task_item("minecraft:hopper_minecart", 1)],
          rewards=[reward_item("minecraft:rail", 16)],
          deps=["items_when"], icon="minecraft:hopper_minecart"),

    quest("belt", col(2), -1.8, "Spann ein Förderband",
          subtitle="Create, Mechanisches Förderband: so schnell wie die Welle dreht.",
          description=[
              "&6Create&r, &6Mechanisches Förderband&r: Rechtsklick mit dem Band auf zwei Wellen, &e2 bis 20 Blöcke&r lang, waagerecht, schräg oder senkrecht. Trägt Gegenstände und Tiere mit der Drehzahl der Welle. Filter nur über Messing-Trichter und -Tunnel. &eStufe 1.&r",
              "",
              "Sechs getrockneter Seetang ergeben ein Band. Rechtsklick mit leerer Hand nimmt Gegenstände vom Band. Andesit-Gehäuse verkleidet es.",
              "",
              "Das Band ist die Maschinenstraße von Stufe 1: Mühle, Presse, Sägewerk und Lüfter arbeiten direkt darauf. Mehr im Kapitel Create.",
          ],
          tasks=[task_item("create:belt_connector", 2)],
          rewards=[reward_item("create:shaft", 8), reward_xp(3)],
          deps=["items_when"], icon="create:belt_connector"),

    quest("chute", col(3), -1.8, "Bau eine Rutsche",
          subtitle="Create, Rutsche: senkrecht nach unten, mit Lüfter nach oben.",
          description=[
              "&6Create&r, &6Rutsche&r: trägt Gegenstände senkrecht von einem Inventar ins nächste, nach unten von allein, nach oben mit einem Ummantelten Lüfter oben oder unten. Schräg, wenn sie seitlich an eine andere Rutsche gesetzt wird. Kein Filter. &eStufe 1.&r",
              "",
              "Zwei Eisenbleche um einen Eisenbarren ergeben vier. Mit dem Schraubenschlüssel bekommt sie ein Fenster.",
              "",
              "&eStufe 2:&r Die &6Intelligente Rutsche&r (Messingblech, Rutsche, Elektronenröhre) filtert und zählt Stapel.",
          ],
          tasks=[task_item("create:chute", 4)],
          rewards=[reward_item("create:iron_sheet", 4)],
          deps=["items_when"], icon="create:chute"),

    quest("funnel", col(4), -1.8, "Setz Trichter und Tunnel von Create",
          subtitle="Create, Andesit-Trichter: ein Gegenstand pro Vorgang auf und vom Band.",
          description=[
              "&6Create&r, &6Andesit-Trichter&r: zieht einzelne Gegenstände aus Inventaren aufs Band oder vom Band hinein, je nachdem, ob du ihn normal oder schleichend setzt. &6Andesit-Tunnel&r teilen vom Band genau einen Gegenstand pro Stapel zur Seite ab. Kein Filter. &eStufe 1.&r",
              "",
              "Andesitlegierung über getrocknetem Seetang ergibt zwei Trichter. Ein Redstone-Signal hält jeden Trichter an.",
              "",
              "&eStufe 2:&r &6Messing-Trichter&r ziehen ganze Stapel und haben einen Filter, &6Messing-Tunnel&r sortieren und verteilen (Aufteilen, Rundlauf, Nächster zuerst), siehe Kapitel Create: Messing.",
          ],
          tasks=[task_item("create:andesite_funnel", 2)],
          rewards=[reward_item("create:andesite_alloy", 4), reward_xp(3)],
          deps=["items_when"], icon="create:andesite_funnel"),

    quest("packages", col(5), -1.8, "Verschick ein Paket",
          subtitle="Create, Verpacker und Kettenförderer: Gegenstände als Paket mit Adresse.",
          description=[
              "&6Create&r, &6Verpacker&r: packt den Inhalt eines Inventars in &6Pakete&r, die auf Bändern, in Rutschen und an &6Kettenförderern&r reisen. &6Froschports&r an der Kette nehmen Pakete mit ihrer Adresse an. Filter über die Adresse. &eStufe 1.&r",
              "",
              "Verpacker: ein Pappblock in der Mitte, Eisenbarren oben und an den Seiten, Redstone unten. Kettenförderer: ein Großes Zahnrad in vier Andesit-Gehäusen ergibt zwei, verbunden mit Ketten.",
              "",
              "Mit &6Lagerverbindung&r und &6Lagerticker&r bestellst du aus allen angeschlossenen Lagern, und der Verpacker schickt es los. Das Postsystem von Create 6, siehe Kapitel Create.",
          ],
          tasks=[task_item("create:packager", 1)],
          rewards=[reward_item("create:cardboard_package_12x12", 4), reward_table("s1_common")],
          deps=["items_when"], icon="create:packager"),

    quest("starbuncle", col(6), -1.8, "Zähm einen Sternbunkel",
          subtitle="Ars Nouveau, Sternbunkel: trägt Stapel von Truhe zu Truhe.",
          description=[
              "&6Ars Nouveau&r, &6Sternbunkel&r: ein Tier, das Gegenstände vom Boden aufsammelt und Stapel aus beliebig vielen Truhen in beliebig viele andere trägt. Filter über eine Gegenstandsrolle in seiner Hand oder einen Rahmen an der Truhe. &eStufe 1.&r",
              "",
              "Ein Goldnugget an einen wilden Sternbunkel gibt Scherben, die Scherben mit vier Goldbarren im Bezaubernden Apparat den &6Sternbunkel-Charme&r. Einrichten mit dem Dominion-Zauberstab: erst Quelle, dann Tier, dann Ziel.",
              "",
              "Er braucht weder Strom noch Quelle und läuft durch Wände, wenn eine Tür offen ist. Mehr im Kapitel Ars Nouveau.",
          ],
          tasks=[task_item("ars_nouveau:starbuncle_charm", 1)],
          rewards=[reward_item("minecraft:gold_nugget", 18), reward_xp(3)],
          deps=["items_when"], icon="ars_nouveau:starbuncle_charm"),

    quest("hopperhock", col(7), -1.8, "Pflanz eine Trichterblume",
          subtitle="Botania, Hopperhock: sammelt vom Boden in die Truhe daneben.",
          description=[
              "&6Botania&r, &6Hopperhock&r: eine Funktionsblume, die herumliegende Gegenstände in ihrer Nähe aufhebt und in angrenzende Inventare legt. Mana ist freiwillig und vergrößert die Reichweite. Filter über Rahmen an den Truhen. &eStufe 1.&r",
              "",
              "Aus der Blütenapotheke, siehe Kapitel Botania. Mit dem Zauberstab des Waldes im Funktionsmodus wechselst du die Sortierregel.",
              "",
              "Unter einer Mobfalle oder hinter einer Kakteenfarm ersetzt eine Blume den ganzen Trichterboden.",
          ],
          tasks=[task_item("botania:hopperhock", 1)],
          rewards=[reward_item("botania:white_mystical_petal", 4)],
          deps=["items_when"], icon="botania:hopperhock"),

    quest("soph_hopper", col(0), 0, "Steck ein Trichter-Upgrade ins Fass",
          subtitle="Sophisticated Storage, Trichter-Upgrade und Lagerkern: das Lager zieht selbst.",
          description=[
              "&6Sophisticated Storage&r, &6Trichter-Upgrade&r: zieht aus dem Block über der Truhe und schiebt in den darunter, jede Richtung mit eigenem Filter. Der &6Lagerkern&r verteilt alles, was Trichter oder Rohre an ihn liefern, auf den ganzen Truhenverbund. &eStufe 1.&r",
              "",
              "Trichter, zwei Eisenbarren, Upgrade-Basis, drei Redstone. Rezepte und Verbund im Kapitel Lager.",
              "",
              "Dazu von &6Functional Storage&r: &6Puller-&r und &6Pusher-Upgrade&r an einer Schublade bewegen &e4 Gegenstände alle 4 Ticks&r in die Schublade hinein oder aus ihr heraus.",
          ],
          tasks=[task_item("sophisticatedstorage:hopper_upgrade", 1)],
          rewards=[reward_item("minecraft:hopper", 1), reward_xp(3)],
          deps=["items_when"], icon="sophisticatedstorage:hopper_upgrade"),

    quest("collector", col(1), 0, "Stell einen Item Collector auf",
          subtitle="Item Collectors, Basic Collector: saugt im Umkreis von 5 Blöcken ein.",
          description=[
              "&6Item Collectors&r, &6Basic Item Collector&r: sammelt alle Gegenstände im eingestellten Bereich bis &e5 Blöcke&r um sich herum in das Inventar, auf dem er sitzt. Kein Filter. &eStufe 1.&r",
              "",
              "Rezept in JEI, Bereich im Fenster einstellen. Ein Collector auf einer Truhe unter dem Mob-Fall ersetzt alle Wasserströme.",
              "",
              "&eStufe 2:&r Der &6Advanced Item Collector&r reicht &e7 Blöcke&r und hat einen Filter mit Whitelist und Blacklist.",
          ],
          tasks=[task_item("itemcollectors:basic_collector", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 1), reward_xp(3)],
          deps=["items_when"], icon="itemcollectors:basic_collector"),

    quest("magnet", col(2), 0, "Trag einen Magneten",
          subtitle="Simple Magnets, Magnet: zieht Gegenstände und XP zu dir.",
          description=[
              "&6Simple Magnets&r, &6Magnet&r: zieht Gegenstände und Erfahrung bis &e5 Blöcke&r weit zu dir, solange er an ist. Der &6Fortgeschrittene Magnet&r reicht &e3 bis 11 Blöcke&r, einstellbar, mit Filter. Beide &eStufe 1.&r",
              "",
              "Rezepte in JEI. Mit der Taste im Tastenmenü schaltest du ihn an und aus. Eine &6Entmagnetisierungsspule&r hält einen Bereich frei, zum Beispiel über dem Werfer deines Handelsplatzes.",
              "",
              "Dasselbe steckt im &6Magnet-Upgrade&r des Rucksacks, siehe Kapitel Lager.",
          ],
          tasks=[task_item("simplemagnets:basicmagnet", 1)],
          rewards=[reward_item("minecraft:redstone", 8)],
          deps=["items_when"], icon="simplemagnets:basicmagnet"),

    quest("harvester", col(3), 0, "Merk dir den Ernte-Pylon",
          subtitle="Pylons, Harvester Pylon: erntet alle drei Sekunden in die Kiste über ihm. Stufe 2.",
          description=[
              "&6Pylons&r, &6Harvester Pylon&r: erntet und pflanzt im eingestellten Bereich alle &e3 Sekunden&r eine Pflanze neu und legt die Ernte in das Inventar direkt über sich. Braucht eine &6Hacke&r im Pylon, keinen Strom, keinen Filter. &eStufe 2&r, Quarz und Schwarzstein kommen aus dem Nether.",
              "",
              "Rezept in JEI. Den Arbeitsbereich stellst du im Fenster in Blöcken ein. Ohne Inventar darüber steht er still. In Stufe 1 übernimmt das der Trichter-Pflanztopf oder die Create-Erntemaschine.",
              "",
              "Die anderen drei Pylonen (Infusion, Interdiktion, Expulsion) haben mit Gegenständen nichts zu tun.",
          ],
          tasks=[task_checkmark("Gemerkt")],
          rewards=[reward_item("minecraft:wheat_seeds", 16), reward_xp(3)],
          deps=["items_when"], icon="minecraft:hay_block"),

    quest("arm", col(4), 0, "Lies: Mechanischer Arm",
          subtitle="Create, Mechanischer Arm: beliebig viele Ziele in 5 Blöcken.",
          description=[
              "&6Create&r, &6Mechanischer Arm&r: greift aus beliebig vielen Eingängen und legt in beliebig viele Ausgänge im Umkreis von &e5 Blöcken&r, Ziele vor dem Setzen anklicken. Filter nur über Messing-Trichter als Ziel. &eStufe 2.&r",
              "",
              "Messingbleche, Andesitlegierung, Messinggehäuse und ein Präzisionsgetriebe. Verteilt nach Rundlauf, erzwungenem Rundlauf oder dem ersten gewählten Ziel.",
              "",
              "Ein Arm füttert ein Dutzend Mixer aus einem Depot. Siehe Kapitel Create: Messing.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="create:andesite_alloy"),

    quest("pipez_item", col(5), 0, "Lies: Pipez Item-Rohr",
          subtitle="Pipez, Item-Rohr: 4 Stück pro Sekunde, mit Modifikation mehr.",
          description=[
              "&6Pipez&r, &6Item-Rohr&r: &e4 Gegenstände pro Sekunde&r ohne Modifikation, 8 alle 15 Ticks mit der Normalen, 16 alle 10 Ticks mit der Verbesserten. Ein Ende zieht, alle anderen liefern. Filter erst mit der Fortgeschrittenen Modifikation in Stufe 3. &eStufe 2.&r",
              "",
              "Sechs Eisen, zwei Werfer, ein Redstone ergeben 16 Rohre. Schleichen und Schraubenschlüssel stellt ein Ende auf Ziehen.",
              "",
              "Alle vier Pipez-Sorten im Kapitel Rohre und Router. Stufe 3 bringt das Universalrohr, Stufe 4 die Ultimative Modifikation mit 64 Stück pro Tick.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:dropper"),

    quest("routers", col(6), 0, "Lies: Modular Routers",
          subtitle="Modular Routers, Router: ein Block, neun Module, jeder Takt ein Stapel.",
          description=[
              "&6Modular Routers&r, &6Router&r: ein Puffer von einem Stapel, neun Module (Ziehen, Senden bis 24 Blöcke durch Wände, Saugen, Vernichten, Abbauen, Setzen), alle 20 Ticks ein Durchlauf, mit Upgrades alle 2 Ticks und 64 Stück. Neun Filterplätze je Modul, der Massenfilter 54. &eStufe 2.&r",
              "",
              "&eRezept auf Kronwerke:&r Vier Andesitlegierungen, vier Eisengitter und ein Leeres Modul ergeben vier Router. Siehe Kapitel Rohre und Router, dort steht auch die Sortieranlage.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:iron_bars"),

    quest("mek_transporter", col(7), 0, "Lies: Logistiktransporter",
          subtitle="Mekanism, Logistiktransporter: 2 Stück pro Sekunde, Sortierer als Filter.",
          description=[
              "&6Mekanism&r, &6Einfacher Logistiktransporter&r: &e2 Gegenstände pro Sekunde&r mit 1 Meter pro Sekunde. Fortgeschritten (Stufe 3) 32 pro Sekunde, Elite 64, Ultimativ 128 pro Sekunde (Stufe 4). Farben trennen Stränge, der &6Logistische Sortierer&r filtert. &eStufe 2.&r",
              "",
              "Zwei Stahlbarren und ein Schaltkreis ergeben acht. Zieht nur, wenn eine Seite mit dem Konfigurator auf Ziehen steht oder die Maschine Auto-Auswurf hat. Siehe Kapitel Mekanism.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:iron_ingot"),

    quest("ie_conveyor", col(0), 1.8, "Lies: IE-Förderbänder",
          subtitle="Immersive Engineering, Förderband: läuft ohne Antrieb.",
          description=[
              "&6Immersive Engineering&r, &6Förderband&r: bewegt Gegenstände und Tiere ganz ohne Antrieb und schiebt sie am Ende in ein Inventar. Varianten: &6Extrahierend&r (zieht wie ein Trichter), &6Senkrecht&r, &6Fallend&r, &6Teilend&r, &6Redstone-gesteuert&r und &6Abgedeckt&r. Kein Filter. &eStufe 2.&r",
              "",
              "Rezepte in JEI, Richtung und Steigung mit dem Ingenieurshammer. Farbstoff färbt die Seitenwände. Siehe Kapitel Immersive Engineering.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:leather"),

    quest("pnc_logistics", col(1), 1.8, "Lies: Logistikmodule und Drohnen",
          subtitle="PneumaticCraft, Logistikmodul: bewegt mit Druckluft, Drohnen fliegen.",
          description=[
              "&6PneumaticCraft&r, &6Logistikmodul&r auf einem Druckrohr: holt und liefert zwischen Inventaren mit &6Logistikrahmen&r (Anbieter, Anforderer, Lager) und braucht dafür Luftdruck aus dem Rohr. Filter in jedem Rahmen. &eStufe 2.&r",
              "",
              "&eStufe 3:&r Die &6Logistikdrohne&r macht dasselbe fliegend in einem Bereich von &e31 x 31 x 31&r Blöcken, die programmierbare &6Drohne&r alles, was du ihr beibringst. &eRezept auf Kronwerke:&r Jede Drohne braucht ein Präzisionsgetriebe von Create.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:glass_bottle"),

    quest("enderio_item", col(2), 1.8, "Lies: Ender-IO-Leitungen",
          subtitle="Ender IO, Item Conduit: 32 Stück pro Netztakt, Filter in jeder Verbindung.",
          description=[
              "&6Ender IO&r, &6Item Conduit&r: &e32 Gegenstände pro Netztakt&r, &6Energetic&r 64, &6Vibrant&r 64 doppelt so oft. Jede Verbindung hat einen Ein- und einen Ausgangsfilter mit Farbkanälen, Prioritäten und Rundlauf. Mehrere Leitungssorten liegen in einem Block. &eStufe 3.&r",
              "",
              "Leitungen aus Conduit Binder und dem Metall der Stufe. Fassaden verstecken sie hinter jedem Block. Siehe Kapitel Ender IO.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:ender_pearl"),

    quest("me_buses", col(3), 1.8, "Lies: Import- und Exportbusse",
          subtitle="AE2 und Refined Storage: das Lager holt und bringt selbst.",
          description=[
              "&6Applied Energistics 2&r, &6ME-Importbus&r und &6Exportbus&r: &e4 Vorgänge pro Sekunde&r, 1 Gegenstand je Vorgang, mit vier Beschleunigungskarten 96. Der &6Speicherbus&r macht jede Truhe zum Netzlager. Filterplätze in jedem Bus. &eStufe 3.&r",
              "",
              "&6Refined Storage&r, &6Importeur&r und &6Exporteur&r: je 2 FE pro Tick, neun Filterplätze, Externer Speicher als Gegenstück zum Speicherbus. &eStufe 3.&r",
              "",
              "Ein Netz ersetzt alle Rohre zwischen Lager und Maschinen. Siehe Kapitel Applied Energistics 2 und Refined Storage.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:comparator"),

    quest("xnet_laser", col(4), 1.8, "Lies: XNet, LaserIO, Integrated Tunnels",
          subtitle="Drei Netze, in denen du alles an einer Stelle einstellst.",
          description=[
              "&6XNet&r: ein Controller, 8 Kanäle, dünne Kabel zu Connectors an jeder Maschine, Advanced Connector bis &e100 000 RF/t&r und 5 000 mB je Vorgang. &6LaserIO&r: Laser zwischen Nodes bis 8 Blöcke, Karten je Seite, Energy Card bis &e1 000 000 FE/t&r. &6Integrated Tunnels&r: Importer und Exporter am Logiknetz, programmierbar. Alle mit Filtern. &eStufe 3.&r",
              "",
              "Alle drei im Kapitel Logistik.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="minecraft:redstone_torch"),

    quest("corporea", col(5), 1.8, "Lies: Corporea",
          subtitle="Botania, Corporea-Funken: ein Lager, das auf den Chat hört.",
          description=[
              "&6Botania&r, &6Corporea-Funken&r über Truhen bilden ein Netz. Der &6Corporea-Trichter&r holt bei Redstone-Signal einen Gegenstand heraus, der &6Corporea-Index&r liefert, was du in den Chat schreibst, zum Beispiel &e64 cobblestone&r. Filter über den Namen. &eStufe 3.&r",
              "",
              "Braucht Ender-Essenz und Feenstaub aus Alfheim. Siehe Kapitel Alfheim.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["items_when"], icon="botania:white_mystical_petal"),

    # ---- Flüssigkeiten -------------------------------------------------------
    quest("fluids_when", 0, 6.5, "&b&lWas wann: Flüssigkeiten",
          subtitle="Zwei Wahlen pro Stufe.",
          description=[
              "&eStufe 1:&r &6Create-Rohre mit Mechanischer Pumpe&r für alles Kurze und der &6Schlauchaufzug&r über einem See oder Lavasee für Unendliches. Lagern im &6Create-Flüssigkeitstank&r.",
              "",
              "&eStufe 2:&r &6Pipez-Flüssigkeitsrohre&r (500 mB/t mit der Verbesserten Modifikation) als Allzweckleitung und die &6Ranged Pump&r im Nether für Lava. Mekanism-Rohre und -Tanks innerhalb der Mekanism-Fabrik.",
              "",
              "&eStufe 3:&r &6Ender-IO-Flüssigkeitsleitungen&r (bis 8 000 mB) für die großen Mengen und &6Flüssigkeitszellen&r in AE2 oder RS, damit Lava, Öl und Chemie im Lager liegen statt in Tanks.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["items_when"], icon="create:fluid_tank", size=1.75, shape="hexagon"),

    quest("create_pump", col(0), 5.6, "Bau Rohr und Pumpe",
          subtitle="Create, Mechanische Pumpe: treibt 16 Blöcke Rohr an.",
          description=[
              "&6Create&r, &6Flüssigkeitsrohr&r und &6Mechanische Pumpe&r: Rohre verbinden Quellen und Ziele, die Pumpe treibt das Netz &e16 Blöcke&r weit an, schneller mit mehr Drehzahl, mehrere Pumpen addieren sich. Pfeil zeigt die Richtung, Schraubenschlüssel dreht sie. Kein Filter. &eStufe 1.&r",
              "",
              "Zwei Kupferbleche um einen Kupferbarren ergeben vier Rohre, Zahnrad und Rohr eine Pumpe. Ein offenes Rohrende nimmt Quellblöcke auf und setzt sie wieder ab.",
              "",
              "&eStufe 2:&r Das &6Intelligente Flüssigkeitsrohr&r filtert eine Flüssigkeit. Mehr im Kapitel Create.",
          ],
          tasks=[task_item("create:mechanical_pump", 1), task_item("create:fluid_pipe", 4)],
          rewards=[reward_item("create:copper_sheet", 4), reward_xp(3)],
          deps=["fluids_when"], icon="create:mechanical_pump"),

    quest("create_tank", col(1), 5.6, "Bau einen Flüssigkeitstank",
          subtitle="Create, Flüssigkeitstank: 8 Eimer pro Block, bis 2 304 Eimer am Stück.",
          description=[
              "&6Create&r, &6Flüssigkeitstank&r: &e8 Eimer pro Block&r, Grundfläche bis 3 x 3, bis &e32 Blöcke hoch&r, zusammen 2 304 Eimer. Rohre füllen und leeren ihn von jeder Seite, ein Komparator misst den Stand. Von Hand geht in Survival nichts hinein. &eStufe 1.&r",
              "",
              "Zwei Kupferbleche um ein Holzfass. Schraubenschlüssel schaltet das Fenster.",
              "",
              "Becken, Flaschenabfüller und Ausguss füllen und leeren Eimer und Flaschen am Tank.",
          ],
          tasks=[task_item("create:fluid_tank", 2)],
          rewards=[reward_item("minecraft:bucket", 2), reward_xp(3)],
          deps=["fluids_when"], icon="create:fluid_tank"),

    quest("hose_pulley", col(2), 5.6, "Häng einen Schlauchaufzug über den See",
          subtitle="Create, Schlauchaufzug: ab 10 000 Blöcken unendlich.",
          description=[
              "&6Create&r, &6Schlauchaufzug&r: lässt einen Schlauch bis &e128 Blöcke&r tief herab und pumpt den See darunter leer oder füllt ihn, so schnell wie das angeschlossene Rohrnetz. Ein Gewässer ab &e10 000 Blöcken&r bleibt dabei unverändert: unendlich Wasser oder Lava. &eStufe 1.&r",
              "",
              "Kupfergehäuse, Trockener-Seetang-Block, Kupferblech. Drehrichtung umkehren zieht den Schlauch ein.",
              "",
              "&eKronwerke:&r Ein Ozean oder ein großer Lavasee im Nether (Stufe 2) am Schlauchaufzug versorgt Waschanlagen und Wärmegeneratoren für immer.",
          ],
          tasks=[task_item("create:hose_pulley", 1)],
          rewards=[reward_item("create:fluid_pipe", 8), reward_table("s1_common")],
          deps=["fluids_when"], icon="create:hose_pulley"),

    quest("fluid_drawer", col(3), 5.6, "Bau eine Flüssigkeitsschublade",
          subtitle="Functional Storage, Fluid Drawer: eine Flüssigkeit, von Hand und per Rohr.",
          description=[
              "&6Functional Storage&r, &6Fluid Drawer&r: lagert eine Flüssigkeit pro Fach, als 1x1, 1x2 oder 2x2. Eimer in der Hand füllt und leert sie, Rohre jeder Mod ebenso. &eStufe 1.&r",
              "",
              "Ein Eimer in acht Holzbrettern. Mit dem &6Water Generator Upgrade&r füllt sie sich selbst mit Wasser, siehe Kapitel Lager.",
          ],
          tasks=[task_item("functionalstorage:fluid_1", 1)],
          rewards=[reward_item("minecraft:bucket", 1)],
          deps=["fluids_when"], icon="functionalstorage:fluid_1"),

    quest("pipez_fluid", col(4), 5.6, "Lies: Pipez Flüssigkeitsrohr",
          subtitle="Pipez, Flüssigkeitsrohr: 50 mB pro Tick, bis 500 mit Modifikation.",
          description=[
              "&6Pipez&r, &6Flüssigkeitsrohr&r: &e50 mB pro Tick&r ohne Modifikation, 100 mit der Normalen, 500 mit der Verbesserten, 2 000 mit der Fortgeschrittenen (Stufe 3), 10 000 mit der Ultimativen (Stufe 4). Flüssigkeitsfilter ab Stufe 3. &eStufe 2.&r",
              "",
              "Wie das Item-Rohr, nur mit zwei Eimern statt der Werfer. Siehe Kapitel Rohre und Router.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["fluids_when"], icon="minecraft:bucket"),

    quest("mek_pipe", col(0), 7.4, "Lies: Mekanism-Rohre und -Tanks",
          subtitle="Mekanism, Rohrleitung: 250 mB pro Tick, Tank 32 Eimer.",
          description=[
              "&6Mekanism&r, &6Einfache Rohrleitung&r: zieht &e250 mB pro Tick&r, Fortgeschritten 1 000 (Stufe 3), Elite 8 000 und Ultimativ 32 000 (Stufe 4). &6Flüssigkeitsbehälter&r: &e32 Eimer&r, dann 64, 128 und 256 Eimer, tragbar mit Inhalt. Kein Filter, Seiten mit dem Konfigurator. &eStufe 2.&r",
              "",
              "Zwei Stahlbarren und ein Eimer ergeben acht Rohre. Siehe Kapitel Mekanism.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["fluids_when"], icon="minecraft:iron_ingot"),

    quest("ie_fluid", col(1), 7.4, "Lies: IE-Rohre, Pumpe und Tanks",
          subtitle="Immersive Engineering: langsam ohne Druck, 512 Eimer im Tank.",
          description=[
              "&6Immersive Engineering&r, &6Flüssigkeitsrohr&r: verteilt gleichmäßig auf alle Ausgänge, langsam ohne Druck, schnell hinter einer &6Flüssigkeitspumpe&r (&e250 RF/t&r für Hochdruck). &6Holz-&r und &6Metallfass&r 12 Eimer, der &6Tank&r aus Blechmetall &e512 Eimer&r. Kein Filter, ein &6Rohrventil&r sperrt per Redstone. &eStufe 2.&r",
              "",
              "Hammer trennt und verbindet Rohre, Farbstoff färbt sie, gefärbte Rohre verbinden sich nicht mit neuen. Siehe Kapitel Immersive Engineering.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["fluids_when"], icon="minecraft:cauldron"),

    quest("ranged_pump", col(2), 7.4, "Lies: Ranged Pump",
          subtitle="Ranged Pumps, Pumpe: saugt 64 Blöcke im Umkreis leer.",
          description=[
              "&6Ranged Pumps&r, &6Pumpe&r: pumpt von ihrem Standort aus Ring um Ring bis Reichweite &e64&r alles unter sich weg, &e100 FE pro Block&r, einer alle 8 Ticks, Tank 32 Eimer. Was weg ist, wird zu Stein. Kein Filter, Redstone hält sie an. &eStufe 2.&r",
              "",
              "&eRezept auf Kronwerke:&r Obsidian, zwei Eisenspitzhacken, Lava- und Wassereimer, in der Mitte eine Mechanische Pumpe von Create. Siehe Kapitel Rohre und Router.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["fluids_when"], icon="minecraft:water_bucket"),

    quest("enderio_fluid", col(3), 7.4, "Lies: Ender-IO-Flüssigkeitsleitungen",
          subtitle="Ender IO, Fluid Conduit: 200, 1 000 oder 8 000 mB pro Netztakt.",
          description=[
              "&6Ender IO&r, &6Fluid Conduit&r &e200 mB&r, &6Energetic&r 1 000, &6Vibrant&r 8 000 pro Netztakt. Eine Leitung führt eine Flüssigkeit, Energetic und Vibrant mehrere, mit Flüssigkeitsfilter an jeder Verbindung. &eStufe 3.&r",
              "",
              "Liegt im selben Block wie Strom- und Gegenstandsleitungen. Siehe Kapitel Ender IO.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["fluids_when"], icon="minecraft:ender_pearl"),

    quest("fluid_cells", col(4), 7.4, "Lies: Flüssigkeiten im Lagernetz",
          subtitle="AE2 und Refined Storage: Lava und Öl liegen im Laufwerk.",
          description=[
              "&6Applied Energistics 2&r, &6Flüssigkeitszelle&r: 8 Eimer je Byte, eine 1k-Zelle fasst rund &e8 000 Eimer&r einer Sorte, Import- und Exportbus bewegen Flüssigkeiten wie Gegenstände. &6Refined Storage&r, &664B-Flüssigspeicherzelle&r: &e64 Eimer&r, bis 4 096B in Stufe 3. &eStufe 3.&r",
              "",
              "Siehe Kapitel Applied Energistics 2 und Refined Storage.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["fluids_when"], icon="minecraft:glass_bottle"),

    # ---- Gase ----------------------------------------------------------------
    quest("gas_when", 0, 11.5, "&a&lWas wann: Gase",
          subtitle="Alles Gas ist Mekanism, bis auf die Luft.",
          description=[
              "&eStufe 1:&r nichts. Es gibt noch kein Gas zu bewegen.",
              "",
              "&eStufe 2:&r &6Mekanism-Druckrohre&r (750 mB/t) für die kurzen Wege in der Fabrik, &6Pipez-Gasrohre&r, wenn Gas über eine Strecke oder zwischen Mods soll. PneumaticCraft bewegt mit seinen Druckrohren nur seine eigene Druckluft.",
              "",
              "&eStufe 3:&r &6Fortgeschrittene Druckrohre&r (2 000 mB/t) und &6Chemikalienzellen&r von Applied Mekanistics im AE2-Netz. Stufe 4 bringt die Elite- und Ultimativ-Rohre und den Quantenverschränker, der Gas ohne Rohr verschickt.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["fluids_when"], icon="minecraft:glass_bottle", size=1.75, shape="hexagon"),

    quest("mek_tube", col(0), 11.5, "Lies: Druckrohre und Chemikalientanks",
          subtitle="Mekanism, Druckrohr: 750 mB pro Tick, Tank 64 000 mB.",
          description=[
              "&6Mekanism&r, &6Einfaches Druckrohr&r: zieht &e750 mB Gas pro Tick&r, Fortgeschritten 2 000 (Stufe 3), Elite 64 000 und Ultimativ 256 000 (Stufe 4). &6Chemikalientank&r: &e64 000 mB&r, dann 256 000, 1 024 000 und 8 192 000 mB. Kein Filter, Seiten mit dem Konfigurator. &eStufe 2.&r",
              "",
              "Zwei Stahlbarren und ein Glas ergeben acht Rohre. Sauerstoff, Wasserstoff, Chlor und alles andere aus dem Kapitel Mekanism: Fortgeschritten.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["gas_when"], icon="minecraft:glass"),

    quest("pipez_gas", col(1), 11.5, "Lies: Pipez Gasrohr",
          subtitle="Pipez, Gasrohr: 200 mB pro Tick, bis 2 000 mit Modifikation.",
          description=[
              "&6Pipez&r, &6Gasrohr&r: &e200 mB pro Tick&r ohne Modifikation, 400 mit der Normalen, 2 000 mit der Verbesserten, 8 000 mit der Fortgeschrittenen (Stufe 3), 40 000 mit der Ultimativen (Stufe 4). Gasfilter ab Stufe 3. &eStufe 2.&r",
              "",
              "Wie das Item-Rohr, nur mit zwei Infundierten Legierungen statt der Werfer. Siehe Kapitel Rohre und Router.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["gas_when"], icon="minecraft:amethyst_shard"),

    quest("pnc_tube", col(2), 11.5, "Lies: PneumaticCraft-Druckrohre",
          subtitle="PneumaticCraft, Druckrohr: Luft bis 5 Bar, verstärkt 10, fortgeschritten 20.",
          description=[
              "&6PneumaticCraft&r, &6Druckrohr&r: trägt Druckluft von Kompressoren zu Maschinen, sicher bis &e5 Bar&r, das &6Verstärkte Druckrohr&r bis 10 Bar, das &6Fortgeschrittene&r bis 20 Bar (Stufe 3). Darüber platzt es. Module auf dem Rohr: Regler, Sicherheitsventil, Logistik. &eStufe 2.&r",
              "",
              "Rezepte in JEI. Mekanism-Gase passen nicht hinein, nur die Luft von PneumaticCraft. Eine &6Rohrkreuzung&r lässt zwei Stränge kreuzen, ohne sie zu verbinden.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["gas_when"], icon="minecraft:lightning_rod"),

    # ---- Strom ---------------------------------------------------------------
    quest("power_when", 0, 16, "&d&lWas wann: Strom",
          subtitle="Zwei Wahlen pro Stufe.",
          description=[
              "&eStufe 1:&r Es gibt keinen Strom, nur &6Drehkraft&r von Create. Wellen, Zahnräder und Riemen tragen sie, ein Getriebe lenkt sie um.",
              "",
              "&eStufe 2:&r &6Universalkabel von Mekanism&r (3 200 FE/t) für alles in der Basis, &6IE-Drähte&r, wenn Strom über Land soll. Pipez-Stromrohre nur für den Anfang, 256 FE/t sind schnell zu wenig.",
              "",
              "&eStufe 3:&r &6Flux Networks&r, weil ein Plug und ein Point jedes Kabel ersetzen, auch zwischen Dimensionen. &6Ender-IO-Leitungen&r (bis 192 000 FE/t) oder Powah-Kabel, wo Kabel bleiben sollen.",
              "",
              "&eStufe 4:&r Elite- und Ultimativkabel von Mekanism bis über 3 Millionen FE/t und Nitro-Kabel von Powah mit einer Million.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["gas_when"], icon="create:cogwheel", size=1.75, shape="hexagon"),

    quest("shafts", col(0), 15.1, "Leg Wellen",
          subtitle="Create, Welle: Drehkraft von Rad zu Maschine.",
          description=[
              "&6Create&r, &6Welle&r: trägt Drehkraft geradeaus, &6Zahnräder&r um die Ecke, &6Riemen&r über Abstand, das &6Getriebe&r in alle Richtungen. Belastung in Stresseinheiten, Tempo in Umdrehungen pro Minute, Brille zeigt beides. &eStufe 1.&r",
              "",
              "Zwei Andesitlegierungen übereinander ergeben acht Wellen, Welle und Brett ein Zahnrad. Großes Zahnrad auf kleines verdoppelt die Drehzahl.",
              "",
              "&eStufe 2:&r Create Crafts and Additions macht mit &6Alternator&r Strom aus Drehkraft und mit dem &6Elektromotor&r Drehkraft aus Strom; seine &6Verbinder&r mit Kupferspule tragen 1 000 FE/t über 16 Blöcke, die großen 5 000 über 32.",
          ],
          tasks=[task_item("create:shaft", 8)],
          rewards=[reward_item("create:cogwheel", 4), reward_xp(3)],
          deps=["power_when"], icon="create:shaft"),

    quest("mek_cable", col(1), 15.1, "Lies: Universalkabel",
          subtitle="Mekanism, Universalkabel: 3 200 FE pro Tick, versteht jede Mod.",
          description=[
              "&6Mekanism&r, &6Einfaches Universalkabel&r: &e3 200 FE pro Tick&r, Fortgeschritten 51 200 (Stufe 3), Elite 409 600 und Ultimativ 3 276 800 (Stufe 4). Verbindet sich mit allem, was FE kennt. Seiten mit dem Konfigurator auf Ziehen, Schieben oder Keine. &eStufe 2.&r",
              "",
              "Zwei Stahlbarren und ein Redstone ergeben acht. Der &6Energie-Würfel&r speichert daneben 1,6 Millionen FE. Siehe Kapitel Mekanism.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["power_when"], icon="minecraft:redstone"),

    quest("ie_wire", col(2), 15.1, "Lies: IE-Drähte",
          subtitle="Immersive Engineering, Drähte: 2 048, 8 192 oder 32 768 RF pro Tick über Land.",
          description=[
              "&6Immersive Engineering&r, &6Kupferdraht&r (NS): &e2 048 RF/t&r, 16 Blöcke je Spanne, &6Elektrumdraht&r (MS): 8 192 RF/t, 16 Blöcke, &6Stahldraht&r (HS): &e32 768 RF/t&r, 32 Blöcke. Ein &6Verbinder&r nimmt nur 256, 1 024 oder 4 096 RF/t an, &6Relais&r reichen weiter. &eStufe 2.&r",
              "",
              "Drahtspule in der Hand, ersten Verbinder anklicken, zweiten anklicken. Drähte zerreißen, wenn ein Block in ihrem Weg steht, und Berühren tut weh. Siehe Kapitel Immersive Engineering.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["power_when"], icon="minecraft:copper_ingot"),

    quest("pipez_energy", col(3), 15.1, "Lies: Pipez Stromrohr",
          subtitle="Pipez, Stromrohr: 256 FE pro Tick, bis 8 192 mit Modifikation.",
          description=[
              "&6Pipez&r, &6Stromrohr&r: &e256 FE pro Tick&r ohne Modifikation, 1 024 mit der Normalen, 8 192 mit der Verbesserten, 32 768 mit der Fortgeschrittenen (Stufe 3), 131 072 mit der Ultimativen (Stufe 4). Verteilt reihum auf alle Verbraucher. &eStufe 2.&r",
              "",
              "Wie das Item-Rohr, nur mit zwei Redstone-Blöcken statt der Werfer. Siehe Kapitel Rohre und Router.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["power_when"], icon="minecraft:redstone_torch"),

    quest("powah_cable", col(0), 16.9, "Lies: Powah-Kabel und Ender-Zellen",
          subtitle="Powah, Energiekabel: 500 bis 200 000 FE pro Tick, Ender-Zellen ohne Kabel.",
          description=[
              "&6Powah&r, &6Energiekabel&r: Starter &e500 FE/t&r, Basic 2 000, Hardened 5 000, Blazing 20 000, Niotic 50 000, Spirited &e200 000&r. Die &6Ender-Zelle&r schickt Strom ohne Kabel an jede andere Zelle auf demselben Kanal, Starter 1 000 bis Spirited 400 000 FE/t. &eStufe 3.&r",
              "",
              "Nitro mit 1 000 000 FE/t öffnet in Stufe 4. &eRezept auf Kronwerke:&r Die Energizing Orb, die alle Powah-Metalle macht, braucht einen Manadiamanten. Siehe Kapitel Powah.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["power_when"], icon="minecraft:amethyst_shard"),

    quest("flux", col(1), 16.9, "Lies: Flux Networks",
          subtitle="Flux Networks, Plug und Point: Strom ohne Kabel, auch zwischen Dimensionen.",
          description=[
              "&6Flux Networks&r, &6Flux Plug&r nimmt Strom ins Netz, &6Flux Point&r gibt ihn ab, überall und in jeder Dimension, bis &e800 000 FE/t&r je Anschluss. &6Basic Flux Storage&r speichert 2 Millionen FE bei 20 000 FE/t. Bis zu 5 Netze je Spieler, Chunks bleiben geladen. &eStufe 3.&r",
              "",
              "&eRezept auf Kronwerke:&r Der &6Flux Core&r braucht ein Quelljuwel von Ars Nouveau statt des Enderauges, der &6Flux Controller&r einen Fortgeschrittenen Steuerschaltkreis. Herculean Storage öffnet in Stufe 4, Gargantuan in Stufe 5.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["power_when"], icon="ars_nouveau:source_gem"),

    quest("enderio_energy", col(2), 16.9, "Lies: Ender-IO-Stromleitungen",
          subtitle="Ender IO, Energy Conduit: 8 000, 48 000 oder 192 000 FE pro Tick.",
          description=[
              "&6Ender IO&r, &6Energy Conduit&r &e8 000 FE/t&r, &6Energetic&r 48 000, &6Vibrant&r &e192 000 FE/t&r. Jede Verbindung einzeln auf Eingang, Ausgang oder beides, mit Redstone-Steuerung. Liegt im selben Block wie Gegenstands- und Flüssigkeitsleitungen. &eStufe 3.&r",
              "",
              "Siehe Kapitel Ender IO.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["power_when"], icon="minecraft:ender_pearl"),

    # ---- Lager ---------------------------------------------------------------
    quest("storage_when", 0, 21.5, "&7&lWas wann: Lager",
          subtitle="Zwei Wahlen pro Stufe.",
          description=[
              "&eStufe 1:&r &6Schubladen&r für alles in Mengen, &6Eisenfässer am Lagerkern&r für den Rest. Der Rucksack ist das Lager unterwegs, die Minendimension der Platz für Löcher.",
              "",
              "&eStufe 2:&r &6Goldfässer&r und &6Kompaktier-Schubladen&r, dazu die &6Tonne&r von Mekanism als Puffer vor der Erzstraße und die &6Endertruhe&r für den Weg zwischen Basis und Nether.",
              "",
              "&eStufe 3:&r &6AE2&r, wenn du Autocrafting willst, &6Refined Storage&r, wenn es einfach sein soll. Beide liegen am besten über einer Schubladenwand per Speicherbus. Tempad und Teleporter bringen dich selbst dorthin.",
              "",
              "&eStufe 4:&r 64k-Zellen, QIO von Mekanism und Netherit für Fässer und Rucksäcke.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["power_when"], icon="sophisticatedstorage:barrel", size=1.75, shape="hexagon"),

    quest("barrels", col(0), 20.6, "Bau ein aufwertbares Fass",
          subtitle="Sophisticated Storage, Fass: 27 Plätze, Eisen 54, wächst mit den Stufen.",
          description=[
              "&6Sophisticated Storage&r, &6Fass&r und &6Truhe&r: &e27 Plätze&r, Kupfer 45, Eisen &e54&r mit zwei Upgrade-Plätzen, Gold 81 (Stufe 2), Diamant 108 (Stufe 3), Netherit (Stufe 4). Aufwerten per Rechtsklick am stehenden Block, der Inhalt bleibt. Filter in jedem Upgrade. &eStufe 1.&r",
              "",
              "Sechs Bretter, zwei Stufen und ein Hebel. Das &6Stack-Upgrade&r aus acht Stämmen verdoppelt jeden Platz. Siehe Kapitel Lager.",
          ],
          tasks=[task_item("sophisticatedstorage:barrel", 1)],
          rewards=[reward_item("minecraft:lever", 2), reward_xp(3)],
          deps=["storage_when"], icon="sophisticatedstorage:barrel"),

    quest("drawers", col(1), 20.6, "Bau Schubladen",
          subtitle="Functional Storage, Schublade: 32 Stapel einer Sorte in einem Block.",
          description=[
              "&6Functional Storage&r, &6Schublade 1x1&r: &e32 Stapel&r einer Sorte, 1x2 zweimal 16, 2x2 viermal 8. Upgrades vervielfachen: Kupfer x8 und Gold x16 (Stufe 2), Diamant x24 (Stufe 3), Netherit x32 (Stufe 4). Sperren mit dem Configuration Tool hält die Sorte fest. &eStufe 1.&r",
              "",
              "Eine Truhe in acht Brettern. Der &6Drawer Controller&r braucht Quarz und damit den Nether (Stufe 2), die &6Kompaktier-Schublade&r für Nugget, Barren und Block öffnet ebenfalls in Stufe 2. Siehe Kapitel Lager.",
          ],
          tasks=[task_item("functionalstorage:oak_1", 2)],
          rewards=[reward_item("minecraft:oak_planks", 16), reward_xp(3)],
          deps=["storage_when"], icon="functionalstorage:oak_1"),

    quest("vault", col(2), 20.6, "Bau einen Tresor",
          subtitle="Create, Tresor: 20 Stapel pro Block, bis 81 Blöcke am Stück.",
          description=[
              "&6Create&r, &6Tresor&r: &e20 Stapel pro Block&r, Grundfläche bis 3 x 3, bis dreimal so lang wie breit, also bis 81 Blöcke und 1 620 Stapel in einem Inventar. Nur Trichter, Bänder, Arme und Rohre kommen hinein, von Hand geht nichts. Kein Filter. &eStufe 1.&r",
              "",
              "Zwei Eisenbleche um ein Holzfass. Ein Tresor am Ende der Maschinenstraße fängt alles auf, und ein Komparator meldet den Stand.",
          ],
          tasks=[task_item("create:item_vault", 1)],
          rewards=[reward_item("create:iron_sheet", 4), reward_xp(3)],
          deps=["storage_when"], icon="create:item_vault"),

    quest("backpack", col(3), 20.6, "Näh einen Rucksack",
          subtitle="Sophisticated Backpacks, Rucksack: 27 Plätze zum Mitnehmen.",
          description=[
              "&6Sophisticated Backpacks&r, &6Rucksack&r: &e27 Plätze&r und ein Upgrade-Platz, Kupfer und Eisen (Stufe 2), Gold und Diamant (Stufe 3), Netherit (Stufe 4). Pickup, Magnet, Lager- und Auffüll-Upgrade bewegen Gegenstände zwischen dir und den Kisten, jedes mit Filter. &eStufe 1.&r",
              "",
              "Eine Truhe, vier Leder, vier Fäden. Taste &eB&r öffnet ihn. Siehe Kapitel Lager.",
          ],
          tasks=[task_item("sophisticatedbackpacks:backpack", 1)],
          rewards=[reward_item("minecraft:leather", 4), reward_xp(3)],
          deps=["storage_when"], icon="sophisticatedbackpacks:backpack"),

    quest("packing", col(4), 20.6, "Kleb eine Truhe zu",
          subtitle="Sophisticated Storage, Packband: eine volle Truhe als ein Gegenstand.",
          description=[
              "&6Sophisticated Storage&r, &6Packband&r: Rechtsklick auf eine Sophisticated-Truhe, abbauen, und sie fällt mit allem Inhalt als ein Gegenstand. Schleimball und Papier, mehrere Einsätze je Rolle. &eStufe 1.&r",
              "",
              "&eStufe 2:&r Der &6Pappkarton&r von Mekanism (Sägespäne) packt jeden Block mit Inhalt ein, auch Maschinen und Öfen. Create-Tresore und Mekanism-Tanks behalten ihren Inhalt beim Abbauen sowieso.",
          ],
          tasks=[task_item("sophisticatedstorage:packing_tape", 1)],
          rewards=[reward_item("minecraft:slime_ball", 2)],
          deps=["storage_when"], icon="sophisticatedstorage:packing_tape"),

    quest("mining_dim", col(5), 20.6, "Reise in die Minenwelt",
          subtitle="Grubenrahmen und ein Quellstein: Platz für Löcher, Erz ohne Ende.",
          description=[
              "&6Minenwelt&r: ein Portal aus &e10 Grubenrahmen&r (vier breit, fünf hoch, Ecken frei), angezündet mit einem &6Quellstein&r. Drüben ist eine eigene Welt zum Graben, alle drei Tage neu. &eStufe 1.&r",
              "",
              "&eWas mitreist:&r Inventar, Enderkiste, Rucksäcke, und alles, was du durchs Portal wirfst. Siehe Kapitel Erkundung.",
          ],
          tasks=[task_advancement(MINING_ADV)],
          rewards=[reward_item("minecraft:torch", 32), reward_table("s1_uncommon")],
          deps=["storage_when"], icon=FRAME),

    quest("waystones", col(6), 20.6, "Schreib eine Rückkehr-Schriftrolle",
          subtitle="Waystones, Wegsteine: ein Level je 100 Blöcke, Schriftrollen kostenlos.",
          description=[
              "&6Waystones&r, &6Wegstein&r: einmal aktivieren, dann von jedem anderen Wegstein, mit dem &6Warpstein&r oder aus dem Inventar hinreisen. Kostet &e1 Level je 100 Blöcke&r, höchstens 27, zwischen Dimensionen immer 27. &6Schriftrollen&r und &6Warpplatten&r reisen umsonst. &eStufe 1.&r",
              "",
              "Rückkehr-Schriftrolle: zwei Goldnuggets und ein Tintenbeutel über drei Papier, bringt dich zum zuletzt aktivierten Wegstein. Wilde Wegsteine stehen alle 25 Chunks und in Dörfern. Siehe Kapitel Erkundung.",
          ],
          tasks=[task_item("waystones:return_scroll", 1)],
          rewards=[reward_item("waystones:warp_dust", 4), reward_xp(3)],
          deps=["storage_when"], icon="waystones:return_scroll"),

    quest("bins", col(0), 22.4, "Lies: Tonne und Persönliche Truhe",
          subtitle="Mekanism, Tonne: 4 096 Stück einer Sorte, QIO in Stufe 4.",
          description=[
              "&6Mekanism&r, &6Einfache Tonne&r: &e4 096&r Stück einer Sorte, Fortgeschritten 8 192 (Stufe 3), Elite 32 768 und Ultimativ 262 144 (Stufe 4). Rechtsklick hinein, Linksklick heraus, Auto-Auswurf nach unten. Die &6Persönliche Truhe&r öffnet nur für dich. &eStufe 2.&r",
              "",
              "&eStufe 4:&r Das &6QIO-Netz&r: Laufwerke mit Millionen Plätzen, Dashboard und tragbares Dashboard, drahtlos ohne Kabel. Siehe Kapitel Mekanism.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["storage_when"], icon="minecraft:barrel"),

    quest("ender_chest", col(1), 22.4, "Lies: Endertruhe",
          subtitle="Vanilla, Endertruhe: 27 Plätze, überall dieselben.",
          description=[
              "&6Vanilla&r, &6Endertruhe&r: &e27 Plätze&r, die dir allein gehören und in jeder Endertruhe der Welt gleich sind, auch im Nether. Acht Obsidian um ein Enderauge, und das Auge braucht Lohenstaub. &eStufe 2.&r",
              "",
              "Trichter kommen nicht hinein. Shulkerkisten als tragbare Truhen gibt es erst mit dem End in Stufe 4.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["storage_when"], icon="minecraft:ender_pearl"),

    quest("ae2", col(2), 22.4, "Lies: Applied Energistics 2",
          subtitle="AE2, ME-Netz: Zellen mit Bytes und Typen, Autocrafting.",
          description=[
              "&6Applied Energistics 2&r, &6ME-Laufwerk&r mit zehn Zellen: 1k &e8 128&r Stück bei einer Sorte, 4 160 bei 63 Sorten, 16k 130 048. Jede Zelle fasst höchstens 63 Typen. Konsole mit Suche, Busse, Autocrafting mit Molekularen Assemblern, drahtlose Konsolen. &eStufe 3.&r",
              "",
              "&eRezept auf Kronwerke:&r Das Laufwerk braucht zwei Fortgeschrittene Steuerschaltkreise, der Controller einen Geistgebundenen Edelstein aus Occultism, der Assembler zwei Präzisionsgetriebe. 64k und 256k öffnen in Stufe 4. Siehe Kapitel Applied Energistics 2.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["storage_when"], icon="minecraft:amethyst_shard"),

    quest("rs", col(3), 22.4, "Lies: Refined Storage",
          subtitle="Refined Storage, Laufwerk: Zellen ohne Typenzahl.",
          description=[
              "&6Refined Storage&r, &6Laufwerk&r mit acht Zellen: 1k &e1 024&r Stück, 4k 4 096, 16k &e16 384&r, egal wie viele Sorten. Konsole, Importeur und Exporteur, Externer Speicher, Autocrafting mit Mustern und Autoherstellern, drahtlose Konsole. &eStufe 3.&r",
              "",
              "Keine Kanäle, keine Typen, dafür weniger Zellplatz als AE2. 64k öffnet in Stufe 4. Siehe Kapitel Refined Storage.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["storage_when"], icon="minecraft:glass"),

    quest("tempad", col(4), 22.4, "Lies: Tempad und Teleporter",
          subtitle="Tempad, Zeittür: 1 000 Chronon je Tür, auch in andere Dimensionen.",
          description=[
              "&6Tempad&r, &6Tempad&r: speichert Orte und öffnet eine &6Zeittür&r dorthin, &e1 000 Chronon&r für 10 Sekunden, 6 000 im Gerät. Chronon macht das Chronometer oder das Metronom. &eStufe 3.&r",
              "",
              "&6Mekanism&r, &6Teleporter&r: ein Rahmen aus Teleporterrahmen, Strom und eine Frequenz, der &6Tragbare Teleporter&r aus der Tasche. &eStufe 3.&r Der Quantenverschränker für Gegenstände, Flüssigkeiten, Gas und Strom ohne Rohr kommt in Stufe 4. Siehe Kapitel Rohre und Router und Mekanism: Fortgeschritten.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["storage_when"], icon="minecraft:compass"),

    quest("done", 0, 26, "&6&lAlles verbunden",
          subtitle="Fünfmal gelesen, einmal gebaut.",
          description=[
              "Du kennst jetzt jeden Weg, auf dem in Kronwerke etwas von A nach B kommt oder liegen bleibt. Zum Abschluss zeig die Stufe-1-Grundausstattung einer Fabrik: Bänder, Trichter, Rohre, Pumpe und ein Fass dafür.",
              "",
              "&eKronwerke:&r Eine Kiste neben dem Obelisken ist dein Zubringer. Alles aus diesem Kapitel, was dort hineinliefert, zählt für dich zum Ziel.",
          ],
          tasks=[task_item("create:belt_connector", 4), task_item("create:andesite_funnel", 4),
                 task_item("create:fluid_pipe", 8), task_item("create:mechanical_pump", 1),
                 task_item("sophisticatedstorage:barrel", 1)],
          rewards=[reward_table("s1_rare"), reward_xp(15)],
          deps=["items_when", "fluids_when", "gas_when", "power_when", "storage_when"],
          icon="create:belt_connector", size=2.0, shape="gear"),
]

images = [
    banner("list_transport/title", "Transport und Lager", 10, -9.5, height=1.75, kind="title", colour="brass"),
    banner("list_transport/items", "Gegenstände", 10, -3.6, height=0.9, colour="brass"),
    banner("list_transport/fluids", "Flüssigkeiten", 7.5, 4.0, height=0.9, colour="water"),
    banner("list_transport/gas", "Gase", 3.5, 9.9, height=0.9, colour="nature"),
    banner("list_transport/power", "Strom", 5, 13.5, height=0.9, colour="fire"),
    banner("list_transport/storage", "Lager", 9, 19.0, height=0.9, colour="stone"),
]

chapter(C, "Checkliste: Transport und Lager", "minecraft:hopper", "lists", quests, shape="circle", order=70,
        stage=1, hide_dependency_lines=True,
        subtitle=["Jeder Weg für Gegenstände, Flüssigkeiten, Gase und Strom, eine Zeile je Block, mit Stufe."],
        images=images)
