"""Mahou Tsukai in stage 4: the blood circle and personal mana, the seven powdered catalysts,
spell cloth and scrolls, attuned gems and mana circuits, Fay Sight, leylines and the Fae,
the Mystic Code, the Mystic Staff of Explosive Mana Condensation (30 for the stage 4 goal),
the Reality Marble dimension and Caliburn. Recipes and costs are from the jar and the
server config (mahoutsukai-server.toml, defaults)."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_advancement, task_dimension,
                  reward_item, reward_table, reward_xp, banner, img, item_texture)

C = "mahou_tsukai"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Der Blutkreis -------------------------------------------------------------
    quest("hammer", 0, 0, "&cMahou Tsukai",
          subtitle="Magie aus Blut, Pulver und Tuch.",
          description=[
              "Mit &6Stufe 4 (Sternwerk)&r öffnet sich &cMahou Tsukai&r. Diese Magie funktioniert anders als alles, was du kennst: Es gibt keine Maschinen und keine Altäre. Du zeichnest einen Kreis aus deinem eigenen Blut auf den Boden, streust drei Pulver hinein und bekommst eine Schriftrolle oder einen Zauberkreis.",
              "",
              "Es gibt keine Klassen und keine Pfade, zwischen denen du wählen musst. Welcher Zauber entsteht, entscheiden allein die drei Pulver.",
              "",
              "Fang mit zwei Dingen an:",
              "&e1.&r Den &6Hammer&r: oben eine Schnur und ein Bruchstein, in der Mitte Bruchstein und Stock, unten ein Stock.",
              "&e2.&r Den &6treuen Ratgeber&r (Knowledge Compendium) aus Leder, Papier und rotem Farbstoff. Er erklärt jeden Zauber mit seinen Kosten, so wie dein Server sie eingestellt hat.",
              "",
              "&eKronwerke:&r Der Obelisk will in dieser Stufe auf der Magieseite &e30 Mystische Stäbe&r aus diesem Kapitel, eine feste Zahl, und dazu &e128 Gaia-Geister&r von Botania.",
          ],
          tasks=[task_item("mahoutsukai:hammer", 1), task_item("mahoutsukai:guidebook", 1)],
          rewards=[reward_item("minecraft:red_dye", 8), reward_table("s4_common")],
          icon="mahoutsukai:guidebook", size=2.0, shape="hexagon"),

    quest("blood", 2.6, 0, "&cDer Blutkreis",
          subtitle="Ein Kreis auf dem Boden, und du bist Magier.",
          description=[
              "Lege in den Steuerungseinstellungen eine Taste für &eMahoujin zeichnen&r fest (Draw Mahoujin, Kategorie Mahou Tsukai). Dann nimm Schaden und drück &esofort danach&r die Taste, während du auf einen festen Block schaust. Ein Kreis aus Blut erscheint auf dem Boden.",
              "",
              "Wer sich nicht von Monstern beißen lassen will, nimmt den &6Dolch&r (Eisen, Gold, ein Stock und lila Farbstoff). Rechtsklick lässt dich bluten, und schon hast du den Schaden, den du brauchst.",
              "",
              "Mit dem ersten Kreis bist du ein &cMahou Tsukai&r. Auf dem Bildschirm erscheint deine Manaleiste, am Anfang mit &d100 Mana&r.",
          ],
          tasks=[task_advancement("mahoutsukai:root", "Einen Blutkreis gezeichnet"),
                 task_item("mahoutsukai:dagger", 1)],
          rewards=[reward_item("minecraft:cooked_beef", 16), reward_xp(5)],
          deps=["hammer"], icon="mahoutsukai:dagger"),

    quest("catalysts", 5.2, 0, "&eDie sieben Pulver",
          subtitle="Jede Schule der Magie hat ihr Pulver.",
          description=[
              "Mit dem Hammer zerschlägst du an der Werkbank sieben Dinge zu &ePulver&r (Powdered Catalysts). Der Hammer bleibt dabei im Raster liegen. Jedes Pulver steht für eine Schule:",
              "",
              "&7Eisen&r: Barrieren rund um einen Kreis",
              "&5Enderperle&r: Teleportation",
              "&bDiamant&r: Projektion, also Waffen",
              "&aSmaragd&r: Tausch, oft gegen Mana",
              "&6Gold&r: Mystik, die besonderen Angriffe",
              "&fQuarz&r: Intelligenz, Vertrautentiere",
              "&2Enderauge&r: Mystische Augen",
              "",
              "&eTipp:&r Der &6Mörser mit Stößel&r gibt aus jedem Stück zwei Pulver statt einem. Der Mörser sind zwei Ziegel über einem Diamanten, der Stößel braucht drei Diamanten und zwei Stöcke. Das lohnt sich schnell.",
          ],
          tasks=[task_item("mahoutsukai:powdered_iron", 1), task_item("mahoutsukai:powdered_gold", 1),
                 task_item("mahoutsukai:powdered_diamond", 1), task_item("mahoutsukai:powdered_emerald", 1),
                 task_item("mahoutsukai:powdered_ender", 1), task_item("mahoutsukai:powdered_eye", 1),
                 task_item("mahoutsukai:powdered_quartz", 1)],
          rewards=[reward_item("minecraft:diamond", 3), reward_table("s4_common")],
          deps=["blood"], icon="mahoutsukai:powdered_gold"),

    quest("cloth", 7.8, 0, "&eZaubertuch",
          subtitle="Ohne Tuch kein Zauber zum Mitnehmen.",
          description=[
              "Weiße Wolle und der Dolch ergeben &e4 Zaubertücher&r (Spell Cloth). Der Dolch bleibt erhalten.",
              "",
              "So wirkst du Magie:",
              "&e1.&r Für eine &6Schriftrolle&r legst du zuerst ein Zaubertuch auf den Boden.",
              "&e2.&r Darauf zeichnest du einen Blutkreis.",
              "&e3.&r Mit drei Pulvern in der Hand klickst du den Kreis an, eins nach dem anderen.",
              "",
              "Stimmt die Mischung, wird der Kreis zur Schriftrolle. Ohne Tuch entsteht ein &6Zauberkreis&r, der am Boden liegen bleibt und dort wirkt, etwa eine Barriere. Manche Zauber brauchen ein Tuch, manche gehen ohne, bei einigen geht beides. Der Ratgeber sagt es dir bei jedem Zauber.",
              "",
              "&eTipp:&r Ein Rechtsklick mit leerer Hand auf einen frischen Blutkreis legt das letzte Rezept wieder hinein, wenn du die Pulver und das Tuch dabei hast.",
          ],
          tasks=[task_item("mahoutsukai:spell_cloth", 8)],
          rewards=[reward_item("minecraft:white_wool", 8)],
          deps=["catalysts"], icon="mahoutsukai:spell_cloth"),

    quest("strengthening", 10.4, 0, "&bVerstärkung",
          subtitle="Die erste Schriftrolle.",
          description=[
              "Eine gute erste Rolle ist die &bVerstärkung&r (Strengthening): &e2 Diamantpulver und 1 Eisenpulver&r auf einem Tuch.",
              "",
              "Benutzt du sie, wird das erste Ding in deiner Schnellleiste verstärkt, oder das in deiner zweiten Hand, wenn du dort etwas hältst. Verstärkte Gegenstände sind eine Zeit lang unzerstörbar, machen mehr Schaden und bauen schneller ab. Das kostet &d50 Mana&r.",
              "",
              "Eine Schriftrolle wird beim Benutzen verbraucht und gehört dem, der sie gezeichnet hat. Das Mana kommt immer von dir.",
              "",
              "&eMana wächst durch Benutzen.&r Je mehr Mana du ausgibst, desto größer wird deine Leiste, wie ein Muskel. Mana kommt langsam von selbst zurück, schneller mit vollem Magen. Schlafen gibt dir die Hälfte deiner Leiste auf einmal zurück.",
          ],
          tasks=[task_item("mahoutsukai:scroll_strengthening", 1)],
          rewards=[reward_item("mahoutsukai:powdered_diamond", 4), reward_xp(5)],
          deps=["cloth"], icon="mahoutsukai:scroll_strengthening"),

    quest("schools", 10.4, -2.6, "&eWeitere Zauber",
          subtitle="Ein paar Rezepte zum Ausprobieren.",
          description=[
              "Jeder Zauber besteht aus drei Pulvern. Hier eine Auswahl, der Rest steht im Ratgeber:",
              "",
              "&6Rho Aias&r (2 Gold, 1 Eisen, Tuch): ein großer Schild vor dir, an dem Monster abprallen und Geschosse verschwinden.",
              "&6Gandr&r (Gold, Smaragd, Diamant, Tuch): ein Fluch, der mit deiner Manaleiste stärker wird und deine negativen Effekte auf den Gegner überträgt.",
              "&5Projektilverschiebung&r (2 Ender, 1 Diamant, Tuch): bringt dich zum letzten Pfeil, den du geschossen hast.",
              "&bProjektion&r (2 Diamant, 1 Quarz, Tuch): merkt sich ein Werkzeug und gibt dir später eine Kopie mit wenig Haltbarkeit.",
              "&7Alarmbarriere&r (2 Eisen, 1 Quarz): meldet dir jedes Wesen, das in ihren Bereich kommt.",
              "&fVertrautentier beschwören&r (3 Quarz, Tuch): ein Begleiter, der dir Spieler, Monster und Blöcke meldet und die Gegend um sich geladen hält.",
              "",
              "Barrieren, die am Boden liegen, ziehen ständig Mana. Rechtsklick schaltet sie an und aus, ein Redstone-Signal auch.",
          ],
          tasks=[task_item("mahoutsukai:scroll_rho_aias", 1)],
          rewards=[reward_item("mahoutsukai:spell_cloth", 8)],
          deps=["strengthening"], icon="mahoutsukai:scroll_rho_aias", optional=True),

    quest("caliburn", 10.4, -4.8, "&6Das Schwert im See",
          subtitle="Konsolidierung der Macht.",
          description=[
              "Der Kreis der &6Konsolidierung&r (Power Consolidation: 2 Diamant, 1 Smaragd, ohne Tuch) erschafft einen See. Jede Erweiterung des Sees kostet &d30 Mana&r.",
              "",
              "Ist der See fertig, wirfst du ein &everzaubertes Schwert&r hinein. Für &d5 000 Mana&r bekommst du &6Caliburn&r zurück, mit dem Schaden des alten Schwerts und einem Bonus für seine Verzauberungen. Untote fliehen vor Caliburn. Du kannst es neu verzaubern und den Vorgang wiederholen.",
              "",
              "Wer noch weiter will: Der Ratgeber kennt &6Emrys&r (ein verstärkter Stock, der vom Blitz getroffen wird), &6Nobu&r (ein verstärkter Bogen, der aus 200 Blöcken trifft) und &6Replica&r. Lies dort nach, die Bedingungen sind lang.",
          ],
          tasks=[task_advancement("mahoutsukai:sword_in_the_lake", "Caliburn aus dem See bekommen")],
          rewards=[reward_item("minecraft:experience_bottle", 16), reward_table("s4_uncommon")],
          deps=["schools"], icon="mahoutsukai:caliburn", optional=True),

    # ---- Mana speichern -----------------------------------------------------------
    quest("gems", 2.6, 3.0, "&dEingestimmte Edelsteine",
          subtitle="Mana für unterwegs.",
          description=[
              "Deine eigene Leiste ist am Anfang winzig. Größere Zauber bezahlst du aus Speichern.",
              "",
              "Der &dEinstimmer&r (Attuner) entsteht aus Gold und Lapis. Formlos mit einem Diamanten wird er zum &deingestimmten Diamanten&r (10 000 Mana), mit einem Smaragd zum &deingestimmten Smaragd&r (5 000 Mana).",
              "",
              "Halte den Edelstein und mach einen Rechtsklick, dann fließt dein Mana hinein. Zauber ziehen automatisch aus allen Edelsteinen in deinem Inventar.",
              "",
              "&eTipp:&r Füll die Steine, bevor du schlafen gehst. Der Schlaf gibt dir die Hälfte deiner Leiste zurück, und am Morgen geht es weiter.",
          ],
          tasks=[task_item("mahoutsukai:attuned_diamond", 1)],
          rewards=[reward_item("minecraft:lapis_lazuli", 16)],
          deps=["blood"], icon="mahoutsukai:attuned_diamond"),

    quest("circuit", 5.2, 3.0, "&dManaschaltkreis",
          subtitle="100 000 Mana neben der Werkbank.",
          description=[
              "Ein &dManaschaltkreis&r speichert &d100 000 Mana&r. Steht er höchstens 10 Blöcke entfernt, zaubern deine Zauber daraus.",
              "",
              "Zwei Rezepte, gleiche Größe:",
              "&e1.&r &dMagitech-Manaschaltkreis&r: 6 Eisenbarren und 3 Smaragdpulver.",
              "&e2.&r &dManaschaltkreis&r: 8 Feen-Essenzen um ein Smaragdpulver.",
              "",
              "Wer den Block nach dem Aufstellen als Erster anklickt, dem gehört er. Rechtsklick gibt Mana hinein, schleichend mit Rechtsklick schaltest du ihn an und aus. Mit Feen-Essenz angeklickt, dürfen auch andere Spieler daraus zaubern.",
          ],
          tasks=[task_item("mahoutsukai:mana_circuit_magitech", 1)],
          rewards=[reward_item("minecraft:emerald", 4), reward_xp(5)],
          deps=["gems"], icon="mahoutsukai:mana_circuit_magitech"),

    quest("sources", 7.8, 3.0, "&aMana von außen",
          subtitle="Tauschkreise, Würmer und Bücher.",
          description=[
              "Die Schule des &aTauschs&r macht Mana aus anderen Dingen. Die ersten beiden sind Kreise ohne Tuch, der dritte eine Rolle:",
              "",
              "&aChronaler Tausch&r (2 Smaragd, 1 Quarz): gibt zwölf Stunden lang Mana, rund um die Uhrzeit des Aufstellens, und zieht in den anderen zwölf Stunden wieder welches ab.",
              "&aHaltbarkeitstausch&r (2 Smaragd, 1 Diamant): frisst die Haltbarkeit von Werkzeugen auf dem Kreis oder aus einer Kiste darunter und macht daraus Mana. Alte Eisenwerkzeuge aus der Monsterfarm sind dafür perfekt.",
              "&aSchadenstausch&r (2 Smaragd, 1 Eisen, Tuch): ein paar Treffer lang wird erlittener Schaden zu Mana.",
              "",
              "Dazu &2Kodoku&r: ein Wurm aus Erde, Karotte, Kartoffel, giftiger Kartoffel, verrottetem Fleisch und Netherwarze. Monster, die andere Wesen töten, sammeln Kodoku-Wert. Setz den hungrigen Wurm auf ein starkes Monster und töte es. Verbrennst du den Wurm danach, bekommen Manaschaltkreise in der Nähe Mana, nahe einer Leylinie mehr.",
          ],
          tasks=[task_item("mahoutsukai:kodoku", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 16)],
          deps=["circuit"], icon="mahoutsukai:kodoku", optional=True),

    quest("fay_sight", 10.4, 3.0, "&2Mystische Augen der Feensicht",
          subtitle="Leylinien und die Fae.",
          description=[
              "Die Rolle der &2Feensicht&r (Fay Sight: 3 Enderaugenpulver, Tuch) kostet &d100 Mana&r und lässt dich eine Weile &2Leylinien&r und &2Fae&r sehen.",
              "",
              "Leylinien verbinden Punkte, die etwa 300 Blöcke auseinanderliegen. Nahe einer Linie oder einem Leypunkt kommt dein Mana deutlich schneller zurück, weit weg davon langsamer. Fliegst du mit Elytren an einer Leylinie entlang, bekommst du Schub.",
              "",
              "&eTipp:&r Bau deine Magierwerkstatt auf einen Leypunkt. Dort regenerierst du am schnellsten, und dort tauchen auch die Fae auf.",
          ],
          tasks=[task_item("mahoutsukai:scroll_fay_sight", 1)],
          rewards=[reward_item("minecraft:ender_eye", 4)],
          deps=["strengthening"], icon="mahoutsukai:scroll_fay_sight"),

    quest("fae", 13.0, 3.0, "&2Feen-Essenz",
          subtitle="Was die Fae zurücklassen.",
          description=[
              "Die &2Fae&r sind Geister, die nahe Leylinien herumschweben. Ihr Lachen klingt wie Glöckchen. Sehen kannst du sie nur mit Feensicht. Besiegt lassen sie &2Feen-Essenz&r fallen.",
              "",
              "Fae mögen Magie auf Leypunkten und kommen dann gern vorbei. Mit einem beliebigen Pulver kannst du sie sogar vermehren.",
              "",
              "Feen-Essenz ist mehr als eine Zutat. Klickst du mit ihr auf den Boden, entsteht ein &2Feenkreis&r statt eines Blutkreises. Rollen und Kreise daraus gehören niemandem und dürfen von allen benutzt werden. Wer sie benutzt, zahlt das Mana.",
              "",
              "&cAchtung:&r Iss keinen &cFeenmuffin&r. Danach meiden dich die Fae, bis du die Feensicht neu erweckst.",
          ],
          tasks=[task_item("mahoutsukai:fae_essence", 8)],
          rewards=[reward_item("mahoutsukai:powdered_eye", 4), reward_xp(5)],
          deps=["fay_sight"], icon="mahoutsukai:fae_essence"),

    quest("reality_marble", 5.2, 5.4, "&bPerle der Realität",
          subtitle="Eine Welt aus Schwertern.",
          description=[
              "Die Rolle der &bPerle der Realität&r (Reality Marble: 3 Diamantpulver, Tuch) kostet &d4 000 Mana&r. Das schafft deine eigene Leiste lange nicht, also zahlst du aus Edelsteinen oder einem Schaltkreis.",
              "",
              "Sie bringt dich an einen festen Ort in einer eigenen Dimension, in der überall Schwerter auftauchen. Die Schwerter kannst du benutzen, sie halten aber nur wenige Schläge.",
              "",
              "Schaust du beim Benutzen ein Wesen an, kommt es mit. Dann kommt nur einer von euch beiden zurück: Einer muss sterben, damit der andere gehen kann. Gehst du allein, reicht es, Schaden zu nehmen, um zurückzukehren.",
              "",
              "&eTipp:&r Ein Zweikampf in der Perle ist ein sauberer Weg, einen gefährlichen Gegner aus deiner Basis zu holen.",
          ],
          tasks=[task_item("mahoutsukai:scroll_reality_marble", 1),
                 task_dimension("mahoutsukai:reality_marble")],
          rewards=[reward_item("minecraft:diamond_sword", 1), reward_table("s4_uncommon")],
          deps=["circuit"], icon="mahoutsukai:scroll_reality_marble"),

    # ---- Der Mystische Stab ---------------------------------------------------------
    quest("mystic_code", 13.0, 0, "&6Mystisches Zeichen",
          subtitle="Drei Stapel Rollen in einer Hand.",
          description=[
              "Das &6Mystische Zeichen&r (Mystic Code) entsteht aus 6 Zaubertüchern und 3 Goldpulvern. Es hält drei Stapel Schriftrollen.",
              "",
              "Schleichend mit Rechtsklick öffnest du sein Inventar. Mit der Taste &eMystisches Zeichen wechseln&r springst du zwischen den Rollen, Rechtsklick benutzt die gewählte.",
              "",
              "So hast du Rho Aias, Verstärkung und einen Angriff immer griffbereit, ohne die Schnellleiste zu füllen.",
          ],
          tasks=[task_item("mahoutsukai:mystic_code", 1)],
          rewards=[reward_item("mahoutsukai:powdered_gold", 4)],
          deps=["strengthening"], icon="mahoutsukai:mystic_code"),

    quest("first_sorcery", 15.6, 0, "&6Erste Magie",
          subtitle="Eine Rolle, viele Zauber.",
          description=[
              "Das &6Mystische Zeichen der ersten Magie&r (First Sorcery) braucht 6 Zaubertücher, 2 Feen-Essenzen und 1 Diamantpulver.",
              "",
              "Es funktioniert wie das normale Zeichen, mit einem großen Unterschied: &eDie Rollen darin werden nicht verbraucht.&r Dafür hat das Zeichen selbst &e50 Haltbarkeit&r. Die Barriere des Lebensraubs darf nicht hinein.",
              "",
              "Für den Obelisken ist das Gold wert. Leg eine Rolle der &6Explosiven Manakondensation&r hinein, und jeder Rechtsklick ruft einen neuen Stab, solange dein Mana reicht.",
          ],
          tasks=[task_item("mahoutsukai:mystic_code_first_sorcery", 1)],
          rewards=[reward_item("mahoutsukai:fae_essence", 4), reward_table("s4_uncommon")],
          deps=["mystic_code", "fae"], icon="mahoutsukai:mystic_code_first_sorcery"),

    quest("staff_scroll", 13.0, -2.6, "&6Explosive Manakondensation",
          subtitle="Die Rolle für den Stab.",
          description=[
              "Die Rolle der &6Explosiven Manakondensation&r: &e2 Goldpulver und 1 Diamantpulver&r auf einem Zaubertuch.",
              "",
              pic("mahoutsukai:scroll_mystic_staff"),
              "",
              "Benutzt du sie, landet ein &6Mystischer Stab der Explosiven Manakondensation&r (Mystic Staff) in deinem Inventar. Das kostet &d2 000 Mana&r. &eRezept auf Kronwerke:&r Der Server hat die Kosten von 100 auf 2 000 Mana angehoben.",
              "",
              "So viel hat deine eigene Leiste lange nicht. Du zahlst aus Speichern: Ein &deingestimmter Diamant&r hält 10 000 Mana, also fünf Stäbe, ein eingestimmter Smaragd 5 000. Ein &dManaschaltkreis&r in höchstens 10 Blöcken Entfernung hält 100 000 Mana, genug für fünfzig Stäbe.",
              "",
              "Die Rolle ist an dich gebunden, nur du kannst sie benutzen. Für einen Stab braucht es also immer einen Magier, der sein eigenes Mana gibt.",
          ],
          tasks=[task_item("mahoutsukai:scroll_mystic_staff", 1)],
          rewards=[reward_item("mahoutsukai:powdered_gold", 8)],
          deps=["strengthening"], icon="mahoutsukai:scroll_mystic_staff"),

    quest("staff", 15.6, -2.6, "&6Der Mystische Stab",
          subtitle="Ein Knall, den der ganze Server hört.",
          description=[
              "Der Stab hat drei Arten zu feuern. Schleichend mit Rechtsklick wechselst du:",
              "",
              "&eGroße Explosion:&r eine lange Aufladung, dann eine riesige Explosion für &d5 000 Mana&r. Der Schaden wächst mit deiner Manaleiste, und danach zieht ein Gewitter auf.",
              "&eViele kleine Explosionen:&r &d600 Mana&r pro Salve.",
              "&eStrahl:&r &d500 Mana pro Tick&r. Je länger du hältst, desto mehr Schaden, und der Strahl zerstört Blöcke.",
              "",
              "&cAchtung:&r Die Explosionen und der Strahl zerstören auf diesem Server die Landschaft. Niemals in der Nähe von Basen benutzen, auch nicht deiner eigenen.",
              "",
              "Für den Obelisken musst du den Stab nicht abfeuern. Er zählt so, wie er ist. Und eine große Explosion kostet mehr als zwei neue Stäbe.",
          ],
          tasks=[task_item("mahoutsukai:mystic_staff", 1)],
          rewards=[reward_item("mahoutsukai:attuned_emerald", 1), reward_xp(10)],
          deps=["staff_scroll"], icon="mahoutsukai:mystic_staff"),

    quest("obelisk", 19.0, -1.3, "&cFür den Obelisken",
          subtitle="Dreißig Stäbe, 60 000 Mana.",
          description=[
              "&eKronwerke:&r Das Magieziel von &6Stufe 4 (Sternwerk)&r heißt &e128 Gaia-Geister&r und &e30 Mystische Stäbe&r. Beide Zahlen sind fest und wachsen nicht mit der Spielerzahl.",
              "",
              "Jeder Stab kostet einen Magier eine Rolle und &d2 000 Mana&r, für alle dreißig also &d60 000 Mana&r. Mit dem Zeichen der ersten Magie reicht eine Rolle für viele Stäbe, bis die Haltbarkeit des Zeichens aufgebraucht ist. Das Mana zahlt aber jedes Mal ein Spieler.",
              "",
              "&eWoher die 2 000 Mana kommen:&r",
              "&e1.&r Deine eigene Leiste. Gib Mana in Edelsteine oder einen Schaltkreis, schlaf, und gib wieder. Jedes ausgegebene Mana lässt die Leiste wachsen.",
              "&e2.&r Ein &aChronaler Tausch&r und ein &aHaltbarkeitstausch&r neben der Werkstatt, der zweite gefüttert mit alten Werkzeugen aus der Monsterfarm.",
              "&e3.&r &2Kodoku&r-Würmer, die neben dem Schaltkreis verbrennen, am besten nahe einer Leylinie.",
              "&e4.&r Die Werkstatt auf einem Leypunkt, dort kommt Mana am schnellsten zurück.",
              "",
              "Ein Stab passt nicht auf einen Stapel. Gib sie einzeln am Obelisken ab, oder stell eine Kiste als Zulieferer daneben.",
              "",
              "&eTipp:&r Sprecht euch ab. Ein voller Manaschaltkreis reicht für das ganze Ziel. Wenn mehrere Magier ihr Mana in denselben Schaltkreis geben, macht einer mit dem Zeichen der ersten Magie die Stäbe. Gebt dazu den Schaltkreis mit Feen-Essenz für alle frei.",
          ],
          tasks=[task_item("mahoutsukai:mystic_staff", 5),
                 task_checkmark("Mystische Stäbe am Obelisken abgegeben")],
          rewards=[reward_table("s4_rare"), reward_xp(20)],
          deps=["staff", "first_sorcery"], icon="mahoutsukai:mystic_staff", size=2.5, shape="gear"),
]

images = [
    banner("mahou_tsukai/title", "Mahou Tsukai", 9.5, -7.6, height=1.8, kind="title", colour="fire"),
    banner("mahou_tsukai/blutkreis", "Der Blutkreis", 2.6, -1.6, height=0.9, colour="fire"),
    banner("mahou_tsukai/mana", "Mana speichern", 5.2, 1.6, height=0.9, colour="magic"),
    banner("mahou_tsukai/feen", "Leylinien und Fae", 11.7, 4.6, height=0.9, colour="nature"),
    banner("mahou_tsukai/stab", "Der Mystische Stab", 14.3, -4.1, height=0.9, colour="brass"),
]

chapter(C, "Mahou Tsukai", "mahoutsukai:mystic_staff", "magic", quests, shape="circle", order=40,
        stage=4, subtitle=["Stufe 4. Blutkreise, Pulver und Rollen, Mana, die Fae und der Mystische Stab."],
        images=images)
