"""Mekanism ore processing as a ladder, one machine per quest in build order, like the ATM10
Mekanism ore chapter: furnace (1x), enrichment chamber and energized smelter (2x, stage 2),
electrolytic separator, pump, purification chamber, crusher, the pipes (3x, stage 3), chemical
infuser, brine and chlorine, chemical injection chamber (4x, stage 4), sulfur chain, dissolution
chamber, washer, crystallizer (5x, stage 4), factories and upgrades, and how Create, the
Metalworks foundry, the IE crusher and Oritech compare per stage. Stage 3 and 4 machines are
only named; their quests check the stage 2 intermediates (clumps, dirty dust) or a checkmark.
Numbers come from the Mekanism recipe jsons, config/Mekanism/machine-usage.toml (Joules, FE =
J / 2.5), tiers.toml and general.toml. Recipes follow kubejs/server_scripts/kronwerke/tech.js."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "mekanism_ores"


def head(name, text, left, y, height=0.9, kind="section", colour="brass"):
    """A banner whose left edge sits at x = left."""
    b = banner(f"{C}/{name}", text, 0, y, height=height, kind=kind, colour=colour)
    b["x"] = round(left + b["width"] / 2, 2)
    return b


quests = [
    # ---- 1x: der Ofen ---------------------------------------------------------------
    quest("welcome", 0, 1.5, "&5&lBau zwei Stahlgehäuse",
          subtitle="Das Fundament jeder Maschine auf der Erzleiter.",
          description=[
              "Vier &6Stahlbarren&r in die Ecken, vier &6Andesitlegierungen&r an die Seiten, ein &6Osmiumbarren&r in die Mitte. &eRezept auf Kronwerke:&r die Legierung ersetzt das Glas.",
              "",
              "Dieses Kapitel ist die Erzleiter von Mekanism: eine Maschine pro Quest, in der Reihenfolge, in der du sie baust. Ofen, dann Anreicherungskammer (2x), Klärkammer (3x), Injektionskammer (4x), Auflösungskammer (5x).",
              "",
              "&eStufen:&r 2x geht sofort. 3x öffnet mit &6Stufe 3&r, 4x und 5x mit &6Stufe 4&r. Die Quests dieser Stufen stehen schon hier, damit du weißt, worauf du hinbaust, abhaken kannst du sie erst dann.",
              "",
              "Osmium, Infusionsanlage, Schaltkreise und Stahl: siehe Kapitel &5Mekanism&r. Hier geht es nur um die Straße.",
          ],
          tasks=[task_item("mekanism:steel_casing", 2)],
          rewards=[reward_item("create:andesite_alloy", 16), reward_table("s2_common")],
          icon="mekanism:steel_casing", size=2.0, shape="hexagon"),

    quest("furnace", 2.75, 1.5, "&7Schmilz Rohes Eisen im Ofen",
          subtitle="Ein Rohes Erz, ein Barren. Die Null-Linie.",
          description=[
              "Leg &6Rohes Eisen&r in einen Ofen oder Schmelzofen. Ein Rohes Erz wird ein &6Eisenbarren&r, ein Erzblock mit Behutsamkeit ebenso.",
              "",
              "Das ist die Zahl, an der sich alles misst: &e1 Barren pro Erz&r. Jede Stufe der Leiter legt einen Barren drauf, bis es in Stufe 4 fünf sind.",
              "",
              "Mit &6Glück III&r fallen aus einem Erzblock im Schnitt etwa 2,2 Rohe Erze. Schon für den Ofen ist Glück also eine Verdopplung.",
          ],
          tasks=[task_item("minecraft:iron_ingot", 32)],
          rewards=[reward_item("minecraft:raw_iron", 16), reward_xp(3)],
          deps=["welcome"], icon="minecraft:furnace"),

    quest("fortune", 5.25, 1.5, "&eNimm Glück III mit",
          subtitle="Rohes Erz ist auf jeder Stufe besser als der Block.",
          description=[
              "Bau Erz ab jetzt mit &6Glück III&r ab, nicht mit Behutsamkeit. Rohes Erz bringt auf jeder Stufe der Leiter mehr als der Erzblock.",
              "",
              "&eBarren pro Erzblock, Block mit Behutsamkeit gegen Rohes Erz mit Glück III:&r",
              "Ofen: 1 gegen etwa 2,2.",
              "Anreicherungskammer: 2 gegen rund 2,9 (drei Rohe Erze geben vier Staub).",
              "Klärkammer: 3 gegen rund 4,4 (ein Rohes Erz gibt zwei Klumpen).",
              "Injektionskammer: 4 gegen rund 5,9 (drei Rohe Erze geben acht Splitter).",
              "Auflösungskammer: 5 gegen rund 7,3 (drei Rohe Erze geben 2 000 mB Schlamm, also zehn Kristalle).",
              "",
              "Der &6Digitale Miner&r aus Stufe 3 kennt kein Glück, er lässt pro Block ein Rohes Erz fallen. Behutsamkeit kostet ihn das Zwölffache an Strom und lohnt sich hier nicht.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["furnace"], icon="minecraft:raw_gold", optional=True),

    quest("ore_map", 7.75, 1.5, "&7Merk dir, wo die Erze liegen",
          subtitle="Jedes Metall hat seine Höhe.",
          description=[
              "&eLaut Server-Config:&r",
              "&6Zinn:&r zwischen Y -32 und Y 94.",
              "&6Blei:&r ganz unten bis Y 64, am meisten in der Tiefenschieferschicht.",
              "&6Uran:&r nur tief, unter Y 8. Viele Adern liegen im Stein vergraben und berühren keine Höhle.",
              "&6Fluorit:&r unter Y 23, ein Teil davon nur in festem Stein unter Y 4.",
              "&6Osmium:&r große Adern im Gebirge über Y 72, dazu kleinere von ganz unten bis Y 64.",
              "",
              "Ein Strip-Mine-Gang auf Y -16 trifft fast alles auf einmal. Salz liegt in Tonablagerungen unter Wasser.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_item("minecraft:torch", 32), reward_xp(3)],
          deps=["furnace"], icon="mekanism:raw_tin", optional=True),

    # ---- 2x: Anreichern -------------------------------------------------------------
    quest("enrichment", 0, 5.5, "&d&lBau eine Anreicherungskammer",
          subtitle="Zwei Staub aus einem Erz.",
          description=[
              "&eRezept:&r ein &6Stahlgehäuse&r in die Mitte, zwei &6Eisenbarren&r links und rechts, zwei &6Einfache Steuerschaltkreise&r oben und unten, Redstone in die Ecken.",
              "",
              "&eWas hinein darf:&r Ein Erzblock wird zu &e2 Staub&r, drei Rohe Erze zu &e4 Staub&r, ein Block aus Rohem Erz zu &e12 Staub&r. Das gilt für Eisen, Kupfer, Gold, Osmium, Zinn, Blei und Uran.",
              "",
              "Sie zieht etwa &d20 FE/t&r, solange sie arbeitet. Ein brennender Wärmegenerator (80 FE/t) daneben reicht für sie und den Schmelzer.",
              "",
              "Den Einfachen Steuerschaltkreis gibt es auf Kronwerke nur aus Elektronenröhre und 20 mB Redstone in der Infusionsanlage, siehe Kapitel Mekanism.",
          ],
          tasks=[task_item("mekanism:enrichment_chamber", 1)],
          rewards=[reward_item("minecraft:raw_iron", 16), reward_table("s2_common"), reward_xp(5)],
          deps=["furnace"], icon="mekanism:enrichment_chamber", size=1.5, shape="hexagon"),

    quest("dust", 2.5, 5.5, "&7Mach Staub aus Rohem Erz",
          subtitle="Drei hinein, vier heraus.",
          description=[
              "Leg &6Rohes Eisen&r und &6Rohes Kupfer&r in den linken Slot der Kammer. Je drei werden zu vier &6Staub&r. Der Rest bleibt liegen, bis wieder drei zusammen sind.",
              "",
              "Staub ist noch kein Barren. Er geht in den Ofen, in den Schmelzofen oder in den Energiegeladenen Schmelzer der nächsten Quest.",
              "",
              "&eNebenbei:&r Dieselbe Kammer macht aus Kohle &6Angereicherten Kohlenstoff&r (80 mB statt 10 mB in der Infusionsanlage) und aus einem Salzblock vier &6Salz&r. Das Salz brauchst du in Stufe 4 wieder.",
          ],
          tasks=[task_item("mekanism:dust_iron", 32), task_item("mekanism:dust_copper", 32)],
          rewards=[reward_item("minecraft:raw_iron", 32), reward_item("minecraft:raw_copper", 16)],
          deps=["enrichment"], icon="mekanism:dust_iron"),

    quest("smelter", 5, 5.5, "&6Bau einen Energiegeladenen Schmelzer",
          subtitle="Staub wird Barren, ohne Kohle.",
          description=[
              "&eRezept:&r wie die Anreicherungskammer, nur mit &6Glas&r statt der Eisenbarren links und rechts: Stahlgehäuse in die Mitte, zwei Schaltkreise, Redstone in die Ecken.",
              "",
              "Er schmilzt alles, was ein Ofen schmilzt, für etwa &d20 FE/t&r und ohne Brennstoff. Stell ihn direkt neben die Kammer und schalte an der Kammer den &eAuto-Auswurf&r ein (Reiter oben links im Fenster), dann wandert der Staub von selbst hinüber.",
              "",
              "Ein normaler Ofen tut es auch. Aber der Schmelzer kann später eine Fabrik werden, der Ofen nicht.",
          ],
          tasks=[task_item("mekanism:energized_smelter", 1)],
          rewards=[reward_item("mekanism:basic_control_circuit", 2), reward_xp(5)],
          deps=["dust"], icon="mekanism:energized_smelter"),

    quest("line2", 7.5, 5.5, "&d&lStell die Zweifach-Straße auf",
          subtitle="Kiste, Kammer, Schmelzer, Kiste.",
          description=[
              "Kiste, dann &6Einfache Logistiktransporter&r (zwei Stahl, ein Schaltkreis, gibt acht) zur Kammer, Auto-Auswurf, Transporter zum Schmelzer, Auto-Auswurf, Transporter in die Ausgangskiste. Strom an beide über Universalkabel.",
              "",
              "Mit dem &6Konfigurator&r stellst du die Transporterseite an der Eingangskiste auf &eZiehen&r, sonst holt der Transporter nichts heraus. Ein einfacher Transporter schafft einen Gegenstand pro halbe Sekunde, für eine einzelne Kammer reicht das lange.",
              "",
              "Zum Beweis: 32 Osmiumstaub, die durch diese Straße gelaufen sind. Osmium brauchst du für jede Maschine, die noch kommt.",
              "",
              "&eKronwerke:&r Hinter dem Schmelzer ist der Platz für die Stahlstraße aus dem Kapitel Mekanism. Mehr Eisen heißt mehr Stahl für das Ziel von Stufe 3.",
          ],
          tasks=[task_item("mekanism:basic_logistical_transporter", 16), task_item("mekanism:dust_osmium", 32)],
          rewards=[reward_table("s2_uncommon"), reward_item("mekanism:raw_osmium", 16), reward_xp(10)],
          deps=["smelter"], icon="mekanism:dust_osmium", size=1.75, shape="gear"),

    quest("tin_lead", 10, 5.5, "&7Schick Zinn und Blei hinterher",
          subtitle="Dieselbe Straße, andere Metalle.",
          description=[
              "Die Zweifach-Straße nimmt jedes Metall von Mekanism. Wirf &6Rohes Zinn&r und &6Rohes Blei&r in die Eingangskiste, heraus kommen Barren, zwei pro Erzblock.",
              "",
              "&eZinn&r brauchst du für Bronze, Seismischen Vibrator, Taucherflasche und Widerstandsheizer. &eBlei&r für Reaktorglas, QIO und den Spaltreaktor in Stufe 5. Beides liegt nicht im Weg, also sammle es jetzt mit.",
          ],
          tasks=[task_item("mekanism:ingot_tin", 16), task_item("mekanism:ingot_lead", 16)],
          rewards=[reward_item("mekanism:raw_tin", 16), reward_item("mekanism:raw_lead", 16)],
          deps=["line2"], icon="mekanism:ingot_tin"),

    quest("sorter", 12.5, 5.5, "&eSortier die Barren",
          subtitle="Ein Sortierer am Ausgang.",
          description=[
              "&6Logistischer Sortierer:&r Eisen rundherum, oben in der Mitte ein Kolben, in der Mitte ein Schaltkreis. Er zieht aus der Kiste hinter ihm und schiebt in den Transporter vor ihm.",
              "",
              "Gib ihm einen Filter pro Barrensorte, zum Beispiel einen Tag wie &ec:ingots/osmium&r, und jedem Filter eine &eFarbe&r. Gefärbte Gegenstände laufen nur durch Transporter dieser Farbe. So landen Osmium, Kupfer und Eisen jedes in seiner eigenen Kiste, und der Rest nimmt den ungefärbten Weg.",
              "",
              "Die Transporter färbst du mit dem Konfigurator im Modus Färben.",
          ],
          tasks=[task_item("mekanism:logistical_sorter", 1)],
          rewards=[reward_item("minecraft:piston", 2), reward_xp(5)],
          deps=["line2"], icon="mekanism:logistical_sorter", optional=True),

    quest("raw_blocks", 10, 6.5, "&6Pack Rohes Erz in Blöcke",
          subtitle="Neunmal so viel pro Arbeitsgang.",
          description=[
              "Neun Rohe Erze ergeben an der Werkbank einen &6Block aus Rohem Erz&r. Die Anreicherungskammer macht daraus &e12 Staub&r, genau so viel wie aus neun einzelnen Rohen Erzen.",
              "",
              "Der Unterschied: Der Block ist &eein&r Arbeitsgang. Drei Rohe Erze brauchen genauso lange wie ein ganzer Block. Eine Kammer schafft mit Blöcken also neunmal so viel Erz pro Minute, und der Transporter trägt ein Stück statt neun.",
              "",
              "Die Klärkammer in Stufe 3 macht aus einem Block 18 Klumpen, auch dort in einem Gang.",
          ],
          tasks=[task_item("minecraft:raw_iron_block", 4)],
          rewards=[reward_item("minecraft:raw_iron", 18), reward_xp(5)],
          deps=["line2"], icon="minecraft:raw_iron_block"),

    quest("uranium", 12.5, 6.5, "&aLeg Uran auf Vorrat",
          subtitle="Heute nutzlos, in Stufe 3 und 5 gesucht.",
          description=[
              "&6Rohes Uran&r aus der Tiefe durch die Straße, wie jedes Metall. Für den Haken acht &6Uranbarren&r.",
              "",
              "&eWozu:&r In der Energizing Orb von &bPowah&r wird ein Uranbarren für 30 000 FE zu Uraninit, dem Brennstoff des Powah-Reaktors (Stufe 3). In Stufe 5 macht die Anreicherungskammer aus einem Barren zwei Gelbkuchen, der Anfang des Spaltbrennstoffs.",
              "",
              "Barren strahlen nicht. Lager sie in einer Kiste, bis du sie brauchst.",
          ],
          tasks=[task_item("mekanism:ingot_uranium", 8)],
          rewards=[reward_item("mekanism:raw_uranium", 8), reward_xp(5)],
          deps=["tin_lead"], icon="mekanism:ingot_uranium", optional=True),

    quest("gem_ores", 2.5, 6.5, "&cReichere Redstone-Erz an",
          subtitle="Mit Behutsamkeit, nicht mit Glück.",
          description=[
              "Die Anreicherungskammer nimmt auch Erzblöcke ohne Barren: &6Redstone-Erz&r gibt &e12 Redstone&r, &6Lapislazulierz&r &e12 Lapislazuli&r, Kohle-, Diamant-, Smaragd- und Quarzerz je &e2&r.",
              "",
              "&eWas sich lohnt:&r Bei Redstone schlägt die Kammer Glück III deutlich, hier also mit Behutsamkeit abbauen. Bei Diamant, Smaragd, Kohle, Quarz und Lapislazuli bringt Glück III im Schnitt etwas mehr. Die bleiben bei der Glück-Spitzhacke.",
          ],
          tasks=[task_checkmark("Redstone-Erz angereichert")],
          rewards=[reward_item("minecraft:redstone_block", 4), reward_xp(3)],
          deps=["enrichment"], icon="minecraft:redstone_ore", optional=True),

    quest("fluorite", 5, 6.5, "&bSammle Fluorit",
          subtitle="Sechs Stück pro Erz.",
          description=[
              "Fluoriterz liegt tief, unter Y 23. Abgebaut lässt es &e2 bis 4 Fluorit&r fallen, mit Glück III im Schnitt gut 6. Mit &6Behutsamkeit&r bleibt der Erzblock ganz, und die Anreicherungskammer macht daraus genau &e6&r. Das lohnt sich, wenn du keine Glück-Spitzhacke hast.",
              "",
              "Fluorit brauchst du später an vielen Stellen: im Chemischen Kristallisator der Fünffach-Straße, als Flusssäure im Spaltbrennstoff, als Staub für Polonium- und Plutonium-Pellets. Neun ergeben einen Block, so lagert es sich gut.",
          ],
          tasks=[task_item("mekanism:fluorite_gem", 12)],
          rewards=[reward_item("mekanism:fluorite_gem", 6), reward_xp(5)],
          deps=["gem_ores"], icon="mekanism:fluorite_gem", optional=True),

    quest("netherite", 0, 6.5, "&8Verdreifache Antiken Schrott",
          subtitle="Zerkleinerer und Kammer statt Ofen.",
          description=[
              "Im Ofen gibt ein &6Antiker Schrott&r eine &6Netheritplatte&r. Im &6Zerkleinerer&r wird er zu &e3 Dreckigen Netheritplatten&r, und die Anreicherungskammer macht aus jeder eine saubere Netheritplatte.",
              "",
              "Dreimal so viel Netherit aus jedem Fund im Nether. Vier Platten und vier Gold sind ein Netheritbarren, die MekaSuit in Stufe 4 braucht vier davon.",
          ],
          tasks=[task_item("mekanism:dirty_netherite_scrap", 3)],
          rewards=[reward_item("minecraft:gold_ingot", 8), reward_xp(10)],
          deps=["enrichment"], icon="minecraft:ancient_debris", optional=True),

    # ---- 3x: Klären -----------------------------------------------------------------
    quest("separator", 0, 9.5, "&bBau einen Elektrolyseur",
          subtitle="Wasser wird Wasserstoff und Sauerstoff.",
          description=[
              "&6Elektrolytischer Kern:&r fünf &6Infundierte Legierungen&r in die Ecken und die Mitte, &6Osmiumstaub&r oben und unten, links ein &6Eisenstaub&r, rechts ein &6Goldstaub&r. &6Elektrolyseur:&r der Kern in die Mitte, Infundierte Legierung links und rechts, Redstone oben und unten, Eisen in die Ecken.",
              "",
              "Aus &e2 mB Wasser&r macht er &e2 mB Wasserstoff&r und &e1 mB Sauerstoff&r. Die Klärkammer der Dreifach-Straße braucht den Sauerstoff. Der Wasserstoff fällt doppelt an: stell seinen Tank im Fenster auf &eAblassen&r, bis du ihn in Stufe 4 für Chlorwasserstoff brauchst.",
              "",
              "Der Elektrolyseur ist in Stufe 2 offen. Bau ihn ruhig jetzt, dann steht er, wenn Stufe 3 die Klärkammer öffnet.",
          ],
          tasks=[task_item("mekanism:electrolytic_separator", 1)],
          rewards=[reward_item("mekanism:basic_pressurized_tube", 8), reward_xp(5)],
          deps=["line2"], icon="mekanism:electrolytic_separator"),

    quest("pump", 2.5, 9.5, "&bPump Wasser hinein",
          subtitle="Elektrische Pumpe und Rohrleitungen.",
          description=[
              "&6Elektrische Pumpe:&r ein Eimer oben in der Mitte, Infundierte Legierung links und rechts von einem &6Stahlgehäuse&r, unten drei &6Osmiumbarren&r. &6Einfache Rohrleitung:&r zwei Stahlbarren mit einem Eimer dazwischen, gibt acht.",
              "",
              "Die Pumpe steht über dem Wasser und zieht etwa &d40 FE/t&r. Von ihr führt eine Rohrleitung zum Elektrolyseur; eine einfache schafft &e250 mB/t&r, mehr als genug. Ein Becken von zwei mal zwei Wasser füllt sich von selbst nach.",
              "",
              "Für den Anfang tut es auch ein Wassereimer im Slot des Elektrolyseurs.",
          ],
          tasks=[task_item("mekanism:electric_pump", 1), task_item("mekanism:basic_mechanical_pipe", 8)],
          rewards=[reward_item("mekanism:basic_mechanical_pipe", 8), reward_xp(5)],
          deps=["separator"], icon="mekanism:electric_pump"),

    quest("purification", 5, 9.5, "&d&lBau eine Klärkammer",
          subtitle="Drei Klumpen aus einem Erz. Stufe 3.",
          description=[
              "&eRezept:&r eine &6Anreicherungskammer&r in die Mitte, Osmiumbarren links und rechts, &6Fortschrittliche Steuerschaltkreise&r oben und unten, Infundierte Legierung in die Ecken. Die Schaltkreise öffnen mit &6Stufe 3&r (Gedrucktes Silizium aus AE2), vorher geht hier nichts.",
              "",
              "&eWas herauskommt:&r Ein Erzblock gibt &e3 Klumpen&r, ein Rohes Erz &e2 Klumpen&r, ein Block aus Rohem Erz &e18&r. Dabei frisst sie rund &e1 mB Sauerstoff pro Tick&r und etwa &d80 FE/t&r, viermal so viel wie die Anreicherungskammer.",
              "",
              "Den Sauerstoff bringst du mit Druckschläuchen vom Elektrolyseur. Zum Testen tut es auch &6Feuerstein&r im Chemikalien-Slot: 10 mB pro Stück.",
              "",
              img(item_texture("mekanism:clump_iron"), 32, 32),
              "",
              "Die Aufgabe sind 16 Eisenklumpen. Die gibt es erst in Stufe 3, die Quest wartet so lange.",
          ],
          tasks=[task_item("mekanism:clump_iron", 16)],
          rewards=[reward_item("minecraft:raw_iron", 32), reward_table("s2_common"), reward_xp(10)],
          deps=["separator"], icon="mekanism:clump_iron", size=1.75, shape="hexagon"),

    quest("crush", 7.5, 9.5, "&4Zerkleinere die Klumpen",
          subtitle="Klumpen wird Dreckiger Staub.",
          description=[
              "Schick die &6Klumpen&r durch den &6Zerkleinerer&r. Jeder Klumpen wird ein &6Dreckiger Staub&r, eins zu eins, für etwa &d20 FE/t&r.",
              "",
              "&eRezept auf Kronwerke:&r Stahlgehäuse in die Mitte, links und rechts ein &6Mahlwerkrad&r von Create statt der Lavaeimer, Schaltkreise oben und unten, Redstone in die Ecken. Die Räder kommen aus den Mechanischen Handwerkseinheiten, zwei pro Rezept, siehe Kapitel Create: Messing.",
              "",
              "Der Zerkleinerer ist Stufe 2. Hast du ihn schon aus dem Kapitel Mekanism, stell ihn einfach hinter die Klärkammer.",
          ],
          tasks=[task_item("mekanism:dirty_dust_iron", 16)],
          rewards=[reward_item("minecraft:raw_copper", 32), reward_xp(5)],
          deps=["purification"], icon="mekanism:dirty_dust_iron"),

    quest("clean", 10, 9.5, "&7Reinige den Staub und schmilz ihn",
          subtitle="Anreicherungskammer, dann Schmelzer, wie gehabt.",
          description=[
              "&6Dreckiger Staub&r in die &6Anreicherungskammer&r: eins zu eins wird daraus sauberer &6Staub&r. Dann in den Schmelzer, Barren heraus.",
              "",
              "Die Dreifach-Straße ist also die Zweifach-Straße mit zwei Maschinen davor: &eKlärkammer, Zerkleinerer, Anreicherungskammer, Schmelzer&r. Kammer und Schmelzer von vorhin bleiben, wo sie sind.",
              "",
              "&cAchtung:&r Rohes Erz gehört jetzt vor die Klärkammer, nicht mehr in die Anreicherungskammer. Sonst verschenkst du einen Barren pro Erz.",
          ],
          tasks=[task_item("mekanism:dust_iron", 48, title="Eisenstaub aus Dreckigem Staub")],
          rewards=[reward_item("minecraft:raw_gold", 16), reward_item("mekanism:enriched_carbon", 16), reward_xp(5)],
          deps=["crush"], icon="mekanism:dust_iron"),

    quest("layout", 2.5, 11.75, "&eVerlege die Leitungen",
          subtitle="Transporter, Druckschläuche, Rohrleitungen.",
          description=[
              "Drei Leitungen, alle aus zwei &6Stahlbarren&r und einem Teil in der Mitte, immer acht Stück: &6Logistiktransporter&r mit Schaltkreis für Gegenstände, &6Druckschlauch&r mit Glas für Gase, &6Rohrleitung&r mit Eimer für Flüssigkeiten.",
              "",
              "&eWas wohin:&r Rohrleitung von der Pumpe zum Elektrolyseur (Wasser). Druckschlauch vom Elektrolyseur zur Klärkammer (Sauerstoff). Transporter von der Kiste zu Klärkammer, Zerkleinerer, Anreicherungskammer, Schmelzer und in die Kiste. Universalkabel an alles.",
              "",
              "&eDurchsatz der einfachen Stufe:&r Transporter 1 Gegenstand pro halbe Sekunde, Druckschlauch 750 mB/t, Rohrleitung 250 mB/t. Das reicht für Einzelmaschinen; Fabriken wollen später die fortschrittliche Stufe.",
              "",
              "&eTipp:&r Leitungen verbinden sich mit allem Passenden daneben. Mit dem Konfigurator färbst du Transporter oder stellst eine Seite auf &eKeine&r, dann bleiben zwei Straßen getrennt.",
          ],
          tasks=[task_item("mekanism:basic_pressurized_tube", 16), task_item("mekanism:basic_universal_cable", 16)],
          rewards=[reward_item("mekanism:basic_logistical_transporter", 16), reward_table("s2_common"), reward_xp(5)],
          deps=["pump"], icon="mekanism:basic_pressurized_tube"),

    quest("tripling", 12.5, 9.5, "&d&lLass die Dreifach-Straße laufen",
          subtitle="Drei Barren aus einem Erz.",
          description=[
              "Füttere die Straße mit allem, was du findest: &6Eisen, Kupfer, Gold, Osmium, Zinn, Blei, Uran&r. Zum Beweis 32 Osmiumklumpen und 16 Zinnklumpen.",
              "",
              "Wenn die Klärkammer stehen bleibt, fehlt fast immer Sauerstoff oder Strom: 80 FE/t für die Kammer, dazu Elektrolyseur, Pumpe und drei Maschinen dahinter. Ein Einfacher Energie-Würfel als Puffer und ein zweiter Wärmegenerator helfen.",
              "",
              "&eKronwerke:&r Für das Ziel von Stufe 3 (4 000 Stahlbarren) ist das die Eisenquelle. Stell die Stahlstraße direkt dahinter.",
              "",
              "&eNächste Stufe:&r 4x braucht die Chemische Injektionskammer mit Elite-Schaltkreisen aus Stufe 4. Bis dahin ist 3x das Beste, was Mekanism kann.",
          ],
          tasks=[task_item("mekanism:clump_osmium", 32), task_item("mekanism:clump_tin", 16)],
          rewards=[reward_item("minecraft:raw_iron", 64), reward_table("s2_uncommon"), reward_xp(15)],
          deps=["clean", "layout"], icon="mekanism:clump_osmium", size=1.75, shape="gear"),

    # ---- 4x: Injizieren -------------------------------------------------------------
    quest("infuser", 0, 15.5, "&bBau einen Chemischen Injektor",
          subtitle="Zwei Gase werden eins.",
          description=[
              "&eRezept:&r ein &6Stahlgehäuse&r in die Mitte, zwei &6Einfache Chemikalienbehälter&r links und rechts, Einfache Steuerschaltkreise oben und unten, Infundierte Legierung in die Ecken. Der Chemikalienbehälter: vier Osmiumbarren an den Seiten, Redstone in den Ecken, Mitte frei.",
              "",
              "Er nimmt zwei Gase, links und rechts, und macht ein drittes: &e1 mB Wasserstoff + 1 mB Chlor = 1 mB Chlorwasserstoff&r. Das ist das Gas der Injektionskammer. Er zieht etwa &d80 FE/t&r.",
              "",
              "Den Wasserstoff hast du: der Elektrolyseur der Dreifach-Straße macht ihn doppelt so schnell wie Sauerstoff. Jetzt nicht mehr ablassen, sondern per Druckschlauch hierher.",
              "",
              "Der Injektor ist Stufe 2. Später macht derselbe Maschinentyp auch Schwefeltrioxid und Schwefelsäure für die Fünffach-Straße.",
          ],
          tasks=[task_item("mekanism:chemical_infuser", 1)],
          rewards=[reward_item("mekanism:basic_chemical_tank", 2), reward_xp(5)],
          deps=["tripling"], icon="mekanism:chemical_infuser"),

    quest("chlorine", 2.5, 15.5, "&aMach Chlor aus Sole",
          subtitle="Salz, Oxidierer, zweiter Elektrolyseur.",
          description=[
              "Ein zweiter &6Elektrolyseur&r mit &6Sole&r statt Wasser: &e10 mB Sole&r werden &e1 mB Natrium&r und &e1 mB Chlor&r. Die Sole macht der &6Chemische Oxidierer&r aus &6Salz&r, 15 mB pro Stück.",
              "",
              "&6Chemischer Oxidierer:&r Infundierte Legierung in die Ecken, Schaltkreise oben und unten, links eine Persönliche Truhe, in der Mitte ein &6Dynamischer Tank&r, rechts ein Einfacher Chemikalienbehälter. Etwa &d80 FE/t&r.",
              "",
              "&eSalz:&r Salzblöcke liegen in Tonablagerungen unter Wasser, ein Block gibt in der Anreicherungskammer 4 Salz. Ohne Salz macht eine &6Wärmeverdampfungsanlage&r aus 10 mB Wasser 1 mB Sole, langsam und mit Sonne.",
              "",
              "&eAbkürzung für den Anfang:&r Salz direkt in den Chemikalien-Slot der Injektionskammer gibt &e2 mB Chlorwasserstoff&r pro Stück, ganz ohne Gase.",
          ],
          tasks=[task_item("mekanism:chemical_oxidizer", 1), task_item("mekanism:salt", 16)],
          rewards=[reward_item("mekanism:block_salt", 8), reward_xp(5)],
          deps=["infuser"], icon="mekanism:salt"),

    quest("injection", 5, 15.5, "&d&lBau eine Chemische Injektionskammer",
          subtitle="Vier Splitter aus einem Erz. Stufe 4.",
          description=[
              "&eRezept:&r die &6Klärkammer&r in die Mitte, Goldbarren links und rechts, &6Elite-Steuerschaltkreise&r oben und unten, &6Verstärkte Legierung&r in die Ecken. Elite-Schaltkreise brauchen Draconiumstaub aus dem End, also &6Stufe 4&r.",
              "",
              "&eWas herauskommt:&r Ein Erzblock gibt &e4 Splitter&r, drei Rohe Erze &e8&r, ein Block aus Rohem Erz &e24&r. Sie frisst rund 1 mB Chlorwasserstoff pro Tick und etwa &d160 FE/t&r, doppelt so viel wie die Klärkammer.",
              "",
              "Die Kammer kommt vor die Dreifach-Straße. Du baust nichts um, du stellst eine Maschine davor.",
              "",
              "Hak die Quest ab, sobald sie steht. Vorher kannst du nichts davon bauen, die Zutaten sind gesperrt.",
          ],
          tasks=[task_checkmark("Injektionskammer steht (Stufe 4)")],
          rewards=[reward_xp(5)],
          deps=["chlorine"], icon="mekanism:basic_chemical_tank", size=1.75, shape="hexagon"),

    quest("shards", 7.5, 15.5, "&d&lLass Splitter durch die Straße laufen",
          subtitle="Splitter, Klumpen, Staub, Barren.",
          description=[
              "Die &6Splitter&r gehen in die &6Klärkammer&r: ein Splitter und 1 mB Sauerstoff geben einen &6Klumpen&r. Dann Zerkleinerer, Anreicherungskammer, Schmelzer wie bisher.",
              "",
              "&eDie Vierfach-Straße:&r Injektionskammer, Klärkammer, Zerkleinerer, Anreicherungskammer, Schmelzer. Fünf Maschinen, zwei Gase (Chlorwasserstoff, Sauerstoff), ein Elektrolyseur für Wasser und einer für Sole.",
              "",
              "&eNebenbei:&r &6Schießpulver&r in der Injektionskammer wird zu &6Schwefelstaub&r, 1 mB Chlorwasserstoff pro Stück. Heb ihn auf, die Fünffach-Straße läuft auf Schwefel.",
              "",
              "Mit Glück III sind das rund 5,9 Barren pro abgebautem Erz.",
          ],
          tasks=[task_checkmark("32 Splitter durch die Straße geschickt")],
          rewards=[reward_xp(10)],
          deps=["injection"], icon="minecraft:raw_iron", size=1.75, shape="gear"),

    # ---- 5x: Auflösen ---------------------------------------------------------------
    quest("oxidizer", 0, 19.5, "&eMach Schwefeldioxid",
          subtitle="Schwefelstaub in den Oxidierer.",
          description=[
              "Leg &6Schwefelstaub&r in den &6Chemischen Oxidierer&r (den aus der Sole-Quest oder einen zweiten). Jeder Staub gibt &e100 mB Schwefeldioxid&r.",
              "",
              "Schwefel kommt aus Schießpulver in der Injektionskammer. Der Oxidierer nimmt jeden Schwefelstaub: drei &6Schwefelessenzen&r von Mystical Agriculture ergeben an der Werkbank acht, und der Zerkleinerer von Immersive Engineering lässt bei Kohleerz zu 15 Prozent einen fallen.",
              "",
              "Der Oxidierer braucht etwa &d80 FE/t&r. Sein Gas geht per Druckschlauch weiter in den Chemischen Injektor.",
          ],
          tasks=[task_item("mekanism:dust_sulfur", 16)],
          rewards=[reward_item("minecraft:gunpowder", 16), reward_xp(5)],
          deps=["shards"], icon="mekanism:dust_sulfur"),

    quest("acid", 2.5, 19.5, "&eBraue Schwefelsäure",
          subtitle="Trioxid, Wasserdampf, Säure.",
          description=[
              "Im &6Chemischen Injektor&r: &e2 mB Schwefeldioxid + 1 mB Sauerstoff = 2 mB Schwefeltrioxid&r. Im zweiten Injektor: &e1 mB Schwefeltrioxid + 1 mB Wasserdampf = 1 mB Schwefelsäure&r.",
              "",
              "&eWasserdampf:&r ein &6Rotationskondensator&r im Modus Verdampfen macht aus Wasser Wasserdampf, 1 zu 1. &eRezept:&r Glas in die Ecken, Schaltkreise oben und unten, links ein Chemikalienbehälter, in der Mitte ein &6Energietablett&r, rechts ein Flüssigkeitsbehälter. Etwa &d20 FE/t&r.",
              "",
              "Der Sauerstoff kommt vom Elektrolyseur der Dreifach-Straße. Säure ist ein Gas, sie läuft in Druckschläuchen und Chemikalienbehältern.",
              "",
              "&eAbkürzung:&r Schwefelstaub direkt in den Slot der Auflösungskammer gibt &e2 mB Schwefelsäure&r pro Stück. Zum Testen reicht das.",
          ],
          tasks=[task_item("mekanism:rotary_condensentrator", 1), task_item("mekanism:chemical_infuser", 2)],
          rewards=[reward_item("mekanism:energy_tablet", 1), reward_xp(5)],
          deps=["oxidizer"], icon="mekanism:rotary_condensentrator"),

    quest("dissolution", 5, 19.5, "&d&lBau eine Chemische Auflösungskammer",
          subtitle="Aus Erz wird Schlamm. Stufe 4.",
          description=[
              "&eRezept:&r Stahlgehäuse in die Mitte, &6Ultimative Steuerschaltkreise&r links und rechts, Einfache Chemikalienbehälter oben und unten, &6Raffiniertes Obsidian&r in die Ecken. Ultimative Schaltkreise sind &6Stufe 4&r (ein Elite-Schaltkreis zwischen zwei Atomlegierungen).",
              "",
              "&eWas herauskommt:&r Ein Erzblock gibt &e1 000 mB Schmutzigen Schlamm&r, drei Rohe Erze &e2 000 mB&r, ein Block aus Rohem Erz &e6 000 mB&r. Dabei rund 1 mB Schwefelsäure pro Tick und etwa &d160 FE/t&r.",
              "",
              "Schlamm ist ein Gas. Er geht in Druckschläuche oder Chemikalienbehälter, nie in eine Kiste. Jedes Metall hat seinen eigenen Schlamm, misch die Leitungen nicht.",
          ],
          tasks=[task_checkmark("Auflösungskammer steht (Stufe 4)")],
          rewards=[reward_xp(5)],
          deps=["acid"], icon="mekanism:basic_chemical_tank", size=1.75, shape="hexagon"),

    quest("washer", 7.5, 19.5, "&bBau eine Chemische Waschanlage",
          subtitle="Schmutziger Schlamm wird sauber.",
          description=[
              "&eRezept:&r Stahlgehäuse in die Mitte, Ultimative Schaltkreise links und rechts, oben ein &6Einfacher Flüssigkeitsbehälter&r, unten ein Einfacher Chemikalienbehälter, Raffiniertes Obsidian in die Ecken.",
              "",
              "Sie wäscht &e1 mB Schmutzigen Schlamm&r mit &e5 mB Wasser&r zu &e1 mB Sauberem Schlamm&r. Für die 1 000 mB eines Erzblocks sind das fünf Eimer Wasser. Gib ihr eine eigene Pumpe mit Rohrleitung.",
              "",
              "Etwa &d80 FE/t&r. Ohne Wasser steht die ganze Fünffach-Straße, also zuerst das Wasser.",
          ],
          tasks=[task_checkmark("Waschanlage steht (Stufe 4)")],
          rewards=[reward_xp(5)],
          deps=["dissolution"], icon="mekanism:basic_fluid_tank"),

    quest("crystallizer", 10, 19.5, "&bBau einen Chemischen Kristallisator",
          subtitle="Fünf Kristalle aus einem Erz.",
          description=[
              "&eRezept:&r Stahlgehäuse in die Mitte, Ultimative Schaltkreise links und rechts, &6Fluorit&r oben und unten, Raffiniertes Obsidian in die Ecken. Fluorit liegt tief, ein Fluoriterz gibt in der Anreicherungskammer 6 Stück.",
              "",
              "Aus &e200 mB Sauberem Schlamm&r wird ein &6Kristall&r. Ein Erzblock (1 000 mB) gibt also &e5 Kristalle&r, drei Rohe Erze 10. Etwa &d160 FE/t&r.",
              "",
              "Der Kristall ist wieder ein Gegenstand. Ab hier geht es mit Transportern weiter.",
          ],
          tasks=[task_checkmark("Kristallisator steht (Stufe 4)")],
          rewards=[reward_xp(5)],
          deps=["washer"], icon="mekanism:fluorite_gem"),

    quest("quintupling", 12.5, 19.5, "&d&lLass die Fünffach-Straße laufen",
          subtitle="Fünf Barren aus einem Erz.",
          description=[
              "Die &6Kristalle&r gehen in die &6Injektionskammer&r: ein Kristall und 1 mB Chlorwasserstoff geben einen &6Splitter&r. Ab da läuft alles wie bei der Vierfach-Straße.",
              "",
              "&eDie ganze Leiter:&r Auflösungskammer, Waschanlage, Kristallisator, Injektionskammer, Klärkammer, Zerkleinerer, Anreicherungskammer, Schmelzer. Acht Maschinen, drei Gase (Schwefelsäure, Chlorwasserstoff, Sauerstoff) und viel Wasser, dazu zwei Elektrolyseure, zwei Injektoren, Oxidierer, Kondensator und Pumpen.",
              "",
              "&eStrom:&r Allein die acht Maschinen der Leiter ziehen zusammen rund &d700 FE/t&r, die Hilfsmaschinen kommen dazu. Das ist etwas für die Industrieturbine, nicht mehr für Wärmegeneratoren.",
              "",
              "&eLohnt sich das?&r Fünf statt vier pro Block, mit Glück III rund 7,3 Barren pro abgebautem Erz. Für Eisen, Kupfer und Gold in den Mengen von Stufe 4 und 5 ja. Für Osmium reicht meist die Dreifach-Straße.",
          ],
          tasks=[task_checkmark("16 Kristalle zu Barren gemacht")],
          rewards=[reward_xp(15)],
          deps=["crystallizer"], icon="mekanism:block_raw_osmium", size=1.75, shape="gear"),

    # ---- Fabriken und Upgrades ------------------------------------------------------
    quest("factory", 0, 23.5, "&aMach eine Einfache Fabrik",
          subtitle="Drei Plätze statt einem.",
          description=[
              "Der &6Einfache Stufen Installateur&r (Redstone in die Ecken, Schaltkreise oben und unten, Eisen links und rechts, ein Brett in die Mitte) macht per Rechtsklick aus jeder Maschine eine &6Einfache Fabrik&r. Oder an der Werkbank: dasselbe Muster mit der Maschine statt dem Brett.",
              "",
              "Eine Einfache Fabrik hat &e3 Plätze&r und arbeitet an drei Gegenständen gleichzeitig. Fabriken gibt es für Anreicherungskammer, Schmelzer, Zerkleinerer, Klärkammer, Injektionskammer, Infusionsanlage, Kompressor, Kombinierer und Sägewerk. Auflösungskammer, Waschanlage und Kristallisator bleiben Einzelmaschinen.",
              "",
              "Der Knopf mit den Pfeilen im Fenster verteilt Stapel auf alle Plätze. Jede Fabrik der Straße braucht das gleiche Tempo, sonst staut es sich vor der langsamsten.",
          ],
          tasks=[task_item("mekanism:basic_enriching_factory", 1)],
          rewards=[reward_item("mekanism:basic_control_circuit", 4), reward_table("s2_common"), reward_xp(5)],
          deps=["line2"], icon="mekanism:basic_enriching_factory", size=1.5, shape="hexagon"),

    quest("factory_adv", 2.5, 23.5, "&aStuf auf Fortschrittlich hoch",
          subtitle="Fünf Plätze. Stufe 3.",
          description=[
              "&6Fortgeschrittener Stufen Installateur:&r Infundierte Legierung in die Ecken, &6Fortschrittliche Steuerschaltkreise&r oben und unten, Osmium links und rechts, ein Brett in die Mitte. Rechtsklick auf die Einfache Fabrik, sie behält ihren Inhalt.",
              "",
              "Eine Fortschrittliche Fabrik hat &e5 Plätze&r. Werkbank-Weg: die Einfache Fabrik in die Mitte, sonst dasselbe Muster. Mit den Schaltkreisen öffnet das in &6Stufe 3&r, zusammen mit der Klärkammer.",
              "",
              "Dazu gehören die fortschrittlichen Leitungen: acht einfache um eine Infundierte Legierung ergeben acht fortschrittliche. Transporter 16 Gegenstände pro halbe Sekunde, Druckschlauch 2 000 mB/t, Rohrleitung 1 000 mB/t.",
          ],
          tasks=[task_checkmark("Eine Fortschrittliche Fabrik steht (Stufe 3)")],
          rewards=[reward_xp(5)],
          deps=["factory"], icon="mekanism:basic_smelting_factory"),

    quest("factory_elite", 5, 23.5, "&aStuf auf Elite und Ultimativ hoch",
          subtitle="Sieben, dann neun Plätze. Stufe 4.",
          description=[
              "&6Elite-Installateur:&r Verstärkte Legierung in die Ecken, &6Elite-Schaltkreise&r oben und unten, Gold links und rechts, ein Brett. &6Ultimativ-Installateur:&r Atomlegierung, &6Ultimative Schaltkreise&r, Diamanten, ein Brett. Beides &6Stufe 4&r.",
              "",
              "Elite-Fabrik &e7 Plätze&r, Ultimative Fabrik &e9 Plätze&r. Die Leitungen wachsen mit: acht fortschrittliche um eine Verstärkte Legierung ergeben Elite, acht Elite um eine Atomlegierung ergeben Ultimativ. Elite-Transporter 32 pro halbe Sekunde, Ultimativ 64, Elite-Druckschlauch 64 000 mB/t.",
              "",
              "&eTipp:&r Rechtsklick mit der nächsten Legierung auf eine liegende Leitung stuft sie an Ort und Stelle hoch, ohne Abbauen.",
          ],
          tasks=[task_checkmark("Eine Elite-Fabrik steht (Stufe 4)")],
          rewards=[reward_xp(5)],
          deps=["factory_adv"], icon="mekanism:basic_crushing_factory"),

    quest("speed", 0, 25.75, "&bSteck Geschwindigkeitsupgrades hinein",
          subtitle="Schneller, aber hungriger.",
          description=[
              "&6Geschwindigkeitsupgrade:&r Glas oben und unten, Infundierte Legierung links und rechts, &6Osmiumstaub&r in die Mitte. Es kommt in den Upgrade-Reiter rechts im Maschinenfenster.",
              "",
              "Bis zu &e8 Stück&r pro Maschine. Acht machen die Maschine &ezehnmal so schnell&r (Faktor 10 in der Server-Config), jedes einzelne ein Achtel des Weges dorthin. Der Strom pro Tick steigt dabei stärker als das Tempo: mit acht zieht sie das Hundertfache pro Tick, also zehnmal so viel pro Gegenstand.",
              "",
              "Bei Klärkammer und Injektionskammer steigt auch der Gasverbrauch pro Tick. Ohne mehr Sauerstoff bringt das Upgrade dort nichts.",
          ],
          tasks=[task_item("mekanism:upgrade_speed", 4)],
          rewards=[reward_item("mekanism:alloy_infused", 8), reward_xp(5)],
          deps=["factory"], icon="mekanism:upgrade_speed"),

    quest("energy", 2.5, 25.75, "&aSteck Energie-Upgrades hinein",
          subtitle="Sparsamer, mehr Puffer.",
          description=[
              "&6Energie Upgrade:&r Glas oben und unten, Infundierte Legierung links und rechts, &6Goldstaub&r in die Mitte.",
              "",
              "Ebenfalls bis zu &e8 Stück&r. Acht senken den Verbrauch pro Tick auf ein Zehntel und vergrößern den Energiespeicher der Maschine. Am Tempo ändern sie nichts.",
              "",
              "&eZusammen:&r 8 Geschwindigkeit und 8 Energie heben sich beim Strom pro Gegenstand genau auf: zehnmal so schnell für denselben Strom pro Barren, nur eben zehnmal so viel pro Tick. Das ist der Standard-Ausbau jeder Maschine in der Straße.",
          ],
          tasks=[task_item("mekanism:upgrade_energy", 4)],
          rewards=[reward_item("mekanism:dust_gold", 8), reward_xp(5)],
          deps=["speed"], icon="mekanism:upgrade_energy"),

    quest("chemical", 5, 25.75, "&8Steck ein Chemie-Upgrade hinein",
          subtitle="Weniger Gas pro Klumpen.",
          description=[
              "&6Chemie-Upgrade&r (Chemical Upgrade): Glas oben und unten, Infundierte Legierung links und rechts, &6Eisenstaub&r in die Mitte.",
              "",
              "Es gehört in Klärkammer, Injektionskammer und Auflösungskammer. Bis zu 8 Stück senken den Gasverbrauch wieder, den die Geschwindigkeitsupgrades hochtreiben. Mit acht und acht liegt der Verbrauch pro Klumpen wieder beim alten Wert.",
              "",
              "In der Anreicherungskammer oder dem Schmelzer bringt es nichts, die brauchen kein Gas.",
          ],
          tasks=[task_item("mekanism:upgrade_chemical", 1)],
          rewards=[reward_item("mekanism:alloy_infused", 4), reward_xp(3)],
          deps=["energy"], icon="mekanism:upgrade_chemical", optional=True),

    quest("full", 7.75, 25.75, "&6&lBestück eine Maschine voll",
          subtitle="Acht Geschwindigkeit, acht Energie.",
          description=[
              "Steck &e8 Geschwindigkeitsupgrades&r und &e8 Energie-Upgrades&r in eine Maschine. Für den Satz brauchst du 16 Glas, 16 Infundierte Legierungen, 8 Osmiumstaub und 8 Goldstaub.",
              "",
              "Die Maschine arbeitet jetzt zehnmal so schnell wie vorher und braucht pro Gegenstand genauso viel Strom wie ohne Upgrades. Eine so bestückte Anreicherungskammer zieht statt 20 nun &d200 FE/t&r, der Schmelzer ebenso.",
              "",
              "Die Aufgabe prüft 8 und 8 im Inventar. Mach den Satz zuerst für die langsamste Maschine der Straße, dann für die nächste. Auch Fabriken nehmen die Upgrades.",
          ],
          tasks=[task_item("mekanism:upgrade_speed", 8), task_item("mekanism:upgrade_energy", 8)],
          rewards=[reward_table("s2_rare"), reward_item("mekanism:upgrade_speed", 2), reward_xp(20)],
          deps=["speed", "energy"], icon="mekanism:upgrade_speed", size=1.75, shape="gear"),

    # ---- Mehr aus dem Erz -----------------------------------------------------------
    quest("create", 0, 29.5, "&6Mahl Erz mit Mahlwerkrädern",
          subtitle="Stufe 1: Create zerkleinert, aber verdoppelt nicht.",
          description=[
              "Zwei &6Mahlwerkräder&r nebeneinander, gegenläufig gedreht, &6Rohes Eisen&r von oben hinein. Heraus fällt &6Zerkleinertes Roheisen&r, dazu zu 75 Prozent ein Erfahrungsnugget.",
              "",
              "&eDie Zahlen:&r Rohes Erz gibt &e1 Zerkleinertes&r, mehr nicht. Ein Erzblock gibt 1 plus zu 75 Prozent ein zweites, ein Tiefenschiefer-Erzblock 2 plus zu 25 Prozent ein drittes. Zerkleinertes wird im Ofen ein Barren, oder beim Waschen 9 Nuggets plus zu 75 Prozent ein Redstone (bei Gold zu 50 Prozent ein Quarz).",
              "",
              "&eLohnt sich:&r in Stufe 1 für Erzblöcke mit Behutsamkeit (bis 2,25 Barren) und für die Nebenprodukte, für Rohes Erz nicht. &eRezept auf Kronwerke:&r der Zerkleinerer von Mekanism braucht zwei dieser Räder, du brauchst sie also sowieso.",
          ],
          tasks=[task_item("create:crushed_raw_iron", 16)],
          rewards=[reward_item("create:andesite_alloy", 16), reward_xp(3)],
          deps=["furnace"], icon="create:crushing_wheel"),

    quest("foundry", 2.5, 29.5, "&cSchmilz Erz in der Gießerei",
          subtitle="Stufe 2: zwei Barren ohne Strom.",
          description=[
              "Wirf &6Rohes Erz&r in die &6Gießerei&r von Productive Metalworks (Lava im Tank, Heizspulen im Boden). Ein Rohes Erz gibt &e180 mB&r flüssiges Metall, ein Barren braucht 90 mB: &ezwei Barren&r.",
              "",
              "Ein Erzblock gibt sogar &e270 mB&r, drei Barren. Staub, Zerkleinertes von Create und Barren geben je 90 mB. Gegossen wird mit der Barrenform auf dem Gießtisch; Bau und Guss stehen im Kapitel &6Productive Bees&r.",
              "",
              "&eLohnt sich:&r in Stufe 2 als Verdopplung ohne Strom, mit Behutsamkeit als einzige Verdreifachung vor Stufe 3. Dafür gibt es keine Nebenprodukte wie Angereicherten Kohlenstoff, und schnell ist sie nur mit vielen Heizspulen.",
          ],
          tasks=[task_item("productivemetalworks:ingot_cast", 1)],
          rewards=[reward_item("productivemetalworks:fire_brick", 16), reward_xp(5)],
          deps=["create"], icon="productivemetalworks:black_foundry_controller"),

    quest("ie", 5, 29.5, "&7Zerkleinere mit Immersive Engineering",
          subtitle="Stufe 3: zwei Staub und etwas Nickel.",
          description=[
              "Der &6Zerkleinerer&r von Immersive Engineering ist ein Multiblock aus 10 Leichten Ingenieursbausteinen, 10 Stahlgerüsten, 8 Stahlzäunen, 9 Trichtern und einem Redstone-Ingenieursbaustein. Die Ingenieursbausteine öffnen in &6Stufe 3&r (auf Kronwerke mit Messingblech).",
              "",
              "&eDie Zahlen:&r Erzblock &e2 Staub&r plus zu 10 Prozent ein Nickelstaub. Rohes Erz 1 Staub plus zu 33 Prozent ein zweiter, also wie die Anreicherungskammer. Block aus Rohem Erz 12 Staub. &e6 000 FE&r pro Erz.",
              "",
              "&eLohnt sich:&r wenn du IE sowieso spielst und Nickel willst. Gegen die Dreifach-Straße verliert er. Siehe Kapitel Immersive Engineering: Schwerindustrie.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["foundry"], icon="immersiveengineering:crusher", optional=True),

    quest("oritech", 7.5, 29.5, "&cPulverisiere mit Oritech",
          subtitle="Stufe 3: Pulverizer und Fragment Forge.",
          description=[
              "Der &6Pulverizer&r von Oritech (Stufe 3, 32 RF/t) macht aus einem Erzblock &e2 Rohe Erze&r und aus einem Rohen Erz &e1 Staub plus 3 kleine Staubhäufchen&r, neun kleine sind ein ganzer. Macht 1,33 pro Rohes Erz.",
              "",
              "Die &6Fragment Forge&r weiter hinten im Kapitel Oritech holt mit Zentrifuge und Wasser etwa &e2,7 Barren&r aus einem Rohen Erz, dazu Nickel nebenbei.",
              "",
              "&eLohnt sich:&r Der Pulverizer vor einer Mekanism-Straße macht aus einem Erzblock zwei Rohe Erze, und die geben in der Klärkammer vier Klumpen statt drei. Die Fragment Forge ist in Stufe 3 fast so gut wie die Dreifach-Straße und braucht keinen Sauerstoff.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["ie"], icon="minecraft:raw_copper", optional=True),

    quest("verdict", 10.25, 29.5, "&6&lWähl die richtige Mühle für deine Stufe",
          subtitle="Was sich wann lohnt.",
          description=[
              "&eStufe 1:&r Mahlwerkräder, nur für Erzblöcke mit Behutsamkeit (bis 2,25) und für Nebenprodukte. Rohes Erz in den Ofen, Glück III an die Spitzhacke.",
              "&eStufe 2:&r Gießerei für zwei Barren ohne Strom. Anreicherungskammer für zwei Barren mit Strom und Angereichertem Kohlenstoff nebenbei, mit Glück rund 2,9 pro Block.",
              "&eStufe 3:&r Klärkammer, drei pro Erz, rund 4,4 mit Glück. Fragment Forge etwa 2,7 pro Rohem Erz. IE-Zerkleinerer zwei plus Nickel.",
              "&eStufe 4:&r Injektionskammer vier, Auflösungskammer fünf, mit Glück rund 5,9 und 7,3. Ab hier sind Strom und Gas die Grenze, nicht das Erz.",
              "",
              "&eRezepte auf Kronwerke, die hier zählen:&r Stahlgehäuse mit Andesitlegierung statt Glas. Zerkleinerer mit zwei Mahlwerkrädern statt Lavaeimern. Einfacher Steuerschaltkreis nur aus Elektronenröhre und 20 mB Redstone. Fortschrittlicher Schaltkreis mit Gedrucktem Silizium (Stufe 3), Elite-Schaltkreis mit Draconiumstaub (Stufe 4).",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_table("s2_uncommon"), reward_xp(10)],
          deps=["oritech"], icon="mekanism:dust_iron", size=1.75, shape="hexagon"),
]

images = [
    head("title", "Mekanism: Erz Schritt für Schritt", 0, -3, height=1.6, kind="title"),
    head("stage", "Stufe 2 bis 4: die Erzleiter", 0, -1.6, height=0.55, kind="note", colour="stone"),
    head("one", "1x: Der Ofen", 0, -0.4, colour="stone"),
    head("two", "2x: Anreichern", 0, 3.6, colour="brass"),
    head("three", "3x: Klären", 0, 7.6, colour="water"),
    head("four", "4x: Injizieren", 0, 13.6, colour="magic"),
    head("five", "5x: Auflösen", 0, 17.6, colour="fire"),
    head("factories", "Fabriken und Upgrades", 0, 21.6, colour="brass"),
    head("more", "Mehr aus dem Erz", 0, 27.6, colour="stone"),
]

chapter(C, "Mekanism: Erz Schritt für Schritt", "mekanism:enrichment_chamber", "tech", quests, shape="square",
        order=67, stage=2,
        subtitle=["Die Erzleiter von Mekanism, eine Maschine pro Quest: Ofen, 2x, 3x, 4x, 5x, Fabriken und was andere Mods dazu beitragen."],
        images=images)
