"""Mekanism in stage 2: osmium, the metallurgic infuser (with manasteel), steel, the basic
machines, power, ore doubling and the first logistics. Elite tier, ore tripling, the digital
miner and teleporters open in stage 3 and are only mentioned, never asked for."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "mekanism"

quests = [
    # ---- Osmium und Mana ---------------------------------------------------
    quest("welcome", 0, 1, "&5&lMekanism",
          subtitle="Aus einem Erz wird eine ganze Fabrik.",
          description=[
              "Willkommen bei &5Mekanism&r, dem großen Technikmod von Kronwerke. Mekanism zerlegt Erze in ihre Bestandteile, legiert Metalle mit Kohlenstoff und Redstone und holt aus jedem Erzbrocken mehr heraus, als ein Ofen es je könnte.",
              "",
              "Alles beginnt mit einem einzigen Erz: &6Osmium&r. Es steckt in fast jeder Maschine, jedem Kabel und jedem Schaltkreis. Die erste Maschine ist die &6Metallurgische Infusionsanlage&r, und auf Kronwerke braucht sie ein wenig Magie.",
              "",
              "&eWas in Stufe 2 offen ist:&r die Grundmaschinen (Infusionsanlage, Anreicherungskammer, Energiegeladener Schmelzer, Zerkleinerer), der Wärmegenerator, einfache Kabel und Transporter, Stahl und die &6Erzverdopplung&r.",
              "",
              "&cWas noch wartet:&r Die Erzverdreifachung, der Digitale Miner, Teleporter und die Elite-Stufe öffnen in Stufe 3, Fusion und die Ultimativ-Stufe in Stufe 4. Gesperrte Gegenstände kannst du tragen, aber nicht benutzen, der Tooltip verrät dir die Stufe.",
              "",
              "Für den Anfang: Grab &68 Rohes Osmium&r aus.",
          ],
          tasks=[task_item("mekanism:raw_osmium", 8)],
          rewards=[reward_item("mekanism:raw_osmium", 16), reward_table("s2_common")],
          icon="mekanism:ingot_osmium", size=2.0, shape="hexagon"),

    quest("osmium", 2.5, 0, "&7Osmiumbarren",
          subtitle="Das Metall, aus dem Mekanism gebaut ist.",
          description=[
              "&6Osmiumerz&r kommt in drei Lagen vor. Die großen Adern stecken im Gebirge oberhalb von &eY 72&r, und dort gibt es richtig viel davon. Mittlere Adern findest du zwischen Y -32 und Y 56, kleine Adern überall unterhalb von Y 64.",
              "",
              "Schmilz das &6Rohe Osmium&r fürs Erste ganz normal im Ofen oder Schmelzofen. 32 Barren reichen für die erste Infusionsanlage, den Wärmegenerator und ein paar Schaltkreise.",
              "",
              "&eTipp:&r Nimm eine Spitzhacke mit &6Glück&r mit. Sobald die Anreicherungskammer läuft, werden aus drei Rohen Osmium vier Staub, und mit Glück III lohnt sich das mehr als Erzblöcke mit Behutsamkeit.",
              "",
              img(item_texture("mekanism:ingot_osmium"), 32, 32),
          ],
          tasks=[task_item("mekanism:ingot_osmium", 32)],
          rewards=[reward_item("minecraft:coal", 32), reward_xp(5)],
          deps=["welcome"]),

    quest("manasteel", 2.5, 2, "&bManastahl für die Technik",
          subtitle="Die Infusionsanlage will Mana.",
          description=[
              "Auf Kronwerke ist das Rezept der &6Metallurgischen Infusionsanlage&r geändert: Statt der beiden unteren Eisenbarren braucht sie zwei &6Manastahlbarren&r aus Botania. Technik kommt hier nicht ohne Magie aus, und genau so ist es gewollt.",
              "",
              "Manastahl entsteht, wenn du einen &6Eisenbarren&r in ein &aManabecken&r wirfst, das genug &dMana&r enthält. Das Becken zieht das Mana ab und gibt dir den Manastahl zurück. Wie du ein Becken baust und mit Blumen füllst, steht im Botania-Kapitel.",
              "",
              "Kein eigenes Becken? Frag im Chat. Zwei Barren sind für jeden Magier eine Kleinigkeit, und ein paar Osmiumbarren als Dankeschön sind schnell getauscht.",
          ],
          tasks=[task_item("botania:manasteel_ingot", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(5)],
          deps=["welcome"], icon="botania:manasteel_ingot"),

    quest("infuser", 5.5, 1, "&9&lMetallurgische Infusionsanlage",
          subtitle="Die erste Maschine, und sie braucht Mana.",
          description=[
              "Die &6Metallurgische Infusionsanlage&r ist das Herz von Mekanism. Sie drückt einen &eInfusionsstoff&r wie Kohlenstoff oder Redstone in einen Gegenstand und macht daraus etwas Neues: Schaltkreise, Legierungen und vor allem Stahl.",
              "",
              "&eRezept auf Kronwerke:&r oben zwei Eisenbarren mit einem Ofen dazwischen, in der Mitte zwei Redstone links und rechts vom Osmiumbarren, unten zwei &6Manastahlbarren&r mit einem Ofen dazwischen.",
              "",
              "&eSo liest du das Fenster:&r Links kommt der Infusionsstoff hinein (Kohle, Redstone), der Balken daneben zeigt, wie viel davon gespeichert ist. In der Mitte liegt der Gegenstand, der veredelt wird, rechts kommt das Ergebnis heraus. Ganz rechts sitzen der Energieslot und die Energieanzeige.",
              "",
              "Die Maschine braucht &dStrom&r, etwa 20 FE pro Tick. Den liefert dir der &6Wärmegenerator&r im Abschnitt Energie. Stell beide direkt nebeneinander, dann fließt der Strom auch ohne Kabel hinüber.",
              "",
              "&cAchtung:&r Ein Infusionsstoff bleibt im Tank, bis er verbraucht ist. Willst du wechseln, leer den Tank mit dem Knopf unter dem Balken.",
          ],
          tasks=[task_item("mekanism:metallurgic_infuser", 1)],
          rewards=[reward_item("minecraft:redstone", 32), reward_table("s2_common"), reward_xp(10)],
          deps=["osmium", "manasteel"], icon="mekanism:metallurgic_infuser", size=2.0, shape="gear"),

    # ---- Stahl ---------------------------------------------------------------
    quest("infusion", 8.5, 1, "&8Infusionsstoffe",
          subtitle="Kohlenstoff und Redstone, flüssig gedacht.",
          description=[
              "Die Infusionsanlage arbeitet mit zwei Stoffen, die du in diesem Kapitel brauchst: &8Kohlenstoff&r und &cRedstone&r.",
              "",
              "&eKohlenstoff:&r Kohle oder Kohlestaub geben 10 mB, Holzkohle sogar 20 mB, ein Kohleblock 90 mB. &6Angereicherter Kohlenstoff&r aus der Anreicherungskammer gibt 80 mB, also achtmal so viel wie ein Stück Kohle.",
              "",
              "&eRedstone:&r Redstone-Staub gibt 10 mB, ein Redstone-Block 90 mB, &6Angereichertes Redstone&r 80 mB.",
              "",
              "Die meisten Rezepte verbrauchen 10 mB pro Gegenstand, der Schaltkreis 20 mB. Solange du nur Kohle hast: nimm Kohleblöcke, dann musst du seltener nachlegen.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("minecraft:coal_block", 4)],
          deps=["infuser"], icon="mekanism:enriched_carbon"),

    quest("enriched_iron", 11, -0.5, "&7Angereichertes Eisen",
          subtitle="Der erste Schritt zum Stahl.",
          description=[
              "Leg &8Kohlenstoff&r in den linken Slot der Infusionsanlage und einen &6Eisenbarren&r oder &6Eisenstaub&r in die Mitte. Für 10 mB Kohlenstoff wird daraus &6Angereichertes Eisen&r.",
              "",
              "Angereichertes Eisen ist ein Zwischenprodukt. Du brauchst es fast nur für den nächsten Schritt, den Stahlstaub. Mach also gleich einen Stapel davon.",
          ],
          tasks=[task_item("mekanism:enriched_iron", 8)],
          rewards=[reward_item("minecraft:iron_ingot", 16)],
          deps=["infusion"]),

    quest("circuit", 11, 1, "&aEinfacher Steuerschaltkreis",
          subtitle="Osmium mit Redstone im Kopf.",
          description=[
              "Tausch den Kohlenstoff gegen &cRedstone&r und leg einen &6Osmiumbarren&r in die Mitte. Für 20 mB Redstone bekommst du einen &6Einfachen Steuerschaltkreis&r.",
              "",
              "Jede Maschine nach der Infusionsanlage braucht mindestens einen Schaltkreis, dazu Kabel, Transporter, Fabriken und der Stufen-Installateur. Ein Vorrat von einem Dutzend spart später viele Wechsel des Infusionsstoffs.",
              "",
              img(item_texture("mekanism:basic_control_circuit"), 32, 32),
          ],
          tasks=[task_item("mekanism:basic_control_circuit", 4)],
          rewards=[reward_item("mekanism:ingot_osmium", 16), reward_item("minecraft:redstone_block", 2)],
          deps=["infusion"]),

    quest("alloy", 11, 2.5, "&cInfundierte Legierung",
          subtitle="Kupfer, das Redstone geschluckt hat.",
          description=[
              "Ein &6Kupferbarren&r mit 10 mB &cRedstone&r ergibt eine &6Infundierte Legierung&r.",
              "",
              "Die Legierung steckt im &6Energietablett&r, im Energie-Würfel, im Wind- und Solargenerator, im Präzisionssägewerk und in den Geschwindigkeits- und Energie-Upgrades. Kupfer hast du genug, also lohnt sich ein kleiner Vorrat.",
          ],
          tasks=[task_item("mekanism:alloy_infused", 4)],
          rewards=[reward_item("minecraft:copper_ingot", 24)],
          deps=["infusion"]),

    quest("steel", 13.5, -0.5, "&8&lStahl",
          subtitle="Eisen, Kohlenstoff, noch mal Kohlenstoff.",
          description=[
              "Jetzt kommt das wichtigste Material von Mekanism. Gib das &6Angereicherte Eisen&r noch einmal mit 10 mB &8Kohlenstoff&r in die Infusionsanlage. Heraus kommt &6Stahlstaub&r, den du im Ofen (oder schneller im Schmelzofen) zu &6Stahlbarren&r schmilzt.",
              "",
              "Stahl steckt in jedem Maschinengehäuse, in allen Kabeln, Rohren und Transportern. Du kannst nicht zu viel davon haben.",
              "",
              "&eKronwerke:&r Das Ziel für Stufe 3 am Obelisken verlangt tausende Stahlbarren. Stahl aus Mekanism und aus dem Hochofen von Immersive Engineering zählt gleich. Wer jetzt eine Stahlstraße baut, hilft später dem ganzen Server.",
              "",
              img(item_texture("mekanism:ingot_steel"), 32, 32),
          ],
          tasks=[task_item("mekanism:dust_steel", 1), task_item("mekanism:ingot_steel", 16)],
          rewards=[reward_item("minecraft:iron_ingot", 32), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["enriched_iron"], icon="mekanism:ingot_steel", size=1.75, shape="hexagon"),

    quest("tools", 16, -1.3, "&7Werkzeug aus Stahl",
          subtitle="Mekanism Tools: stärker als Eisen.",
          description=[
              "&6Mekanism Tools&r macht aus Osmium, Bronze und Stahl eigene Werkzeug- und Rüstungssätze. Stahl ist dabei der Allrounder: haltbarer als Eisen und schnell gemacht, wenn die Stahlstraße läuft.",
              "",
              "Besonders praktisch ist die &6Stahlpaxel&r: Spitzhacke, Axt und Schaufel in einem Werkzeug. Sie wird aus den drei Einzelwerkzeugen und zwei Eisenbarren gebaut.",
          ],
          tasks=[task_item("mekanismtools:steel_pickaxe", 1)],
          rewards=[reward_item("mekanism:ingot_steel", 8)],
          deps=["steel"], optional=True),

    quest("casing", 16, 1.3, "&7&lStahlgehäuse",
          subtitle="Der Rumpf jeder Maschine.",
          description=[
              "Vier &6Stahlbarren&r in die Ecken, vier &6Glas&r an die Seiten und ein &6Osmiumbarren&r in die Mitte ergeben ein &6Stahlgehäuse&r.",
              "",
              "Ab hier ist jede Maschine ein Stahlgehäuse plus das, was sie besonders macht: Schaltkreise, Redstone, Eisen oder ein Lavaeimer. Mit vier Gehäusen kannst du Anreicherungskammer, Schmelzer, Zerkleinerer und den Energie-Würfel bauen.",
          ],
          tasks=[task_item("mekanism:steel_casing", 4)],
          rewards=[reward_item("minecraft:glass", 16), reward_table("s2_common")],
          deps=["steel"], icon="mekanism:steel_casing", size=2.0, shape="gear"),

    # ---- Energie -------------------------------------------------------------
    quest("heat_gen", 0, 7, "&6&lWärmegenerator",
          subtitle="Strom aus allem, was brennt.",
          description=[
              "Der &6Wärmegenerator&r ist die erste Stromquelle von Mekanism. &eRezept:&r oben drei Eisenbarren, in der Mitte Holzbretter links und rechts von einem Osmiumbarren, unten zwei Kupferbarren mit einem Ofen dazwischen.",
              "",
              "Er arbeitet auf zwei Arten gleichzeitig. &eAktiv:&r Leg Brennstoff hinein (Kohle, Holz, alles, was im Ofen brennt), dann liefert er &d80 FE/t&r. &ePassiv:&r Jede angrenzende &bLava&r bringt weitere &d12 FE/t&r, ohne dass Lava verbraucht wird. Im &cNether&r kommen noch einmal &d40 FE/t&r dazu.",
              "",
              "Eine Maschine der Grundstufe braucht etwa &d20 FE/t&r. Ein brennender Wärmegenerator reicht also für drei bis vier Maschinen.",
              "",
              "&eTipp:&r Bau ihn in ein Becken aus Lava, dann läuft er auch dann noch ein bisschen, wenn die Kohle alle ist.",
          ],
          tasks=[task_item("mekanismgenerators:heat_generator", 1)],
          rewards=[reward_item("minecraft:coal_block", 8), reward_xp(5)],
          deps=["welcome"], icon="mekanismgenerators:heat_generator", size=1.5, shape="hexagon"),

    quest("cables", 2.5, 7, "&aUniversalkabel",
          subtitle="Strom von hier nach da.",
          description=[
              "Zwei &6Stahlbarren&r mit einem Redstone dazwischen ergeben acht &6Einfache Universalkabel&r. Sie tragen bis zu &d3.200 FE/t&r, genug für die ganze Grundstufe.",
              "",
              "Kabel verbinden sich von selbst mit Generatoren, Maschinen und Speichern. Mit dem &6Konfigurator&r (Abschnitt Logistik) stellst du an jeder Kabelseite ein, ob sie zieht, schiebt oder gar nichts tut.",
              "",
              "&eTipp:&r Kabel verbinden sich mit allem, was Strom annimmt oder abgibt. Soll an einer Stelle keine Verbindung entstehen, stell diese Kabelseite mit dem Konfigurator auf &eKeine&r.",
          ],
          tasks=[task_item("mekanism:basic_universal_cable", 16)],
          rewards=[reward_item("mekanism:basic_universal_cable", 16)],
          deps=["heat_gen"]),

    quest("tablet", 2.5, 9, "&aEnergietablett",
          subtitle="Eine Batterie für die Tasche.",
          description=[
              "Redstone, Goldbarren und &6Infundierte Legierung&r ergeben ein &6Energietablett&r. Es speichert Strom wie eine kleine Batterie und lädt in jedem Energieslot einer Maschine.",
              "",
              "Vor allem ist es eine Zutat: Der Energie-Würfel braucht zwei davon, der Wind- und der Solargenerator je eines.",
          ],
          tasks=[task_item("mekanism:energy_tablet", 2)],
          rewards=[reward_item("minecraft:gold_ingot", 8)],
          deps=["heat_gen"]),

    quest("cube", 5, 7, "&aEinfacher Energie-Würfel",
          subtitle="Strom für schlechte Zeiten.",
          description=[
              "Der &6Einfache Energie-Würfel&r speichert &d1,6 Millionen FE&r und gibt bis zu &d1.600 FE/t&r ab. Er fängt auf, was deine Generatoren tagsüber oder beim Kohlenachlegen zu viel machen.",
              "",
              "&eRezept:&r zwei Energietabletts, zwei Eisenbarren, vier Redstone und ein Stahlgehäuse in der Mitte.",
              "",
              "&eEinrichten:&r Öffne den Würfel und schau dir die Seitenkonfiguration an. Standardmäßig ist eine Seite Ausgang, alle anderen sind Eingänge. Stell den Ausgang so, dass er zur Maschinenleitung zeigt, und die Generatoren an eine Eingangsseite.",
          ],
          tasks=[task_item("mekanism:basic_energy_cube", 1)],
          rewards=[reward_table("s2_common"), reward_xp(5)],
          deps=["cables", "tablet"], icon="mekanism:basic_energy_cube"),

    quest("wind", 7.5, 7, "&bWindgenerator",
          subtitle="Je höher, desto besser.",
          description=[
              "Der &6Windgenerator&r braucht keinen Brennstoff. Er liefert zwischen &d24 und 192 FE/t&r, und wie viel genau, hängt von der Höhe ab: tief im Tal fast nichts, hoch oben am Himmel das Maximum.",
              "",
              "Er ragt mehrere Blöcke in die Höhe und braucht freien Raum über und um sich. Ein paar Windgeneratoren auf einem Berggipfel oder einem hohen Turm, per Kabel mit dem Energie-Würfel verbunden, ersetzen einen ganzen Kohlevorrat.",
          ],
          tasks=[task_item("mekanismgenerators:wind_generator", 1)],
          rewards=[reward_item("mekanism:basic_universal_cable", 16), reward_xp(5)],
          deps=["cube"], optional=True),

    quest("solar", 5, 9, "&eSolargenerator",
          subtitle="Klein, leise, nur tagsüber.",
          description=[
              "Drei &6Solarmodule&r auf Infundierter Legierung, Eisen, Osmium und einem Energietablett ergeben einen &6Solargenerator&r. Er liefert tagsüber bei freiem Himmel etwa &d20 FE/t&r, nachts und bei Regen nichts.",
              "",
              "Das ist nicht viel, aber er kostet nichts im Betrieb. Eine Reihe davon auf dem Dach hält einen Energie-Würfel tagsüber voll.",
          ],
          tasks=[task_item("mekanismgenerators:solar_generator", 1)],
          rewards=[reward_item("mekanism:alloy_infused", 4)],
          deps=["tablet"], optional=True),

    # ---- Erzverdopplung ------------------------------------------------------
    quest("enrichment", 11, 7, "&d&lAnreicherungskammer",
          subtitle="Mehr Staub aus jedem Erz.",
          description=[
              "Die &6Anreicherungskammer&r ist die Maschine, auf die du hingearbeitet hast. &eRezept:&r ein Stahlgehäuse in der Mitte, zwei Eisenbarren links und rechts, zwei Schaltkreise oben und unten, Redstone in die Ecken.",
              "",
              "&eWas sie mit Erzen macht:&r Ein &6Erzblock&r wird zu zwei Staub. Drei &6Rohe Erze&r werden zu vier Staub, ein Block aus Rohem Erz zu zwölf. Den Staub schmilzt du danach zu Barren. So bekommst du aus jedem Erz deutlich mehr als mit dem Ofen allein.",
              "",
              "&eWas sie sonst noch kann:&r Kohle wird zu &6Angereichertem Kohlenstoff&r, Redstone zu &6Angereichertem Redstone&r, Kies zu Feuerstein, Steinziegel zu gemeißelten Steinziegeln, und bemooste Blöcke werden wieder sauber.",
              "",
              "Im Fenster liegt der Eingang links oben, der Energieslot links unten, der Ausgang rechts. Die Kammer braucht etwa &d20 FE/t&r.",
          ],
          tasks=[task_item("mekanism:enrichment_chamber", 1)],
          rewards=[reward_item("minecraft:raw_iron", 32), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["casing"], icon="mekanism:enrichment_chamber", size=1.75, shape="hexagon"),

    quest("smelter", 13.5, 7, "&6Energiegeladener Schmelzer",
          subtitle="Ein Ofen, der Strom frisst statt Kohle.",
          description=[
              "Der &6Energiegeladene Schmelzer&r macht alles, was ein Ofen macht, nur schneller und ohne Brennstoff. &eRezept:&r wie die Anreicherungskammer, aber mit Glas statt Eisen.",
              "",
              "Stell ihn direkt hinter die Anreicherungskammer: Staub hinein, Barren heraus. Zusammen sind die beiden deine erste &eErzstraße&r.",
          ],
          tasks=[task_item("mekanism:energized_smelter", 1)],
          rewards=[reward_item("mekanism:basic_control_circuit", 2)],
          deps=["enrichment"]),

    quest("enriched_carbon", 13.5, 9, "&8Angereicherter Kohlenstoff",
          subtitle="Achtmal so viel aus einer Kohle.",
          description=[
              "Schick &6Kohle&r durch die Anreicherungskammer. Jedes Stück wird zu &6Angereichertem Kohlenstoff&r, und der gibt in der Infusionsanlage &d80 mB&r statt 10 mB.",
              "",
              "Für eine Stahlstraße heißt das: Mit einem Stapel Kohle machst du nicht mehr 32 Stahlbarren, sondern über 250. Leite einen Teil der Kohle immer über die Kammer, bevor sie in die Infusionsanlage geht.",
          ],
          tasks=[task_item("mekanism:enriched_carbon", 16)],
          rewards=[reward_item("minecraft:coal", 32)],
          deps=["enrichment"]),

    quest("ore_doubling", 16, 7, "&d&lErzverdopplung",
          subtitle="Kammer, Schmelzer, doppelt so viel Metall.",
          description=[
              "Jetzt rechnet sich die Mühe. Ein Erzblock mit &6Behutsamkeit&r abgebaut wird in der Kammer zu zwei Staub, also zwei Barren. Rohes Erz mit &6Glück III&r bringt im Schnitt etwa 2,2 Rohe Erze pro Block, und drei davon werden zu vier Staub: fast drei Barren pro Erzblock.",
              "",
              "Das gilt für Eisen, Kupfer, Gold, Osmium, Zinn, Blei und Uran. Mach dir eine Kiste für Erze, die nur über die Kammer läuft.",
              "",
              "&eKronwerke:&r Die Erzverdreifachung mit der Reinigungskammer ist bis Stufe 3 gesperrt. Bis dahin ist die Verdopplung das Beste, was Mekanism kann. Auf der magischen Seite gibt es in Stufe 3 übrigens eine gleichwertige Verdreifachung ohne Strom.",
          ],
          tasks=[task_item("mekanism:dust_iron", 64)],
          rewards=[reward_item("minecraft:raw_iron", 32), reward_item("minecraft:raw_copper", 32), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["smelter"], icon="mekanism:dust_iron", size=2.0, shape="diamond"),

    quest("crusher", 16, 9, "&4Zerkleinerer",
          subtitle="Barren zu Staub, und noch mehr.",
          description=[
              "Der &6Zerkleinerer&r mahlt Barren zurück zu Staub, Bruchstein zu Kies, Kies zu Sand und Obsidian zu Obsidianstaub. &eRezept:&r Stahlgehäuse, zwei Lavaeimer, zwei Schaltkreise und Redstone.",
              "",
              "&eNether-Tipp:&r Eine &6Lohenrute&r gibt im Zerkleinerer &6vier Lohenstaub&r statt zwei an der Werkbank. Das lohnt sich, wenn du Braustände oder Rezepte mit Lohenstaub versorgst.",
              "",
              "Außerdem macht er aus Pflanzen und Samen &6Bio-Brennstoff&r, falls du später einen Biogenerator bauen willst.",
          ],
          tasks=[task_item("mekanism:crusher", 1)],
          rewards=[reward_item("mekanism:ingot_osmium", 16)],
          deps=["smelter"]),

    quest("sawmill", 18.5, 9, "&ePräzisionssägewerk",
          subtitle="Sechs Bretter pro Stamm.",
          description=[
              "Das &6Präzisionssägewerk&r macht aus einem Stamm sechs Bretter statt vier und wirft mit etwas Glück &6Sägespäne&r ab. Auch Treppen, Türen und Truhen zerlegt es wieder in Holz.",
              "",
              "Wer viel mit Holz baut oder Behandeltes Holz für Immersive Engineering braucht, spart hier auf Dauer ein Drittel der Bäume.",
          ],
          tasks=[task_item("mekanism:precision_sawmill", 1)],
          rewards=[reward_item("minecraft:oak_log", 32)],
          deps=["crusher"], optional=True),

    quest("tin_bronze", 18.5, 7, "&6Zinn und Bronze",
          subtitle="Drei Kupfer, ein Hauch Zinn.",
          description=[
              "Mekanism bringt &6Zinnerz&r mit, das in kleinen und großen Adern in der Oberwelt liegt. Reichere es an wie jedes andere Erz.",
              "",
              "&6Zinnstaub&r oder &6Angereichertes Zinn&r ist ein Infusionsstoff: Drei &6Kupferbarren&r mit 10 mB Zinn ergeben in der Infusionsanlage vier &6Bronzebarren&r. Bronze gibt es auch als Werkzeug- und Rüstungssatz, und einige Rezepte anderer Mods fragen danach.",
          ],
          tasks=[task_item("mekanism:ingot_bronze", 8)],
          rewards=[reward_item("minecraft:copper_ingot", 24)],
          deps=["ore_doubling"], icon="mekanism:ingot_bronze", optional=True),

    quest("other_ores", 21, 7, "&7Was sonst im Boden liegt",
          subtitle="Blei, Uran, Fluorit und Salz.",
          description=[
              "Mekanism hat noch mehr Erze, die du beim Graben findest. &6Blei&r brauchst du später für Strahlenschutz und Reaktoren. &6Uran&r liegt tief unten und wird erst spät im Pack wirklich wichtig, heb es trotzdem auf.",
              "",
              "&6Fluorit&r liegt ebenfalls tief und wird für spätere Chemie gebraucht. &6Salz&r findest du als Blöcke in Tonablagerungen unter Wasser, es wird in Stufe 3 wichtig.",
              "",
              "Nichts davon brauchst du in Stufe 2. Aber wer jetzt eine Truhe dafür anlegt, muss später nicht noch einmal los.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["tin_bronze"], icon="mekanism:ingot_lead", optional=True),

    # ---- Logistik und Ausbau -------------------------------------------------
    quest("configurator", 11, 13, "&3Konfigurator",
          subtitle="Das Werkzeug, das jeder Techniker braucht.",
          description=[
              "Der &6Konfigurator&r wird aus zwei Eisenbarren, einem Osmiumbarren und einem Stahlbarren gebaut. Mit &eShift und Mausrad&r wechselst du seinen Modus.",
              "",
              "&eModi:&r Im Konfigurationsmodus zeigt ein Klick auf eine Maschinenseite, welche Aufgabe sie hat, und schaltet sie weiter. Im Leeren-Modus wirft er den Inhalt aus, im Drehmodus dreht er Blöcke, im Schraubenschlüssel-Modus baut er Maschinen samt Inhalt ab.",
              "",
              "&eSeitenkonfiguration:&r Jede Maschine hat oben links im Fenster kleine Reiter. Dort legst du fest, welche Seite Eingang (rot), Ausgang (blau) oder Energie (grün) ist, und schaltest &eAuto-Auswurf&r ein, damit fertige Gegenstände von selbst in das nächste Rohr oder die nächste Maschine gehen.",
          ],
          tasks=[task_item("mekanism:configurator", 1)],
          rewards=[reward_item("mekanism:ingot_steel", 8)],
          deps=["enrichment"]),

    quest("transporter", 13.5, 13, "&eLogistiktransporter",
          subtitle="Gegenstände auf Wanderschaft.",
          description=[
              "Zwei &6Stahlbarren&r und ein Schaltkreis ergeben acht &6Einfache Logistiktransporter&r. Sie verbinden Truhen und Maschinen und schieben Gegenstände durch das Netz.",
              "",
              "Ein Transporter zieht nichts von selbst aus einer Kiste. Entweder schaltet die Maschine &eAuto-Auswurf&r ein, oder du stellst mit dem Konfigurator eine Transporterseite auf &eZiehen&r.",
              "",
              "Mit dem Konfigurator kannst du Transporter auch einfärben. Transporter verschiedener Farben verbinden sich nicht miteinander, so laufen zwei Straßen direkt nebeneinander, ohne sich zu vermischen.",
          ],
          tasks=[task_item("mekanism:basic_logistical_transporter", 16)],
          rewards=[reward_item("mekanism:basic_logistical_transporter", 8)],
          deps=["configurator"]),

    quest("factory", 16, 13, "&aEinfache Fabriken",
          subtitle="Drei Plätze statt einem.",
          description=[
              "Der &6Einfache Stufen Installateur&r (Redstone, Schaltkreise, Eisen und ein Brett) macht aus einer Maschine eine &6Einfache Fabrik&r. Klick damit einfach auf die Maschine, sie behält ihren Inhalt.",
              "",
              "Eine Fabrik arbeitet an &edrei Gegenständen gleichzeitig&r. Aus dem Energiegeladenen Schmelzer wird die Einfache Schmelzfabrik, aus der Anreicherungskammer die Einfache Anreicherungsfabrik. Sie braucht mehr Strom, schafft aber das Dreifache.",
              "",
              "&eTipp:&r Der Knopf mit den Pfeilen im Fenster verteilt Stapel automatisch auf alle drei Plätze.",
          ],
          tasks=[task_item("mekanism:basic_tier_installer", 1)],
          rewards=[reward_item("mekanism:basic_control_circuit", 4), reward_table("s2_common")],
          deps=["transporter"], icon="mekanism:basic_tier_installer"),

    quest("pipes", 11, 15, "&bRohre und Tanks",
          subtitle="Wenn es fließt, gehört es ins Rohr.",
          description=[
              "Zwei Stahlbarren und ein Eimer ergeben acht &6Einfache Rohrleitungen&r. Sie pumpen &bFlüssigkeiten&r wie Wasser und Lava aus Tanks und Maschinen.",
              "",
              "Der &6Einfache Flüssigkeitsbehälter&r fasst 32 Eimer und behält seinen Inhalt, wenn du ihn abbaust. Ein Tank voller Lava neben dem Wärmegenerator ist eine gute Reserve.",
          ],
          tasks=[task_item("mekanism:basic_mechanical_pipe", 8), task_item("mekanism:basic_fluid_tank", 1)],
          rewards=[reward_item("minecraft:bucket", 4)],
          deps=["configurator"], icon="mekanism:basic_fluid_tank", optional=True),

    quest("bin", 13.5, 15, "&eEinfache Tonne",
          subtitle="Viertausend Stück von einer Sorte.",
          description=[
              "Die &6Einfache Tonne&r speichert 4.096 Gegenstände einer Sorte. Linksklick nimmt einen Stapel heraus, Rechtsklick legt hinein.",
              "",
              "Sie ist ein guter Puffer am Anfang deiner Erzstraße: Rohe Erze hinein, Transporter heraus. Mit dem Konfigurator kannst du sie so einstellen, dass sie nach unten automatisch auswirft.",
          ],
          tasks=[task_item("mekanism:basic_bin", 1)],
          rewards=[reward_item("minecraft:cobblestone", 64)],
          deps=["transporter"], optional=True),

    quest("upgrades", 16, 15, "&8Maschinen-Upgrades",
          subtitle="Schneller, sparsamer.",
          description=[
              "Upgrades steckst du in den Upgrade-Reiter rechts im Maschinenfenster. Das &6Geschwindigkeitsupgrade&r (Glas, Infundierte Legierung, Osmiumstaub) macht die Maschine schneller, braucht aber mehr Strom. Das &6Energie Upgrade&r (Glas, Infundierte Legierung, Goldstaub) senkt den Verbrauch.",
              "",
              "Pro Maschine passen bis zu acht Stück jeder Sorte. Eine Mischung aus beiden ist fast immer besser als nur Geschwindigkeit.",
          ],
          tasks=[task_item("mekanism:upgrade_speed", 1)],
          rewards=[reward_item("mekanism:alloy_infused", 8)],
          deps=["factory"], optional=True),

    quest("ore_line", 19, 14, "&5&lDie Erzstraße",
          subtitle="Kiste, Kammer, Schmelzer, Kiste.",
          description=[
              "Zeit, alles zusammenzubauen. Eine &eErzstraße&r nimmt Rohe Erze aus einer Kiste oder Tonne, schickt sie durch die &6Anreicherungskammer&r und den &6Energiegeladenen Schmelzer&r und legt die Barren in eine Kiste am Ende.",
              "",
              "&eSo geht es:&r Transporter von der Eingangskiste zur Kammer, Auto-Auswurf an der Kammer, Transporter zum Schmelzer, Auto-Auswurf am Schmelzer, Transporter zur Ausgangskiste. Strom über Universalkabel an beide Maschinen. Mit Fabriken statt Einzelmaschinen läuft das Ganze dreimal so schnell.",
              "",
              "&eUnd dann Stahl:&r Häng eine Infusionsanlage mit Angereichertem Kohlenstoff an das Eisen, einmal für Angereichertes Eisen und einmal für Stahlstaub, und schick den Staub durch den Schmelzer. Das ist die Straße, die der Server für Stufe 3 braucht.",
          ],
          tasks=[task_item("mekanism:basic_logistical_transporter", 16), task_item("mekanism:ingot_steel", 64)],
          rewards=[reward_table("s2_rare"), reward_item("mekanism:basic_control_circuit", 4), reward_xp(20)],
          deps=["factory"], icon="mekanism:basic_logistical_transporter", size=2.5, shape="gear"),

    quest("outlook", 22.5, 14, "&dAusblick auf Stufe 3",
          subtitle="Was hinter dem Stahlziel wartet.",
          description=[
              "Wenn das Obelisk-Ziel für Stufe 3 gefüllt ist, öffnet Mekanism seine nächste Ebene: die &6Erzverdreifachung&r mit Sauerstoff und der Reinigungskammer, die Elite-Stufe für Kabel und Fabriken, den &6Digitalen Miner&r, der ganze Gebiete abbaut, und &6Teleporter&r.",
              "",
              "Das Ziel verlangt unter anderem viele &6Stahlbarren&r. Jede Stahlstraße, die jetzt läuft, bringt den Server dorthin. Stell eine Kiste neben den Obelisken und verbinde sie mit deiner Straße: Was hineinfällt, zählt für dich.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(10)],
          deps=["ore_line"], icon="mekanism:steel_casing", optional=True),
]

images = [
    banner("mekanism/title", "Mekanism", 7.5, -5, height=1.75, kind="title", colour="brass"),
    banner("mekanism/osmium", "Osmium und Mana", 2.5, -2.7, height=0.9, colour="magic"),
    banner("mekanism/steel", "Stahl", 12.5, -2.7, height=0.9, colour="stone"),
    banner("mekanism/power", "Energie", 3.5, 5, height=0.9, colour="brass"),
    banner("mekanism/ores", "Erzverdopplung", 17.5, 5, height=0.9, colour="brass"),
    banner("mekanism/logistics", "Logistik und Ausbau", 18, 11.3, height=0.9, colour="water"),
]

chapter(C, "Mekanism", "mekanism:metallurgic_infuser", "tech", quests, shape="square", order=10, stage=2,
        subtitle=["Stufe 2: Osmium, Stahl, die Grundmaschinen und die Erzverdopplung."], images=images)
