"""The Nether: opened on stream with the stage 2 event (the portal at spawn is lit). Getting
there safely, what to bring back and why, the fortresses with their blazes (the Create blaze
burner), the bastions and the Nether content of the other mods in the pack."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_dimension, task_kill, task_advancement,
                  reward_item, reward_table, reward_xp, banner, img, item_texture)

C = "nether"

quests = [
    # ---- Ankunft -------------------------------------------------------------
    quest("welcome", 0, 6.5, "&c&lDer Nether",
          subtitle="Auf Stream entzündet. Jetzt gehört er allen.",
          description=[
              "Mit dem Event zu Beginn von &eStufe 2&r wurde das Portal am Spawn vor laufender Kamera entzündet. Seitdem ist der Nether für alle offen: Du kannst durch das Portal am Spawn gehen oder dir ein eigenes bauen.",
              "",
              "Der Nether ist heiß, laut und gefährlich, und er ist für diese Stufe unverzichtbar. &6Lohenruten&r für den Lohenbrenner von Create, &6Netherquarz&r für Elektronenröhren, &6Magmablöcke&r und &6Netherziegel&r für den Hochofen von Immersive Engineering: Fast jede Maschine dieser Stufe braucht etwas von hier unten.",
              "",
              "Lies die nächste Quest, bevor du durchgehst. Wer unvorbereitet in einen Lavasee fällt, verliert alles, was er dabei hat.",
          ],
          tasks=[task_dimension("minecraft:the_nether")],
          rewards=[reward_item("minecraft:fire_charge", 4), reward_table("s2_common"), reward_xp(5)],
          icon="minecraft:netherrack", size=2.0, shape="hexagon"),

    quest("gear", 2.5, 6.5, "&6Richtig ausgerüstet",
          subtitle="Gold am Kopf, Schild in der Hand.",
          description=[
              "&eGold:&r Trag mindestens &6ein Rüstungsteil aus Gold&r, zum Beispiel einen Goldhelm. Dann lassen dich die &6Piglins&r in Ruhe. Ohne Gold greifen sie sofort an. Aber Vorsicht: Wenn du vor ihren Augen Goldblöcke abbaust oder ihre Truhen öffnest, werden sie trotzdem wütend.",
              "",
              "&eSchild:&r &6Ghasts&r schießen Feuerbälle, die explodieren. Ein Schild fängt sie ab, und mit einem gut getimten Schlag schickst du den Feuerball sogar zurück.",
              "",
              "&eBlöcke:&r Netherrack und Holz zerbrechen bei Ghast-Explosionen, &6Bruchstein&r und alles, was ähnlich widerstandsfähig ist, hält. Nimm einen Stapel für Brücken und Schutzwände mit.",
              "",
              "&eFeuerresistenz:&r Beim ersten Besuch hast du noch keine Tränke. Piglins tauschen sie aber gelegentlich gegen Gold, und ab dem Abschnitt Festungen kannst du sie selbst brauen.",
              "",
              "&cNiemals&r im Nether ein Bett benutzen: Es explodiert.",
          ],
          tasks=[task_item("minecraft:golden_helmet", 1), task_item("minecraft:shield", 1)],
          rewards=[reward_item("minecraft:cobblestone", 64), reward_item("minecraft:gold_ingot", 4)],
          deps=["welcome"], icon="minecraft:golden_helmet", size=1.5),

    quest("portal", 0, 9.3, "&5Ein eigenes Portal",
          subtitle="Zehn Obsidian und ein Funke.",
          description=[
              "Ein Portal ist ein Rahmen aus &6Obsidian&r, mindestens vier breit und fünf hoch. Die Ecken darfst du weglassen, dann reichen &6zehn Obsidian&r. Entzünde es mit einem &6Feuerzeug&r.",
              "",
              "Auf der anderen Seite entsteht ein passendes Portal. Bau auf der Nether-Seite eine kleine Hütte aus Bruchstein darum, damit Ghasts es nicht zerschießen, und nimm immer ein Feuerzeug mit, falls es doch einmal ausgeht.",
              "",
              "&eTipp:&r Obsidian machst du, indem du Wasser über stehende Lava gießt. Abbauen geht nur mit einer Diamant- oder Netheritspitzhacke.",
          ],
          tasks=[task_item("minecraft:obsidian", 10), task_item("minecraft:flint_and_steel", 1)],
          rewards=[reward_item("minecraft:obsidian", 4), reward_xp(5)],
          deps=["welcome"], icon="minecraft:flint_and_steel"),

    quest("fast_travel", 0, 11.3, "&dDie Abkürzung",
          subtitle="Ein Block hier, acht Blöcke dort.",
          description=[
              "Jeder Block, den du im Nether gehst, zählt in der Oberwelt wie &eacht Blöcke&r. Ein Portal bei deiner Basis und eines 100 Blöcke weiter im Nether führt dich in der Oberwelt 800 Blöcke weit.",
              "",
              "&eSo baust du ein Portalnetz:&r Teile die Oberwelt-Koordinaten deines Ziels durch acht, geh im Nether genau dorthin (auf ungefähr Y 100 bis 120, dort ist es meist ruhiger) und bau dort ein Portal. Viele Server legen gemeinsam einen Tunnel aus Bruchstein an. Sprich dich mit den anderen ab.",
              "",
              "Die Quest ist erledigt, wenn du auf diese Weise 7.000 Oberwelt-Blöcke auf einmal zurückgelegt hast.",
          ],
          tasks=[task_advancement("minecraft:nether/fast_travel", "Durch den Nether reisen")],
          rewards=[reward_item("minecraft:obsidian", 8), reward_xp(10)],
          deps=["portal"], icon="minecraft:compass", optional=True),

    quest("waystone", 0, 3.8, "&bEin Wegstein im Nether",
          subtitle="Der schnelle Weg zurück.",
          description=[
              "Ein &6Wegstein&r funktioniert auch im Nether. Stell dir einen an einen sicheren Ort, zum Beispiel direkt neben dein Portal oder in die Nähe einer Festung, die du öfter besuchst.",
              "",
              "&cAber:&r Ein Sprung zwischen zwei Dimensionen kostet über einen Wegstein viele Erfahrungslevel. Für den Weg zwischen Oberwelt und Nether ist das Portal meist günstiger, innerhalb des Nethers sind Wegsteine dagegen Gold wert.",
          ],
          tasks=[task_item("waystones:waystone", 1)],
          rewards=[reward_item("waystones:warp_dust", 8)],
          deps=["welcome"], icon="waystones:waystone", optional=True),

    # ---- Rohstoffe -----------------------------------------------------------
    quest("netherrack", 6, 1, "&4Netherrack",
          subtitle="Davon gibt es mehr als genug.",
          description=[
              "Fast der ganze Nether besteht aus &6Netherrack&r. Er lässt sich schnell abbauen und brennt, wenn du ihn anzündest, ewig weiter.",
              "",
              "&eWofür du ihn brauchst:&r Im Ofen geschmolzen wird er zu &6Netherziegeln&r. Die brauchst du für die &6Sprengziegel&r des Hochofens von Immersive Engineering. Und in jedem &6Leeren Lohenbrenner&r steckt ein Netherrack.",
              "",
              "Eine Mühle von Create mahlt ihn zu &6Aschenmehl&r.",
          ],
          tasks=[task_item("minecraft:netherrack", 64)],
          rewards=[reward_item("minecraft:coal", 16)],
          deps=["gear"], icon="minecraft:netherrack"),

    quest("quartz", 8.5, -0.6, "&fNetherquarz",
          subtitle="Überall in den Wänden.",
          description=[
              "&6Netherquarzerz&r leuchtet weiß aus dem Netherrack und ist sehr häufig. Mit Glück auf der Spitzhacke fällt deutlich mehr heraus.",
              "",
              "Quarz ist der Anfang der Elektronik von Create (siehe nächste Quest). Außerdem wird er zu Quarzblöcken, Komparatoren und Beobachtern, und einige Magie-Rezepte wollen ihn ebenfalls.",
              "",
              img(item_texture("minecraft:quartz"), 32, 32),
          ],
          tasks=[task_item("minecraft:quartz", 32)],
          rewards=[reward_item("minecraft:redstone", 32)],
          deps=["netherrack"]),

    quest("rose_quartz", 11, -0.6, "&dRosenquarz",
          subtitle="Quarz, der Redstone getrunken hat.",
          description=[
              "Ein &6Netherquarz&r und &6acht Redstone&r ergeben an der Werkbank einen &6Rosenquarz&r. Mit &6Schmirgelpapier&r in der Hand (Rechtsklick gedrückt halten) wird daraus &6Polierter Rosenquarz&r.",
              "",
              "Polierter Rosenquarz auf einem &6Eisenblech&r ergibt eine &6Elektronenröhre&r. Die steckt in Create in allem, was Signale verarbeitet: Mechanischer Arm, Smarte Rutsche, Anzeigeverbindung und mehr.",
          ],
          tasks=[task_item("create:rose_quartz", 8), task_item("create:electron_tube", 2)],
          rewards=[reward_item("minecraft:redstone", 32), reward_xp(5)],
          deps=["quartz"], icon="create:electron_tube"),

    quest("glowstone", 8.5, 1, "&eLeuchtstein",
          subtitle="Er hängt an der Decke, über der Lava.",
          description=[
              "&6Leuchtstein&r wächst in Klumpen an der Decke des Nethers. Mit Behutsamkeit bekommst du den Block, sonst zwei bis vier &6Leuchtsteinstaub&r.",
              "",
              "&cVorsicht:&r Die Klumpen hängen oft über Lavaseen. Bau dir eine Plattform darunter, bevor du anfängst.",
              "",
              "Leuchtstein ist Licht, Tränke-Verstärker und der Brennstoff des &6Seelenankers&r, mit dem du dir im Nether einen Wiedereinstiegspunkt setzen kannst. Mehrere Mods brauchen ihn für spätere Rezepte.",
          ],
          tasks=[task_item("minecraft:glowstone_dust", 32)],
          rewards=[reward_item("minecraft:glowstone_dust", 16)],
          deps=["netherrack"]),

    quest("magma", 8.5, 2.6, "&6Magma",
          subtitle="Heiß unter den Füßen.",
          description=[
              "&6Magmablöcke&r liegen an Lavaseen und in großen Mengen in den &eBasaltdeltas&r. Wer darauf steht, verbrennt sich, außer beim Schleichen.",
              "",
              "&6Magmacreme&r lassen die hüpfenden &6Magmawürfel&r fallen. Vier Magmacreme ergeben einen Magmablock, und Magmacreme ist die Zutat für den &6Trank der Feuerresistenz&r.",
              "",
              "Neun Magmablöcke brauchst du für die Sprengziegel eines Hochofens von Immersive Engineering.",
          ],
          tasks=[task_item("minecraft:magma_block", 9), task_item("minecraft:magma_cream", 4)],
          rewards=[reward_item("minecraft:slime_ball", 4)],
          deps=["netherrack"], icon="minecraft:magma_cream"),

    # ---- Festungen -----------------------------------------------------------
    quest("fortress", 6, 6.5, "&4&lNetherfestung",
          subtitle="Dunkle Ziegel, lange Brücken.",
          description=[
              "&6Netherfestungen&r sind große Anlagen aus dunklen Netherziegeln mit langen Brücken, Gängen und Treppenhäusern. Auf Kronwerke ersetzt &eYUNG's Better Nether Fortresses&r die alten Festungen: Sie sind größer und verwinkelter, mit Mauern, Brücken und eigenen Räumen für die Spawner.",
              "",
              "&eSo findest du eine:&r Halte Ausschau nach dunklen Ziegelmauern über den Lavaseen. Von einer erhöhten Stelle aus siehst du weiter, und wer eine Festung gefunden hat, teilt die Koordinaten am besten im Chat.",
              "",
              "&cGefahren:&r Lohen, Witherskelette (die dich mit Wither vergiften) und manchmal Ghasts in großen Hallen. Bau dir einen sicheren Eingang und hab Essen dabei.",
              "",
              "Bring ein paar Netherziegelblöcke mit, damit wir wissen, dass du drin warst.",
          ],
          tasks=[task_item("minecraft:nether_bricks", 16)],
          rewards=[reward_item("minecraft:cooked_beef", 16), reward_table("s2_common")],
          deps=["gear"], icon="minecraft:nether_bricks", size=1.5, shape="hexagon"),

    quest("blaze", 8.5, 6.5, "&6&lLohenruten",
          subtitle="Der Rohstoff, um den sich diese Stufe dreht.",
          description=[
              "In den Festungen sitzen &6Lohen-Spawner&r. Lohen schweben, schießen Feuerkugeln und lassen beim Tod bis zu eine &6Lohenrute&r fallen, mit Plünderung mehr.",
              "",
              "&eKampf:&r Schneebälle machen Lohen Schaden. Ein Schild blockt die Feuerkugeln. Stell dich so, dass die Lohen zu dir kommen müssen, statt offen in den Spawnerraum zu laufen.",
              "",
              "&eWofür:&r Braustand, Lohenstaub, Enderaugen und vor allem der &6Lohenbrenner&r von Create. Im Zerkleinerer von Mekanism wird eine Rute zu vier Lohenstaub statt zwei.",
              "",
              "&cLass den Spawner stehen!&r Du brauchst ihn noch, um eine lebende Lohe einzufangen, und für Nachschub an Ruten.",
              "",
              img(item_texture("minecraft:blaze_rod"), 32, 32),
          ],
          tasks=[task_kill("minecraft:blaze", 5), task_item("minecraft:blaze_rod", 8)],
          rewards=[reward_item("minecraft:blaze_rod", 4), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["fortress"], icon="minecraft:blaze_rod", size=1.75, shape="diamond"),

    quest("blaze_burner", 11, 6.5, "&6&lLohenbrenner",
          subtitle="Eine Lohe im Käfig, und Create wird heiß.",
          description=[
              "Der &6Lohenbrenner&r ist der Grund, warum Create in dieser Stufe den Nether braucht: Unter einem &6Becken&r erhitzt er den &6Mechanischen Mixer&r, und nur so entsteht &6Messing&r aus Kupfer und Zink.",
              "",
              "&eDer leere Käfig:&r Auf Kronwerke braucht der &6Leere Lohenbrenner&r zwei &6Quelljuwelen&r aus Ars Nouveau. Oben ein Quelljuwel, ein Eisenblech, ein Quelljuwel, in der Mitte ein Netherrack zwischen zwei Eisenblechen, unten ein Eisenblech. Messing braucht also auch einen Magier.",
              "",
              "&eDie Lohe:&r Geh mit dem Leeren Lohenbrenner in der Hand in die Festung und rechtsklick eine lebende &6Lohe&r. Sie landet im Käfig, und du hast einen Lohenbrenner.",
              "",
              "&eBetrieb:&r Er frisst jeden Brennstoff, den auch ein Ofen nimmt. Mit einem &6Lohenkuchen&r wird er überhitzt, das brauchen einige besondere Rezepte.",
          ],
          tasks=[task_item("create:blaze_burner", 1)],
          rewards=[reward_item("create:brass_ingot", 8), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["blaze"], icon="create:blaze_burner", size=2.0, shape="gear"),

    quest("wart", 8.5, 8.7, "&4Netherwarze",
          subtitle="Die Grundlage jedes Tranks.",
          description=[
              "&6Netherwarzen&r wachsen auf Seelensand in den Treppenhäusern der Festungen, oft auch in eigenen kleinen Gärten. Nimm alles mit, was du findest.",
              "",
              "Zuhause pflanzt du sie ebenfalls auf &6Seelensand&r. Sie brauchen weder Licht noch Wasser und wachsen auch in der Oberwelt. Ein kleines Feld reicht für alle Tränke, die du je brauen wirst.",
          ],
          tasks=[task_item("minecraft:nether_wart", 8)],
          rewards=[reward_item("minecraft:soul_sand", 8)],
          deps=["fortress"]),

    quest("brewing", 11, 8.7, "&cFeuerresistenz",
          subtitle="Lava wird zum Badewasser.",
          description=[
              "Eine &6Lohenrute&r und drei Bruchstein ergeben einen &6Braustand&r. Er läuft mit &6Lohenstaub&r als Brennstoff.",
              "",
              "&eDer wichtigste Trank:&r Wasserflasche plus Netherwarze ergibt einen seltsamen Trank, dazu &6Magmacreme&r ergibt den &6Trank der Feuerresistenz&r. Mit Redstone hält er acht Minuten statt drei.",
              "",
              "Mit Feuerresistenz kannst du durch Lava schwimmen und Feuerkugeln ignorieren. Für jede längere Tour in den Nether gehört ein Stapel davon in die Tasche.",
          ],
          tasks=[task_item("minecraft:brewing_stand", 1)],
          rewards=[reward_item("minecraft:glass_bottle", 6), reward_item("minecraft:blaze_powder", 4)],
          deps=["wart"], icon="minecraft:brewing_stand"),

    quest("wither_skull", 6, 8.9, "&8Witherskelettschädel",
          subtitle="Selten, und besser im Schrank.",
          description=[
              "&6Witherskelette&r sind die großen, schwarzen Skelette der Festungen. Selten lassen sie ihren Schädel fallen, mit Plünderung etwas häufiger.",
              "",
              "Drei Schädel auf Seelensand beschwören den &cWither&r. Tu das auf keinen Fall in der Nähe einer Basis, auch nicht deiner eigenen. Heb die Schädel auf, bis der Server gemeinsam bereit ist.",
          ],
          tasks=[task_item("minecraft:wither_skeleton_skull", 1)],
          rewards=[reward_item("minecraft:bone_block", 8), reward_xp(10)],
          deps=["fortress"], icon="minecraft:wither_skeleton_skull", optional=True),

    # ---- Bastionen -----------------------------------------------------------
    quest("gold", 14, 8.7, "&6Nethergold",
          subtitle="Glitzernd im Netherrack.",
          description=[
              "&6Nethergolderz&r liefert beim Abbau &6Goldnuggets&r, mit Glück mehr davon. In der Netherödnis ist es überall.",
              "",
              "Gold ist im Nether eine Währung: Piglins tauschen dagegen allerhand Nützliches. Neun Nuggets ergeben einen Barren.",
              "",
              img(item_texture("minecraft:gold_nugget"), 32, 32),
          ],
          tasks=[task_item("minecraft:gold_nugget", 64)],
          rewards=[reward_item("minecraft:gold_ingot", 8)],
          deps=["brewing"], icon="minecraft:gold_nugget"),

    quest("barter", 16.5, 8.7, "&eTauschhandel",
          subtitle="Wirf einen Barren, sieh, was kommt.",
          description=[
              "Wirf einem &6Piglin&r einen &6Goldbarren&r zu. Er schaut ihn sich an und wirft dir nach ein paar Sekunden etwas zurück.",
              "",
              "&eWas es gibt:&r Enderperlen, Tränke der Feuerresistenz, Obsidian, Weinender Obsidian, Faden, Quarz, Leder, Seelensand, Eisennuggets, Spektralpfeile und mit Glück ein Buch mit Seelenläufer.",
              "",
              "&eTipp:&r Ein Piglin hinter einem Zaun oder in einem Boot, dazu ein Trichter unter ihm, ist eine kleine Tauschfabrik. Gold dafür gibt es später reichlich aus der Erzverdopplung.",
          ],
          tasks=[task_advancement("minecraft:nether/distract_piglin", "Einen Piglin mit Gold ablenken")],
          rewards=[reward_item("minecraft:ender_pearl", 4)],
          deps=["gold"], icon="minecraft:gold_ingot"),

    quest("bastion", 19, 7.8, "&8&lBastionsruinen",
          subtitle="Die Festung der Piglins.",
          description=[
              "&6Bastionsruinen&r sind riesige Bauten aus Schwarzstein. Hier leben &6Piglins&r und die kräftigen &6Piglin-Barbaren&r, die sich von Gold nicht ablenken lassen, dazu Hoglins in den Ställen.",
              "",
              "Die Truhen sind gut gefüllt: Gold, Eisen, Diamantausrüstung, Antiker Schrott und die &6Schmiedevorlage&r für die Netheritaufwertung. Jede Truhe, die du öffnest, macht die Piglins in der Nähe wütend, auch mit Goldrüstung.",
              "",
              "&eErkennungszeichen:&r &6Golddurchzogener Schwarzstein&r. Bring einen Block davon mit.",
          ],
          tasks=[task_item("minecraft:gilded_blackstone", 1)],
          rewards=[reward_item("minecraft:gold_block", 2), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["barter"], icon="minecraft:gilded_blackstone", size=1.5, shape="hexagon"),

    quest("debris", 21.5, 7.8, "&4&lAntiker Schrott",
          subtitle="Tief unten, feuerfest, jede Mühe wert.",
          description=[
              "&6Antiker Schrott&r liegt tief im Nether, am häufigsten um &eY 15&r. Er leuchtet nicht, ist sprengfest und schwimmt als Gegenstand sogar auf Lava.",
              "",
              "&eSo suchst du:&r Grab einen langen Tunnel auf Y 15 und schau in die Wände. Schneller geht es mit Sprengungen: TNT oder Betten (die im Nether explodieren) räumen das Netherrack weg, der Schrott bleibt liegen. Halt Abstand und sichere dich vor Lava.",
              "",
              "Im Ofen geschmolzen wird jeder Block zu einer &6Netheritplatte&r.",
          ],
          tasks=[task_item("minecraft:ancient_debris", 4)],
          rewards=[reward_item("minecraft:gold_ingot", 8), reward_table("s2_rare"), reward_xp(15)],
          deps=["bastion"], icon="minecraft:ancient_debris", size=1.75, shape="diamond"),

    quest("netherite", 24, 7.8, "&8Netherit",
          subtitle="Vier Platten, vier Gold, ein Barren.",
          description=[
              "Vier &6Netheritplatten&r und vier &6Goldbarren&r ergeben einen &6Netheritbarren&r.",
              "",
              "Am Schmiedetisch wird aus Diamantausrüstung mit Barren und &6Schmiedevorlage&r Netheritausrüstung: stärker, haltbarer und sie verbrennt nicht in Lava. Die Vorlage findest du in Bastionen. Mit sieben Diamanten und einem Netherrack kannst du sie kopieren.",
          ],
          tasks=[task_item("minecraft:netherite_ingot", 1)],
          rewards=[reward_xp(20)],
          deps=["debris"], icon="minecraft:netherite_ingot", optional=True),

    # ---- Biome und Strukturen ------------------------------------------------
    quest("biomes", 6, 13, "&cDie Biome des Nethers",
          subtitle="Fünf Welten unter der Welt.",
          description=[
              "Der Nether hat fünf eigene Biome, und jedes hat seine Tücken:",
              "&6Netherödnis:&r viel Netherrack, Ghasts, Quarz und Gold.",
              "&6Karmesinwald:&r rote Pilzbäume, Hoglins und Piglins.",
              "&6Wirrwald:&r türkise Pilzbäume und Endermen, der ruhigste Ort im Nether.",
              "&6Seelensandtal:&r Seelensand bremst dich aus, Skelette und Ghasts sehen dich von weit her.",
              "&6Basaltdeltas:&r zerklüftet, voller Magmawürfel und Magmablöcke.",
              "",
              "Die Pilzstiele sind Bauholz, das nicht brennt. Seelensand brauchst du für Netherwarzen.",
          ],
          tasks=[task_item("minecraft:crimson_stem", 16), task_item("minecraft:warped_stem", 16), task_item("minecraft:soul_sand", 16)],
          rewards=[reward_item("minecraft:bone_meal", 16), reward_xp(5)],
          deps=["gear"], icon="minecraft:warped_fungus", size=1.5, shape="hexagon"),

    quest("bop", 8.5, 11.4, "&dBiomes O' Plenty im Nether",
          subtitle="Kristalle, Fleisch und Abgründe.",
          description=[
              "&6Biomes O' Plenty&r bringt eigene Nether-Biome mit:",
              "&6Kristalline Kluft:&r Hallen voller Rosenquarz-Kristalle.",
              "&6Unterholz:&r dichte Höllenrinden-Wälder mit Dornengestrüpp.",
              "&6Eingeweidehalde:&r Blöcke aus Fleisch. Sieht eklig aus, ist aber harmlos.",
              "&6Verdorrter Abgrund:&r tiefe Schluchten. &cHier geht es sehr weit nach unten.",
              "&6Ausbrechendes Inferno:&r Lava, Feuer und Schwefel. Nur mit Feuerresistenz.",
              "",
              "Bring einen &6Rosenquarzbrocken&r aus der Kristallinen Kluft mit. Er ist nicht dasselbe wie der Rosenquarz von Create, aber ein schöner Baustoff.",
          ],
          tasks=[task_item("biomesoplenty:rose_quartz_chunk", 4)],
          rewards=[reward_xp(10)],
          deps=["biomes"], icon="biomesoplenty:rose_quartz_chunk", optional=True),

    quest("mod_ores", 8.5, 14.6, "&5Erze aus anderen Mods",
          subtitle="Purpur-Eisen und Seelenstein.",
          description=[
              "&6Silent Gear&r lässt im Nether &6Purpur-Eisenerz&r wachsen. Das rohe Erz schmilzt du zu Purpur-Eisenbarren, der nächsten Materialstufe für deine Silent-Gear-Werkzeuge, und später zu Purpur-Stahl.",
              "",
              "&6Mystical Agriculture&r verteilt &6Seelenstein&r im Nether. Er gehört zur Seelen-Mechanik des Mods, mit der du später die Seelen von Monstern für neue Samen sammelst.",
          ],
          tasks=[task_item("silentgear:raw_crimson_iron", 8)],
          rewards=[reward_item("minecraft:iron_ingot", 16), reward_xp(5)],
          deps=["biomes"], icon="silentgear:raw_crimson_iron"),

    quest("structures", 11, 13, "&6Neue Bauwerke",
          subtitle="Mehr als Festungen und Bastionen.",
          description=[
              "Mehrere Mods bauen den Nether aus. Halt die Augen offen:",
              "",
              "&eDungeons and Taverns&r setzt eigene Anlagen in die Biome: Nether-Burgen, Häfen an Lavaseen und Skelett-Türme und Lager, je nach Biom in anderem Stil.",
              "",
              "&eFormations Nether&r verteilt kleinere Bauten: Basalthütten, Schwarzstein-Ruinen, Quarzspitzen, Lavaschreine, Arenen und Kletterparcours, einige davon mit Beute.",
              "",
              "&eYUNG's Better Nether Fortresses&r kennst du schon aus dem Abschnitt Festungen.",
          ],
          tasks=[task_checkmark("Eine neue Struktur gefunden")],
          rewards=[reward_table("s2_common"), reward_xp(10)],
          deps=["biomes"], icon="minecraft:chiseled_polished_blackstone", size=1.5),

    quest("bosses", 13.5, 13, "&4Bosse im Nether",
          subtitle="Für Gruppen, nicht für Einzelgänger.",
          description=[
              "&6L_Ender's Cataclysm&r versteckt zwei große Bosse im Nether: &cIgnis&r wartet in der &6Burning Arena&r, einem brennenden Kolosseum, die &cNetherite Monstrosity&r in der &6Soul Black Smith&r, einer verlassenen Schmiede.",
              "",
              "Beide sind für gut ausgerüstete Gruppen gedacht. Mit Eisenrüstung und ohne Feuerresistenz ist der Kampf schnell vorbei, und nicht zu deinen Gunsten.",
              "",
              "&eKronwerke:&r So etwas ist perfekt für einen gemeinsamen Stream-Abend. Wer eine Arena findet, sagt im Chat Bescheid und gibt die Koordinaten weiter.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(5)],
          deps=["structures"], icon="minecraft:blaze_powder", optional=True),

    # ---- Abschluss -----------------------------------------------------------
    quest("supply", 14.5, 2, "&c&lNether-Versorgung",
          subtitle="Genug für eine ganze Stufe.",
          description=[
              "Du kennst jetzt alles, was der Nether für Stufe 2 hergibt. Zeit für einen Vorrat, der eine Weile hält.",
              "",
              "&6Lohenruten&r für weitere Lohenbrenner und Braustände, &6Netherquarz&r für Elektronenröhren, &6Leuchtstein&r für Licht und spätere Rezepte.",
              "",
              "&eKronwerke:&r Der Server braucht für das Stufenziel tausende Messingbarren, und jeder Mixer mit Messing braucht einen Lohenbrenner. Wenn du mehr Lohen einfängst, als du brauchst: Andere freuen sich.",
          ],
          tasks=[task_item("minecraft:blaze_rod", 16), task_item("minecraft:quartz", 64), task_item("minecraft:glowstone_dust", 32)],
          rewards=[reward_table("s2_rare"), reward_item("minecraft:blaze_rod", 8), reward_xp(20)],
          deps=["blaze_burner", "rose_quartz"], icon="minecraft:blaze_powder", size=2.5, shape="gear"),
]

images = [
    banner("nether/title", "Der Nether", 6, -4.6, height=1.75, kind="title", colour="fire"),
    banner("nether/arrival", "Ankunft", 0, 2.2, height=0.9, colour="fire"),
    banner("nether/resources", "Rohstoffe", 8.5, -2.4, height=0.9, colour="fire"),
    banner("nether/fortresses", "Festungen", 6.5, 4.5, height=0.9, colour="fire"),
    banner("nether/bastions", "Bastionen", 19, 5.6, height=0.9, colour="fire"),
    banner("nether/biomes", "Biome und Strukturen", 9.5, 10.2, height=0.9, colour="fire"),
]

chapter(C, "Der Nether", "minecraft:netherrack", "world", quests, shape="circle", order=8, stage=2,
        subtitle=["Stufe 2: sicher hinein, Lohenruten, Quarz und alles, was die Maschinen von hier unten brauchen."],
        images=images)
