"""Occultism in stage 2: Demon's Dream, Spiritfire, the spirit attuned gem, white chalk, the
first ritual, every Foliot job of Aviar's Circle, Hedyrin's Lure with its possessions and
familiars, Eziveus' Spectral Compulsion, the Djinni pentacles (Ophyx, Strigeor, Ihagan) with
every Djinni job, and Susje's circle. Each ritual is one quest: pentacle, bowls and sacrifice
in the first three lines, numbers from the ritual recipes and multiblocks in the jar.
Afrit, Marid, iesnium, miners and storage are stage 3 (occultism_afrit.py). The root quest
asks for a sacrificial bowl, which is locked until stage 2; the prep quests after it work in
stage 1 already (flexible progression)."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_kill, reward_item, reward_table,
                  reward_xp, banner, img, item_texture)

C = "occultism"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Den Schleier lueften ------------------------------------------------
    quest("welcome", 0, 0, "&5&lSchlag das Dictionary of Spirits auf",
          subtitle="Geister aus der Anderswelt arbeiten für dich.",
          description=[
              "Crafte das &6Dictionary of Spirits&r formlos aus einem &6Buch&r und &6Demon's Dream Seeds&r (fallen beim Abbauen von Gras).",
              "Bau dazu eine &6Sacrificial Bowl&r: &e5 Otherstone&r in U-Form. Die Schale öffnet mit &6Stufe 2&r.",
              "",
              pic("occultism:dictionary_of_spirits"),
              "",
              "&5Occultism&r ruft Geister herbei: Foliot, Djinni, später Afrit und Marid. Sie zerkleinern Erz, schmelzen, fällen Holz und tragen Items. Das Buch zeigt jedes Ritual und jedes Pentakel, auf Wunsch als Vorschau in der Welt.",
              "",
              "Spiritfire, Otherstone und die Kreidezutaten (die Quests rechts) gehen schon in Stufe 1. Kreide, Schalen und Bindungsbücher öffnen mit &6Stufe 2&r, Afrit und Marid mit &6Stufe 3&r.",
          ],
          tasks=[task_item("occultism:dictionary_of_spirits", 1), task_item("occultism:sacrificial_bowl", 1)],
          rewards=[reward_item("occultism:datura_seeds", 8), reward_xp(3)],
          icon="occultism:dictionary_of_spirits", size=2.0, shape="hexagon"),

    quest("datura", 2.5, -1, "&6Bau Demon's Dream an",
          subtitle="Die Frucht, um die sich alles dreht.",
          description=[
              "Pflanz &6Demon's Dream Seeds&r auf Ackerland wie Weizen. Reif gibt die Pflanze &6Demon's Dream Fruit&r und neue Samen.",
              "",
              pic("occultism:datura"),
              "",
              "Die Frucht zündet &dSpiritfire&r, heilt Geister (Rechtsklick auf den Geist) und gibt gegessen mit etwas Glück den &5Third Eye&r. Leg gleich ein kleines Feld an, du brauchst viele.",
          ],
          tasks=[task_item("occultism:datura", 8)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["welcome"], icon="occultism:datura"),

    quest("third_eye", 2.5, 1.2, "&5Öffne den Third Eye",
          subtitle="Neun Früchte, ein klarer Blick.",
          description=[
              "Neun &6Demon's Dream Fruits&r oder Samen (frei gemischt) im Crafting-Feld ergeben &6Demon's Dream Essence&r. Trink sie: Third Eye garantiert und länger.",
              "",
              "Nur mit dem Third Eye aus Demon's Dream baust du &6Otherworld Logs&r und &6Otherstone&r ab. Die Essenz hat Nebenwirkungen, gute und schlechte.",
              "",
              "In Spiritfire geworfen wird sie zu &6Otherworld Essence&r, ohne die schlechten Nebenwirkungen. Die brauchst du später für Händler, Reparaturen und Susje's Circle.",
          ],
          tasks=[task_item("occultism:demons_dream_essence", 1)],
          rewards=[reward_item("occultism:datura_seeds", 8)],
          deps=["datura"], icon="occultism:demons_dream_essence", optional=True),

    quest("spirit_fire", 4.5, -1, "&dZünde Spiritfire",
          subtitle="Ein Feuer, das verwandelt statt verbrennt.",
          description=[
              "Wirf eine &6Demon's Dream Fruit&r auf den Boden und zünde sie mit einem &6Feuerzeug&r an. Wirf dann &6Andesit&r hinein: heraus kommt &6Otherstone&r.",
              "",
              "Spiritfire verletzt keine Lebewesen. Weitere Rezepte: Diorit wird Otherrock, Eichensetzling wird Otherworld-Setzling, Feder, schwarzer Farbstoff und Buch werden Bindungsbuch-Zutaten, Blumen werden Otherflower (ein Farbstoff-Verdreifacher).",
              "",
              "&cAchtung:&r Das Feuer geht nach einer Weile aus. Halt ein paar Früchte bereit.",
          ],
          tasks=[task_item("occultism:otherstone", 16)],
          rewards=[reward_item("minecraft:flint_and_steel", 1), reward_xp(3)],
          deps=["datura"], icon="occultism:otherstone"),

    quest("spirit_campfire", 3.6, 2.9, "&6Bau ein Spirit Campfire",
          subtitle="Spiritfire, das nicht ausgeht.",
          description=[
              "Wie ein Lagerfeuer: &e3 Stämme&r unten, &e3 Stöcke&r, in der Mitte eine &6Demon's Dream Fruit&r statt Kohle. Es brennt dauerhaft mit Spiritfire.",
              "",
              "Stell eine &6Sacrificial Bowl&r darauf: Jedes Item, das in die Schale kommt, verwandelt sich sofort. Mit einem Trichter darüber wird daraus eine kleine Otherstone- oder Kreidefabrik.",
          ],
          tasks=[task_item("occultism:spirit_campfire", 1)],
          rewards=[reward_item("occultism:datura", 8)],
          deps=["spirit_fire"], icon="occultism:spirit_campfire", optional=True),

    quest("otherworld_tree", 6.5, -1, "&6Fäll einen Otherworld-Baum",
          subtitle="Sieht aus wie eine Eiche, ist keine.",
          description=[
              "Wirf einen &6Eichensetzling&r in Spiritfire, pflanz den &6Unstable Otherworld Sapling&r und fäll den Baum &emit Third Eye&r. Ohne ihn gibt es nur Eichenholz.",
              "",
              "Otherworld-Setzlinge fallen nur aus Blättern, die du von Hand abbaust. Wild wachsen die Bäume in &eOtherworld Groves&r, Höhlen tief unter der Oberwelt.",
              "",
              "&eTipp:&r Ein Foliot-Händler tauscht später instabile Setzlinge gegen stabile, die jeder ohne Third Eye fällen kann.",
          ],
          tasks=[task_item("occultism:otherworld_log", 16)],
          rewards=[reward_item("minecraft:oak_sapling", 8), reward_xp(3)],
          deps=["spirit_fire"], icon="occultism:otherworld_log"),

    quest("ashes", 8.5, -1, "&6Brenn Otherworld Ashes",
          subtitle="Die erste Hälfte jeder Kreide.",
          description=[
              "Wirf &6Otherworld Logs&r in Spiritfire. Sie zerfallen zu &6Otherworld Ashes&r, eine Asche pro Stamm.",
          ],
          tasks=[task_item("occultism:otherworld_ashes", 8)],
          rewards=[reward_xp(3)],
          deps=["otherworld_tree"], icon="occultism:otherworld_ashes"),

    quest("burnt_otherstone", 6.5, 1.2, "&6Brenn Otherstone zweimal",
          subtitle="Die zweite Hälfte jeder Kreide.",
          description=[
              "&6Otherstone&r im Ofen wird zu &6Polished Otherstone&r, der noch einmal geschmolzen wird zu &6Burnt Otherstone&r.",
              "",
              "Leg einen ganzen Stapel in einen Ofen und das Ergebnis gleich in einen zweiten. Otherstone brauchst du auch für Schalen, nimm reichlich.",
          ],
          tasks=[task_item("occultism:burnt_otherstone", 8)],
          rewards=[reward_item("minecraft:coal", 16)],
          deps=["spirit_fire"], icon="occultism:burnt_otherstone"),

    quest("spirit_gem", 5.5, 2.9, "&bMach einen Spirit Attuned Gem",
          subtitle="Ein Diamant, der Geister hört.",
          description=[
              "Wirf einen &6Diamanten&r in Spiritfire. Heraus kommt ein &bSpirit Attuned Gem&r.",
              "",
              "Der Gem steckt in der Wünschelrute, den Linsen, der Zauberlampe und, vier im Quadrat, im &bSpirit Attuned Crystal&r für große Pentakel.",
              "",
              "&eRezept auf Kronwerke:&r Der &6ME-Controller&r von AE2 braucht oben einen Spirit Attuned Gem statt eines Fluix-Kristalls. AE2 öffnet mit Stufe 3, leg dir also jetzt schon ein paar Gems zur Seite. Die Abkürzung über Ars Ocultas ist entfernt, nur Spiritfire bleibt.",
          ],
          tasks=[task_item("occultism:spirit_attuned_gem", 2)],
          rewards=[reward_item("minecraft:diamond", 1), reward_xp(5)],
          deps=["spirit_fire"], icon="occultism:spirit_attuned_gem"),

    quest("divination_rod", 7.5, 2.1, "&6Bau eine Wünschelrute",
          subtitle="Findet, was das Auge nicht sieht.",
          description=[
              "&eRezept:&r &6Spirit Attuned Gem&r in die Mitte, &e2 Goldbarren&r oben und unten, &e2 Glas&r links und rechts. Das ist die &6Divination Rod&r.",
              "",
              "Schleichend auf einen Block klicken stellt sie ein: Andesit sucht Otherstone, Eichenholz sucht Otherworld Logs, Eichenlaub sucht Otherworld-Blätter, Netherrack sucht Iesnium. Dann Rechtsklick halten, bis die Animation fertig ist.",
              "",
              "Der Fund leuchtet durch die Wände. Weiße Kristalle heißt nichts gefunden, je violetter, desto näher. Auf Laub oder Holz eingestellt führt sie dich zu einem Otherworld Grove.",
          ],
          tasks=[task_item("occultism:divination_rod", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 4)],
          deps=["spirit_gem"], icon="occultism:divination_rod", optional=True),

    quest("impure_chalk", 10.5, 0, "&6Misch unreine Kreide",
          subtitle="Fast fertig.",
          description=[
              "Im Crafting-Feld &e3 Burnt Otherstone&r in eine Spalte, &e3 Otherworld Ashes&r in die Spalte daneben. Das ergibt eine &6Impure White Chalk&r.",
              "",
              "Unreine weiße Kreide ist die Basis aller 16 Kreidefarben. Jede wird mit Zusatzstoffen gemischt und am Ende in Spiritfire gereinigt.",
          ],
          tasks=[task_item("occultism:chalk_white_impure", 2)],
          rewards=[reward_xp(5)],
          deps=["ashes", "burnt_otherstone"], icon="occultism:chalk_white_impure"),

    quest("white_chalk", 10.5, 2.6, "&f&lReinige weiße Kreide",
          subtitle="Das Werkzeug jedes Beschwörers.",
          description=[
              "Wirf die &6Impure White Chalk&r in Spiritfire. Heraus kommt &fWhite Chalk&r, nutzbar ab &6Stufe 2&r.",
              "",
              "Rechtsklick auf einen Block zeichnet ein Zeichen. Für Rituale zählen nur &eFarbe&r und &ePosition&r, nicht das Symbol. Jede Kreide nutzt sich ab.",
              "",
              "Die Muster aus Kreide, Kerzen und Schädeln heißen &5Pentakel&r. Auf jeder Ritualseite im Dictionary führt ein blauer Link oben zum passenden Pentakel, mit Vorschau in der Welt.",
          ],
          tasks=[task_item("occultism:chalk_white", 2)],
          rewards=[reward_table("s2_common"), reward_xp(5)],
          deps=["impure_chalk"], icon="occultism:chalk_white", size=1.75, shape="diamond"),

    # ---- Das erste Ritual ------------------------------------------------------
    quest("tallow", 0.5, 5.5, "&6Schmied ein Butcher Knife",
          subtitle="Talg für Kerzen.",
          description=[
              "&e2 Eisenbarren&r und &e3 Stöcke&r diagonal ergeben das &6Butcher Knife&r. Schweine, Kühe und Schafe, damit erlegt, lassen &6Tallow&r fallen.",
              "",
              "Aus Talg werden Kerzen, und fast jedes Pentakel braucht Kerzen.",
          ],
          tasks=[task_item("occultism:butcher_knife", 1), task_item("occultism:tallow", 8)],
          rewards=[reward_item("minecraft:string", 16)],
          deps=["white_chalk"], icon="occultism:butcher_knife"),

    quest("candles", 2.5, 5.5, "&6Zieh vier Large Candles",
          subtitle="Kerzen halten den Kreis stabil.",
          description=[
              "Ein &6Faden&r über einem &6Tallow&r ergibt eine &6Large Candle&r. Kerzen aus Minecraft oder anderen Mods zählen in Pentakeln genauso.",
              "",
              "Kerzen verlangsamen den Essenzzerfall des gerufenen Geistes. Große Kerzen zählen am Zaubertisch wie Bücherregale und lassen sich in 16 Farben färben.",
          ],
          tasks=[task_item("occultism:large_candle", 4)],
          rewards=[reward_item("occultism:tallow", 8)],
          deps=["tallow"], icon="occultism:large_candle"),

    quest("bowls", 0.5, 7.5, "&6Stell vier Opferschalen auf",
          subtitle="Hier liegen die Zutaten.",
          description=[
              "&e5 Otherstone&r in U-Form ergeben eine &6Sacrificial Bowl&r. Zutaten legst du mit Rechtsklick hinein und nimmst sie genauso wieder heraus.",
              "",
              "Die Schalen müssen irgendwo im Umkreis von &e8 Blöcken&r um die Mitte stehen, die genaue Stelle ist egal. Mit Kupfer- oder Silberbarren gecraftet bekommst du hübschere Varianten.",
              "",
              "&eTipp:&r Bau gleich acht. Spätere Rituale haben bis zu acht Zutaten.",
          ],
          tasks=[task_item("occultism:sacrificial_bowl", 4)],
          rewards=[reward_item("occultism:otherstone", 16)],
          deps=["tallow"], icon="occultism:sacrificial_bowl"),

    quest("golden_bowl", 2.5, 7.5, "&6Bau die goldene Ritualschale",
          subtitle="Die Mitte jedes Pentakels.",
          description=[
              "Eine &6Sacrificial Bowl&r mit &e8 Goldblechen&r aus der Create-Presse drumherum ergibt die &6Golden Ritual Bowl&r. Sie steht immer in der Mitte.",
              "",
              "Rechtsklick mit dem Startitem (meist ein gebundenes Bindungsbuch) startet das Ritual. Ein Trichter kann das Startitem auch hineinlegen. Eine Opferschale kopfüber bis drei Blöcke darüber fängt das Ergebnis auf.",
              "",
              "Redstone-Signal der Schale: &e1&r wartet auf ein Opfer, &e2&r wartet auf ein benutztes Item, &e8&r läuft.",
          ],
          tasks=[task_item("occultism:golden_sacrificial_bowl", 1)],
          rewards=[reward_item("create:golden_sheet", 8)],
          deps=["bowls", "candles"], icon="occultism:golden_sacrificial_bowl"),

    quest("book_parts", 4.5, 5.5, "&6Weih Feder, Tinte und Buch",
          subtitle="Drei Zutaten aus Spiritfire.",
          description=[
              "Wirf eine &6Feder&r, &6schwarzen Farbstoff&r und ein &6Buch&r in Spiritfire. Heraus kommen &6Awakened Feather&r, &6Purified Ink&r und &6Taboo Book&r.",
              "",
              "Jedes Ritual verbraucht ein Bindungsbuch, mach gleich mehrere Sätze. Schwarzen Farbstoff gibt es auch aus Belladonna-Beeren von Hexerei. Formlos zusammen ergeben die drei ein leeres Bindungsbuch.",
          ],
          tasks=[task_item("occultism:awakened_feather", 1), task_item("occultism:purified_ink", 1),
                 task_item("occultism:taboo_book", 1)],
          rewards=[reward_item("minecraft:book", 4), reward_item("minecraft:feather", 8)],
          deps=["white_chalk"], icon="occultism:taboo_book"),

    quest("book_foliot", 6.5, 5.5, "&9Bind einen Foliot-Namen",
          subtitle="Ein Name auf Papier ist eine Leine.",
          description=[
              "&6Taboo Book&r, &6Purified Ink&r, &6Awakened Feather&r und &e4 blauer Farbstoff&r ergeben das &6Book of Binding: Foliot&r.",
              "Dann formlos mit dem &6Dictionary of Spirits&r craften. Das Dictionary bleibt, das Buch ist jetzt gebunden.",
              "",
              pic("occultism:book_of_binding_bound_foliot"),
              "",
              "Farbe pro Rang: &9Blau&r Foliot, &5Violett&r Djinni, &eGelb&r Afrit, &aGrün&r Marid. Der Name im Buch ist egal, nur der Rang zählt.",
              "",
              "&eTipp:&r Bis zu sechs Bücher auf einmal: in ein Gemeißeltes Bücherregal stellen und schleichend mit dem Dictionary darauf klicken.",
          ],
          tasks=[task_item("occultism:book_of_binding_bound_foliot", 2)],
          rewards=[reward_item("minecraft:blue_dye", 8), reward_xp(5)],
          deps=["book_parts"], icon="occultism:book_of_binding_bound_foliot"),

    quest("silver", 8.5, 4.4, "&7Schmilz Silber",
          subtitle="Das Metall, das Geister respektieren.",
          description=[
              "&6Silbererz&r liegt in der Oberwelt, auch als Tiefenschiefer-Erz. Rohsilber schmilzt im Ofen zu &6Silver Ingots&r.",
              "",
              "Das erste Ritual will einen Silberbarren. Später steckt Silber in Lampen, Taschen, Linsen und Seelensteinen.",
          ],
          tasks=[task_item("occultism:silver_ingot", 8)],
          rewards=[reward_item("occultism:raw_silver", 8)],
          deps=["white_chalk"], icon="occultism:silver_ingot"),

    quest("aviar", 8.5, 6.5, "&5Zeichne Aviar's Circle",
          subtitle="Das Pentakel für Foliot.",
          description=[
              "&5Aviar's Circle&r, 9x9: &e24 weiße&r Zeichen als Kreis mit Kreuz, &e4 Kerzen&r diagonal neben der Mitte, goldene Schale im Zentrum.",
              "Stell mindestens &e4 Opferschalen&r im Umkreis von 8 Blöcken dazu. Die Vorschau im Dictionary zeigt jedes Zeichen.",
              "",
              "&eWas es ruft:&r Foliot mit Beruf. Brecher, Schmelzer, Kristallisierer, Holzfäller, Bauer, Träger, Hausmeister und drei Händler. Die Checkliste rechts hat für jeden eine Quest.",
              "",
              "&eTipp:&r Graue Partikel an der goldenen Schale heißen: Das Ritual wartet auf ein Opfer oder ein benutztes Item.",
          ],
          tasks=[task_checkmark("Aviar's Circle gezeichnet")],
          rewards=[reward_item("occultism:large_candle", 4), reward_xp(5)],
          deps=["golden_bowl", "book_foliot"], icon="occultism:chalk_white"),

    quest("foliot_crusher", 10.7, 6.5, "&d&lRuf einen Foliot Crusher",
          subtitle="Ein Erz, zwei Staub.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r je ein &6Eisen-, Gold-, Kupfer-&r und &6Silberbarren&r.",
              "&cOpfer:&r keins. Gebundenes Foliot-Buch auf die goldene Schale, nach &e60 Sekunden&r steht er da.",
              "",
              "Wirf ihm Erz oder Rohes Erz hin: &eein Erz wird zwei Staub&r. Staub im Ofen gibt Barren, das verdoppelt deine Ausbeute. Er arbeitet halb so schnell wie der Djinni.",
              "",
              "Foliot mit Beruf altern nicht. Verletzt heilst du sie mit einer Demon's Dream Fruit.",
          ],
          tasks=[task_checkmark("Foliot Crusher beschworen")],
          rewards=[reward_item("minecraft:raw_iron", 32), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["aviar", "silver"], icon="occultism:book_of_binding_foliot", size=1.75, shape="diamond"),

    # ---- Aviar's Circle: alle Foliot-Berufe -------------------------------------
    quest("foliot_smelter", 13.2, 4.6, "&dRuf einen Foliot Smelter",
          subtitle="Ein Ofen ohne Brennstoff.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r &6Kohle&r, ein &6Ofen&r, ein &6Lagerfeuer&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Er schmilzt alles, was Ofen, Hochofen, Räucherofen oder Lagerfeuer können, ohne Brennstoff und so schnell wie ein Ofen.",
          ],
          tasks=[task_checkmark("Foliot Smelter beschworen")],
          rewards=[reward_item("minecraft:coal", 16)],
          deps=["foliot_crusher"], icon="minecraft:furnace"),

    quest("foliot_crystallizer", 15.2, 4.6, "&dRuf einen Foliot Crystallizer",
          subtitle="Staub wird wieder Edelstein.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r ein &bSpirit Attuned Crystal&r (4 Gems im Quadrat), &6Amethyst-, Lapis-&r und &6Smaragdstaub&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Er macht aus Edelsteinstaub wieder Edelsteine und vervielfacht Edelsteinerze. Der Foliot ist dabei sehr langsam, der Djinni doppelt so schnell.",
          ],
          tasks=[task_checkmark("Foliot Crystallizer beschworen")],
          rewards=[reward_item("minecraft:lapis_lazuli", 16)],
          deps=["foliot_smelter"], icon="occultism:spirit_attuned_crystal", optional=True),

    quest("foliot_transporter", 13.2, 6.5, "&dRuf einen Foliot Transporter",
          subtitle="Ein Träger, der nie müde wird.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r eine &6Lore&r, eine &6Truhe&r, ein &6Werfer&r, ein &6Trichter&r.",
              "&cOpfer:&r keins. Mit ihm erscheint sein &6Book of Calling&r.",
              "",
              "Schleichend mit dem Buch auf eine Truhe klicken legt fest, woher er nimmt, genauso das Ziel. Er liefert auch in Geister, zum Beispiel Erz direkt in den Crusher.",
              "",
              "&cAchtung:&r Er startet auf &eWhitelist&r und trägt nichts. Schleichend auf ihn klicken und die Items eintragen.",
          ],
          tasks=[task_item("occultism:book_of_calling_foliot_transport_items", 1)],
          rewards=[reward_item("minecraft:chest", 4), reward_xp(5)],
          deps=["foliot_crusher"], icon="occultism:book_of_calling_foliot_transport_items"),

    quest("foliot_janitor", 15.2, 6.5, "&dRuf einen Foliot Janitor",
          subtitle="Er räumt hinter den anderen auf.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r ein &6Chalk Brush&r (3 Bretter, 2 Wolle, Faden), eine &6Truhe&r, ein &6Werfer&r, ein &6Trichter&r.",
              "&cOpfer:&r keins. Mit ihm erscheint sein Book of Calling.",
              "",
              "Er sammelt liegende Items ein und bringt sie in eine Zieltruhe. Neben dem Crusher trägt er den Staub weg, sobald du ihn in die Erlaubt-Liste einträgst (er startet ebenfalls auf Whitelist).",
              "",
              "Transporter rein, Janitor raus: Das ist deine erste automatische Erzstraße. Der Brush selbst wischt Kreidezeichen schnell weg.",
          ],
          tasks=[task_item("occultism:book_of_calling_foliot_cleaner", 1)],
          rewards=[reward_item("minecraft:hopper", 2), reward_xp(5)],
          deps=["foliot_transporter"], icon="occultism:book_of_calling_foliot_cleaner"),

    quest("foliot_farmer", 17.2, 6.5, "&dRuf einen Foliot Farmer",
          subtitle="Ernten und neu säen.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r &6Demon's Dream Fruit&r, &6Weizen&r, &6Karotte&r, &6Kartoffel&r, eine &6Hacke&r.",
              "&cOpfer:&r keins. Mit ihm erscheint sein Book of Calling.",
              "",
              "Mit dem Buch legst du Arbeitsbereich und Abgabetruhe fest. Er erntet reife Pflanzen und pflanzt neu. Macht er nach einem leeren Feld ein paar Minuten Pause, ist das Absicht.",
          ],
          tasks=[task_item("occultism:book_of_calling_foliot_farmer", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 32)],
          deps=["foliot_janitor"], icon="occultism:book_of_calling_foliot_farmer", optional=True),

    quest("ars_ocultas", 17.2, 4.6, "&bBau den Sacrificial Altar",
          subtitle="Ars Ocultas: Opfer mit Quelle bezahlen.",
          description=[
              "Im Bezaubernden Apparat von &dArs Nouveau&r: &6Golden Ritual Bowl&r in die Mitte, &e4 Silberbarren&r, &e2 Quellstein&r, ein &6Drygmy-Scherben&r und ein &6Eindämmungsglas&r, dazu 5 000 Quelle.",
              "",
              "Der Altar kommt unter die goldene Schale. Will ein Ritual ein Tieropfer und steht ein Eindämmungsglas mit dem passenden Tier in der Nähe, zahlt der Altar mit Quelle aus einem Quellglas. Das Tier lebt weiter.",
              "",
              "Außerdem arbeiten Geister wie dein Crusher in einem Eindämmungsglas weiter, per Trichter befüllt.",
          ],
          tasks=[task_item("ars_ocultas:altar", 1)],
          rewards=[reward_item("occultism:silver_ingot", 4), reward_xp(5)],
          deps=["foliot_crystallizer"], icon="ars_ocultas:altar", optional=True),

    quest("sapling_trader", 13.2, 8.4, "&dRuf den Setzlingshändler",
          subtitle="Stabile Setzlinge für alle.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r je ein &6Eichen-, Birken-, Fichten-&r und &6Tropenbaumsetzling&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Wirf ihm &6Unstable Otherworld Saplings&r hin, er gibt &6Stable Otherworld Saplings&r zurück. Deren Bäume fällt jeder ohne Third Eye, und sie geben wieder stabile Setzlinge.",
              "",
              "&cAchtung:&r Händler zerfallen. Nach etwa &eeiner Stunde&r ist er weg, tausch gleich einen Stapel.",
          ],
          tasks=[task_item("occultism:otherworld_sapling", 4)],
          rewards=[reward_item("minecraft:oak_sapling", 16), reward_xp(5)],
          deps=["foliot_crusher"], icon="occultism:otherworld_sapling"),

    quest("foliot_lumberjack", 15.2, 8.4, "&dRuf einen Foliot Lumberjack",
          subtitle="Holz fällen und nachpflanzen.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r ein &6Stable Otherworld Sapling&r, ein &6Eichen-, Birken-&r und &6Fichtensetzling&r, eine &6Axt&r.",
              "&cOpfer:&r keins. Mit ihm erscheint sein Book of Calling.",
              "",
              "Leg mit dem Buch Arbeitsbereich und Abgabetruhe fest. Er fällt jeden Baum im Bereich, bringt das Holz weg und pflanzt die Setzlinge neu.",
          ],
          tasks=[task_item("occultism:book_of_calling_foliot_lumberjack", 1)],
          rewards=[reward_item("minecraft:iron_axe", 1), reward_xp(5)],
          deps=["sapling_trader"], icon="occultism:book_of_calling_foliot_lumberjack"),

    quest("otherstone_trader", 17.2, 8.4, "&dRuf den Otherstone-Händler",
          subtitle="Baumaterial im Großen.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r je ein &6Stein&r, &6Granit&r, &6Diorit&r und &6Andesit&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Wirf ihm Steinsorten hin, er tauscht sie gegen &6Otherstone&r, schneller als Spiritfire. Er zerfällt nach etwa einer Stunde.",
          ],
          tasks=[task_checkmark("Otherstone-Händler beschworen")],
          rewards=[reward_item("minecraft:andesite", 32)],
          deps=["foliot_lumberjack"], icon="occultism:otherstone", optional=True),

    quest("otherrock_trader", 19.2, 8.4, "&dRuf den Otherrock-Händler",
          subtitle="Dunkler Stein für Baumeister.",
          description=[
              "&5Pentakel:&r Aviar's Circle.",
              "&6Schalen:&r je ein &6Tiefenschiefer&r, &6Tropfsteinblock&r, &6Kalzit&r und &6Magmablock&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Er tauscht wie der Otherstone-Händler, nur gegen &6Otherrock&r. Otherrock taugt für Schalen und zum Bauen, aber nicht für Kreide.",
          ],
          tasks=[task_checkmark("Otherrock-Händler beschworen")],
          rewards=[reward_item("minecraft:diorite", 32)],
          deps=["otherstone_trader"], icon="occultism:otherrock", optional=True),

    # ---- Hedyrin's Lure: Besessenheit -----------------------------------------
    quest("yellow_chalk", 0.5, 12.5, "&eMisch gelbe Kreide",
          subtitle="Die Farbe der Besessenheit.",
          description=[
              "&6Impure White Chalk&r, &6Glowstonestaub&r und &e2 Goldstaub&r (vom Crusher) formlos, dann in Spiritfire. Das ist &eYellow Chalk&r (im Spiel Golden Chalk).",
              "",
              "Gelb lässt Geister in Lebewesen fahren. Besessene Wesen lassen seltene Beute viel häufiger fallen. Glowstone kommt aus dem Nether, der ab Stufe 2 offen ist.",
          ],
          tasks=[task_item("occultism:chalk_gold", 1)],
          rewards=[reward_item("minecraft:glowstone_dust", 8)],
          deps=["foliot_crusher"], icon="occultism:chalk_gold"),

    quest("hedyrin", 2.5, 12.5, "&5Zeichne Hedyrin's Lure",
          subtitle="Das Pentakel für Foliot-Besessenheit.",
          description=[
              "&5Hedyrin's Lure&r, 9x9: &e12 weiße&r Zeichen, &e4 gelbe&r Zeichen, &e4 Kerzen&r, goldene Schale in der Mitte.",
              "Gestartet wird mit dem gebundenen Foliot-Buch, wie bei Aviar's Circle.",
              "",
              "&eWas es ruft:&r besessene Endermite, Skelette, Hexen und Phantome, einen wilden Papagei, Zufallstiere (gewöhnlich, klein, Wasser) und die ersten Vertrauten: Greedy, Beaver, Deer, Blacksmith und Parrot.",
          ],
          tasks=[task_checkmark("Hedyrin's Lure gezeichnet")],
          rewards=[reward_item("occultism:large_candle", 4), reward_xp(5)],
          deps=["yellow_chalk"], icon="occultism:chalk_gold"),

    quest("endermite", 4.5, 11.5, "&5Ruf einen Possessed Endermite",
          subtitle="Endstein, ohne ins End zu reisen.",
          description=[
              "&5Pentakel:&r Hedyrin's Lure.",
              "&6Schalen:&r &e2 Erde&r, &e2 Stein&r.",
              "&cOpfer:&r keins, aber bei grauen Partikeln wirfst du ein &6Ei&r in die Nähe.",
              "",
              "Der Endermite reist mit dem Foliot ins End und zurück. Besiegt lässt er immer &6Endstein&r fallen. Das End öffnet erst mit Stufe 4, bis dahin ist er deine Quelle für violette Kreide.",
          ],
          tasks=[task_kill("occultism:possessed_endermite", 2)],
          rewards=[reward_item("minecraft:egg", 16), reward_xp(5)],
          deps=["hedyrin"], icon="minecraft:egg"),

    quest("skeleton", 4.5, 13.5, "&5Ruf ein Possessed Skeleton",
          subtitle="Schädel für stärkere Pentakel.",
          description=[
              "&5Pentakel:&r Hedyrin's Lure.",
              "&6Schalen:&r &e4 Knochen&r.",
              "&cOpfer:&r ein &6Huhn&r in der Nähe, wenn die grauen Partikel kommen.",
              "",
              "Das Skelett brennt nicht in der Sonne und lässt immer einen &6Skelettschädel&r fallen. Ophyx' Calling braucht 4 Schädel, Strigeor's Higher Binding 8.",
          ],
          tasks=[task_item("minecraft:skeleton_skull", 4)],
          rewards=[reward_item("minecraft:bone", 16), reward_xp(5)],
          deps=["hedyrin"], icon="minecraft:skeleton_skull"),

    quest("possess_more", 6.5, 13.5, "&5Ruf Hexe und Phantom",
          subtitle="Flaschen und Membranen auf Bestellung.",
          description=[
              "&5Pentakel:&r Hedyrin's Lure, beide mit dem Foliot-Buch.",
              "&6Hexe:&r Glasflasche, Redstone, brauner und roter Pilz, &cOpfer:&r ein Huhn. Lässt Erfahrungs-, Honig- oder Unheilvolle Flaschen fallen.",
              "&6Phantom:&r &e2 Leder&r, &e2 Federn&r, &cOpfer:&r ein fliegendes Tier. Lässt immer &6Phantomhaut&r fallen.",
              "",
              "Phantomhaut brauchst du für die Gray Paste. Zufallstiere rufst du mit 8 Zutaten (Samen und Feldfrüchte, Federn und Zucker, Seegras und Schlamm) und einem Ei oder Schneeball statt eines Opfers.",
          ],
          tasks=[task_item("minecraft:phantom_membrane", 2)],
          rewards=[reward_item("minecraft:leather", 8)],
          deps=["skeleton"], icon="minecraft:phantom_membrane", optional=True),

    quest("familiars", 2.5, 14.7, "&dRuf einen Greedy Familiar",
          subtitle="Dein erster Vertrauter sammelt für dich.",
          description=[
              "&5Pentakel:&r Hedyrin's Lure.",
              "&6Schalen:&r eine &6Truhe&r, ein &6Eisenblock&r, ein &6Werfer&r, ein &6Trichter&r.",
              "&cOpfer:&r ein &6Zombie&r in der Nähe.",
              "",
              "Vertraute folgen dir und geben Boni. Der Greedy hebt Items im Umkreis von 32 Blöcken für dich auf. Im &6Familiar Ring&r (Strigeor's Higher Binding) erhöht er deinen Aufsammelradius.",
          ],
          tasks=[task_checkmark("Greedy Familiar gerufen")],
          rewards=[reward_item("minecraft:iron_block", 1), reward_xp(5)],
          deps=["hedyrin"], icon="minecraft:chest"),

    quest("fam_beaver", 0.5, 16.3, "&dRuf einen Beaver",
          subtitle="Holzfällen schneller.",
          description=[
              "&5Pentakel:&r Hedyrin's Lure.",
              "&6Schalen:&r &e4 Stämme&r.",
              "&cOpfer:&r ein &6Schwein&r.",
              "",
              "Der Biber lässt dich Holz schneller abbauen und fällt kleine Bäume, die neben ihm aus Setzlingen wachsen.",
          ],
          tasks=[task_checkmark("Beaver gerufen")],
          rewards=[reward_item("minecraft:oak_log", 16)],
          deps=["familiars"], icon="minecraft:oak_log", optional=True),

    quest("fam_deer", 2.5, 16.5, "&dRuf einen Deer",
          subtitle="Tempo, Sprungkraft, Stufenhilfe.",
          description=[
              "&5Pentakel:&r Hedyrin's Lure.",
              "&6Schalen:&r &e4 Stöcke&r, &e2 Fäden&r.",
              "&cOpfer:&r eine &6Kuh&r.",
              "",
              "Der Hirsch gibt Tempo und Sprungkraft und lässt dich ganze Blöcke hochlaufen. Wer viel zu Fuß unterwegs ist, nimmt ihn zuerst.",
          ],
          tasks=[task_checkmark("Deer gerufen")],
          rewards=[reward_item("minecraft:string", 8)],
          deps=["familiars"], icon="minecraft:stick", optional=True),

    quest("fam_blacksmith", 4.5, 16.3, "&dRuf einen Blacksmith",
          subtitle="Repariert dich und verbessert die anderen.",
          description=[
              "&5Pentakel:&r Hedyrin's Lure.",
              "&6Schalen:&r eiserne &6Schaufel&r, &6Spitzhacke&r und &6Axt&r, ein &6Amboss&r, &e4 Stein&r.",
              "&cOpfer:&r ein &6Zombie&r.",
              "",
              "Hebst du Stein auf, repariert er deine Ausrüstung mit 33 Prozent Chance ein Stück. Gib ihm &e18 Eisen&r, und er verbessert einen anderen Vertrauten. Verbesserte bekommen einen Stern am Namen und einen Zusatzeffekt.",
          ],
          tasks=[task_checkmark("Blacksmith gerufen")],
          rewards=[reward_item("minecraft:iron_ingot", 18)],
          deps=["familiars"], icon="minecraft:anvil", optional=True),

    # ---- Eziveus: Foliot in Gegenstaenden ---------------------------------------
    quest("purple_chalk", 6.5, 11.5, "&5Misch violette Kreide",
          subtitle="Die Kreide der Bindung.",
          description=[
              "&6Impure White Chalk&r, &e1 Endsteinstaub&r und &e2 Obsidianstaub&r formlos, dann in Spiritfire. Beide Stäube macht dein Crusher.",
              "",
              "Violett bindet Geister in Gegenstände. Das erste Pentakel dafür ist Eziveus' Spectral Compulsion.",
          ],
          tasks=[task_item("occultism:chalk_purple", 1)],
          rewards=[reward_item("minecraft:obsidian", 4)],
          deps=["endermite"], icon="occultism:chalk_purple"),

    quest("eziveus", 8.5, 11.5, "&5Zeichne Eziveus' Spectral Compulsion",
          subtitle="Das Pentakel für Foliot-Gegenstände.",
          description=[
              "&5Eziveus' Spectral Compulsion&r, 9x9: &e16 weiße&r und &e12 violette&r Zeichen, &e8 Kerzen&r.",
              "Gestartet wird mit dem Foliot-Buch. Heraus kommt kein Geist, sondern ein Gegenstand.",
              "",
              "&eWas es macht:&r Research Fragment Dust, Nature Paste, Fragile Soul Gem, Vitality Compass, Knowledge Tablet, Infused Lenses und zwei Taschen. In Stufe 3 dazu: Foliot Miner, Speicherbasis, Stable Wormhole, Speicherstabilisator Stufe 1.",
          ],
          tasks=[task_checkmark("Eziveus' Spectral Compulsion gezeichnet")],
          rewards=[reward_item("occultism:large_candle", 4), reward_xp(5)],
          deps=["purple_chalk"], icon="occultism:chalk_purple"),

    quest("research_dust", 10.5, 11.5, "&6Mahl Research Fragment Dust",
          subtitle="Wissen, zu Staub zermahlen.",
          description=[
              "&5Pentakel:&r Eziveus' Spectral Compulsion.",
              "&6Schalen:&r &6Smaragdstaub&r (vom Crusher), &e2 Erfahrungsfläschchen&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch, 60 Sekunden.",
              "",
              "Der Staub ist die Hauptzutat der Limettenkreide, und die steckt in jedem Djinni-Pentakel.",
          ],
          tasks=[task_item("occultism:research_fragment_dust", 2)],
          rewards=[reward_item("minecraft:experience_bottle", 8)],
          deps=["eziveus"], icon="occultism:research_fragment_dust"),

    quest("satchel", 8.5, 13.5, "&6Binde eine Apprentice Ritual Satchel",
          subtitle="Pentakel zeichnen ohne Kopfzerbrechen.",
          description=[
              "&5Pentakel:&r Eziveus' Spectral Compulsion.",
              "&6Schalen:&r &6Trichter&r, &6Werfer&r, &e2 Wolle&r, &e2 Leder&r, &6Faden&r, &6Silberbarren&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Pack Kreiden, Kerzen und Schädel hinein (schleichend Rechtsklick). Wähl im Dictionary über das Auge ein Pentakel, setz die Vorschau mit Rechtsklick fest, dann setzt jeder Klick mit der Tasche auf ein Vorschauzeichen das richtige Teil.",
              "",
              "Die Artisanal Satchel aus Stufe 3 zeichnet das ganze Pentakel mit einem Klick.",
          ],
          tasks=[task_item("occultism:ritual_satchel_t1", 1)],
          rewards=[reward_item("minecraft:leather", 8), reward_xp(5)],
          deps=["eziveus"], icon="occultism:ritual_satchel_t1"),

    quest("substantial_satchel", 8.5, 15.3, "&6Binde eine Substantial Satchel",
          subtitle="Eine Tasche, innen größer als außen.",
          description=[
              "&5Pentakel:&r Eziveus' Spectral Compulsion.",
              "&6Schalen:&r eine &6Holztruhe&r, &e2 Leder&r, &6Faden&r, &6Silberbarren&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Ein Foliot verbiegt den Raum in der &6Surprisingly Substantial Satchel&r ein wenig. Sie fasst deutlich mehr, als sie groß ist.",
          ],
          tasks=[task_item("occultism:satchel", 1)],
          rewards=[reward_item("minecraft:chest", 2)],
          deps=["satchel"], icon="occultism:satchel", optional=True),

    quest("foliot_trinkets", 10.5, 13.5, "&6Binde kleine Artefakte",
          subtitle="Seelenstein, Kompass, Erfahrungstafel.",
          description=[
              "&5Pentakel:&r Eziveus' Spectral Compulsion, alle mit dem Foliot-Buch, kein Opfer.",
              "&6Fragile Soul Gem:&r Eisenbarren, Ei, Glas. &6Vitality Compass:&r Amethyst, &e2 Spirit Attuned Gems&r, Kompass.",
              "&6Knowledge Tablet:&r Otherstone Tablet, Research Fragment Dust, Spirit Attuned Gem, Enderperle.",
              "",
              "Der zerbrechliche Seelenstein trägt ein Wesen einmal, dann zerbricht er. Er steckt im echten Soul Gem. Der Kompass zeigt auf ein Wesen, das du damit angeklickt hast. Die Tafel speichert deine Erfahrung (Rechtsklick) und gibt sie zurück (schleichend Rechtsklick).",
          ],
          tasks=[task_item("occultism:fragile_soul_gem", 1)],
          rewards=[reward_item("minecraft:egg", 8), reward_xp(5)],
          deps=["research_dust"], icon="occultism:fragile_soul_gem"),

    quest("nature_paste", 10.5, 15.3, "&aMisch Nature Paste",
          subtitle="Grün für die wilden Geister.",
          description=[
              "&5Pentakel:&r Eziveus' Spectral Compulsion.",
              "&6Schalen:&r &e3 Laubblöcke&r, &e3 Setzlinge&r, &e3 Samen&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch.",
              "",
              "Mit unreiner weißer Kreide wird daraus &aGreen Chalk&r für Osorin's Unbound Calling (Stufe 3, braucht auch rosa und hellblaue Kreide). Nebenbei macht die Paste aus Bruchstein bemoosten Bruchstein.",
          ],
          tasks=[task_item("occultism:nature_paste", 2)],
          rewards=[reward_item("minecraft:mossy_cobblestone", 8)],
          deps=["foliot_trinkets"], icon="occultism:nature_paste", optional=True),

    # ---- Djinni ----------------------------------------------------------------
    quest("lime_chalk", 12.5, 11.5, "&aMisch Limettenkreide",
          subtitle="Die Farbe der Djinni.",
          description=[
              "&6Impure White Chalk&r, &6Research Fragment Dust&r, &6Smaragdstaub&r und ein &6Schleimball&r formlos, dann in Spiritfire: &aLime Chalk&r.",
              "",
              "Limette gibt einem Pentakel die Rufkraft für Djinni. Ophyx' Calling braucht &e36 Zeichen&r davon, also mehrere Stück Kreide.",
          ],
          tasks=[task_item("occultism:chalk_lime", 2)],
          rewards=[reward_item("minecraft:slime_ball", 8), reward_xp(5)],
          deps=["research_dust"], icon="occultism:chalk_lime"),

    quest("light_gray_chalk", 12.5, 13.5, "&7Misch hellgraue Kreide",
          subtitle="Ein Fundament ohne Weiß.",
          description=[
              "&6Impure White Chalk&r mit &6Silber-&r, &6Eisen-&r und &6Kalzitstaub&r, alle vom Crusher, dann in Spiritfire.",
              "",
              "Djinni-Pentakel haben Stellen, an die keine weiße Kreide darf. Dort gehört Hellgrau hin, Grau oder Schwarz gehen auch. Hellgrau darf außerdem überall stehen, wo Weiß verlangt ist.",
          ],
          tasks=[task_item("occultism:chalk_light_gray", 1)],
          rewards=[reward_item("minecraft:calcite", 16)],
          deps=["lime_chalk"], icon="occultism:chalk_light_gray"),

    quest("book_djinni", 14.5, 11.5, "&5Bind einen Djinni-Namen",
          subtitle="Ein stärkerer Name.",
          description=[
              "&6Taboo Book&r, &6Purified Ink&r, &6Awakened Feather&r und &e4 violetter Farbstoff&r, dann mit dem Dictionary binden.",
              "",
              "Djinni sind die meistgerufene Klasse: schneller als Foliot, gut für Besessenheit stärkerer Wesen und wertvollere Bindungen.",
          ],
          tasks=[task_item("occultism:book_of_binding_bound_djinni", 2)],
          rewards=[reward_item("minecraft:purple_dye", 8), reward_xp(5)],
          deps=["lime_chalk"], icon="occultism:book_of_binding_bound_djinni"),

    quest("ophyx", 16.5, 12.5, "&5Zeichne Ophyx' Calling",
          subtitle="Das Pentakel für Djinni.",
          description=[
              "&5Ophyx' Calling&r, 13x13: &e36 limettengrüne&r, &e16 weiße&r und &e8 hellgraue&r Zeichen, &e8 Kerzen&r, &e4 Skelettschädel&r.",
              "Die Schädel holst du vom Possessed Skeleton. Lass die Ritual Satchel zeichnen, das spart viel Zählerei.",
              "",
              "&eWas es ruft:&r Djinni Crusher, Smelter und Crystallizer, Tag, Nacht und klares Wetter, den Glücksspieler, den Wandernden Händler, den Maschinenbediener und den dämonischen Partner.",
          ],
          tasks=[task_checkmark("Ophyx' Calling gezeichnet")],
          rewards=[reward_item("occultism:large_candle", 8), reward_xp(5)],
          deps=["book_djinni", "light_gray_chalk"], icon="occultism:chalk_lime"),

    quest("djinni_crusher", 18.7, 12.5, "&d&lRuf einen Djinni Crusher",
          subtitle="Ein Erz, drei Staub.",
          description=[
              "&5Pentakel:&r Ophyx' Calling.",
              "&6Schalen:&r je ein &6Eisen-, Gold-, Kupfer-&r und &6Silberstaub&r.",
              "&cOpfer:&r keins. Gebundenes Djinni-Buch, 120 Sekunden.",
              "",
              "Er macht aus &eeinem Erz drei Staub&r und ist doppelt so schnell wie der Foliot. Er zerkleinert auch Eis, Packeis und Blaueis zu Staub, ohne dass es schmilzt.",
              "",
              "Afrit (vier Staub) und Marid (sechs) kommen mit &6Stufe 3&r.",
          ],
          tasks=[task_checkmark("Djinni Crusher beschworen")],
          rewards=[reward_item("minecraft:raw_gold", 32), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["ophyx"], icon="occultism:book_of_binding_djinni", size=1.75, shape="diamond"),

    quest("djinni_smelter", 20.9, 10.9, "&dRuf einen Djinni Smelter",
          subtitle="Doppelt so schnell wie ein Ofen.",
          description=[
              "&5Pentakel:&r Ophyx' Calling.",
              "&6Schalen:&r eine &6Feuerkugel&r, ein &6Hochofen&r, ein &6Räucherofen&r, ein &6Feuerzeug&r.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch.",
              "",
              "Er schmilzt ohne Brennstoff in der halben Zeit. Neben den Djinni Crusher gestellt, mit Transporter und Janitor dazwischen, wird aus Erz ohne dein Zutun Barren.",
          ],
          tasks=[task_checkmark("Djinni Smelter beschworen")],
          rewards=[reward_item("minecraft:blast_furnace", 1)],
          deps=["djinni_crusher"], icon="minecraft:blast_furnace"),

    quest("djinni_time", 20.9, 12.5, "&dStell Zeit und Wetter",
          subtitle="Djinni, die einmal wirken und gehen.",
          description=[
              "&5Pentakel:&r Ophyx' Calling, alle mit dem Djinni-Buch, kein Opfer, 60 Sekunden.",
              "&eTag:&r Fackel, Setzling, Weizen, gelber Farbstoff. &eNacht:&r Schwarzpulver, verrottetes Fleisch, Knochen, schwarzer Farbstoff.",
              "&eKlares Wetter:&r Rote Bete, Karotte, Kartoffel, Weizen.",
              "",
              "Der Geist ändert die Welt einmal und verschwindet. Zeit und Wetter gelten für alle, sprecht euch auf dem Server ab. Regen und Gewitter rufen erst Afrit (Stufe 3).",
          ],
          tasks=[task_checkmark("Einen Zeit- oder Wettergeist gerufen")],
          rewards=[reward_item("minecraft:clock", 1)],
          deps=["djinni_crusher"], icon="minecraft:clock", optional=True),

    quest("djinni_extras", 20.9, 14.1, "&dRuf die übrigen Djinni",
          subtitle="Glücksspieler, Händler, Partner, Bediener.",
          description=[
              "&5Pentakel:&r Ophyx' Calling, alle mit dem Djinni-Buch.",
              "&6Glücksspieler:&r Smaragd, Diamantblock, Goldbarren, Silberblock. &6Wandernder Händler:&r &e2 Otherworld Essence&r, &e2 Smaragde&r.",
              "&6Partner:&r Goldbarren, Smaragd (Mann) oder Diamant (Frau), Schwarzpulver, Schweinefleisch, Schwert, Glasflasche, &cOpfer:&r ein Huhn.",
              "",
              "Der Glücksspieler tauscht Edelsteine gegen zufällige Edelsteine oder Nuggets, selten Iesnium, und geht nach 30 Minuten. Der Partner kocht Essen und verlängert Tränke, die Bindung ist dauerhaft.",
              "",
              "Der &6Maschinenbediener&r (Kohleblock, Gold, Eisen, Ofen) bedient Maschinen aus dem magischen Speicher, der mit Stufe 3 kommt.",
          ],
          tasks=[task_checkmark("Einen dieser Djinni gerufen")],
          rewards=[reward_item("minecraft:emerald", 4)],
          deps=["djinni_crusher"], icon="minecraft:emerald", optional=True),

    # ---- Strigeor und Ihagan ---------------------------------------------------
    quest("strigeor", 16.5, 16.5, "&5Zeichne Strigeor's Higher Binding",
          subtitle="Das Pentakel für Djinni-Gegenstände.",
          description=[
              "&5Strigeor's Higher Binding&r, 13x13: &e32 violette&r, &e20 limettengrüne&r, &e8 weiße&r und &e8 hellgraue&r Zeichen, &e8 Kerzen&r, &e8 Skelettschädel&r.",
              "Gestartet wird mit dem Djinni-Buch, 150 Sekunden pro Ritual.",
              "",
              "&eWas es macht:&r Soul Gem, Familiar Ring, Gray Paste, Infused Pickaxe, Ender Satchel, Spirit Grindstone. In Stufe 3 dazu: Dimensional Mineshaft, Djinni Miner, Dimensional Matrix, Storage Remote, Wormholes.",
          ],
          tasks=[task_checkmark("Strigeor's Higher Binding gezeichnet")],
          rewards=[reward_item("minecraft:skeleton_skull", 2), reward_xp(5)],
          deps=["djinni_crusher"], icon="minecraft:skeleton_skull"),

    quest("soul_gem", 18.5, 16.5, "&6Binde einen Soul Gem",
          subtitle="Ein Wesen in der Hosentasche.",
          description=[
              "&5Pentakel:&r Strigeor's Higher Binding.",
              "&6Schalen:&r &6Diamant&r, je ein &6Kupfer-, Silber-&r und &6Goldbarren&r, eine &6Fragile Soul Gem&r, &e3 Seelensand&r oder Seelenerde.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch.",
              "",
              "Rechtsklick auf ein Wesen fängt es, noch ein Rechtsklick lässt es frei. Bosse passen nicht hinein. So bringst du Tiere, Dorfbewohner oder Geister ohne Leine ans Ziel.",
          ],
          tasks=[task_item("occultism:soul_gem", 1)],
          rewards=[reward_item("minecraft:soul_sand", 8), reward_xp(5)],
          deps=["strigeor"], icon="occultism:soul_gem"),

    quest("familiar_ring", 20.5, 16.5, "&6Binde einen Familiar Ring",
          subtitle="Ein Vertrauter als Schmuckstück.",
          description=[
              "&5Pentakel:&r Strigeor's Higher Binding.",
              "&6Schalen:&r ein &6Soul Gem&r, &e2 Gold-&r und &e2 Silberbarren&r.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch.",
              "",
              "Fang deinen Vertrauten mit dem Ring und trag ihn als Curio. Er wirkt weiter, ohne neben dir herzulaufen. Wer den Ring bekommt und den Vertrauten freilässt, wird sein neuer Meister.",
          ],
          tasks=[task_item("occultism:familiar_ring", 1)],
          rewards=[reward_item("occultism:silver_ingot", 4), reward_xp(5)],
          deps=["soul_gem"], icon="occultism:familiar_ring"),

    quest("gray_paste", 18.5, 18.3, "&6Misch Gray Paste",
          subtitle="Staub wird wieder Stein.",
          description=[
              "&5Pentakel:&r Strigeor's Higher Binding.",
              "&6Schalen:&r &6Schwarzpulver&r, &6Tonklumpen&r, &6Phantomhaut&r, &6grauer Farbstoff&r.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch.",
              "",
              "Paste plus Staub im Crafting-Feld gibt den Block zurück: Amethyst, Obsidian, Kalzit, Eis, Smaragd, Lapis und mehr. Mit unreiner Kreide wird daraus &7Gray Chalk&r, das dunkle Fundament für die Afrit-Pentakel.",
          ],
          tasks=[task_item("occultism:gray_paste", 2)],
          rewards=[reward_item("minecraft:clay_ball", 16)],
          deps=["strigeor"], icon="occultism:gray_paste"),

    quest("djinni_crystallizer", 20.5, 18.3, "&dRuf einen Djinni Crystallizer",
          subtitle="Mehr Edelsteine aus jedem Erz.",
          description=[
              "&5Pentakel:&r Ophyx' Calling.",
              "&6Schalen:&r &6Gray Paste&r, &6Lapis&r, &6Amethystscherbe&r, &6Smaragd&r.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch.",
              "",
              "Doppelt so schnell wie der Foliot und mehr Edelsteine pro Erz. Er zerlegt außerdem Amethyst- und Quarzblöcke.",
          ],
          tasks=[task_checkmark("Djinni Crystallizer beschworen")],
          rewards=[reward_item("minecraft:amethyst_shard", 8)],
          deps=["gray_paste"], icon="minecraft:amethyst_shard", optional=True),

    quest("ihagan", 14.5, 18.3, "&5Zeichne Ihagan's Enthrallment",
          subtitle="Das Pentakel für Djinni-Besessenheit.",
          description=[
              "&5Ihagan's Enthrallment&r, 13x13: &e12 limettengrüne&r, &e12 gelbe&r, &e8 hellgraue&r und &e4 weiße&r Zeichen, &e8 Kerzen&r, &e4 Skelettschädel&r.",
              "Gestartet wird mit dem Djinni-Buch.",
              "",
              "&eWas es ruft:&r besessene Enderman, Ghast, Lohe, Biene und schwacher Shulker, Reit- und Sondertiere, Dorfbewohner, den Drikwing und zehn Vertraute.",
          ],
          tasks=[task_checkmark("Ihagan's Enthrallment gezeichnet")],
          rewards=[reward_item("occultism:large_candle", 8), reward_xp(5)],
          deps=["ophyx"], icon="occultism:chalk_gold"),

    quest("djinni_possess", 12.5, 19.9, "&5Ruf besessene Nethermonster",
          subtitle="Perlen und Tränen ohne Suche.",
          description=[
              "&5Pentakel:&r Ihagan's Enthrallment, alle mit dem Djinni-Buch.",
              "&6Enderman:&r Knochen, Faden, Endstein, verrottetes Fleisch, &cOpfer:&r Schwein. &6Ghast:&r 2 Seelensand, 2 Magmablöcke, Netherrack, Lavaeimer, Diamant, &cOpfer:&r Kuh.",
              "&6Lohe:&r Feuerkugel, Feuerwerksstern, Fackel, Kerze, Gold- und Kupferbarren, &cOpfer:&r Huhn.",
              "",
              "Der Enderman lässt immer eine &6Enderperle&r fallen, der Ghast immer eine &6Ghast-Träne&r, die Lohe Netherpflanzen und Netherblöcke. Die Biene für Cursed Honey steht im Afrit-Kapitel.",
          ],
          tasks=[task_item("minecraft:ghast_tear", 2)],
          rewards=[reward_item("minecraft:ender_pearl", 4), reward_xp(5)],
          deps=["ihagan"], icon="minecraft:ghast_tear", optional=True),

    quest("djinni_familiars", 14.5, 20.1, "&dRuf einen Djinni-Vertrauten",
          subtitle="Zehn Vertraute für Ihagan's Enthrallment.",
          description=[
              "&5Pentakel:&r Ihagan's Enthrallment. &eFledermaus&r (Nachtsicht): Goldene Karotte, Spinnenauge, Glowstone, Lava, Fackel, Opfer Fledermaus. &eBeholder&r (markiert Feinde): 4 Spinnenaugen, 4 Glowstone, Opfer Spinne.",
              "&eTeufel&r (Feuerresistenz): 2 Magma, 2 Knochen, Lava, Opfer Pferd. &eFee&r (schützt andere Vertraute): 2 Goldäpfel, Ghast-Träne, 3 Schwarzpulver, Milch, Opfer Pferd.",
              "&eChimäre&r (Reittier), &eDrache&r (mehr EP), &eMumie&r (kämpft), &eCthulhu&r (Wasseratmung), &eKopfloser&r (Schaden gegen eine Mobart), &eDrikwing&r (Mehrfachsprung). Zutaten im Dictionary.",
              "",
              "Stirbt ein Vertrauter, bleibt ein Seelensplitter. Damit holst du ihn in Susje's Simple Circle zurück.",
          ],
          tasks=[task_checkmark("Einen Djinni-Vertrauten gerufen")],
          rewards=[reward_item("minecraft:golden_carrot", 4), reward_xp(5)],
          deps=["ihagan"], icon="minecraft:spider_eye", optional=True),

    quest("susje", 16.5, 20.1, "&5Zeichne Susje's Simple Circle",
          subtitle="Gefallene Vertraute zurückholen.",
          description=[
              "&5Susje's Simple Circle&r, 11x11: nur &e16 weiße&r Zeichen um die goldene Schale.",
              "&6Schalen:&r &e4 Otherworld Essence&r. &cStart:&r der &6Seelensplitter&r deines Vertrauten statt eines Buches, 15 Sekunden.",
              "",
              "Der Vertraute kommt mit neuem Körper zurück. Im selben Kreis wird ein Vex mit Redstone-, Glowstone-, Silber- und Goldstaub und Zucker als Start zum Allay.",
          ],
          tasks=[task_checkmark("Susje's Simple Circle gezeichnet")],
          rewards=[reward_item("occultism:datura", 16)],
          deps=["djinni_familiars"], icon="occultism:chalk_white", optional=True),

    # ---- Ziel ------------------------------------------------------------------
    quest("summoner", 23.2, 15.5, "&5&lWerd Beschwörer",
          subtitle="Geister arbeiten, während du schläfst.",
          description=[
              "Halte &e4 gebundene Djinni-Bücher&r und &e2 Limettenkreide&r bereit. Das ist dein Vorrat für den Start in Stufe 3.",
              "",
              "Du kennst jetzt sieben Pentakel: Aviar, Hedyrin, Eziveus, Ophyx, Strigeor, Ihagan und Susje. Crusher, Schmelzer, Träger und Holzfäller arbeiten für dich.",
              "",
              "&eKronwerke:&r Mit &6Stufe 3&r öffnen Afrit und Marid. Das Magieziel will dann &e150 Afrit-Essenzen&r, jede ein gerufener und besiegter Afrit, und jeder Elfenstern zwei. Weiter im Kapitel &5Occultism: Afrit und Marid&r.",
          ],
          tasks=[task_item("occultism:book_of_binding_bound_djinni", 4), task_item("occultism:chalk_lime", 2)],
          rewards=[reward_table("s2_rare"), reward_xp(15)],
          deps=["familiar_ring", "djinni_extras"], icon="occultism:golden_sacrificial_bowl", size=2.5, shape="gear"),

    # ---- Neue Quests -------------------------------------------------------------
    quest("otherworld_essence", 3.5, 1.2, "&dReinige Otherworld Essence",
          subtitle="Die Essenz ohne Nebenwirkungen.",
          description=[
              "Wirf eine &6Demon's Dream Essence&r in Spiritfire. Heraus kommt &6Otherworld Essence&r.",
              "",
              pic("occultism:otherworld_essence"),
              "",
              "Du brauchst sie öfter, als du denkst: &e2&r für den Wandernden Händler der Djinni, &e4&r für jede Wiederbelebung in Susje's Simple Circle, &e3&r für jede Kreidereparatur.",
              "",
              "In Stufe 3 reparieren Afrit mit ihr auch Werkzeuge, Rüstung und Miner. Leg dir einen kleinen Vorrat an.",
          ],
          tasks=[task_item("occultism:otherworld_essence", 4)],
          rewards=[reward_item("occultism:datura", 16), reward_xp(5)],
          deps=["third_eye"], icon="occultism:otherworld_essence", optional=True),

    quest("netherite_dust", 19.2, 6.5, "&dZerkleinere Antiken Schrott",
          subtitle="Mehr Netherit aus jedem Fund.",
          description=[
              "Wirf deinem Crusher &6Antiken Schrott&r hin. Der Foliot macht daraus &e2&r, der Djinni &e3&r &6Netherite Scrap Dust&r.",
              "",
              "Der Staub schmilzt im Ofen oder Hochofen zu je einer &6Netheritplatte&r. Aus einem Fund werden so zwei oder drei Platten statt einer.",
              "",
              "&eTipp:&r Fertige Netheritplatten zu zerkleinern lohnt sich nicht, eine Platte gibt nur einen Staub.",
          ],
          tasks=[task_item("occultism:netherite_scrap_dust", 4)],
          rewards=[reward_item("minecraft:ancient_debris", 1), reward_table("s2_common"), reward_xp(10)],
          deps=["foliot_crusher"], icon="occultism:netherite_scrap_dust", optional=True),

    quest("knowledge_tablet", 11.5, 15.3, "&6Binde eine Knowledge Tablet",
          subtitle="Erfahrung auf Vorrat.",
          description=[
              "Erst die &6Otherworldly Tablet&r: &6Otherstone&r in die Mitte, &e4 Goldbarren&r an die Seiten, &e4 Otherworld Ashes&r in die Ecken.",
              "",
              "&5Pentakel:&r Eziveus' Spectral Compulsion.",
              "&6Schalen:&r die Tafel, &6Research Fragment Dust&r, ein &6Spirit Attuned Gem&r, eine &6Enderperle&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch, 60 Sekunden.",
              "",
              "Rechtsklick speichert all deine Erfahrung, schleichend Rechtsklick gibt sie zurück. Bei sehr großen Mengen geht durch Rundung ein kleiner Rest verloren. So reichst du Erfahrung auch an Mitspieler weiter.",
          ],
          tasks=[task_item("occultism:knowledge_tablet", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 8), reward_xp(5)],
          deps=["research_dust"], icon="occultism:knowledge_tablet", optional=True),

    quest("infused_lenses", 11.5, 17.0, "&6Binde Infused Lenses",
          subtitle="Vorarbeit für die Otherworld Goggles.",
          description=[
              "&eRezept:&r &e8 Glasscheiben&r um einen &6Spirit Attuned Gem&r ergeben die &6Glass Lenses&r.",
              "",
              "&5Pentakel:&r Eziveus' Spectral Compulsion.",
              "&6Schalen:&r die Linsen, &e2 Silberbarren&r, &e1 Goldbarren&r.",
              "&cOpfer:&r keins. Start mit dem Foliot-Buch, 60 Sekunden.",
              "",
              "Die &6Infused Lenses&r stecken in den &6Otherworld Goggles&r aus dem Kapitel &5Occultism: Afrit und Marid&r. Wer sie jetzt schon bindet, hat in Stufe 3 einen Schritt weniger.",
          ],
          tasks=[task_item("occultism:infused_lenses", 1)],
          rewards=[reward_item("occultism:silver_ingot", 2), reward_xp(5)],
          deps=["research_dust"], icon="occultism:infused_lenses", optional=True),

    quest("ender_satchel", 18.5, 20.1, "&6Binde eine Ender Satchel",
          subtitle="Die Endertruhe in der Tasche.",
          description=[
              "&5Pentakel:&r Strigeor's Higher Binding.",
              "&6Schalen:&r eine &6Endertruhe&r, &e2 Leder&r, ein &6Faden&r, ein &6Silber-&r und ein &6Goldbarren&r.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch, 150 Sekunden.",
              "",
              "Rechtsklick öffnet deine Endertruhe, wo immer du bist. Schleichend Rechtsklick bindet die Tasche an dich: Wer sie dann benutzt, öffnet deine Endertruhe. So schickst du Mitspielern Items über jede Entfernung.",
          ],
          tasks=[task_item("occultism:ender_satchel", 1)],
          rewards=[reward_item("minecraft:leather", 8), reward_xp(5)],
          deps=["strigeor"], icon="occultism:ender_satchel"),

    quest("spirit_grindstone", 20.5, 20.1, "&6Binde einen Spirit Grindstone",
          subtitle="Flüche weg, Verzauberungen bleiben.",
          description=[
              "&5Pentakel:&r Strigeor's Higher Binding.",
              "&6Schalen:&r ein &6Schleifstein&r, ein &6Glas&r, ein &bSpirit Attuned Crystal&r, ein &6Prismarinkristall&r.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch, 150 Sekunden.",
              "",
              "Anders als der normale Schleifstein entfernt er &enur Flüche&r und lässt alle anderen Verzauberungen dran. Du bekommst die volle Erfahrung der Flüche zurück.",
              "",
              "Kombinierst du zwei Gegenstände, bleiben die Verzauberungen des oberen. Die Reparatur gibt die Haltbarkeit beider plus &d20 Prozent&r.",
          ],
          tasks=[task_item("occultism:spirit_grindstone", 1)],
          rewards=[reward_item("minecraft:prismarine_crystals", 4), reward_xp(5)],
          deps=["strigeor"], icon="occultism:spirit_grindstone", optional=True),

    quest("repair_chalk", 22.5, 16.5, "&6Reparier deine Kreide",
          subtitle="Ein Djinni füllt sie wieder auf.",
          description=[
              "&5Pentakel:&r Strigeor's Higher Binding.",
              "&6Schalen:&r &e3 Otherworld Essence&r, ein &6Spirit Attuned Gem&r.",
              "&cStart:&r die abgenutzte Kreide selbst statt eines Buches. Nach wenigen Sekunden ist sie wieder voll.",
              "",
              "Lohnt sich vor allem bei Limetten- und violetter Kreide, deren Zutaten aufwendig sind. Weiße Kreide machst du billiger neu.",
          ],
          tasks=[task_checkmark("Eine Kreide repariert")],
          rewards=[reward_item("occultism:datura", 8), reward_xp(5)],
          deps=["strigeor", "otherworld_essence"], icon="occultism:chalk_purple", optional=True),

    quest("special_animal", 12.5, 21.7, "&5Ruf ein seltenes Tier",
          subtitle="Pandas, Schnüffler und Eisengolems auf Bestellung.",
          description=[
              "&5Pentakel:&r Ihagan's Enthrallment.",
              "&6Schalen:&r &e2 Wolle&r, ein &6Pilzblock&r, ein &6Moosblock&r, ein &6Eisenblock&r, ein &6Packeis&r, ein &6Keramik&r, ein &6Bambusblock&r.",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch.",
              "",
              "Heraus kommt zufällig eins davon: Gürteltier, Mooshroom, Panda, Eisbär, Ziege, &6Eisengolem&r oder &6Schnüffler&r. Für eine Eisenfarm oder seltene Samen musst du so nicht durch die halbe Welt reisen.",
              "",
              "Die Reittiere (Pferd, Esel, Lama, Kamel, Schreiter und mehr) rufst du im selben Pentakel mit &e2 Heuballen&r, Apfel, Goldapfel, Karotte, goldener Karotte, Kaktus und Wirrpilz.",
          ],
          tasks=[task_checkmark("Ein seltenes Tier gerufen")],
          rewards=[reward_item("minecraft:iron_block", 1), reward_table("s2_common"), reward_xp(10)],
          deps=["ihagan"], icon="minecraft:moss_block", optional=True),

    quest("villager", 14.5, 21.9, "&5Ruf einen Dorfbewohner",
          subtitle="Ein Dorf ohne Suche.",
          description=[
              "&5Pentakel:&r Ihagan's Enthrallment.",
              "&6Schalen:&r ein &6Bett&r, ein &6Lagerfeuer&r, ein &6Kürbiskuchen&r (andere Pies aus Kochmods gehen auch).",
              "&cOpfer:&r keins. Start mit dem Djinni-Buch.",
              "",
              "Heraus kommt ein Dorfbewohner oder ein Wandernder Händler. So baust du dein Handelszentrum, ohne Dorfbewohner quer durch die Welt zu treiben.",
          ],
          tasks=[task_checkmark("Einen Dorfbewohner gerufen")],
          rewards=[reward_item("minecraft:emerald", 4), reward_xp(5)],
          deps=["ihagan"], icon="minecraft:campfire", optional=True),
]

images = [
    banner("occultism/title", "Occultism", 6.5, -4.4, height=1.8, kind="title", colour="magic"),
    banner("occultism/schleier", "Den Schleier lüften", 7.5, -2.5, height=0.9, colour="magic"),
    banner("occultism/ritual", "Das erste Ritual", 4.5, 3.7, height=0.9, colour="magic"),
    banner("occultism/foliot", "Aviar's Circle: alle Foliot-Berufe", 17.5, 3.4, height=0.9, colour="magic"),
    banner("occultism/hedyrin", "Hedyrin's Lure: Besessenheit", 3.0, 10.4, height=0.9, colour="nature"),
    banner("occultism/kreiden", "Eziveus: Foliot in Gegenständen", 10.0, 10.8, height=0.9, colour="magic"),
    banner("occultism/djinni", "Djinni", 13.5, 11.0, height=0.9, colour="magic"),
    banner("occultism/strigeor", "Strigeor und Ihagan", 17.5, 15.6, height=0.9, colour="magic"),
]

chapter(C, "Occultism", "occultism:dictionary_of_spirits", "magic", quests, shape="circle", order=13, stage=2,
        subtitle=["Stufe 2. Spiritfire, Kreide, Foliot und Djinni."], images=images)
