"""Pipes and routers in stage 2: Pipez (item, fluid, energy and gas pipes, the wrench, the basic
and improved upgrades, extraction and distribution), Modular Routers (router, modules, upgrades,
augments, filters, the sorting setup) and the Ranged Pump. Numbers follow the server configs
(pipez-server.toml, modularrouters-common.toml, rangedpumps-server.toml). The advanced upgrade and
the universal pipe open in stage 3, the ultimate upgrade in stage 4, Tempad in stage 3; they are
only mentioned. No Kronwerke recipe change touches these mods."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "pipes"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Pipez ----------------------------------------------------------------
    quest("item_pipe", 0, 0, "&b&lBau Item-Rohre",
          subtitle="Sechzehn Rohre, und die Truhen reden miteinander.",
          description=[
              "&eRezept:&r oben und unten je drei &6Eisenbarren&r, in der Mitte zwei &6Werfer&r links und rechts von einem &6Redstone&r. Das gibt &616 Item-Rohre&r.",
              "",
              "&6Pipez&r ist das einfachste Rohrsystem im Pack. Rohre verbinden sich von selbst mit Truhen, Maschinen und untereinander. Ein Rohr bewegt Gegenstände nur, wenn eine Seite auf &eZiehen&r steht, wie das geht, zeigt die nächste Quest.",
              "",
              "Ohne Upgrade schiebt ein Rohr &e4 Gegenstände pro Sekunde&r, und zwar immer in die &enächste&r Truhe oder Maschine, die noch Platz hat.",
              "",
              "&eWas in Stufe 2 offen ist:&r alle vier Rohrsorten, der Schraubenschlüssel, die Normale und die Verbesserte Modifikation. Filter und das Universalrohr kommen in Stufe 3.",
          ],
          tasks=[task_item("pipez:item_pipe", 16)],
          rewards=[reward_item("minecraft:iron_ingot", 12), reward_table("s2_common")],
          icon="pipez:item_pipe", size=2.0, shape="hexagon"),

    quest("wrench", 2.6, -1.3, "&7Mach einen Schraubenschlüssel",
          subtitle="Ohne ihn zieht kein Rohr.",
          description=[
              "&eRezept:&r zwei &6Stöcke&r diagonal von links unten, zwei &6Feuersteine&r oben und rechts, wie eine kleine Zange. Ein &6Schraubenschlüssel&r.",
              "",
              "Halt &eSchleichen&r und klick mit dem Schlüssel auf das Rohrende an einer Truhe. Jeder Klick schaltet die Verbindung weiter: &everbunden&r, &eziehend&r (das Ende wird markiert), &egetrennt&r, und wieder von vorn.",
              "",
              "Getrennte Enden sind praktisch, wenn zwei Rohrstränge dicht nebeneinander laufen oder ein Rohr an einer Truhe vorbei soll, ohne hineinzugreifen.",
          ],
          tasks=[task_item("pipez:wrench", 1)],
          rewards=[reward_item("minecraft:flint", 8), reward_xp(3)],
          deps=["item_pipe"], icon="pipez:wrench"),

    quest("extract", 2.6, 1.3, "&bLass das Rohr ziehen",
          subtitle="Eine Seite zieht, alle anderen liefern.",
          description=[
              "Stell das Rohrende an deiner &6Quelltruhe&r mit Schleichen und Schraubenschlüssel auf &eZiehen&r. Alles, was dort liegt, wandert in die Truhen und Maschinen am selben Rohrstrang, die nächste zuerst.",
              "",
              "Ein Rechtsklick mit leerer Hand auf ein ziehendes Ende öffnet sein Fenster. Dort liegt ein Slot für eine &6Modifikation&r, und mit ihr kommen Redstone-Steuerung, Verteilung und später Filter.",
              "",
              "&eTipp:&r Ein Rohrstrang kann mehrere ziehende Enden haben. Zwei Truhen mit Erz, ein Strang, eine Anreicherungskammer am Ende: fertig ist der Zubringer.",
          ],
          tasks=[task_checkmark("Ein Rohr zieht")],
          rewards=[reward_item("pipez:item_pipe", 16)],
          deps=["wrench"], icon="minecraft:hopper"),

    quest("fluid_pipe", 5.2, -1.3, "&9Bau Flüssigkeitsrohre",
          subtitle="Wasser, Lava und alles, was Mekanism ausspuckt.",
          description=[
              "&eRezept:&r wie das Item-Rohr, aber mit zwei &6Eimern&r statt der Werfer. &616 Flüssigkeitsrohre&r.",
              "",
              "Sie bewegen &e50 mB pro Tick&r ohne Upgrade, das ist ein Eimer pro Sekunde. Ziehen und Trennen funktionieren genau wie beim Item-Rohr, nur dass die Quelle ein Tank, ein Kessel oder eine Maschine ist.",
              "",
              "Eine Lavaquelle im Nether, ein Rohr, der Wärmegenerator von Mekanism: Das ist der erste sinnvolle Einsatz.",
          ],
          tasks=[task_item("pipez:fluid_pipe", 16)],
          rewards=[reward_item("minecraft:bucket", 2), reward_xp(3)],
          deps=["extract"], icon="pipez:fluid_pipe"),

    quest("energy_pipe", 5.2, 1.3, "&cBau Stromrohre",
          subtitle="FE für alle Mods.",
          description=[
              "&eRezept:&r wie das Item-Rohr, aber mit zwei &6Redstone-Blöcken&r statt der Werfer. &616 Stromrohre&r.",
              "",
              "Ein Stromrohr trägt &e256 FE pro Tick&r ohne Upgrade und versteht jedes FE-Gerät im Pack: Mekanism, Create Crafts and Additions, Immersive Engineering, Pylonen. Die ziehende Seite kommt an den Generator oder Energie-Würfel.",
              "",
              "Strom verteilt das Rohr &ereihum&r auf alle Verbraucher, nicht nur auf den nächsten.",
          ],
          tasks=[task_item("pipez:energy_pipe", 16)],
          rewards=[reward_item("minecraft:redstone", 16), reward_xp(3)],
          deps=["extract"], icon="pipez:energy_pipe"),

    quest("gas_pipe", 7.8, 1.3, "&aBau Gasrohre",
          subtitle="Für die Chemie von Mekanism.",
          description=[
              "&eRezept:&r wie das Item-Rohr, aber mit zwei &6Infundierten Legierungen&r aus Mekanism statt der Werfer. &616 Gasrohre&r.",
              "",
              "Gasrohre bewegen &e200 mB Gas pro Tick&r: Sauerstoff, Wasserstoff, Chlor und alles, was Mekanism in Tanks füllt. In Stufe 2 brauchst du sie kaum, ab Stufe 3 trägt der Sauerstoff die Erzverdreifachung.",
              "",
              pic("mekanism:alloy_infused"),
          ],
          tasks=[task_item("pipez:gas_pipe", 16)],
          rewards=[reward_item("mekanism:alloy_infused", 4)],
          deps=["energy_pipe"], icon="pipez:gas_pipe", optional=True),

    quest("basic_upgrade", 7.8, -1.3, "&fBau die Normale Modifikation",
          subtitle="Doppelt so viel, und Redstone hört zu.",
          description=[
              "&eRezept:&r vier &6Eisenbarren&r in die Ecken, vier &6Eisenklumpen&r an die Seiten, ein &6Redstone&r in die Mitte. Steck sie in den Slot eines ziehenden Rohrendes.",
              "",
              "Mit ihr zieht das Ende &e8 Gegenstände alle 15 Ticks&r, &e100 mB&r Flüssigkeit, &e1 024 FE&r oder &e400 mB&r Gas pro Tick.",
              "",
              "Dazu kommt der &eRedstone-Modus&r: ignorieren, aus bei Signal, an bei Signal oder immer aus. Ein Hebel am Rohr schaltet damit eine ganze Straße ab.",
              "",
              "&eTipp:&r Leg eine eingestellte Modifikation mit einer neuen zusammen in die Werkbank, dann übernimmt die neue alle Einstellungen. Eine Modifikation allein in der Werkbank wird zurückgesetzt.",
          ],
          tasks=[task_item("pipez:basic_upgrade", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(5)],
          deps=["fluid_pipe"], icon="pipez:basic_upgrade"),

    quest("improved_upgrade", 10.4, -1.3, "&6Bau die Verbesserte Modifikation",
          subtitle="Schneller, und du bestimmst, wohin.",
          description=[
              "&eRezept auf Kronwerke:&r vier &6Messingbarren&r in die Ecken, vier &6Redstone&r an die Seiten, die &6Normale Modifikation&r in die Mitte.",
              "",
              "Jetzt zieht das Ende &e16 Gegenstände alle 10 Ticks&r, &e500 mB&r Flüssigkeit, &e8 192 FE&r oder &e2 000 mB&r Gas pro Tick.",
              "",
              "Neu ist die &eVerteilung&r: &6Nächste zuerst&r, &6Weiteste zuerst&r, &6Rundlauf&r oder &6Zufällig&r. Für eine Reihe Fabriken nimm Rundlauf, dann bekommt jede gleich viel. Für Überlauf in eine Mülltonne nimm Nächste zuerst und stell die Tonne ans Ende.",
          ],
          tasks=[task_item("pipez:improved_upgrade", 1)],
          rewards=[reward_item("create:brass_ingot", 6), reward_table("s2_common")],
          deps=["basic_upgrade"], icon="pipez:improved_upgrade"),

    quest("outlook", 13, -1.3, "&dLies, was in Stufe 3 kommt",
          subtitle="Filter, Ziele und das Universalrohr.",
          description=[
              "Die &6Fortgeschrittene Modifikation&r (Diamanten und Redstone-Blöcke um die Verbesserte) öffnet mit &eStufe 3&r. Erst sie bringt &eFilter&r: Gegenstände, Tags mit # davor, Flüssigkeiten, als Whitelist oder Blacklist.",
              "",
              "Zu den Filtern gehört das &6Filter-Ziel-Gerät&r, das du schon jetzt bauen kannst: Klick damit auf eine Truhe, und ein Filter schickt seine Gegenstände nur noch genau dorthin. Damit wird aus einem Rohrstrang eine Sortieranlage.",
              "",
              "Das &6Universalrohr&r (Item-, Strom- und Flüssigkeitsrohr mit Eisen um einen Redstone-Block, sechs Stück) trägt alle vier Sorten in einem Block. Stufe 4 bringt die Ultimative Modifikation aus Netherit.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["improved_upgrade"], icon="pipez:filter_destination_tool", optional=True),

    # ---- Modular Routers --------------------------------------------------------
    quest("blank_module", 0, 6, "&e&lMach leere Module",
          subtitle="Papier, Gold und Redstone, sechs auf einmal.",
          description=[
              "&eRezept:&r ein &6Redstone&r oben in der Mitte, drei &6Papier&r in der mittleren Reihe, drei &6Goldklumpen&r unten. Das gibt &66 Leere Module&r.",
              "",
              "&6Modular Routers&r ist das Gegenstück zu den Rohren: ein einziger Block, der durch Module lernt, was er tun soll. Ziehen, senden, aufsaugen, platzieren, abbauen, vernichten. Fast jedes Modul ist ein leeres Modul plus ein Gegenstand aus Vanilla.",
              "",
              "Mach gleich zwölf, du brauchst sie für den Router selbst und für jedes Modul.",
          ],
          tasks=[task_item("modularrouters:blank_module", 12)],
          rewards=[reward_item("minecraft:paper", 16), reward_item("minecraft:gold_ingot", 4), reward_table("s2_common")],
          icon="modularrouters:blank_module", size=2.0, shape="hexagon"),

    quest("router", 2.6, 6, "&e&lBau einen Router",
          subtitle="Ein Block, neun Module, ein Puffer.",
          description=[
              "&eRezept auf Kronwerke:&r vier &6Andesitlegierungen&r in die Ecken, vier &6Eisengitter&r an die Seiten, ein &6Leeres Modul&r in die Mitte. Das gibt &64 Router&r.",
              "",
              "Ein Router hat einen &ePuffer&r von einem Stapel, &eneun Modulplätze&r und &efünf Upgradeplätze&r. Jede Sekunde arbeitet er alle Module von links nach rechts ab. Trichter und Rohre dürfen den Puffer befüllen und leeren.",
              "",
              "Oben rechts stellst du die &eRedstone-Steuerung&r ein (immer, nur ohne Signal, nur mit Signal, nie, einmal pro Impuls) und den &eÖko-Modus&r: nach 5 Sekunden ohne Arbeit läuft der Router nur noch alle 5 Sekunden, bis wieder etwas kommt.",
              "",
              "Module stellst du im Router ein, ohne sie herauszunehmen: &eMittelklick&r auf das Modul.",
          ],
          tasks=[task_item("modularrouters:modular_router", 1)],
          rewards=[reward_item("minecraft:iron_bars", 8), reward_xp(5)],
          deps=["blank_module"], icon="modularrouters:modular_router", size=1.5, shape="gear"),

    quest("puller", 5.2, 4.5, "&eZieh aus einer Truhe",
          subtitle="Das Puller-Modul Mk1.",
          description=[
              "&eRezept:&r ein &6Leeres Modul&r und ein &6Klebriger Kolben&r, formlos. Ein &6Puller-Modul Mk1&r.",
              "",
              "Es zieht pro Durchlauf einen Gegenstand aus der Truhe, die direkt neben dem Router liegt, in den Puffer. Die &eRichtung&r stellst du im Modul ein, sie zählt relativ zur Vorderseite des Routers.",
              "",
              "Jedes Modul hat &eneun Filterplätze&r für Geisterkopien von Gegenständen, dazu Knöpfe für Whitelist oder Blacklist, Haltbarkeit, NBT und Tags. Leer heißt: alles.",
          ],
          tasks=[task_item("modularrouters:puller_module_1", 1)],
          rewards=[reward_item("minecraft:slime_ball", 4), reward_xp(3)],
          deps=["router"], icon="modularrouters:puller_module_1"),

    quest("sender", 5.2, 7.5, "&eSchick es weiter",
          subtitle="Das Sender-Modul Mk1.",
          description=[
              "&eRezept:&r ein &6Leeres Modul&r und ein &6Kolben&r, formlos (oder Bogen und Pfeil). Ein &6Sender-Modul Mk1&r.",
              "",
              "Es schickt einen Gegenstand aus dem Puffer in eine Truhe bis zu &e8 Blöcke&r weit in Modulrichtung. Die Truhe muss genau auf der Achse liegen und der Weg frei sein, Glas, Zäune und Gitter stören nicht.",
              "",
              "Puller auf der einen Seite, Sender auf der anderen: Das ist ein Trichter, der acht Blöcke weit springt.",
          ],
          tasks=[task_item("modularrouters:sender_module_1", 1)],
          rewards=[reward_item("minecraft:piston", 2), reward_xp(3)],
          deps=["router"], icon="modularrouters:sender_module_1"),

    quest("mk2", 7.8, 6, "&6Sende durch Wände",
          subtitle="Mk2 mit Enderperle: Ziel anklicken, fertig.",
          description=[
              "Ein &6Sender Mk1&r und eine &6Enderperle&r ergeben ein &6Sender-Modul Mk2&r, vier Mk1 und eine Perle gleich vier. Genauso wird aus dem Puller Mk1 der &6Puller Mk2&r.",
              "",
              "Mk2 braucht keine Sichtlinie und keine Achse mehr. Halt das Modul in der Hand, &eschleichen und rechtsklick&r auf die Zieltruhe, und der Router sendet oder zieht bis zu &e24 Blöcke&r (Sender) oder &e12 Blöcke&r (Puller) weit, durch jede Wand.",
              "",
              "Das Ziel wird markiert, solange du das Modul hältst. Mit &6Reichweiten-Augments&r kommst du auf 48 und 24 Blöcke.",
              "",
              "&cAusblick:&r Das &6Sender-Modul Mk3&r sendet in jede Dimension, braucht aber Endstein. Das gibt es erst mit dem End in Stufe 4.",
          ],
          tasks=[task_item("modularrouters:sender_module_2", 1), task_item("modularrouters:puller_module_2", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 4), reward_table("s2_common")],
          deps=["puller", "sender"], icon="modularrouters:sender_module_2"),

    quest("vacuum", 10.4, 4.5, "&aSaug den Boden leer",
          subtitle="Das Vakuum-Modul holt, was herumliegt.",
          description=[
              "&eRezept:&r ein &6Leeres Modul&r, ein &6Trichter&r und ein &6Enderauge&r, formlos. Ein &6Vakuum-Modul&r.",
              "",
              "Es sammelt alle Gegenstände in einem Würfel von &e13 Blöcken&r Kantenlänge um den Router in den Puffer. Mit Reichweiten-Augments bis 25 Blöcke, mit Richtung nur auf einer Seite.",
              "",
              "Unter einer Mobfarm, hinter einem Create-Bohrer, neben dem Bienenhaus: überall, wo etwas fällt, ersetzt ein Router mit Vakuum und Sender einen Haufen Trichter.",
              "",
              "&eTipp:&r Das &6XP-Vakuum-Augment&r (Augment-Kern und Seelensand) saugt stattdessen Erfahrung ein und macht daraus &6Erfahrungsfläschchen&r, eines je 7 XP.",
          ],
          tasks=[task_item("modularrouters:vacuum_module", 1)],
          rewards=[reward_item("minecraft:hopper", 2), reward_xp(5)],
          deps=["mk2"], icon="modularrouters:vacuum_module"),

    quest("void", 10.4, 7.5, "&cVernichte den Überschuss",
          subtitle="Das Void-Modul, mit Vorsicht.",
          description=[
              "&eRezept:&r ein &6Leeres Modul&r und ein &6Lavaeimer&r, formlos. Ein &6Void-Modul&r.",
              "",
              "Es löscht, was im Puffer liegt, unwiderruflich. Trag &eimmer&r eine Whitelist ein (Bruchstein, Kies, Erde), sonst ist irgendwann der Diamant weg.",
              "",
              "&eTipp:&r Der Knopf &eT&r unter den Filterplätzen heißt &6Termination&r. Ist er an, hört der Router nach diesem Modul auf, wenn es etwas getan hat. Void mit Bruchstein-Whitelist und T zuerst, dann der Sender: So geht nur Bruchstein weg und der Rest weiter.",
          ],
          tasks=[task_item("modularrouters:void_module", 1)],
          rewards=[reward_item("minecraft:lava_bucket", 1), reward_xp(3)],
          deps=["mk2"], icon="modularrouters:void_module"),

    quest("breaker", 13, 4.5, "&7Lass den Router graben und bauen",
          subtitle="Breaker, Placer und Activator.",
          description=[
              "&6Breaker-Modul:&r ein &6Leeres Modul&r und eine &6Spitzhacke&r, formlos. &6Placer-Modul:&r Leeres Modul, &6Werfer&r und &6Erde&r.",
              "",
              "Der Breaker baut den Block vor dem Router ab und legt ihn in den Puffer. Die Spitzhacke bestimmt, was er schafft: mit Eisen kein Obsidian, mit &eBehutsamkeit&r oder &eGlück&r darauf übernimmt er die Verzauberung. Der Placer setzt Blöcke aus dem Puffer, auch Saatgut auf Ackerland.",
              "",
              "Das &6Activator-Modul&r (Werfer, Hebel, Quarz, Redstone um ein Modul) klickt wie ein Spieler: rechts auf Blöcke, rechts auf Tiere (melken, scheren), oder es greift an, dann kostet jeder Schlag 150 FE aus einem Energie-Upgrade.",
              "",
              "Breaker vor einem Bruchsteingenerator, Placer in einer Baumfarm: Der Router ersetzt den Spieler, der daneben steht.",
          ],
          tasks=[task_item("modularrouters:breaker_module", 1), task_item("modularrouters:placer_module", 1)],
          rewards=[reward_item("minecraft:iron_pickaxe", 1), reward_table("s2_common")],
          deps=["vacuum"], icon="modularrouters:breaker_module"),

    quest("fluid_module", 13, 7.5, "&9Pump mit dem Router",
          subtitle="Flüssigkeiten über einen Eimer im Puffer.",
          description=[
              "&eRezept:&r ein &6Kessel&r oben, darunter &6Glas&r, &6Leeres Modul&r, &6Glas&r. Ein &6Flüssigkeits-Modul Mk1&r.",
              "",
              "Ein Router hat keinen Tank. Leg einen &6Eimer&r oder einen Tank-Gegenstand in den Puffer, dann füllt oder leert das Modul ihn aus dem Block in Modulrichtung, auch aus Wasser oder Lava in der Welt. &e1 Eimer pro Sekunde&r, egal wie viele Geschwindigkeits-Upgrades.",
              "",
              "Mehr Durchsatz geben nur &6Flüssigkeits-Upgrades&r (Eimer über Glas, Leeres Upgrade, Glas, drei Stück): je &e10 mB/t&r mehr, bis 400 mB/t.",
              "",
              "&cAchtung:&r Steht die Richtung falsch, kippt der Router Lava über dich. Erst mit Wasser testen.",
          ],
          tasks=[task_item("modularrouters:fluid_module", 1)],
          rewards=[reward_item("minecraft:bucket", 2), reward_xp(3)],
          deps=["void"], icon="modularrouters:fluid_module", optional=True),

    quest("upgrades", 2.6, 10, "&6Beschleunige den Router",
          subtitle="Leere Upgrades, Geschwindigkeit und Stapel.",
          description=[
              "&eLeeres Upgrade:&r vier &6Papier&r links, ein &6Lapislazuli&r in der Mitte, drei &6Goldklumpen&r rechts, gibt vier. &eGeschwindigkeits-Upgrade:&r Redstone, Gold, Redstone oben, Klumpen, Leeres Upgrade, Klumpen in der Mitte, Schwarzpulver, &6Lohenrute&r, Schwarzpulver unten, gibt drei.",
              "",
              "Jedes Geschwindigkeits-Upgrade nimmt &e2 Ticks&r vom Takt von 20, bis zu einem Takt von 2 Ticks mit neun Stück. Das &6Stapel-Upgrade&r (Leeres Upgrade, Steinziegel, Ziegel) verdoppelt die Gegenstände pro Durchlauf, sechs Stück machen aus 1 ganze 64.",
              "",
              "Nimm Stapel-Upgrades, wo es geht, sie schonen den Server. Fünf Upgradeplätze, mehrere gleiche passen in einen Platz.",
              "",
              "Weitere Upgrades: &6Energie&r (50 000 FE Puffer und 1 000 FE pro Takt je Stück), &6Sicherheit&r (nur du öffnest ihn, der Router arbeitet in Claims als du), &6Tarnung&r, &6Dämpfer&r gegen Geräusche und Partikel, &6Sync&r für Routergruppen.",
          ],
          tasks=[task_item("modularrouters:speed_upgrade", 1), task_item("modularrouters:stack_upgrade", 1)],
          rewards=[reward_item("modularrouters:blank_upgrade", 4), reward_xp(5)],
          deps=["router"], icon="modularrouters:speed_upgrade"),

    quest("augments", 5.2, 10, "&6Steck Augments ins Modul",
          subtitle="Reichweite, Regulator, Redstone.",
          description=[
              "&eAugment-Kern:&r ein &6Leeres Modul&r und ein &6Leeres Upgrade&r, formlos, gibt vier. &eReichweite hoch:&r ein Quarz oben, Quarz, Kern, Quarz in der Mitte, ein Stock unten, gibt vier.",
              "",
              "Augments sind Upgrades für ein einzelnes Modul, vier Plätze pro Modul. &6Reichweite hoch&r oder &6runter&r je ein Block, stapelbar. Der &6Regulator&r (Komparatoren und Quarz um einen Kern) sendet nur, bis eine Zahl erreicht ist, oder zieht nur, solange mehr da ist: so hält ein Router genau 64 Kohle in einer Maschine.",
              "",
              "Das &6Redstone-Augment&r (Redstone-Fackeln) gibt dem Modul eigene Redstone-Regeln, das &6Stapel-Augment&r (Kern und Stapel-Upgrade) verdoppelt nur dieses Modul.",
          ],
          tasks=[task_item("modularrouters:augment_core", 4), task_item("modularrouters:range_up_augment", 1)],
          rewards=[reward_item("minecraft:quartz", 8), reward_xp(5)],
          deps=["upgrades"], icon="modularrouters:augment_core"),

    quest("filters", 7.8, 10, "&bFiltere klug",
          subtitle="Der Massenfilter merkt sich eine ganze Truhe.",
          description=[
              "&eRezept:&r vier &6Eisenbarren&r in die Ecken, &6Glas&r oben und unten, zwei &6Leere Module&r links und rechts, ein &6Diamant&r in der Mitte. Ein &6Massen-Gegenstandsfilter&r.",
              "",
              "Er passt in einen Filterplatz und kennt bis zu &e54 Gegenstände&r. Schleichen und Rechtsklick auf eine Truhe kopiert ihren Inhalt in den Filter. Steckt er in einem Sender Mk2 mit Ziel, erscheinen im Fenster &e+&r (Zielinhalt dazuladen) und &e=&r (Zielinhalt übernehmen).",
              "",
              "Aus dem Massenfilter entstehen weitere: &6Mod-Filter&r (Verstärker und Redstone-Fackel, alles eines Mods), &6Tag-Filter&r (Papier und schwarzer Farbstoff), &6Regex-Filter&r (Komparator, Muster wie _ore), &6Prüf-Filter&r (Spinnenaugen und Papier, filtert nach Haltbarkeit, Füllstand oder Verzauberung).",
          ],
          tasks=[task_item("modularrouters:bulk_item_filter", 1)],
          rewards=[reward_item("minecraft:diamond", 1), reward_table("s2_uncommon")],
          deps=["augments"], icon="modularrouters:bulk_item_filter"),

    quest("distributor", 10.4, 10, "&6Verteile auf acht Ziele",
          subtitle="Das Verteiler-Modul.",
          description=[
              "&eRezept:&r ein &6Sender Mk2&r oben in der Mitte, darunter &6Sender Mk2&r, &6Leeres Modul&r, &6Sender Mk2&r. Ein &6Verteiler-Modul&r.",
              "",
              "Es ist ein Sender Mk2 mit bis zu &eacht Zielen&r: Schleichen und Rechtsklick auf jede Truhe, noch einmal zum Entfernen. Verteilt wird &eRundlauf&r, &eZufällig&r, &eNächste&r oder &eWeiteste&r zuerst.",
              "",
              "Ein Router, ein Puller aus der Erzkiste, ein Verteiler auf drei Anreicherungsfabriken im Rundlauf: Keine Fabrik steht still, keine läuft über.",
              "",
              "Das &6Energie-Verteiler-Modul&r (Energie-Ausgangs-Modul und Verteiler) macht dasselbe mit FE aus einem Energie-Upgrade, drahtlos auf acht Maschinen.",
          ],
          tasks=[task_item("modularrouters:distributor_module", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 4), reward_xp(5)],
          deps=["filters", "mk2"], icon="modularrouters:distributor_module"),

    quest("sorting", 13.5, 10.5, "&6&lBau eine Sortieranlage",
          subtitle="Eine Kiste rein, zwanzig Kisten richtig.",
          description=[
              "Ein Router mit einem &6Puller Mk1&r aus der Eingangskiste. Daneben je Sorte ein &6Sender Mk2&r mit einem &6Massenfilter&r, der per &e=&r den Inhalt seiner Zielkiste gelernt hat. Als letztes Modul ein Sender Mk2 ohne Filter in die Restekiste.",
              "",
              "Der Router arbeitet die Module von links nach rechts ab: Was in eine Zielkiste passt, geht dorthin, der Rest ganz rechts hinaus. Ein paar &6Stapel-Upgrades&r, und ein Stapel pro Sekunde ist sortiert. Der Filter merkt sich die Sorte auch, wenn die Kiste zwischendurch leer ist.",
              "",
              "&eKronwerke:&r Stell die Restekiste neben den Obelisken oder leite Messing und Manaperlen in deinen Zubringer. Was dort hineinfällt, zählt für dich zum Ziel von Stufe 2.",
          ],
          tasks=[task_item("modularrouters:modular_router", 2), task_item("modularrouters:sender_module_2", 4),
                 task_item("modularrouters:bulk_item_filter", 4)],
          rewards=[reward_table("s2_rare"), reward_item("modularrouters:stack_upgrade", 2), reward_xp(20)],
          deps=["distributor"], icon="modularrouters:bulk_item_filter", size=2.5, shape="gear"),

    # ---- Modular Routers: neue Quests ---------------------------------------------
    quest("activator", 15.6, 4.5, "&7Lass den Router klicken",
          subtitle="Das Activator-Modul, ein falscher Spieler.",
          description=[
              "&eRezept:&r oben Redstone, &6Hebel&r, Redstone, in der Mitte &6Werfer&r, &6Leeres Modul&r, Werfer, unten Redstone, &6Quarz&r, Redstone.",
              "",
              "Es benutzt das Item im Puffer wie ein Spieler. Drei Modi: &eRechtsklick auf Blöcke&r (Türen, Hebel, Saatgut), &eRechtsklick auf Tiere&r (Kühe melken, Schafe scheren) und &eAngriff&r. Nur der Angriff kostet Strom, &d150 FE&r pro Schlag aus einem Energie-Upgrade.",
              "",
              "Es reicht etwa &e4 Blöcke&r weit, wie ein Spieler. Im Modul stellst du ein, ob es geradeaus, nach oben oder nach unten schaut. Viele Geschwindigkeits-Upgrades helfen beim Angriff nicht, die Abklingzeit der Waffe gilt trotzdem.",
          ],
          tasks=[task_item("modularrouters:activator_module", 1)],
          rewards=[reward_item("minecraft:quartz", 8), reward_xp(4)],
          deps=["breaker"], icon="modularrouters:activator_module"),

    quest("extruder", 15.6, 6, "&7Bau eine Zugbrücke",
          subtitle="Das Extruder-Modul.",
          description=[
              "&eRezept:&r ein &6Leeres Modul&r, ein &6Breaker-Modul&r und ein &6Placer-Modul&r, formlos. Die Spitzhacke des Breakers geht auf den Extruder über, für Obsidian also mit Diamant bauen.",
              "",
              "Mit Redstone-Signal schiebt das &6Extruder-Modul Mk1&r eine Reihe Blöcke aus dem Puffer in Modulrichtung heraus, ohne Signal zieht es sie zurück. Bis &e16 Blöcke&r weit, mit Reichweiten-Augments bis 32. Brücken, Tore und Geheimtüren.",
              "",
              "Das &6Extruder-Modul Mk2&r (Leeres Modul und Truhe) setzt Blöcke aus einer Vorlage im Modul statt aus dem Puffer. Diese Blöcke sind nur Kulisse und lassen beim Abbauen nichts fallen. Es reicht 32 Blöcke, mit Augments 64. Mehrere Router für ein breites Tor hält das &6Sync-Upgrade&r im Gleichtakt.",
          ],
          tasks=[task_item("modularrouters:extruder_module_1", 1)],
          rewards=[reward_item("minecraft:stone_bricks", 32), reward_xp(4)],
          deps=["breaker"], icon="modularrouters:extruder_module_1", optional=True),

    quest("flinger", 15.6, 7.5, "&eWirf Gegenstände durch die Luft",
          subtitle="Dropper- und Flinger-Modul.",
          description=[
              "&6Dropper-Modul:&r ein Leeres Modul und ein &6Spender&r, formlos. Es lässt Gegenstände aus dem Puffer vor dem Router fallen. Ein &6Schwarzpulver&r dazu macht daraus das &6Flinger-Modul&r.",
              "",
              "Der Flinger wirft die Gegenstände mit einstellbarer Geschwindigkeit, Neigung und Richtung. Mit Tempo 1,0 und geradeaus fliegen sie etwa &e7 Blöcke&r über den Boden.",
              "",
              "So landen Saatgut, Futter oder Fackeln dort, wo kein Rohr hinkommt, etwa über eine Mauer in ein Gehege.",
          ],
          tasks=[task_item("modularrouters:flinger_module", 1)],
          rewards=[reward_item("minecraft:gunpowder", 8), reward_xp(3)],
          deps=["sender"], icon="modularrouters:flinger_module", optional=True),

    quest("xp_vacuum", 10.4, 3, "&aSaug Erfahrung ein",
          subtitle="Das XP-Vakuum-Augment.",
          description=[
              "Ein &6Augment-Kern&r und ein &6Seelensand&r, formlos, ergeben das &6XP-Vakuum-Augment&r. Es passt nur in ein Vakuum-Modul.",
              "",
              "Dann saugt das Modul &eErfahrungskugeln&r statt Gegenständen ein und füllt sie in &6Erfahrungsfläschchen&r, eines je &e7 XP&r. Liegt ein passender Tank im Puffer oder steht einer neben dem Router, kann es die Erfahrung auch als Flüssigkeit abfüllen.",
              "",
              "Unter einer Mobfarm sammelt ein Router so Beute und Erfahrung in einem Rutsch.",
          ],
          tasks=[task_item("modularrouters:xp_vacuum_augment", 1)],
          rewards=[reward_item("minecraft:experience_bottle", 8), reward_xp(5)],
          deps=["vacuum"], icon="modularrouters:xp_vacuum_augment", optional=True),

    quest("detector", 0, 8.5, "&cMeld per Redstone, was im Puffer liegt",
          subtitle="Das Detektor-Modul.",
          description=[
              "Ein &6Leeres Modul&r und ein &6Komparator&r, formlos, ergeben das &6Detektor-Modul&r. Es bewegt nichts.",
              "",
              "Passt der Inhalt des Puffers zu seinem Filter, gibt der Router in Modulrichtung ein Redstone-Signal aus. Stärke (Standard 15) und Art (schwach oder stark) stellst du im Modul ein.",
              "",
              "So schaltet ein Router eine Lampe oder Kupplung, sobald zum Beispiel Diamanten durchkommen.",
          ],
          tasks=[task_item("modularrouters:detector_module", 1)],
          rewards=[reward_item("minecraft:comparator", 2), reward_xp(3)],
          deps=["router"], icon="modularrouters:detector_module", optional=True),

    quest("security", 0, 10, "&6Sichere deinen Router",
          subtitle="Das Sicherheits-Upgrade, wichtig auf dem Server.",
          description=[
              "&eRezept:&r ein &6Quarz&r oben, &6Goldklumpen&r, &6Leeres Upgrade&r, Goldklumpen in der Mitte, ein &6Redstone&r unten.",
              "",
              "Einen Router mit diesem Upgrade öffnen nur du und die Spieler, die du einträgst: Rechtsklick mit dem Upgrade auf einen Mitspieler fügt ihn hinzu, Schleichen und Rechtsklick entfernt ihn, bis zu sechs pro Upgrade.",
              "",
              "&eWichtig für Claims:&r Breaker, Placer und Activator arbeiten sonst als falscher Spieler namens &e[Modular Routers]&r. Mit dem Upgrade arbeiten sie als du und dürfen in deinem Claim alles, was du darfst. Ein Activator im Angriffsmodus verschont eingetragene Spieler.",
              "",
              "Das &6Tarnungs-Upgrade&r (Leeres Upgrade, roter, grüner und blauer Farbstoff) lässt den Router wie einen anderen Block aussehen: Schleichen und Rechtsklick auf den Block speichert ihn.",
          ],
          tasks=[task_item("modularrouters:security_upgrade", 1)],
          rewards=[reward_item("minecraft:gold_nugget", 16), reward_xp(4)],
          deps=["upgrades"], icon="modularrouters:security_upgrade"),

    quest("energy", 2.6, 11.5, "&cMach den Router zum Akku",
          subtitle="Energie-Upgrade und Energie-Ausgangs-Modul.",
          description=[
              "&6Energie-Upgrade:&r oben Quarz, &6Redstoneblock&r, Quarz, in der Mitte ein &6Leeres Upgrade&r, unten Quarz, &6Goldbarren&r, Quarz. Jedes gibt dem Router &d50 000 FE&r Speicher und &d1 000 FE&r Durchsatz pro Router-Takt.",
              "",
              "Das &6Energie-Ausgangs-Modul&r (Redstoneblock über einem Leeren Modul zwischen zwei Goldbarren, Quarz darunter) schiebt den Strom in den Block daneben. Liegt ein aufladbares Item im Puffer, lädt der Router es auf oder leert es.",
              "",
              "&cAchtung:&r Ein Router-Takt ist ohne Geschwindigkeits-Upgrade eine ganze Sekunde, also 20 Ticks. Die Angabe pro Takt ist kein FE pro Tick.",
          ],
          tasks=[task_item("modularrouters:energy_upgrade", 1), task_item("modularrouters:energy_output_module", 1)],
          rewards=[reward_item("minecraft:redstone_block", 2), reward_xp(4)],
          deps=["upgrades"], icon="modularrouters:energy_upgrade", optional=True),

    quest("regulator", 5.2, 11.5, "&6Halt einen festen Vorrat",
          subtitle="Das Regulator-Augment.",
          description=[
              "Zwei &6Komparatoren&r links und rechts von einem &6Augment-Kern&r, je ein &6Quarz&r darüber und darunter, ergeben das &6Regulator-Augment&r. Im Modul erscheint dann ein Zahlenfeld.",
              "",
              "Ein Sender liefert nur, solange im Ziel &eweniger&r als diese Zahl liegt. Ein Puller zieht nur, solange im Ziel &emehr&r liegt. Breaker und Vakuum arbeiten, bis der Puffer die Zahl erreicht. Beim Flüssigkeits-Modul geht es um Prozent oder mB im Tank.",
              "",
              "So stehen in jedem Ofen genau 16 Kohle und kein Stück mehr.",
          ],
          tasks=[task_item("modularrouters:regulator_augment", 1)],
          rewards=[reward_item("minecraft:comparator", 2), reward_xp(4)],
          deps=["augments"], icon="modularrouters:regulator_augment"),

    # ---- Ranged Pumps und Tempad -------------------------------------------------
    quest("pump", 0, 14.5, "&9Bau die Pumpe",
          subtitle="Ein See verschwindet, Block für Block.",
          description=[
              "&eRezept auf Kronwerke:&r vier &6Obsidian&r in die Ecken, zwei &6Eisenspitzhacken&r oben und unten, links ein &6Lavaeimer&r, rechts ein &6Wassereimer&r, in der Mitte eine &6Mechanische Pumpe&r von Create. Eine &6Pumpe&r von Ranged Pumps.",
              "",
              "Stell sie über das Wasser oder die Lava und gib ihr Strom. Sie arbeitet sich von ihrem Standort aus Ring für Ring nach außen, bis zur Reichweite &e64&r, und saugt alles unter sich leer. Jeder Block kostet &e100 FE&r und dauert 8 Ticks, der Puffer fasst 32 000 FE.",
              "",
              "Der eigene Tank fasst &e32 Eimer&r. Zieh ihn mit einem &6Flüssigkeitsrohr&r leer, sonst steht die Pumpe. Ein Redstone-Signal hält sie an. Was sie wegpumpt, wird zu Stein, damit nichts nachfließt.",
              "",
              "&eKronwerke:&r Ein Lavasee im Nether, eine Pumpe, ein Rohr zu drei Wärmegeneratoren: Strom für die ganze Messingstufe.",
          ],
          tasks=[task_item("rangedpumps:pump", 1)],
          rewards=[reward_item("pipez:fluid_pipe", 16), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["fluid_pipe"], icon="rangedpumps:pump", size=1.5, shape="hexagon"),

    quest("tempad", 3, 14.5, "&dLies, was Tempad kann",
          subtitle="Türen durch die Zeit, ab Stufe 3.",
          description=[
              "&6Tempad&r öffnet mit &eStufe 3&r. Das Gerät speichert Orte und öffnet eine &6Zeittür&r dorthin, auch in andere Dimensionen. Jede Tür kostet &e1 000 Chronon&r für 10 Sekunden, jede weitere Sekunde 10.",
              "",
              "Chronon macht das &6Chronometer&r (ein Chronon alle 36 Ticks) oder das &6Metronom&r als Block. Das Tempad selbst fasst 6 000 Chronon, also sechs Türen.",
              "",
              "Bis dahin reichen Wegsteine, und wer früh das Material sammelt, baut am ersten Abend von Stufe 3 sein Gerät.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(5)],
          deps=["pump"], icon="minecraft:clock", optional=True),
]

images = [
    banner("pipes/title", "Rohre und Router", 7, -5, height=1.75, kind="title", colour="water"),
    banner("pipes/pipez", "Pipez", 6.5, -2.9, height=0.9, colour="water"),
    banner("pipes/routers", "Modular Routers", 6.8, 2.9, height=0.9, colour="brass"),
    banner("pipes/pumps", "Pumpen und Zeit", 1.5, 12.8, height=0.9, colour="stone"),
]

chapter(C, "Rohre und Router", "pipez:item_pipe", "tech", quests, shape="square", order=54, stage=2,
        subtitle=["Stufe 2: Pipez, Modular Routers und die Pumpe. Alles, was Dinge von A nach B bringt."],
        images=images)
