"""PneumaticCraft in stage 2: compressed iron (explosion or pressure chamber), the air
compressor and pressure, tubes and the safety valve, the pressure chamber multiblock and its
first recipes, the charging station, manometer and wrench, oil (seismic sensor, gas lift,
refinery, the four fuels), heat (vortex tube, heat sink, heat frame, static heat sources),
plastic and the pneumatic cylinder, elevator, door, hopper and air cannon, the machine
upgrades and the printed circuit board via UV light box and etching tank. Numbers come from
the mod's recipes, configs and guide book. Advanced compressors, assembly line, drones and
the programmer are stage 3 and only named; the Kronwerke recipes for the flux compressor,
pneumatic dynamo and drone follow kubejs/server_scripts/kronwerke/added.js."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_advancement, reward_item,
                  reward_table, reward_xp, banner, img, item_texture)

C = "pneumaticcraft"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Druckluft ----------------------------------------------------------
    quest("welcome", 0, 0, "&b&lSprenge Eisen zu Druckeisen",
          subtitle="PneumaticCraft beginnt mit einem Knall.",
          description=[
              "Wirf &6Eisenbarren&r auf den Boden, stell &6TNT&r daneben und zünde es. Aus den Barren wird &6Druckeisen&r (Compressed Iron Ingot), etwa &e20 Prozent&r gehen dabei verloren. Ein Eisenblock wird genauso zu einem Druckeisenblock.",
              "",
              pic("pneumaticcraft:ingot_iron_compressed"),
              "",
              "&bPneumaticCraft&r arbeitet nicht mit Strom, sondern mit &bDruckluft&r in Bar. Kompressoren machen Luft, Rohre leiten sie, Maschinen verbrauchen sie, und wer zu viel Druck auf ein Rohr gibt, bekommt eine Explosion. Druckeisen steckt in fast jedem Rezept dieses Mods.",
              "",
              "&eWas in Stufe 2 offen ist:&r die Druckkammer, der Luft- und der Flüssigkeitskompressor, Öl und Raffinerie, Hitze, Kunststoff, Aufzug, Tür, Luftkanone, die Maschinen-Upgrades und die erste Platine.",
              "",
              "&cWas noch wartet:&r Die fortgeschrittenen Kompressoren, die Montagestraße, Drohnen und der Programmierer öffnen in &6Stufe 3&r. Die Druckluftrüstung und die Minigun kommen in Stufe 4.",
              "",
              "Sobald die Druckkammer steht, machst du Druckeisen ohne Verlust. Für den Anfang reichen ein paar gesprengte Barren.",
          ],
          tasks=[task_item("pneumaticcraft:ingot_iron_compressed", 8)],
          rewards=[reward_item("pneumaticcraft:ingot_iron_compressed", 8), reward_item("minecraft:tnt", 4), reward_table("s2_common")],
          icon="pneumaticcraft:ingot_iron_compressed", size=2.0, shape="hexagon"),

    quest("reinforced_stone", 2.5, -1, "&7Verstärke Stein",
          subtitle="Das Baumaterial aller Druckluftmaschinen.",
          description=[
              "Acht &6Stein&r um einen &6Druckeisenbarren&r ergeben acht &6Verstärkten Stein&r (Reinforced Stone). Vier davon im Quadrat werden zu vier &6Verstärkten Ziegeln&r (Reinforced Bricks).",
              "",
              "Aus den Ziegeln baust du den Luftkompressor und die Wände der Druckkammer, aus den Stufen des Steins fast jede andere Maschine. Mach gleich einen Stapel Stein zu Ziegeln, du brauchst für die erste Kammer über 50.",
          ],
          tasks=[task_item("pneumaticcraft:reinforced_bricks", 16)],
          rewards=[reward_item("minecraft:stone", 32), reward_xp(3)],
          deps=["welcome"], icon="pneumaticcraft:reinforced_bricks"),

    quest("tube", 2.5, 1, "&bLeg Druckluftrohre",
          subtitle="Acht Rohre aus zwei Barren und Glas.",
          description=[
              "Zwei &6Druckeisenbarren&r mit einem &6Flüssigkeitsrohr&r aus Create dazwischen ergeben acht &6Druckluftrohre&r (Pressure Tube). Sie fassen je 1 000 mL Luft und halten &e5 Bar&r aus.",
              "",
              "Ein offenes Rohrende zischt und verliert Luft. Verbinde jedes Rohr mit einer Maschine oder einem anderen Rohr, oder schließ die Seite später mit dem Druckluftschlüssel. Rohre lassen sich außerdem mit Modulen bestücken, dem Sicherheitsventil zum Beispiel.",
          ],
          tasks=[task_item("pneumaticcraft:pressure_tube", 16)],
          rewards=[reward_item("pneumaticcraft:pressure_tube", 8), reward_item("minecraft:glass", 16)],
          deps=["welcome"]),

    quest("compressor", 5, 0, "&6&lBau einen Luftkompressor",
          subtitle="Kohle rein, Druck raus.",
          description=[
              "&eRezept:&r sechs &6Verstärkte Ziegel&r außen herum, ein &6Ofen&r unten in der Mitte, ein &6Druckluftrohr&r rechts in der Mitte ergeben den &6Luftkompressor&r (Air Compressor).",
              "",
              "Er verbrennt alles, was ein Ofen verbrennt, und macht daraus &b10 mL Luft pro Tick&r. Ein Stück Kohle brennt 1 600 Ticks, das sind 16 000 mL. Eimer mit Lava nimmt er nicht, dafür gibt es den Flüssigkeitskompressor.",
              "",
              "Der Kompressor ist eine Maschine der ersten Stufe und hält selbst nur &e5 Bar&r aus. Läuft er ohne Verbraucher weiter, explodiert er irgendwann. Häng also immer ein Rohr mit Ventil dran, oder nimm die Kohle heraus.",
              "",
              "&eOhne Kohle:&r Der &6Handkompressor&r (Manual Compressor: zwei Druckeisenzahnräder, ein Steinsockel, Rohr, Barren, zwei rote Farbstoffe) pumpt, solange du Rechtsklick hältst, und kostet Hunger statt Brennstoff. Jeder Pumpstoß gibt 1 000 mL.",
          ],
          tasks=[task_item("pneumaticcraft:air_compressor", 1)],
          rewards=[reward_item("minecraft:coal_block", 4), reward_table("s2_common"), reward_xp(8)],
          deps=["reinforced_stone", "tube"], icon="pneumaticcraft:air_compressor", size=1.75, shape="gear"),

    quest("pressure", 7.5, 0, "&bVersteh, was Bar bedeutet",
          subtitle="Druck ist Luft geteilt durch Volumen.",
          description=[
              "Jede Maschine hat ein &eVolumen&r in mL. Der Druck ist: &bLuft geteilt durch Volumen, minus 1&r. Eine Maschine mit 5 000 mL Volumen und 20 000 mL Luft darin steht bei &e3 Bar&r. 0 Bar ist normale Luft, minus 1 Bar ein Vakuum.",
              "",
              "Luft fließt immer von hohem zu niedrigem Druck, bis alles gleich ist. Ein kleines Rohr an einer großen Kammer bekommt deren Druck. Maschinen verbrauchen &eLuft&r, nicht Druck: Die Anzeige fällt, weil weniger Luft im selben Volumen steckt.",
              "",
              "&eDie Anzeige:&r Im Fenster jeder Maschine sitzt eine runde Druckanzeige. Der &crote Bereich&r beginnt bei der Gefahrengrenze (5 Bar für alles in diesem Kapitel). Wie weit darüber es knallt, ist Zufall. Der Reiter &eProbleme&r am Fensterrand sagt dir, wenn Druck fehlt.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:pressure_tube", 8)],
          deps=["compressor"], icon="pneumaticcraft:pressure_gauge"),

    quest("gauge", 10, 0, "&7Bau Druckmesser",
          subtitle="Vier Kupfer, ein Druckeisen.",
          description=[
              "Vier &6Kupferbarren&r im Kreuz um einen &6Druckeisenbarren&r ergeben einen &6Druckmesser&r (Pressure Gauge). Allein kann er nichts, aber er steckt im Sicherheitsventil, im Manometer und in der Vakuumpumpe.",
              "",
              pic("pneumaticcraft:pressure_gauge"),
              "",
              "Mach gleich vier. Kupfer hast du genug.",
          ],
          tasks=[task_item("pneumaticcraft:pressure_gauge", 4)],
          rewards=[reward_item("minecraft:copper_ingot", 16)],
          deps=["pressure"]),

    quest("safety", 12.5, 0, "&c&lSetz ein Sicherheitsventil",
          subtitle="Ab 4,9 Bar zischt es, statt zu knallen.",
          description=[
              "Ein &6Druckmesser&r oben, darunter ein &6Druckluftrohr&r zwischen zwei &6Hebeln&r ergeben das &6Sicherheitsventil&r (Safety Tube Module). Klick es an die Seite eines Rohrs.",
              "",
              "Steigt der Druck im Rohr auf &e4,9 Bar&r, bläst das Ventil Luft ab. Das Rohr platzt bei 5 Bar, der Kompressor ebenso, also sitzt es genau richtig. Abgeblasene Luft ist verbrannte Kohle, darum ist das Ventil die Notbremse und nicht die Regelung.",
              "",
              "&eDie Regelung:&r Ein &6Druckanzeige-Modul&r (Pressure Gauge Module: Druckmesser über einem Rohr zwischen zwei Redstone) gibt ein Redstone-Signal mit &eStärke 2 mal Bar&r, bei 3,5 Bar also 7. Damit schaltest du den Kompressor über seinen Redstone-Reiter ab, bevor das Ventil überhaupt anspricht.",
              "",
              "&cMerk dir:&r Jedes Rohr, jeder Kompressor und jede Maschine in diesem Kapitel hält 5 Bar. Später gibt es Rohre für 10 Bar, in Stufe 3 für 20.",
          ],
          tasks=[task_item("pneumaticcraft:safety_tube_module", 1), task_item("pneumaticcraft:pressure_gauge_module", 1)],
          rewards=[reward_item("minecraft:redstone", 16), reward_table("s2_common"), reward_xp(8)],
          deps=["gauge"], icon="pneumaticcraft:safety_tube_module", size=1.5, shape="hexagon"),

    # ---- Die Druckkammer ----------------------------------------------------
    quest("walls", 0, 5, "&7Bau Kammerwände",
          subtitle="Acht Ziegel, sechzehn Wände.",
          description=[
              "Acht &6Verstärkte Ziegel&r im Ring ergeben 16 &6Kammerwände&r (Pressure Chamber Wall). Mit einem &6Glas&r in der Mitte werden es 16 &6Kammergläser&r, die genauso tragen, aber durchsichtig sind.",
              "",
              "Eine 3x3x3-Kammer braucht 26 Blöcke in der Hülle. Rechne mit 20 Wänden oder Gläsern, der Rest sind Ventil und Schnittstellen aus dem nächsten Schritt.",
          ],
          tasks=[task_item("pneumaticcraft:pressure_chamber_wall", 16), task_item("pneumaticcraft:pressure_chamber_glass", 4)],
          rewards=[reward_item("pneumaticcraft:reinforced_bricks", 16), reward_xp(3)],
          deps=["tube"], icon="pneumaticcraft:pressure_chamber_glass"),

    quest("valve_interface", 2.5, 5, "&7Ventil und Schnittstellen",
          subtitle="Luft rein, Gegenstände rein und raus.",
          description=[
              "Ein &6Druckluftrohr&r formlos mit vier &6Kammerwänden&r ergibt vier &6Kammerventile&r (Pressure Chamber Valve). Ein &6Trichter&r mit zwei Kammerwänden ergibt zwei &6Kammerschnittstellen&r (Pressure Chamber Interface).",
              "",
              "Das &eVentil&r ist der Anschluss für die Luft, dort kommt das Rohr vom Kompressor an. Die &eSchnittstelle&r schleust Gegenstände durch die Wand: eine mit dem &eI&r nach außen nimmt auf, eine mit dem &eO&r nach außen gibt fertige Sachen ab. Jeder Gegenstand kostet dabei &e1 000 mL&r Luft.",
              "",
              "Du brauchst mindestens ein Ventil. Zwei Schnittstellen sind die Empfehlung, sonst musst du alles von Hand hineinwerfen und wieder herausfischen.",
          ],
          tasks=[task_item("pneumaticcraft:pressure_chamber_valve", 1), task_item("pneumaticcraft:pressure_chamber_interface", 2)],
          rewards=[reward_item("minecraft:hopper", 2)],
          deps=["walls"], icon="pneumaticcraft:pressure_chamber_valve"),

    quest("chamber", 5, 5, "&b&lSetz die Druckkammer zusammen",
          subtitle="Ein hohler Würfel, 3x3x3 bis 5x5x5.",
          description=[
              "Bau einen &ehohlen Würfel&r aus Kammerwänden und Kammergläsern, 3x3x3, 4x4x4 oder 5x5x5. &6Ventil&r und &6Schnittstellen&r sitzen in einer &eFläche&r, nie an einer Kante oder Ecke. Sobald die Hülle geschlossen ist, bildet sich die Kammer von selbst.",
              "",
              "&eSo stellst du sie auf:&r Schnittstelle mit dem I nach außen an eine Seite, daneben eine mit dem O nach außen, einen Trichter oder ein Rohr an jede. Das Ventil bekommt das Rohr vom Kompressor. Rechtsklick auf das Ventil öffnet das Fenster mit Druck und Inhalt.",
              "",
              "Eine 3x3x3-Kammer hat &e16 000 mL&r Volumen. Für einen vollen Stapel durch die Schnittstelle braucht sie 64 000 mL, also 4 Bar. Größere Kammern fassen mehr Luft und sind ein guter Druckspeicher, brauchen aber länger, bis der Druck steht.",
              "",
              "&cAchtung:&r Auch die Kammer hält nur &e5 Bar&r. Das verstärkte Ventil für 20 Bar kommt in Stufe 3 aus der Montagestraße.",
          ],
          tasks=[task_advancement("pneumaticcraft:pressure_chamber", "Eine Druckkammer zusammensetzen")],
          rewards=[reward_item("pneumaticcraft:pressure_chamber_glass", 8), reward_table("s2_uncommon"), reward_xp(12)],
          deps=["valve_interface", "compressor"], icon="pneumaticcraft:pressure_chamber_wall", size=2.0, shape="hexagon"),

    quest("chamber_iron", 7.5, 4, "&7Presse Eisen ohne Verlust",
          subtitle="2 Bar statt TNT.",
          description=[
              "Leg &6Eisenbarren&r in die Kammer und gib &e2 Bar&r darauf. Jeder Barren wird zu einem &6Druckeisenbarren&r, nichts geht verloren. Ein &6Eisenblock&r wird genauso zu einem &6Druckeisenblock&r.",
              "",
              "Nimm Blöcke statt Barren: Die Schnittstelle kostet 1 000 mL pro Gegenstand, ein Block ist neun Barren für den Preis von einem. Neun Druckeisenblöcke ergeben an der Werkbank wieder 81 Barren.",
              "",
              "Ab hier ist Druckeisen kein Engpass mehr. Druckeisenblöcke sind außerdem sehr gute Wärmeleiter, dazu mehr im Abschnitt Hitze.",
          ],
          tasks=[task_item("pneumaticcraft:compressed_iron_block", 2)],
          rewards=[reward_item("minecraft:iron_block", 4), reward_xp(5)],
          deps=["chamber"], icon="pneumaticcraft:compressed_iron_block"),

    quest("chamber_recipes", 7.5, 6, "&7Die ersten Kammerrezepte",
          subtitle="Stein, Mehl, Eis und Diamanten.",
          description=[
              "Die Kammer presst bei &e1 Bar&r &6Stein&r zu &6Druckstein&r (Baumaterial, vier davon ergeben Druckziegel), einen &6Goldbarren&r mit zwei Redstone zu einem &6Turbinenblatt&r und einen &6Milcheimer&r mit vier grünen Farbstoffen zu vier &6Schleimbällen&r.",
              "",
              "Bei &e1,5 Bar&r wird &6Weizen&r zu drei &6Mehl&r und vier Schneeblöcke zu Eis. Bei &e2 Bar&r werden vier Eis zu Packeis, bei &e2,5 Bar&r vier Packeis zu Blaueis.",
              "",
              "Und bei &e4 Bar&r werden acht &6Kohleblöcke&r zu einem &6Diamanten&r. Das sind 72 Kohle pro Diamant, teuer, aber ohne Graben. Dafür musst du nah an die 5-Bar-Grenze, also Sicherheitsventil nicht vergessen.",
          ],
          tasks=[task_item("pneumaticcraft:compressed_stone", 8)],
          rewards=[reward_item("minecraft:coal_block", 8), reward_xp(5)],
          deps=["chamber"], icon="pneumaticcraft:compressed_stone"),

    # ---- Werkzeug -----------------------------------------------------------
    quest("canister", 12.5, 5, "&7Bau Luftkanister und Manometer",
          subtitle="Luft zum Mitnehmen.",
          description=[
              "Ein &6Druckluftrohr&r oben, darunter zwei Reihen aus &6Druckeisen&r, &6Redstone&r, &6Druckeisen&r ergeben einen &6Luftkanister&r (Air Canister). Er fasst 3 000 mL, lädt bis 10 Bar und explodiert nie.",
              "",
              pic("pneumaticcraft:air_canister"),
              "",
              "Ein &6Druckmesser&r über einem Kanister ergibt das &6Manometer&r. Rechtsklick auf ein Rohr oder eine Maschine zeigt dir den Druck im Chat, beim Sicherheitsventil auch dessen Schwelle. Mit Jade im Pack siehst du den Druck meist schon beim Hinsehen, trotzdem ist es für die ersten Fehlersuchen Gold wert.",
              "",
              "Jedes Druckluftwerkzeug wird aus einem Kanister gebaut und übernimmt dessen Luft.",
          ],
          tasks=[task_item("pneumaticcraft:air_canister", 2), task_item("pneumaticcraft:manometer", 1)],
          rewards=[reward_item("minecraft:redstone", 16), reward_xp(3)],
          deps=["compressor"], icon="pneumaticcraft:manometer"),

    quest("charging", 15, 5, "&a&lBau eine Ladestation",
          subtitle="Werkzeug auftanken, Upgrades einsetzen.",
          description=[
              "&eRezept:&r ein &6Druckluftrohr&r rechts oben, drei &6Ziegelsteine&r (die aus dem Ofen) in der Mitte, drei &6Verstärkte Steinstufen&r unten ergeben die &6Ladestation&r (Charging Station).",
              "",
              "Leg ein Druckluftwerkzeug hinein, schließ ein Rohr an, und der Druck gleicht sich aus. Werkzeuge laden bis &e10 Bar&r, also mehr, als ein Rohr aushält: Die Station bekommt, was das Netz hergibt, und ein voller Kanister braucht Geduld.",
              "",
              "Der &ePfeil über dem Slot&r öffnet das Upgrade-Fenster des Werkzeugs. Mit einem &6Spender-Upgrade&r in der Station wird sie zum &eLadefeld&r: Alles, was auf ihr liegt oder in deiner Tasche steckt, wenn du draufstehst, wird geladen.",
              "",
              "&eNebenbei:&r Die Ladestation ist der Arbeitsblock des &6Druckmechanikers&r. Ein Dorfbewohner ohne Beruf nimmt ihn an, und dieser Händler wird später für die Platinen-Vorlage wichtig.",
          ],
          tasks=[task_item("pneumaticcraft:charging_station", 1)],
          rewards=[reward_item("minecraft:brick", 8), reward_table("s2_common"), reward_xp(8)],
          deps=["canister"], icon="pneumaticcraft:charging_station", size=1.5, shape="gear"),

    quest("wrench", 17.5, 5, "&6Bau den Druckluftschlüssel",
          subtitle="Dreht, schließt, baut ab.",
          description=[
              "Vier &6Druckeisenbarren&r in die Ecken, &6oranger Farbstoff&r oben in der Mitte, ein &6Hebel&r unten in der Mitte, ein &6Luftkanister&r links in der Mitte ergeben den &6Druckluftschlüssel&r (Pneumatic Wrench). Lad ihn in der Station auf mindestens 3 Bar, ohne Luft tut er nichts.",
              "",
              "&eRechtsklick&r dreht Blöcke und schließt oder öffnet einzelne Seiten eines Druckluftrohrs. &eSchleichen und Rechtsklick&r baut eine Maschine samt Luft und Upgrades ab. Mit der Spitzhacke verlierst du beides. Module am Rohr nimmst du genauso wieder ab.",
          ],
          tasks=[task_item("pneumaticcraft:pneumatic_wrench", 1)],
          rewards=[reward_item("pneumaticcraft:ingot_iron_compressed", 8), reward_xp(5)],
          deps=["charging"]),

    quest("omni_hopper", 20, 5, "&eBau einen Rundum-Trichter",
          subtitle="Ein Trichter, der in jede Richtung zeigt.",
          description=[
              "Vier &6Druckeisenbarren&r um eine &6Truhe&r (zwei oben außen, zwei in der Mitte, einer unten) ergeben den &6Rundum-Trichter&r (Omnidirectional Hopper). Er braucht keine Luft.",
              "",
              "Beim Setzen zeigt der Eingang zu dir, der Ausgang auf den Block, an den du ihn gesetzt hast. &eRechtsklick mit dem Schlüssel&r dreht den Eingang, &eSchleichen und Rechtsklick&r den Ausgang. So zieht er aus einer Truhe oben heraus und schiebt seitlich in die Kammerschnittstelle.",
              "",
              "Jedes &6Geschwindigkeits-Upgrade&r verdoppelt sein Tempo. Mit einem &6Spender-Upgrade&r wirft er Gegenstände in die Welt, was du für flüssigen Kunststoff noch brauchen wirst. Der &6Flüssigkeitstrichter&r (Liquid Hopper: kleiner Tank über einem Trichter) macht dasselbe mit Flüssigkeiten.",
          ],
          tasks=[task_item("pneumaticcraft:omnidirectional_hopper", 2)],
          rewards=[reward_item("minecraft:chest", 4), reward_xp(5)],
          deps=["wrench"], icon="pneumaticcraft:omnidirectional_hopper"),

    # ---- Öl -----------------------------------------------------------------
    quest("liquid_compressor", 0, 9, "&6Bau einen Flüssigkeitskompressor",
          subtitle="Für alles, was aus dem Eimer brennt.",
          description=[
              "Ein &6Kleiner Tank&r (Small Tank: vier Eisengitter, vier Druckeisen, ein Glas, 32 000 mB) zwischen zwei &6Druckluftrohren&r oben, ein &6Luftkompressor&r zwischen zwei &6Leder&r unten ergeben den &6Flüssigkeitskompressor&r (Liquid Compressor).",
              "",
              "Er verbrennt Flüssigkeiten: &bLava&r geht schon, richtig gut werden Diesel, Kerosin, Benzin und LPG aus der Raffinerie. Der Reiter &eVerfügbare Brennstoffe&r im Fenster listet alles von bestem bis schlechtestem. Eimer rechtsklicken, in den oberen Slot legen oder per Rohr hineinpumpen.",
              "",
              "Der kleine Tank lohnt sich auch allein: Er behält seinen Inhalt beim Abbauen, und mit dem Schlüssel stapelst du mehrere zu einem großen.",
          ],
          tasks=[task_item("pneumaticcraft:liquid_compressor", 1), task_item("pneumaticcraft:small_tank", 2)],
          rewards=[reward_item("minecraft:leather", 8), reward_table("s2_common"), reward_xp(8)],
          deps=["compressor"], icon="pneumaticcraft:liquid_compressor", size=1.5),

    quest("find_oil", 2.5, 9, "&8Such Öl mit dem Seismischen Sensor",
          subtitle="Ölseen liegen meist tief unter der Erde.",
          description=[
              "Eine &6Redstone-Fackel&r oben, ein &6Verstärker&r zwischen zwei &6Glas&r in der Mitte, ein &6Notenblock&r zwischen zwei Glas unten ergeben den &6Seismischen Sensor&r (Seismic Sensor). Er braucht keine Luft.",
              "",
              "Rechtsklick auf den Boden sagt dir, ob direkt darunter &8Rohöl&r liegt, wie tief und etwa wie viele Eimer. &eUnterirdische Ölseen&r gibt es in jedem sechsten Chunk, zwischen Y 0 und der Oberfläche und mindestens 5 Blöcke unter ihr. Seen an der Oberfläche sind seltener, einer in 25 Chunks.",
              "",
              "Lauf also mit dem Sensor im Raster von 16 Blöcken über die Gegend nahe deiner Basis und markiere Treffer. Der Ölscanner von Create Diesel Generators zeigt übrigens etwas anderes an, nämlich das Öl für die Pumpjacks aus Stufe 3.",
          ],
          tasks=[task_item("pneumaticcraft:seismic_sensor", 1)],
          rewards=[reward_item("minecraft:glass", 8), reward_xp(3)],
          deps=["liquid_compressor"]),

    quest("pump_oil", 5, 9, "&8Pump Öl mit dem Gaslift",
          subtitle="Der erste Eimer Rohöl.",
          description=[
              "Ein &6Druckluftrohr&r oben, ein &6Kleiner Tank&r zwischen zwei Rohren in der Mitte, drei &6Verstärkte Steinstufen&r unten ergeben den &6Gaslift&r (Gas Lift). Drei Rohre übereinander ergeben drei &6Bohrrohre&r (Drill Pipe), leg sie in sein Inventar.",
              "",
              "Stell den Gaslift über den Treffer des Sensors und gib Luft darauf. Er bohrt mit den Bohrrohren nach unten, Erde und Stein werden ohne Ausbeute entfernt, und sobald er Flüssigkeit trifft, pumpt er sie in seinen Tank. Je tiefer, desto mehr Druck braucht er, höchstens 4,9 Bar.",
              "",
              "Der Modus &ePumpen und Flüssigkeit im Filter lassen&r behält 1 000 mB im Tank, damit kein Wasser dazukommt. &eBohrrohre einziehen&r holt alles wieder hoch. Das Öl pumpst du mit Rohren von Mekanism oder Pipez oder einem Flüssigkeitstrichter in Tanks.",
              "",
              "&eNotnagel:&r Rohöl ist selbst ein schlechter Brennstoff, 200 000 mL Luft pro Eimer. Erst die Raffinerie macht etwas daraus.",
          ],
          tasks=[task_item("pneumaticcraft:gas_lift", 1), task_item("pneumaticcraft:oil_bucket", 1)],
          rewards=[reward_item("pneumaticcraft:drill_pipe", 12), reward_table("s2_uncommon"), reward_xp(8)],
          deps=["find_oil"], icon="pneumaticcraft:gas_lift", size=1.5),

    quest("refinery", 7.5, 9, "&6&lBau die Raffinerie",
          subtitle="Ein Steuerblock, zwei bis vier Ausgänge, Hitze.",
          description=[
              "&eRezept Steuerblock:&r sechs &6Verstärkte Steinstufen&r oben und unten, ein &6Kleiner Tank&r zwischen zwei &6Redstone&r in der Mitte ergeben die &6Raffinerie&r (Refinery). &eRezept Ausgang:&r dieselben Stufen, in der Mitte ein &6Diamant&r zwischen zwei &6Glas&r ergeben einen &6Raffinerie-Ausgang&r (Refinery Output).",
              "",
              "Stell den Steuerblock hin und &ezwei bis vier Ausgänge&r direkt darauf oder daneben übereinander. Öl kommt in den Steuerblock, die Brennstoffe sammeln sich in den Ausgängen: der leichteste oben, der schwerste unten. Aus 10 mB Öl werden mit zwei Ausgängen 4 Diesel und 2 LPG, mit drei 2 Diesel, 3 Kerosin, 2 LPG, mit vier 2 Diesel, 3 Kerosin, 3 Benzin, 2 LPG.",
              "",
              "Die Raffinerie läuft &eab 100 Grad&r und braucht weder Luft noch Strom, nur &cHitze&r. Je heißer, desto schneller. Wie du heizt, steht im Abschnitt Hitze: ein Wirbelrohr, Lava oder Magma daneben, oder ein &6Lohenbrenner&r von Create.",
              "",
              "&eTipp:&r Sie hat viele offene Seiten und verliert Hitze an die Luft. Verkleide alles, was frei ist, mit beliebigen Blöcken, Platten oder Falltüren, am besten mit &6Wärmedämmung&r (Thermal Lagging: Wolle und Glas im Schachbrett).",
          ],
          tasks=[task_item("pneumaticcraft:refinery", 1), task_item("pneumaticcraft:refinery_output", 2)],
          rewards=[reward_item("minecraft:diamond", 2), reward_table("s2_uncommon"), reward_xp(12)],
          deps=["pump_oil", "vortex"], icon="pneumaticcraft:refinery", size=1.75, shape="gear"),

    quest("fuels", 10, 9, "&eDiesel, Kerosin, Benzin und LPG",
          subtitle="Vier Brennstoffe, vier Aufgaben.",
          description=[
              "Hol je einen Eimer &bDiesel&r und &bLPG&r aus den Ausgängen. Im Flüssigkeitskompressor gibt ein Eimer Öl 200 000 mL Luft, &bDiesel&r 1 000 000, &bKerosin&r 1 100 000, &bBenzin&r 1 500 000 und &bLPG&r 1 800 000. Benzin und LPG brennen dabei schneller als Diesel, also mehr Luft pro Tick.",
              "",
              "&eWofür du sie brauchst:&r &bLPG&r wird zu Kunststoff, &bDiesel&r zu Schmiermittel für Geschwindigkeits-Upgrades. &bKerosin&r brennt in der &6Kerosinlampe&r (drei Druckeisen, zwei Glasscheiben, ein kleiner Tank), die bis zu 30 Blöcke weit ausleuchtet; ein Eimer reicht bei 10 Blöcken etwa 40 echte Minuten.",
              "",
              "&eKronwerke:&r Der Diesel läuft auch im &6Dieselmotor&r von Create Diesel Generators, mit 96 RPM und 6 144 SU pro Motor (siehe Kapitel Create: Erweiterungen). Ein Raffinerie-Diesel treibt also die Präzisionslinie für das Stufenziel an. Ein Eimer LPG im Ofen schmilzt außerdem 450 Gegenstände.",
              "",
              "Zu viel von einer Sorte? Die &6Thermopneumatische Anlage&r knackt bei 300 Grad und 2 Bar Diesel zu Kerosin, Kerosin zu Benzin und Benzin zu LPG, mit 80 Prozent Ausbeute.",
          ],
          tasks=[task_item("pneumaticcraft:diesel_bucket", 1), task_item("pneumaticcraft:lpg_bucket", 1)],
          rewards=[reward_item("pneumaticcraft:kerosene_lamp", 1), reward_item("minecraft:bucket", 4), reward_xp(8)],
          deps=["refinery"], icon="pneumaticcraft:diesel_bucket"),

    quest("tpp", 12.5, 9, "&6&lBau die Thermopneumatische Anlage",
          subtitle="Hitze und Druck für Flüssigkeiten.",
          description=[
              "Sechs &6Verstärkte Steinstufen&r oben und unten, ein &6Druckluftrohr&r zwischen zwei &6Kleinen Tanks&r in der Mitte ergeben die &6Thermopneumatische Anlage&r (Thermopneumatic Processing Plant, kurz TPP).",
              "",
              "Links kommt eine Flüssigkeit und ein Gegenstand hinein, rechts eine Flüssigkeit oder ein Gegenstand heraus. Manche Rezepte wollen Hitze, manche Druck, manche beides. Die Anlage heizt du wie die Raffinerie, und sie bekommt ein Rohr für die Luft.",
              "",
              "&eDie wichtigsten Rezepte:&r 100 mB LPG und eine Kohle ergeben bei 100 Grad &b1 000 mB Kunststoff&r. 1 000 mB Diesel und ein Redstone ergeben bei 100 Grad &b1 000 mB Schmiermittel&r. Ein Lapislazuli und 1 000 mB Wasser ergeben bei 2 Bar vier &6Upgrade-Matrizen&r, die in Upgrades den Lapis ersetzen. Ein Rohr mit 50 mB Kunststoff wird bei 1,5 Bar zum &6Verstärkten Rohr&r.",
              "",
              "Mit einem &6Spender-Upgrade&r schiebt sie ihre Flüssigkeit von selbst in einen Tank daneben.",
          ],
          tasks=[task_item("pneumaticcraft:thermopneumatic_processing_plant", 1)],
          rewards=[reward_item("pneumaticcraft:small_tank", 2), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["fuels"], icon="pneumaticcraft:thermopneumatic_processing_plant", size=1.5, shape="gear"),

    # ---- Hitze --------------------------------------------------------------
    quest("vortex", 15, 9, "&c&lBau ein Wirbelrohr",
          subtitle="Druckluft wird zu heiß und kalt.",
          description=[
              "Zwei &6Druckluftrohre&r übereinander in der Mitte, zwei &6Kupferbarren&r links und rechts in der mittleren Reihe, der Rest &6Druckeisen&r (sechs Stück) ergeben das &6Wirbelrohr&r (Vortex Tube).",
              "",
              "Es teilt die Luft, die hineinströmt, in eine &cheiße&r und eine &bkalte&r Seite. Beim Setzen zeigt die heiße Seite zu dir, ein roter und ein blauer Ring markieren die Enden. Mehr Druck gibt mehr Temperaturunterschied, verbraucht aber auch mehr Luft.",
              "",
              "Die heiße Seite kommt an die Raffinerie oder die Anlage. Auf die kalte Seite gehört ein &6Kühlkörper&r, denn beide Seiten hängen schwach zusammen: Wird die kalte Seite nicht entlüftet, bremst sie die heiße.",
              "",
              "&eKronwerke:&r Ein Komparator an der Raffinerie gibt 15, solange sie Arbeit hat. Damit schaltest du die Luft zum Wirbelrohr ab, wenn nichts zu tun ist.",
          ],
          tasks=[task_item("pneumaticcraft:vortex_tube", 1)],
          rewards=[reward_item("minecraft:copper_ingot", 16), reward_table("s2_common"), reward_xp(8)],
          deps=["safety"], icon="pneumaticcraft:vortex_tube", size=1.5, shape="hexagon"),

    quest("heat_sources", 17.5, 8, "&cWas heizt und was kühlt",
          subtitle="Lava, Magma, Lohenbrenner, Eis.",
          description=[
              "Hitze wandert von Block zu Block, immer vom heißen zum kalten, und nur zwischen Blöcken, die Hitze kennen. &bLava&r neben einer Maschine heizt sie und wird dabei langsam zu &7Obsidian&r. &6Magma&r heizt und wird zu Netherrack. Fackeln und Lagerfeuer heizen nur schwach.",
              "",
              "&eKronwerke:&r Der &6Lohenbrenner&r von Create ist eine Hitzequelle, die &enicht verbraucht&r wird. Entzündet überträgt er gut, überhitzt (mit Lohenkuchen) noch fünfmal besser. Du hast einen im Startpaket dieser Stufe. Stell ihn direkt an die Raffinerie und spar dir das Wirbelrohr fürs Erste.",
              "",
              "&bKälte&r kommt von Eis, Packeis, Blaueis und Schnee, die dabei schmelzen. Ein &6Druckeisenblock&r leitet Hitze fast ohne Widerstand weiter, ein &6Wärmerohr&r (Heat Pipe: Wärmedämmung um Druckeisenblöcke, sechs Stück) genauso, nur ohne Verlust an die Luft.",
              "",
              "Ein normaler &6Ofen&r neben einer heißen Maschine braucht ab 100 Grad keinen Brennstoff mehr, er läuft auf der Hitze. Das gilt auch für Schmelzofen und Räucherofen.",
              "",
              "&cStufe 3:&r Der fortgeschrittene Luft- und der fortgeschrittene Flüssigkeitskompressor erzeugen beim Arbeiten selbst Hitze und müssen gekühlt werden, die Hitze heizt dann nebenbei die Raffinerie.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_item("minecraft:magma_block", 8), reward_xp(5)],
          deps=["vortex"], icon="create:blaze_burner"),

    quest("heat_sink", 17.5, 10, "&bKühl mit Kühlkörpern",
          subtitle="Hitze oder Kälte an die Luft abgeben.",
          description=[
              "Drei &6Eisengitter&r oben, darunter &6Druckeisen&r, &6Kupfer&r, &6Druckeisen&r ergeben einen &6Kühlkörper&r (Heat Sink). Er gibt Hitze oder Kälte des Blocks, an dem er &esitzt&r, an die Luft ab. Nur an den Block, auf dem er klebt, nicht an Nachbarn.",
              "",
              "Setz ihn auf die kalte Seite des Wirbelrohrs. Mehrere Kühlkörper brauchen mehrere Flächen, dafür hängst du einen Druckeisenblock oder ein Wärmerohr dazwischen. Ein &6Luftgitter-Modul&r an einem Rohr vor den Kühlkörpern bläst sie an und kühlt sie deutlich stärker.",
              "",
              "&cVorsicht:&r Ein Kühlkörper über 60 Grad oder unter minus 60 Grad verletzt dich beim Anfassen.",
          ],
          tasks=[task_item("pneumaticcraft:heat_sink", 2)],
          rewards=[reward_item("minecraft:iron_bars", 16), reward_xp(5)],
          deps=["vortex"]),

    quest("heat_frame", 20, 9, "&6Schmilz mit einem Hitzerahmen",
          subtitle="Ein Ofen ohne Ofen, oder ein Gefrierfach.",
          description=[
              "Acht &6Druckeisenbarren&r um einen &6Ofen&r ergeben den &6Hitzerahmen&r (Heat Frame). Klick ihn an eine Truhe oder eine andere Kiste. Heizt du ihn, schmilzt er alles in der Kiste wie ein Ofen, bis zu einem Gegenstand pro Sekunde. Kühlst du ihn, friert er.",
              "",
              "Der Rahmen nimmt Hitze nicht direkt von Lava oder einem Lohenbrenner. Stell ein Wärmerohr oder einen Druckeisenblock dazwischen, oder häng ihn an die heiße Seite eines Wirbelrohrs.",
              "",
              "&eGefroren wird unter 0 Grad:&r Ein Wassereimer in der Kiste wird zu Eis, ein Lavaeimer zu Obsidian, und ein Eimer flüssiger Kunststoff zu einer &6Kunststoffplatte&r, je kälter, desto öfter mit einer zweiten obendrauf. Der Eimer bleibt dir erhalten.",
          ],
          tasks=[task_item("pneumaticcraft:heat_frame", 1)],
          rewards=[reward_item("pneumaticcraft:ingot_iron_compressed", 8), reward_table("s2_common"), reward_xp(8)],
          deps=["heat_sources", "heat_sink"], icon="pneumaticcraft:heat_frame"),

    # ---- Kunststoff ---------------------------------------------------------
    quest("plastic", 0, 13, "&f&lKoch Kunststoff",
          subtitle="LPG und Kohle, ausgegossen.",
          description=[
              "Gib &b100 mB LPG&r und eine &6Kohle&r in die heiße Thermopneumatische Anlage (ab 100 Grad, kein Druck nötig). Heraus kommen &b1 000 mB flüssiger Kunststoff&r. Schöpf ihn in einen Eimer und &egieß ihn aus&r: Nach einer halben Sekunde liegt eine &6Kunststoffplatte&r (Plastic Sheet) da.",
              "",
              pic("pneumaticcraft:plastic"),
              "",
              "&eAutomatisch:&r Ein Flüssigkeitstrichter mit Spender-Upgrade gießt den Kunststoff aus, ein Rundum-Trichter sammelt die Platte ein. Oder du stellst einen Eimer Kunststoff in eine Kiste mit kaltem Hitzerahmen, das gibt bei tiefen Minusgraden bis zu 75 Prozent öfter eine zweite Platte.",
              "",
              "Kunststoff steckt im Druckluftzylinder, im GPS-Werkzeug, in den Aufzugrufern, im Amadron-Tablet und in jeder Platine. Ein Eimer LPG macht zehn Platten, ein Eimer Öl aus der Raffinerie also zwei. Plane eine Linie, keine Einzelrezepte.",
          ],
          tasks=[task_item("pneumaticcraft:plastic", 8)],
          rewards=[reward_item("pneumaticcraft:plastic", 8), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["tpp"], icon="pneumaticcraft:plastic", size=1.75, shape="hexagon"),

    quest("reinforced_tube", 2.5, 12, "&bVerstärke deine Rohre",
          subtitle="10 Bar statt 5.",
          description=[
              "Ein &6Druckluftrohr&r mit &b50 mB flüssigem Kunststoff&r bei &e1,5 Bar&r in der Anlage ergibt ein &6Verstärktes Druckluftrohr&r (Reinforced Pressure Tube). Es hält &e10 Bar&r aus, fasst wie das einfache 1 000 mL und nimmt dieselben Module.",
              "",
              "Damit lädst du Werkzeuge im Netz schneller auf ihre 10 Bar. Deine Maschinen bleiben trotzdem bei 5 Bar, also brauchen sie ein &6Regler-Modul&r (Regulator Module: zwei Sicherheitsventile um ein Rohr) vor dem Eingang. Es lässt ohne Redstone-Signal 4,9 Bar durch und sperrt bei vollem Signal ganz.",
              "",
              "&cStufe 3:&r Das &6Fortgeschrittene Rohr&r für 20 Bar und 4 000 mL kommt aus der Montagestraße.",
          ],
          tasks=[task_item("pneumaticcraft:reinforced_pressure_tube", 8)],
          rewards=[reward_item("pneumaticcraft:regulator_tube_module", 1), reward_xp(5)],
          deps=["plastic"], icon="pneumaticcraft:reinforced_pressure_tube"),

    quest("cylinder", 2.5, 14, "&7Bau Druckluftzylinder",
          subtitle="Das Bauteil für alles, was sich bewegt.",
          description=[
              "Zuerst ein &6Kanonenrohr&r (Cannon Barrel): sechs &6Verstärkte Ziegelmauern&r in zwei Säulen, unten in der Mitte ein &6Druckluftrohr&r. Dann der &6Druckluftzylinder&r (Pneumatic Cylinder): sechs &6Kunststoffplatten&r in die äußeren Spalten, zwei &6Druckeisen&r oben und mittig, das Kanonenrohr unten in der Mitte, ergibt zwei Zylinder.",
              "",
              pic("pneumaticcraft:pneumatic_cylinder"),
              "",
              "Zylinder stecken in der Aufzugbasis und im Türantrieb. Das Kanonenrohr brauchst du außerdem einzeln für die Luftkanone.",
          ],
          tasks=[task_item("pneumaticcraft:pneumatic_cylinder", 4)],
          rewards=[reward_item("pneumaticcraft:cannon_barrel", 1), reward_item("pneumaticcraft:plastic", 4), reward_xp(5)],
          deps=["plastic"], icon="pneumaticcraft:pneumatic_cylinder"),

    # ---- Maschinen ----------------------------------------------------------
    quest("elevator", 7.5, 12, "&a&lBau einen Aufzug",
          subtitle="Sechs Blöcke Höhe pro Basis.",
          description=[
              "Zwei &6Druckluftzylinder&r und zwei &6Kunststoffplatten&r schräg zueinander ergeben die &6Aufzugbasis&r (Elevator Base). Sechs &6Druckeisen&r in zwei Säulen ergeben vier &6Aufzugrahmen&r (Elevator Frame). Vier &6Steinknöpfe&r in die Ecken, vier Kunststoffplatten an die Seiten, ein Stein in die Mitte ergeben den &6Aufzugrufer&r (Elevator Caller).",
              "",
              "Die Basis kommt unten hin, Rahmen stapelst du darüber, so hoch der Aufzug fahren soll. Jede Basis trägt &e6 Blöcke&r Höhe, zwei Basen übereinander also 12. Die Basis bekommt Luft über ein Rohr.",
              "",
              "&eSteuern:&r Ein Redstone-Signal an die Basis fährt sie hoch, Stärke 15 ganz, Stärke 7 halb. Oder du setzt an jede Etage einen Aufzugrufer neben einen Rahmen, dann zeigt er die Etagen als Knöpfe. Namen gibst du den Etagen im Fenster der Basis.",
              "",
              "Mehrere Basen nebeneinander ergeben eine größere Plattform. Mit &6Lade-Upgrades&r holt sich der Aufzug beim Herunterfahren bis zu 60 Prozent der Luft zurück.",
          ],
          tasks=[task_item("pneumaticcraft:elevator_base", 1), task_item("pneumaticcraft:elevator_frame", 4), task_item("pneumaticcraft:elevator_caller", 2)],
          rewards=[reward_item("pneumaticcraft:elevator_frame", 8), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["cylinder"], icon="pneumaticcraft:elevator_base", size=1.5),

    quest("door", 7.5, 14, "&aBau eine Drucklufttür",
          subtitle="Geht auf, wenn du kommst.",
          description=[
              "Sechs &6Druckeisen&r in zwei Säulen ergeben die &6Drucklufttür&r (Pneumatic Door). Ein &6Druckluftzylinder&r oben in der Mitte, ein &6Druckluftrohr&r rechts in der Mitte, der Rest &6Druckeisen&r (sechs Stück) ergeben den &6Türantrieb&r (Pneumatic Door Base).",
              "",
              "Setz die Tür und daneben den Antrieb, und zwar auf Höhe der &eoberen Hälfte&r der Tür. Mit Luft öffnet sie sich, sobald ein Spieler im Umkreis von 2 Blöcken steht. Jedes &6Reichweiten-Upgrade&r gibt einen Block dazu.",
              "",
              "Im Fenster des Antriebs wählst du: &eSpieler in der Nähe&r, &eNähe und hinsehen&r oder &eHolztür&r (dann verhält sie sich wie eine normale Tür). Zwei Türen nebeneinander ergeben eine Doppeltür. In Stufe 3 öffnet sie mit einer Sicherheitsstation nur noch für Freunde.",
          ],
          tasks=[task_item("pneumaticcraft:pneumatic_door", 1), task_item("pneumaticcraft:pneumatic_door_base", 1)],
          rewards=[reward_item("pneumaticcraft:range_upgrade", 1), reward_xp(5)],
          deps=["cylinder"], icon="pneumaticcraft:pneumatic_door_base"),

    quest("air_cannon", 10, 13, "&eSchieß mit der Luftkanone",
          subtitle="Gegenstände fliegen zum GPS-Punkt.",
          description=[
              "Ein &6Kanonenrohr&r oben in der Mitte, darunter ein &6Steinsockel&r (Stone Base: vier Stein und ein Rohr) mit einem &6Druckluftrohr&r rechts daneben, unten drei &6Verstärkte Steinstufen&r ergeben die &6Luftkanone&r (Air Cannon).",
              "",
              "Dazu ein &6GPS-Werkzeug&r (GPS Tool): Redstone-Fackel oben, Glasscheibe zwischen zwei Kunststoffplatten, Diamant zwischen zwei Kunststoffplatten. Rechtsklick auf den Zielblock speichert ihn, dann kommt das Werkzeug in den GPS-Slot der Kanone. Ein Redstone-Impuls feuert alles, was im Inventar liegt, zum Ziel. Dort fängt eine Truhe mit Trichter oder ein Rundum-Trichter auf.",
              "",
              "Jedes &6Reichweiten-Upgrade&r bringt etwa 25 Blöcke mehr, bis 250. Mit einem &6Spender-Upgrade&r wirft sie TNT und Feuerkugeln wie ein Werfer. Mit einem &6Wesen-Tracker-Upgrade&r schießt sie statt Gegenständen das nächste Lebewesen los, dich eingeschlossen.",
          ],
          tasks=[task_item("pneumaticcraft:air_cannon", 1), task_item("pneumaticcraft:gps_tool", 1)],
          rewards=[reward_item("minecraft:diamond", 1), reward_table("s2_common"), reward_xp(8)],
          deps=["cylinder"], icon="pneumaticcraft:air_cannon"),

    # ---- Upgrades -----------------------------------------------------------
    quest("lubricant", 13.5, 13, "&eKoch Schmiermittel",
          subtitle="Diesel und Redstone, heiß.",
          description=[
              "&b1 000 mB Diesel&r und ein &6Redstone&r ergeben in der Anlage ab 100 Grad &b1 000 mB Schmiermittel&r (Lubricant). Schöpf es in einen Eimer, das ist die Zutat für jedes Geschwindigkeits-Upgrade.",
              "",
              "Biodiesel aus der Fermentation (siehe Kapitel Create: Erweiterungen) geht genauso. Und wer gar kein Öl findet: Amadron tauscht einen Eimer Öl gegen einen Smaragd.",
          ],
          tasks=[task_item("pneumaticcraft:lubricant_bucket", 1)],
          rewards=[reward_item("minecraft:redstone", 16), reward_xp(5)],
          deps=["tpp"], icon="pneumaticcraft:lubricant_bucket"),

    quest("upgrades", 16, 13, "&d&lBau Maschinen-Upgrades",
          subtitle="Volumen, Geschwindigkeit, Sicherheit.",
          description=[
              "Alle Upgrades haben dieselbe Form: vier &6Lapislazuli&r in die Ecken, vier gleiche Dinge an die Seiten, eins in die Mitte. &6Volumen&r: Druckeisen außen, ein &6Luftkanister&r innen. &6Geschwindigkeit&r: Zucker außen, ein &6Eimer Schmiermittel&r innen. &6Sicherheit&r: Obsidian außen, ein &6Sicherheitsventil&r innen.",
              "",
              "Upgrades kommen in den Upgrade-Reiter am Fensterrand der Maschine, in Werkzeuge über die Ladestation. Das &6Volumen-Upgrade&r vergrößert den Luftspeicher, eins verdoppelt, vier vervierfachen, dafür sinkt der Druck beim Einsetzen. Das &6Geschwindigkeits-Upgrade&r macht Maschinen je Stück &e1,5-mal&r so schnell, der Verbrauch steigt auf das 1,65-fache. Das &6Sicherheits-Upgrade&r ist ein Sicherheitsventil in der Maschine selbst.",
              "",
              "Vier &6Upgrade-Matrizen&r aus der Anlage (ein Lapis und Wasser bei 2 Bar) ersetzen die vier Lapis, das spart drei Viertel des Lapis. Im Rundum-Trichter verdoppelt jedes Geschwindigkeits-Upgrade das Tempo, im Kompressor bringt es mehr Luft pro Tick für mehr Kohle.",
          ],
          tasks=[task_item("pneumaticcraft:volume_upgrade", 1), task_item("pneumaticcraft:speed_upgrade", 1), task_item("pneumaticcraft:security_upgrade", 1)],
          rewards=[reward_item("minecraft:lapis_lazuli", 16), reward_table("s2_uncommon"), reward_xp(10)],
          deps=["lubricant"], icon="pneumaticcraft:speed_upgrade", size=1.5, shape="hexagon"),

    # ---- Die Platine --------------------------------------------------------
    quest("blueprint", 0, 16, "&9Besorg die Platinen-Vorlage",
          subtitle="Die gibt es nur im Handel.",
          description=[
              "Die &6Platinen-Vorlage&r (PCB Blueprint) lässt sich nicht craften. Bau ein &6Amadron-Tablet&r (sieben &6Kunststoffplatten&r um ein &6GPS-Werkzeug&r, unten in der Mitte ein &6Luftkanister&r), klick damit auf eine Truhe mit &e8 Smaragden&r und bestell die Vorlage. Eine Drohne von Amadron holt die Smaragde ab, eine zweite liefert.",
              "",
              pic("pneumaticcraft:pcb_blueprint"),
              "",
              "Oder du findest einen &6Druckmechaniker&r: Dieser Dorfbewohner hat sein eigenes Haus in manchen Dörfern, und jeder arbeitslose Dorfbewohner nimmt den Beruf an einer Ladestation an. Er handelt unter anderem mit der Vorlage.",
              "",
              "Amadron braucht Luft im Tablet und verkauft noch mehr: einen Eimer Öl für einen Smaragd, und es kauft deine Brennstoffe, zum Beispiel 1 000 mB LPG oder 4 000 mB Diesel für je einen Smaragd. Die Montageprogramme aus Stufe 3 kommen ebenfalls von dort.",
          ],
          tasks=[task_item("pneumaticcraft:pcb_blueprint", 1)],
          rewards=[reward_item("minecraft:emerald", 8), reward_xp(8)],
          deps=["plastic"], icon="pneumaticcraft:amadron_tablet"),

    quest("empty_pcb", 0, 18, "&9Presse leere Platinen",
          subtitle="Drei auf einmal, bei 1,5 Bar.",
          description=[
              "Zwei &6Redstone-Fackeln&r, drei &6Gold- oder Kupferklumpen&r und eine &6Kunststoffplatte&r in der Druckkammer bei &e1,5 Bar&r ergeben drei &6Leere Platinen&r (Empty PCB).",
              "",
              pic("pneumaticcraft:empty_pcb"),
              "",
              "Kupferklumpen sind das billigere Kabel, du bekommst sie aus Kupferbarren an der Werkbank. Mach gleich ein Dutzend Platinen, denn beim Ätzen geht noch etwas schief.",
          ],
          tasks=[task_item("pneumaticcraft:empty_pcb", 6)],
          rewards=[reward_item("minecraft:copper_ingot", 16), reward_xp(5)],
          deps=["plastic", "chamber"]),

    quest("uv_box", 2.5, 16, "&9Belichte im UV-Lichtkasten",
          subtitle="Zehn Minuten für hundert Prozent.",
          description=[
              "Drei &6Redstone-Lampen&r oben, in der Mitte &6Druckeisen&r, die &6Platinen-Vorlage&r und ein &6Druckluftrohr&r, unten drei Druckeisen ergeben den &6UV-Lichtkasten&r (UV Light Box). Er braucht Luft.",
              "",
              "Leg eine leere Platine hinein. Nach &e10 Minuten&r ist sie zu 100 Prozent belichtet und das Ätzen klappt sicher. Du kannst früher abbrechen, der Schieberegler setzt die Schwelle, dann steigt die Fehlerquote. Am Anfang geht es schnell, zum Ende hin zäh.",
              "",
              "&6Geschwindigkeits-Upgrades&r lassen die Lampen heller leuchten und belichten schneller. Mit einem &6Spender-Upgrade&r wirft er fertige Platinen in Richtung des Upgrades aus, zum Beispiel direkt ins Ätzbecken.",
          ],
          tasks=[task_item("pneumaticcraft:uv_light_box", 1)],
          rewards=[reward_item("minecraft:redstone_lamp", 3), reward_table("s2_common"), reward_xp(8)],
          deps=["blueprint"]),

    quest("etching", 2.5, 18, "&9Ätze die Platine",
          subtitle="Ätzsäure aus der Kammer, ein Becken aus Obsidian.",
          description=[
              "&eÄtzsäure&r (Etching Acid): ein &6Eimer flüssiger Kunststoff&r, zwei &6Verrottetes Fleisch&r, zwei &6Spinnenaugen&r und zwei &6Schwarzpulver&r in der Druckkammer bei 1 Bar ergeben einen Eimer. &eÄtzbecken&r (Etching Tank): zwei &6Obsidian&r um eine &6Glasscheibe&r oben, ein &6Kleiner Tank&r zwischen zwei &6Verstärkten Ziegelmauern&r, unten drei &6Verstärkte Ziegelstufen&r.",
              "",
              "Füll die Säure ins Becken und leg bis zu 25 belichtete Platinen hinein. Ohne Hitze dauert eine Platine &e150 Sekunden&r, geheizt über 50 Grad bis zu 30 Sekunden, dann wird aber langsam Säure verbraucht. Gelungene &6Unbestückte Platinen&r (Unassembled PCB) landen rechts oben, &6Fehlplatinen&r rechts unten.",
              "",
              "Fehlplatinen werden im &6Schmelzofen&r wieder zu leeren Platinen. Zum Automatisieren: Unbestückte von der Seite abziehen, Fehlplatinen oben oder unten.",
          ],
          tasks=[task_item("pneumaticcraft:etching_tank", 1), task_item("pneumaticcraft:unassembled_pcb", 2)],
          rewards=[reward_item("minecraft:obsidian", 4), reward_table("s2_common"), reward_xp(8)],
          deps=["empty_pcb", "uv_box"], icon="pneumaticcraft:etching_tank"),

    quest("pcb", 5.5, 17, "&9&lSetz die Platine zusammen",
          subtitle="Transistoren, Kondensatoren, fertig.",
          description=[
              "Zurück in die Druckkammer, je bei &e1 Bar&r: drei &6Klumpen&r, ein &6Redstone&r und eine &6Kunststoffplatte&r ergeben einen &6Transistor&r, zwei Klumpen, ein &6Schleimball&r und eine Kunststoffplatte einen &6Kondensator&r. An der Werkbank: eine &6Unbestückte Platine&r in der Mitte, zwei Transistoren oben und unten, zwei Kondensatoren links und rechts ergeben die &6Platine&r (Printed Circuit Board).",
              "",
              pic("pneumaticcraft:printed_circuit_board"),
              "",
              "Die Platine ist das Bauteil, mit dem die höheren Maschinen beginnen. In Stufe 2 steckt sie in der &6Modul-Erweiterungskarte&r (Platine, vier Kunststoffplatten, vier Redstone, ergibt vier), die dem Sicherheitsventil, dem Regler und der Druckanzeige ein Fenster mit genauer Schwelle gibt. In Stufe 3 braucht sie jede Drohne, der Programmierer, die Montagestraße und die fortgeschrittenen Kompressoren.",
              "",
              "&eKronwerke:&r Wer jetzt eine Platinenlinie aufbaut (Kammer, Lichtkasten, Becken, Schmelzofen für die Fehlplatinen), hat am ersten Tag von Stufe 3 die Teile für die Montagestraße fertig.",
          ],
          tasks=[task_item("pneumaticcraft:printed_circuit_board", 2)],
          rewards=[reward_table("s2_rare"), reward_item("pneumaticcraft:module_expansion_card", 4), reward_xp(20)],
          deps=["etching"], icon="pneumaticcraft:printed_circuit_board", size=2.5, shape="gear"),

    quest("outlook", 8.5, 17, "&dAusblick auf Stufe 3",
          subtitle="Montagestraße, Drohnen, Strom.",
          description=[
              "Mit &6Stufe 3&r öffnet PneumaticCraft seine zweite Hälfte. Die &6Montagestraße&r (Controller, Plattform, Bohrer, Laser, zwei Ein- und Ausgabearme) baut fortgeschrittene Rohre für 20 Bar, das verstärkte Kammerventil und bestückt Platinen ohne Lichtkasten. Ihre Programme kaufst du bei Amadron.",
              "",
              "Der &6Fortgeschrittene Luftkompressor&r macht 50 mL pro Tick statt 10, wird dabei heiß und braucht Kühlkörper. Dazu kommen &6Drohnen&r, der &6Programmierer&r mit seinen Puzzleteilen, der Programmierbare Controller, die Sicherheitsstation und der Universalsensor.",
              "",
              "&eRezept auf Kronwerke:&r Der &6Flux-Kompressor&r und der &6Druckluft-Dynamo&r, die Brücken zu Strom, brauchen statt der Platine einen &6Einfachen Steuerschaltkreis&r von Mekanism, dazu ein fortgeschrittenes Rohr und einen Turbinenrotor. Die &6Drohne&r bekommt unter ihre Platine ein &6Präzisionsgetriebe&r von Create, drei Turbinenrotoren drum herum.",
              "",
              "Die &6Druckluftrüstung&r mit Düsenstiefeln und die Minigun warten bis Stufe 4. Alles andere aus diesem Kapitel bleibt die Grundlage: Druck, Hitze, Kunststoff und Platinen brauchst du dort nur in größeren Mengen.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(10)],
          deps=["pcb"], icon="pneumaticcraft:turbine_rotor", optional=True),
]

images = [
    banner("pneumaticcraft/title", "PneumaticCraft", 9, -5, height=1.75, kind="title", colour="water"),
    banner("pneumaticcraft/air", "Druckluft", 6.5, -2.7, height=0.9, colour="water"),
    banner("pneumaticcraft/chamber", "Die Druckkammer", 4, 3.3, height=0.9, colour="stone"),
    banner("pneumaticcraft/tools", "Werkzeug", 16.5, 3.3, height=0.9, colour="brass"),
    banner("pneumaticcraft/oil", "Öl und Raffinerie", 6.5, 7.3, height=0.9, colour="stone"),
    banner("pneumaticcraft/heat", "Hitze", 17.5, 7.3, height=0.9, colour="brass"),
    banner("pneumaticcraft/plastic", "Kunststoff", 1.5, 11.3, height=0.9, colour="water"),
    banner("pneumaticcraft/machines", "Maschinen", 8.5, 11.3, height=0.9, colour="brass"),
    banner("pneumaticcraft/upgrades", "Upgrades", 15, 11.3, height=0.9, colour="magic"),
    banner("pneumaticcraft/pcb", "Die Platine", 4, 15.3, height=0.9, colour="water"),
]

chapter(C, "PneumaticCraft", "pneumaticcraft:air_compressor", "tech", quests, shape="circle", order=60, stage=2,
        subtitle=["Stufe 2: Druckeisen, die Druckkammer, Öl und Hitze, Kunststoff und die erste Platine."], images=images)
