"""PneumaticCraft in stage 3: the assembly line (controller, IO units, drill, laser, platform,
the traded programs), advanced pressure tubes, the tier 2 compressors (advanced air and liquid,
flux and dynamo with their Kronwerke recipes, electrostatic, thermal, solar), PCBs by laser,
the programmer, puzzle pieces and the first drone (Kronwerke: precision mechanism), the ready-made
drones and logistics frames, aerial interface, universal sensor, security station, programmable
controller, spawner extractor, vacuum trap and pressurized spawner. Compressed iron, the basic
compressors, the pressure chamber, oil, plastic and the first PCB are in the stage 2 chapter
pneumaticcraft.py and only referenced. Pneumatic armor, minigun and micromissiles are stage 4
and only named. Recipes follow kubejs/server_scripts/kronwerke/added.js."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_advancement, reward_item,
                  reward_table, reward_xp, banner, img, item_texture)

C = "pneumaticcraft_advanced"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


quests = [
    # ---- Die Montagestrasse ---------------------------------------------------
    quest("controller", 0, 1, "&b&lBau einen Assembly Controller",
          subtitle="Das Gehirn der Montagestraße.",
          description=[
              "&eRezept:&r oben ein &6Printed Circuit Board&r, in der Mitte ein &6Pressure Tube&r und zwei weitere PCBs, unten drei &6Compressed Iron Ingots&r.",
              "",
              "Mit &6Stufe 3 (Stahlwerk)&r öffnet PneumaticCraft seine zweite Ebene: die &eMontagestraße&r (Assembly System), Rohre und Kompressoren für &e20 bar&r, und die &eDrohnen&r. Alles davon beginnt hier, denn Advanced Pressure Tubes gibt es nur aus der Montagestraße.",
              "",
              "Was du mitbringen solltest, steht im Kapitel &bPneumaticCraft&r: Compressed Iron, einen laufenden Air Compressor, die Druckkammer, Plastik und drei fertige PCBs. Der Controller ist die einzige Maschine der Straße, die Luft braucht. Ein Rohr an ihn, und die ganze Straße läuft.",
              "",
              "&cNoch gesperrt:&r Die &6Pneumatic Armor&r, die &6Minigun&r und die &6Micromissiles&r kommen in Stufe 4.",
          ],
          tasks=[task_item("pneumaticcraft:assembly_controller", 1)],
          rewards=[reward_item("pneumaticcraft:ingot_iron_compressed", 16), reward_table("s3_common")],
          icon="pneumaticcraft:assembly_controller", size=2.0, shape="hexagon"),

    quest("programs", 2.5, -0.5, "&eKauf die Assembly Programs",
          subtitle="Drill und Laser, für Smaragde.",
          description=[
              "Die Programme kann niemand craften. Du kaufst sie beim &6Pressure Mechanic&r, einem Dorfbewohner mit eigenem Haus in Dörfern, oder über das &6Amadron Tablet&r: &eAssembly Program: Drill&r und &eAssembly Program: Laser&r kosten je &68 Smaragde&r, &eDrill & Laser&r kostet 14.",
              "",
              "Das &6Amadron Tablet&r (7 Plastic Sheets, ein GPS Tool, ein Air Canister, danach aufladen) bindest du per Rechtsklick an eine Kiste. In der Kiste liegen die Smaragde, eine Drohne holt sie ab, eine zweite bringt die Ware. Gleich dort gibt es auch den &6PCB Blueprint&r.",
              "",
              "&eTipp:&r Ein arbeitsloser Dorfbewohner neben einer &6Charging Station&r wird von selbst zum Pressure Mechanic. Dann sparst du dir die Lieferdrohnen.",
              "",
              "Das Programm &eDrill & Laser&r macht nicht beides, sondern nur Rezepte mit zwei Schritten, zum Beispiel vom Compressed Iron Block direkt zum Advanced Pressure Tube.",
          ],
          tasks=[task_item("pneumaticcraft:assembly_program_drill", 1), task_item("pneumaticcraft:assembly_program_laser", 1)],
          rewards=[reward_item("minecraft:emerald", 8), reward_xp(5)],
          deps=["controller"], icon="pneumaticcraft:assembly_program_laser"),

    quest("platform", 2.5, 1, "&bBau eine Assembly Platform",
          subtitle="Der Werktisch in der Mitte.",
          description=[
              "&eRezept:&r zwei &6Pneumatic Cylinders&r in die oberen Ecken, drei &6Plastic Sheets&r in die Mitte, unten Compressed Iron, &6PCB&r, Compressed Iron.",
              "",
              "Die Plattform hält das Werkstück fest, während Bohrer und Laser arbeiten. Alle anderen Maschinen müssen sie erreichen, also kommt sie in die Mitte.",
              "",
              "Einen &6Pneumatic Cylinder&r baust du aus sechs Plastic Sheets, zwei Compressed Iron und einem Cannon Barrel, und bekommst gleich zwei. Die ganze Straße braucht 14 Zylinder, also sieben Rezepte.",
          ],
          tasks=[task_item("pneumaticcraft:assembly_platform", 1)],
          rewards=[reward_item("pneumaticcraft:plastic", 8), reward_xp(5)],
          deps=["controller"]),

    quest("io_units", 5, -0.5, "&bBau zwei Assembly IO Units",
          subtitle="Ein Arm, der hineinlegt, einer, der herausnimmt.",
          description=[
              "&eRezept:&r ein &6Hopper&r (Import) oder ein &6Dropper&r (Export) oben links, drei &6Pneumatic Cylinders&r, unten Compressed Iron, &6PCB&r, Compressed Iron. Eine Import Unit wird an der Werkbank ohne Zutat zur Export Unit und zurück.",
              "",
              "Die Straße braucht &egenau zwei&r: eine &9blaue&r Import Unit, die Werkstücke aus einer Kiste auf die Plattform legt, und eine &6orange&r Export Unit, die das Ergebnis in eine Kiste räumt. Die Arme greifen auch &ediagonal&r, Kiste und Plattform müssen also nur in Reichweite stehen.",
          ],
          tasks=[task_item("pneumaticcraft:assembly_io_unit_import", 1), task_item("pneumaticcraft:assembly_io_unit_export", 1)],
          rewards=[reward_item("pneumaticcraft:pneumatic_cylinder", 4), reward_xp(5)],
          deps=["platform"], icon="pneumaticcraft:assembly_io_unit_import"),

    quest("drill", 5, 1, "&bBau einen Assembly Drill",
          subtitle="Ein Diamantbohrer für die härtesten Blöcke.",
          description=[
              "&eRezept:&r ein &6Diamant&r oben links, drei &6Pneumatic Cylinders&r, unten Compressed Iron, &6PCB&r, Compressed Iron.",
              "",
              "Der Bohrer greift &cnicht&r diagonal, er muss direkt neben der Plattform stehen. Mit dem Programm &eDrill&r macht er aus einem &6Compressed Iron Block&r 20 Pressure Chamber Valves, aus einem Solar Wafer eine Solar Cell und aus Redstone zwei roten Farbstoff.",
          ],
          tasks=[task_item("pneumaticcraft:assembly_drill", 1)],
          rewards=[reward_item("minecraft:diamond", 2), reward_xp(5)],
          deps=["platform"]),

    quest("laser", 5, 2.5, "&bBau einen Assembly Laser",
          subtitle="Schneidet, was der Bohrer nicht kann.",
          description=[
              "&eRezept:&r ein &6rotes Glas&r (Red Stained Glass) oben links, drei &6Pneumatic Cylinders&r, unten Compressed Iron, &6PCB&r, Compressed Iron.",
              "",
              "Auch der Laser muss direkt an die Plattform. Mit dem Programm &eLaser&r macht er aus 20 Pressure Chamber Valves acht &6Advanced Pressure Tubes&r, aus einem Empty PCB ein &6Unassembled PCB&r und aus einem Quarzblock vier Aphorism Tiles.",
          ],
          tasks=[task_item("pneumaticcraft:assembly_laser", 1)],
          rewards=[reward_item("minecraft:red_stained_glass", 4), reward_xp(5)],
          deps=["platform"]),

    quest("first_run", 7.5, 1, "&b&lLass die Straße laufen",
          subtitle="Ein Block hinein, zwanzig Ventile heraus.",
          description=[
              "&eAufbau:&r Plattform in die Mitte, Drill und Laser direkt daneben, die beiden IO Units an die freien Seiten, dahinter je eine Kiste. Der Controller steht irgendwo in der Reihe, alle Maschinen müssen sich &ewaagerecht berühren&r. Nur der Controller bekommt ein Pressure Tube.",
              "",
              "Leg das Programm &eDrill&r in den Controller und einen &6Compressed Iron Block&r in die Eingangskiste. Die Import Unit legt ihn auf die Plattform, der Bohrer arbeitet, die Export Unit räumt &e20 Pressure Chamber Valves&r in die Ausgangskiste.",
              "",
              "Die Anzeige auf dem Controller sagt dir, was fehlt. Rot heißt meistens: eine Maschine fehlt, steht doppelt oder nicht in der Reihe.",
          ],
          tasks=[task_item("pneumaticcraft:pressure_chamber_valve", 20)],
          rewards=[reward_item("pneumaticcraft:compressed_iron_block", 2), reward_table("s3_common"), reward_xp(10)],
          deps=["programs", "io_units", "drill", "laser"], icon="pneumaticcraft:assembly_program_drill", size=1.5, shape="gear"),

    # ---- Druck der zweiten Stufe ----------------------------------------------
    quest("advanced_tube", 10.5, 1.5, "&3&lMach Advanced Pressure Tubes",
          subtitle="Rohre für 20 bar.",
          description=[
              "Programm &eLaser&r in den Controller, &620 Pressure Chamber Valves&r in die Eingangskiste, heraus kommen &68 Advanced Pressure Tubes&r. Mit dem Programm &eDrill & Laser&r geht es direkt vom &6Compressed Iron Block&r zu den acht Rohren.",
              "",
              pic("pneumaticcraft:advanced_pressure_tube"),
              "",
              "Ein normales Rohr hält 5 bar, ein Reinforced Tube 10. Das Advanced Tube hält &e20 bar&r und fasst 4 000 mL statt 1 000. Jede Maschine dieser Stufe braucht es als Zutat: die großen Kompressoren, der Dynamo, der Pressurized Spawner, das Aerial Interface.",
              "",
              "&eTipp:&r Ein Block wird zu acht Rohren. Mach gleich vier Blöcke durch, 32 Rohre brauchst du schnell.",
          ],
          tasks=[task_item("pneumaticcraft:advanced_pressure_tube", 8)],
          rewards=[reward_item("pneumaticcraft:advanced_pressure_tube", 8), reward_table("s3_common"), reward_xp(10)],
          deps=["first_run"], icon="pneumaticcraft:advanced_pressure_tube", size=1.5, shape="hexagon"),

    quest("adv_air", 13, 0, "&3Bau einen Advanced Air Compressor",
          subtitle="Fünfmal so viel Luft, und er wird heiß.",
          description=[
              "&eRezept:&r sechs &6Compressed Iron&r, ein &6Advanced Pressure Tube&r rechts in der Mitte und dein alter &6Air Compressor&r unten in der Mitte. Der Kompressor wird aufgewertet, du brauchst keinen neuen.",
              "",
              "Er macht &e50 mL Luft pro Tick&r statt 10 und hält &e20 bar&r. Speed Upgrades machen ihn schneller, aber er &cmuss gekühlt&r werden: Je heißer er wird, desto weniger Luft kommt heraus, bis gar nichts mehr.",
              "",
              "&eKühlen:&r Ein &6Heat Sink&r (drei Eisengitter, zwei Compressed Iron, ein Kupfer) an jede freie Seite leitet die Wärme in die Luft. Heat Pipes bringen weitere Kühlkörper heran, ein Air Grate Module an einem Rohr daneben macht sie wirksamer. Offene Seiten zur Luft kühlen von selbst ein bisschen.",
          ],
          tasks=[task_item("pneumaticcraft:advanced_air_compressor", 1)],
          rewards=[reward_item("pneumaticcraft:heat_sink", 4), reward_table("s3_common"), reward_xp(10)],
          deps=["advanced_tube"], icon="pneumaticcraft:advanced_air_compressor"),

    quest("adv_liquid", 13, 3, "&3Bau einen Advanced Liquid Compressor",
          subtitle="Diesel, Kerosin oder LPG zu 20 bar.",
          description=[
              "&eRezept:&r sechs &6Compressed Iron&r, zwei &6Advanced Pressure Tubes&r in der Mitte rechts und dein &6Liquid Compressor&r unten in der Mitte.",
              "",
              "Er verbrennt flüssigen Brennstoff aus der Raffinerie (Kapitel &bPneumaticCraft&r) und macht &e50 mL pro Tick&r. Wie der Luftkompressor muss er gekühlt werden, Heat Sinks an die freien Seiten.",
              "",
              "Wer eine Raffinerie hat, fährt mit diesem Kompressor am besten: Er läuft, solange der Tank voll ist, Tag und Nacht.",
          ],
          tasks=[task_item("pneumaticcraft:advanced_liquid_compressor", 1)],
          rewards=[reward_item("pneumaticcraft:heat_sink", 4), reward_xp(10)],
          deps=["advanced_tube"], icon="pneumaticcraft:advanced_liquid_compressor", optional=True),

    quest("flux", 15.5, 0, "&dBau einen Flux Compressor",
          subtitle="Strom wird zu Luft.",
          description=[
              "&eRezept auf Kronwerke:&r oben Redstone, &6Compressed Iron Gear&r, &6Einfacher Steuerschaltkreis&r von Mekanism. Mitte: Redstoneblock, &6Turbine Rotor&r, &6Advanced Pressure Tube&r. Unten Redstone, &6Schmelzofen&r (Blast Furnace), noch ein Steuerschaltkreis.",
              "",
              "Der Flux Compressor nimmt &dFE&r aus jedem Kabel des Packs und macht daraus Druckluft: &e40 FE pro Tick&r, aus 100 FE werden 40 mL Luft. Er speichert 100 000 FE und nimmt Strom doppelt so schnell auf, wie er ihn verbraucht. Auch er muss gekühlt werden.",
              "",
              "Den Steuerschaltkreis gibt es nur aus der Infusionsanlage mit einer Elektronenröhre, siehe Kapitel &5Mekanism&r. So hängt PneumaticCraft am Stromnetz des Servers: Ein Mekanism-Kabel oder ein Flux Point an diesen Block, und die Luft kommt aus der Steckdose.",
          ],
          tasks=[task_item("pneumaticcraft:flux_compressor", 1)],
          rewards=[reward_item("mekanism:basic_control_circuit", 2), reward_table("s3_common"), reward_xp(10)],
          deps=["adv_air"], icon="pneumaticcraft:flux_compressor"),

    quest("dynamo", 15.5, 3, "&dBau einen Pneumatic Dynamo",
          subtitle="Luft wird zu Strom.",
          description=[
              "&eRezept auf Kronwerke:&r oben ein &6Advanced Pressure Tube&r, in der Mitte Gear, Compressed Iron, Gear, unten Compressed Iron, &6Einfacher Steuerschaltkreis&r, Compressed Iron.",
              "",
              "Der Dynamo ist der Flux Compressor rückwärts: aus 100 mL Luft werden &e40 FE&r, bei &e40 FE pro Tick&r im Grundzustand und einem Ausgang von 80 FE pro Tick. Speed Upgrades erhöhen beides. Auch er wird warm und braucht Heat Sinks.",
              "",
              "Wann lohnt das? Wenn du mit Elektrostatik oder Sonne mehr Luft hast als Maschinen. Ein Dynamo neben einem Energie-Würfel macht aus dem Überschuss Strom für alle anderen Mods.",
          ],
          tasks=[task_item("pneumaticcraft:pneumatic_dynamo", 1)],
          rewards=[reward_item("pneumaticcraft:compressed_iron_gear", 4), reward_xp(10)],
          deps=["advanced_tube"], icon="pneumaticcraft:pneumatic_dynamo", optional=True),

    quest("electrostatic", 18, 0, "&eBau einen Electrostatic Compressor",
          subtitle="Ein Blitz, 200 000 mL Luft.",
          description=[
              "&eRezept:&r vier &6Eisengitter&r in die Ecken, drei &6Plastic Sheets&r oben und an den Seiten, ein &6Turbine Rotor&r in die Mitte, der &6Advanced Air Compressor&r unten.",
              "",
              "Jeder Blitzeinschlag bringt &e200 000 mL&r Luft auf einmal. Der Kompressor erzeugt die Blitze selbst, bei klarem Himmel fast nie, bei Regen öfter, im &eGewitter&r sehr oft. Echte Blitze zählen nicht.",
              "",
              "&eAufbau:&r Ein Gitter aus &6Eisengittern&r oder Blitzableitern, mit dem Kompressor verbunden, bis 5 Blöcke zur Seite und 5 nach oben und unten, erhöht die Chance. Bis zu 10 Gitter direkt darüber bilden einen Blitzableiter. Eisengitter &edirekt darunter&r leiten je 10 000 mL Überdruck ab, damit er nach dem Einschlag nicht platzt. Zwei bis drei reichen bei einem Kompressor.",
          ],
          tasks=[task_item("pneumaticcraft:electrostatic_compressor", 1)],
          rewards=[reward_item("minecraft:iron_bars", 32), reward_table("s3_common"), reward_xp(10)],
          deps=["adv_air"], icon="pneumaticcraft:electrostatic_compressor", optional=True),

    quest("thermal", 18, 3, "&cBau einen Thermal Compressor",
          subtitle="Heiß auf der einen Seite, kalt auf der anderen.",
          description=[
              "&eRezept:&r vier &6Compressed Iron&r in die Ecken, &6Pressure Tubes&r oben und unten, zwei &6schwere Druckplatten&r (Eisen) links und rechts, ein &6Air Compressor&r in die Mitte.",
              "",
              "Er macht Luft aus einem &eTemperaturunterschied&r zwischen zwei gegenüberliegenden Seiten: &cLava&r auf der einen, &bPacked Ice&r auf der anderen. Nord-Süd und Ost-West sind getrennt, du kannst also zwei Paare anlegen. Je größer der Unterschied, desto mehr Luft.",
              "",
              "Die Wärme gleicht sich mit der Zeit aus, Eis schmilzt nicht, verliert aber seine Kälte. Nutz ihn für die &eAbwärme&r eines Advanced Compressors oder der heißen Seite eines Vortex Tube, dann holst du etwas zurück, was sonst in Heat Sinks verpufft. Ein Redstone-Signal schaltet ihn ab und hält den Unterschied fest.",
          ],
          tasks=[task_item("pneumaticcraft:thermal_compressor", 1)],
          rewards=[reward_item("minecraft:packed_ice", 16), reward_xp(10)],
          deps=["advanced_tube"], icon="pneumaticcraft:thermal_compressor", optional=True),

    quest("solar_cell", 20.5, 0, "&6Mach drei Solar Cells",
          subtitle="Lapis, Wasser, Amethyst und der Bohrer.",
          description=[
              "&e1.&r &6Upgrade Matrix&r: ein Lapislazuli mit 1 000 mB Wasser in der &6Thermopneumatic Processing Plant&r bei 2 bar ergibt vier Matrizen.",
              "&e2.&r &6Solar Wafer&r: eine Matrix und eine &6Amethystscherbe&r in der Druckkammer bei &e2,5 bar&r.",
              "&e3.&r &6Solar Cell&r: der Wafer mit dem Programm &eDrill&r durch die Montagestraße.",
              "",
              "Du brauchst drei Zellen für den Kompressor und weitere, um ihn zu reparieren, falls er überhitzt. Mach also gleich sechs.",
              "",
              "&eTipp:&r Die Upgrade Matrix ersetzt in jedem Upgrade-Rezept den Lapislazuli, aus einem Lapis werden so vier Upgrades statt einem.",
          ],
          tasks=[task_item("pneumaticcraft:solar_cell", 3)],
          rewards=[reward_item("minecraft:amethyst_shard", 8), reward_item("minecraft:lapis_lazuli", 16), reward_xp(10)],
          deps=["advanced_tube"], icon="pneumaticcraft:solar_cell", optional=True),

    quest("solar", 20.5, 3, "&6Bau einen Solar Compressor",
          subtitle="Luft aus Sonne, aber nur bei 350 Grad.",
          description=[
              "&eRezept:&r drei &6Solar Cells&r oben, &6PCB&r, &6Compressed Iron Gear&r, &6PCB&r in der Mitte, unten &6Advanced Pressure Tube&r, &6Compressed Iron Block&r, Advanced Pressure Tube.",
              "",
              "Er braucht &efreien Himmel&r und arbeitet nicht nachts, nicht drinnen und nicht im Gewitter. Das Besondere: Er macht Wärme mit, und er läuft erst richtig, wenn er &eheiß&r ist. Volle Leistung bei &c350 °C&r, ab &c425 °C&r überhitzt er und geht kaputt. Dann reparierst du ihn mit Solar Cells.",
              "",
              "&eEinstellen:&r Heat Sinks und Heat Pipes nehmen Wärme weg, ein Vortex Tube kann welche dazugeben. Ziel ist ein Gleichgewicht knapp unter 425 Grad. Solange er still steht, hält er seine Temperatur von selbst.",
          ],
          tasks=[task_item("pneumaticcraft:solar_compressor", 1)],
          rewards=[reward_item("pneumaticcraft:solar_cell", 2), reward_table("s3_uncommon"), reward_xp(15)],
          deps=["solar_cell"], icon="pneumaticcraft:solar_compressor", optional=True),

    # ---- Leiterplatten -------------------------------------------------------
    quest("pcb_laser", 5, 5.5, "&aLaser dir Unassembled PCBs",
          subtitle="Kein UV-Kasten, keine Säure mehr.",
          description=[
              "Programm &eLaser&r in den Controller, &6Empty PCBs&r in die Eingangskiste. Jedes wird zu einem &6Unassembled PCB&r, ohne UV Light Box, ohne Etching Tank und ohne Fehlversuche.",
              "",
              "Empty PCBs kommen weiter aus der Druckkammer: zwei Redstone-Fackeln, drei Nuggets (Gold oder Kupfer) und ein Plastic Sheet bei 1,5 bar ergeben drei. Mit zwei &6Transistoren&r und zwei &6Kondensatoren&r um das Unassembled PCB wird daraus das fertige &6Printed Circuit Board&r, wie im Kapitel &bPneumaticCraft&r.",
              "",
              "Der Laser ist bequem und schnell genug für ein Dutzend Platinen. Für hunderte ist die Säure mit Heizung am Ende schneller, siehe nächste Aufgabe.",
          ],
          tasks=[task_item("pneumaticcraft:unassembled_pcb", 8)],
          rewards=[reward_item("pneumaticcraft:transistor", 8), reward_item("pneumaticcraft:capacitor", 8), reward_xp(10)],
          deps=["laser"], icon="pneumaticcraft:unassembled_pcb"),

    quest("pcb_mass", 7.5, 5.5, "&a&lMach Leiterplatten in Serie",
          subtitle="Sechzehn PCBs, dann reicht es für alles hier.",
          description=[
              "Zähl zusammen, was dieses Kapitel an &6Printed Circuit Boards&r will: Programmer, Solar Compressor, Security Station, Programmable Controller, jede Drohne, jede Charge Puzzleteile. Sechzehn sind ein guter Anfang.",
              "",
              "&eWenn die Säure schneller sein soll:&r Ein &6Etching Tank&r ohne Wärme braucht 150 Sekunden pro Platine, aber ätzt 25 auf einmal. Geheizt sinkt die Zeit auf &e30 Sekunden&r, dafür verbraucht er dabei etwas Säure. Speed Upgrades in der &6UV Light Box&r drücken die 10 Minuten Belichtung.",
              "",
              "&eFehlversuche:&r Ein &6Failed PCB&r wird im Schmelzofen (Blast Furnace) wieder zum Empty PCB. Ein Trichter unter dem Etching Tank in einen Blast Furnace und zurück, und nichts geht verloren.",
          ],
          tasks=[task_item("pneumaticcraft:printed_circuit_board", 16)],
          rewards=[reward_item("pneumaticcraft:printed_circuit_board", 4), reward_table("s3_uncommon"), reward_xp(15)],
          deps=["pcb_laser"], icon="pneumaticcraft:printed_circuit_board", size=1.5, shape="diamond"),

    # ---- Drohnen programmieren -----------------------------------------------
    quest("programmer", 5, 9.5, "&5&lBau einen Programmer",
          subtitle="Hier werden Drohnen programmiert.",
          description=[
              "&eRezept:&r oben roter Farbstoff, eine &6schwarze Glasscheibe&r, roter Farbstoff. Mitte: &6Turbine Rotor&r, &6PCB&r, Turbine Rotor. Unten zwei &6Plastic Sheets&r in die Ecken.",
              "",
              "Der Programmer braucht &ekeine Luft&r. Du setzt Programme aus &6Puzzleteilen&r zusammen, die ineinandergreifen wie ein Puzzle, und schreibst sie mit dem Pfeil auf eine Drohne im Slot oben rechts. Die Teile dafür liegen in deinem Inventar oder in einer Kiste direkt am Programmer.",
              "",
              "&eIm Fenster:&r Links die Fläche für dein Programm, rechts die Ablage mit allen Teilen (mit &eLeertaste&r aufklappen und suchen), unten die Schwierigkeit: Easy zeigt nur die wichtigsten Teile. Fang damit an.",
          ],
          tasks=[task_item("pneumaticcraft:programmer", 1)],
          rewards=[reward_item("pneumaticcraft:turbine_rotor", 2), reward_table("s3_common"), reward_xp(10)],
          deps=["pcb_laser"], icon="pneumaticcraft:programmer", size=1.5, shape="hexagon"),

    quest("puzzles", 2.5, 8.5, "&5Mach Programming Puzzles",
          subtitle="Acht Plastik, ein PCB, acht Teile.",
          description=[
              "&eRezept:&r acht &6Plastic Sheets&r um ein &6Printed Circuit Board&r ergeben acht &6Programming Puzzles&r.",
              "",
              "Jedes Teil im Programm kostet beim Schreiben ein Puzzleteil. Überschreibst du die Drohne mit einem kürzeren Programm, bekommst du die Teile zurück. Ein einfaches Programm hat sechs bis zehn Teile, also mach gleich eine Kiste voll.",
          ],
          tasks=[task_item("pneumaticcraft:programming_puzzle", 16)],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 8), reward_xp(5)],
          deps=["programmer"]),

    quest("gps", 2.5, 10.5, "&5Bau GPS Tool und GPS Area Tool",
          subtitle="So sagst du der Drohne, wo.",
          description=[
              "&eRezept GPS Tool:&r eine Redstone-Fackel oben, Plastic Sheet, Glasscheibe, Plastic Sheet in der Mitte, Plastic Sheet, &6Diamant&r, Plastic Sheet unten. Zwei GPS Tools zusammen ergeben das &6GPS Area Tool&r.",
              "",
              "Das &6GPS Tool&r merkt sich mit Rechtsklick einen Block. Das &6Area Tool&r merkt sich zwei Ecken: Rechtsklick für die erste, Linksklick für die zweite, und zeigt den Bereich dazwischen an.",
              "",
              "Im Programmer klickst du mit dem Werkzeug auf ein &eArea&r-Teil, und die Koordinaten springen hinein. Linksklick mit dem Area Tool auf eine freie Stelle legt gleich ein neues Area-Teil an.",
          ],
          tasks=[task_item("pneumaticcraft:gps_tool", 1), task_item("pneumaticcraft:gps_area_tool", 1)],
          rewards=[reward_item("pneumaticcraft:plastic", 8), reward_xp(5)],
          deps=["programmer"], icon="pneumaticcraft:gps_area_tool"),

    quest("drone", 7.5, 9.5, "&d&lBau eine Drone",
          subtitle="Ein fliegender Roboter mit Präzisionsgetriebe.",
          description=[
              "&eRezept auf Kronwerke:&r drei &6Turbine Rotors&r oben und an den Seiten, ein &6Printed Circuit Board&r in der Mitte, unten ein &6Präzisionsgetriebe&r von Create. Fliegende Maschinen brauchen auf Kronwerke ein Getriebe, wie der Assembler von AE2.",
              "",
              pic("pneumaticcraft:drone"),
              "",
              "Das Präzisionsgetriebe entsteht auf dem Depot mit dem Einsatzgerät, siehe Kapitel &6Create: Messing&r. Frag die Create-Spieler, die machen die am laufenden Band.",
              "",
              "&eLaden:&r Eine Drohne läuft mit Luft, 1 mL pro Tick. Leg sie in eine &6Charging Station&r. Steck ein &6Dispenser Upgrade&r in die Station, dann wird sie zum Ladefeld: Jede Drohne mit wenig Luft fliegt von selbst zur nächsten Station mit Dispenser Upgrade im Umkreis von 80 Blöcken, tankt und arbeitet weiter.",
              "",
              "&cAchtung:&r Geht die Luft aus, fällt die Drohne und nimmt Fallschaden. Zerstört lässt sie sich als Item fallen. Mit einem Pneumatic Wrench nimmst du sie sauber auf.",
          ],
          tasks=[task_item("pneumaticcraft:drone", 1)],
          rewards=[reward_item("pneumaticcraft:dispenser_upgrade", 1), reward_table("s3_uncommon"), reward_xp(15)],
          deps=["programmer"], icon="pneumaticcraft:drone", size=2.0, shape="hexagon"),

    quest("pz_start", 0, 12.5, "&7Puzzleteil: Start",
          subtitle="Jedes Programm hat genau einen Anfang.",
          description=[
              "Zieh das Teil &eStart&r auf die Fläche. Hier beginnt die Drohne. Es muss genau einmal vorkommen, und alles, was folgen soll, wird &eunten&r angesteckt.",
              "",
              "Ein roter Rand an einem Teil heißt: Da fehlt etwas. Fahr mit der Maus darüber, der Tooltip sagt dir, was. Ist das letzte Teil abgearbeitet, fängt die Drohne wieder bei Start an.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 2)],
          deps=["puzzles"], icon="pneumaticcraft:programming_puzzle"),

    quest("pz_import", 2, 12.5, "&7Puzzleteil: Import from Inventory",
          subtitle="Die Drohne holt etwas aus einer Kiste.",
          description=[
              "&eImport from Inventory&r schickt die Drohne zur nächsten Kiste im angegebenen &eArea&r und lässt sie Gegenstände herausnehmen. Das Area-Teil kommt &erechts&r dran, ein &eItem Filter&r ebenfalls rechts.",
              "",
              "Filter rechts heißt: nur das. Filter links heißt: alles außer dem. Ohne Filter nimmt sie, was sie findet. Rechtsklick auf das Teil: Seite der Kiste und Höchstmenge. Ohne Inventory Upgrades trägt eine Drohne &eeinen Stapel&r.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 3)],
          deps=["pz_start"], icon="minecraft:hopper"),

    quest("pz_export", 4, 12.5, "&7Puzzleteil: Export to Inventory",
          subtitle="Die Drohne legt etwas in eine Kiste.",
          description=[
              "&eExport to Inventory&r ist das Gegenstück: Die Drohne fliegt zur nächsten Kiste im &eArea&r und legt ab, was sie trägt. Item Filter rechts für nur das, links für alles außer dem.",
              "",
              "Import und Export zusammen sind schon ein Programm: Start, Import aus Kiste A, Export in Kiste B. Die Drohne pendelt, bis A leer oder B voll ist, und wartet dann.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 3)],
          deps=["pz_import"], icon="minecraft:dropper"),

    quest("pz_goto", 6, 12.5, "&7Puzzleteil: Go to Location",
          subtitle="Flieg dorthin, dann weiter.",
          description=[
              "&eGo to Location&r schickt die Drohne zum nächsten erreichbaren Block im &eArea&r. Ist sie da, oder kommt sie nicht hin, geht es mit dem nächsten Teil weiter.",
              "",
              "Nützlich, um die Drohne nach der Arbeit an einen Warteplatz zu schicken statt über der Kiste zu schweben, oder um sie an einer Stelle vorbeizuführen, die sie sonst umfliegt.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 4)],
          deps=["pz_export"], icon="pneumaticcraft:gps_tool"),

    quest("pz_dig", 8, 12.5, "&7Puzzleteil: Dig Area",
          subtitle="Die Drohne gräbt einen Bereich aus.",
          description=[
              "&eDig Area&r baut jeden Block im &eArea&r ab. Was fällt, lässt sie liegen, dafür hängst du ein &ePick up Items&r-Teil dahinter oder stellst eine Sammeldrohne daneben.",
              "",
              "Lass sie vorher eine &6Spitzhacke&r importieren, sonst gräbt sie mit bloßen Händen, und das dauert. Mit Haken bei &eRequires digging tool&r gräbt sie nur mit Werkzeug. Rechtsklick auf das Teil: Schicht für Schicht, von oben oder von unten, und eine Höchstzahl an Blöcken pro Durchlauf.",
              "",
              "Ein Item Filter rechts sagt ihr, welche Blöcke sie abbauen darf. Bei Pflanzen filterst du nach dem Samen, den sie fallen lassen.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 4)],
          deps=["pz_goto"], icon="minecraft:iron_pickaxe"),

    quest("pz_place", 10, 12.5, "&7Puzzleteil: Place",
          subtitle="Die Drohne baut aus ihrem Inventar.",
          description=[
              "&ePlace&r setzt Blöcke aus dem Inventar der Drohne in den &eArea&r, zuerst die nächstgelegenen Stellen. Rechtsklick: Schicht für Schicht, von oben oder unten, zufällige Blöcke aus dem Inventar, und eine Höchstzahl.",
              "",
              "Import aus einer Kiste voller Bruchstein, Place in einen Bereich, zurück zu Start: eine Mauer, die sich von selbst baut. Mit einem Filter rechts setzt sie nur bestimmte Blöcke.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 5)],
          deps=["pz_dig"], icon="minecraft:bricks"),

    quest("pz_harvest", 12, 12.5, "&7Puzzleteil: Harvest",
          subtitle="Erntet reife Felder und Bäume.",
          description=[
              "&eHarvest&r erntet jede reife Pflanze und jeden Baum im &eArea&r. Aufsammeln tut sie nichts, dafür wieder &ePick up Items&r dahinter oder eine Sammeldrohne.",
              "",
              "Lass sie eine &6Hacke&r importieren, dann pflanzt sie &enach&r. Mit Haken bei &eRequires Hoe&r erntet sie nur mit Hacke und holt sich eine neue, wenn die alte bricht. Ein Filter rechts mit dem Samen bestimmt, welche Pflanze sie erntet.",
              "",
              "Das war die Grundausstattung. Alles weitere (Bedingungen, Schleifen, Flüssigkeiten, Kämpfen, Crafting) steht im Patchouli-Buch von PneumaticCraft unter Programming.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 6)],
          deps=["pz_place"], icon="minecraft:iron_hoe"),

    quest("first_program", 14.5, 12.5, "&d&lProgrammiere deine erste Drohne",
          subtitle="Start, Import, Dig. Mehr braucht es nicht.",
          description=[
              "&eDas Programm:&r Start, darunter &eImport from Inventory&r mit einem Area auf eine Kiste mit einer Schaufel und einem Item Filter auf die Schaufel (Haltbarkeit aus). Darunter &eDig Area&r mit einem Area auf ein Stück Erde oder Sand.",
              "",
              "Geladene Drohne in den Slot oben rechts, Pfeil drücken, Ton hören. Dann die Drohne irgendwo in der Nähe der Kiste in die Welt klicken und zusehen.",
              "",
              "&eWenn sie nichts tut:&r Hat sie Luft? Liegt die Schaufel wirklich in der Kiste im Area? Ist der Filter auf dieselbe Schaufel? Ein Rechtsklick mit einem GPS Tool auf die Drohne schickt sie zu dessen Koordinate, so testest du, ob sie überhaupt fliegt.",
              "",
              "Ab hier gilt: Wer eine Drohne programmieren kann, kann fast alles automatisieren. Rechtsklick mit Farbstoff färbt sie, damit du deine Flotte auseinanderhältst.",
          ],
          tasks=[task_advancement("pneumaticcraft:program_drone", "Eine Drohne programmieren")],
          rewards=[reward_item("pneumaticcraft:programming_puzzle", 16), reward_item("pneumaticcraft:speed_upgrade", 2), reward_table("s3_uncommon"), reward_xp(20)],
          deps=["pz_harvest"], icon="pneumaticcraft:drone", size=2.0, shape="gear"),

    # ---- Fertige Drohnen -------------------------------------------------------
    quest("frames", 10, 8.5, "&6Bau Logistics Frames",
          subtitle="Rahmen an die Kiste, fertig ist das Netz.",
          description=[
              "&eRezept:&r sieben &6Stöcke&r, ein &6Farbstoff&r in der Mitte und ein &6Logistics Core&r unten in der Mitte ergeben acht Rahmen. Der Core: acht &6Reinforced Brick Tiles&r um ein Redstone, ergibt zwei.",
              "",
              "Die Farbe bestimmt den Rahmen. &cRot, Passive Provider:&r bietet an, nur Anforderer holen ab. &5Lila, Active Provider:&r schiebt alles aktiv weg in Lager und Anforderer. &9Blau, Requester:&r fordert an, du stellst im Rahmen ein, wie viel vorrätig sein soll. &eGelb, Storage:&r nimmt von Active Providern an und gibt an Requester. &aGrün, Default Storage:&r wie Storage, aber zuletzt.",
              "",
              "Rahmen klebst du an jede Kiste oder jeden Tank, auch von anderen Mods. Rechtsklick mit dem Rahmen in der Hand oder mit dem &6Logistics Configurator&r (vier Compressed Iron, roter Farbstoff, Air Canister, Hebel) stellt Filter ein, Shift-Rechtsklick nimmt ihn ab.",
          ],
          tasks=[task_item("pneumaticcraft:logistics_frame_passive_provider", 1), task_item("pneumaticcraft:logistics_frame_requester", 1)],
          rewards=[reward_item("pneumaticcraft:logistics_core", 2), reward_xp(5)],
          deps=["drone"], icon="pneumaticcraft:logistics_frame_requester"),

    quest("logistics_drone", 12.5, 8.5, "&6Setz eine Logistics Drone ein",
          subtitle="Transport ohne eine Zeile Programm.",
          description=[
              "&eRezept:&r vier &6Turbine Rotors&r um einen &6Logistics Core&r. Kein PCB, kein Präzisionsgetriebe, kein Programm.",
              "",
              "Lade sie und setz sie mitten in deine Kisten. Sie bedient jeden Rahmen in einem Würfel von &e33 Blöcken&r Kantenlänge um ihren Startpunkt: holt bei Providern, bringt zu Requestern, räumt in Storage. Mehr kann sie nicht, mehr muss sie nicht.",
              "",
              "&eTipp:&r Speed Upgrades und Inventory Upgrades über die Charging Station (Pfeil über dem Slot) machen sie schneller und lassen sie mehr tragen. Im Requester-Rahmen setzt du eine Mindestmenge, sonst fliegt sie für jedes einzelne Stück.",
          ],
          tasks=[task_item("pneumaticcraft:logistics_drone", 1)],
          rewards=[reward_item("pneumaticcraft:logistics_frame_storage", 8), reward_table("s3_common"), reward_xp(10)],
          deps=["frames"], icon="pneumaticcraft:logistics_drone"),

    quest("harvesting_drone", 10, 10.5, "&aSetz eine Harvesting Drone ein",
          subtitle="Ein Bauer, der nie schläft.",
          description=[
              "&eRezept:&r vier &6Turbine Rotors&r um eine &6Feldfrucht&r, zum Beispiel Weizen.",
              "",
              "Sie erntet reife Pflanzen und Bäume in einem Würfel von &e17 Blöcken&r um ihren Startpunkt. Setz sie mit &eShift-Rechtsklick&r gegen eine Kiste, in der nur eine &6Hacke&r liegt, dann pflanzt sie nach und arbeitet nur mit Hacke. Gegen jeden anderen Block gesetzt, erntet sie ohne nachzupflanzen.",
              "",
              "Aufsammeln tut sie nichts. Dafür gibt es die &6Collector Drone&r (vier Rotoren um einen Trichter): gegen eine Kiste gesetzt sammelt sie alles im 17er-Würfel ein, was auf dem Boden liegt, und filtert auf das, was schon in der Kiste liegt.",
          ],
          tasks=[task_item("pneumaticcraft:harvesting_drone", 1)],
          rewards=[reward_item("pneumaticcraft:collector_drone", 1), reward_xp(10)],
          deps=["drone"], icon="pneumaticcraft:harvesting_drone", optional=True),

    quest("guard_drone", 12.5, 10.5, "&cSetz eine Guard Drone ein",
          subtitle="Ein Schwert aus der Kiste, dann Wache.",
          description=[
              "&eRezept:&r vier &6Turbine Rotors&r um ein &6Eisenschwert&r.",
              "",
              "Setz sie gegen eine Kiste mit einem Nahkampf-Schwert. Sie holt sich eins und greift jedes feindliche Monster an: &e16 Blöcke&r zur Seite, 8 nach oben, 5 nach unten. Weniger nach unten, damit sie nicht in jede Höhle teleportiert.",
              "",
              "Leg Ersatzschwerter in die Kiste. Bricht das letzte, kämpft sie mit bloßen Rotoren weiter, und das bringt wenig. In Stufe 4 bekommt sie ein Minigun Upgrade und Munition statt Schwert.",
          ],
          tasks=[task_item("pneumaticcraft:guard_drone", 1)],
          rewards=[reward_item("minecraft:iron_sword", 2), reward_xp(10)],
          deps=["drone"], icon="pneumaticcraft:guard_drone", optional=True),

    # ---- Steuerung und Schutz -------------------------------------------------
    quest("aerial_interface", 16, 8.5, "&d&lBau ein Aerial Interface",
          subtitle="Eine Kiste, die direkt in deine Taschen führt.",
          description=[
              "&eRezept:&r vier &6Pressure Chamber Walls&r in die Ecken, ein &6Omnidirectional Hopper&r oben, zwei &6Enderperlen&r an den Seiten, ein &6Netherstern&r in der Mitte, ein &6Advanced Pressure Tube&r unten.",
              "",
              "Unter Druck verhält sich der Block wie ein Inventar, nur dass alles, was hineingeht, &edirekt bei dir&r landet, egal wo du bist. Ein &9Requester&r-Rahmen darauf, 64 Fackeln eingestellt, und du hast immer Fackeln dabei. Über die Seitenkonfiguration erreichst du auch Rüstung, Zweithand und Endertruhe.",
              "",
              "&eMehr:&r Mit FE am Block lädt er jedes Strom-Item in deinem Inventar (100 000 FE Puffer). Mit einem &6Dispenser Upgrade&r füttert er dich mit Essen aus dem Netz, sobald du hungrig genug bist, und pumpt flüssige Erfahrung hinein oder heraus. Für 80 mL pro Tick atmest du unter Wasser.",
              "",
              "Der Netherstern kommt vom Wither, siehe Kapitel &cNether&r. Tu das nicht in der Nähe einer Basis.",
          ],
          tasks=[task_item("pneumaticcraft:aerial_interface", 1)],
          rewards=[reward_item("pneumaticcraft:logistics_frame_requester", 8), reward_table("s3_uncommon"), reward_xp(20)],
          deps=["logistics_drone"], icon="pneumaticcraft:aerial_interface", size=1.5, shape="diamond"),

    quest("universal_sensor", 16, 10.5, "&3Bau einen Universal Sensor",
          subtitle="Redstone aus Bedingungen.",
          description=[
              "&eRezept:&r ein &6Seismic Sensor&r oben, Plastic Sheet, &6Verstärker&r (Repeater), Plastic Sheet in der Mitte, Plastic Sheet, &6Pressure Tube&r, Plastic Sheet unten.",
              "",
              "Er misst, was um ihn herum passiert, und gibt ein &cRedstone-Signal&r aus: Druck in einem Rohr, Licht, Regen, Zeit, ein Spieler oder Monster in Reichweite, ein Block an einer Koordinate. Über 15 Bedingungen, jede im Fenster erklärt. Er braucht 1 mL Luft pro Tick.",
              "",
              "&eUpgrades schalten frei:&r Ein &6Entity Tracker Upgrade&r (Knochen, fermentiertes Spinnenauge) für alles mit Lebewesen, ein Block Tracker Upgrade plus GPS Tool für Blöcke an einer Koordinate. Welcher Sensor welches Upgrade will, steht im Fenster. Range Upgrades vergrößern die Reichweite.",
              "",
              "&eBeispiel:&r Entity Tracker hinein, Entity, Within Range, Filter &ecow&r: Das Signal geht an, wenn genug Kühe im Gehege sind, und startet die Schlachtmaschine.",
          ],
          tasks=[task_item("pneumaticcraft:universal_sensor", 1)],
          rewards=[reward_item("pneumaticcraft:entity_tracker_upgrade", 1), reward_item("pneumaticcraft:range_upgrade", 2), reward_xp(10)],
          deps=["guard_drone"], icon="pneumaticcraft:universal_sensor"),

    quest("security_station", 18.5, 10.5, "&cBau eine Security Station",
          subtitle="Niemand außer dir fasst deine Kisten an.",
          description=[
              "&eRezept:&r grauer Farbstoff, &6Glasscheibe&r, grauer Farbstoff oben, &6Turbine Rotor&r, &6PCB&r, Turbine Rotor in der Mitte, zwei &6Plastic Sheets&r unten in die Ecken.",
              "",
              "In ihrem Bereich kann kein fremder Spieler Blöcke setzen, abbauen oder Kisten öffnen. Jedes &6Range Upgrade&r vergrößert den Bereich um einen Block, bis 16 in jede Richtung. Freunde trägst du im Reiter &eShared Users&r ein.",
              "",
              "&eEinrichten:&r Im Netzraster müssen ein &6Diagnostic Subroutine&r, ein &6Network IO Port&r und eine &6Network Registry&r liegen, verbunden durch &6Network Nodes&r (Truhe mit Transistoren und lila Farbstoff, 16 Stück). Die Komponenten sind Plastik oder Transistoren um eine Truhe mit Farbstoff.",
              "",
              "&cHacken ist auf diesem Server erlaubt:&r Mit einem Pneumatic Helmet und Security Upgrades (Stufe 4) kann jemand deine Station knacken. Größere Stapel Network Nodes und Entity Tracker Upgrades machen das schwerer, Security Upgrades in der Station verlangen vom Hacker mehr Upgrades. Versteck sie gut.",
          ],
          tasks=[task_item("pneumaticcraft:security_station", 1)],
          rewards=[reward_item("pneumaticcraft:network_node", 16), reward_item("pneumaticcraft:range_upgrade", 4), reward_xp(10)],
          deps=["universal_sensor"], icon="pneumaticcraft:security_station", optional=True),

    quest("controller_block", 17.5, 12.5, "&5Bau einen Programmable Controller",
          subtitle="Eine Drohne im Block, die durch Wände geht.",
          description=[
              "&eRezept:&r Compressed Iron, &6Remote&r, Compressed Iron oben, &6PCB&r, &6Drone&r, &6Advanced Pressure Tube&r in der Mitte, Compressed Iron, &6Network Registry&r, Compressed Iron unten. Das Remote: Network IO Port, zwei Transistoren, GPS Tool, zwei Transistoren, Network Data Storage.",
              "",
              "Leg eine programmierte Drohne oder eine &6Network API&r hinein. Der Block führt das Programm mit einer &eMinidrohne&r aus, die keine echte Einheit ist: kein Pfadfinden, sie geht durch Wände, der Server dankt. Dafür 10 mL Luft pro Tick statt 1.",
              "",
              "Was sie sammelt, nimmst du an den Seiten des Blocks ab, Flüssigkeiten an jeder Seite. Ein Slot und 16 Eimer Tank, jedes Inventory Upgrade (bis 35) gibt einen Slot und 1 000 mB mehr. Teile wie Entity Attack, Teleport und Standby kann sie nicht. Für große Gruben und große Bauten ist sie das richtige Werkzeug.",
          ],
          tasks=[task_item("pneumaticcraft:programmable_controller", 1)],
          rewards=[reward_item("pneumaticcraft:inventory_upgrade", 4), reward_table("s3_uncommon"), reward_xp(15)],
          deps=["first_program"], icon="pneumaticcraft:programmable_controller", optional=True),

    # ---- Spawner --------------------------------------------------------------
    quest("spawner_extractor", 13, 5.5, "&2Bau einen Spawner Extractor",
          subtitle="Reiß dem Spawner sein Herz heraus.",
          description=[
              "&eRezept:&r Compressed Iron, &6Pressure Tube&r, Compressed Iron oben, &6Pressure Chamber Wall&r, &6Spawner Agitator&r, Pressure Chamber Wall in der Mitte, Obsidian, &6Drill Pipe&r, Obsidian unten. Der Agitator: acht Compressed Iron um eine &6Ghast-Träne&r.",
              "",
              "Setz ihn &eauf&r einen Spawner aus einem Verlies und gib ihm &c-0,5 bar&r Unterdruck oder weniger (Vacuum Pump, siehe Kapitel &bPneumaticCraft&r). Dann wehr dich: Der Spawner spawnt wie wild, jedes Monster in der Nähe bremst, zu viele halten alles an. Du musst in der Nähe bleiben.",
              "",
              "Nach etwa &e60 Sekunden&r springt ein &6Spawner Core&r heraus, zu 100 Prozent mit diesem Monster gefüllt, und der Spawner wird zum &6Empty Spawner&r. Bau den ab, du brauchst ihn für den Pressurized Spawner.",
              "",
              "&eTipp:&r Wer Apotheosis-Spawner mit Behutsamkeit holt (Kapitel &dApotheosis&r), stellt sie zu Hause auf und extrahiert dort, mit Licht und Mauern nach Wunsch.",
          ],
          tasks=[task_item("pneumaticcraft:spawner_extractor", 1)],
          rewards=[reward_item("minecraft:obsidian", 8), reward_table("s3_common"), reward_xp(10)],
          deps=["advanced_tube"], icon="pneumaticcraft:spawner_extractor"),

    quest("vacuum_trap", 15.5, 5.5, "&2Bau eine Vacuum Trap",
          subtitle="Monster einsaugen, Essenz sammeln.",
          description=[
              "&eRezept:&r Compressed Iron, &6Eisenfalltür&r, Compressed Iron oben, &6Reinforced Brick Wall&r, &6Enderauge&r, &6Pressure Tube&r in der Mitte, drei &6Reinforced Stone Slabs&r unten.",
              "",
              "Der zweite Weg zum Spawner Core: Die Falle braucht &c-0,5 bar&r, Volume Upgrades helfen. Leg einen leeren oder halbvollen &6Spawner Core&r hinein und öffne die Klappe mit Shift-Rechtsklick oder Redstone. Jedes Monster, das hineingezogen wird, füllt den Core um 1 Prozent.",
              "",
              "&eSpawner Core selbst machen:&r Eine &6Spawner Core Shell&r (vier Compressed Iron, vier Pressure Chamber Glass, ein Smaragd) mit 4 000 mB flüssiger Erfahrung (Memory Essence) in der Thermopneumatic Processing Plant bei 3 bar.",
              "",
              "Mit 100 mB &6Memory Essence&r im Tank der Falle zählt jedes Monster 2 bis 4 Prozent, also 25 bis 50 statt 100. Spieler, Drohnen, Bosse, gezähmte Tiere und Monster aus Spawnern fängt sie nie. Gemischte Cores spawnen gemischt, also eine Falle pro Monsterart.",
          ],
          tasks=[task_item("pneumaticcraft:vacuum_trap", 1)],
          rewards=[reward_item("pneumaticcraft:spawner_core_shell", 1), reward_item("pneumaticcraft:volume_upgrade", 2), reward_xp(10)],
          deps=["spawner_extractor"], icon="pneumaticcraft:vacuum_trap"),

    quest("pressurized_spawner", 18, 5.5, "&2&lBau einen Pressurized Spawner",
          subtitle="Ein Spawner, der auf dich hört.",
          description=[
              "&eRezept:&r vier &6Compressed Iron&r in die Ecken, vier &6Advanced Pressure Tubes&r an die Seiten, der &6Empty Spawner&r in die Mitte.",
              "",
              "Leg einen gefüllten &6Spawner Core&r hinein und gib ihm mindestens &e10 bar&r. Dann spawnt er, egal wie hell es ist und egal, ob ein Spieler in der Nähe steht, und ein Redstone-Signal schaltet ihn ab. Jeder Versuch kostet Luft, auch wenn der Core an der Stelle leer ist.",
              "",
              "Ein Core zu 50 Prozent Zombie und 25 Prozent Creeper spawnt in der Hälfte der Fälle einen Zombie, in einem Viertel einen Creeper, sonst nichts. Volle Cores aus dem Extractor sind darum die besten.",
              "",
              "&eKronwerke:&r Monsterfarmen mit Guard Drone und Collector Drone daneben sind ein Weg zu den Seelen und Essenzen, die die Magier für die Rituale dieser Stufe brauchen. Und wer Hostile Neural Networks spielt, füttert so die Simulation mit Modellen.",
          ],
          tasks=[task_item("pneumaticcraft:pressurized_spawner", 1)],
          rewards=[reward_table("s3_rare"), reward_item("pneumaticcraft:advanced_pressure_tube", 16), reward_xp(25)],
          deps=["vacuum_trap"], icon="pneumaticcraft:pressurized_spawner", size=2.0, shape="gear"),

    quest("outlook", 20.5, 5.5, "&dAusblick auf Stufe 4",
          subtitle="Rüstung, Minigun, Raketen.",
          description=[
              "Mit &6Stufe 4 (Sternwerk)&r öffnet PneumaticCraft seine Waffenkammer: die &6Pneumatic Armor&r (Helm, Brustplatte, Hose, Stiefel) mit Upgrades für Jetboots, Nachtsicht, Blockscanner, Entity Tracker und das Hacken von Security Stations und Drohnen. Dazu die &6Minigun&r mit Munitionssorten und die &6Micromissiles&r.",
              "",
              "Bis dahin: Jede Drohne, die du jetzt programmierst, jedes Rohr, das du jetzt legst, läuft dann weiter. Und der Drohnen-Debugger im Helm wird dir zeigen, warum die eine Drohne von damals nie geflogen ist.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(10)],
          deps=["pressurized_spawner"], icon="pneumaticcraft:programming_puzzle", optional=True),
]

images = [
    banner("pneumaticcraft_advanced/title", "PneumaticCraft: Drohnen und Druck", 9.5, -4.6, height=1.75, kind="title", colour="water"),
    banner("pneumaticcraft_advanced/assembly", "Die Montagestraße", 3.75, -2.4, height=0.9, colour="water"),
    banner("pneumaticcraft_advanced/pressure", "Druck der zweiten Stufe", 16, -2.4, height=0.9, colour="brass"),
    banner("pneumaticcraft_advanced/pcb", "Leiterplatten", 8.3, 4.3, height=0.9, colour="nature"),
    banner("pneumaticcraft_advanced/spawner", "Spawner", 14.6, 4.3, height=0.9, colour="fire"),
    banner("pneumaticcraft_advanced/drones", "Drohnen programmieren", 0.5, 7.6, height=0.9, colour="magic"),
    banner("pneumaticcraft_advanced/ready", "Fertige Drohnen", 11.25, 7.6, height=0.9, colour="brass"),
    banner("pneumaticcraft_advanced/control", "Steuerung und Schutz", 17.8, 7.6, height=0.9, colour="water"),
]

chapter(C, "PneumaticCraft: Drohnen und Druck", "pneumaticcraft:drone", "tech", quests, shape="circle", order=61, stage=3,
        subtitle=["Stufe 3: Montagestraße, Kompressoren für 20 bar, Drohnen und ihre Programme."], images=images)
