"""Productive Trees in stage 1, the full chapter: the Farming for Blockheads market (on Kronwerke it
sells the crossings of generations 1 to 3 and the five mutation saplings for 1, 2 and 4 emeralds,
kubejs/data/kronwerke/recipe/market/productivetrees/, everything later comes from breeding or loot),
fruit ripening and harvesting, crates and roasting, mega trees, Botany Pots, the sawmill, stripper and
Create saw, the tree families (fruit, citrus, tropical, berries, nuts, spices, dyes, hardwood, conifers),
the special trees (strip drops, the Tree Tap products that cannot be made here, the loot saplings, the
glowing hybrids, sapling mutations, the Time Traveller display), breeding with bees in detail, pollen
(the sifter has a Kronwerke recipe, kronwerke:added/pollen_sifter) and a checklist of all 148 crossings by
generation. Numbers come from the mod jar (trees.json, pollination recipes, block entity code).
cooking.py has the sawmill, the first bee crossing, the sifter and the beechnuts; those are referenced."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "productive_trees"


def pic(item_id, size=32):
    return img(item_texture(item_id), size, size)


def fruit_pic(name, size=32):
    """Fruits, nuts and spices keep their textures under textures/item/fruit/."""
    return img(f"productivetrees:textures/item/fruit/{name}.png", size, size)


# German names of every tree that appears as a parent or a result. Fantasy trees keep their names.
NAMES = {
    "oak": "Eiche", "birch": "Birke", "spruce": "Fichte", "jungle": "Tropenbaum", "dark_oak": "Schwarzeiche",
    "acacia": "Akazie", "cherry": "Kirsche", "mangrove": "Mangrove", "flowering_azalea": "Blühende Azalee",
    "alder": "Erle", "allspice": "Piment", "almond": "Mandel", "apricot": "Aprikose", "aquilaria": "Adlerholz",
    "asai_palm": "Acai-Palme", "ash": "Esche", "aspen": "Espe", "avocado": "Avocado", "balsa": "Balsa",
    "balsam_fir": "Balsamtanne", "banana": "Banane", "beech": "Buche", "beliy_naliv_apple": "Beliy-Naliv-Apfel",
    "black_cherry": "Schwarzkirsche", "black_ember": "Black Ember", "black_locust": "Robinie",
    "blackthorn": "Schlehe", "blue_mahoe": "Blue Mahoe", "blue_yonder": "Blue Yonder", "boxwood": "Buchsbaum",
    "brazil_nut": "Paranuss", "brazilwood": "Brasilholz", "breadfruit": "Brotfrucht", "brown_amber": "Brown Amber",
    "buddhas_hand": "Buddhas Hand", "bull_pine": "Gelbkiefer", "butternut": "Butternuss", "cacao": "Kakao",
    "candlenut": "Kerzennuss", "carob": "Johannisbrot", "cashew": "Cashew", "cave_dweller": "Cave Dweller",
    "cedar": "Zeder", "cempedak": "Cempedak", "ceylon_ebony": "Ceylon-Ebenholz", "cherry_plum": "Kirschpflaume",
    "cinnamon": "Zimt", "citron": "Zitronatzitrone", "clove": "Gewürznelke", "cocobolo": "Cocobolo",
    "coconut": "Kokospalme", "coffea": "Kaffee", "copoazu": "Copoazu", "copper_beech": "Blutbuche",
    "cork_oak": "Korkeiche", "cultivated_pear": "Kulturbirne", "date_palm": "Dattelpalme", "dogwood": "Hartriegel",
    "douglas_fir": "Douglasie", "elderberry": "Holunder", "elm": "Ulme", "european_larch": "Europäische Lärche",
    "finger_lime": "Fingerlimette", "firecracker": "Firecracker", "flickering_sun": "Flickering Sun",
    "flowering_crabapple": "Zierapfel", "foggy_blast": "Foggy Blast", "ginkgo": "Ginkgo",
    "golden_delicious_apple": "Golden-Delicious-Apfel", "grandidiers_baobab": "Grandidier-Baobab",
    "granny_smith_apple": "Granny-Smith-Apfel", "grapefruit": "Grapefruit", "great_sallow": "Salweide",
    "greenheart": "Greenheart", "hawthorn": "Weißdorn", "hazel": "Hasel", "holly": "Stechpalme",
    "hornbeam": "Hainbuche", "ipe": "Ipe", "iroko": "Iroko", "jackfruit": "Jackfrucht", "juniper": "Wacholder",
    "kapok": "Kapok", "key_lime": "Key-Lime", "kumquat": "Kumquat", "lawson_cypress": "Lawson-Zypresse",
    "lemon": "Zitrone", "lime": "Limette", "loblolly_pine": "Weihrauchkiefer", "logwood": "Blauholz",
    "mahogany": "Mahagoni", "mandarin": "Mandarine", "mango": "Mango", "monkey_puzzle": "Araukarie",
    "moonlight_magic_crepe_myrtle": "Moonlight-Magic-Kreppmyrte", "myrtle_ebony": "Myrten-Ebenholz",
    "nectarine": "Nektarine", "night_fuchsia": "Night Fuchsia", "nutmeg": "Muskat", "old_fustic": "Gelbholz",
    "olive": "Olive", "orange": "Orange", "osage_orange": "Osagedorn", "padauk": "Padauk", "pandanus": "Pandanus",
    "papaya": "Papaya", "peach": "Pfirsich", "pecan": "Pekannuss", "persimmon": "Kaki", "pink_ipe": "Rosa Ipe",
    "pink_ivory": "Pink Ivory", "pistachio": "Pistazie", "plantain": "Kochbanane", "plum": "Pflaume",
    "pomegranate": "Granatapfel", "pomelo": "Pomelo", "prairie_crabapple": "Prärie-Holzapfel",
    "purple_blackthorn": "Purpurschlehe", "purple_crepe_myrtle": "Purpur-Kreppmyrte", "purple_ipe": "Lila Ipe",
    "purple_spiral": "Purple Spiral", "purpleheart": "Purpleheart", "rainbow_gum": "Regenbogeneukalyptus",
    "red_banana": "Rote Banane", "red_crepe_myrtle": "Rote Kreppmyrte", "red_delicious_apple": "Red-Delicious-Apfel",
    "red_maple": "Rotahorn", "rippling_willow": "Rippling Willow", "rose_gum": "Rosen-Eukalyptus",
    "rosewood": "Palisander", "rowan": "Eberesche", "rubber_tree": "Gummibaum", "salak": "Salak",
    "sand_pear": "Nashi-Birne", "sandalwood": "Sandelholz", "satsuma": "Satsuma", "sequoia": "Mammutbaum",
    "silver_fir": "Weißtanne", "silver_lime": "Silberlinde", "slimy_delight": "Slimy Delight",
    "socotra_dragon": "Drachenblutbaum", "soul_tree": "Soul Tree", "sour_cherry": "Sauerkirsche",
    "soursop": "Stachelannone", "sparkle_cherry": "Sparkle Cherry", "star_anise": "Sternanis",
    "star_fruit": "Sternfrucht", "sugar_apple": "Zimtapfel", "sugar_maple": "Zuckerahorn",
    "swamp_gum": "Sumpf-Eukalyptus", "sweet_chestnut": "Edelkastanie", "sweet_crabapple": "Süßer Holzapfel",
    "sweetgum": "Amberbaum", "sycamore_fig": "Sykomore", "tangerine": "Tangerine", "teak": "Teak",
    "thunder_bolt": "Thunder Bolt", "time_traveller": "Time Traveller",
    "tuscarora_crepe_myrtle": "Tuscarora-Kreppmyrte", "walnut": "Walnuss", "water_wonder": "Water Wonder",
    "wenge": "Wenge", "western_hemlock": "Westliche Hemlocktanne", "white_ipe": "Weißer Ipe",
    "white_poplar": "Silberpappel", "white_willow": "Silberweide", "whitebeam": "Mehlbeere",
    "wild_cherry": "Vogelkirsche", "yellow_meranti": "Gelbes Meranti", "yew": "Eibe", "zebrano": "Zebrano",
}

# Every crossing from data/productivetrees/recipe/pollination/: result, generation (parents' generation
# plus one, vanilla and loot saplings are 0), leaf A, leaf B (several allowed leaves joined with |), chance.
HYBRIDS = [
    ('silver_lime', 1, 'oak', 'birch', 0.55),
    ('beech', 1, 'oak', 'birch', 0.5),
    ('teak', 1, 'dark_oak', 'jungle', 0.4),
    ('cacao', 1, 'jungle', 'cherry', 0.35),
    ('european_larch', 1, 'spruce', 'birch', 0.1),
    ('red_delicious_apple', 1, 'cherry', 'oak|dark_oak', 0.1),
    ('cave_dweller', 1, 'black_ember', 'soul_tree', 0.05),
    ('purple_spiral', 1, 'blue_yonder', 'firecracker', 0.05),
    ('rippling_willow', 1, 'blue_yonder', 'flickering_sun', 0.05),
    ('sparkle_cherry', 1, 'firecracker', 'soul_tree', 0.05),
    ('thunder_bolt', 1, 'firecracker', 'flickering_sun', 0.05),
    ('water_wonder', 1, 'blue_yonder', 'soul_tree', 0.05),
    ('alder', 2, 'beech', 'birch', 0.1),
    ('ash', 2, 'silver_lime', 'spruce', 0.1),
    ('balsa', 2, 'teak', 'acacia', 0.1),
    ('brazil_nut', 2, 'beech', 'cacao', 0.1),
    ('bull_pine', 2, 'european_larch', 'spruce', 0.1),
    ('cashew', 2, 'teak', 'mangrove', 0.1),
    ('granny_smith_apple', 2, 'red_delicious_apple', 'cherry', 0.1),
    ('ipe', 2, 'teak', 'dark_oak', 0.1),
    ('kapok', 2, 'teak', 'jungle', 0.1),
    ('pecan', 2, 'beech', 'birch', 0.1),
    ('prairie_crabapple', 2, 'red_delicious_apple', 'birch', 0.1),
    ('red_maple', 2, 'silver_lime', 'european_larch', 0.1),
    ('sand_pear', 2, 'red_delicious_apple', 'flowering_azalea', 0.1),
    ('walnut', 2, 'silver_lime', 'cherry', 0.1),
    ('wild_cherry', 2, 'silver_lime', 'cherry', 0.1),
    ('yew', 2, 'european_larch', 'spruce', 0.1),
    ('dogwood', 2, 'silver_lime', 'cherry', 0.05),
    ('foggy_blast', 2, 'cave_dweller', 'soul_tree', 0.05),
    ('night_fuchsia', 2, 'purple_spiral', 'sparkle_cherry', 0.05),
    ('slimy_delight', 2, 'rippling_willow', 'soul_tree', 0.05),
    ('time_traveller', 2, 'blue_yonder', 'rippling_willow', 0.05),
    ('white_willow', 2, 'silver_lime', 'oak|birch', 0.05),
    ('aquilaria', 3, 'teak', 'ipe', 0.1),
    ('aspen', 3, 'beech', 'alder', 0.1),
    ('balsam_fir', 3, 'alder', 'european_larch', 0.1),
    ('banana', 3, 'balsa', 'cacao', 0.1),
    ('black_locust', 3, 'balsa', 'silver_lime', 0.1),
    ('butternut', 3, 'walnut', 'wild_cherry', 0.1),
    ('ceylon_ebony', 3, 'kapok', 'dark_oak', 0.1),
    ('cocobolo', 3, 'balsa', 'dark_oak', 0.1),
    ('coconut', 3, 'brazil_nut', 'balsa', 0.1),
    ('cultivated_pear', 3, 'red_delicious_apple', 'sand_pear', 0.1),
    ('elm', 3, 'ash', 'silver_lime', 0.1),
    ('golden_delicious_apple', 3, 'red_delicious_apple', 'granny_smith_apple', 0.1),
    ('iroko', 3, 'balsa', 'teak', 0.1),
    ('lawson_cypress', 3, 'bull_pine', 'spruce', 0.1),
    ('loblolly_pine', 3, 'bull_pine', 'spruce', 0.1),
    ('olive', 3, 'alder', 'wild_cherry', 0.1),
    ('rose_gum', 3, 'balsa', 'flowering_azalea', 0.1),
    ('sour_cherry', 3, 'white_willow', 'cherry', 0.1),
    ('sugar_apple', 3, 'pecan', 'wild_cherry', 0.1),
    ('sweet_chestnut', 3, 'walnut', 'wild_cherry|silver_lime', 0.1),
    ('whitebeam', 3, 'ash', 'birch', 0.1),
    ('blue_mahoe', 3, 'teak', 'balsa', 0.05),
    ('padauk', 3, 'red_maple', 'jungle', 0.05),
    ('papaya', 3, 'wild_cherry', 'cacao', 0.05),
    ('sequoia', 3, 'european_larch', 'bull_pine', 0.05),
    ('sugar_maple', 3, 'european_larch', 'red_maple', 0.05),
    ('white_poplar', 3, 'white_willow', 'oak|birch|silver_lime', 0.05),
    ('beliy_naliv_apple', 4, 'golden_delicious_apple', 'granny_smith_apple', 0.1),
    ('black_cherry', 4, 'ceylon_ebony', 'sour_cherry', 0.1),
    ('cork_oak', 4, 'lawson_cypress', 'oak', 0.1),
    ('elderberry', 4, 'aspen', 'alder', 0.1),
    ('great_sallow', 4, 'white_willow', 'aspen', 0.1),
    ('hazel', 4, 'aspen', 'beech', 0.1),
    ('hornbeam', 4, 'ash', 'whitebeam', 0.1),
    ('pandanus', 4, 'walnut', 'coconut', 0.1),
    ('plantain', 4, 'banana', 'teak', 0.1),
    ('rainbow_gum', 4, 'balsa', 'rose_gum', 0.1),
    ('red_banana', 4, 'banana', 'kapok', 0.1),
    ('rowan', 4, 'aspen', 'alder', 0.1),
    ('silver_fir', 4, 'balsam_fir', 'bull_pine', 0.1),
    ('soursop', 4, 'sugar_apple', 'banana', 0.1),
    ('sweet_crabapple', 4, 'red_delicious_apple', 'sugar_maple', 0.1),
    ('sweetgum', 4, 'european_larch', 'sugar_maple', 0.1),
    ('sycamore_fig', 4, 'ash', 'sugar_maple', 0.1),
    ('wenge', 4, 'balsa', 'cocobolo', 0.1),
    ('yellow_meranti', 4, 'ceylon_ebony', 'kapok', 0.1),
    ('citron', 4, 'silver_lime', 'sour_cherry', 0.05),
    ('date_palm', 4, 'papaya', 'cacao', 0.05),
    ('purple_crepe_myrtle', 4, 'ceylon_ebony', 'cherry', 0.05),
    ('zebrano', 4, 'white_poplar', 'ceylon_ebony', 0.05),
    ('western_hemlock', 5, 'bull_pine', 'silver_fir', 3),
    ('avocado', 5, 'wenge', 'oak', 0.1),
    ('breadfruit', 5, 'sycamore_fig', 'sugar_maple', 0.1),
    ('cedar', 5, 'silver_fir', 'european_larch', 0.1),
    ('coffea', 5, 'black_cherry', 'cacao', 0.1),
    ('douglas_fir', 5, 'silver_fir', 'spruce', 0.1),
    ('flowering_crabapple', 5, 'sweet_crabapple', 'flowering_azalea', 0.1),
    ('ginkgo', 5, 'wenge', 'silver_lime', 0.1),
    ('grandidiers_baobab', 5, 'balsa', 'wenge', 0.1),
    ('hawthorn', 5, 'rowan', 'beech', 0.1),
    ('holly', 5, 'alder', 'rowan', 0.1),
    ('juniper', 5, 'elderberry', 'silver_fir', 0.1),
    ('key_lime', 5, 'citron', 'wild_cherry', 0.1),
    ('mahogany', 5, 'yellow_meranti', 'kapok', 0.1),
    ('pomelo', 5, 'citron', 'wild_cherry', 0.1),
    ('rubber_tree', 5, 'sweetgum', 'loblolly_pine', 0.1),
    ('salak', 5, 'pandanus', 'coconut', 0.1),
    ('socotra_dragon', 5, 'wenge', 'cocobolo', 0.1),
    ('swamp_gum', 5, 'yellow_meranti', 'rose_gum', 0.1),
    ('asai_palm', 5, 'date_palm', 'black_cherry', 0.05),
    ('persimmon', 5, 'ceylon_ebony', 'purple_crepe_myrtle', 0.05),
    ('plum', 5, 'citron', 'wild_cherry', 0.05),
    ('almond', 6, 'plum', 'walnut', 0.1),
    ('blackthorn', 6, 'plum', 'red_delicious_apple', 0.1),
    ('boxwood', 6, 'holly', 'alder', 0.1),
    ('brazilwood', 6, 'teak', 'mahogany', 0.1),
    ('candlenut', 6, 'ginkgo', 'hazel', 0.1),
    ('cempedak', 6, 'sycamore_fig', 'breadfruit', 0.1),
    ('cherry_plum', 6, 'plum', 'cherry', 0.1),
    ('clove', 6, 'coffea', 'teak', 0.1),
    ('finger_lime', 6, 'citron', 'key_lime', 0.1),
    ('greenheart', 6, 'mahogany', 'kapok', 0.1),
    ('lemon', 6, 'pomelo', 'citron', 0.1),
    ('lime', 6, 'pomelo', 'key_lime', 0.1),
    ('mandarin', 6, 'pomelo', 'wild_cherry', 0.1),
    ('monkey_puzzle', 6, 'western_hemlock', 'jungle', 0.1),
    ('old_fustic', 6, 'red_maple', 'mahogany', 0.1),
    ('peach', 6, 'plum', 'sweet_chestnut', 0.1),
    ('rosewood', 6, 'mahogany', 'teak', 0.1),
    ('myrtle_ebony', 6, 'ceylon_ebony', 'persimmon', 0.05),
    ('pomegranate', 6, 'holly', 'purple_crepe_myrtle', 0.05),
    ('allspice', 7, 'teak', 'clove', 0.1),
    ('apricot', 7, 'plum', 'peach', 0.1),
    ('buddhas_hand', 7, 'mandarin', 'citron', 0.1),
    ('cinnamon', 7, 'rosewood', 'teak', 0.1),
    ('copoazu', 7, 'cacao', 'candlenut', 0.1),
    ('jackfruit', 7, 'cempedak', 'breadfruit', 0.1),
    ('kumquat', 7, 'mandarin', 'wild_cherry', 0.1),
    ('logwood', 7, 'kapok', 'rosewood', 0.1),
    ('nectarine', 7, 'plum', 'peach', 0.1),
    ('nutmeg', 7, 'teak', 'clove', 0.1),
    ('orange', 7, 'mandarin', 'pomelo', 0.1),
    ('osage_orange', 7, 'kapok', 'old_fustic', 0.1),
    ('pink_ivory', 7, 'brazilwood', 'rose_gum', 0.1),
    ('pistachio', 7, 'almond', 'cashew', 0.1),
    ('purpleheart', 7, 'brazilwood', 'kapok', 0.1),
    ('sandalwood', 7, 'brazilwood', 'mahogany', 0.1),
    ('carob', 8, 'sweet_chestnut', 'copoazu', 0.1),
    ('grapefruit', 8, 'pomelo', 'orange', 0.1),
    ('mango', 8, 'orange', 'mangrove', 0.1),
    ('satsuma', 8, 'mandarin', 'kumquat', 0.1),
    ('star_anise', 8, 'clove', 'allspice', 0.1),
    ('tangerine', 8, 'mandarin', 'kumquat', 0.1),
    ('star_fruit', 9, 'mango', 'star_anise', 0.1),
]


def parents(a, b):
    return " + ".join(" oder ".join(NAMES[p] for p in side.split("|")) for side in (a, b))


def chance_text(c):
    return "jeder Versuch" if c >= 1 else f"{round(c * 100):d} %"


def hybrid_line(row):
    name, gen, a, b, c = row
    return f"&6{NAMES[name]}&r: {parents(a, b)}, {chance_text(c)}"


def hybrid_task(row):
    name, gen, a, b, c = row
    return task_checkmark(f"{NAMES[name]} ({parents(a, b)}, {chance_text(c)})")


def checklist(name, x, y, title, rows, deps, icon, intro):
    """One checklist quest: a tick per crossing, the same lines in the description."""
    return quest(name, x, y, title,
                 subtitle=f"{len(rows)} Kreuzungen, ein Haken pro gezüchteter Art.",
                 description=[intro, ""] + [hybrid_line(r) for r in rows],
                 tasks=[hybrid_task(r) for r in rows],
                 rewards=[reward_item("minecraft:emerald", 2), reward_xp(3)],
                 deps=deps, icon=icon, optional=True)


def gen_rows(g):
    return [r for r in HYBRIDS if r[1] == g]


G1, G2, G3, G4, G5, G6, G7 = (gen_rows(g) for g in range(1, 8))
G89 = gen_rows(8) + gen_rows(9)

quests = [
    # ---- Der Markt ---------------------------------------------------------------------
    quest("market", 0, 0, "&a&lKauf einen Setzling am Markt",
          subtitle="Jede Baumart für einen Smaragd.",
          description=[
              "Stell den &6Markt&r von Farming for Blockheads auf (Rezept im Kapitel &6Essen und Landwirtschaft&r) und kauf unter &eSetzlinge&r einen &6Walnuss-Setzling&r für &62 Smaragde&r.",
              "",
              "&eKronwerke:&r Die Bäume von &6Productive Trees&r wachsen nirgends in der Welt. Der Markt verkauft die Kreuzungen der ersten drei Generationen: &eGeneration 1&r (Buche, Silberlinde, Teak, Kakao, Lärche, Red-Delicious-Apfel) für &61 Smaragd&r, &eGeneration 2&r und die fünf Mutationen für &62&r, &eGeneration 3&r für &64&r.",
              "",
              "Alles ab Generation 4, die leuchtenden Bäume und die Fundstücke gibt es nur durch &eZüchten&r mit Bienen oder Pollen und aus Truhen. 57 Setzlinge zum Kaufen, gut 100 zum Erarbeiten.",
              "",
              "Smaragde bekommst du bei Dorfbewohnern, aus Smaragderz im Gebirge und aus den Kisten dieses Kapitels. 163 Baumarten warten, mit Obst, Nüssen, Gewürzen, Farben und 163 Holzsorten. JEI zeigt unter &eBaumbestäubung&r zu jedem Baum die Eltern.",
          ],
          tasks=[task_item("productivetrees:walnut_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 4), reward_table("s1_common")],
          icon="farmingforblockheads:market", size=2.0, shape="hexagon"),

    quest("first_tree", 2.5, 0, "&aPflanz die Walnuss und ernte Nüsse",
          subtitle="Früchte reifen am Blatt, Rechtsklick pflückt.",
          description=[
              "Pflanz den &6Walnuss-Setzling&r auf Erde oder Gras und lass ihn wachsen, mit &6Knochenmehl&r geht es sofort. Etwa 60 Prozent der Blätter sind &eFruchtblätter&r, die erst grün und dann braun werden. Rechtsklick auf ein reifes Blatt gibt &63 Walnüsse&r, das Blatt bleibt und trägt wieder.",
              "",
              fruit_pic("walnut"),
              "",
              "Jedes Fruchtblatt hat &e7 Reifestufen&r und braucht Licht 9 oder mehr. Von allein dauert eine Stufe bei den meisten Bäumen im Schnitt knapp eine Stunde, Bananen und Paranüsse brauchen das Zweieinhalbfache. &6Knochenmehl&r auf das Blatt schaltet eine Stufe weiter, sieben Stück machen es reif.",
              "",
              "Abbauen lohnt nicht: Ein abgeschlagenes reifes Blatt gibt nur eine Nuss, dazu mit 5 Prozent einen Setzling. Rohe Nüsse geben 1 Hunger, geröstet im Ofen oder Räucherofen (6 Sekunden) sättigen sie dreimal so gut. Nüsse und Obst im Pflanztopf gehen viel schneller, siehe weiter rechts.",
          ],
          tasks=[task_item("productivetrees:walnut", 12)],
          rewards=[reward_item("minecraft:bone_meal", 32), reward_xp(5)],
          deps=["market"], icon="productivetrees:walnut"),

    quest("crates", 5, 0, "&aPack Nüsse in eine Kiste",
          subtitle="Neun Stück pro Kiste, geröstet wird im Ganzen.",
          description=[
              "Neun &6Walnüsse&r in der Werkbank ergeben eine &6Kiste Walnüsse&r, die Kiste formlos wieder neun Nüsse. Das gibt es für jedes Obst, jede Nuss, jedes Gewürz und für Kaffeebohnen, insgesamt 90 Kistensorten.",
              "",
              "Eine Kiste Nüsse röstet im Ofen in 54 Sekunden zu einer &6Kiste geröstete Walnüsse&r, das ist pro Nuss genauso schnell wie einzeln, aber nur ein Ofenslot. Die Kisten sind Blöcke und lassen sich stapeln wie Fässer.",
              "",
              "&eTipp:&r Die zwölf Nusssorten (Mandel, Buchecker, Paranuss, Butternuss, Kerzennuss, Cashew, Edelkastanie, Ginkgo, Hasel, Pekan, Pistazie, Walnuss) und Kaffeebohnen lassen sich rösten. Obst isst du roh.",
          ],
          tasks=[task_item("productivetrees:walnut_crate", 1)],
          rewards=[reward_item("productivetrees:roasted_walnut", 18), reward_xp(3)],
          deps=["first_tree"], icon="productivetrees:walnut_crate"),

    quest("mega", 2.5, 2.2, "&aPflanz vier Setzlinge im Quadrat",
          subtitle="Manche Bäume wachsen nur als Riesen.",
          description=[
              "Setz &64 Pekannuss-Setzlinge&r als 2x2-Quadrat und dünge einen davon. Die &6Pekannuss&r wächst nur so, als einzelner Setzling passiert gar nichts. Genauso Ulme, Iroko, Padauk, Pandanus und Eibe.",
              "",
              "Andere brauchen &e3x3&r (Brown Amber, Cave Dweller, Grandidier-Baobab, Regenbogeneukalyptus, Rosen-Eukalyptus) oder &e5x5&r (Paranuss, Kapok, Purpleheart, Mammutbaum, Westliche Hemlocktanne, Gelbes Meranti). Der Mammutbaum wird mit &e9x9&r Setzlingen noch einmal größer.",
              "",
              "Viele normale Bäume haben zusätzlich eine große Form: Buche, Walnuss, Hasel, Zeder, Mango und rund vierzig weitere wachsen aus 2x2 oder 3x3 Setzlingen zu einem Riesenbaum mit viel mehr Blättern, also mehr Früchten pro Baum.",
          ],
          tasks=[task_item("productivetrees:pecan_sapling", 4)],
          rewards=[reward_item("minecraft:bone_meal", 16), reward_table("s1_common")],
          deps=["first_tree"], icon="productivetrees:pecan_sapling"),

    quest("pots", 5, 2.2, "&aZieh Bäume im Pflanztopf",
          subtitle="Alle zwei Minuten Holz, Blätter und die ganze Ernte.",
          description=[
              "Steck einen &6Setzling&r von Productive Trees in einen &6Pflanztopf&r (Botany Pots, Kapitel &6Kochen&r) mit Erde. Alle &e2 Minuten&r kommen &e2 Stämme&r, ein Blatt und bei Obstbäumen die volle Ernte eines Blatts heraus, bei der Walnuss also 3 Nüsse, bei der Schwarzkirsche 5 Kirschen.",
              "",
              "Mit 5 Prozent fällt dabei ein weiterer Setzling ab. Ein &6Trichter-Pflanztopf&r wirft alles in die Kiste darunter. Das ist der schnellste Weg zu Obst, Gewürzen und Kaffee, viel schneller als das Reifen am Baum.",
              "",
              "Alle 163 Arten funktionieren so, auch die Fundstücke und die leuchtenden Hybriden. Kork, Zimt und Schleim aus dem Entrinder gibt es im Topf aber nicht, dafür brauchst du die Stämme.",
          ],
          tasks=[task_item("botanypots:terracotta_hopper_botany_pot", 1)],
          rewards=[reward_item("productivetrees:beech_sapling", 2), reward_xp(5)],
          deps=["first_tree"], icon="botanypots:terracotta_hopper_botany_pot"),

    # ---- Holz --------------------------------------------------------------------------
    quest("sawmill_run", 0, 5.5, "&6Säge Stämme im Sägewerk",
          subtitle="Sechs Bretter und zwei Sägemehl pro Stamm, 10 Sekunden.",
          description=[
              "Leg Stämme in das &6Sägewerk&r (Rezept im Kapitel &6Kochen&r). Alle &e10 Sekunden&r wird ein Stamm zu &e6 Brettern&r und &e2 Sägemehl&r, an der Werkbank wären es nur 4 Bretter. Trichter oben hinein, Trichter unten heraus, fertig ist die Bretterfabrik.",
              "",
              pic("productivetrees:sawdust"),
              "",
              "Das geht mit jedem Stamm, auch Vanilla. &6Blauholz&r und &6Brasilholz&r geben zusätzlich &5Hämatoxylin&r, &6Gelbholz&r gibt &eFustik&r, mehr dazu bei den Farbbäumen. Acht &6Sägemehl&r um einen Wassereimer oder eine Wasserflasche ergeben 2 Papier.",
              "",
              "&eKronwerke:&r Für die Mühle und die Pressen der Technikziele brauchst du Unmengen Bretter. Ein Sägewerk am Baumgarten liefert 50 Prozent mehr aus demselben Holz.",
          ],
          tasks=[task_item("productivetrees:sawdust", 32)],
          rewards=[reward_item("minecraft:paper", 16), reward_table("s1_common")],
          deps=["first_tree"], icon="productivetrees:sawmill", size=1.5),

    quest("stripper", 2.5, 5.5, "&6Bau den Entrinder",
          subtitle="Eine Axt im Block entrindet stapelweise.",
          description=[
              "&eRezept:&r oben Bretter, ein &6Stamm&r, Bretter, in der Mitte drei &6Eisenbarren&r, unten drei Bretter. Leg eine &6Axt&r in den Werkzeugslot des &6Entrinders&r und Stämme oder Holz in den Eingang, alle halbe Sekunde kommt ein entrindeter Block heraus.",
              "",
              "Die Axt verliert pro Block einen Punkt Haltbarkeit, eine Steinaxt schafft also 131 Stämme. Mit Reparatur hält sie entsprechend länger, Haltbarkeit ist alles, was zählt.",
              "",
              "Der vierte Slot ist der &eRindenslot&r: Bei Zimt-, Korkeichen- und Slimy-Delight-Stämmen fällt dort &6Zimt&r, &6Kork&r oder ein &6Schleimball&r an, pro Stamm einer. Von Hand mit der Axt klappt das auch, dann liegt es am Boden.",
          ],
          tasks=[task_item("productivetrees:stripper", 1)],
          rewards=[reward_item("minecraft:iron_axe", 1), reward_xp(5)],
          deps=["sawmill_run"], icon="productivetrees:stripper"),

    quest("wood_set", 5, 5.5, "&6Bau mit einem neuen Holz",
          subtitle="163 Holzsorten, jede mit kompletter Blockfamilie.",
          description=[
              "Mach aus Brettern einer Productive-Trees-Art Treppen, Stufen, Zaun, Zauntor, Tür, Falltür, Knopf, Druckplatte, Schild, Hängeschild und ein &6Bücherregal&r (sechs Bretter um drei Bücher). Die Rezepte sind die von Eichenholz.",
              "",
              "Bücherregale aus diesen Hölzern zählen am Zaubertisch wie Eichenregale, auch für Apotheosis. Die Create-Säge schneidet Bretter in alle diese Blöcke, und Supplementaries hat für jedes Holz einen Wegweiser.",
              "",
              "Die Hölzer unterscheiden sich stark in der Farbe: Ebenholz fast schwarz, Balsa fast weiß, Padauk dunkelrot, Purpleheart lila, Pink Ivory rot, Mahagoni rotbraun. Für Bauer ist das der eigentliche Schatz des Mods.",
              "",
              "&eStufe 2:&r Mit &6Productive Bees&r gibt es den Fortgeschrittenen Bienenstock und die Erweiterungsbox in jedem dieser Hölzer: Bretter, zwei Waben, ein Stock, Lagerfeuer und Schere.",
          ],
          tasks=[task_checkmark("Gebaut")],
          rewards=[reward_item("minecraft:book", 6), reward_xp(3)],
          deps=["sawmill_run"], icon="productivetrees:mahogany_planks"),

    quest("create_saw", 7.5, 5.5, "&6Lass die Create-Säge schneiden",
          subtitle="Auch die Mechanische Säge kennt jedes Holz.",
          description=[
              "Stell eine &6Mechanische Säge&r von Create aufrecht und wirf ihr Stämme von Productive Trees vor. Sie schneidet jeden Stamm in &e6 Bretter&r, genau wie das Sägewerk, nur ohne Sägemehl und mit Rotation statt Wartezeit.",
              "",
              "Waagerecht fällt die Säge ganze Bäume, auch die Riesenbäume aus 2x2 oder 5x5 Setzlingen, und die Blätter mit. Mit einem Einsatzgerät, das den Setzling nachpflanzt, hast du eine Holzfarm für jede der 163 Arten.",
              "",
              "&eTipp:&r Fruchtblätter geben beim Fällen nur dann eine Frucht, wenn sie gerade reif sind. Für Obst bleib beim Pflücken oder beim Pflanztopf, für Holz ist die Säge unschlagbar.",
          ],
          tasks=[task_item("create:mechanical_saw", 1)],
          rewards=[reward_item("create:andesite_alloy", 8), reward_xp(5)],
          deps=["wood_set"], icon="create:mechanical_saw", optional=True),

    quest("upgrades", 2.5, 7.7, "&6Ausblick: Zeit-Upgrades",
          subtitle="Sägewerk, Entrinder und Sieb werden schneller.",
          description=[
              "Sägewerk, Entrinder und Pollensieber haben je &e4 Upgrade-Slots&r für die Zeit-Upgrades von Productive Lib. &6Upgrade: Speed&r ist eine Upgrade-Basis mit vier Uhren und vier Honigwabenblöcken.",
              "",
              "&eSägewerk und Sieber:&r jedes Speed-Upgrade plus eine Geschwindigkeitsstufe, vier Stück machen das Sägewerk fünfmal so schnell, ein Stamm in 2 Sekunden. &6Upgrade: Speedier&r zählt doppelt, braucht aber Netherstern und Herz des Meeres.",
              "&eEntrinder:&r jedes Speed-Upgrade entrindet &e4 Blöcke&r pro halbe Sekunde statt einem, Speedier 8. Die Axt verliert entsprechend mehr Haltbarkeit.",
              "",
              "&cStufe 2:&r Die &6Upgrade-Basis&r braucht ein &6Honey Treat&r aus Productive Bees, das Rezept steht im Kapitel &6Bienen&r. Vorher läuft alles in der Grundgeschwindigkeit.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_item("minecraft:clock", 1)],
          deps=["stripper"], icon="minecraft:clock", optional=True),

    # ---- Die Baumfamilien ---------------------------------------------------------------
    quest("fruit_trees", 11, -1.2, "&aPflanz einen Apfelbaum",
          subtitle="Äpfel, Birnen, Pflaumen, Pfirsiche: 4 Hunger pro Frucht.",
          description=[
              "Kauf einen &6Granny-Smith-Apfelbaum&r. Jedes reife Blatt gibt einen Apfel mit &e4 Hunger&r, so viel wie ein Steak-Bissen. Dasselbe liefern Golden Delicious, Beliy Naliv, die drei Holzäpfel, Kulturbirne, Nashi-Birne, Avocado, Kaki, Granatapfel und Zimtapfel.",
              "",
              fruit_pic("granny_smith_apple"),
              "",
              "&eSteinobst:&r Pflaume (2 pro Blatt), Pfirsich, Nektarine, Aprikose, Kirschpflaume, Vogelkirsche (2), Sauerkirsche, Schwarzkirsche (5), Olive (2), Datteln (3), Feigen (2) und Kumquat geben ebenfalls 4 Hunger.",
              "",
              "Der &6Red-Delicious-Apfelbaum&r trägt echte Vanilla-Äpfel, zwei pro Blatt. Mit Gold wird daraus der Goldene Apfel, ein Baum für die Bosse.",
          ],
          tasks=[task_item("productivetrees:granny_smith_apple_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 2), reward_xp(3)],
          deps=["first_tree"], icon="productivetrees:granny_smith_apple"),

    quest("citrus", 13.5, -1.2, "&eZüchte die Zitronatzitrone",
          subtitle="Der Stammvater von dreizehn Zitrusarten.",
          description=[
              "Kreuz &6Silberlinde&r und &6Sauerkirsche&r (5 Prozent), und du hast die &6Zitronatzitrone&r, den Anfang aller Zitrusfrüchte. Keine davon steht im Markt. Zitrusfrüchte geben nur 2 Hunger (Zitrone, Limette, Key-Lime, Fingerlimette, Zitronatzitrone) oder 3 (Orange, Mandarine, Buddhas Hand) und keine Sättigung.",
              "",
              fruit_pic("lemon"),
              "",
              "Von dort geht es weiter: Zitronatzitrone und Vogelkirsche ergeben Pomelo oder Key-Lime, Pomelo und Zitronatzitrone die &6Zitrone&r (3 pro Blatt), über Mandarine und Kumquat bis zu Grapefruit, Satsuma und Tangerine, die als Obst mit 4 Hunger zählen. Die ganze Familie steht in der Checkliste unten.",
          ],
          tasks=[task_item("productivetrees:citron_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 4), reward_xp(5)],
          deps=["pollinated"], icon="productivetrees:lemon", optional=True),

    quest("tropical", 16, -1.2, "&aPflanz eine Banane",
          subtitle="Bananen, Mango, Kokos und Kakao, die großen Früchte.",
          description=[
              "Kauf eine &6Banane&r (Generation 3, 4 Smaragde): &e3 Bananen&r pro Blatt mit je 4 Hunger, aber die Blätter reifen langsam (Tempo 0,2). Die Rote Banane (3) ist eine Verwandte mit 4 Hunger. Kochbanane (2), Kokosnuss, Mango, Papaya, Brotfrucht, Jackfrucht, Cempedak, Copoazu, Stachelannone, Hala-Frucht und Baobabfrucht geben &e5 Hunger&r.",
              "",
              fruit_pic("banana"),
              "",
              "&eKokospalme:&r Reife Kokosnüsse fallen von selbst herunter und schlagen hart auf, stell dich nicht darunter. Der Kokosspross am Boden ist die Frucht, abbauen und aufheben.",
              "&eKakao:&r Der Baum wächst mit Vanilla-&6Kakaoschoten&r am Stamm, die Bohnen kommen also wie im Dschungel.",
              "",
              "Dattelpalme, Acai-Palme, Salak und Pandanus (Hala-Frucht) runden die Tropen ab. Alle Palmen und Bananen haben zusammenhängende Kronen, abgetrennte Blätter zerfallen.",
          ],
          tasks=[task_item("productivetrees:banana_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 2), reward_xp(3)],
          deps=["first_tree"], icon="productivetrees:banana"),

    quest("berries", 18.5, -1.2, "&dZüchte einen Holunder",
          subtitle="Beeren: schneller Snack, fünf pro Blatt.",
          description=[
              "Kreuz &6Espe&r und &6Erle&r (10 Prozent, beide im Markt), und du bekommst den &6Holunder&r oder die Eberesche. Der Holunder trägt &e5 Holunderbeeren&r pro Blatt. Beeren geben nur 1 Hunger, werden aber schnell gegessen und immer, auch mit vollem Magen. Wacholder (3), Weißdorn (3), Eberesche, Acai (3) und die Schlehen (3) sind die anderen Beerenbäume.",
              "",
              fruit_pic("elderberry"),
              "",
              "Der &6Weißdorn&r und die &6Stechpalme&r kommen beide über die Eberesche, Holunder und Weißtanne ergeben den Wacholder. Beeren brauchst du vor allem als Zwischenschritt, Kisten voller Beeren sind hübsche Deko.",
          ],
          tasks=[task_item("productivetrees:elderberry_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 3), reward_xp(5)],
          deps=["pollinated"], icon="productivetrees:elderberry", optional=True),

    quest("nuts", 11, 1.0, "&6Pflanz einen Cashewbaum",
          subtitle="Zwölf Nussbäume, geröstet dreimal so sättigend.",
          description=[
              "Kauf einen &6Cashewbaum&r (Teak und Mangrove, 2 Smaragde): &e3 Cashews&r pro Blatt. Nussbäume tragen fast alle drei Nüsse (Mandel, Buche, Paranuss, Butternuss, Kerzennuss, Cashew, Ginkgo, Hasel, Pekan, Pistazie, Walnuss), nur die Edelkastanie zwei.",
              "",
              fruit_pic("roasted_cashew"),
              "",
              "Roh geben Nüsse 1 Hunger und kaum Sättigung, im Ofen oder Räucherofen in 6 Sekunden geröstet dreimal so viel Sättigung. Die &6Bucheckern&r und ihr Rösten stehen im Kapitel &6Kochen&r.",
              "",
              "Die &6Kaffeebohne&r (4 pro Blatt am Kaffeebaum) röstet genauso. Hasel, Mandel, Pistazie und Kaffee gibt es nur durch Züchten: Espe und Buche ergeben die Hasel, Mandel und Cashew die Pistazie.",
          ],
          tasks=[task_item("productivetrees:cashew_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 2), reward_xp(3)],
          deps=["first_tree"], icon="productivetrees:cashew"),

    quest("spices", 13.5, 1.0, "&6Züchte Gewürzbäume",
          subtitle="Piment, Nelke, Muskat, Sternanis und Zimt.",
          description=[
              "Gewürzbäume stehen in Generation 6 bis 8, keiner im Markt. Vier Gewürze wachsen als Frucht: &6Piment&r (2 pro Blatt), &6Gewürznelke&r (3), &6Muskat&r (3) und &6Sternanis&r (3). &6Zimt&r (Palisander und Teak) kommt nicht vom Blatt, sondern von der Rinde: Zimtstämme im Entrinder oder mit der Axt entrindet geben je einen Zimt.",
              "",
              fruit_pic("cinnamon"),
              "",
              "Die Gewürze sind keine Nahrung, und kein Rezept im Pack verwendet sie, sie landen in Kisten als Deko. Ihr Wert liegt im Stammbaum: Nelke und Piment ergeben den Sternanis, Mango und Sternanis die Sternfrucht, die letzte Kreuzung überhaupt.",
              "",
              "Der &6Lorbeer&r steht im Mod, hat aber weder Rezept noch Marktplatz, den gibt es auf Kronwerke nicht.",
          ],
          tasks=[task_item("productivetrees:cinnamon_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 6), reward_table("s1_uncommon")],
          deps=["stripper", "pollinated"], icon="productivetrees:cinnamon", optional=True),

    quest("dyes", 16, 1.0, "&5Züchte Farbbäume",
          subtitle="Blauholz und Gelbholz färben.",
          description=[
              "Das &6Blauholz&r (Kapok und Palisander, Generation 7) gibt im &6Sägewerk&r neben Brettern und Sägemehl ein &5Hämatoxylin&r. Zwei davon nebeneinander ergeben &e2 Blauen Farbstoff&r, zwei übereinander &e2 Lila Farbstoff&r.",
              "",
              pic("productivetrees:haematoxylin"),
              "",
              "&6Brasilholz&r (Teak und Mahagoni, Generation 6) gibt im Sägewerk ebenfalls Hämatoxylin, der kürzere Weg. &6Gelbholz&r (Rotahorn und Mahagoni) gibt &eFustik&r, das als gelber Farbstoff zählt, überall wo ein Rezept gelben Farbstoff per Tag verlangt.",
              "",
              "Das Blut des &6Drachenblutbaums&r wäre roter Farbstoff, braucht aber den Baumzapfen, siehe unten. Blauholz und Gelbholz sind die einzigen Farben, die hier wirklich fließen.",
          ],
          tasks=[task_item("productivetrees:haematoxylin", 2)],
          rewards=[reward_item("minecraft:lapis_lazuli", 8), reward_table("s1_uncommon")],
          deps=["sawmill_run", "pollinated"], icon="productivetrees:haematoxylin", optional=True),

    quest("hardwood", 18.5, 1.0, "&6Pflanz ein Edelholz",
          subtitle="Mahagoni, Ebenholz, Teak, Zebrano: Holz zum Angeben.",
          description=[
              "Kauf ein &6Ceylon-Ebenholz&r (Generation 3, 4 Smaragde). Es trägt keine Früchte, dafür sind seine Bretter fast schwarz. Mit Kapok wird daraus das Gelbe Meranti, daraus mit Kapok der &6Mahagoni&r, der Vater von Brasilholz, Palisander, Greenheart, Gelbholz und Sandelholz.",
              "",
              "&eDunkel:&r Ceylon-Ebenholz, Myrten-Ebenholz, Wenge, Blauholz. &eHell:&r Balsa, Silberpappel, Espe, Buchsbaum. &eBunt:&r Padauk, Purpleheart, Pink Ivory, Zebrano, Cocobolo, Regenbogeneukalyptus, Blue Mahoe. Jedes Holz hat seine eigenen Bretter, Stufen, Türen und Regale.",
              "",
              "Die Riesenformen aus 2x2 und 5x5 Setzlingen liefern bei Mahagoni, Ebenholz, Purpleheart und Mammutbaum Stämme im Hunderterpack, ideal für die Create-Säge.",
          ],
          tasks=[task_item("productivetrees:ceylon_ebony_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 3), reward_xp(3)],
          deps=["first_tree"], icon="productivetrees:ceylon_ebony_planks"),

    quest("conifers", 11, 3.2, "&2Pflanz eine Lawson-Zypresse",
          subtitle="Nadelbäume: Lärche, Tannen, Kiefern, Mammutbaum.",
          description=[
              "Kauf eine &6Lawson-Zypresse&r (Gelbkiefer und Fichte, 4 Smaragde), sie wächst einzeln oder als 3x3-Riese. Aus Fichte und Birke kommt die &6Europäische Lärche&r, aus ihr Gelbkiefer und Eibe, dann Balsamtanne, Weißtanne, Zeder, Douglasie, Weihrauchkiefer, Westliche Hemlocktanne, Wacholder und Araukarie.",
              "",
              "Die &6Westliche Hemlocktanne&r (Gelbkiefer und Weißtanne) ist die einzige Kreuzung, die bei jedem Versuch gelingt. Der &6Mammutbaum&r braucht 5x5 Setzlinge, mit 9x9 wird er zum größten Baum des Mods.",
              "",
              "Nadelbäume tragen nichts außer Wacholderbeeren (3 pro Blatt). Sie sind Holzlieferanten und Eltern: Amberbaum plus Weihrauchkiefer ergibt den &6Gummibaum&r.",
          ],
          tasks=[task_item("productivetrees:lawson_cypress_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 3), reward_xp(3)],
          deps=["first_tree"], icon="productivetrees:lawson_cypress_sapling"),

    quest("strip_drops", 13.5, 3.2, "&6Züchte die Korkeiche",
          subtitle="Drei Bäume verstecken etwas unter der Rinde.",
          description=[
              "Kreuz &6Lawson-Zypresse&r und &6Eiche&r (10 Prozent) zur &6Korkeiche&r und schick ihre Stämme durch den &6Entrinder&r: pro Stamm ein &6Kork&r im Rindenslot. Zimtstämme geben &6Zimt&r, die Stämme des &6Slimy Delight&r einen &aSchleimball&r.",
              "",
              pic("productivetrees:cork"),
              "",
              "Kork hat im Pack kein Rezept, er ist ein Sammelstück. Der Schleimball dagegen ist ein echter Grund für den Slimy Delight: eine Schleimfarm aus Holz, ohne Sumpf und ohne Schleimkreide. Der Baum ist ein leuchtender Hybrid aus Rippling Willow und Soul Tree, siehe rechts.",
              "",
              "Von Hand geht es auch: Axt-Rechtsklick auf den Stamm entrindet ihn und lässt den Kork oder Schleim fallen. Holz-Blöcke (4 Stämme) geben beim Entrinden nichts, nur Stämme.",
          ],
          tasks=[task_item("productivetrees:cork", 4)],
          rewards=[reward_item("minecraft:slime_ball", 4), reward_xp(5)],
          deps=["stripper", "conifers", "pollinated"], icon="productivetrees:cork", optional=True),

    quest("tap", 16, 3.2, "&cGummi, Ahornsirup und Sandelöl",
          subtitle="Fünf Bäume brauchen einen Zapfhahn, den es hier nicht gibt.",
          description=[
              "Der &6Gummibaum&r, der &6Zuckerahorn&r, das &6Sandelholz&r, die &6Dattelpalme&r und der &6Drachenblutbaum&r sollen angezapft werden: &6Gummi&r, &6Ahornsaft&r, &6Sandelholzöl&r, &6Dattelsaft&r und &cDrachenblut&r. Dafür braucht der Mod den Mod &6Tree Tap&r.",
              "",
              pic("productivetrees:rubber"),
              "",
              "&cTree Tap ist auf Kronwerke nicht installiert.&r Diese fünf Produkte gibt es hier nicht, der Gummibaum lässt sich nicht anzapfen. Vulkanisierter Gummi, Ahornsirup und der Zucker daraus bleiben Einträge in JEI ohne Weg.",
              "",
              "Die Bäume selbst wachsen trotzdem, geben Holz und zählen für die Checkliste. Der Gummibaum (Generation 5) ist Elternteil von nichts, züchte ihn also nur für die Liste. Der Zuckerahorn steht im Markt und ist Vater von Amberbaum, Sykomore, Süßem Holzapfel und Brotfrucht.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_item("minecraft:emerald", 2), reward_xp(3)],
          deps=["first_tree"], icon="productivetrees:rubber_tree_sapling", optional=True),

    quest("mutations", 18.5, 3.2, "&dLass einen Setzling mutieren",
          subtitle="Jeder zwanzigste Baum wird eine andere Art.",
          description=[
              "Pflanz &6Ipe&r-Setzlinge (Teak und Schwarzeiche, im Markt für 2 Smaragde) und lass sie wachsen. Mit &e5 Prozent&r wächst statt des Ipe ein &6Weißer Ipe&r, dessen Blätter Setzlinge der neuen Art abwerfen. Aus Weißem Ipe wird so Rosa Ipe, aus Rosa Ipe Lila Ipe, immer 5 Prozent pro gewachsenem Baum.",
              "",
              "Dieselbe Mutation gibt es bei der &6Buche&r (wird zur &6Blutbuche&r), der &6Schlehe&r (&6Purpurschlehe&r) und der &6Purpur-Kreppmyrte&r (Rote, dann Tuscarora-, dann Moonlight-Magic-Kreppmyrte). Diese fünf Mutationen stehen für je 2 Smaragde im Markt, die drei Ipe-Farben nicht.",
              "",
              "&eTipp:&r Knochenmehl zählt. Pflanz zwanzig Ipe in einer Reihe, dünge durch und schau, welcher aus der Reihe tanzt. Setzlinge gibt es nach dem Fällen aus den Blättern zurück.",
          ],
          tasks=[task_item("productivetrees:white_ipe_sapling", 1)],
          rewards=[reward_item("productivetrees:ipe_sapling", 4), reward_table("s1_uncommon")],
          deps=["first_tree"], icon="productivetrees:white_ipe_sapling", optional=True),

    # ---- Fundstücke und leuchtende Bäume ----------------------------------------------
    quest("loot_saplings", 11, 5.8, "&bFinde einen Setzling in einer Truhe",
          subtitle="Sechs Bäume gibt es nur als Fundstück.",
          description=[
              "Sechs Setzlinge wachsen aus keiner Kreuzung: &6Blue Yonder&r liegt in &eSchiffswrack-Schatztruhen&r (30 Prozent), &6Flickering Sun&r in &eWüstentempeln&r (15), &6Firecracker&r in &eAntiken Städten&r (15), &6Brown Amber&r kommt beim Ausgraben verdächtigen Kieses in &ekalten Ozeanruinen&r (10).",
              "",
              fruit_pic("planet_peach"),
              "",
              "&6Black Ember&r liegt in Bastionstruhen (30 Prozent) und kommt mit dem Nether in Stufe 2, der &6Soul Tree&r in Endsiedlungen (5 Prozent) mit dem End in Stufe 4. Keines der Fundstücke steht im Markt.",
              "",
              "Alle sechs sind &efeuerfest&r wie Netherholz, und bis auf Brown Amber leuchten sie (Lichtlevel 11, Flickering Sun 14). Blue Yonder trägt den &6Planetenpfirsich&r, der satt macht wie eine Goldene Karotte, wächst aber am Baum extrem langsam (Tempo 0,1), nimm den Pflanztopf. Firecracker trägt &6Feuerwerksraketen&r, eine pro Blatt.",
          ],
          tasks=[task_item("productivetrees:blue_yonder_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 4), reward_table("s1_uncommon")],
          deps=["first_tree"], icon="productivetrees:blue_yonder_sapling", optional=True),

    quest("amber", 13.5, 5.8, "&6Grab den Brown Amber aus",
          subtitle="Ein Baum, der Bernstein tropft.",
          description=[
              "Pinsle &everdächtigen Kies&r in kalten Ozeanruinen. Jeder zehnte Fund ist ein &6Brown-Amber-Setzling&r. Er wächst nur als &e3x3&r (oder 5x5) und seine Fruchtblätter tragen nichts, sie tropfen: Unter dem Baum sammeln sich &6Bernsteinpfützen&r, Schicht für Schicht, bis sie überlaufen.",
              "",
              "Die Pfützen sind reine Deko, man kann sie nicht aufsammeln. Das Holz ist feuerfest, die Blätter durchscheinend wie Glas. Ein Baum für den Garten, nicht für die Fabrik.",
              "",
              "Brown Amber ist Elternteil von nichts, braucht also keinen Partner. Der Setzling kommt beim Fällen aus den Blättern zurück, einer reicht für immer.",
          ],
          tasks=[task_item("productivetrees:brown_amber_sapling", 1)],
          rewards=[reward_item("minecraft:brush", 1), reward_table("s1_uncommon")],
          deps=["loot_saplings"], icon="productivetrees:brown_amber_sapling", optional=True),

    quest("glow_hybrids", 16, 5.8, "&dZüchte die leuchtenden Hybriden",
          subtitle="Zehn Bäume, die nur aus Fundstücken entstehen.",
          description=[
              "Kreuz zwei Fundstücke miteinander, immer mit &e5 Prozent&r: Blue Yonder und Firecracker ergeben &6Purple Spiral&r, Blue Yonder und Flickering Sun &6Rippling Willow&r, Firecracker und Flickering Sun &6Thunder Bolt&r, Blue Yonder und Soul Tree &6Water Wonder&r, Firecracker und Soul Tree &6Sparkle Cherry&r.",
              "",
              "Zweite Runde: Blue Yonder und Rippling Willow ergeben &6Time Traveller&r, Rippling Willow und Soul Tree &6Slimy Delight&r (Schleim aus der Rinde), Purple Spiral und Sparkle Cherry &6Night Fuchsia&r. Mit Black Ember aus Stufe 2: &6Cave Dweller&r und daraus &6Foggy Blast&r.",
              "",
              "Alle leuchten und sind feuerfest, Cave Dweller, Purple Spiral, Water Wonder und Blue Yonder lassen Blätter rieseln, Foggy Blast und Water Wonder sind durchscheinend. Der Thunder Bolt wächst als Blitzzacke. In Stufe 1 schaffst du Purple Spiral, Rippling Willow, Thunder Bolt und Time Traveller, der Rest wartet auf Soul Tree und Black Ember.",
          ],
          tasks=[task_item("productivetrees:purple_spiral_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 6), reward_table("s1_uncommon")],
          deps=["loot_saplings", "pairs"], icon="productivetrees:purple_spiral_sapling", optional=True),

    quest("time_traveller", 18.5, 5.8, "&dBau das Time-Traveller-Display",
          subtitle="Ein Schaukasten aus dem seltensten Holz.",
          description=[
              "&eRezept:&r oben und unten je drei &6Time-Traveller-Bretter&r, in der Mitte &6Faden&r, &6Glas&r, &6Faden&r. Das &6Time-Traveller-Display&r ist ein Block mit einem Slot, der den Gegenstand darin sichtbar ausstellt, wie ein Rahmen mit Glas davor.",
              "",
              "Das Holz dafür gibt es nur vom &6Time Traveller&r, der Kreuzung aus Blue Yonder und Rippling Willow, mit 5 Prozent. Ein Baum liefert Stämme genug, im Pflanztopf alle zwei Minuten zwei weitere.",
              "",
              "Das ist das einzige Funktionsrezept, das an ein bestimmtes Holz gebunden ist. Wer es baut, hat die halbe leuchtende Reihe hinter sich.",
          ],
          tasks=[task_item("productivetrees:time_traveller_display", 1)],
          rewards=[reward_item("minecraft:emerald", 8), reward_table("s1_rare")],
          deps=["glow_hybrids"], icon="productivetrees:time_traveller_display", optional=True),

    # ---- Züchten ----------------------------------------------------------------------
    quest("station", 0, 10.5, "&e&lBau eine Zuchtstation",
          subtitle="Ein Bienenstock, zwei Bäume, Blumen, Geduld.",
          description=[
              "Pflanz zwei verschiedene Bäume so, dass Blätter von beiden höchstens &e4 Blöcke&r von einem &6Bienennest&r oder &6Bienenstock&r entfernt sind, und setz Blumen daneben. Jedes Mal, wenn eine Biene mit Pollen von einer Blume heimkommt, versucht sie &eeinmal&r, ein Blatt in diesem Würfel zu bestäuben.",
              "",
              "So läuft ein Versuch: Die Biene sammelt alle Blattarten im 9x9x9-Würfel um den Stock, sucht alle Kreuzungen, die aus zwei davon möglich sind, würfelt eine aus und prüft deren Chance. Klappt es, wird ein Blatt eines der beiden Eltern zum &6bestäubten Blatt&r.",
              "",
              "&eTipp:&r Mehrere Stöcke mit je drei Bienen vervielfachen die Versuche. Stell nur die zwei Bäume in Reichweite, die du kreuzen willst, sonst würfelt die Biene auch die unerwünschten Paare aus. Die erste Kreuzung, Eiche und Birke zur Buche, steht im Kapitel &6Kochen&r.",
          ],
          tasks=[task_item("minecraft:beehive", 1), task_item("minecraft:spyglass", 1)],
          rewards=[reward_item("minecraft:honeycomb", 6), reward_table("s1_common")],
          deps=["first_tree"], icon="minecraft:bee_nest", size=1.5, shape="hexagon"),

    quest("pairs", 2.5, 10.5, "&eLies die Chancen richtig",
          subtitle="5, 10 oder 50 Prozent, und ein Paar mit zwei Kindern.",
          description=[
              "JEI zeigt unter &eBaumbestäubung&r zu jedem Setzling die beiden Elternblätter und die Chance. &e116 Kreuzungen&r haben 10 Prozent, &e27&r nur 5 Prozent, die ersten Vanilla-Paare 35 bis 55 Prozent. Die Westliche Hemlocktanne gelingt bei jedem Versuch.",
              "",
              "&eZwei Kinder, ein Paar:&r Eiche und Birke ergeben Buche oder Silberlinde, Buche und Birke Erle oder Pekannuss, Silberlinde und Kirsche Walnuss, Vogelkirsche oder Hartriegel, Pflaume und Pfirsich Aprikose oder Nektarine. Die Biene würfelt jedes Mal neu, welches Rezept sie versucht.",
              "",
              "&eMehrere erlaubte Blätter:&r Beim Red-Delicious-Apfel darf statt Eiche auch Schwarzeiche stehen, bei Silberweide und Silberpappel Eiche oder Birke. JEI zeigt die Alternativen im Wechsel.",
              "",
              "&eKronwerke:&r Der Markt nimmt dir die ersten drei Generationen ab. Ab &eGeneration 4&r (Hasel, Holunder, Korkeiche, Zitronatzitrone und 83 weitere) führt kein Weg am Züchten vorbei, und JEI zeigt dir zu jedem Ziel die Eltern, die du kaufen kannst.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("minecraft:emerald", 2), reward_xp(3)],
          deps=["station"], icon="productivetrees:silver_lime_sapling"),

    quest("pollinated", 5, 10.5, "&eZüchte die Hasel",
          subtitle="Fernrohr raus, Blatt abschlagen, Setzling einstecken.",
          description=[
              "Stell &6Espe&r und &6Buche&r (beide im Markt) an deine Zuchtstation, mit 10 Prozent pro Versuch entsteht die &6Hasel&r, die erste Art, die es nicht zu kaufen gibt.",
              "",
              "Ein &6bestäubtes Blatt&r sieht aus wie vorher. Halt ein &6Fernrohr&r in die Hand (Haupt- oder Nebenhand reicht, nicht hindurchschauen), dann sprühen bestäubte Blätter grüne Funken. Schlag das Blatt ab, und der &6Setzling der neuen Art&r fällt heraus, egal mit welchem Werkzeug.",
              "",
              pic("minecraft:spyglass"),
              "",
              "Bestäubte Blätter zerfallen nie, auch wenn du den Baum fällst. Du kannst also erst den Stamm nehmen und danach in Ruhe suchen. Ein bestäubtes Blatt wird nicht noch einmal bestäubt, und Fruchtblätter werden nie bestäubt, nur normale Blätter.",
              "",
              "Pflanz den neuen Setzling, fäll den Baum, und seine normalen Blätter geben mit 5 Prozent (Glück III: 10) weitere Setzlinge. Ab zwei Setzlingen bist du die Art nie wieder los.",
          ],
          tasks=[task_item("productivetrees:hazel_sapling", 1)],
          rewards=[reward_item("minecraft:emerald", 4), reward_table("s1_uncommon"), reward_xp(5)],
          deps=["station"], icon="productivetrees:hazel_sapling"),

    quest("pollen", 7.5, 10.5, "&eBestäube ein Blatt mit Pollen",
          subtitle="Gezielt kreuzen, ohne Würfeln.",
          description=[
              "Leg Blätter in den &6Pollensieber&r (Rezept im Kapitel &6Kochen&r, auf Kronwerke extra wieder eingebaut). Alle &e30 Sekunden&r verbraucht er ein Blatt und gibt mit &e11 Prozent&r einen &6Pollen&r dieser Baumart, im Schnitt also einen pro neun Blätter. Blätter erntest du mit der Schere.",
              "",
              pic("productivetrees:pollen"),
              "",
              "Rechtsklick mit dem Pollen auf ein Blatt eines anderen Baums macht es &esofort&r zum bestäubten Blatt mit der passenden Kreuzung, ohne Chance-Wurf. Für die 5-Prozent-Kreuzungen ist das der Weg. Gibt es keine Kreuzung, fällt ein Setzling eines der beiden Eltern heraus.",
              "",
              "&eStufe 2:&r Das &6Pollensieb-Upgrade&r (Upgrade-Basis, zwei Papier, zwei Glasflaschen, vier Setzlinge) im Fortgeschrittenen Bienenstock liefert bei 2 Prozent der Heimflüge Pollen eines Baums in Reichweite, Reichweiten-Upgrades vergrößern den Würfel um 2 Blöcke pro Stück.",
              "Die &6Allergie-Biene&r entsteht, wenn du einer Biene Pollen gibst (10 Prozent). Sie bringt fünfmal so oft Pollen, und ihre Kreuzungen gelingen fünfmal so oft, aus 10 werden 50 Prozent.",
          ],
          tasks=[task_item("productivetrees:pollen", 1)],
          rewards=[reward_item("minecraft:shears", 1), reward_table("s1_common"), reward_xp(5)],
          deps=["pairs"], icon="productivetrees:pollen"),

    quest("star_fruit", 10.5, 10.5, "&6&lErnte die Sternfrucht",
          subtitle="Neun Generationen Stammbaum enden hier.",
          description=[
              "Zieh eine &6Sternfrucht&r und ernte &e8 Sternfrüchte&r. Der Baum ist die tiefste Kreuzung des Mods: Mango (Orange und Mangrove) und Sternanis (Nelke und Piment), hinter denen neun Generationen stehen, von Eiche und Birke bis zur Pomelo.",
              "",
              fruit_pic("star_fruit"),
              "",
              "Der Markt hilft bis Generation 3 (Kakao, Ceylon-Ebenholz, Silberlinde und Sauerkirsche kannst du kaufen), die restlichen sechs Generationen züchtest du selbst, mit Bienen oder Pollen. Die Checkliste darunter führt alle 148 Kreuzungen nach Generationen auf, mit Eltern und Chance, ein Haken pro Art.",
              "",
              "&eKronwerke:&r Ein Baumgarten mit Sägewerk, Pflanztöpfen und einer Create-Säge liefert Bretter für die Mühle und die Pressen des Steinwerks und Essen für alle. Und er sieht besser aus als jede Erzstraße.",
          ],
          tasks=[task_item("productivetrees:star_fruit", 8)],
          rewards=[reward_table("s1_rare"), reward_item("minecraft:emerald", 8), reward_xp(15)],
          deps=["pollinated", "crates"], icon="productivetrees:star_fruit_sapling", size=2.0, shape="gear"),

    # ---- Checkliste: alle Kreuzungen --------------------------------------------------
    checklist("gen1", 0, 15, "&aGeneration 1: aus Vanilla und Fundstücken", G1, ["pairs"],
              "productivetrees:beech_sapling",
              "Die Eltern sind Vanilla-Bäume oder die sechs Fundstücke. Die sechs Vanilla-Kreuzungen stehen für 1 Smaragd im Markt, Black Ember kommt in Stufe 2, Soul Tree in Stufe 4."),
    checklist("gen2a", 2.5, 15, "&aGeneration 2: Erle bis Rotahorn", G2[:12], ["gen1"],
              "productivetrees:walnut_sapling",
              "Ein Elternteil ist eine Kreuzung der ersten Generation. Alle zwölf stehen für 2 Smaragde im Markt."),
    checklist("gen2b", 5, 15, "&aGeneration 2: Nashi-Birne bis Silberweide", G2[12:], ["gen2a"],
              "productivetrees:slimy_delight_sapling",
              "Zweite Generation, zweiter Teil. Nashi-Birne bis Hartriegel und die Silberweide stehen für 2 Smaragde im Markt, die leuchtende Reihe nicht."),
    checklist("gen3a", 7.5, 15, "&aGeneration 3: Adlerholz bis Kulturbirne", G3[:10], ["gen2b"],
              "productivetrees:banana_sapling",
              "Dritte Generation, erster Teil, im Markt für 4 Smaragde."),
    checklist("gen3b", 10, 15, "&aGeneration 3: Ulme bis Mehlbeere", G3[10:21], ["gen3a"],
              "productivetrees:sweet_chestnut_sapling",
              "Dritte Generation, zweiter Teil, im Markt für 4 Smaragde."),
    checklist("gen3c", 12.5, 15, "&aGeneration 3: Blue Mahoe bis Silberpappel", G3[21:], ["gen3b"],
              "productivetrees:sugar_maple_sapling",
              "Dritte Generation mit 5 Prozent, darunter Mammutbaum und Zuckerahorn, im Markt für 4 Smaragde. Danach verkauft der Markt nichts mehr."),
    checklist("gen4a", 15, 15, "&aGeneration 4: Beliy Naliv bis Eberesche", G4[:12], ["gen3c"],
              "productivetrees:cork_oak_sapling",
              "Vierte Generation, erster Teil. Ab hier nur noch durch Züchten."),
    checklist("gen4b", 17.5, 15, "&aGeneration 4: Weißtanne bis Zebrano", G4[12:], ["gen4a"],
              "productivetrees:zebrano_sapling",
              "Vierte Generation, zweiter Teil."),
    checklist("gen5a", 0, 17.5, "&aGeneration 5: Hemlocktanne bis Stechpalme", G5[:11], ["gen4b"],
              "productivetrees:douglas_fir_sapling",
              "Fünfte Generation, erster Teil. Die Hemlocktanne gelingt immer."),
    checklist("gen5b", 2.5, 17.5, "&aGeneration 5: Wacholder bis Pflaume", G5[11:], ["gen5a"],
              "productivetrees:rubber_tree_sapling",
              "Fünfte Generation, zweiter Teil, mit dem Gummibaum."),
    checklist("gen6a", 5, 17.5, "&aGeneration 6: Mandel bis Greenheart", G6[:10], ["gen5b"],
              "productivetrees:almond_sapling",
              "Sechste Generation, erster Teil."),
    checklist("gen6b", 7.5, 17.5, "&aGeneration 6: Zitrone bis Granatapfel", G6[10:], ["gen6a"],
              "productivetrees:lemon_sapling",
              "Sechste Generation, zweiter Teil, die Zitrusfrüchte."),
    checklist("gen7a", 10, 17.5, "&aGeneration 7: Piment bis Blauholz", G7[:8], ["gen6b"],
              "productivetrees:cinnamon_sapling",
              "Siebte Generation, erster Teil, die Gewürze."),
    checklist("gen7b", 12.5, 17.5, "&aGeneration 7: Nektarine bis Sandelholz", G7[8:], ["gen7a"],
              "productivetrees:orange_sapling",
              "Siebte Generation, zweiter Teil."),
    checklist("gen89", 15, 17.5, "&aGeneration 8 und 9: bis zur Sternfrucht", G89, ["gen7b"],
              "productivetrees:star_fruit_sapling",
              "Die letzten sieben Kreuzungen. Mit der Sternfrucht ist der Stammbaum vollständig."),
]

images = [
    banner("productive_trees/title", "Productive Trees", 9, -4.4, height=1.8, kind="title", colour="nature"),
    banner("productive_trees/markt", "Der Markt und die Ernte", 3.75, -1.7, height=0.9, colour="brass"),
    banner("productive_trees/holz", "Holz", 3.75, 3.9, height=0.9, colour="stone"),
    banner("productive_trees/familien", "Die Baumfamilien", 14.75, -2.9, height=0.9, colour="nature"),
    banner("productive_trees/funde", "Fundstücke und leuchtende Bäume", 14.75, 4.5, height=0.9, colour="magic"),
    banner("productive_trees/zucht", "Züchten", 5.25, 8.7, height=0.9, colour="nature"),
    banner("productive_trees/liste", "Checkliste: alle 148 Kreuzungen", 8.75, 13.2, height=0.9, colour="brass"),
]

chapter(C, "Productive Trees", "productivetrees:hazel_sapling", "world", quests, shape="circle", order=66, stage=1,
        subtitle=["Stufe 1. Der Markt, 163 Baumarten, Obst, Nüsse, Holz, Züchten mit Bienen und die Checkliste aller Kreuzungen."],
        images=images)
