"""Refined Storage 2 in stage 3: quartz enriched iron, silicon and the three processors (bound
and smelted, no machine), the machine casing and cores, the controller, cables, grids, the disk
drive and disks up to 16k, importer, exporter, external storage, wireless access, autocrafting
with the pattern grid and autocrafters, and the elite and ultra tiers of Cable Tiers. Recipes
are the mod's own, Kronwerke changes none of them. 64k disks and the Cable Tiers mega tier
(dragon head) are stage 4 and only mentioned."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "refined_storage"

quests = [
    # ---- Quarz und Prozessoren ---------------------------------------------
    quest("welcome", 0, 1, "&3&lRefined Storage",
          subtitle="Das einfachere Lagernetz.",
          description=[
              "&eRezept:&r Drei &6Eisenbarren&r und ein &6Netherquarz&r im 2x2-Feld (Eisen oben links, oben rechts, unten links, Quarz unten rechts) ergeben vier &6Quarzangereichertes Eisen&r. Mach gleich zwei Stapel, es steckt in fast allem.",
              "",
              "&3Refined Storage&r (kurz RS) macht dasselbe wie AE2: Gegenstände liegen auf Speicherzellen, ein Kabelnetz verbindet alles, und du suchst in einer Konsole. Der Unterschied liegt im Aufwand.",
              "",
              "&eWo RS anders ist:&r Es gibt &ekeine Kanäle&r, du hängst so viele Geräte ans Kabel, wie du willst. Prozessoren kommen aus dem Ofen statt aus einer Maschine. Eine Zelle zählt &ekeine Typen&r, nur Stück. Autocrafting braucht nur Rezepte und einen Autohersteller, keinen Multiblock.",
              "",
              "&eWas RS nicht hat:&r P2P-Tunnel, Raumspeicher, die Tiefe an Zusatzmods. Wer ein großes Netz mit vielen Unterwerken plant, ist bei AE2 besser aufgehoben. Wer ein Lager will, das in einer Stunde steht, ist hier richtig.",
              "",
              "&eWas in Stufe 3 offen ist:&r alles bis zur &616k-Zelle&r, Autocrafting und die Elite- und Ultra-Geräte von &6Cable Tiers&r. &cWas noch wartet:&r 64k-Zellen und die Mega-Geräte kommen in Stufe 4.",
          ],
          tasks=[task_item("refinedstorage:quartz_enriched_iron", 16)],
          rewards=[reward_item("minecraft:quartz", 16), reward_table("s3_common")],
          icon="refinedstorage:controller", size=2.0, shape="hexagon"),

    quest("silicon", 2.5, 0, "&7Schmilz Silizium",
          subtitle="Netherquarz im Ofen.",
          description=[
              "Leg &6Netherquarz&r in den Ofen oder Schmelzofen, heraus kommt &6Silizium&r. Ein Quarz, ein Silizium.",
              "",
              "Silizium steckt in jedem Prozessor, im Kontrollblock und in jedem 1k-Speicherkern. Ein Stapel reicht für den Anfang, zwei sind besser.",
              "",
              "&eTipp:&r Das Silizium von AE2 (aus Certusquarzstaub) zählt in allen RS-Rezepten genauso, und umgekehrt. Wer beide Mods spielt, braucht nur eine Siliziumquelle.",
          ],
          tasks=[task_item("refinedstorage:silicon", 16)],
          rewards=[reward_item("minecraft:quartz", 16), reward_xp(3)],
          deps=["welcome"]),

    quest("binding", 2.5, 2, "&aMach Prozessor-Rohmaterial",
          subtitle="Faden, Schleim, Faden.",
          description=[
              "&eRezept:&r Ein &6Faden&r, ein &6Schleimball&r und noch ein Faden in einer Reihe ergeben acht &6Prozessor-Rohmaterial&r (Processor Binding).",
              "",
              "Das ist die Grundlage jedes Prozessors. Acht Stück pro Schleimball, also reicht ein kleiner Vorrat Schleim für lange Zeit.",
          ],
          tasks=[task_item("refinedstorage:processor_binding", 8)],
          rewards=[reward_item("minecraft:slime_ball", 4), reward_item("minecraft:string", 16)],
          deps=["welcome"], icon="refinedstorage:processor_binding"),

    quest("processors", 5, 1, "&b&lBack die Prozessoren",
          subtitle="Rohmaterial, Metall, Silizium, Redstone, dann in den Ofen.",
          description=[
              "&eRezept:&r Prozessor-Rohmaterial, ein &6Silizium&r, ein &6Redstone&r und ein Metall formlos zusammen ergeben einen Rohprozessor. &6Eisenbarren&r für den Basisprozessor, &6Goldbarren&r für den Verbesserten, &6Diamant&r für den Fortschrittlichen. Dann den Rohprozessor im Ofen backen.",
              "",
              "Anders als bei AE2 gibt es keine Gravurmaschine und keine Pressen. Ein Ofen reicht, und der Schmelzofen ist doppelt so schnell.",
              "",
              "&eWofür:&r Basisprozessoren für Kerne und 4k-Speicherkerne. Verbesserte für Konsole, Importeur, Exporteur und 16k-Kerne. Fortschrittliche für Autohersteller und alles Drahtlose, Kontrollblock und Laufwerk nehmen auf Kronwerke einen Fortgeschrittenen Steuerschaltkreis. Ein Dutzend von jeder Sorte ist ein guter Vorrat.",
          ],
          tasks=[task_item("refinedstorage:basic_processor", 4), task_item("refinedstorage:improved_processor", 4),
                 task_item("refinedstorage:advanced_processor", 4)],
          rewards=[reward_item("minecraft:diamond", 4), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["silicon", "binding"], icon="refinedstorage:advanced_processor", size=2.0, shape="gear"),

    quest("casing", 7.5, 0, "&7Bau ein Maschinengehäuse",
          subtitle="Acht Quarzeisen um einen Stein.",
          description=[
              "&eRezept:&r Acht &6Quarzangereichertes Eisen&r rundherum, ein &6Stein&r in der Mitte ergeben ein &6Maschinengehäuse&r.",
              "",
              "Jeder Block von RS, der kein Kabel ist, hat ein Gehäuse in der Mitte: Kontrollblock, Konsole, Laufwerk, Schnittstelle, Funksender, Autohersteller. Vier Stück reichen für das erste Netz.",
          ],
          tasks=[task_item("refinedstorage:machine_casing", 4)],
          rewards=[reward_item("refinedstorage:quartz_enriched_iron", 16)],
          deps=["welcome"], icon="refinedstorage:machine_casing"),

    quest("cores", 7.5, 2, "&eMach die beiden Kerne",
          subtitle="Glowstone baut, Quarz zerstört.",
          description=[
              "&eRezept:&r Ein &6Basisprozessor&r und ein &6Glowstone-Staub&r formlos ergeben einen &6Konstruktionskern&r. Ein Basisprozessor und ein &6Netherquarz&r ergeben einen &6Zerstörungskern&r.",
              "",
              "Der Konstruktionskern steckt in allem, was aus dem Netz hinausgibt (Exporteur, Konstruktor), der Zerstörungskern in allem, was hineinholt (Importeur, Destruktor). Die Konsole will beide, der Autohersteller auf Kronwerke nur den Zerstörungskern.",
          ],
          tasks=[task_item("refinedstorage:construction_core", 2), task_item("refinedstorage:destruction_core", 2)],
          rewards=[reward_item("minecraft:glowstone_dust", 8), reward_item("minecraft:quartz", 8), reward_xp(3)],
          deps=["processors"], icon="refinedstorage:construction_core"),

    # ---- Das Netzwerk ----------------------------------------------------------
    quest("controller", 10.5, 1, "&3&lBau den Kontrollblock",
          subtitle="Der Strom für das ganze Netz.",
          description=[
              "&eRezept auf Kronwerke:&r Quarzeisen in die vier Ecken, ein &6Fortgeschrittener Steuerschaltkreis&r von Mekanism oben in die Mitte, &6Silizium&r links, rechts und unten, ein &6Maschinengehäuse&r ins Zentrum.",
              "",
              "Der &6Kontrollblock&r nimmt &dFE&r von jeder Seite an, ein Universalkabel von Mekanism oder Powah genügt. Er speichert &d1 000 FE&r und gibt sie an alle Geräte im Netz weiter. Was das Netz braucht, siehst du, wenn du ihn anklickst.",
              "",
              "&eKein Ritual, keine Kanäle:&r Anders als der ME-Controller braucht er keine seltenen Teile, und er verteilt keine Kanäle. Du darfst sogar mehrere Kontrollblöcke in ein Netz setzen, wenn der Strom nicht reicht.",
              "",
              "Zum Vergleich: Konsole 10 FE/t, Laufwerk 10 FE/t plus 4 pro Zelle, Importeur und Exporteur je 2 FE/t, Funksender 16 FE/t. Ein kleines Netz läuft mit unter &d50 FE/t&r.",
          ],
          tasks=[task_item("refinedstorage:controller", 1)],
          rewards=[reward_item("mekanism:basic_universal_cable", 16), reward_table("s3_common"), reward_xp(10)],
          deps=["processors", "casing"], icon="refinedstorage:controller", size=1.75, shape="gear"),

    quest("cable", 13, 0, "&bZieh Kabel",
          subtitle="Zwölf auf einen Schlag, ohne Kanäle.",
          description=[
              "&eRezept:&r Drei Kupferbarren und ein Netherquarz im 2x2-Feld ergeben vier &6Quarzangereichertes Kupfer&r. Davon drei oben und drei unten, in der Mitte Glas, &6Redstone&r, Glas: zwölf &6Kabel&r.",
              "",
              "Kabel verbinden alle RS-Blöcke und brauchen keinen Strom. Es gibt &ekeine Kanäle&r: Ein einziges Kabel trägt hundert Laufwerke, wenn der Kontrollblock genug Strom hat.",
              "",
              "&eFarben:&r Mit Farbstoff an der Werkbank färbst du Kabel und Geräte. Gefärbte Kabel verbinden sich nur mit derselben Farbe oder mit grauen. So laufen zwei Netze direkt nebeneinander.",
              "",
              "&eTipp:&r Volle Blöcke wie Laufwerk oder Konsole verbinden sich auch direkt miteinander, ganz ohne Kabel dazwischen.",
          ],
          tasks=[task_item("refinedstorage:cable", 24)],
          rewards=[reward_item("refinedstorage:cable", 24), reward_xp(3)],
          deps=["controller"]),

    quest("grid", 13, 2, "&bBau eine Konsole",
          subtitle="Das Fenster ins Lager.",
          description=[
              "&eRezept:&r Links oben und links unten je ein &6Verbesserter Prozessor&r, links in die Mitte Quarzeisen, oben in die Mitte ein &6Konstruktionskern&r, unten ein &6Zerstörungskern&r, ein Maschinengehäuse ins Zentrum, rechts drei &6Glas&r.",
              "",
              "Die &6Konsole&r zeigt alles im Netz. Linksklick holt einen Stapel, Rechtsklick ein Stück, Shift-Klick aus dem Inventar legt ein. Sie braucht 10 FE/t.",
              "",
              "&eSuchen:&r &e@mekanism&r zeigt nur Dinge aus einer Mod, &e#ingots&r nur Dinge mit einem Tag, &e$text&r sucht im Tooltip. Sortieren kannst du nach Menge, Name oder zuletzt geändert.",
          ],
          tasks=[task_item("refinedstorage:grid", 1)],
          rewards=[reward_item("minecraft:glass", 16), reward_xp(5)],
          deps=["controller", "cores"], icon="refinedstorage:grid"),

    quest("drive", 15.5, 1, "&3&lBau ein Laufwerk",
          subtitle="Acht Zellen in einem Block.",
          description=[
              "&eRezept auf Kronwerke:&r Quarzeisen rundherum, eine &6Truhe&r oben in die Mitte, ein &6Maschinengehäuse&r ins Zentrum, ein &6Fortgeschrittener Steuerschaltkreis&r von Mekanism unten in die Mitte.",
              "",
              "Das &6Laufwerk&r hat &e8 Plätze&r für Speicherzellen. Es braucht 10 FE/t plus 4 FE/t für jede Zelle darin. Stell es direkt an den Kontrollblock oder an ein Kabel.",
              "",
              "&ePriorität:&r Im Laufwerk stellst du ein, in welcher Reihenfolge das Netz einlagert. Höhere Zahl zuerst. Mit Filtern im Laufwerk bekommt eine Zelle nur bestimmte Dinge, zum Beispiel nur Erze.",
          ],
          tasks=[task_item("refinedstorage:disk_drive", 1)],
          rewards=[reward_item("refinedstorage:storage_housing", 2), reward_table("s3_common"), reward_xp(10)],
          deps=["grid"], icon="refinedstorage:disk_drive", size=1.75, shape="hexagon"),

    quest("disk_1k", 18, 0, "&7Mach eine 1k-Speicherzelle",
          subtitle="1 024 Stück, egal welcher Sorte.",
          description=[
              "&eRezept:&r Das &6Speichergehäuse&r ist Glas, Redstone, Glas oben, Redstone links und rechts, drei Quarzeisen unten, die Mitte bleibt leer. Der &61k-Speicherkern&r ist Silizium, Quarzeisen, Silizium oben, Glas, Redstone, Glas in der Mitte, Silizium, Glas, Silizium unten. Gehäuse und Kern formlos zusammen ergeben die &61k-Speicherzelle&r.",
              "",
              "Eine 1k-Zelle fasst &e1 024 Gegenstände&r. Und das ist alles, was du wissen musst: RS zählt &ekeine Typen&r. 1 024 verschiedene Dinge je ein Stück passen genauso hinein wie 1 024 Bruchstein. Die 63-Typen-Grenze von AE2 gibt es hier nicht.",
              "",
              "Ist eine Zelle leer, gibt ein Rechtsklick mit ihr in der Hand den Speicherkern zurück.",
              "",
              img(item_texture("refinedstorage:1k_storage_disk"), 32, 32),
          ],
          tasks=[task_item("refinedstorage:1k_storage_disk", 2)],
          rewards=[reward_item("refinedstorage:1k_storage_part", 2), reward_xp(5)],
          deps=["drive"], icon="refinedstorage:1k_storage_disk"),

    quest("disk_16k", 20.5, 0, "&bRüste auf 16k auf",
          subtitle="Das Größte, was Stufe 3 hergibt.",
          description=[
              "&eRezept:&r Der &64k-Speicherkern&r: vier &6Basisprozessoren&r in die Ecken, Quarzeisen oben in die Mitte, drei &61k-Speicherkerne&r links, rechts und unten, Redstone ins Zentrum. Der &616k-Speicherkern&r genauso, nur mit vier &6Verbesserten Prozessoren&r und drei 4k-Kernen.",
              "",
              "4k fasst &e4 096&r Stück, 16k &e16 384&r. Eine volle Zelle rüstest du auf, indem du sie mit dem größeren Kern an die Werkbank legst: Der Inhalt bleibt, der kleine Kern kommt zurück.",
              "",
              "Ein Laufwerk mit acht 16k-Zellen hält über 130 000 Gegenstände. Das reicht für eine ganze Stufe.",
              "",
              "&cAusblick:&r Der 64k-Kern (vier Fortschrittliche Prozessoren, drei 16k-Kerne) öffnet in Stufe 4.",
          ],
          tasks=[task_item("refinedstorage:4k_storage_disk", 1), task_item("refinedstorage:16k_storage_disk", 1)],
          rewards=[reward_item("refinedstorage:basic_processor", 8), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["disk_1k"], icon="refinedstorage:16k_storage_disk"),

    quest("crafting_grid", 18, 2, "&bBau eine Herstellungskonsole",
          subtitle="Werkbank mit Lager dahinter.",
          description=[
              "&eRezept:&r Eine &6Konsole&r, ein &6Fortschrittlicher Prozessor&r und eine &6Werkbank&r formlos zusammen.",
              "",
              "Die &6Herstellungskonsole&r hat ein Werkbankfeld, das direkt aus dem Netz zieht. Shift-Klick auf das Ergebnis craftet einen ganzen Stapel. Sie braucht 14 FE/t.",
              "",
              "&eTipp:&r Shift und Strg zusammen gedrückt zeigt die Konsole nur noch die Dinge, die in das gerade liegende Rezept passen.",
          ],
          tasks=[task_item("refinedstorage:crafting_grid", 1)],
          rewards=[reward_item("refinedstorage:improved_processor", 4), reward_xp(5)],
          deps=["grid"], icon="refinedstorage:crafting_grid"),

    quest("fluids", 20.5, 2, "&9Lagere Flüssigkeiten",
          subtitle="Eimer statt Redstone.",
          description=[
              "&eRezept:&r Der &664B-Flüssigspeicherkern&r ist der 1k-Kern mit einem leeren &6Eimer&r statt dem Redstone in der Mitte. Kern und Speichergehäuse ergeben die &664B-Flüssigspeicherzelle&r, sie fasst 64 Eimer.",
              "",
              "Flüssigzellen liegen im selben Laufwerk wie Gegenstandszellen. Lava, Wasser, Öl, Mekanism-Flüssigkeiten: alles, was in ein Rohr passt, kommt mit Importeur und Exporteur ins Netz. In der Konsole stellst du oben um, ob du Gegenstände oder Flüssigkeiten sehen willst.",
              "",
              "256B, 1024B und 4096B gehen wie bei den Gegenstandskernen, nur immer mit Eimer in der Mitte.",
          ],
          tasks=[task_item("refinedstorage:64b_fluid_storage_disk", 1)],
          rewards=[reward_item("minecraft:bucket", 4), reward_xp(5)],
          deps=["disk_1k"], icon="refinedstorage:64b_fluid_storage_disk", optional=True),

    # ---- Rein und raus ---------------------------------------------------------
    quest("importer", 0, 7, "&aSetz einen Importeur",
          subtitle="Holt alles aus einer Kiste ins Netz.",
          description=[
              "&eRezept:&r Ein &6Kabel&r, ein &6Zerstörungskern&r und ein &6Verbesserter Prozessor&r formlos zusammen.",
              "",
              "Der &6Importeur&r sitzt am Kabel und zeigt auf eine Kiste, einen Ofen oder eine Maschine. Alles, was dort liegt, zieht er ins Netz. Er braucht 2 FE/t. Mit dem &6Schraubenschlüssel&r (Quarzeisen und ein Basisprozessor) drehst du ihn in die richtige Richtung.",
              "",
              "&eFilter:&r Im Fenster legst du Gegenstände in die neun Filterplätze. Umschalten zwischen &eErlauben&r (nur das) und &eBlockieren&r (alles außer dem). Leer heißt: alles.",
          ],
          tasks=[task_item("refinedstorage:importer", 2)],
          rewards=[reward_item("refinedstorage:cable", 12), reward_xp(5)],
          deps=["drive"], icon="refinedstorage:importer"),

    quest("exporter", 2.5, 7, "&aSetz einen Exporteur",
          subtitle="Schiebt aus dem Netz hinaus.",
          description=[
              "&eRezept:&r Ein &6Kabel&r, ein &6Konstruktionskern&r und ein &6Verbesserter Prozessor&r formlos zusammen.",
              "",
              "Der &6Exporteur&r schiebt, was in seinen Filterplätzen liegt, aus dem Netz in den Block vor sich. Ohne Filter tut er nichts. Er braucht 2 FE/t.",
              "",
              "&eDer Klassiker:&r Exporteur mit Roheisen oben an einen Ofen, Importeur unten dran, fertig ist der Ofen, der nie leer läuft. Dasselbe geht mit der Anreicherungskammer, dem Schmelzer oder jeder Create-Maschine mit Eingang.",
          ],
          tasks=[task_item("refinedstorage:exporter", 2)],
          rewards=[reward_item("refinedstorage:construction_core", 2), reward_item("refinedstorage:destruction_core", 2), reward_xp(5)],
          deps=["importer"], icon="refinedstorage:exporter"),

    quest("upgrades", 2.5, 9, "&eBau Upgrades",
          subtitle="Zucker macht schnell.",
          description=[
              "&eRezept:&r Das leere &6Upgrade&r ist sechs Quarzeisen, Glas oben und unten in der Mitte, ein Verbesserter Prozessor im Zentrum. Mit drei &6Zucker&r und fünf Quarzeisen drumherum wird daraus ein &6Geschwindigkeitsupgrade&r. Vier Geschwindigkeitsupgrades und fünf Zucker im Schachbrett ergeben ein &6Stapelupgrade&r.",
              "",
              "Upgrades steckst du in die vier Plätze rechts im Fenster von Importeur, Exporteur und Co. Geschwindigkeit: schneller, 4 FE/t mehr. Stapel: ein ganzer Stapel pro Vorgang statt einem Stück, 16 FE/t mehr.",
              "",
              "Dazu gibt es das &6Regulationsupgrade&r (hält eine feste Menge im Ziel) und für Konstruktor und Destruktor &6Glück&r und &6Behutsamkeit&r aus dem passenden verzauberten Buch.",
          ],
          tasks=[task_item("refinedstorage:speed_upgrade", 2), task_item("refinedstorage:stack_upgrade", 1)],
          rewards=[reward_item("minecraft:sugar", 32), reward_xp(5)],
          deps=["exporter"], icon="refinedstorage:stack_upgrade", optional=True),

    quest("external", 5, 7, "&6Häng eine Kiste ans Netz",
          subtitle="Truhen, Schubladen, Tonnen als Speicher.",
          description=[
              "&eRezept:&r Oben ein &6Konstruktionskern&r, Quarzeisen, ein &6Zerstörungskern&r. In der Mitte &6Truhe&r, &6Kabel&r, Truhe. Unten Quarzeisen, ein &6Verbesserter Prozessor&r, Quarzeisen.",
              "",
              "Der &6Externe Speicher&r sitzt am Kabel und macht den Block vor sich zum Teil des Netzes. Eine Truhe, eine Schubladenwand, eine Mekanism-Tonne, ein Flüssigkeitstank: Alles darin erscheint in der Konsole, und das Netz lagert dort ein. Er braucht 6 FE/t.",
              "",
              "&eTipp:&r Eine Schubladenwand am Externen Speicher ist der billigste Massenspeicher für Bruchstein, Erde und Erze. Gib ihr im Fenster eine hohe Priorität, dann füllt sich die Wand vor den Zellen.",
          ],
          tasks=[task_item("refinedstorage:external_storage", 1)],
          rewards=[reward_item("minecraft:chest", 8), reward_table("s3_common"), reward_xp(5)],
          deps=["importer"], icon="refinedstorage:external_storage"),

    quest("interface", 5, 9, "&6Bau eine Schnittstelle",
          subtitle="Importeur und Exporteur in einem Block.",
          description=[
              "&eRezept:&r Ein &6Importeur&r oben in die Mitte, ein &6Exporteur&r unten, Redstone links und rechts, ein &6Maschinengehäuse&r ins Zentrum, Quarzeisen in die Ecken.",
              "",
              "Die &6Schnittstelle&r ist ein voller Block mit eigenen Plätzen: eine Reihe, in die alles kommt, was ins Netz soll, und Plätze, in denen sie eingestellte Gegenstände aus dem Netz bereithält. Trichter, Create-Förderbänder oder Mekanism-Transporter bedienen sie wie eine Kiste. Sie braucht 4 FE/t.",
              "",
              "Mit einem &6Autoherstellung-Upgrade&r (Quarzeisen, Konstruktionskern, zwei Werkbänke, ein Upgrade) bestellt sie fehlende Gegenstände beim Autocrafting nach.",
          ],
          tasks=[task_item("refinedstorage:interface", 1)],
          rewards=[reward_item("minecraft:hopper", 4), reward_xp(5)],
          deps=["exporter"], icon="refinedstorage:interface", optional=True),

    quest("wireless", 7.5, 7, "&d&lGeh drahtlos",
          subtitle="Das Lager in der Hosentasche.",
          description=[
              "&eRezept:&r Der &6Funksender&r ist sechs Quarzeisen, eine &6Enderperle&r oben in der Mitte, ein Maschinengehäuse im Zentrum, ein Fortschrittlicher Prozessor unten. Die &6Drahtlose Konsole&r genauso, nur mit einer &6Konsole&r statt dem Gehäuse.",
              "",
              "Der Funksender sitzt am Kabel und reicht &e16 Blöcke&r weit, jedes &6Reichweitenupgrade&r (fünf Quarzeisen, drei Enderperlen, ein Upgrade) bringt 8 Blöcke mehr. Er braucht 16 FE/t. Mehrere Sender decken eine ganze Basis ab.",
              "",
              "&eVerbinden:&r Rechtsklick mit der Drahtlosen Konsole auf irgendeinen Block des Netzes. Sie speichert 1 000 FE, jedes Öffnen und jeder Griff kostet 5 FE, aufgeladen wird sie in jedem Ladeplatz für FE-Gegenstände. Ein Tastenkürzel in den Steuerungseinstellungen öffnet sie ohne Griff zur Hotbar.",
              "",
              "&eTipp:&r Die &6Mobile Konsole&r (Quarzeisen, zwei Konsolen, ein Kontrollblock) nimmt eine Speicherzelle direkt auf und braucht gar kein Netz. Gut für den Nether-Ausflug.",
          ],
          tasks=[task_item("refinedstorage:wireless_transmitter", 1), task_item("refinedstorage:wireless_grid", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 8), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["crafting_grid"], icon="refinedstorage:wireless_grid", size=1.5, shape="hexagon"),

    quest("builders", 7.5, 9, "&cKonstruktor und Destruktor",
          subtitle="Blöcke setzen und abbauen.",
          description=[
              "&eRezept:&r Der &6Konstruktor&r ist Quarzeisen in den Ecken, ein &6Konstruktionskern&r oben, zwei &6Diamanten&r links und rechts, ein Kabel in der Mitte, ein Verbesserter Prozessor unten. Der &6Destruktor&r ist dasselbe mit einem &6Zerstörungskern&r oben.",
              "",
              "Der Konstruktor setzt den Block aus seinem Filter vor sich in die Welt, der Destruktor baut ab, was vor ihm steht, und legt es ins Netz. Je 3 FE/t.",
              "",
              "Zusammen sind sie ein Bruchsteingenerator ohne Hopper, ein Obsidian-Abbauer oder ein Werfer für Gegenstände, denn der Konstruktor kann auch Items fallen lassen. Mit dem Behutsamkeits-Upgrade holt der Destruktor sogar Glas heil zurück.",
          ],
          tasks=[task_item("refinedstorage:constructor", 1), task_item("refinedstorage:destructor", 1)],
          rewards=[reward_item("minecraft:diamond", 4), reward_xp(5)],
          deps=["external"], icon="refinedstorage:destructor", optional=True),

    quest("storage_monitor", 0, 9, "&7Häng einen Speichermonitor auf",
          subtitle="Eine Zahl an der Wand, ein Griff ins Lager.",
          description=[
              "&eRezept:&r links &6Basisprozessor&r, Quarzeisen, Basisprozessor untereinander, oben in der Mitte ein &6Konstruktionskern&r, unten ein &6Zerstörungskern&r, ein &6Maschinengehäuse&r im Zentrum, rechts drei &6Glas&r.",
              "",
              "Der &6Speichermonitor&r zeigt, wie viel von einem Gegenstand im Netz liegt. Shift und Rechtsklick stellt ihn ein. Linksklick holt einen Stapel, Shift und Linksklick ein Stück, Rechtsklick legt ein, mehrfach Rechtsklick alles Passende aus dem Inventar.",
              "",
              "Eine Reihe Monitore neben der Tür zeigt Eisen, Kohle und Diamanten auf einen Blick. Er braucht 4 FE/t.",
          ],
          tasks=[task_item("refinedstorage:storage_monitor", 1)],
          rewards=[reward_item("minecraft:glass", 8), reward_xp(4)],
          deps=["importer"], icon="refinedstorage:storage_monitor"),

    quest("detector", 0, 11, "&cMelde Füllstände per Redstone",
          subtitle="Der Detektor.",
          description=[
              "&eRezept:&r Quarzeisen in den Ecken, eine &6Redstonefackel&r oben, zwei &6Komparatoren&r links und rechts von einem &6Maschinengehäuse&r, ein &6Verbesserter Prozessor&r unten.",
              "",
              "Der &6Detektor&r gibt ein Redstone-Signal, wenn das Netz von einem Gegenstand &egenau&r, &emehr&r oder &eweniger&r als eine eingestellte Menge hat. Er braucht 2 FE/t.",
              "",
              "So läuft eine Bruchsteinmaschine nur, solange weniger als 10 000 Bruchstein im Lager liegen.",
          ],
          tasks=[task_item("refinedstorage:detector", 1)],
          rewards=[reward_item("minecraft:comparator", 2), reward_xp(4)],
          deps=["storage_monitor"], icon="refinedstorage:detector", optional=True),

    quest("regulator", 2.5, 11, "&eHalt eine feste Menge im Ziel",
          subtitle="Das Regulationsupgrade.",
          description=[
              "&eRezept:&r oben Quarzeisen, &6Komparator&r, Quarzeisen, in der Mitte &6Redstone&r, &6Upgrade&r, Redstone, unten drei Quarzeisen. Rechtsklick mit dem Upgrade in der Hand stellt die Menge ein.",
              "",
              "In einem &6Exporteur&r liefert er nur, solange im Ziel weniger liegt als eingestellt. In einem &6Importeur&r holt er nur, solange im Ziel mehr liegt. Genau 16 Kohle im Ofen, nie mehr.",
          ],
          tasks=[task_item("refinedstorage:regulator_upgrade", 1)],
          rewards=[reward_item("minecraft:comparator", 2), reward_xp(4)],
          deps=["upgrades"], icon="refinedstorage:regulator_upgrade", optional=True),

    quest("config_card", 0, 12.5, "&7Kopier Einstellungen",
          subtitle="Die Konfigurationskarte.",
          description=[
              "&eRezept:&r drei Quarzeisen oben und unten, in der Mitte &6Papier&r, ein &6Verbesserter Prozessor&r, Papier.",
              "",
              "Die &6Konfigurationskarte&r speichert die Einstellungen eines Geräts, mit Filtern und Modi, und überträgt sie auf ein anderes Gerät derselben Art. Zwanzig Exporteure mit demselben Filter stellst du so in einer Minute ein.",
          ],
          tasks=[task_item("refinedstorage:configuration_card", 1)],
          rewards=[reward_item("minecraft:paper", 8), reward_xp(3)],
          deps=["exporter"], icon="refinedstorage:configuration_card", optional=True),

    quest("relay", 5, 11, "&6Schalt Teile des Netzes ab",
          subtitle="Das Relais.",
          description=[
              "&eRezept:&r formlos aus &6Maschinengehäuse&r, &6Kabel&r, &6Fortschrittlichem Prozessor&r und &6Redstonefackel&r.",
              "",
              "Das &6Relais&r verbindet ein Eingangs- mit einem Ausgangsnetz und schaltet den Ausgang per Redstone ab. Ohne Durchleitung gibst du gezielt weiter: Strom, Lager, Sicherheit, Rezepte, oder per Filter nur bestimmte Gegenstände.",
              "",
              "So bekommt die Werkstatt eines Mitspielers nur Erze und Kohle aus deinem Netz zu sehen. Es braucht je 8 FE/t auf beiden Seiten.",
          ],
          tasks=[task_item("refinedstorage:relay", 1)],
          rewards=[reward_item("refinedstorage:cable", 12), reward_xp(4)],
          deps=["external"], icon="refinedstorage:relay", optional=True),

    quest("disk_interface", 7.5, 11, "&bLeer und füll Zellen",
          subtitle="Die Festplatten-Schnittstelle.",
          description=[
              "&eRezept:&r Quarzeisen in den Ecken, &6Speichergehäuse&r oben und unten in der Mitte, links ein &6Konstruktionskern&r, rechts ein &6Zerstörungskern&r, ein Maschinengehäuse im Zentrum.",
              "",
              "Sie verschiebt Inhalt zwischen Netz und den Zellen, die du hineinlegst: eine volle Zelle ins Netz leeren, oder eine leere Zelle mit bestimmten Dingen füllen, etwa für den Umzug oder als Paket für einen Mitspieler. Sie braucht 6 FE/t plus 4 pro Zelle.",
          ],
          tasks=[task_item("refinedstorage:disk_interface", 1)],
          rewards=[reward_item("refinedstorage:storage_housing", 2), reward_xp(4)],
          deps=["external"], icon="refinedstorage:disk_interface", optional=True),

    quest("storage_block", 23, 1, "&7Setz einen Speicherblock",
          subtitle="Speicher ohne Laufwerk.",
          description=[
              "&eRezept:&r Quarzeisen links und rechts, ein &61k-Speicherkern&r oben, ein &6Maschinengehäuse&r in der Mitte, &6Redstone&r unten.",
              "",
              "Der &61k Speicherblock&r fasst 1 024 Gegenstände wie die Zelle, steht aber selbst am Kabel, ganz ohne Laufwerk. Mit dem nächstgrößeren Kern an der Werkbank wird er zum 4k- oder 16k-Block, der Inhalt bleibt. Leer gibt Rechtsklick in der Hand Kern und Gehäuse zurück.",
              "",
              "Er braucht nur 2 FE/t. Für ein kleines Nebenlager in einem anderen Raum ist das günstiger als ein Laufwerk.",
          ],
          tasks=[task_item("refinedstorage:1k_storage_block", 1)],
          rewards=[reward_item("refinedstorage:machine_casing", 1), reward_xp(4)],
          deps=["disk_1k"], icon="refinedstorage:1k_storage_block", optional=True),

    quest("network_bridge", 10, 11, "&dVerbinde zwei Netze ohne Kabel",
          subtitle="Netzwerksender, Empfänger und Karte.",
          description=[
              "&eRezept:&r Sender und Empfänger haben je drei &6Enderperlen&r, einen &6Konstruktions-&r und einen &6Zerstörungskern&r, ein Maschinengehäuse, zwei &6Fortschrittliche Prozessoren&r und einen &6Netheritbarren&r. Die &6Netzwerkkarte&r ist Quarzeisen, Papier und ein Fortschrittlicher Prozessor.",
              "",
              "Stell den &6Netzwerkempfänger&r an das entfernte Netz, Schleichen und Rechtsklick mit der Karte bindet sie an ihn. Steck die Karte in den &6Netzwerksender&r am Hauptnetz: beide sind jetzt ein Netz. Der Sender braucht 32 FE/t, der Empfänger 8.",
              "",
              "So hängt die Erzfabrik am Rand der Welt an deinem Lager zu Hause.",
          ],
          tasks=[task_item("refinedstorage:network_transmitter", 1), task_item("refinedstorage:network_receiver", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 6), reward_table("s3_uncommon"), reward_xp(8)],
          deps=["wireless"], icon="refinedstorage:network_transmitter"),

    quest("security", 12.5, 11, "&cSchütz dein Netz",
          subtitle="Sicherheits-Manager und Sicherheitskarten.",
          description=[
              "&eRezept:&r Die &6Sicherheitskarte&r ist Quarzeisen oben und unten, zwei &6Netzwerkkarten&r und ein Fortschrittlicher Prozessor in der Mitte. Mit Papier formlos wird daraus die &6Standard-Sicherheitskarte&r. Der &6Sicherheits-Manager&r: Quarzeisen, eine &6Truhe&r oben, zwei Sicherheitskarten links und rechts vom Gehäuse, die Standardkarte unten.",
              "",
              "Ist der Manager aktiv, ist im Netz erst einmal &calles verboten&r. Mit Sicherheitskarten erlaubst du einzelnen Spielern, was sie dürfen: einlagern, entnehmen, Geräte bauen. Die Standardkarte gilt für alle ohne eigene Karte.",
              "",
              "Auf einem Server mit dreißig Leuten der beste Schutz für deine Diamanten. Er braucht 16 FE/t.",
          ],
          tasks=[task_item("refinedstorage:security_manager", 1)],
          rewards=[reward_item("refinedstorage:advanced_processor", 2), reward_xp(6)],
          deps=["wireless"], icon="refinedstorage:security_manager", optional=True),

    # ---- Autocrafting ----------------------------------------------------------
    quest("pattern", 11, 7, "&aSchreib ein Rezept",
          subtitle="Rezeptkonsole und leere Rezepte.",
          description=[
              "&eRezept:&r Ein leeres &6Rezept&r (Pattern) ist Glas, Redstone, Glas oben, Redstone, Glas, Redstone in der Mitte, drei Quarzeisen unten. Die &6Rezeptkonsole&r ist eine Konsole, ein Fortschrittlicher Prozessor und ein Rezept formlos zusammen.",
              "",
              "In der Rezeptkonsole legst du die Zutaten ins Feld und drückst &eRezept erstellen&r. Ein &eHerstellungsrezept&r ist ein Werkbankrezept. Ein &eVerarbeitungsrezept&r sagt nur: Diese Zutaten gehen in eine Maschine, das kommt zurück. Auch Steinsäge und Schmiedetisch haben eigene Rezeptarten.",
              "",
              "&eFuzzy-Modus:&r Eingeschaltet nimmt das Rezept auch Alternativen (jede Holzart, jedes Eisen mit demselben Tag). Für Verarbeitungsrezepte kannst du erlaubte Alternativen einzeln anklicken.",
          ],
          tasks=[task_item("refinedstorage:pattern_grid", 1), task_item("refinedstorage:pattern", 8)],
          rewards=[reward_item("refinedstorage:pattern", 8), reward_xp(5)],
          deps=["crafting_grid"], icon="refinedstorage:pattern_grid"),

    quest("autocrafter", 13.5, 7, "&a&lBau einen Autohersteller",
          subtitle="Neun Rezepte, kein Multiblock.",
          description=[
              "&eRezept auf Kronwerke:&r Quarzeisen in die Ecken, ein &6Präzisionsmechanismus&r von Create oben in die Mitte, zwei &6Fortschrittliche Prozessoren&r links und rechts, ein Maschinengehäuse ins Zentrum, ein &6Zerstörungskern&r unten.",
              "",
              "Der &6Autohersteller&r hält &e9 Rezepte&r. Herstellungsrezepte craftet er selbst, direkt im Block. Keine Fertigungs-CPU, kein Molekularassembler, keine Präzisionsgetriebe wie bei AE2. Er braucht 4 FE/t plus 2 pro Rezept.",
              "",
              "&eVerarbeitungsrezepte:&r Der Autohersteller schaut auf die Maschine und schiebt die Zutaten hinein. Das Ergebnis muss zurück ins Netz, also Importeur an die Maschine. Mehr als neun Rezepte für eine Maschine? Stell einen zweiten Autohersteller so hin, dass er auf den ersten zeigt, dann bilden sie eine Kette.",
              "",
              "&eBestellen:&r In der Konsole auf etwas klicken, das ein Rezept hat (Strg-Klick, wenn du es schon auf Lager hast). Die Vorschau zeigt, was fehlt, dann &eStart&r.",
          ],
          tasks=[task_item("refinedstorage:autocrafter", 2)],
          rewards=[reward_item("refinedstorage:advanced_processor", 4), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["pattern"], icon="refinedstorage:autocrafter", size=1.75, shape="gear"),

    quest("monitor", 13.5, 9, "&7Behalte die Aufträge im Blick",
          subtitle="Monitor, Manager, Nachschub.",
          description=[
              "&eRezept:&r Der &6Autoherstellungsmonitor&r ist zwei Verbesserte Prozessoren links, zwei &6Rezepte&r oben und unten in der Mitte, Quarzeisen links in die Mitte, ein Gehäuse im Zentrum, drei Glas rechts.",
              "",
              "Er zeigt alle laufenden Aufträge und bricht sie ab, wenn eine Maschine klemmt. Die drahtlose Version (Monitor, Enderperle, Fortschrittlicher Prozessor) tut das aus der Tasche.",
              "",
              "Der &6Autohersteller-Manager&r (zwei Fortschrittliche Prozessoren, zwei Autohersteller, Gehäuse, Quarzeisen, drei Glas) zeigt die Rezepte aller Autohersteller in einem Fenster. Und ein &6Autoherstellung-Upgrade&r in einem Exporteur hält einen Vorrat: Fällt der Stand unter den Filter, bestellt er nach.",
          ],
          tasks=[task_item("refinedstorage:autocrafting_monitor", 1), task_item("refinedstorage:autocrafting_upgrade", 1)],
          rewards=[reward_item("refinedstorage:pattern", 8), reward_xp(5)],
          deps=["autocrafter"], icon="refinedstorage:autocrafting_monitor"),

    quest("cabletiers", 16, 7, "&5Rüste auf Elite auf",
          subtitle="Cable Tiers: schneller, mehr Filter.",
          description=[
              "&eRezept:&r Vier &6Importeure&r an die Seiten, vier &6Eisenblöcke&r in die Ecken, ein &6Fortschrittlicher Prozessor&r in die Mitte: ein &6Elite Importer&r. Genauso gehen Elite Exporter, Elite Constructor, Elite Destructor, Elite Interface und Elite Autocrafter.",
              "",
              "&6Cable Tiers&r baut die Geräte von RS in drei Stufen aus. &eElite:&r doppelt so schnell, &e18 Filterplätze&r statt 9, 4 FE/t. &eUltra:&r vier Elite-Geräte, vier &6Diamantblöcke&r und ein Fortschrittlicher Prozessor, fünfmal so schnell, 36 Filterplätze, Stapelupgrade eingebaut, 8 FE/t.",
              "",
              "Elite-Filter können auch nach &eTags&r filtern: Klick auf einen Filterplatz öffnet den erweiterten Filter mit Tag-Auswahl. Der Elite Autocrafter arbeitet doppelt so schnell wie der normale, für 5 FE/t.",
              "",
              "&cAusblick:&r Die Mega-Stufe braucht Netheritblöcke und einen &6Drachenkopf&r, also Stufe 4.",
          ],
          tasks=[task_item("cabletiers:elite_importer", 1), task_item("cabletiers:elite_exporter", 1)],
          rewards=[reward_item("minecraft:iron_block", 8), reward_table("s3_uncommon"), reward_xp(10)],
          deps=["autocrafter", "exporter"], icon="cabletiers:elite_importer"),

    quest("factory", 18.5, 8, "&3&lDie Schaltkreisfabrik mit RS",
          subtitle="Der Ofen schläft nie, der Autohersteller auch nicht.",
          description=[
              "Jetzt alles zusammen: Lass das Netz &6Fortgeschrittene Steuerschaltkreise&r für den Obelisken bauen.",
              "",
              "&eSo geht es:&r Ein Verarbeitungsrezept für Gedrucktes Silizium an einer Gravurmaschine von AE2 (Autohersteller davor, Importeur dahinter). Ein zweites für Infundierte Legierung an einer Infusionsanlage, ein drittes für Einfache Steuerschaltkreise aus Elektronenröhren. Ein Herstellungsrezept setzt alles zusammen. Ein Exporteur mit Autoherstellung-Upgrade an einer Kiste neben dem Obelisken hält den Vorrat.",
              "",
              "&eKronwerke:&r &e\"Der Ofen schläft nie\"&r will &e250 Fortgeschrittene Steuerschaltkreise&r und &e4 000 Stahlbarren&r. Mit RS ist die Fabrik billiger als mit AE2, denn sie braucht keine Präzisionsgetriebe und keine CPU. Was in der Kiste am Obelisken landet, zählt für dich.",
              "",
              "Dazu zwei 16k-Zellen, damit das Lager nicht vorher voll ist.",
          ],
          tasks=[task_item("mekanism:advanced_control_circuit", 32), task_item("refinedstorage:16k_storage_disk", 2)],
          rewards=[reward_table("s3_rare"), reward_item("refinedstorage:16k_storage_part", 1), reward_xp(25)],
          deps=["monitor", "disk_16k"], icon="mekanism:advanced_control_circuit", size=2.5, shape="gear"),
]

images = [
    banner("refined_storage/title", "Refined Storage", 10, -5, height=1.75, kind="title", colour="water"),
    banner("refined_storage/processors", "Quarz und Prozessoren", 3.7, -2.7, height=0.9, colour="brass"),
    banner("refined_storage/network", "Das Netzwerk", 15.5, -2.7, height=0.9, colour="water"),
    banner("refined_storage/io", "Rein und raus", 3.7, 4.6, height=0.9, colour="brass"),
    banner("refined_storage/autocrafting", "Autocrafting", 14.7, 4.6, height=0.9, colour="water"),
]

chapter(C, "Refined Storage", "refinedstorage:controller", "tech", quests, shape="square", order=53, stage=3,
        subtitle=["Stufe 3: Quarzeisen, Prozessoren aus dem Ofen, das Netz bis 16k, Autocrafting und Cable Tiers."],
        images=images)
