"""Silent Gear in Stufe 1: Ausrüstung aus Teilen bis zur Eisenstufe. Blaupausen und Vorlagen, Köpfe,
Stiele, Verbindungen, Griffe und Spitzen, Reparatur und gute frühe Builds. Purpur-Eisen, Purpur-Stahl,
Lohengold, Alloy Forge und Recycler öffnen mit dem Nether in Stufe 2."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "silent_gear"

quests = [
    # ---- Erste Schritte ------------------------------------------------------------------------
    quest("welcome", 0, 0, "&6Silent Gear",
          subtitle="Werkzeug aus Teilen. Das Material entscheidet alles.",
          description=[
              "In Silent Gear baust du Werkzeuge, Waffen und Rüstung aus &eTeilen&r zusammen, und jedes Teil kann aus einem anderen Material sein. Eine Spitzhacke ist hier kein festes Item, sondern ein &6Kopf&r plus ein &6Stiel&r, dazu auf Wunsch eine &6Verbindung&r, ein &6Griff&r und eine &6Spitze&r.",
              "",
              "Jedes Material bringt eigene &eWerte&r mit (Haltbarkeit, Abbautempo, Schaden, Abbaustufe) und eigene &eEigenschaften&r (Traits), zum Beispiel &6Biegsam&r bei Eisen: Das Werkzeug nimmt manchmal weniger Schaden. Aus der Mischung entsteht dein ganz eigenes Werkzeug.",
              "",
              "&eDer Ablauf ist immer gleich:&r",
              "1. Eine &6Blaupause&r oder &6Vorlage&r für das Teil besorgen.",
              "2. Blaupause plus Material ins Handwerksraster: Das ergibt das Teil.",
              "3. Teile zusammen ins Raster: Das ergibt das Werkzeug.",
              "",
              "&cKronwerke:&r In Stufe 1 (Steinwerk) reicht Silent Gear bis &6Eisen&r. Die starken Metalle der Mod, &6Purpur-Eisen&r, &6Purpur-Stahl&r und &6Lohengold&r, kommen aus dem Nether und öffnen in Stufe 2. Stahl aus Mekanism und Immersive Engineering ebenfalls.",
          ],
          tasks=[task_checkmark("Los geht's")],
          rewards=[reward_item("minecraft:stick", 32), reward_table("s1_common")],
          icon="silentgear:pickaxe", size=2.0, shape="hexagon"),

    quest("starter_blueprints", 2.5, 0, "Blaupausenbündel",
          subtitle="Das Startpaket hast du schon.",
          description=[
              "Beim ersten Betreten des Servers hast du ein &6Blaupausenbündel&r bekommen. Ein &eRechtsklick&r öffnet es und du erhältst Blaupausen für &6Stiel&r, &6Spitzhacke&r, &6Schaufel&r, &6Axt&r, &6Hacke&r und &6Schwert&r.",
              "",
              "&6Blaupausen&r werden beim Herstellen &enicht verbraucht&r. Du legst sie ins Raster, und sie bleiben danach liegen. Halte über einer Blaupause die Taste &eAlt&r, dann zeigt der Tooltip, welche Teile das fertige Werkzeug braucht, und die Taste &eU&r zeigt die Rezepte in JEI.",
              "",
              "Bündel verloren? Kein Problem, die nächste Quest zeigt, wie du selbst Blaupausen machst. Für diese Quest reicht eine &6Spitzhacke Blaupause&r, egal woher.",
          ],
          tasks=[task_item("silentgear:pickaxe_blueprint", 1)],
          rewards=[reward_item("minecraft:paper", 8), reward_xp(2)],
          deps=["welcome"], icon="silentgear:blueprint_package"),

    quest("blueprint_paper", 4.5, 0, "Blaues Papier",
          subtitle="Das Papier für alle weiteren Blaupausen.",
          description=[
              img(item_texture("silentgear:blueprint_paper"), 32, 32),
              "",
              "Für alle Blaupausen, die nicht im Startpaket sind, brauchst du &6Blaues Papier&r (Blueprint Paper): &6vier Papier&r und &6ein blauer Farbstoff&r, formlos. Du bekommst vier Blätter.",
              "",
              "Blauen Farbstoff gibt es aus &6Kornblumen&r, aus &6Lapislazuli&r oder aus den &6Flachsblumen&r von Silent Gear. Papier machst du aus Zuckerrohr.",
              "",
              "Jede Blaupause wird aus Blauem Papier und meist ein paar Stöcken in der Form des Werkzeugs gebaut. Eine Spitzhacke zum Beispiel: drei Papier oben, zwei Stöcke senkrecht darunter. JEI kennt alle Formen.",
          ],
          tasks=[task_item("silentgear:blueprint_paper", 8)],
          rewards=[reward_item("minecraft:sugar_cane", 16), reward_item("minecraft:lapis_lazuli", 4)],
          deps=["starter_blueprints"], icon="silentgear:blueprint_paper"),

    quest("material_book", 2.5, 2, "Material Book",
          subtitle="Das Nachschlagewerk für jedes Material.",
          description=[
              "Das &6Material Book&r listet jedes Material, das Silent Gear kennt, mit all seinen Werten und Eigenschaften, sortiert nach Name oder nach einer bestimmten Eigenschaft. Wenn du wissen willst, welches Material am schnellsten abbaut oder am längsten hält: hier steht es.",
              "",
              "Du hast es beim ersten Betreten bekommen. Falls nicht: ein &6Buch&r und ein &6Blaues Papier&r, formlos.",
              "",
              "&6Tipp:&r Auch über jedem Material im Inventar zeigt der Tooltip, für welche Teile es taugt. Halte &eStrg&r für die Werte.",
          ],
          tasks=[task_item("silentgear:material_book", 1)],
          rewards=[reward_xp(3)],
          deps=["starter_blueprints"], icon="silentgear:material_book", optional=True),

    # ---- Vorlagen -------------------------------------------------------------------------------
    quest("crude_parts", 8, 0, "Crude Tool Parts",
          subtitle="Aus Dreck gemacht.",
          description=[
              img(item_texture("silentgear:crude_tool_parts"), 32, 32),
              "",
              "Neben Blaupausen gibt es einen zweiten, ganz einfachen Weg: &6Vorlagen&r aus Holz. Die werden beim Benutzen verbraucht, kosten aber fast nichts. Und die &6Vorlagenbretter&r dafür brauchst du auch für Reparaturkits.",
              "",
              "Los geht es mit &6Crude Tool Parts&r: &6ein Bruchstein&r, &6ein Erdblock&r und &6ein Stock&r, formlos. Das ergibt vier Stück.",
          ],
          tasks=[task_item("silentgear:crude_tool_parts", 4)],
          rewards=[reward_item("minecraft:cobblestone", 32)],
          icon="silentgear:crude_tool_parts"),

    quest("crude_knife", 10, 0, "Crude Knife",
          subtitle="Schneidet Stämme zu Brettern.",
          description=[
              img(item_texture("silentgear:crude_knife"), 32, 32),
              "",
              "Das &6Crude Knife&r ist ein &6Bruchstein&r über den &6Crude Tool Parts&r. Es ist kein Kampfmesser, sondern ein Schnitzwerkzeug für den Steinamboss.",
              "",
              "Jeder Schnitt kostet einen Punkt Haltbarkeit, irgendwann ist es verbraucht. Mach dir gleich zwei.",
              "",
              "Übrigens: Ein richtiges Messer aus Silent Gear (Messerklinge plus Stiel) kann dasselbe und hält viel länger.",
          ],
          tasks=[task_item("silentgear:crude_knife", 1)],
          rewards=[reward_xp(2)],
          deps=["crude_parts"], icon="silentgear:crude_knife"),

    quest("stone_anvil", 10, 2, "Stone Anvil",
          subtitle="Die Werkbank für Messer und Hammer.",
          description=[
              "Der &6Stone Anvil&r ist ein kleiner Arbeitsblock: ein &6Bruchstein&r oben in der Mitte, darunter &6Bruchstein, Erde, Bruchstein&r.",
              "",
              "Auf ihm bearbeitest du Blöcke mit Werkzeugen: Leg etwas mit &eRechtsklick&r darauf und klick dann mit dem passenden Werkzeug darauf. Mit dem Messer wird so aus einem Stamm ein Stapel Bretter.",
          ],
          tasks=[task_item("silentgear:stone_anvil", 1)],
          rewards=[reward_item("minecraft:oak_log", 16)],
          deps=["crude_parts"], icon="silentgear:stone_anvil"),

    quest("template_boards", 12, 0, "Vorlagenbrett",
          subtitle="Sechs Bretter aus einem Stamm.",
          description=[
              img(item_texture("silentgear:template_board"), 32, 32),
              "",
              "Leg einen &6Holzstamm&r auf den Stone Anvil und klick mit dem &6Crude Knife&r darauf. Heraus kommen &esechs Vorlagenbretter&r.",
              "",
              "Aus Brettern und Stöcken baust du &6Vorlagen&r in denselben Formen wie die Blaupausen. Vorlagenbretter brauchst du außerdem für das &6Reparaturkit&r, das &6Ausrüstungs-Modkit&r und das &6Blaupausenbuch&r.",
          ],
          tasks=[task_item("silentgear:template_board", 12)],
          rewards=[reward_item("minecraft:oak_log", 16), reward_xp(3)],
          deps=["crude_knife", "stone_anvil"], icon="silentgear:template_board"),

    quest("template", 14, 0, "Spitzhacke Vorlage",
          subtitle="Billig und nur einmal zu gebrauchen.",
          description=[
              "Eine &6Vorlage&r macht dasselbe wie eine Blaupause, verschwindet aber nach einem Teil. Die Spitzhacke Vorlage: &6drei Vorlagenbretter&r oben und &6zwei Stöcke&r senkrecht darunter.",
              "",
              "Wann lohnt sich das? Für Teile, die du nur einmal brauchst, oder wenn dir gerade blauer Farbstoff fehlt. Für alles, was du öfter baust, ist die Blaupause besser.",
          ],
          tasks=[task_item("silentgear:pickaxe_template", 1)],
          rewards=[reward_xp(2)],
          deps=["template_boards"], icon="silentgear:pickaxe_template", optional=True),

    quest("blueprint_book", 14, 2, "Blaupausenbuch",
          subtitle="Alle Blaupausen in einem Slot.",
          description=[
              "Irgendwann hast du zehn Blaupausen im Inventar. Das &6Blaupausenbuch&r sammelt sie alle: &6ein Buch&r, &6eine Wolle&r, &6ein Goldbarren&r und &6drei Vorlagenbretter&r, formlos.",
              "",
              "Das Buch zählt im Handwerksraster als die gerade ausgewählte Blaupause. Mit den Tasten &eZ&r und &eC&r wechselst du durch.",
          ],
          tasks=[task_item("silentgear:blueprint_book", 1)],
          rewards=[reward_xp(3)],
          deps=["template_boards"], icon="silentgear:blueprint_book", optional=True),

    # ---- Bauteile ---------------------------------------------------------------------------------
    quest("rod", 0, 6.5, "Stiel",
          subtitle="Der Teil, den du in der Hand hältst.",
          description=[
              "Jedes Werkzeug braucht einen &6Stiel&r (Tool Rod). &cAchtung:&r Das Spiel nennt das Teil auf Deutsch ebenfalls &eGriff&r, genau wie das Zusatzteil weiter hinten. Wir sagen hier Stiel, damit es nicht durcheinandergeht.",
              "",
              "Rezept: die &6Stiel Blaupause&r plus &6zwei Stäbe&r aus demselben Material. Das ergibt &evier&r Stiele.",
              "",
              "- &6Holz&r: zwei Stöcke. Eigenschaft Flexibel.",
              "- &6Stein&r: zwei Steinstäbe (zwei Bruchstein übereinander). Brüchig, eher nicht zu empfehlen.",
              "- &6Knochen&r: zwei Knochen. Flexibel und etwas mehr Schaden.",
              "- &6Eisen&r: zwei Eisenstäbe, siehe Nebenquest darunter. Flexibel.",
              "",
              "Der Stiel beeinflusst die Werte nur wenig, bringt aber seine Eigenschaften ins Werkzeug. Für den Anfang sind Stöcke völlig in Ordnung.",
          ],
          tasks=[task_item("silentgear:rod", 4)],
          rewards=[reward_item("minecraft:stick", 32)],
          icon="silentgear:rod", size=1.5, shape="square"),

    quest("pickaxe_head", 2.5, 6.5, "Spitzhackenkopf",
          subtitle="Blaupause plus drei Mal Material.",
          description=[
              "Der &6Kopf&r ist das wichtigste Teil: Er bestimmt Haltbarkeit, Abbautempo, Schaden und die &eAbbaustufe&r.",
              "",
              "Rezept: die &6Spitzhacke Blaupause&r plus &edrei&r Einheiten Material. Ein Barren, ein Edelstein oder ein Block Bruchstein zählt als eine Einheit.",
              "",
              "- &6Bruchstein&r: 131 Haltbarkeit, Stufe Stein, Urzeitlich (mehr Erfahrung).",
              "- &6Feuerstein&r: 124 Haltbarkeit, Stufe Feuerstein (wie Stein), Gezackt.",
              "- &6Kupfer&r: 151 Haltbarkeit, Stufe Kupfer (zwischen Stein und Eisen), Weich.",
              "- &6Eisen&r: 250 Haltbarkeit, Tempo 6, Stufe Eisen (baut Diamanterz ab), Biegsam.",
              "- &6Gold&r: nur 32 Haltbarkeit, aber Tempo 12.",
              "",
              "Du darfst Materialien mischen, etwa zwei Eisen und ein Gold. Die Werte werden dann gemittelt, und die &eSynergie&r im Tooltip sinkt, je unterschiedlicher die Materialien sind.",
          ],
          tasks=[task_item("silentgear:pickaxe_head", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 6)],
          deps=["rod"], icon="silentgear:pickaxe_head"),

    quest("pickaxe", 5, 6.5, "&6Deine eigene Spitzhacke",
          subtitle="Kopf plus Stiel, fertig.",
          description=[
              "Leg den &6Spitzhackenkopf&r und einen &6Stiel&r ins Handwerksraster: Das ist deine erste Silent-Gear-Spitzhacke. Aussehen, Farbe und Name kommen vom Material.",
              "",
              "&eAbkürzung:&r Blaupause, drei Materialien und ein Stiel zusammen ins Raster ergeben die Spitzhacke in einem Schritt, ganz ohne den Kopf einzeln zu bauen.",
              "",
              "&eZusatzteile&r (Verbindung, Griff, Spitze) kannst du gleich beim Zusammenbauen mit ins Raster legen oder später nachrüsten: Werkzeug plus neues Teil ins Raster, und das Teil wird eingebaut. Ein altes Teil derselben Sorte bekommst du dabei zurück.",
              "",
              "&6Wichtig:&r Silent-Gear-Werkzeuge verschwinden nicht, wenn sie kaputtgehen. Sie bleiben als &ezerbrochen&r im Inventar, bis du sie reparierst. Dazu mehr im Abschnitt Pflege und Reparatur.",
          ],
          tasks=[task_item("silentgear:pickaxe", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["pickaxe_head"], icon="silentgear:pickaxe", size=2.0, shape="hexagon"),

    quest("reading_stats", 5, 8.8, "Werte lesen",
          subtitle="Was der Tooltip dir verrät.",
          description=[
              "Der Tooltip eines Silent-Gear-Werkzeugs hat drei Ebenen:",
              "",
              "- &eStrg&r halten: alle &6Werte&r (Haltbarkeit, Abbautempo, Angriffsschaden, Abbaustufe, Verzauberbarkeit) und die &6Eigenschaften&r.",
              "- &eShift&r halten: Erklärungen zu jeder &6Eigenschaft&r.",
              "- &eAlt&r halten: der &6Aufbau&r, also aus welchen Teilen und Materialien das Werkzeug besteht.",
              "",
              "Die &6Synergie&r ist ein Faktor auf viele Werte. Bleibt sie bei 100 Prozent oder darüber, ist alles gut. Viele verschiedene Materialien in einem Kopf senken sie. Die Eigenschaft &6Rostig&r (Papier, Terrakotta) hebt eine niedrige Synergie wieder an, &6Synergistisch&r (Smaragd) belohnt eine hohe.",
              "",
              "Eigenschaften haben Stufen. Kommt dieselbe Eigenschaft aus mehreren Teilen, wird sie stärker. Manche heben sich auch auf: &6Biegsam&r wirkt gegen &6Brüchig&r.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["pickaxe"], icon="minecraft:spyglass"),

    quest("binding", 7.5, 6.5, "Verbindung",
          subtitle="Hält Kopf und Stiel zusammen.",
          description=[
              "Die &6Verbindung&r (Binding) ist ein Zusatzteil, das vor allem &eEigenschaften&r bringt, meist &6Flexibel&r: Das Werkzeug nimmt dann oft gar keinen Schaden.",
              "",
              "Die &6Verbindung Blaupause&r ist das erste Mal, dass du selbst eine Blaupause baust: &6ein Blaues Papier&r und &6zwei Fäden&r, formlos. Dann Blaupause plus &eein&r Material ergibt eine Verbindung.",
              "",
              "- &6Faden&r: Flexibel I.",
              "- &6Ranken&r: keine Eigenschaft, nur Optik.",
              "- &6Flachsstrang&r: Flexibel III und etwas Tempo.",
              "- &6Sehnenfaser&r: Flexibel IV, die beste Verbindung in Stufe 1.",
          ],
          tasks=[task_item("silentgear:binding", 1)],
          rewards=[reward_item("minecraft:string", 16)],
          deps=["pickaxe"], icon="silentgear:binding"),

    quest("grip", 9.5, 6.5, "Griff",
          subtitle="Mehr Tempo beim Graben und Schlagen.",
          description=[
              "Der &6Griff&r (Grip) wird um den Stiel gewickelt und macht dein Werkzeug schneller. &6Griff Blaupause&r: &6zwei Blaues Papier&r und &eeine Wolle&r, formlos. Dann Blaupause plus ein Material.",
              "",
              "- &6Leder&r: +15 Prozent Abbautempo, etwas mehr Angriffstempo, Flexibel III.",
              "- &6Wolle&r: +10 Prozent Abbautempo, etwas mehr Angriffstempo, Flexibel II.",
              "- &6Phantomhaut&r: +10 Prozent Abbautempo und Urzeitlich (mehr Erfahrung).",
              "",
              "Leder ist die einfachste gute Wahl. Kühe gibt es überall, und den Rest vom Leder brauchst du für Rucksäcke.",
          ],
          tasks=[task_item("silentgear:grip", 1)],
          rewards=[reward_item("minecraft:leather", 6)],
          deps=["binding"], icon="silentgear:grip"),

    quest("tip", 11.5, 6.5, "Spitze",
          subtitle="Ein harter Kern an der Arbeitskante.",
          description=[
              "Die &6Spitze&r (Tip Upgrade) verstärkt den Kopf. &6Spitze Blaupause&r: &6zwei Blaues Papier&r, &6ein Papier&r und &6ein Stein&r, formlos. Dann Blaupause plus ein Material.",
              "",
              "- &6Eisen&r: +128 Haltbarkeit, +1 Tempo, +1 Schaden, hebt die Abbaustufe auf Eisen.",
              "- &6Gold&r: +6 Abbautempo, aber kaum zusätzliche Haltbarkeit.",
              "- &6Redstone&r: +20 Prozent Tempo und +2 Schaden.",
              "- &6Diamant&r: +256 Haltbarkeit und &eDiamant-Abbaustufe&r, damit baust du Obsidian ab.",
              "",
              "&6Tipp:&r Eine Eisenspitze auf einem Steinkopf macht aus einer billigen Spitzhacke eine, die Diamanterz abbaut. Und wer einen Diamanten übrig hat, macht daraus eine Diamantspitze statt einer ganzen Diamant-Spitzhacke.",
          ],
          tasks=[task_item("silentgear:tip", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(3)],
          deps=["grip"], icon="silentgear:tip"),

    quest("iron_rod", 0, 8.6, "Eisenstab",
          subtitle="Für einen Eisenstiel.",
          description=[
              img(item_texture("silentgear:iron_rod"), 32, 32),
              "",
              "&6Zwei Eisenbarren&r übereinander ergeben &evier Eisenstäbe&r. Zwei davon mit der Stiel Blaupause ergeben vier &6Eisenstiele&r.",
              "",
              "Werte und Eigenschaft sind wie beim Holzstiel, Flexibel II. Der Unterschied ist vor allem die Optik: Mit Eisenstiel ist dein Werkzeug ganz aus Eisen.",
          ],
          tasks=[task_item("silentgear:iron_rod", 4)],
          rewards=[reward_xp(2)],
          deps=["rod"], icon="silentgear:iron_rod", optional=True),

    quest("sinew", 7, 8.6, "Sehne",
          subtitle="Das beste Bindematerial kommt von Tieren.",
          description=[
              img(item_texture("silentgear:sinew_fiber"), 32, 32),
              "",
              "Kühe, Schweine und Schafe lassen manchmal eine &6Sehne&r fallen. Brate sie im Ofen zu &6Getrockneter Sehne&r, und im Handwerksraster wird daraus &edrei Sehnenfasern&r.",
              "",
              "Sehnenfaser ist mit Flexibel IV die beste Verbindung, die Stufe 1 zu bieten hat. Sie taugt auch als Sehne für Bögen.",
          ],
          tasks=[task_item("silentgear:sinew_fiber", 3)],
          rewards=[reward_item("minecraft:cooked_beef", 8)],
          deps=["binding"], icon="silentgear:sinew_fiber", optional=True),

    quest("flax", 8.8, 8.6, "Flachsstrang",
          subtitle="Eine Pflanze mit vielen Talenten.",
          description=[
              img(item_texture("silentgear:flax_string"), 32, 32),
              "",
              "&6Wilder Flachs&r wächst in der Überwelt. Abbauen gibt &6Flachssamen&r, die du auf Ackerland anbaust. Reife Pflanzen liefern &6Flachsfasern&r, neue Samen und oft &6Flachsblumen&r.",
              "",
              "- Zwei Flachsfasern ergeben einen &6Flachsstrang&r: Verbindung mit Flexibel III.",
              "- Flachsblumen ergeben &6blauen Farbstoff&r, genau das, was du für Blaues Papier brauchst.",
          ],
          tasks=[task_item("silentgear:flax_string", 4)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["binding"], icon="silentgear:flax_string", optional=True),

    quest("builds", 11.5, 8.6, "Gute Builds für den Anfang",
          subtitle="Rezepte, die sich bewährt haben.",
          description=[
              "Ein paar Kombinationen, mit denen du in Stufe 1 gut fährst:",
              "",
              "&6Der erste Tag:&r Kopf aus drei Bruchstein, Holzstiel. Kostet nichts, baut Eisenerz ab und gibt mit Urzeitlich etwas mehr Erfahrung.",
              "",
              "&6Die Aufsteiger-Hacke:&r Steinkopf, Holzstiel und eine &6Eisenspitze&r. Für einen einzigen Eisenbarren baut sie Diamanterz ab.",
              "",
              "&6Der Alltag:&r Kopf aus drei Eisen, Eisenstiel, &6Sehnen-Verbindung&r und &6Ledergriff&r. Biegsam und zweimal Flexibel sorgen dafür, dass sie sehr lange hält.",
              "",
              "&6Der Tempo-Build:&r wie der Alltag, aber mit &6Goldspitze&r. Deutlich schneller, dafür etwas weniger haltbar.",
              "",
              "&6Die Waffe:&r Schwertklinge aus zwei &6Feuerstein&r. Gezackt erhöht den Schaden, je abgenutzter die Klinge ist. Mit Ledergriff schlägt sie schneller.",
          ],
          tasks=[task_checkmark("Notiert")],
          rewards=[reward_xp(3)],
          deps=["tip"], icon="minecraft:writable_book", optional=True),

    # ---- Werkzeuge ---------------------------------------------------------------------------------
    quest("axe", 0, 13, "Axt",
          subtitle="Bäume fällen im neuen Stil.",
          description=[
              "Mit der &6Axt Blaupause&r aus dem Startpaket und &edrei&r Materialien baust du einen &6Axtkopf&r, dazu einen Stiel: fertig ist die Axt.",
              "",
              "Die Axt ist in Silent Gear auch eine ordentliche Waffe, aber langsamer als das Schwert. Eisen gibt ihr einen kleinen Tempoabzug, Feuerstein macht sie mit Gezackt im Kampf gefährlich.",
              "",
              "&6Tipp:&r Mit dem Werkzeugtausch-Upgrade im Rucksack wechselt dein Werkzeug automatisch zur Axt, sobald du auf Holz schlägst.",
          ],
          tasks=[task_item("silentgear:axe", 1)],
          rewards=[reward_item("minecraft:oak_log", 16)],
          icon="silentgear:axe", size=1.5, shape="square"),

    quest("shovel", 2.5, 13, "Schaufel",
          subtitle="Nur ein Material für den Kopf.",
          description=[
              "Der &6Schaufelkopf&r braucht nur &eein&r Material. Damit ist die Schaufel das billigste Werkzeug, um ein neues Material auszuprobieren.",
              "",
              "&6Tipp:&r Gold baut mit Tempo 12 Erde und Sand sehr schnell ab. Da eine Schaufel wenig Schaden nimmt, fällt die geringe Haltbarkeit hier weniger ins Gewicht.",
          ],
          tasks=[task_item("silentgear:shovel", 1)],
          rewards=[reward_xp(3)],
          deps=["axe"], icon="silentgear:shovel"),

    quest("sword", 4.5, 13, "Schwert",
          subtitle="Klinge, Stiel, und dann los.",
          description=[
              "Die &6Schwertklinge&r braucht &ezwei&r Materialien. Dazu ein Stiel, und auf Wunsch ein Griff für mehr Angriffstempo.",
              "",
              "&6Eisen&r gibt +2 Schaden und hält lange. &6Feuerstein&r gibt ebenfalls +2 Schaden und steigert ihn mit Gezackt weiter, je mehr das Schwert abgenutzt ist. &6Knochen&r bringt ein wenig Magieschaden und Splittern.",
              "",
              "Schwerter verzaubern sich wie in Vanilla. Wie gut, zeigt der Wert &6Verzauberbarkeit&r: Gold und Kupfer sind da stark, Stein und Feuerstein schwach.",
          ],
          tasks=[task_item("silentgear:sword", 1)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["shovel"], icon="silentgear:sword"),

    quest("hammer", 6.5, 13, "&6Hammer",
          subtitle="Graben in 3x3.",
          description=[
              "Der &6Hammer&r baut &e3x3 Blöcke&r auf einmal ab, eine Spitzhacke für Tunnel. Er ist der große Gewinn, den Silent Gear dir schon in Stufe 1 schenkt.",
              "",
              "&6Hammer Blaupause&r: &6sechs Blaues Papier&r in den oberen zwei Reihen, &6ein Stock&r unten in der Mitte. Der &6Hammerkopf&r braucht &esechs&r Materialien, also sechs Eisenbarren für einen Eisenhammer.",
              "",
              "Er ist langsamer als eine Spitzhacke und nutzt sich bei jedem Block ab. Eine Sehnen-Verbindung und ein Ledergriff lohnen sich hier besonders.",
              "",
              "&6Tipp:&r Hammer für Tunnel, FTB Ultimine für Erzadern. Zusammen räumen sie jede Mine aus.",
          ],
          tasks=[task_item("silentgear:hammer", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 12), reward_xp(5)],
          deps=["sword"], icon="silentgear:hammer"),

    quest("armor", 2.5, 15, "Helm",
          subtitle="Rüstung aus Teilen.",
          description=[
              "Auch Rüstung baut Silent Gear aus Material. Die &6Helm Blaupause&r ist fünf Blaues Papier in Helmform, die &6Helmbasis&r braucht &efünf&r Materialien. Brustplatte, Beinschutz und Stiefel folgen demselben Muster mit acht, sieben und vier Materialien.",
              "",
              "Eisen gibt solide Rüstung, Gold und Kupfer mehr Magieschutz. Eine &6Beschichtung&r (Lining) aus Leder oder Wolle bringt zusätzlich Flexibel, damit die Rüstung langsamer verschleißt.",
          ],
          tasks=[task_item("silentgear:helmet", 1)],
          rewards=[reward_item("minecraft:leather", 4)],
          deps=["sword"], icon="silentgear:helmet", optional=True),

    quest("knife", 4.5, 15, "Messer",
          subtitle="Das Messer, das nicht bricht.",
          description=[
              "Ein &6Messer&r aus Silent Gear: &6Messer Blaupause&r (ein Blaues Papier, ein Stock), Klinge aus &eeinem&r Material, dazu ein Stiel.",
              "",
              "Es ist eine schnelle, leichte Waffe und schneidet auf dem Stone Anvil Bretter wie das Crude Knife. Anders als das Crude Knife kannst du es reparieren.",
          ],
          tasks=[task_item("silentgear:knife", 1)],
          rewards=[reward_xp(3)],
          deps=["sword"], icon="silentgear:knife", optional=True),

    quest("sickle", 6.5, 15, "Sichel",
          subtitle="Mäht ein ganzes Feld.",
          description=[
              "Die &6Sichel&r erntet Pflanzen, Gras und Blumen in einem Bereich um den Block, den du triffst. Blaupause: drei Blaues Papier und ein Stock. Die Klinge braucht &edrei&r Materialien.",
              "",
              "Praktisch für große Felder aus Farmer's Delight und zum Freiräumen von hohem Gras.",
          ],
          tasks=[task_item("silentgear:sickle", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16)],
          deps=["hammer"], icon="silentgear:sickle", optional=True),

    quest("paxel", 8.5, 15, "Spaxfel",
          subtitle="Spitzhacke, Axt und Schaufel in einem.",
          description=[
              "Der &6Spaxfel&r (Paxel) vereint Spitzhacke, Axt und Schaufel. Ein Werkzeug für alles, gut für Ausflüge mit wenig Platz.",
              "",
              "Blaupause: sechs Blaues Papier und zwei Stöcke. Der Kopf braucht &efünf&r Materialien. Er ist etwas langsamer als die einzelnen Werkzeuge, spart aber drei Plätze in der Hotbar.",
          ],
          tasks=[task_item("silentgear:paxel", 1)],
          rewards=[reward_xp(5)],
          deps=["hammer"], icon="silentgear:paxel", optional=True),

    # ---- Pflege und Reparatur -------------------------------------------------------------------
    quest("broken", 0, 19.5, "Kaputt, nicht weg",
          subtitle="Zerbrochen heißt hier: reparieren.",
          description=[
              "Ein Silent-Gear-Werkzeug, das keine Haltbarkeit mehr hat, &ezerbricht&r, verschwindet aber nicht. Es bleibt im Inventar und kann nichts mehr, bis du es reparierst. Alle Teile, Verzauberungen und Materialien bleiben erhalten.",
              "",
              "&cAchtung:&r Loses Material allein repariert gar nichts. Du brauchst ein &6Reparaturkit&r, siehe nächste Quest. Alternativ geht es im Amboss mit dem Material des Kopfes, das kostet aber Erfahrungsstufen und ist nur halb so wirksam.",
          ],
          tasks=[task_checkmark("Gut zu wissen")],
          rewards=[reward_xp(2)],
          icon="silentgear:crude_repair_kit", size=1.5, shape="square"),

    quest("repair_kit", 2.5, 19.5, "Rohes-Reparaturkit",
          subtitle="Füllen, dann reparieren.",
          description=[
              img(item_texture("silentgear:crude_repair_kit"), 32, 32),
              "",
              "Rezept: ein &6Stock&r oben, darunter &6Vorlagenbrett, Eisenbarren, Vorlagenbrett&r und unten &6drei Vorlagenbretter&r.",
              "",
              "&eSo geht es:&r",
              "1. &eFüllen:&r Kit und Material zusammen ins Raster. Das Material muss eines der Materialien des Werkzeugkopfes sein. Das Rohe Kit fasst &e16&r Einheiten.",
              "2. &eReparieren:&r Gefülltes Kit und Werkzeug zusammen ins Raster. Das Kit gibt so viel Material ab wie nötig.",
              "3. &eLeeren:&r Kit und ein Stock ins Raster, falls du das Material zurück willst.",
              "",
              "Das &6Sehr einfache Reparaturkit&r (Stein statt Eisen) fasst nur 8 und arbeitet mit 30 statt 35 Prozent Effizienz. Das &6Robuste Reparaturkit&r (Eisen, Eisenstäbe und ein Diamant) fasst 32 und arbeitet mit 40 Prozent.",
          ],
          tasks=[task_item("silentgear:crude_repair_kit", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(3)],
          deps=["broken"], icon="silentgear:crude_repair_kit"),

    quest("swap_parts", 4.5, 19.5, "Teile tauschen",
          subtitle="Ein Werkzeug, das mit dir wächst.",
          description=[
              "Du musst nie ein ganzes Werkzeug wegwerfen. Leg ein Werkzeug und ein neues Teil ins Raster, und das Teil wird eingebaut. Ein altes Teil derselben Art bekommst du zurück.",
              "",
              "So wird aus der Spitzhacke vom ersten Tag Schritt für Schritt die gute: erst eine Eisenspitze, dann eine Sehnen-Verbindung, dann ein Ledergriff. Nur den &eKopf&r kannst du nicht tauschen, der macht das Werkzeug aus.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["repair_kit"], icon="silentgear:binding"),

    quest("mod_kit", 6.5, 19.5, "Ausrüstungs-Modkit",
          subtitle="Teile wieder ausbauen.",
          description=[
              img(item_texture("silentgear:mod_kit"), 32, 32),
              "",
              "Das &6Ausrüstungs-Modkit&r baut Teile aus, ohne neue einzusetzen. Rezept: &6vier Vorlagenbretter&r, ein &6Eisenbarren&r und ein &6Stock&r.",
              "",
              "Wähle mit dem Modkit in der Hand über die Tasten &eZ&r und &eC&r die Art des Teils (zum Beispiel Spitze), dann Modkit und Werkzeug zusammen ins Raster. Heraus kommen das Werkzeug ohne dieses Teil und das Teil selbst.",
          ],
          tasks=[task_item("silentgear:mod_kit", 1)],
          rewards=[reward_xp(2)],
          deps=["swap_parts"], icon="silentgear:mod_kit", optional=True),

    quest("sturdy_kit", 2.5, 21.5, "Robustes Reparaturkit",
          subtitle="Mehr Vorrat, bessere Reparatur.",
          description=[
              img(item_texture("silentgear:sturdy_repair_kit"), 32, 32),
              "",
              "Das &6Robuste Reparaturkit&r fasst &e32&r Einheiten und repariert mit &e40 Prozent&r Effizienz. Rezept: ein &6Eisenstab&r oben, darunter &6Eisenbarren, Diamant, Eisenbarren&r und unten &6drei Eisenbarren&r.",
              "",
              "Den Diamanten zahlst du einmal, dafür holst du aus jedem Eisenbarren mehr Haltbarkeit heraus. Für Hammer und Spaxfel, die viel verschleißen, lohnt sich das.",
          ],
          tasks=[task_item("silentgear:sturdy_repair_kit", 1)],
          rewards=[reward_xp(3)],
          deps=["repair_kit"], icon="silentgear:sturdy_repair_kit", optional=True),

    # ---- Ziel und Ausblick -----------------------------------------------------------------------
    quest("iron_kit", 16, 10, "&6Eisenzeit",
          subtitle="Ein Satz Werkzeug, ganz nach deinem Plan.",
          description=[
              "Spitzhacke, Axt, Schwert und Hammer, alles aus Teilen, alles reparierbar. Damit bist du für den Rest von Stufe 1 ausgestattet.",
              "",
              "Die Quest will die vier Werkzeuge sehen. Aus welchem Material sie sind, entscheidest du. Für die harte Arbeit empfiehlt sich Eisen im Kopf.",
              "",
              "&6Tipp:&r Leg die Werkzeuge mit dem Werkzeugtausch-Upgrade in deinen Rucksack. Dann hast du immer das richtige in der Hand.",
          ],
          tasks=[task_item("silentgear:pickaxe", 1), task_item("silentgear:axe", 1),
                 task_item("silentgear:sword", 1), task_item("silentgear:hammer", 1)],
          rewards=[reward_table("s1_rare"), reward_xp(10)],
          deps=["tip", "hammer", "swap_parts"], icon="silentgear:hammer", size=2.5, shape="gear"),

    quest("outlook", 16, 13.5, "Ausblick: Nether-Metalle",
          subtitle="Was Stufe 2 für Silent Gear bringt.",
          description=[
              "Mit Stufe 2 (Messingwerk) öffnet der Nether, und damit bekommt Silent Gear seine eigenen Metalle:",
              "",
              "- &6Purpur-Eisen&r aus Erz im Nether: 420 Haltbarkeit, Tempo 10, Hart und Hitzebeständig.",
              "- &6Purpur-Stahl&r und &6Lohengold&r, gemischt in der &6Alloy Forge&r.",
              "- Der &6Recycler&r (Salvager), der Werkzeuge wieder in Teile und Materialien zerlegt. Er braucht Purpur-Eisen und ist deshalb in Stufe 1 noch nicht zu bauen.",
              "- Der &6Material-Veredler&r (Material Grader), der Materialien eine Qualitätsstufe gibt.",
              "- &6Stahl&r aus Mekanism und Immersive Engineering, mit Biegsam V ein hervorragendes Kopfmaterial.",
              "",
              "Purpur-Eisen und Co. kannst du schon aufheben, wenn du sie findest. Der Tooltip zeigt, dass sie erst in Stufe 2 benutzbar sind. Die Werkzeuge aus Stufe 1 musst du nicht wegwerfen: Mit neuen Spitzen, Verbindungen und Griffen rüstest du sie einfach auf.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["iron_kit"], icon="minecraft:netherrack", optional=True),
]

images = [
    banner("silent_gear/title", "Silent Gear", 4.4, -4.0, height=1.8, kind="title", colour="stone"),
    banner("silent_gear/first_steps", "Erste Schritte", 1.4, -1.85, height=0.9, colour="stone"),
    banner("silent_gear/templates", "Vorlagen", 9.6, -1.85, height=0.9, colour="nature"),
    banner("silent_gear/parts", "Bauteile", 0.42, 4.6, height=0.9, colour="brass"),
    banner("silent_gear/tools", "Werkzeuge", 0.83, 11.1, height=0.9, colour="brass"),
    banner("silent_gear/repair", "Pflege und Reparatur", 2.54, 17.6, height=0.9, colour="stone"),
    banner("silent_gear/goal", "Ziel", 16, 7.6, height=0.9, colour="brass"),
]

chapter(C, "Silent Gear", "silentgear:pickaxe", "storage", quests, shape="circle", order=6,
        subtitle=["Werkzeuge aus Teilen, bis zur Eisenstufe."], images=images)
