"""Silent Gear, stage 1: blueprints and templates, the first compound parts (heads, rods, bindings,
grips, tips), mixing materials and the crude mixer, a checklist of tools, upgrades, repair kits,
and the material tiers of the pack with durability and harvest speed from the 4.2.1.1 material
JSONs. Crimson iron, crimson steel, blaze gold and steel open in stage 2 (alloy forge, grader,
starlight charger, salvager need them); azure silver comes from End ore only, so azure electrum
and tyrian steel are effectively stage 4. Later quests are checkmarks. Repair kit numbers and the
crude mixer factor come from config/silentgear-common.toml."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner)

C = "silent_gear"


def mat(name, x, y, title, subtitle, line, tip, item, count, deps, rewards=None):
    """One material of the tier checklist: the stats line, one tip, one tick."""
    return quest(name, x, y, title, subtitle=subtitle,
                 description=[line, "", tip],
                 tasks=[task_item(item, count)],
                 rewards=rewards or [reward_xp(2)],
                 deps=deps, icon=item, shape="square")


def later(name, x, y, title, subtitle, description, deps, icon, stage=2):
    """A stage 2+ step, ticked by hand: its items are not open in stage 1."""
    return quest(name, x, y, title, subtitle=subtitle, description=description,
                 tasks=[task_checkmark(f"Kommt in Stufe {stage}: gelesen")],
                 rewards=[reward_xp(3)], deps=deps, icon=icon, optional=True)


quests = [
    # ---- Erste Schritte ---------------------------------------------------------------------
    quest("welcome", 0, 0, "&6&lBau Werkzeug aus Teilen",
          subtitle="Kopf plus Stiel, das Material entscheidet.",
          description=[
              "Eine Silent-Gear-Spitzhacke ist ein &6Kopf&r plus ein &6Stiel&r. Dazu kommen auf Wunsch &6Verbindung&r, &6Griff&r und &6Spitze&r. Jedes Teil darf aus einem anderen Material sein.",
              "",
              "&eDer Ablauf:&r Blaupause besorgen. Blaupause plus Material ins Raster ergibt das Teil. Teile zusammen ins Raster ergeben das Werkzeug.",
              "",
              "&eKronwerke:&r In Stufe 1 reicht Silent Gear bis Diamant. Die Nether-Metalle (Purpur-Eisen, Lohengold, Purpur-Stahl) und Stahl kommen in Stufe 2, die Azur-Metalle aus dem End in Stufe 4.",
          ],
          tasks=[task_checkmark("Los geht's")],
          rewards=[reward_item("minecraft:stick", 32), reward_table("s1_common")],
          icon="silentgear:pickaxe", size=2.0, shape="hexagon"),

    quest("starter_blueprints", 2.5, -1, "&7Pack das Blaupausenbündel aus",
          subtitle="Sechs Blaupausen geschenkt.",
          description=[
              "&eRechtsklick&r auf das &6Blaupausenbündel&r aus deinem Startinventar. Du bekommst Blaupausen für Stiel, Spitzhacke, Schaufel, Axt, Hacke und Schwert.",
              "",
              "Blaupausen werden beim Herstellen &enicht verbraucht&r. Über einer Blaupause zeigt &eAlt&r, welche Teile das Werkzeug braucht, &eU&r zeigt die Rezepte in JEI.",
          ],
          tasks=[task_item("silentgear:pickaxe_blueprint", 1)],
          rewards=[reward_item("minecraft:paper", 8), reward_xp(2)],
          deps=["welcome"], icon="silentgear:blueprint_package"),

    quest("blueprint_paper", 5, -1, "&7Mach Blaues Papier",
          subtitle="Das Papier für jede weitere Blaupause.",
          description=[
              "&6Vier Papier&r und &6ein blauer Farbstoff&r, formlos, ergeben &evier Blaue Papiere&r.",
              "",
              "Blauen Farbstoff gibt es aus Kornblumen, Lapis oder den &6Flachsblumen&r von Silent Gear. Eine Spitzhacke-Blaupause ist drei Blaues Papier oben, zwei Stöcke senkrecht darunter.",
          ],
          tasks=[task_item("silentgear:blueprint_paper", 8)],
          rewards=[reward_item("minecraft:sugar_cane", 16), reward_item("minecraft:lapis_lazuli", 4)],
          deps=["starter_blueprints"], icon="silentgear:blueprint_paper"),

    quest("material_book", 2.5, 1, "&7Schlag ein Material nach",
          subtitle="Jedes Material mit allen Werten.",
          description=[
              "Das &6Material Book&r liegt im Startinventar. Sonst: ein &6Buch&r und ein &6Blaues Papier&r, formlos.",
              "",
              "Es listet jedes Material mit Haltbarkeit, Tempo, Schaden und Eigenschaften und sortiert danach. Im Inventar zeigt &eStrg&r über einem Material dieselben Werte.",
          ],
          tasks=[task_item("silentgear:material_book", 1)],
          rewards=[reward_xp(3)],
          deps=["welcome"], icon="silentgear:material_book", optional=True),

    quest("blueprint_book", 5, 1, "&7Sammle Blaupausen im Buch",
          subtitle="Alle Blaupausen in einem Slot.",
          description=[
              "&6Ein Buch&r, &6eine Wolle&r, &6ein Goldbarren&r und &6drei Vorlagenbretter&r, formlos.",
              "",
              "Das Buch zählt im Raster als die gerade gewählte Blaupause. Mit &eZ&r und &eC&r blätterst du durch.",
          ],
          tasks=[task_item("silentgear:blueprint_book", 1)],
          rewards=[reward_xp(3)],
          deps=["blueprint_paper", "template_boards"], icon="silentgear:blueprint_book", optional=True),

    # ---- Vorlagen ---------------------------------------------------------------------------
    quest("crude_parts", 8, -1, "&7Bau grobe Werkzeugteile",
          subtitle="Bruchstein, Erde, Stock.",
          description=[
              "&6Ein Bruchstein&r, &6ein Erdblock&r und &6ein Stock&r, formlos, ergeben &evier Crude Tool Parts&r.",
              "",
              "Daraus baust du das grobe Messer, das aus Stämmen Vorlagenbretter schnitzt. Vorlagen sind der billige Weg ohne Blaupause.",
          ],
          tasks=[task_item("silentgear:crude_tool_parts", 4)],
          rewards=[reward_item("minecraft:cobblestone", 32)],
          deps=["welcome"], icon="silentgear:crude_tool_parts"),

    quest("crude_knife", 10.5, -1, "&7Schnitz ein grobes Messer",
          subtitle="Ein Werkzeug für den Steinamboss.",
          description=[
              "&6Ein Bruchstein&r über &6Crude Tool Parts&r ergibt das &6Crude Knife&r.",
              "",
              "Jeder Schnitt kostet einen Punkt Haltbarkeit. Mach gleich zwei. Ein Silent-Gear-Messer (Klinge plus Stiel) schnitzt genauso und lässt sich reparieren.",
          ],
          tasks=[task_item("silentgear:crude_knife", 1)],
          rewards=[reward_xp(2)],
          deps=["crude_parts"], icon="silentgear:crude_knife"),

    quest("stone_anvil", 8, 1, "&7Stell einen Steinamboss auf",
          subtitle="Die Arbeitsfläche für Messer und Hammer.",
          description=[
              "Oben in der Mitte &6ein Bruchstein&r, darunter &6Bruchstein, Erde, Bruchstein&r.",
              "",
              "Leg einen Block mit &eRechtsklick&r darauf und klick dann mit dem passenden Werkzeug darauf. Mit einem Hammer wird aus einem Bruchstein so &eneun Kiesel&r.",
          ],
          tasks=[task_item("silentgear:stone_anvil", 1)],
          rewards=[reward_item("minecraft:oak_log", 16)],
          deps=["crude_parts"], icon="silentgear:stone_anvil"),

    quest("template_boards", 10.5, 1, "&7Schneide Vorlagenbretter",
          subtitle="Sechs Bretter aus einem Stamm.",
          description=[
              "Leg einen &6Holzstamm&r auf den Steinamboss und klick mit dem &6Crude Knife&r darauf: &esechs Vorlagenbretter&r.",
              "",
              "Du brauchst sie für Vorlagen, für Reparaturkits, das Modkit und das Blaupausenbuch.",
          ],
          tasks=[task_item("silentgear:template_board", 12)],
          rewards=[reward_item("minecraft:oak_log", 16), reward_xp(3)],
          deps=["crude_knife", "stone_anvil"], icon="silentgear:template_board"),

    quest("template", 13, 0, "&7Bau eine Spitzhacke-Vorlage",
          subtitle="Wie eine Blaupause, aber nur einmal.",
          description=[
              "Drei &6Vorlagenbretter&r oben, zwei &6Stöcke&r senkrecht darunter. Gleiche Form wie die Blaupause.",
              "",
              "Die Vorlage verschwindet nach einem Teil. Gut für Teile, die du nur einmal brauchst, oder wenn dir blauer Farbstoff fehlt.",
          ],
          tasks=[task_item("silentgear:pickaxe_template", 1)],
          rewards=[reward_xp(2)],
          deps=["template_boards"], icon="silentgear:pickaxe_template", optional=True),

    # ---- Die ersten Teile -------------------------------------------------------------------
    quest("rod", 0, 5, "&6Bau vier Stiele",
          subtitle="Der Teil, den du in der Hand hältst.",
          description=[
              "&6Stiel-Blaupause&r plus &6zwei Stöcke&r ergibt &evier Stiele&r. Mit zwei Knochen oder zwei Eisenstäben geht es genauso.",
              "",
              "&cAchtung:&r Das Spiel nennt den Stiel auf Deutsch auch &eGriff&r, wie das Zusatzteil. Hier heißt er Stiel.",
              "",
              "Holz und Eisen geben Flexibel II, Knochen +20 Prozent Schaden. Steinstiele sind Brüchig II, besser nicht.",
          ],
          tasks=[task_item("silentgear:rod", 4)],
          rewards=[reward_item("minecraft:stick", 32)],
          deps=["welcome"], icon="silentgear:rod", size=1.5, shape="square"),

    quest("iron_rod", 0, 7, "&7Schmiede Eisenstäbe",
          subtitle="Für einen Stiel ganz aus Eisen.",
          description=[
              "&6Zwei Eisenbarren&r übereinander ergeben &evier Eisenstäbe&r. Zwei davon mit der Stiel-Blaupause: vier Eisenstiele.",
              "",
              "Werte wie beim Holzstiel, Flexibel II. Der Unterschied ist die Optik.",
          ],
          tasks=[task_item("silentgear:iron_rod", 4)],
          rewards=[reward_xp(2)],
          deps=["rod"], icon="silentgear:iron_rod", optional=True),

    quest("pickaxe_head", 2.5, 5, "&6Bau einen Spitzhackenkopf",
          subtitle="Blaupause plus drei Material.",
          description=[
              "&6Spitzhacke-Blaupause&r plus &edrei&r Einheiten Material. Ein Barren, ein Edelstein oder ein Bruchstein ist eine Einheit.",
              "",
              "Der Kopf bestimmt Haltbarkeit, Tempo, Schaden und Abbaustufe. Ein Eisenkopf hat 250 Haltbarkeit und Tempo 6 und baut Diamanterz ab.",
          ],
          tasks=[task_item("silentgear:pickaxe_head", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 6)],
          deps=["rod"], icon="silentgear:pickaxe_head"),

    quest("pickaxe", 5, 5, "&6&lSteck deine Spitzhacke zusammen",
          subtitle="Kopf plus Stiel, fertig.",
          description=[
              "&6Spitzhackenkopf&r und &6Stiel&r zusammen ins Raster. Oder in einem Schritt: Blaupause, drei Material und ein Stiel.",
              "",
              "Silent-Gear-Werkzeug &everschwindet nicht&r, wenn es kaputtgeht. Es bleibt als zerbrochen im Inventar, bis du es reparierst.",
          ],
          tasks=[task_item("silentgear:pickaxe", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["pickaxe_head"], icon="silentgear:pickaxe", size=2.0, shape="hexagon"),

    quest("reading_stats", 5, 7.5, "&7Lies den Tooltip",
          subtitle="Strg, Shift, Alt.",
          description=[
              "&eStrg&r halten: alle Werte und Eigenschaften. &eShift&r: was jede Eigenschaft tut. &eAlt&r: aus welchen Teilen das Werkzeug besteht.",
              "",
              "Kommt dieselbe Eigenschaft aus mehreren Teilen, steigt ihre Stufe. Manche heben sich auf: Biegsam gegen Brüchig.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["pickaxe"], icon="minecraft:spyglass"),

    quest("mix", 2.5, 7.5, "&7Misch zwei Materialien im Kopf",
          subtitle="Werte werden gemittelt.",
          description=[
              "Leg zur Blaupause zum Beispiel &6zwei Eisen&r und &6ein Gold&r. Der Kopf mittelt die Werte und nimmt die Eigenschaften beider mit.",
              "",
              "Die &6Synergie&r im Tooltip sinkt, je unterschiedlicher die Materialien sind. &6Rostig&r (Papier, Terrakotta) hebt eine niedrige Synergie, &6Synergistisch&r (Smaragd) belohnt eine hohe.",
          ],
          tasks=[task_checkmark("Einen gemischten Kopf gebaut")],
          rewards=[reward_item("minecraft:gold_ingot", 3), reward_xp(3)],
          deps=["pickaxe_head"], icon="minecraft:gold_ingot", optional=True),

    quest("binding", 7.5, 4, "&6Bau eine Verbindung",
          subtitle="Flexibel: das Werkzeug nimmt oft keinen Schaden.",
          description=[
              "&eBlaupause:&r ein &6Blaues Papier&r und &6zwei Fäden&r, formlos. Dann Blaupause plus &eein&r Material: die Verbindung.",
              "",
              "Faden gibt Flexibel I, Flachsstrang Flexibel III und +5 Prozent Tempo, Sehnenfaser Flexibel IV. Ranken geben nur Optik.",
          ],
          tasks=[task_item("silentgear:binding", 1)],
          rewards=[reward_item("minecraft:string", 16)],
          deps=["pickaxe"], icon="silentgear:binding"),

    quest("sinew", 10, 3, "&7Trockne Sehnen",
          subtitle="Die beste Verbindung in Stufe 1.",
          description=[
              "Kühe, Schweine und Schafe lassen manchmal eine &6Sehne&r fallen. Im Ofen wird sie &6Getrocknete Sehne&r, im Raster &edrei Sehnenfasern&r.",
              "",
              "Sehnenfaser ist Flexibel IV, als Bogensehne Flexibel II und +20 Prozent Fernschaden.",
          ],
          tasks=[task_item("silentgear:sinew_fiber", 3)],
          rewards=[reward_item("minecraft:cooked_beef", 8)],
          deps=["binding"], icon="silentgear:sinew_fiber", optional=True),

    quest("flax", 10, 5, "&7Bau Flachs an",
          subtitle="Fasern, Samen und blauer Farbstoff.",
          description=[
              "&6Wilder Flachs&r wächst in der Oberwelt. Abbauen gibt Samen für Ackerland. Reife Pflanzen geben &6Flachsfasern&r und &6Flachsblumen&r.",
              "",
              "Zwei Fasern ergeben einen &6Flachsstrang&r. Flachsblumen werden zu blauem Farbstoff für Blaues Papier.",
          ],
          tasks=[task_item("silentgear:flax_string", 4)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["binding"], icon="silentgear:flax_string", optional=True),

    quest("grip", 7.5, 6, "&6Wickel einen Griff",
          subtitle="Mehr Tempo beim Graben und Schlagen.",
          description=[
              "&eBlaupause:&r &6zwei Blaues Papier&r und &eein Leder&r oder &eeine Wolle&r, formlos. Dann Blaupause plus ein Material.",
              "",
              "Leder: +15 Prozent Abbautempo, +0,15 Angriffstempo, Flexibel III. Wolle: +10 Prozent Abbautempo, +0,2 Angriffstempo, Flexibel II.",
          ],
          tasks=[task_item("silentgear:grip", 1)],
          rewards=[reward_item("minecraft:leather", 6)],
          deps=["binding"], icon="silentgear:grip"),

    quest("tip", 7.5, 8, "&6Setz eine Spitze auf",
          subtitle="Ein harter Kern an der Kante.",
          description=[
              "&eBlaupause:&r &6zwei Blaues Papier&r, &6ein Papier&r, &6ein Stein&r, formlos. Dann Blaupause plus ein Material. Werkzeug plus Spitze ins Raster baut sie ein.",
              "",
              "Eisen: +128 Haltbarkeit, +1 Tempo, +1 Schaden, Abbaustufe Eisen. Gold: +6 Tempo. Redstone: +20 Prozent Tempo, +2 Schaden. Diamant: +256 Haltbarkeit, Abbaustufe Diamant.",
              "",
              "&eTipp:&r Eine Eisenspitze auf einem Steinkopf baut für einen Barren Diamanterz ab.",
          ],
          tasks=[task_item("silentgear:tip", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(3)],
          deps=["grip"], icon="silentgear:tip"),

    quest("builds", 10, 8, "&7Merk dir vier gute Builds",
          subtitle="Rezepte, die sich bewährt haben.",
          description=[
              "&6Tag eins:&r Kopf aus drei Bruchstein, Holzstiel. &6Aufsteiger:&r Steinkopf plus Eisenspitze, baut Diamanterz ab.",
              "",
              "&6Alltag:&r Eisenkopf, Eisenstiel, Sehnen-Verbindung, Ledergriff. Biegsam III und zweimal Flexibel halten lange.",
              "",
              "&6Waffe:&r Schwertklinge aus zwei Feuerstein. Gezackt III erhöht den Schaden, je abgenutzter die Klinge ist.",
          ],
          tasks=[task_checkmark("Notiert")],
          rewards=[reward_xp(3)],
          deps=["tip"], icon="minecraft:writable_book", optional=True),

    quest("crude_mixer", 2.5, 9.5, "&6Bau einen Crude Mixer",
          subtitle="Die erste Legierung, aus allem.",
          description=[
              "Oben &6Stein, Flachsstrang, Stein&r. Mitte &6Stein, Brett, Stein&r. Unten in der Mitte &6Stein&r.",
              "",
              "Der Crude Mixer mischt beliebige Materialien zu einer &6Rohen Legierung&r, auch Metall mit Edelstein. Sie trägt die Eigenschaft &cRoh&r und hat nur &e80 Prozent&r der gemischten Werte.",
          ],
          tasks=[task_item("silentgear:crude_mixer", 1)],
          rewards=[reward_item("minecraft:stone", 16), reward_xp(4)],
          deps=["mix", "flax"], icon="silentgear:crude_mixer"),

    quest("crude_alloy", 5, 9.5, "&7Misch eine Rohe Legierung",
          subtitle="Ein neues Material aus zwei alten.",
          description=[
              "Leg zwei verschiedene Materialien in den &6Crude Mixer&r, etwa Kupfer und Eisen. Heraus kommt eine &6Rohe Legierung&r, die wie ein eigenes Material in Köpfe geht.",
              "",
              "Lohnt sich, wenn zwei Eigenschaften zusammen sollen. Für reine Werte ist ein sortenreiner Kopf besser. Die echte Legierungsschmiede kommt in Stufe 2.",
          ],
          tasks=[task_item("silentgear:crude_alloy", 1)],
          rewards=[reward_xp(5)],
          deps=["crude_mixer"], icon="silentgear:crude_alloy", optional=True),

    # ---- Werkzeuge (Checkliste) ---------------------------------------------------------------
    quest("axe", 0, 13, "&6Bau eine Axt",
          subtitle="Axtkopf aus drei Material.",
          description=[
              "&6Axt-Blaupause&r plus &edrei&r Material ergibt den Axtkopf, dazu ein Stiel.",
              "",
              "Eisen gibt der Axt -0,1 Angriffstempo. Feuerstein macht sie mit Gezackt im Kampf gefährlich.",
          ],
          tasks=[task_item("silentgear:axe", 1)],
          rewards=[reward_item("minecraft:oak_log", 16)],
          deps=["pickaxe"], icon="silentgear:axe", size=1.5, shape="square"),

    quest("shovel", 2.5, 12, "&7Bau eine Schaufel",
          subtitle="Nur ein Material für den Kopf.",
          description=[
              "&6Schaufel-Blaupause&r plus &eein&r Material, dazu ein Stiel.",
              "",
              "Das billigste Werkzeug, um ein neues Material auszuprobieren. Gold baut mit Tempo 12 Erde und Sand sehr schnell ab.",
          ],
          tasks=[task_item("silentgear:shovel", 1)],
          rewards=[reward_xp(2)],
          deps=["axe"], icon="silentgear:shovel"),

    quest("sword", 2.5, 14, "&7Bau ein Schwert",
          subtitle="Klinge aus zwei Material.",
          description=[
              "&6Schwert-Blaupause&r plus &ezwei&r Material, dazu ein Stiel, auf Wunsch ein Griff.",
              "",
              "Eisen und Feuerstein geben je +2 Schaden. Gold und Kupfer verzaubern sich besser (Verzauberbarkeit 22 und 15 gegen 14 bei Eisen).",
          ],
          tasks=[task_item("silentgear:sword", 1)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["axe"], icon="silentgear:sword"),

    quest("knife", 5, 14, "&7Bau ein Messer",
          subtitle="Klinge aus einem Material.",
          description=[
              "&6Messer-Blaupause&r: ein Blaues Papier, ein Stock. Klinge aus &eeinem&r Material, dazu ein Stiel.",
              "",
              "Schnell, leicht, und es schnitzt Vorlagenbretter auf dem Steinamboss. Anders als das grobe Messer lässt es sich reparieren.",
          ],
          tasks=[task_item("silentgear:knife", 1)],
          rewards=[reward_xp(2)],
          deps=["sword"], icon="silentgear:knife", optional=True),

    quest("hammer", 5, 12, "&6&lGrab mit dem Hammer 3x3",
          subtitle="Neun Blöcke pro Schlag.",
          description=[
              "&eBlaupause:&r &6sechs Blaues Papier&r in den oberen zwei Reihen, &6ein Stock&r unten in der Mitte. Der Hammerkopf braucht &esechs&r Material.",
              "",
              "Langsamer als die Spitzhacke und jeder Block kostet Haltbarkeit. Eine Sehnen-Verbindung und ein Ledergriff lohnen sich hier am meisten.",
              "",
              "&eTipp:&r Hammer für Tunnel, FTB Ultimine für Erzadern.",
          ],
          tasks=[task_item("silentgear:hammer", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 12), reward_xp(5)],
          deps=["shovel"], icon="silentgear:hammer", size=1.5),

    quest("excavator", 7.5, 12, "&7Bau einen Aushöhler",
          subtitle="Der Hammer für Erde und Sand.",
          description=[
              "&eBlaupause:&r oben zwei Blaues Papier mit Lücke, Mitte drei, unten ein Stock in der Mitte. Der Kopf braucht &efünf&r Material, dazu ein Stiel.",
              "",
              "Gräbt wie die Schaufel, aber 3x3. Ideal für Baustellen und Sandwüsten.",
          ],
          tasks=[task_item("silentgear:excavator", 1)],
          rewards=[reward_xp(4)],
          deps=["hammer"], icon="silentgear:excavator", optional=True),

    quest("saw", 10, 12, "&7Bau eine Säge",
          subtitle="Ein Schnitt, der ganze Baum fällt.",
          description=[
              "&eBlaupause:&r fünf Blaues Papier und zwei Stöcke, siehe JEI. Das Sägeblatt braucht &efünf&r Material, dazu ein Stiel.",
              "",
              "Die Säge fällt den ganzen Baum auf einmal. Pro Stamm kostet sie Haltbarkeit.",
          ],
          tasks=[task_item("silentgear:saw", 1)],
          rewards=[reward_item("minecraft:oak_sapling", 8), reward_xp(4)],
          deps=["hammer"], icon="silentgear:saw", optional=True),

    quest("paxel", 7.5, 14, "&7Bau einen Spaxfel",
          subtitle="Spitzhacke, Axt und Schaufel in einem.",
          description=[
              "&eBlaupause:&r sechs Blaues Papier und zwei Stöcke. Der Kopf braucht &efünf&r Material.",
              "",
              "Etwas langsamer als die einzelnen Werkzeuge, spart aber zwei Plätze in der Hotbar.",
          ],
          tasks=[task_item("silentgear:paxel", 1)],
          rewards=[reward_xp(4)],
          deps=["hammer"], icon="silentgear:paxel", optional=True),

    quest("sickle", 10, 14, "&7Bau eine Sichel",
          subtitle="Mäht ein ganzes Feld.",
          description=[
              "&eBlaupause:&r drei Blaues Papier und ein Stock. Die Klinge braucht &edrei&r Material.",
              "",
              "Erntet Pflanzen, Gras und Blumen um den getroffenen Block. Praktisch für die Felder von Farmer's Delight.",
          ],
          tasks=[task_item("silentgear:sickle", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16)],
          deps=["paxel"], icon="silentgear:sickle", optional=True),

    quest("prospector", 12.5, 13, "&7Bau einen Prospektorhammer",
          subtitle="Findet Erz hinter der Wand.",
          description=[
              "&eBlaupause:&r zwei Blaues Papier oben, ein Stock, ein Eisenbarren unten. Der Kopf braucht &ezwei&r Material.",
              "",
              "Klick damit auf einen Block. Er meldet Erze in bis zu &e16 Blöcken&r Entfernung.",
          ],
          tasks=[task_item("silentgear:prospector_hammer", 1)],
          rewards=[reward_item("minecraft:raw_iron", 8), reward_xp(4)],
          deps=["saw", "sickle"], icon="silentgear:prospector_hammer", optional=True),

    quest("armor", 0, 16, "&7Bau einen Helm",
          subtitle="Rüstung aus Teilen.",
          description=[
              "&6Helm-Blaupause&r: fünf Blaues Papier in Helmform. Die Helmplatten brauchen &efünf&r Material. Brust, Beine, Stiefel brauchen acht, sieben und vier.",
              "",
              "Ein voller Eisensatz gibt 15 Rüstungspunkte. Ein &6Futter&r (Lining) aus Leder bringt Flexibel IV.",
          ],
          tasks=[task_item("silentgear:helmet", 1)],
          rewards=[reward_item("minecraft:leather", 4)],
          deps=["sword"], icon="silentgear:helmet", optional=True),

    quest("bow", 2.5, 16, "&7Spann einen Bogen",
          subtitle="Bogenarme, Stiel und Sehne.",
          description=[
              "Bogenarme aus &edrei&r Material, ein Stiel und eine &6Sehne&r (Cord) ins Raster. Die Sehnen-Blaupause ist drei Blaues Papier neben drei Fäden.",
              "",
              "Faden spannt 10 Prozent schneller, Sehnenfaser gibt +20 Prozent Fernschaden.",
          ],
          tasks=[task_item("silentgear:bow", 1)],
          rewards=[reward_item("minecraft:arrow", 32)],
          deps=["sword"], icon="silentgear:bow", optional=True),

    # ---- Upgrades ---------------------------------------------------------------------------
    quest("upgrade_base", 0, 20, "&7Bau Upgrade-Basen",
          subtitle="Die Grundplatte für jedes Upgrade.",
          description=[
              "&6Zwei Papier&r, &6ein Brett&r, &6ein Stein&r, formlos: &evier Upgrade-Basen&r. Eine Basis mit rotem Farbstoff gibt vier &6Rote Karten&r.",
              "",
              "Mit der Roten Karte zerbricht ein Werkzeug endgültig wie in Vanilla. Eingebaut wird jedes Upgrade am &6Schmiedetisch&r mit einem &6Stock&r als Vorlage.",
          ],
          tasks=[task_item("silentgear:upgrade_base", 4)],
          rewards=[reward_item("minecraft:paper", 16)],
          deps=["tip"], icon="silentgear:upgrade_base"),

    quest("adv_upgrade", 2.5, 20, "&7Bau eine verbesserte Upgrade-Basis",
          subtitle="Diamantsplitter, Gold, Farbe.",
          description=[
              "Oben &6drei Diamantsplitter&r, Mitte &6blauer Farbstoff, Upgrade-Basis, blauer Farbstoff&r, unten &6drei Goldnuggets&r.",
              "",
              "Einen Diamanten zerlegst du im Raster in &eneun Splitter&r.",
              "",
              "Daraus: &6Straßenplanierer&r (plus Eisenschaufel und oranger Farbstoff, Trampelpfade in 3x3 mit dem Aushöhler) und &6Löffel-Upgrade&r (plus Diamantschaufel, die Spitzhacke gräbt auch Erde).",
          ],
          tasks=[task_item("silentgear:advanced_upgrade_base", 1)],
          rewards=[reward_item("minecraft:gold_nugget", 9), reward_xp(3)],
          deps=["upgrade_base"], icon="silentgear:advanced_upgrade_base", optional=True),

    # ---- Pflege und Reparatur ---------------------------------------------------------------
    quest("broken", 0, 24, "&7Reparier statt wegzuwerfen",
          subtitle="Zerbrochen heißt hier: reparieren.",
          description=[
              "Ein Werkzeug ohne Haltbarkeit bleibt als &ezerbrochen&r im Inventar. Teile, Verzauberungen und Materialien bleiben.",
              "",
              "Repariert wird mit einem &6Reparaturkit&r. Im Amboss mit dem Kopfmaterial geht es auch, kostet aber Level und wirkt nur halb so gut.",
          ],
          tasks=[task_checkmark("Gut zu wissen")],
          rewards=[reward_xp(2)],
          deps=["pickaxe"], icon="silentgear:very_crude_repair_kit", size=1.5, shape="square"),

    quest("repair_kit", 2.5, 24, "&6Füll ein Reparaturkit",
          subtitle="Material rein, Werkzeug heil.",
          description=[
              "Oben ein &6Stock&r, Mitte &6Vorlagenbrett, Eisenbarren, Vorlagenbrett&r, unten &6drei Vorlagenbretter&r. Kit plus Material füllt es, Kit plus Werkzeug repariert.",
              "",
              "Das Material muss eins aus dem Kopf sein. Das Kit fasst &e16&r Einheiten bei &e35 Prozent&r Wirkung. Mit Stein statt Eisen: 8 Einheiten, 30 Prozent.",
          ],
          tasks=[task_item("silentgear:crude_repair_kit", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 8), reward_xp(3)],
          deps=["broken", "template_boards"], icon="silentgear:crude_repair_kit"),

    quest("sturdy_kit", 5, 24, "&7Bau ein robustes Reparaturkit",
          subtitle="32 Einheiten, 40 Prozent.",
          description=[
              "Oben ein &6Eisenstab&r, Mitte &6Eisenbarren, Diamant, Eisenbarren&r, unten &6drei Eisenbarren&r.",
              "",
              "Fasst &e32&r Einheiten und repariert mit &e40 Prozent&r. Für Hammer und Spaxfel, die viel verschleißen.",
          ],
          tasks=[task_item("silentgear:sturdy_repair_kit", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 12), reward_xp(4)],
          deps=["repair_kit"], icon="silentgear:sturdy_repair_kit", optional=True),

    quest("swap_parts", 2.5, 26, "&7Tausch ein Teil aus",
          subtitle="Ein Werkzeug, das mit dir wächst.",
          description=[
              "Werkzeug plus neues Teil ins Raster: das Teil wird eingebaut, das alte kommt zurück.",
              "",
              "So wird die Spitzhacke vom ersten Tag Stück für Stück besser. Nur den Kopf tauschst du so nicht.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["repair_kit"], icon="silentgear:binding"),

    quest("mod_kit", 5, 26, "&7Bau ein Modkit",
          subtitle="Teile wieder ausbauen.",
          description=[
              "Oben &6zwei Vorlagenbretter, Eisenbarren&r, unten &6zwei Vorlagenbretter, Stock&r.",
              "",
              "Mit dem Kit in der Hand wählst du per &eZ&r und &eC&r die Teilart, dann Kit plus Werkzeug ins Raster. Heraus kommen Werkzeug und Teil getrennt.",
          ],
          tasks=[task_item("silentgear:mod_kit", 1)],
          rewards=[reward_xp(2)],
          deps=["swap_parts"], icon="silentgear:mod_kit", optional=True),

    # ---- Materialstufen in Stufe 1 (Checkliste) ----------------------------------------------
    mat("m_stone", 16, -1, "&7Stein", "131 Haltbarkeit, Tempo 4.",
        "&6Bruchstein&r: &e131&r Haltbarkeit, Tempo &e4&r, Abbaustufe Stein, Urzeitlich I (mehr Erfahrung).",
        "Der Kopf für den ersten Tag. Kostet nichts.", "minecraft:cobblestone", 3, ["pickaxe_head"]),
    mat("m_flint", 16, 0.5, "&7Feuerstein", "124 Haltbarkeit, Tempo 5.",
        "&6Feuerstein&r: &e124&r Haltbarkeit, Tempo &e5&r, +2 Schaden, Gezackt III.",
        "Für Klingen: Gezackt erhöht den Schaden, je abgenutzter die Klinge ist.", "minecraft:flint", 3, ["m_stone"]),
    mat("m_copper", 16, 2, "&6Kupfer", "151 Haltbarkeit, Tempo 5.",
        "&6Kupfer&r: &e151&r Haltbarkeit, Tempo &e5&r, Abbaustufe Kupfer, Weich I.",
        "Weich bremst das Tempo, je abgenutzter das Werkzeug ist. Gut verzauberbar (15).", "minecraft:copper_ingot", 3, ["m_flint"]),
    mat("m_iron", 16, 3.5, "&fEisen", "250 Haltbarkeit, Tempo 6.",
        "&6Eisen&r: &e250&r Haltbarkeit, Tempo &e6&r, +2 Schaden, Abbaustufe Eisen, Biegsam III.",
        "Der Standard für Stufe 1. Baut Diamanterz ab.", "minecraft:iron_ingot", 3, ["m_copper"],
        rewards=[reward_item("minecraft:iron_ingot", 3), reward_xp(2)]),
    mat("m_gold", 16, 5, "&eGold", "32 Haltbarkeit, Tempo 12.",
        "&6Gold&r: nur &e32&r Haltbarkeit, aber Tempo &e12&r, Verzauberbarkeit 22, Weich III.",
        "Besser als Spitze (+6 Tempo) als im ganzen Kopf.", "minecraft:gold_ingot", 3, ["m_iron"]),
    mat("m_emerald", 16, 6.5, "&aSmaragd", "1 080 Haltbarkeit, Tempo 10.",
        "&6Smaragd&r: &e1 080&r Haltbarkeit, Tempo &e10&r, Brüchig I, Synergistisch II.",
        "Als Spitze: +512 Haltbarkeit und +2 Tempo.", "minecraft:emerald", 3, ["m_gold"]),
    mat("m_diamond", 16, 8, "&bDiamant", "1 561 Haltbarkeit, Tempo 8.",
        "&6Diamant&r: &e1 561&r Haltbarkeit, Tempo &e8&r, +3 Schaden, Abbaustufe Diamant, Brüchig II.",
        "Das Beste in Stufe 1. Brüchig gleichst du mit Eisenstiel und Sehnen-Verbindung aus.", "minecraft:diamond", 3, ["m_emerald"],
        rewards=[reward_table("s1_uncommon"), reward_xp(4)]),

    # ---- Ziel -------------------------------------------------------------------------------
    quest("iron_kit", 19.5, 3.5, "&6&lRüste dich komplett aus",
          subtitle="Vier Werkzeuge, alle aus Teilen.",
          description=[
              "Spitzhacke, Axt, Schwert und Hammer, alle aus Silent Gear. Das Material entscheidest du.",
              "",
              "Leg sie mit dem Werkzeugtausch-Upgrade in den Rucksack, dann hast du immer das richtige in der Hand.",
          ],
          tasks=[task_item("silentgear:pickaxe", 1), task_item("silentgear:axe", 1),
                 task_item("silentgear:sword", 1), task_item("silentgear:hammer", 1)],
          rewards=[reward_table("s1_rare"), reward_xp(10)],
          deps=["tip", "hammer", "repair_kit", "m_diamond"], icon="silentgear:hammer", size=2.5, shape="gear"),

    # ---- Stufe 2 und später -----------------------------------------------------------------
    later("outlook", 16, 11.5, "&cFinde Purpur-Eisen im Nether",
          "420 Haltbarkeit, Tempo 10.",
          ["&6Purpur-Eisenerz&r liegt im Nether, auch im Schwarzstein. Rohes Erz im Ofen gibt den Barren.",
           "",
           "&6Purpur-Eisen&r: &e420&r Haltbarkeit, Tempo &e10&r, Biegsam III, Hart II, Hitzebeständig IV. Als Spitze +224 Haltbarkeit und Feurig."],
          ["iron_kit"], "silentgear:raw_crimson_iron"),
    later("blaze_gold", 18.5, 11.5, "&6Schmilz Lohengold",
          "69 Haltbarkeit, Tempo 15.",
          ["&6Ein Goldbarren&r und &6vier Lohenstaub&r, formlos. In der Legierungsschmiede reichen zwei Lohenstaub.",
           "",
           "&6Lohengold&r: &e69&r Haltbarkeit, Tempo &e15&r, Gierig III (schneller an Erz). Du brauchst es für Veredler und Sternlicht-Ladestation."],
          ["outlook"], "silentgear:blaze_gold_dust"),
    later("steel", 21, 11.5, "&7Nimm Stahl in den Kopf",
          "500 Haltbarkeit, Tempo 6.",
          ["&6Stahl&r aus Mekanism oder Immersive Engineering zählt als Material.",
           "",
           "&e500&r Haltbarkeit, Tempo &e6&r, +4 Schaden, Biegsam V. Als Stiel +25 Prozent Haltbarkeit. Das Arbeitstier von Stufe 2."],
          ["outlook"], "minecraft:iron_block"),
    later("crimson_steel", 16, 13.5, "&4Schmiede Purpur-Stahl",
          "2 400 Haltbarkeit, Tempo 15.",
          ["Oben &6zwei Lohenruten&r, Mitte &6Purpur-Eisen, Magmacreme, Purpur-Eisen&r, unten &6zwei Purpur-Eisen&r: ein Barren.",
           "",
           "&6Purpur-Stahl&r: &e2 400&r Haltbarkeit, Tempo &e15&r, +6 Schaden, Biegsam V, Hart III.",
           "",
           "In der Legierungsschmiede gibt ein Purpur-Eisenblock mit zwei Lohenruten und Magmacreme &edrei&r Barren."],
          ["outlook"], "silentgear:crimson_repair_kit"),
    later("alloy_forge", 18.5, 13.5, "&6Bau die Legierungsschmiede",
          "Legierungen ohne Raster, mehr pro Erz.",
          ["&eRezept auf Kronwerke:&r Oben &6Purpur-Stahl, Schwarzstein, Purpur-Stahl&r. Mitte zwei &6Purpur-Stahl&r. Unten &6Schwarzstein&r, ein &6Messinggehäuse&r von Create, &6Schwarzstein&r.",
           "",
           "Sie macht Purpur-Stahl, Lohengold, Azur-Elektrum und Tyrann-Stahl. Dazu &6Kohlenstoffstahl&r: ein Eisen und drei Kohle, 420 Haltbarkeit und +4 Schaden."],
          ["crimson_steel"], "silentgear:alloy_forge"),
    later("salvager", 21, 13.5, "&7Bau einen Recycler",
          "Altes Werkzeug zurück in Material.",
          ["Oben ein &6Kolben&r, Mitte &6Purpur-Eisen, Eisenblock, Purpur-Eisen&r, unten &6Purpur-Eisen, Obsidian, Purpur-Eisen&r.",
           "",
           "Zerlegt Silent-Gear-Werkzeug und Vanilla-Werkzeug in Material. Pro Teil gehen &e0 bis 50 Prozent&r verloren."],
          ["outlook"], "silentgear:salvager"),
    later("grader", 16, 15.5, "&dVeredle ein Material",
          "Noten von E bis SSS.",
          ["Oben &6Quarz, Eisen, Quarz&r, Mitte &6Eisen, verbesserte Upgrade-Basis, Eisen&r, unten &6drei Lohengold&r.",
           "",
           "Material plus Katalysator rein, heraus kommt es mit einer Note. Der Mittelwert ist &eC&r.",
           "",
           "Katalysator I: &6Leuchtender Staub&r (Stock, zwei Glowstone, Quarz, gibt vier). II: Lohengold-Staub und zwei Glowstone."],
          ["blaze_gold"], "silentgear:material_grader"),
    later("charger", 18.5, 15.5, "&dLad Material im Sternlicht",
          "Nur nachts, nur unter freiem Himmel.",
          ["Oben &6Quarzblock, Glas, Quarzblock&r. Mitte &6polierter Schwarzstein, Glas, polierter Schwarzstein&r. Unten polierter Schwarzstein, &6Lohengoldblock&r, polierter Schwarzstein.",
           "",
           "Die &6Sternlicht-Ladestation&r sammelt nachts Ladung, wenn sie den Himmel sieht. Katalysator I ist Lohengold-Staub, II Azur-Silber-Staub, III Sternmetall-Staub."],
          ["blaze_gold"], "silentgear:starlight_charger"),
    later("azure", 16, 17.5, "&bFinde Azur-Silber im End",
          "197 Haltbarkeit, Tempo 19.",
          ["&6Azur-Silbererz&r gibt es nur im &5End&r, also praktisch ab Stufe 4.",
           "",
           "&6Azur-Silber&r: &e197&r Haltbarkeit, Tempo &e19&r, Mondläufer IV (weniger Schwerkraft).",
           "",
           "&6Azur-Elektrum&r (Block Azur-Silber, zwei Gold, Enderperle, gibt drei): &e1 259&r Haltbarkeit, Tempo &e29&r."],
          ["charger"], "silentgear:raw_azure_silver", stage=4),
    later("tyrian", 18.5, 17.5, "&5Legier Tyrann-Stahl",
          "3 652 Haltbarkeit, Tempo 18.",
          ["In der Legierungsschmiede: &6Purpur-Stahl&r, &6Azur-Elektrum&r, &6zerkleinerte Shulkerschale&r und &6Netheritschrott&r: vier Barren.",
           "",
           "&6Tyrann-Stahl&r: &e3 652&r Haltbarkeit, Tempo &e18&r, +8 Schaden, Robust III, Leerenwächter. Das Ende der Leiter."],
          ["azure", "alloy_forge"], "minecraft:purple_dye", stage=4),

    # ---- neue Quests -----------------------------------------------------------------
    quest("fluffy", 12.5, 5, "&7Ernte Flauschpflanzen",
          subtitle="Weiche Fasern für Sehne und Verbindung.",
          description=[
              "&6Wilde Flauschpflanzen&r wachsen wie Flachs überall in der Oberwelt. Abbauen gibt &6Flauschige Samen&r für Ackerland, reife Pflanzen geben &6Flauschbälle&r, mit Glück mehr.",
              "",
              "Drei Flauschbälle in einer Reihe ergeben einen &6Flauschigen Strang&r. Als Verbindung bringt er Flexibel III, als Sehne (Cord) +5 Prozent Fernschaden bei etwas langsamerem Spannen. Vier im Quadrat ergeben &6Flauschigen Stoff&r, fünf schräg eine &6Flauschige Feder&r.",
          ],
          tasks=[task_item("silentgear:fluffy_string", 4)],
          rewards=[reward_item("minecraft:bone_meal", 16)],
          deps=["flax"], icon="silentgear:fluffy_string", optional=True),

    quest("mattock", 12.5, 12, "&7Bau eine Breithacke",
          subtitle="Hacke, Schaufel und Axt für den Hof.",
          description=[
              "&eBlaupause:&r vier Blaues Papier und zwei Stöcke. Der Kopf braucht &evier&r Material.",
              "",
              "Die &6Breithacke&r pflügt Ackerland, gräbt Erde und fällt Holz. Etwas langsamer als Schaufel oder Axt, dafür haltbarer, und sie zählt überall, wo eine Hacke verlangt wird.",
          ],
          tasks=[task_item("silentgear:mattock", 1)],
          rewards=[reward_item("minecraft:wheat_seeds", 16), reward_xp(3)],
          deps=["shovel"], icon="silentgear:mattock", optional=True),

    quest("machete", 12.5, 15, "&7Bau eine Machete",
          subtitle="Schwert, Axt und Sichel in einem.",
          description=[
              "&eBlaupause:&r drei Blaues Papier und ein Stock. Die Klinge braucht &edrei&r Material.",
              "",
              "Die &6Machete&r ist vor allem ein Schwert, etwas schneller und schwächer als das normale. Dazu fällt sie Holz und mäht wie eine Sichel Pflanzen um den Block, nur auf kleinerer Fläche. Für den Dschungel genau richtig.",
          ],
          tasks=[task_item("silentgear:machete", 1)],
          rewards=[reward_xp(3)],
          deps=["sickle"], icon="silentgear:machete", optional=True),

    quest("katana", 0, 15, "&7Schmiede ein Katana",
          subtitle="Schwerer und stärker als ein Schwert.",
          description=[
              "&eBlaupause:&r drei Blaues Papier und ein Stock. Die Klinge braucht &edrei&r Material statt zwei.",
              "",
              "Das &6Katana&r ist schwerer und stärker als das Schwert. Wer es lieber schnell mag: Der &6Dolch&r (ein Material) schlägt sehr schnell und verkürzt die Schutzzeit des Ziels. Der &6Speer&r (ein Material) ist schwächer, reicht aber weiter.",
          ],
          tasks=[task_item("silentgear:katana", 1)],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["sword"], icon="silentgear:katana"),

    quest("shield", 0, 17, "&7Bau einen Schild",
          subtitle="Ein Schild, der so viel hält wie sein Material.",
          description=[
              "&eBlaupause:&r Blaues Papier, Eisenbarren, Blaues Papier oben, drei Stöcke in der Mitte, ein Blaues Papier unten. Die Schildplatte braucht &ezwei&r Material.",
              "",
              "Der Schild blockt wie der aus Vanilla, seine Haltbarkeit kommt aus dem Material. Repariert wird er wie jedes Silent-Gear-Teil mit einem Reparaturkit.",
          ],
          tasks=[task_item("silentgear:shield", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 4), reward_xp(3)],
          deps=["armor"], icon="silentgear:shield", optional=True),

    quest("crossbow", 5, 16, "&7Spann eine Armbrust",
          subtitle="Wie die der Plünderer, nur aus deinem Material.",
          description=[
              "&eBlaupause:&r vier Blaues Papier und drei Stöcke. Die Armbrustglieder brauchen &edrei&r Material, dazu ein Stiel und eine Sehne wie beim Bogen.",
              "",
              "Sie schießt wie eine Vanilla-Armbrust. Mit Sehnenfaser oder Flauschigem Strang als Sehne trifft sie härter.",
          ],
          tasks=[task_item("silentgear:crossbow", 1)],
          rewards=[reward_item("minecraft:arrow", 32), reward_xp(3)],
          deps=["bow"], icon="silentgear:crossbow", optional=True),

    quest("arrows", 5, 17, "&7Bau eigene Pfeile",
          subtitle="Pfeilspitzen aus jedem Material.",
          description=[
              "&eBlaupause:&r Blaues Papier, Stock und Feder übereinander. Die &6Pfeilspitzen&r brauchen &eein&r Material, dazu ein Stiel und eine &6Befiederung&r. Welche Teile genau, zeigt JEI.",
              "",
              "Die Pfeile passen in Bogen und Armbrust. Das Material der Spitze bestimmt den Schaden.",
          ],
          tasks=[task_item("silentgear:arrow", 1)],
          rewards=[reward_item("minecraft:feather", 16), reward_xp(3)],
          deps=["bow"], icon="silentgear:arrow", optional=True),

    quest("ring", 7.5, 16, "&eSchmiede einen Ring",
          subtitle="Schmuck mit den Eigenschaften des Metalls.",
          description=[
              "&eBlaupause:&r vier Blaues Papier und zwei Metallbarren. Mit der Ring-Blaupause und &ezwei&r Metallbarren entsteht ein &6Ring&r.",
              "",
              "Er kommt in einen &eRing-Slot&r (Curios) und trägt die Eigenschaften seines Metalls. Was ein Metall mitbringt, steht im &6Material Book&r. Armband und Halskette folgen demselben Prinzip.",
          ],
          tasks=[task_item("silentgear:ring", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 4), reward_xp(3)],
          deps=["armor"], icon="silentgear:ring", optional=True),

    quest("fishing_rod", 7.5, 17.2, "&7Bau eine Angel",
          subtitle="Rolle, Haken, Stiel, Sehne.",
          description=[
              "&eBlaupause:&r zwei Blaues Papier und drei Stöcke. &6Angelspule und Haken&r brauchen &ezwei&r Material, dazu ein Stiel und eine Sehne.",
              "",
              "Sie angelt wie die Vanilla-Angel, hält aber so lange wie ihr Material und lässt sich reparieren statt neu bauen.",
          ],
          tasks=[task_item("silentgear:fishing_rod", 1)],
          rewards=[reward_item("minecraft:cod", 8), reward_xp(3)],
          deps=["bow"], icon="silentgear:fishing_rod", optional=True),
]

images = [
    banner("silent_gear/title", "Silent Gear", 5, -4.2, height=1.8, kind="title", colour="stone"),
    banner("silent_gear/first_steps", "Erste Schritte", 2.5, -2.4, height=0.9, colour="stone"),
    banner("silent_gear/templates", "Vorlagen", 10.5, -2.4, height=0.9, colour="nature"),
    banner("silent_gear/parts", "Die ersten Teile", 3.5, 2.8, height=0.9, colour="brass"),
    banner("silent_gear/tools", "Werkzeuge", 5, 10.9, height=0.9, colour="brass"),
    banner("silent_gear/upgrades", "Upgrades", 2.5, 18, height=0.9, colour="magic"),
    banner("silent_gear/repair", "Pflege und Reparatur", 2.5, 22.6, height=0.9, colour="stone"),
    banner("silent_gear/tiers", "Materialstufen", 16, -2.4, height=0.9, colour="brass"),
    banner("silent_gear/later", "Ab Stufe 2", 18.5, 10, height=0.9, colour="fire"),
]

chapter(C, "Silent Gear", "silentgear:pickaxe", "storage", quests, shape="circle", order=6,
        subtitle=["Werkzeug aus Teilen, Materialstufen bis Tyrann-Stahl."], images=images)
