"""Hier geht's los: was Kronwerke ist, der erste Tag, der Obelisk, die Stufen, der Server und
der Weg in alle anderen Kapitel. Der Einstieg ins Questbuch."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "start_here"

quests = [
    # ---- Willkommen ---------------------------------------------------------
    quest("welcome", 0, 3, "&6Willkommen in den Kronwerken",
          subtitle="Eine Welt, viele Streamer, ein gemeinsames Ziel.",
          description=[
              "&6Kronwerke Season 2&r ist ein Tech- und Magie-Modpack für Streamer und ihre Communities. Rund dreißig Leute spielen sechs bis acht Wochen lang in derselben Welt, und nichts Wichtiges schaltet ein einzelner Spieler für sich allein frei.",
              "",
              "Die Season hat &6fünf Stufen&r. Jede öffnet sich für alle gleichzeitig, sobald der ganze Server am &6Obelisken&r am Spawn ein gemeinsames Ziel gefüllt hat. Dafür braucht es Technik und Magie zu gleichen Teilen, und am Anfang vor allem eins: sehr viel Stein.",
              "",
              "Dieses Buch führt dich durch alles, was gerade offen ist. Jedes Kapitel ist ein Mod oder ein Thema, jede Quest zeigt dir den nächsten Schritt. Dieses Kapitel ist dein Einstieg: oben &eder erste Tag&r, darunter &eder Obelisk&r, dann &edie Stufen&r und &eder Server&r, und ganz rechts der Überblick über alle anderen Kapitel.",
              "",
              "Viele Quests belohnen dich mit &6Kisten&r: &7Steinkiste&r, &fEisenkiste&r und &6Goldkiste&r, in dieser Reihenfolge besser. Ein Rechtsklick öffnet sie. Deine Belohnung holst du dir, indem du eine fertige Quest anklickst.",
              "",
              "&eTipp:&r Das Questbuch öffnest du jederzeit über das Buch oben links in deinem Inventar.",
          ],
          tasks=[task_checkmark("Los geht's")],
          rewards=[reward_item("minecraft:bread", 16), reward_table("s1_common")],
          icon="ftbquests:book", size=2.5, shape="hexagon"),

    # ---- Der erste Tag ------------------------------------------------------
    quest("d_table", 4.5, -8, "&6Werkbank",
          subtitle="Hau auf einen Baum. Wirklich.",
          description=[
              "Jede Runde Minecraft beginnt gleich: Such dir einen Baum und schlag mit der bloßen Hand auf den Stamm, bis er als Block herausfällt. Welche Holzart, ist egal. Dank Terralith und Biomes O' Plenty stehen hier viele neue Bäume herum, und ihr Holz funktioniert genauso.",
              "",
              "Aus einem Stamm werden vier &6Bretter&r, aus zwei Brettern vier &6Stöcke&r. Vier Bretter im Quadrat ergeben eine &6Werkbank&r, und damit hast du das 3x3-Feld für alle größeren Rezepte.",
              "",
              "&eTipp:&r Wenn du nicht weißt, wie etwas hergestellt wird: Fahr im Inventar mit der Maus über den Gegenstand und drück &eR&r. JEI zeigt dir dann das Rezept. Mehr dazu weiter unten bei den Server-Quests.",
          ],
          tasks=[task_item("minecraft:crafting_table", 1)],
          rewards=[reward_item("minecraft:apple", 6)],
          deps=["welcome"], icon="minecraft:crafting_table"),

    quest("d_tools", 6.5, -8, "&6Steinwerkzeug",
          subtitle="Holz reicht genau für eine Spitzhacke.",
          description=[
              "Bau dir eine &6Holzspitzhacke&r und grab dich ein paar Blöcke in einen Hang. Stein wird beim Abbauen zu &6Bruchstein&r, und aus Bruchstein machst du dir &6Steinspitzhacke&r, &6Steinaxt&r, &6Steinschaufel&r und ein &6Steinschwert&r.",
              "",
              "Wirf keinen Bruchstein weg! Der Obelisk braucht in Stufe 1 davon &e20 000 Stück&r vom ganzen Server. Alles, was du ohnehin abbaust, ist ein Beitrag.",
              "",
              "Besseres Werkzeug kommt bald: Eisen gleich im Anschluss, und das Kapitel &6Silent Gear&r zeigt dir Werkzeug aus Einzelteilen, das du nach deinen Wünschen zusammenbaust.",
          ],
          tasks=[task_item("minecraft:stone_pickaxe", 1)],
          rewards=[reward_item("minecraft:coal", 8)],
          deps=["d_table"], icon="minecraft:stone_pickaxe"),

    quest("d_food", 8.5, -8, "&6Lagerfeuer",
          subtitle="Warmes Essen, ganz ohne Brennstoff.",
          description=[
              "Hunger kommt schneller, als man denkt. Kühe, Schweine, Schafe und Hühner laufen fast überall herum. Rohes Fleisch macht kaum satt, gebratenes schon.",
              "",
              "Ein &6Lagerfeuer&r (Stöcke, Kohle oder Holzkohle, Holzstämme) brät bis zu vier Stücke auf einmal und braucht dabei nie Brennstoff. Später dient es auch als Hitzequelle unter dem &6Kochtopf&r von Farmer's Delight.",
              "",
              "Die Werte der Nahrung siehst du dank &6AppleSkin&r direkt im Tooltip und an deiner Hungerleiste. Wie du richtig kochst, zeigt dir das Kapitel &6Essen und Landwirtschaft&r.",
          ],
          tasks=[task_item("minecraft:campfire", 1)],
          rewards=[reward_item("minecraft:cooked_beef", 8)],
          deps=["d_tools"], icon="minecraft:campfire"),

    quest("d_shelter", 10.5, -8, "&6Ein Dach über dem Kopf",
          subtitle="Die erste Nacht ist die gefährlichste.",
          description=[
              "Sobald es dunkel wird, kommen die Monster. Neben den bekannten Zombies und Skeletten ziehen hier auch die Kreaturen aus &6Born in Chaos&r durch die Nacht, und einige davon sind unangenehm zäh.",
              "",
              "Bau dir etwas mit vier Wänden und einer Tür. Es muss nicht hübsch sein, ein Loch im Berg reicht für die erste Nacht. Monster erscheinen nur bei völliger Dunkelheit, also stell genug &6Fackeln&r auf, drinnen und rund ums Haus.",
              "",
              "Eine &6Truhe&r gehört dazu, damit du nicht alles mit dir herumtragen musst. Sobald du weißt, wo du bleiben willst, sichere die Stelle mit FTB Chunks (siehe &eClaims&r weiter unten).",
          ],
          tasks=[task_item("minecraft:torch", 16), task_item("minecraft:chest", 1)],
          rewards=[reward_table("s1_common")],
          deps=["d_food"], icon="minecraft:torch"),

    quest("d_bed", 10.5, -6.5, "&6Ein Bett",
          subtitle="Schlafen setzt deinen Spawnpunkt.",
          description=[
              "Drei Wolle von Schafen und drei Bretter ergeben ein &6Bett&r. Wer darin schläft, überspringt die Nacht, sofern genug Spieler auf dem Server mitschlafen, und setzt vor allem seinen &eSpawnpunkt&r: Nach dem Tod wachst du hier auf und nicht irgendwo am Weltspawn.",
              "",
              "Für unterwegs gibt es den Schlafsack aus Comforts, der deinen Spawnpunkt nicht verschiebt. Mehr dazu unten bei den Server-Quests.",
              "",
              "&cAchtung:&r In der Minendimension explodieren Betten, genau wie im Nether.",
          ],
          tasks=[task_checkmark("Mein Bett steht")],
          rewards=[reward_xp(3)],
          deps=["d_shelter"], icon="minecraft:red_bed", optional=True),

    quest("d_stone", 12.5, -8, "&7Der erste Stein",
          subtitle="Jeder Stapel zählt.",
          description=[
              "Das erste Gemeinschaftsziel will vor allem eins: &6Bruchstein&r, und zwar von allen. Jede Sorte zählt, auch Bruchtiefenschiefer und bemooster Bruchstein.",
              "",
              "Sammle deinen Bruchstein, statt ihn zu entsorgen, und bring ihn zum &6Obelisken&r am Spawn. Wie das Abgeben genau funktioniert, steht im Abschnitt &eDer Obelisk&r gleich darunter.",
              "",
              "&eTipp:&r Mit &6Ultimine&r baust du ganze Reihen Stein auf einmal ab, und in der Minendimension (Kapitel &6Erkundung&r) darfst du graben, so viel du willst, ohne die Landschaft zu zerlöchern.",
          ],
          tasks=[task_item("minecraft:cobblestone", 64)],
          rewards=[reward_xp(3)],
          deps=["d_shelter"], icon="minecraft:cobblestone"),

    quest("d_iron", 14.5, -8, "&6Eisen",
          subtitle="Das Metall, das du überall brauchst.",
          description=[
              "Eisenerz findest du in Höhlen und in den Bergen. Mit einer Steinspitzhacke abbauen, das &6Roheisen&r im &6Ofen&r schmelzen, fertig ist der &6Eisenbarren&r.",
              "",
              "Eisen steckt in fast allem, was jetzt kommt: Eimer, Werkzeug, Rüstung, der Kochtopf, die Teile für Create und die ersten Zauber-Geräte. Ein kleiner Vorrat erspart dir später viele Wege.",
              "",
              "&eTipp:&r Eisennuggets sind mit Andesit die Zutat für &6Andesitlegierung&r, das Material der Technik-Säule am Obelisken.",
          ],
          tasks=[task_item("minecraft:iron_ingot", 16)],
          rewards=[reward_item("minecraft:coal", 16)],
          deps=["d_stone"], icon="minecraft:iron_ingot"),

    quest("d_pick", 16.5, -8, "&6Eisenspitzhacke",
          subtitle="Jetzt geht es an die Diamanten.",
          description=[
              "Mit einer &6Eisenspitzhacke&r baust du Gold, Redstone, Lapislazuli und Diamanten ab. Diamanten brauchst du bald: Zwei davon stecken in der &6Verzauberten Spitzhacke&r, dem Schlüssel zur Minendimension.",
              "",
              "Obsidian geht erst mit einer Diamantspitzhacke. Den brauchst du für eigene Wegsteine und den Zaubertisch.",
          ],
          tasks=[task_item("minecraft:iron_pickaxe", 1)],
          rewards=[reward_table("s1_common")],
          deps=["d_iron"], icon="minecraft:iron_pickaxe"),

    quest("d_done", 18.5, -8, "&6Der erste Tag",
          subtitle="Geschafft. Jetzt wird es interessant.",
          description=[
              "Du hast Werkzeug, Essen, ein Dach über dem Kopf, den ersten Bruchstein und Eisen. Das ist mehr, als die meisten nach dem ersten Abend haben.",
              "",
              "Ab hier gibt es keinen festen Pfad mehr. Lies dir die Abschnitte zum &eObelisken&r und zu den &eStufen&r durch, damit du weißt, worauf der Server hinarbeitet, und schau dann rechts bei &eDeine Wege&r, welches Kapitel dich am meisten reizt.",
          ],
          tasks=[task_checkmark("Geschafft")],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["d_pick"], icon="minecraft:clock", size=1.5, shape="gear"),

    # ---- Der Obelisk ---------------------------------------------------------
    quest("o_obelisk", 4.5, 0, "&6Der Obelisk",
          subtitle="Das Herz des Servers.",
          description=[
              "Am Spawn steht der &6Obelisk&r. Er sammelt alles, was der Server für die nächste Stufe braucht, und zwar von allen Spielern gemeinsam.",
              "",
              "Jedes Ziel hat mehrere &6Säulen&r, zum Beispiel Stein, Technik und Magie. Eine Stufe öffnet sich erst, wenn &ealle&r Säulen gefüllt sind. Ein Server, der nur Maschinen baut oder nur zaubert, kommt also nicht weiter.",
              "",
              "Oben auf dem Bildschirm zeigt dir eine &eBossleiste&r das aktive Ziel und wie weit es schon ist. Alles, was du abgibst, wird dir persönlich gutgeschrieben.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(5)],
          deps=["welcome"], icon="minecraft:lodestone", size=2, shape="diamond"),

    quest("o_handin", 7.5, -1, "&eAbgeben",
          subtitle="Ein Rechtsklick genügt.",
          description=[
              "Halte einen Stapel in der Hand und mach einen &eRechtsklick&r auf den Obelisken. Wenn das aktuelle Ziel diesen Gegenstand nimmt, gibst du damit den ganzen Stapel ab.",
              "",
              "&eSchleichen und Rechtsklick&r gibt alles aus deinem Inventar ab, was das aktuelle Ziel gebrauchen kann. Was das Ziel nicht braucht, bleibt bei dir. Ideal, wenn du mit vollen Taschen aus der Mine kommst.",
              "",
              "&eTipp:&r Ein Rucksack aus Sophisticated Backpacks voller Bruchstein, einmal schleichen und klicken, und schon ist alles drin. Achte nur darauf, dass nichts in deinem Inventar ist, das du lieber behalten willst.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["o_obelisk"], icon="minecraft:cobblestone"),

    quest("o_feeder", 7.5, 1, "&6Zubringer",
          subtitle="Truhe hinstellen, Fabrik anschließen.",
          description=[
              "Eine &6Truhe&r oder ein &6Fass&r, das du im Umkreis von &e3 Blöcken&r um den Obelisken aufstellst, wird dein &6Zubringer&r. Jeder Spieler kann höchstens &ezwei&r davon haben.",
              "",
              "Alle &e2 Sekunden&r nimmt das Ziel aus deinem Zubringer heraus, was es gebrauchen kann, und schreibt es dir gut. Alles andere bleibt liegen.",
              "",
              "Genau dafür ist er da: Deine Fabriken können direkt einzahlen. Leite Bruchstein, Andesitlegierung oder Quelljuwelen per Trichter oder Förderband in den Zubringer, und dein Beitrag wächst, während du etwas anderes machst.",
              "",
              "&cAchtung:&r Gezählt wird für den, der die Truhe aufgestellt hat. Leg nichts hinein, das du nicht abgeben willst.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["o_obelisk"], icon="minecraft:barrel"),

    quest("o_commands", 9.5, 0, "&6/kw",
          subtitle="Alles Wichtige per Befehl.",
          description=[
              "&e/kw goals&r zeigt alle Ziele und wie weit jede Säule ist.",
              "&e/kw top&r zeigt, wer bisher am meisten beigetragen hat.",
              "&e/kw deposit&r gibt den Gegenstand in deiner Hand ab.",
              "&e/kw deposit all&r gibt alles ab, was das aktuelle Ziel nimmt.",
              "",
              "Die Befehle sind der Ausweichweg, falls der Rechtsklick einmal nicht klappt. Die Bossleiste oben zeigt dir das aktive Ziel auch ohne Befehl.",
          ],
          tasks=[task_checkmark("Ausprobiert")],
          rewards=[reward_xp(3)],
          deps=["o_handin", "o_feeder"], icon="minecraft:command_block"),

    quest("o_stone", 11.5, -1.5, "&7Säule: Stein",
          subtitle="20 000 Bruchstein.",
          description=[
              "Die Stein-Säule ist die Säule für alle. Jeder kann ab der ersten Minute mithelfen, ganz ohne Maschinen und Zauber.",
              "",
              "Es zählt jede Sorte &6Bruchstein&r: normaler, bemooster und Bruchtiefenschiefer. Mit Ultimine und in der Minendimension geht es am schnellsten.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["o_commands"], icon="minecraft:cobblestone"),

    quest("o_tech", 11.5, 0, "&6Säule: Technik",
          subtitle="1 500 Andesitlegierung und 12 Steinwerk-Getriebe.",
          description=[
              "Die Technik-Säule will &6Andesitlegierung&r aus Create. Von Hand stellst du sie aus zwei &6Andesit&r und zwei &6Eisennuggets&r (oder Zinknuggets) her, jeweils diagonal.",
              "",
              img(item_texture("create:andesite_alloy"), 32, 32),
              "",
              "1 500 Stück von Hand wären mühsam: die Werkbank gibt pro Rezept nur eine Legierung. Der &6Mechanische Mixer&r macht aus einem Andesit und einem Nugget gleich &ezwei&r, braucht also nur ein Viertel des Materials. Wer eine Andesitquelle und eine Nuggetquelle aufbaut und den Mixer ranlässt, schafft ein paar Hundert in der Stunde und schickt sie per Zubringer direkt zum Obelisken.",
              "",
              "Dazu kommen &e12 Steinwerk-Getriebe&r, der Meilenstein dieser Säule. Mehr dazu in der Quest daneben.",
              "",
              "Wie das geht, zeigt dir das Kapitel &6Create&r.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["o_commands"], icon="create:andesite_alloy"),

    quest("o_magic", 11.5, 1.5, "&dSäule: Magie",
          subtitle="800 Quelljuwelen und 12 Quellschlusssteine.",
          description=[
              "Die Magie-Säule will &6Quelljuwelen&r (Source Gems) aus Ars Nouveau. Die gibt es nur auf einem Weg: in der &aImbuement-Kammer&r, die Amethyst mit &dSource&r auflädt.",
              "",
              img(item_texture("ars_nouveau:source_gem"), 32, 32),
              "",
              "Dafür brauchst du Quellgläser und etwas, das Source erzeugt. Eine kleine Anlage liefert ein paar Dutzend Juwelen in der Stunde, und auch die kannst du per Zubringer einzahlen. &e800&r Juwelen will der Obelisk, dazu &e12 Quellschlusssteine&r als Meilenstein der Säule.",
              "",
              "Wie das geht, zeigt dir das Kapitel &6Ars Nouveau&r.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["o_commands"], icon="ars_nouveau:source_gem"),

    quest("m_gearbox", 13.5, -1.75, "&6Steinwerk-Getriebe",
          subtitle="Der Meilenstein der Technik-Säule.",
          description=[
              "Neben Stein, Legierung und Juwelen in großen Mengen will jedes Stufenziel ein paar &6Meilensteine&r: besondere Gegenstände, die es nur für den Obelisken gibt und in denen Technik und Magie zusammenkommen. In Stufe 1 ist das für die Technik-Säule das &6Steinwerk-Getriebe&r.",
              "",
              img("kronwerke:textures/item/stone_gearbox.png", 32, 32),
              "",
              "&eRezept an der Werkbank:&r",
              "Oben: &6Andesitgehäuse&r, &6Großes Zahnrad&r, &6Andesitgehäuse&r.",
              "Mitte: &6Mechanische Presse&r, &6Infused Iron&r, &6Mahlstein&r.",
              "Unten: &6Andesitgehäuse&r, &6Wasserrad&r, &6Andesitgehäuse&r.",
              "",
              "Alles davon kommt aus dem Kapitel &6Create&r, bis auf das &6Infused Iron&r: Das entsteht am &aNatural Altar&r von Nature's Aura, wenn du einen Eisenbarren auf den Altar legst und genug Aura in der Umgebung ist. Wer keinen Altar hat, fragt einen Magier.",
              "",
              "&eWie viele:&r Der Obelisk will &e12 Steinwerk-Getriebe&r. Diese Zahl ist fest, sie wächst nicht mit der Spielerzahl. Dafür zählt ein einziges Getriebe auf der Fortschrittsleiste so viel wie &e125 Andesitlegierungen&r, die zwölf zusammen tragen etwa die Hälfte der Technik-Säule.",
              "",
              "&cWichtig:&r Meilensteine nimmt der Obelisk nur an, solange ihr Stufenziel aktiv ist. Das Ziel von Stufe 1 ist es vom ersten Tag an. In Stufe 2 folgen &6Messingherz&r und &6Runenkern&r, von denen der Obelisk dann je &e8&r will.",
          ],
          tasks=[task_item("kronwerke:stone_gearbox", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["o_tech"], icon="kronwerke:stone_gearbox", size=1.25, shape="gear"),

    quest("m_keystone", 13.5, 1.75, "&dQuellschlussstein",
          subtitle="Der Meilenstein der Magie-Säule.",
          description=[
              "Der Meilenstein der Magie-Säule in Stufe 1 ist der &dQuellschlussstein&r. In ihm stecken alle drei Magie-Mods der ersten Stufe: Quelle aus Ars Nouveau, Mana aus Botania und Gold aus Nature's Aura, zusammengehalten von einer Andesitlegierung aus Create.",
              "",
              img("kronwerke:textures/item/source_keystone.png", 32, 32),
              "",
              "&eRezept an der Werkbank:&r",
              "Oben: &6Quelljuwelblock&r, &6Quellglas&r, &6Quelljuwelblock&r.",
              "Mitte: &bManadiamant&r, &6Andesitlegierung&r, &bManadiamant&r.",
              "Unten: &6Quelljuwelblock&r, &6Gold Leaf&r, &6Quelljuwelblock&r.",
              "",
              "Die &bManadiamanten&r infundierst du im Manabecken von Botania, je &d10 000 Mana&r. Das &6Gold Leaf&r wächst an einem &aBrilliant Tree&r von Nature's Aura: Leg etwas Brilliant Fiber in die Krone eines Baums, und mit der Zeit lassen seine Blätter beim Abbauen Gold Leaf fallen.",
              "",
              "&eWie viele:&r Der Obelisk will &e12 Quellschlusssteine&r, fest, egal wie viele Spieler dabei sind. Einer zählt auf der Leiste so viel wie gut &e60 Quelljuwelen&r, die zwölf zusammen tragen fast die Hälfte der Magie-Säule.",
              "",
              "&cWichtig:&r Wie alle Meilensteine geht er nur in den Obelisken, solange sein Stufenziel aktiv ist. Ab Stufe 2 will der Obelisk stattdessen &e8 Messingherzen&r und &e8 Runenkerne&r.",
          ],
          tasks=[task_item("kronwerke:source_keystone", 1)],
          rewards=[reward_table("s1_uncommon"), reward_xp(5)],
          deps=["o_magic"], icon="kronwerke:source_keystone", size=1.25, shape="gear"),

    quest("o_scale", 13.5, 0, "&6Mengen, die mitwachsen",
          subtitle="Mehr Spieler, größere Ziele.",
          description=[
              "Die Zahlen oben (20 000 Bruchstein, 1 500 Andesitlegierung, 800 Quelljuwelen) gelten für &e30 aktive Spieler&r. Sind mehr oder weniger Leute regelmäßig dabei, wachsen oder schrumpfen die Mengen mit.",
              "",
              "&eAusnahme Meilensteine:&r Die 12 Steinwerk-Getriebe und 12 Quellschlusssteine bleiben immer gleich, egal wie viele mitspielen.",
              "",
              "Die genaue Menge wird festgelegt, wenn eine Stufe öffnet, und bleibt dann für diese Stufe gleich. Was aktuell gilt, zeigen dir &e/kw goals&r und die Statusseite auf der Website.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["o_stone", "o_tech", "o_magic"], icon="minecraft:comparator"),

    quest("o_event", 15.5, 0, "&c98 Prozent",
          subtitle="Das letzte Stück machen alle zusammen.",
          description=[
              "Bei &e98 Prozent&r hört der Obelisk auf, Gegenstände anzunehmen. Dann wird ein Termin festgelegt, alle Streamer gehen gemeinsam live, und die letzten Gegenstände wandern zusammen hinein.",
              "",
              "In diesem Moment öffnet sich die nächste Stufe &efür alle gleichzeitig&r. Niemand ist früher dran, niemand verpasst etwas, weil er gerade offline war.",
              "",
              "&eTipp:&r Halte dir für den Abend einen kleinen Vorrat zurück, damit du beim Finale selbst etwas einwerfen kannst. Den Termin erfährst du im Discord.",
          ],
          tasks=[task_checkmark("Ich bin dabei")],
          rewards=[reward_table("s1_common"), reward_xp(5)],
          deps=["o_scale"], icon="minecraft:beacon", size=1.75, shape="gear"),

    # ---- Stufen und Sperren -------------------------------------------------
    quest("s_stages", 4.5, 6.5, "&6Fünf Stufen",
          subtitle="Eine nach der anderen, für alle zugleich.",
          description=[
              "Die Season hat fünf Stufen: &7Steinwerk&r, &6Messingwerk&r, &fStahlwerk&r, &dSternwerk&r und &cChaoswerk&r. Jede öffnet sich über ein Gemeinschaftsziel am Obelisken.",
              "",
              "Jede Stufe kann ungefähr doppelt so viel wie die davor: mehr Erz, mehr Energie, mehr Mana, mehr Lager, schnellere Wege. Nichts wird aus dem Pack entfernt, manches kommt nur später. Am Ende ist jeder Mod erreichbar.",
              "",
              "Vanilla ist nicht gesperrt, mit zwei Ausnahmen: der &cNether&r (Stufe 2) und das &dEnde&r (Stufe 4). Beide öffnen mit einem Event.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(5)],
          deps=["o_obelisk"], icon="minecraft:stone_bricks", size=1.75, shape="hexagon"),

    quest("s_1", 7, 5, "&7Stufe 1: Steinwerk",
          subtitle="Holz, Stein, Wasserräder, die ersten Zauber.",
          description=[
              "Hier bist du gerade. Offen sind die Oberwelt und die Minendimension, Create bis zur Andesit-Stufe (Wasserrad, Mahlstein, Presse, Mixer, Förderbänder, Lüfter), Ars Nouveau mit den Glyphen für Anfänger, Botania bis zum Manabecken, dazu Farmer's Delight, Aquaculture, Silent Gear bis Eisen, Rucksäcke aus Leder, Schubladen aus Eiche, Wegsteine und Apotheosis.",
              "",
              "Das Ziel, das &6Fundament des Kronwerks&r, will Bruchstein, Andesitlegierung und Quelljuwelen.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["s_stages"], icon="minecraft:cobblestone"),

    quest("s_2", 9, 5, "&6Stufe 2: Messingwerk",
          subtitle="Messing, der Nether, die ersten Maschinen.",
          description=[
              "Die zweite Stufe beginnt mit einem Event: Das &cNetherportal am Spawn&r wird live auf Stream entzündet.",
              "",
              "Dann kommen Messing und der Lohenbrenner für Create, Züge und Kontraptionen, die Grundlagen von Mekanism und Immersive Engineering, der Runenaltar und Terrastahl in Botania, die Lehrlings-Glyphen in Ars Nouveau, die ersten Geister in Occultism und Hexerei.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["s_1"], icon="minecraft:netherrack"),

    quest("s_3", 11, 5, "&fStufe 3: Stahlwerk",
          subtitle="Stahl, Erzvervielfachung, Rituale.",
          description=[
              "Stahl in großen Mengen, Erzverdreifachung, Lagernetzwerke mit Applied Energistics, Maschinen, die rund um die Uhr laufen, und Rituale mit Folgen.",
              "",
              "Tech und Magie halten sich hier die Waage: Eine reine Magie-Basis vervielfacht Erz genauso gut wie eine reine Tech-Basis.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["s_2"], icon="minecraft:iron_block"),

    quest("s_4", 13, 5, "&dStufe 4: Sternwerk",
          subtitle="Das Ende, die Sterne, der Drache.",
          description=[
              "Das &dEnde&r öffnet sich mit einem Event, und der Enderdrache ist der erste Boss, den der Server gemeinsam bekämpft.",
              "",
              "Danach geht es um die Sterne und um Maschinen, die Energie fressen: Fusion, die ersten Schritte von Draconic Evolution und der Kampf gegen die Gaia-Wächterin in Botania.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["s_3"], icon="minecraft:ender_eye"),

    quest("s_5", 15, 5, "&cStufe 5: Chaoswerk",
          subtitle="Die letzten Maschinen und der letzte Kampf.",
          description=[
              "Die letzte Stufe öffnet alles, was noch fehlt. Ihr Ziel ist kein reines Sammelziel: Der Obelisk will das, was den Endkampf möglich macht.",
              "",
              "Das Finale ist der Kampf gegen den &cChaos Guardian&r, live auf allen Streams. Wer ihn besiegt, beendet die Season.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(2)],
          deps=["s_4"], icon="minecraft:dragon_head"),

    quest("s_locked", 7, 8, "&cGesperrte Gegenstände",
          subtitle="Einstecken geht, benutzen noch nicht.",
          description=[
              "Gegenstände aus einer späteren Stufe kannst du &eaufheben und mit dir tragen&r, aber nicht in der Hand halten, anziehen oder benutzen.",
              "",
              "Der Tooltip sagt dir, zu welcher Stufe ein Gegenstand gehört, etwa &7Gesperrt bis Stufe 2 (Messingwerk)&r. Beim Aufheben erscheint dieselbe Nachricht über der Hotbar. Ist dein Inventar voll, bleibt der Gegenstand vor dir liegen.",
              "",
              "Findest du so etwas in einer Truhe, heb es auf. Sobald die Stufe offen ist, kannst du es sofort benutzen.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["s_stages"], icon="minecraft:barrier"),

    quest("s_craft", 9, 8, "&cHerstellen gesperrt",
          subtitle="JEI zeigt alles, die Werkbank nicht.",
          description=[
              "Einen gesperrten Gegenstand kannst du nicht herstellen. Die Werkbank oder Maschine verweigert das Rezept mit dem Hinweis &7Das kannst du noch nicht herstellen&r.",
              "",
              "JEI zeigt dir trotzdem alle Rezepte, auch die der späteren Stufen. Nutz das zum Vorausplanen: Zink für Messing kannst du zum Beispiel schon jetzt abbauen und einlagern, damit dein Messingwerk am ersten Abend von Stufe 2 läuft.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["s_locked"], icon="minecraft:crafting_table"),

    quest("s_latejoin", 11, 8, "&aSpäter dazugekommen?",
          subtitle="Niemand fängt ganz von vorne an.",
          description=[
              "Wer erst in Woche drei oder vier einsteigt, bekommt die &6Starterpakete&r aller Stufen, die schon offen sind. Zum Beispiel gibt es mit Stufe 2 Messingbarren, einen Lohenbrenner, ein Quellglas und Manaperlen.",
              "",
              "So kannst du direkt bei den anderen mitmachen, statt wochenlang aufzuholen. Und wer Hilfe braucht, fragt einfach im Chat oder im Voice-Chat, hier hilft man sich.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["s_craft"], icon="minecraft:chest"),

    quest("s_ties", 13, 8, "&dTechnik und Magie",
          subtitle="Keine Seite kommt allein weiter.",
          description=[
              "Nicht nur die Ziele verlangen beides, auch einige Rezepte binden Technik und Magie aneinander. Ab Stufe 2 zum Beispiel:",
              "",
              "Der &6Lohenbrenner&r aus Create braucht zwei &6Quelljuwelen&r. Messing braucht also einen Magier.",
              "Die &6Terrestrische Agglomerationsplatte&r aus Botania braucht zwei &6Messinggehäuse&r, der &6Runenaltar&r einen Messingbarren, und &6Manaperlen&r gibt es nur aus einem Becken mit einem Messinggehäuse darunter. Botania braucht also einen Ingenieur.",
              "Die &6Metallurgische Infusionsmaschine&r aus Mekanism braucht &6Manastahl&r, und der erste Manastahl kommt aus einem Ritual von Nature's Aura.",
              "Der &6Einfache Steuerschaltkreis&r von Mekanism entsteht aus einer &6Elektronenröhre&r von Create.",
              "",
              "Schon in Stufe 1 verbinden die beiden &6Meilensteine&r des Obelisken alle Seiten: das Steinwerk-Getriebe braucht Infused Iron vom Natural Altar, der Quellschlussstein Manadiamanten und Andesitlegierung.",
              "",
              "Die betroffenen Quests erklären das geänderte Rezept jeweils genau. Sprich dich mit den anderen ab, wer was übernimmt.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_table("s1_common")],
          deps=["s_latejoin"], icon="minecraft:amethyst_shard"),

    # ---- Auf dem Server -----------------------------------------------------
    quest("v_discord", 4.5, 13, "&9Der Discord",
          subtitle="Hier wird die Season organisiert.",
          description=[
              "Auf den Server kommst du über den &9Discord&r: Captcha lösen, dann gibt dir ein Streamer einen Platz auf der Whitelist.",
              "",
              "Wer schon in &6Season 1&r dabei war, nutzt im Discord &e/link&r mit seinem Minecraft-Namen und bekommt zwei eigene Plätze für Freunde.",
              "",
              "&cWichtig:&r Wer den Discord verlässt, fliegt auch von der Whitelist.",
              "",
              "Events, Termine für die Stufen-Finale und Neuigkeiten zum Gemeinschaftsziel stehen dort immer zuerst.",
          ],
          tasks=[task_checkmark("Bin im Discord")],
          rewards=[reward_xp(3)],
          deps=["welcome"], icon="minecraft:bell", size=1.5),

    quest("v_website", 7, 12, "&6Die Website",
          subtitle="kronwerke.elchi.dev",
          description=[
              "Auf &ekronwerke.elchi.dev&r findest du alles zum Nachlesen: die Stufen im Detail, die komplette Modliste, eine Installationsanleitung, die häufigsten Fragen und eine &eLive-Statusseite&r mit den Gemeinschaftszielen.",
              "",
              "Die Statusseite zeigt dir auch dann, wie weit der Obelisk ist, wenn du gerade nicht online bist.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(3)],
          deps=["v_discord"], icon="minecraft:map"),

    quest("v_origin", 7, 14, "&6Dein Ursprung",
          subtitle="Wer du bist, ändert, wie du spielst.",
          description=[
              "Beim ersten Betreten hast du einen &6Ursprung&r gewählt (Neo Origins). Jeder hat Stärken und Schwächen, und manche machen bestimmte Teile des Packs leichter oder schwerer.",
              "",
              "Wenn du noch unsicher bist, spiel ein paar Abende damit. Hast du wirklich etwas erwischt, das gar nicht passt, sprich die Streamer oder das Team an.",
          ],
          tasks=[task_checkmark("Mein Ursprung steht")],
          rewards=[reward_xp(3)],
          deps=["v_discord"], icon="minecraft:player_head"),

    quest("v_claim", 9, 12, "&6Claims",
          subtitle="Schütze, was du baust.",
          description=[
              "Öffne mit &eM&r die Karte von &6FTB Chunks&r. Über den Knopf für &eClaims&r siehst du die Chunks um dich herum. Mit gedrückter linker Maustaste ziehst du über die Chunks, die du beanspruchen willst, mit der rechten gibst du sie wieder frei.",
              "",
              "In deinen Chunks kann niemand außerhalb deines Teams Blöcke abbauen oder Truhen öffnen. Jeder hat nur eine begrenzte Zahl an Claims, also sichere deine Basis und nicht das ganze Tal.",
          ],
          tasks=[task_checkmark("Meine Basis ist gesichert")],
          rewards=[reward_table("s1_common")],
          deps=["v_website"], icon="minecraft:filled_map"),

    quest("v_team", 11, 12, "&6Teams",
          subtitle="Gemeinsam bauen, gemeinsam claimen.",
          description=[
              "Mit &6FTB Teams&r gründest du ein Team: &e/ftbteams party create <Name>&r, Mitspieler lädst du mit &e/ftbteams party invite <Spieler>&r ein.",
              "",
              "Teammitglieder teilen sich die Claims und können in eurer Basis alles benutzen. &cAchtung:&r Auch der &eQuestfortschritt&r gilt fürs ganze Team. Was einer erledigt, ist für alle erledigt, und die Belohnung holt sich jeder selbst ab.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["v_claim"], icon="minecraft:white_banner"),

    quest("v_voice", 9, 14, "&6Sprachchat",
          subtitle="Wer nah ist, hört dich.",
          description=[
              "&6Simple Voice Chat&r ist im Pack. Spieler in deiner Nähe hören dich, weiter entfernte nicht. Mit &eV&r öffnest du die Einstellungen: Mikrofon wählen, Lautstärke einstellen und auf Wunsch Push-to-Talk einschalten.",
              "",
              "Im selben Menü kannst du Gruppen anlegen, damit dich dein Team auch über große Entfernung hört.",
          ],
          tasks=[task_checkmark("Eingerichtet")],
          rewards=[reward_xp(3)],
          deps=["v_origin"], icon="minecraft:note_block", optional=True),

    quest("v_death", 11, 14, "&cWenn du stirbst",
          subtitle="Deine Sachen warten, wo du gefallen bist.",
          description=[
              "Wenn du stirbst, bleibt dein &6Körper&r an Ort und Stelle liegen, mit allem, was du dabeihattest. Lauf zurück, öffne ihn und nimm dir deine Sachen.",
              "",
              "Die Minendimension, die tiefen Höhlen und manche Bauwerke sind gefährlich. Merk dir vorher die Koordinaten (&eF3&r) oder setz dir einen Wegpunkt auf der Karte.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("minecraft:golden_apple", 1)],
          deps=["v_voice"], icon="minecraft:skeleton_skull"),

    quest("v_ultimine", 13, 12, "&6Ultimine",
          subtitle="Eine ganze Ader auf einmal.",
          description=[
              "Halte die Ultimine-Taste gedrückt (standardmäßig &e`&r, die Taste links neben der 1), während du einen Block abbaust, und alle passenden Blöcke daneben gehen mit: ganze Erzadern, ganze Bäume, eine Reihe Stein.",
              "",
              "Das kostet Hunger, also nimm Essen mit. Für die Stein-Säule am Obelisken ist Ultimine dein bester Freund.",
          ],
          tasks=[task_checkmark("Ausprobiert")],
          rewards=[reward_item("minecraft:cooked_beef", 8)],
          deps=["v_team"], icon="minecraft:diamond_pickaxe"),

    quest("v_jei", 13, 14, "&6JEI und Jade",
          subtitle="Jedes Rezept, jeder Block.",
          description=[
              "&6JEI&r ist die Liste rechts in deinem Inventar. Fahr mit der Maus über einen Gegenstand und drück &eR&r für seine Rezepte oder &eU&r für alles, wofür er gebraucht wird. Mit &eA&r setzt du ein Lesezeichen.",
              "",
              "&6Jade&r zeigt oben am Bildschirm, auf welchen Block du gerade schaust und aus welchem Mod er stammt.",
              "",
              "Rezepte späterer Stufen tauchen in JEI auch auf. Herstellen kannst du sie erst, wenn die Stufe offen ist.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["v_death"], icon="minecraft:knowledge_book"),

    quest("v_ponder", 15, 14, "&6Ponder",
          subtitle="Create erklärt sich selbst.",
          description=[
              "Fahr im Inventar oder in JEI mit der Maus über einen Block aus Create und halte &eW&r gedrückt. Dann öffnet sich eine kleine animierte Szene, die zeigt, wie der Block funktioniert und womit er zusammenspielt.",
              "",
              "Die &6Ingenieursbrille&r zeigt dir später in der Welt Drehzahl und Belastung deiner Maschinen an.",
          ],
          tasks=[task_checkmark("Ausprobiert")],
          rewards=[reward_xp(3)],
          deps=["v_jei"], icon="create:wrench", optional=True),

    quest("v_sleep", 15, 12, "&6Schlafsack und Hängematte",
          subtitle="Unterwegs schlafen, ohne den Spawnpunkt zu verlieren.",
          description=[
              "Mit einem &6Schlafsack&r aus Comforts überspringst du unterwegs die Nacht, ohne deinen Spawnpunkt zu verschieben. Die &6Hängematte&r macht dasselbe für den Tag.",
              "",
              "Den Schlafsack machst du aus drei Wolle übereinander, die Hängematte aus Wolle, Faden und Stöcken. Jede Farbe geht.",
          ],
          tasks=[task_checkmark("Habe einen")],
          rewards=[reward_item("minecraft:cooked_beef", 8)],
          deps=["v_ultimine"], icon="comforts:sleeping_bag_red", optional=True),

    # ---- Deine Wege ---------------------------------------------------------
    quest("p_hub", 21, 2.5, "&6Wie geht es weiter?",
          subtitle="Sieben Kapitel für die erste Stufe.",
          description=[
              "Für Stufe 1 gibt es sieben Kapitel. Links im Buch findest du sie nach Gruppen sortiert: &6Technik&r, &dMagie&r, &aWelt und Erkundung&r sowie &6Lager und Werkzeug&r.",
              "",
              "Die Säulen am Obelisken brauchen &eTechnik und Magie&r. Wenn du dich nicht entscheiden kannst: Frag in die Runde, was gerade fehlt.",
              "",
              "Die Kapitel der späteren Stufen erscheinen, sobald die Stufe offen ist.",
          ],
          tasks=[task_checkmark("Zeig her")],
          rewards=[reward_xp(3)],
          deps=["d_done", "o_event"], icon="minecraft:compass", size=1.75, shape="hexagon"),

    quest("p_create", 24.5, -3.5, "&6Create",
          subtitle="Drehung, Förderbänder und die ersten Maschinen.",
          description=[
              "Create baut Maschinen aus Drehung: Ein &6Wasserrad&r treibt Wellen und Zahnräder, die treiben &6Mahlstein&r, &6Mechanische Presse&r und &6Mechanischen Mixer&r.",
              "",
              "In Stufe 1 bist du auf der Andesit-Stufe unterwegs, und genau die füllt die Technik-Säule mit &6Andesitlegierung&r.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(2)],
          deps=["p_hub"], icon="create:large_cogwheel"),

    quest("p_ars", 24.5, -1.5, "&dArs Nouveau",
          subtitle="Zauber selbst zusammensetzen.",
          description=[
              "In Ars Nouveau baust du deine Zauber aus Glyphen zusammen. Dazu kommen &dSource&r, Quellgläser, die &aImbuement-Kammer&r und kleine Helfer wie der Sternbunkel.",
              "",
              "Die Imbuement-Kammer ist der einzige Weg zu &6Quelljuwelen&r, und die füllen die Magie-Säule.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(2)],
          deps=["p_hub"], icon="ars_nouveau:novice_spell_book"),

    quest("p_botania", 24.5, 0.5, "&aBotania",
          subtitle="Blumen, die Mana machen.",
          description=[
              "Botania ist Magie mit Blumen. Das &6Reine Gänseblümchen&r verwandelt Stein in lebendigen Stein, erzeugende Blumen machen &dMana&r, und der &6Manaverbreiter&r schickt es ins &6Manabecken&r.",
              "",
              "In Stufe 1 geht es bis zum Manabecken. Das ist der Anfang eines langen Weges, der sich in Stufe 2 richtig auszahlt.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(2)],
          deps=["p_hub"], icon="botania:pure_daisy"),

    quest("p_storage", 24.5, 2.5, "&6Lager",
          subtitle="Rucksäcke, Schubladen und Truhen.",
          description=[
              "Bruchstein für den Obelisken, Erz aus der Mine, Zutaten für Zauber: Das muss irgendwo hin. Das Kapitel zeigt dir Rucksäcke aus Sophisticated Backpacks, Schubladen aus Functional Storage und größere Truhen.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(2)],
          deps=["p_hub"], icon="sophisticatedbackpacks:backpack"),

    quest("p_silent", 24.5, 4.5, "&6Silent Gear",
          subtitle="Werkzeug aus Einzelteilen.",
          description=[
              "Mit Silent Gear baust du Werkzeug, Waffen und Rüstung aus Teilen zusammen, deren Material die Werte bestimmt. In Stufe 1 geht das bis zur Eisen-Stufe, und schon damit schlägst du jedes Vanilla-Werkzeug aus Eisen.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(2)],
          deps=["p_hub"], icon="silentgear:pickaxe"),

    quest("p_food", 24.5, 6.5, "&6Essen und Landwirtschaft",
          subtitle="Kochen, anbauen, angeln.",
          description=[
              "Farmer's Delight bringt echte Küche: Kochtopf, Schneidebrett und Mahlzeiten, die lange satt machen. Dazu Farming for Blockheads für Felder und Tiere und Aquaculture für die Fischerei.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(2)],
          deps=["p_hub"], icon="farmersdelight:cooking_pot"),

    quest("p_explore", 24.5, 8.5, "&6Erkundung",
          subtitle="Biome, Wegsteine, die Minendimension.",
          description=[
              "Neue Biome, Wegsteine zum Reisen, die Minendimension zum hemmungslosen Graben, Bauwerke voller Beute und Ausrüstung mit zufälligen Affixen aus Apotheosis.",
          ],
          tasks=[task_checkmark("Angeschaut")],
          rewards=[reward_xp(2)],
          deps=["p_hub"], icon="minecraft:filled_map"),

    quest("p_ready", 28.5, 2.5, "&6Wähle deinen Weg",
          subtitle="Technik, Magie oder beides. Der Server braucht beides.",
          description=[
              "Du weißt jetzt, wie Kronwerke funktioniert: Der Server arbeitet gemeinsam auf den Obelisken hin, jede Stufe öffnet sich für alle, und dieses Buch zeigt dir den Weg durch jedes Kapitel.",
              "",
              "Such dir einen Anfang aus. Früher oder später wirst du ohnehin in alle drei großen Kapitel hineinschauen wollen: &6Create&r, &dArs Nouveau&r und &aBotania&r.",
              "",
              "Viel Spaß in den Kronwerken!",
          ],
          tasks=[task_checkmark("Auf geht's")],
          rewards=[reward_table("s1_uncommon"), reward_xp(10)],
          deps=["p_create", "p_ars", "p_botania", "p_storage", "p_silent", "p_food", "p_explore"],
          icon="minecraft:recovery_compass", size=2.5, shape="gear"),
]

images = [
    banner("start_here/title", "Kronwerke", 0, -2.2, height=1.8, kind="title", colour="brass"),
    banner("start_here/season", "Season 2", 0, 5.2, height=0.7, kind="note", colour="stone"),
    banner("start_here/day", "Der erste Tag", 11.5, -9.8, height=0.9, colour="nature"),
    banner("start_here/obelisk", "Der Obelisk", 10, -3.2, height=0.9, colour="stone"),
    banner("start_here/stages", "Stufen und Sperren", 10, 3.6, height=0.9, colour="brass"),
    banner("start_here/server", "Auf dem Server", 10, 10.4, height=0.9, colour="water"),
    banner("start_here/paths", "Deine Wege", 24.5, -5.4, height=0.9, colour="magic"),
]

chapter(C, "Hier geht's los", "ftbquests:book", "start", quests, shape="circle", order=0,
        subtitle=["Was Kronwerke ist, der erste Tag, der Obelisk und wie die Stufen funktionieren."],
        images=images)
