"""Lager: Sophisticated Backpacks (Leder), Functional Storage (Holzschubladen), Sophisticated Storage
(Truhen, Fässer, Lagerkern) und Trash Cans in Stufe 1. Kupfer- und Eisenrucksäcke, Kompaktier-Schubladen
und Schubladen-Speicherupgrades sowie Gold-Truhen und -Fässer öffnen in Stufe 2, Gold- und Diamantrucksäcke,
Diamant-Truhen und AE2 in Stufe 3."""
from ftbq import (chapter, quest, task_item, task_checkmark, reward_item, reward_table, reward_xp,
                  banner, img, item_texture)

C = "storage"

quests = [
    # ---- Rucksäcke (Sophisticated Backpacks) ------------------------------------------------
    quest("welcome", 0, 0, "&6Rucksack",
          subtitle="Dein Lager zum Mitnehmen.",
          description=[
              "Drei Mods halten hier Ordnung: &6Sophisticated Backpacks&r für alles, was du mitnimmst, &6Functional Storage&r für große Mengen einer Sorte und &6Sophisticated Storage&r für Truhen und Fässer, die mit dir mitwachsen. Dazu kommen ein paar kleine Helfer zum Aufräumen.",
              "",
              "Den Anfang macht der &6Rucksack&r. Rezept: eine &6Holztruhe&r in der Mitte, darum &6vier Leder&r (eins oben, drei unten) und &6vier Fäden&r an den Seiten.",
              "",
              "Der Lederrucksack hat &e27 Plätze&r, so viel wie eine Truhe, und &eeinen Upgrade-Platz&r. Du öffnest ihn mit Rechtsklick in der Hand oder mit der Taste &eB&r, solange er irgendwo in deinem Inventar steckt. Mit Schleichen und Rechtsklick auf den Boden stellst du ihn ab, der Inhalt bleibt dabei immer drin.",
              "",
              "Oben im Rucksack findest du einen Sortierknopf und die Einstellungen. Mit Farbstoffen im Handwerksraster färbst du ihn um, damit du mehrere Rucksäcke auseinanderhältst.",
              "",
              "&cKronwerke:&r Größere Rucksäcke kommen mit den Stufen. &6Kupfer&r und &6Eisen&r öffnen in Stufe 2 (Messingwerk), &6Gold&r und &6Diamant&r in Stufe 3, &6Netherit&r in Stufe 4. Gesperrte Rucksäcke kannst du schon finden und aufheben, benutzen aber erst, wenn die Stufe offen ist. Der Tooltip sagt dir, welche Stufe fehlt.",
          ],
          tasks=[task_item("sophisticatedbackpacks:backpack", 1)],
          rewards=[reward_item("minecraft:leather", 8), reward_item("minecraft:string", 8), reward_table("s1_common")],
          icon="sophisticatedbackpacks:backpack", size=2.0, shape="hexagon"),

    quest("upgrade_base", 2.5, 0, "Upgrade-Basis",
          subtitle="Jedes Rucksack-Upgrade beginnt hier.",
          description=[
              img(item_texture("sophisticatedbackpacks:upgrade_base"), 32, 32),
              "",
              "Upgrades machen aus dem Rucksack ein Werkzeug. Sie stecken in den Plätzen links neben dem Rucksackinventar, und jedes wird aus einer &6Upgrade-Basis&r gebaut.",
              "",
              "Rezept: &6Leder&r in die Mitte, &6vier Eisenbarren&r an die Seiten und &6vier Fäden&r in die Ecken.",
              "",
              "&eWichtig:&r Der Lederrucksack hat nur &eeinen&r Upgrade-Platz. Du kannst Upgrades aber jederzeit herausnehmen und tauschen, je nachdem was du gerade vorhast: Bergbau, Bauen oder Farmen. Mehr Plätze gibt es mit dem Eisenrucksack in Stufe 2.",
              "",
              "&6Tipp:&r Sophisticated Storage hat eine eigene Upgrade-Basis für Truhen und Fässer. Die beiden sehen ähnlich aus, sind aber nicht dasselbe. Achte in JEI darauf, welche Mod im Rezept steht.",
          ],
          tasks=[task_item("sophisticatedbackpacks:upgrade_base", 2)],
          rewards=[reward_item("minecraft:string", 16), reward_item("minecraft:iron_ingot", 4)],
          deps=["welcome"], icon="sophisticatedbackpacks:upgrade_base"),

    quest("pickup", 4.5, 0, "Pickup-Upgrade",
          subtitle="Alles, was du aufhebst, landet im Rucksack.",
          description=[
              img(item_texture("sophisticatedbackpacks:pickup_upgrade"), 32, 32),
              "",
              "Mit dem &6Pickup-Upgrade&r wandern aufgehobene Items zuerst in den Rucksack und erst dann in dein Inventar. Beim Graben und Holzfällen bleibt deine Hotbar so frei.",
              "",
              "Rezept: ein &6Klebriger Kolben&r oben, &6Faden&r links und rechts der &6Upgrade-Basis&r und &6drei Redstone&r unten. Für den Kolben brauchst du einen &6Schleimball&r.",
              "",
              "Im Upgrade-Tab stellst du einen Filter mit &e9 Plätzen&r ein. &eWhitelist&r heißt: nur diese Items. &eBlacklist&r heißt: alles außer diesen Items. Ein leerer Filter auf Blacklist nimmt einfach alles.",
              "",
              "&6Tipp:&r Stell Erze, Kohle und Rohmetalle auf die Whitelist. Dann bleibt der Stein im Inventar und du kannst ihn direkt am Obelisken mit &e/kw deposit&r abgeben.",
          ],
          tasks=[task_item("sophisticatedbackpacks:pickup_upgrade", 1)],
          rewards=[reward_item("minecraft:slime_ball", 4), reward_xp(3)],
          deps=["upgrade_base"], icon="sophisticatedbackpacks:pickup_upgrade"),

    quest("magnet", 6.5, 0, "Magnet-Upgrade",
          subtitle="Zieht Items in der Nähe zu dir.",
          description=[
              img(item_texture("sophisticatedbackpacks:magnet_upgrade"), 32, 32),
              "",
              "Das &6Magnet-Upgrade&r kann alles, was das Pickup-Upgrade kann, und zieht zusätzlich Items aus etwa &edrei Blöcken&r Umkreis heran. Perfekt zusammen mit FTB Ultimine, wenn ganze Adern auf einmal abbrechen.",
              "",
              "Rezept: das &6Pickup-Upgrade&r in die Mitte, &6zwei Enderperlen&r in die oberen Ecken, &6drei Eisenbarren&r dazwischen und an die Seiten, unten &6ein Redstone&r links und &6ein Lapislazuli&r rechts.",
              "",
              "Auch der Magnet hat einen Filter, damit dein Rucksack nicht mit Knochen, Pfeilen und Erde vollläuft.",
              "",
              "&cAchtung:&r Der Magnet zieht auch Items an, die ein Mitspieler gerade fallen lässt. Beim Handeln oder Teilen ausschalten: Im Upgrade-Tab gibt es einen Schalter dafür.",
          ],
          tasks=[task_item("sophisticatedbackpacks:magnet_upgrade", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 2), reward_table("s1_common")],
          deps=["pickup"], icon="sophisticatedbackpacks:magnet_upgrade"),

    quest("deposit", 8.5, 0, "Lager-Upgrade",
          subtitle="Ein Klick, und der Rucksack ist leer.",
          description=[
              img(item_texture("sophisticatedbackpacks:deposit_upgrade"), 32, 32),
              "",
              "Zurück von der Mine und alles muss in die Kisten? Mit dem &6Lager-Upgrade&r (Deposit Upgrade) nimmst du den Rucksack in die Hand und klickst mit &eSchleichen und Rechtsklick&r auf eine Truhe, ein Fass oder eine Schublade. Die passenden Items wandern hinein.",
              "",
              "Rezept: ein &6Kolben&r oben, &6zwei Eisenbarren&r neben der &6Upgrade-Basis&r, unten &6Redstone&r, eine &6Holztruhe&r und noch einmal &6Redstone&r.",
              "",
              "Im Filter kannst du einstellen, dass nur Items abgegeben werden, die im Ziel schon liegen. Zusammen mit den Schubladen weiter unten ist das die schnellste Art, einen Bergbauausflug einzuräumen.",
              "",
              "Das Gegenstück ist das &6Auffüll-Upgrade&r (Restock): Es holt Items aus einer Kiste in den Rucksack.",
          ],
          tasks=[task_item("sophisticatedbackpacks:deposit_upgrade", 1)],
          rewards=[reward_item("minecraft:redstone", 16), reward_xp(3)],
          deps=["magnet"], icon="sophisticatedbackpacks:deposit_upgrade"),

    quest("stack_starter", 10.5, 0, "Stack Upgrade Starter Tier",
          subtitle="Mehr pro Platz, ohne einen größeren Rucksack.",
          description=[
              img(item_texture("sophisticatedbackpacks:stack_upgrade_starter_tier"), 32, 32),
              "",
              "Stack-Upgrades vergrößern nicht die Zahl der Plätze, sondern wie viel in &ejeden&r Platz passt. Die &6Starterstufe&r macht aus 64 Stein pro Platz 96, also das &e1,5-fache&r.",
              "",
              "Rezept: die &6Upgrade-Basis&r in der Mitte, rundherum &6acht Kupferblöcke&r. Kupfer gibt es in Stufe 1 reichlich, gerade mit der Create-Erzverarbeitung.",
              "",
              "Die nächste Stufe, &6Stack-Upgrade Stufe 1&r, verdoppelt. Sie braucht &6acht Eisenblöcke&r, oder du wertest die Starterstufe mit &6vier Eisenblöcken&r auf. Die Stufen danach brauchen Gold-, Diamant- und Netheritblöcke.",
              "",
              "&cAchtung:&r Ein Stack-Upgrade lässt sich nur herausnehmen, wenn danach noch alles in die Plätze passt. Und denk daran: Beim Lederrucksack belegt es deinen einzigen Upgrade-Platz.",
          ],
          tasks=[task_item("sophisticatedbackpacks:stack_upgrade_starter_tier", 1)],
          rewards=[reward_item("minecraft:copper_block", 4), reward_table("s1_uncommon")],
          deps=["deposit"], icon="sophisticatedbackpacks:stack_upgrade_starter_tier"),

    quest("crafting", 2.5, 2, "Werkbank-Upgrade",
          subtitle="Eine Werkbank, die du immer dabei hast.",
          description=[
              "Das &6Werkbank-Upgrade&r legt ein 3x3-Handwerksraster in einen eigenen Tab des Rucksacks. Nie wieder zurücklaufen, weil unterwegs ein Rezept fehlt.",
              "",
              "Rezept: eine &6Werkbank&r oben, &6zwei Eisenbarren&r neben der &6Upgrade-Basis&r und eine &6Truhe&r unten.",
              "",
              "Das Raster greift direkt auf den Rucksackinhalt zu, JEI-Rezepte lassen sich mit dem Plus-Knopf hineinlegen. Beim Lederrucksack musst du dich allerdings zwischen Werkbank und anderen Upgrades entscheiden.",
          ],
          tasks=[task_item("sophisticatedbackpacks:crafting_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["upgrade_base"], icon="sophisticatedbackpacks:crafting_upgrade", optional=True),

    quest("void", 4.5, 2, "Leere-Upgrade",
          subtitle="Löscht, was du nicht haben willst.",
          description=[
              "Das &6Leere-Upgrade&r (Void Upgrade) vernichtet alle Items, die du in seinen Filter legst, sobald sie im Rucksack ankommen. Gut für Erde, Kies oder Diorit.",
              "",
              "Rezept: eine &6Enderperle&r oben, &6drei Obsidian&r um die &6Upgrade-Basis&r herum und &6zwei Redstone&r unten in den Ecken.",
              "",
              "&cAchtung:&r Bruchstein gehört nicht in den Filter! Der Obelisk braucht für das Ziel von Stufe 1 &e20 000 Bruchstein&r vom ganzen Server (gerechnet für 30 Spieler). Gib ihn lieber mit &e/kw deposit&r ab, jeder Block zählt.",
          ],
          tasks=[task_item("sophisticatedbackpacks:void_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["pickup"], icon="sophisticatedbackpacks:void_upgrade", optional=True),

    quest("feeding", 6.5, 2, "Futter-Upgrade",
          subtitle="Essen, ohne daran zu denken.",
          description=[
              "Das &6Futter-Upgrade&r füttert dich automatisch aus dem Rucksack, sobald du Hunger hast. Es wählt ein Essen, das nicht verschwendet wird.",
              "",
              "Rezept: eine &6Goldene Karotte&r oben, links ein &6Goldener Apfel&r, rechts eine &6Glitzernde Melonenscheibe&r, unten eine &6Enderperle&r und in der Mitte die &6Upgrade-Basis&r.",
              "",
              "&6Tipp:&r Leg ein paar Stapel gutes Essen aus Farmer's Delight hinein. Die Sättigung hält viel länger als Brot.",
          ],
          tasks=[task_item("sophisticatedbackpacks:feeding_upgrade", 1)],
          rewards=[reward_item("minecraft:cooked_beef", 16)],
          deps=["magnet"], icon="sophisticatedbackpacks:feeding_upgrade", optional=True),

    quest("restock", 8.5, 2, "Auffüll-Upgrade",
          subtitle="Holt Vorräte aus der Kiste.",
          description=[
              "Das Gegenstück zum Lager-Upgrade: Mit dem &6Auffüll-Upgrade&r (Restock Upgrade) klickst du mit dem Rucksack in der Hand und &eSchleichen und Rechtsklick&r auf eine Kiste, und die Items aus dem Filter wandern in den Rucksack.",
              "",
              "Rezept: ein &6Klebriger Kolben&r oben, &6zwei Eisenbarren&r neben der &6Upgrade-Basis&r, unten &6Redstone&r, eine &6Holztruhe&r und &6Redstone&r.",
              "",
              "Praktisch vor dem Bauen: Fackeln, Stufen und Baublöcke mit einem Klick einpacken.",
          ],
          tasks=[task_item("sophisticatedbackpacks:restock_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["deposit"], icon="sophisticatedbackpacks:restock_upgrade", optional=True),

    quest("tool_swapper", 10.5, 2, "Werkzeugtausch-Upgrade",
          subtitle="Immer das richtige Werkzeug in der Hand.",
          description=[
              "Das &6Werkzeugtausch-Upgrade&r schaut, worauf du mit Linksklick schlägst, und tauscht das passende Werkzeug aus dem Rucksack in deine Hand: Spitzhacke für Stein, Axt für Holz, Schaufel für Erde, Schwert für Monster.",
              "",
              "Rezept: oben &6Redstone, ein Holzschwert und Redstone&r, in der Mitte &6Holzspitzhacke, Upgrade-Basis und Holzaxt&r, unten &6Eisen, eine Holzschaufel und Eisen&r.",
              "",
              "Es funktioniert auch mit den Werkzeugen aus Silent Gear. Leg einfach dein Werkzeugset in den Rucksack.",
          ],
          tasks=[task_item("sophisticatedbackpacks:tool_swapper_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["stack_starter"], icon="sophisticatedbackpacks:tool_swapper_upgrade", optional=True),

    # ---- Schubladen (Functional Storage) -----------------------------------------------------
    quest("drawers", 0, 6.5, "&6Eichenschublade (1x1)",
          subtitle="Tausende einer Sorte in einem Block.",
          description=[
              "Eine &6Schublade&r aus Functional Storage speichert genau &eeine Sorte&r Item, davon aber sehr viel: Die 1x1-Schublade fasst &e32 Stapel&r, also 2048 Bruchstein in einem Block. Die Menge steht direkt auf der Front.",
              "",
              "Rezept: eine &6Holztruhe&r in der Mitte, rundherum &6acht Eichenbretter&r. Jede Holzsorte geht, sie ändert nur das Aussehen.",
              "",
              "&eSo bedienst du sie:&r",
              "- &eRechtsklick&r mit einem Item legt es hinein.",
              "- &eDoppelter Rechtsklick&r legt alle passenden Items aus deinem Inventar hinein.",
              "- &eLinksklick&r nimmt ein einzelnes Item heraus.",
              "- &eSchleichen und Linksklick&r nimmt einen ganzen Stapel heraus.",
              "",
              "&cAchtung:&r Jeder Schlag auf die Front holt Items heraus. Zum Abbauen schlägst du deshalb besser mit der Axt auf die Seite der Schublade. Der Inhalt bleibt beim Abbauen in der Schublade.",
          ],
          tasks=[task_item("functionalstorage:oak_1", 4)],
          rewards=[reward_item("minecraft:oak_log", 32), reward_table("s1_common")],
          icon="functionalstorage:oak_1", size=1.75, shape="rsquare"),

    quest("drawers_2", 2.5, 6.5, "Eichenschublade (1x2)",
          subtitle="Zwei Sorten, eine Front.",
          description=[
              "Die &61x2-Schublade&r hat zwei Fächer übereinander, jedes fasst &e16 Stapel&r.",
              "",
              "Rezept: &6zwei Holztruhen&r (oben und unten in der Mitte) und &6sieben Eichenbretter&r. Du bekommst gleich &ezwei&r Schubladen.",
              "",
              "Gut für Paare, die zusammengehören: Kohle und Holzkohle, Eisen- und Kupferbarren, Samen und Weizen.",
          ],
          tasks=[task_item("functionalstorage:oak_2", 2)],
          rewards=[reward_item("minecraft:chest", 2)],
          deps=["drawers"], icon="functionalstorage:oak_2"),

    quest("drawers_4", 4.5, 6.5, "Eichenschublade (2x2)",
          subtitle="Vier Fächer für die bunte Mischung.",
          description=[
              "Die &62x2-Schublade&r hat vier Fächer mit je &e8 Stapeln&r. Sie ist die beste Wahl für viele verschiedene Dinge in kleinen bis mittleren Mengen: Erze, Barren, Farbstoffe, Mob-Drops.",
              "",
              "Rezept: &6vier Holztruhen&r in den Ecken und &6fünf Eichenbretter&r. Du bekommst &evier&r Schubladen.",
              "",
              "&6Tipp:&r Baue eine Wand aus Schubladen. Mit dem Lager-Upgrade im Rucksack räumst du sie danach mit einem einzigen Klick pro Schublade ein.",
          ],
          tasks=[task_item("functionalstorage:oak_4", 4)],
          rewards=[reward_item("minecraft:chest", 4), reward_xp(3)],
          deps=["drawers_2"], icon="functionalstorage:oak_4"),

    quest("config_tool", 6.5, 6.5, "Configuration Tool",
          subtitle="Sperren, ausblenden, einstellen.",
          description=[
              "Das &6Configuration Tool&r stellt Schubladen ein. Das Wichtigste ist das &eSperren&r: Eine gesperrte Schublade merkt sich ihre Sorte, auch wenn sie leer ist. So landet in der Eisen-Schublade nie etwas anderes, und Trichter oder Förderbänder füllen immer die richtige.",
              "",
              "Rezept: &6fünf Papier&r, &6zwei Goldbarren&r, eine beliebige &6Schublade&r und ein &6Smaragd&r.",
              "",
              "Mit &eSchleichen und Rechtsklick in die Luft&r wechselst du den Modus: Sperren, Mengen ein- und ausblenden, Items ein- und ausblenden, Upgrades ein- und ausblenden und die Füllstandsanzeige. Mit &eRechtsklick&r auf eine Schublade wendest du den Modus an.",
          ],
          tasks=[task_item("functionalstorage:configuration_tool", 1)],
          rewards=[reward_item("minecraft:gold_ingot", 4), reward_xp(5)],
          deps=["drawers_4"], icon="functionalstorage:configuration_tool"),

    quest("puller", 8.5, 6.5, "Puller Upgrade",
          subtitle="Die Schublade holt sich ihre Items selbst.",
          description=[
              img(item_texture("functionalstorage:puller_upgrade"), 32, 32),
              "",
              "Schubladen haben neben dem Speicher auch &eUpgrade-Plätze&r. Am einfachsten setzt du ein Upgrade ein, indem du mit ihm in der Hand auf die Schublade rechtsklickst. Das Menü öffnest du mit Rechtsklick auf den Rahmen der Front, neben dem Item.",
              "",
              "Das &6Puller Upgrade&r zieht Items aus dem Block auf einer Seite in die Schublade, &e4 Items alle 4 Ticks&r. Welche Seite, stellst du im Menü ein: &eRechtsklick auf das Upgrade&r wechselt die Richtung.",
              "",
              "Rezept: &6sechs Stein&r, ein &6Trichter&r oben in der Mitte, eine &6Schublade&r in der Mitte und &6Redstone&r unten. Die Schublade im Rezept wird verbraucht.",
              "",
              "&6Tipp:&r Stell eine Schublade unter das Ausgabefach deiner Create-Mühle oder neben eine Truhe voller Beute, und sie sortiert sich selbst ein.",
          ],
          tasks=[task_item("functionalstorage:puller_upgrade", 1)],
          rewards=[reward_item("minecraft:hopper", 2)],
          deps=["config_tool"], icon="functionalstorage:puller_upgrade"),

    quest("pusher", 10.5, 6.5, "Pusher Upgrade",
          subtitle="Und wieder hinaus, wohin du willst.",
          description=[
              img(item_texture("functionalstorage:pusher_upgrade"), 32, 32),
              "",
              "Das &6Pusher Upgrade&r schiebt Items aus der Schublade in den Block daneben, genauso schnell wie der Puller zieht. So versorgt eine Schublade voller Kohle deine Öfen oder ein Förderband.",
              "",
              "Rezept: &6sechs Stein&r, &6Redstone&r oben in der Mitte, eine &6Schublade&r in der Mitte und ein &6Trichter&r unten.",
              "",
              "Puller und Pusher zusammen machen aus einer Schublade einen kleinen Zwischenspeicher für Create-Anlagen. Mit Create-Trichtern (Funnels) geht es übrigens auch ohne Upgrades, denn Schubladen sind ganz normale Inventare.",
          ],
          tasks=[task_item("functionalstorage:pusher_upgrade", 1)],
          rewards=[reward_item("create:andesite_alloy", 16), reward_xp(5)],
          deps=["puller"], icon="functionalstorage:pusher_upgrade"),

    quest("framed", 2.5, 8.5, "Framed Drawer (1x1)",
          subtitle="Schubladen in deinem Baustil.",
          description=[
              "&6Framed Drawers&r funktionieren wie normale Schubladen, lassen sich aber mit jedem Block verkleiden. Rezept: eine &6Holztruhe&r umgeben von &6acht Eisennuggets&r.",
              "",
              "So änderst du das Aussehen: Leg im Handwerksraster in den &eersten&r Platz den Block für außen, in den &ezweiten&r den Block für innen und in den &edritten&r die Schublade. Ein Block im vierten Platz färbt die Trennleisten.",
              "",
              "Damit passt dein Lager zu Andesit-Gehäusen, Steinziegeln oder dunkler Eiche.",
          ],
          tasks=[task_item("functionalstorage:framed_1", 1)],
          rewards=[reward_item("minecraft:iron_nugget", 16)],
          deps=["drawers_2"], icon="functionalstorage:framed_1", optional=True),

    quest("fluid", 4.5, 8.5, "Fluid Drawer (1x1)",
          subtitle="Eine Schublade für Flüssigkeiten.",
          description=[
              "Die &6Fluid Drawer&r speichert eine Sorte Flüssigkeit, zum Beispiel &bWasser&r, &bLava&r oder &bHonig&r. Rezept: ein &6Eimer&r in der Mitte, rundherum &6acht Holzbretter&r.",
              "",
              "Mit einem Eimer in der Hand füllst du sie per Rechtsklick oder holst Flüssigkeit heraus. Create-Rohre können sie ebenfalls füllen und leeren.",
              "",
              "Es gibt sie wie die normalen Schubladen auch als 1x2 und 2x2.",
          ],
          tasks=[task_item("functionalstorage:fluid_1", 1)],
          rewards=[reward_item("minecraft:bucket", 2)],
          deps=["drawers_4"], icon="functionalstorage:fluid_1", optional=True),

    quest("water_gen", 4.5, 10.3, "Water Generator Upgrade",
          subtitle="Wasser ohne Ende, ohne Quelle.",
          description=[
              img(item_texture("functionalstorage:water_generator_upgrade"), 32, 32),
              "",
              "Setz das &6Water Generator Upgrade&r in eine Fluid Drawer, und sie füllt sich von selbst mit &bWasser&r. Rezept: &6sechs Stein&r, &6zwei Wassereimer&r oben und unten in der Mitte und ein leerer &6Eimer&r im Zentrum.",
              "",
              "Praktisch für Create: Ein Rohr an der Schublade liefert Wasser für Waschanlagen, Mixer oder die Beton-Herstellung, ganz ohne unendliche Quelle im Boden.",
          ],
          tasks=[task_item("functionalstorage:water_generator_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["fluid"], icon="functionalstorage:water_generator_upgrade", optional=True),

    quest("drawer_void", 6.5, 8.5, "Void Upgrade",
          subtitle="Wenn voll, dann weg.",
          description=[
              img(item_texture("functionalstorage:void_upgrade"), 32, 32),
              "",
              "Eine Schublade mit &6Void Upgrade&r nimmt weiter Items an, wenn sie voll ist, und löscht alles, was nicht mehr hineinpasst. So verstopft keine Förderstrecke, nur weil eine Schublade voll ist.",
              "",
              "Rezept: eine &6Schublade&r in der Mitte, rundherum &6acht Obsidian&r.",
              "",
              "&6Tipp:&r Ideal hinter einer Bruchstein-Maschine. Die Schublade bleibt immer bei 2048 Stück, und bevor der Rest verschwindet, bringst du den Vorrat zum Obelisken.",
          ],
          tasks=[task_item("functionalstorage:void_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["config_tool"], icon="functionalstorage:void_upgrade", optional=True),

    quest("collector", 8.5, 8.5, "Collector Upgrade",
          subtitle="Sammelt herumliegende Items ein.",
          description=[
              img(item_texture("functionalstorage:collector_upgrade"), 32, 32),
              "",
              "Das &6Collector Upgrade&r saugt Items auf, die vor der eingestellten Seite der Schublade auf dem Boden liegen. Rezept: &6vier Stein&r in den Ecken, &6zwei Trichter&r oben und unten, &6zwei Redstone&r an den Seiten und eine &6Schublade&r in der Mitte.",
              "",
              "Gut für Farmen, bei denen Items einfach herunterfallen: Kakteen, Zuckerrohr oder eine Mob-Falle.",
          ],
          tasks=[task_item("functionalstorage:collector_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["puller"], icon="functionalstorage:collector_upgrade", optional=True),

    quest("redstone_upgrade", 10.5, 8.5, "Redstone Upgrade",
          subtitle="Die Schublade meldet ihren Füllstand.",
          description=[
              img(item_texture("functionalstorage:redstone_upgrade"), 32, 32),
              "",
              "Mit dem &6Redstone Upgrade&r gibt die Schublade ein Redstone-Signal aus, das mit ihrem Füllstand steigt. Im Menü wählst du per Rechtsklick auf das Upgrade, welches Fach gemessen wird.",
              "",
              "Rezept: &6vier Redstone&r in den Ecken, &6zwei Redstoneblöcke&r oben und unten, &6zwei Komparatoren&r an den Seiten und eine &6Schublade&r in der Mitte.",
              "",
              "Damit schaltest du eine Create-Anlage ab, sobald das Lager voll ist, zum Beispiel über eine Kupplung (Clutch) im Antrieb.",
          ],
          tasks=[task_item("functionalstorage:redstone_upgrade", 1)],
          rewards=[reward_item("minecraft:redstone", 16)],
          deps=["pusher"], icon="functionalstorage:redstone_upgrade", optional=True),

    # ---- Truhen und Fässer (Sophisticated Storage) ------------------------------------------
    quest("barrel", 0, 14.5, "&6Fass",
          subtitle="Ein Fass, das du aufwertest statt ersetzt.",
          description=[
              "Die Truhen und Fässer aus &6Sophisticated Storage&r haben einen großen Vorteil: Du wertest sie &edirekt in der Welt&r auf. Der Block bleibt stehen, alles drin bleibt drin, nur der Platz wächst.",
              "",
              "Rezept für das &6Fass&r: &6sechs Holzbretter&r, &6zwei Holzstufen&r (oben und unten in der Mitte) und ein &6Hebel&r in der Mitte. Es übernimmt das Aussehen der verwendeten Holzsorte.",
              "",
              "Wie eine Truhe hat es &e27 Plätze&r und dazu &eeinen Upgrade-Platz&r. Fässer lassen sich im Gegensatz zu Truhen in jede Richtung drehen und direkt aneinanderbauen.",
              "",
              "&6Tipp:&r Ein Hebel ist die Zutat, die aus normalen Holzblöcken die aufwertbare Version macht. Auch eine Vanilla-Truhe plus Hebel ergibt eine Sophisticated-Truhe.",
          ],
          tasks=[task_item("sophisticatedstorage:barrel", 2)],
          rewards=[reward_item("minecraft:lever", 4), reward_table("s1_common")],
          icon="sophisticatedstorage:barrel", size=1.75, shape="rsquare"),

    quest("copper_tier", 2.5, 14.5, "Kupferstufe",
          subtitle="Kupfer ist genau dafür da.",
          description=[
              img(item_texture("sophisticatedstorage:basic_to_copper_tier_upgrade"), 32, 32),
              "",
              "Die erste Aufwertung: Das &6Basic to Copper Tier Upgrade&r aus &6acht Kupferbarren&r und einem &6Hebel&r in der Mitte.",
              "",
              "&eSo geht es:&r Nimm das Upgrade in die Hand und mach einen &eRechtsklick auf die platzierte Truhe oder das Fass&r. Fertig. Aus 27 Plätzen werden &e45&r, der Inhalt bleibt, wo er ist.",
              "",
              "Kupfer ist in Stufe 1 der günstigste Weg zu mehr Platz. Wer Create-Erzverarbeitung betreibt, hat es sowieso in Mengen.",
          ],
          tasks=[task_item("sophisticatedstorage:basic_to_copper_tier_upgrade", 1)],
          rewards=[reward_item("minecraft:copper_ingot", 16)],
          deps=["barrel"], icon="sophisticatedstorage:basic_to_copper_tier_upgrade"),

    quest("iron_tier", 4.5, 14.5, "Eisenstufe",
          subtitle="Mehr Platz und ein zweiter Upgrade-Platz.",
          description=[
              img(item_texture("sophisticatedstorage:basic_to_iron_tier_upgrade"), 32, 32),
              "",
              "Die &6Eisenstufe&r bringt &e54 Plätze&r und vor allem einen &ezweiten Upgrade-Platz&r. Zwei Wege führen hin:",
              "",
              "- &6Copper to Iron Tier Upgrade&r: &6vier Eisenbarren&r und ein &6Hebel&r, für Truhen, die schon Kupfer sind.",
              "- &6Basis zu Eisenversion Upgrade&r: &6acht Eisenbarren&r und ein &6Hebel&r, direkt von Holz auf Eisen.",
              "",
              "Wie immer: Rechtsklick auf den platzierten Block. Für diese Quest brauchst du ein &6Eisenfass&r im Inventar. Das geht auch direkt im Handwerksraster: ein Fass in die Mitte, acht Eisenbarren drumherum.",
              "",
              "Die Stufen danach kommen mit dem Server: &6Gold&r (81 Plätze, 3 Upgrades) öffnet mit Stufe 2, &6Diamant&r (108 Plätze, 4 Upgrades) mit Stufe 3 und &6Netherit&r mit Stufe 4. Eisen ist also das Beste, was du in Stufe 1 bekommst, und mit einem Stack-Upgrade reicht das für lange Zeit.",
          ],
          tasks=[task_item("sophisticatedstorage:iron_barrel", 1)],
          rewards=[reward_item("minecraft:iron_ingot", 16), reward_xp(5)],
          deps=["copper_tier"], icon="sophisticatedstorage:basic_to_iron_tier_upgrade"),

    quest("storage_upgrade_base", 6.5, 14.5, "Upgrade Basis",
          subtitle="Die Upgrade-Basis für Truhen und Fässer.",
          description=[
              img(item_texture("sophisticatedstorage:upgrade_base"), 32, 32),
              "",
              "Truhen und Fässer nehmen fast dieselben Upgrades wie der Rucksack, dazu ein paar eigene. Sie werden aus der &6Upgrade Basis&r von Sophisticated Storage gebaut: &6fünf Holzbretter&r und &6vier Eisenbarren&r im Schachbrettmuster.",
              "",
              "Upgrades legst du im Menü der Truhe in die Plätze links. Ein Holzfass hat einen Platz, ab Eisen sind es zwei.",
              "",
              "&6Tipp:&r Upgrades lassen sich zwischen Rucksack und Lager umbauen. Ein Lager-Upgrade mit Leder und Faden wird zum Rucksack-Upgrade. JEI zeigt dir die Rezepte.",
          ],
          tasks=[task_item("sophisticatedstorage:upgrade_base", 2)],
          rewards=[reward_item("minecraft:iron_ingot", 8)],
          deps=["iron_tier"], icon="sophisticatedstorage:upgrade_base"),

    quest("storage_stack", 8.5, 14.5, "Stack Upgrade Stufe 1",
          subtitle="Doppelt so viel pro Platz, aus Holz.",
          description=[
              img(item_texture("sophisticatedstorage:stack_upgrade_tier_1"), 32, 32),
              "",
              "Das Stack-Upgrade für Truhen ist in Stufe 1 überraschend günstig: die &6Upgrade Basis&r in der Mitte und &6acht Holzstämme&r drumherum. Jeder Platz fasst danach das &eDoppelte&r.",
              "",
              "Ein Eisenfass mit 54 Plätzen und diesem Upgrade hält so viel wie vier normale Truhen. Pro Truhe oder Fass sind höchstens &ezwei Stack-Upgrades&r erlaubt.",
              "",
              "Aufwerten geht auch hier: &6Stack Upgrade Tier 1 Plus&r (Kupfer, dreifach) und &6Stufe 2&r (Eisen, vierfach).",
          ],
          tasks=[task_item("sophisticatedstorage:stack_upgrade_tier_1", 1)],
          rewards=[reward_item("minecraft:oak_log", 32), reward_xp(5)],
          deps=["storage_upgrade_base"], icon="sophisticatedstorage:stack_upgrade_tier_1"),

    quest("hopper", 10.5, 14.5, "Trichter-Upgrade",
          subtitle="Ein Trichter, der im Fass wohnt.",
          description=[
              img(item_texture("sophisticatedstorage:hopper_upgrade"), 32, 32),
              "",
              "Das &6Trichter-Upgrade&r zieht Items aus dem Block &eüber&r dem Lager und schiebt sie in den Block &edarunter&r. Beide Richtungen haben einen eigenen Filter und lassen sich einzeln abschalten.",
              "",
              "Rezept: ein &6Trichter&r oben, &6zwei Eisenbarren&r neben der &6Upgrade Basis&r und &6drei Redstone&r unten.",
              "",
              "&6Tipp:&r Ein Fass mit Trichter-Upgrade unter einer Farm sammelt die Ernte ein, und ein Filter schickt nur die Samen weiter nach unten zurück in die Pflanzmaschine.",
          ],
          tasks=[task_item("sophisticatedstorage:hopper_upgrade", 1)],
          rewards=[reward_item("minecraft:hopper", 2), reward_xp(3)],
          deps=["storage_stack"], icon="sophisticatedstorage:hopper_upgrade"),

    quest("controller", 12.5, 14.5, "&6Lagerkern",
          subtitle="Viele Truhen, ein Zugang.",
          description=[
              "Der &6Lagerkern&r (Storage Controller) verbindet alle Sophisticated-Truhen und -Fässer, die ihn berühren oder sich gegenseitig berühren, zu einem gemeinsamen Lager.",
              "",
              "Rezept: &6vier Stein&r in den Ecken, &6zwei Komparatoren&r oben und unten, &6zwei Holzbretter&r an den Seiten und in der Mitte eine &6Sophisticated-Truhe oder ein -Fass&r der Holzstufe.",
              "",
              "&eSo nutzt du ihn:&r",
              "- Rechtsklick mit einem Item auf den Kern legt es in eine passende Truhe im Verbund.",
              "- Trichter, Create-Trichter und Rohre am Kern verteilen Items automatisch auf den ganzen Verbund und holen sie auch wieder heraus.",
              "- &6Storage Connector&r aus Stöcken und Brettern überbrücken Lücken zwischen den Truhen.",
              "",
              "Das ist noch kein echtes Speichernetzwerk mit Suchfunktion. Das bringt &6Applied Energistics 2&r in Stufe 3 (Stahlwerk). Bis dahin ist der Lagerkern das beste Sammelbecken für deine Basis.",
          ],
          tasks=[task_item("sophisticatedstorage:controller", 1)],
          rewards=[reward_item("minecraft:comparator", 2), reward_table("s1_uncommon"), reward_xp(5)],
          deps=["hopper"], icon="sophisticatedstorage:controller", size=1.5, shape="hexagon"),

    quest("chest", 0, 16.5, "Truhe",
          subtitle="Die Sophisticated-Truhe.",
          description=[
              "Die &6Truhe&r aus Sophisticated Storage funktioniert wie das Fass und wird genauso aufgewertet. Rezept: &6acht Holzbretter&r um einen &6Hebel&r, oder eine Vanilla-Truhe und ein Hebel.",
              "",
              "Zwei nebeneinander gestellte Truhen werden wie in Vanilla zu einer &eDoppeltruhe&r.",
              "",
              "Ob Fass oder Truhe ist Geschmackssache. Fässer lassen sich platzsparender stapeln, Truhen sehen in Wohnräumen schöner aus.",
          ],
          tasks=[task_item("sophisticatedstorage:chest", 1)],
          rewards=[reward_item("minecraft:oak_planks", 32)],
          deps=["barrel"], icon="sophisticatedstorage:chest", optional=True),

    quest("packing_tape", 0, 18.3, "Packband",
          subtitle="Umziehen, ohne auszuräumen.",
          description=[
              img(item_texture("sophisticatedstorage:packing_tape"), 32, 32),
              "",
              "Mit &6Packband&r klebst du eine volle Truhe zu: &eRechtsklick&r mit dem Band auf den Block, dann abbauen. Sie fällt als ein einziges Item samt Inhalt heraus und lässt sich woanders wieder aufstellen.",
              "",
              "Rezept: &6ein Schleimball&r und &6ein Papier&r, formlos. Eine Rolle hält mehrere Einsätze, der Tooltip zeigt die übrigen an.",
              "",
              "Perfekt, wenn deine erste Hütte zu klein wird und die Basis umzieht.",
          ],
          tasks=[task_item("sophisticatedstorage:packing_tape", 1)],
          rewards=[reward_item("minecraft:slime_ball", 2)],
          deps=["chest"], icon="sophisticatedstorage:packing_tape", optional=True),

    quest("basic_tier", 2.5, 16.5, "Umwandlungsupgrade",
          subtitle="Aus Vanilla wird Sophisticated.",
          description=[
              img(item_texture("sophisticatedstorage:basic_tier_upgrade"), 32, 32),
              "",
              "Du hast schon zehn volle Vanilla-Truhen? Kein Problem. Das &6Umwandlungsupgrade&r (Basic Tier Upgrade) macht aus einer platzierten Vanilla-Truhe oder einem Vanilla-Fass per Rechtsklick die Sophisticated-Version, mit allem Inhalt.",
              "",
              "Rezept: ein &6Hebel&r in der Mitte, &6vier Stöcke&r oben, unten und an den Seiten.",
              "",
              "Danach kannst du sie wie jede andere Sophisticated-Truhe auf Kupfer und Eisen bringen.",
          ],
          tasks=[task_item("sophisticatedstorage:basic_tier_upgrade", 1)],
          rewards=[reward_xp(3)],
          deps=["copper_tier"], icon="sophisticatedstorage:basic_tier_upgrade", optional=True),

    quest("limited_barrel", 8.5, 16.5, "Eingeschränktes Fass",
          subtitle="Schublade oder Fass? Beides.",
          description=[
              "&6Eingeschränkte Fässer&r (Limited Barrels) sind die Schubladen von Sophisticated Storage: wenige Fächer, aber jedes davon riesig. Die Zahl im Namen sagt, wie viele Fächer:",
              "",
              "- &6I&r: ein Fach mit &e32 Stapeln&r",
              "- &6II&r: zwei Fächer mit je &e16 Stapeln&r",
              "- &6III&r: drei Fächer mit je &e10 Stapeln&r",
              "- &6IV&r: vier Fächer mit je &e8 Stapeln&r",
              "",
              "Rezept: Holzbretter, Holzstufen und ein Hebel, je nach Variante in einem anderen Muster (JEI zeigt alle vier). Im Unterschied zu Functional Storage lassen sie sich mit den Stufen-Upgrades vergrößern und nehmen Sophisticated-Upgrades auf.",
          ],
          tasks=[task_item("sophisticatedstorage:limited_barrel_1", 1)],
          rewards=[reward_xp(3)],
          deps=["storage_stack"], icon="sophisticatedstorage:limited_barrel_1", optional=True),

    quest("storage_link", 12.5, 16.5, "Lagerverbindung",
          subtitle="Truhen verbinden, die sich nicht berühren.",
          description=[
              "Deine Lager stehen in verschiedenen Räumen? Eine &6Lagerverbindung&r (Storage Link) hängt einen entfernten Truhenblock an den Lagerkern.",
              "",
              "Rezept: &6Enderperle&r und &6Holzbrett&r oben, &6Verstärker&r und &6Stein&r unten. Oder formlos: ein Lagerkern und eine Enderperle ergeben drei Stück.",
              "",
              "Verbunden wird mit dem &6Lagerwerkzeug&r (Storage Tool: Enderperle, Eisenbarren, Redstonefackel und zwei Stöcke): erst den Lagerkern anklicken, dann die Lagerverbindung.",
          ],
          tasks=[task_item("sophisticatedstorage:storage_link", 1)],
          rewards=[reward_item("minecraft:ender_pearl", 2)],
          deps=["controller"], icon="sophisticatedstorage:storage_link", optional=True),

    # ---- Aufräumen ---------------------------------------------------------------------------
    quest("trash", 0, 22, "Item Trash Can",
          subtitle="Was hineinfällt, ist weg.",
          description=[
              "Die &6Item Trash Can&r aus der Mod Trash Cans löscht alles, was hineinkommt: per Hand, per Trichter, per Create-Trichter oder per Förderband.",
              "",
              "Rezept: &6drei Stein&r oben, eine &6Holztruhe&r in der Mitte, &6fünf Bruchstein&r drumherum.",
              "",
              "Im Menü gibt es einen Filter mit &e9 Plätzen&r, als Whitelist (nur diese löschen) oder Blacklist (alles außer diesen löschen). Hinter einer Farm oder einem Sortiersystem fängt sie ab, was sonst die Leitungen verstopfen würde.",
              "",
              "&cAchtung:&r Bevor Bruchstein im Müll landet: Der Obelisk braucht ihn! Mit &e/kw deposit all&r gibst du alles ab, was das aktuelle Ziel gebrauchen kann.",
          ],
          tasks=[task_item("trashcans:item_trash_can", 1)],
          rewards=[reward_xp(3), reward_table("s1_common")],
          icon="trashcans:item_trash_can", size=1.5, shape="rsquare"),

    quest("liquid_trash", 2.5, 22, "Fluid Trash Can",
          subtitle="Für überschüssige Flüssigkeiten.",
          description=[
              "Die &6Fluid Trash Can&r macht dasselbe mit Flüssigkeiten. Rezept wie die Item-Version, nur mit einem &6Eimer&r statt der Truhe in der Mitte.",
              "",
              "Nützlich, wenn eine Create-Anlage mehr &bWasser&r oder &bLava&r pumpt als du brauchst. Sie hat einen eigenen Filter für bis zu 9 Flüssigkeiten.",
              "",
              "Aus Item-, Fluid- und Energy Trash Can zusammen entsteht die &6Ultimate Trash Can&r, die alles auf einmal kann.",
          ],
          tasks=[task_item("trashcans:liquid_trash_can", 1)],
          rewards=[reward_xp(3)],
          deps=["trash"], icon="trashcans:liquid_trash_can", optional=True),

    quest("sack", 4.5, 22, "Sack",
          subtitle="Neun Plätze in einem Sack.",
          description=[
              "Aus Supplementaries kommt der &6Sack&r: ein kleines tragbares Lager mit &e9 Plätzen&r, das du auch als Block abstellen kannst. Rezept: &6ein Faden&r oben in der Mitte und &6sieben Flachs&r drumherum. Flachs wächst wild in der Welt, die Samen kannst du anbauen.",
              "",
              "&cAchtung:&r Säcke sind schwer. Wer mehr als zwei davon mit sich trägt, wird langsamer, und mit jedem weiteren Paar noch langsamer.",
              "",
              "Als Beutel für Samen oder Baumaterial neben dem Rucksack ist er trotzdem praktisch.",
          ],
          tasks=[task_item("supplementaries:sack", 1)],
          rewards=[reward_item("minecraft:string", 8)],
          deps=["trash"], icon="supplementaries:sack", optional=True),

    # ---- Ziel und Ausblick ---------------------------------------------------------------------
    quest("organised", 16, 9, "&6Ordnung im Kronwerk",
          subtitle="Eine Basis, in der man Dinge wiederfindet.",
          description=[
              "Du hast alle drei Säulen eines guten Lagers beisammen:",
              "",
              "- einen &6Rucksack&r mit dem Upgrade, das zu deinem Tag passt,",
              "- eine &6Schubladenwand&r für alles, was in großen Mengen kommt,",
              "- &6aufgewertete Fässer&r am &6Lagerkern&r für den Rest.",
              "",
              "Zeig, was du gebaut hast: acht 2x2-Schubladen, zwei Eisenfässer und einen Lagerkern. Damit ist deine Basis bereit für die Mengen, die Create in den nächsten Tagen ausspuckt.",
          ],
          tasks=[task_item("functionalstorage:oak_4", 8), task_item("sophisticatedstorage:iron_barrel", 2),
                 task_item("sophisticatedstorage:controller", 1)],
          rewards=[reward_table("s1_rare"), reward_xp(10)],
          deps=["stack_starter", "pusher", "controller"], icon="sophisticatedstorage:iron_barrel",
          size=2.5, shape="gear"),

    quest("outlook", 16, 12.5, "Ausblick: Mehr Platz",
          subtitle="Was die nächsten Stufen bringen.",
          description=[
              "Lager wächst in Kronwerke mit jeder Stufe, die der Server gemeinsam öffnet:",
              "",
              "&6Stufe 2 (Messingwerk):&r &6Kupfer-&r und &6Eisenrucksack&r (Eisen hat zwei Upgrade-Plätze), die &6Compacting Drawer&r, die Nuggets, Barren und Blöcke in einem Block zusammenfasst, die Schubladen-Upgrades aus &6Kupfer&r und &6Gold&r (achtfacher und sechzehnfacher Platz), die &6Goldstufe&r für Truhen und Fässer (81 Plätze, drei Upgrade-Plätze) und mit dem Nether auch Quarz für den &6Storage Controller&r von Functional Storage.",
              "",
              "&6Stufe 3 (Stahlwerk):&r &6Gold-&r und &6Diamantrucksack&r, die &6Diamantstufe&r für Truhen, die &6Ender Drawer&r und &6Applied Energistics 2&r, das erste echte Speichernetzwerk mit Suche und Autocrafting.",
              "",
              "Gesperrte Items zeigen im Tooltip, in welcher Stufe sie öffnen. Du darfst sie schon sammeln, nur benutzen geht erst später.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_xp(3)],
          deps=["organised"], icon="minecraft:chest", optional=True),
]

images = [
    banner("storage/title", "Lager und Ordnung", 5.2, -4.0, height=1.7, kind="title", colour="stone"),
    banner("storage/backpacks", "Rucksäcke", 0.6, -1.85, height=0.9, colour="brass"),
    banner("storage/drawers", "Schubladen", 0.98, 4.6, height=0.9, colour="nature"),
    banner("storage/chests", "Truhen und Fässer", 1.75, 12.6, height=0.9, colour="stone"),
    banner("storage/cleanup", "Aufräumen", 0.7, 20.3, height=0.9, colour="stone"),
    banner("storage/goal", "Ziel", 16, 6.6, height=0.9, colour="brass"),
]

chapter(C, "Lager", "sophisticatedbackpacks:backpack", "storage", quests, shape="circle", order=5,
        subtitle=["Rucksäcke, Schubladen und Truhen, die mit dir wachsen."], images=images)
