"""The End: opened on stream with the stage 4 event (the End portal is activated). Getting
there, the dragon as the first shared boss, respawning it, the gateways and the outer
islands with end cities, shulkers and elytra, and what the other mods need from the End
(draconium, elite circuits, the big storage cells)."""
from ftbq import (chapter, quest, task_item, task_checkmark, task_dimension, task_kill, task_advancement,
                  reward_item, reward_table, reward_xp, banner, img, item_texture)

C = "the_end"

quests = [
    # ---- Anreise -------------------------------------------------------------
    quest("arrival", 0, 4.5, "&5&lDas End",
          subtitle="Auf Stream geöffnet. Der Drache wartet auf alle.",
          description=[
              "Mit dem Event zu Beginn von &eStufe 4&r wurde das &5Endportal&r vor laufender Kamera aktiviert. Seitdem ist das End für alle offen.",
              "",
              "Du landest auf einer Plattform aus Obsidian, ein Stück neben der Hauptinsel. Dort kreist der &5Enderdrache&r über einem Kreis aus hohen Obsidiansäulen. &eYUNG's Better End Island&r baut die Insel auf Kronwerke etwas um: eine neue Plattform, ein Turm in der Mitte und eigene Transitportale.",
              "",
              "&cWichtig:&r Unter den Inseln ist nichts als Leere. Wer hinunterfällt, stirbt, und alles, was er dabei hatte, ist weg. Nimm beim ersten Mal nur mit, was du wirklich brauchst.",
              "",
              "&eKronwerke:&r Der Drache ist der erste gemeinsame Boss der Season. Der erste Kampf läuft auf Stream, also wartet mit dem Drachen auf die anderen.",
          ],
          tasks=[task_dimension("minecraft:the_end")],
          rewards=[reward_item("minecraft:ender_pearl", 8), reward_table("s4_common"), reward_xp(10)],
          icon="minecraft:end_stone", size=2.0, shape="hexagon"),

    quest("prepare", 2.5, 4.5, "&dRichtig ausgerüstet",
          subtitle="Kürbis, Bogen, Blöcke.",
          description=[
              "&eEndermen:&r Hier wimmelt es von ihnen. Schau ihnen nicht in die Augen, sonst greifen sie an. Mit einem &6geschnitzten Kürbis&r auf dem Kopf kannst du sie ansehen, wie du willst. Die Sicht wird dabei schlechter, also wechsle ihn beim Kampf gegen den Drachen lieber gegen einen Helm.",
              "",
              "&eFernkampf:&r Für die Kristalle und den Drachen brauchst du einen &6Bogen&r und viele Pfeile.",
              "",
              "&eBlöcke:&r Nimm einen Stapel Bruchstein oder ähnliches mit, um Säulen hochzubauen und Lücken zu schließen. Ein &6Wassereimer&r hilft gegen Endermen: Wasser mögen sie gar nicht.",
              "",
              "&eEssen und Tränke:&r Goldene Karotten, Heiltränke und, wenn du hast, Tränke des sanften Falls.",
          ],
          tasks=[task_item("minecraft:carved_pumpkin", 1), task_item("minecraft:bow", 1), task_item("minecraft:arrow", 64)],
          rewards=[reward_item("minecraft:arrow", 64), reward_item("minecraft:golden_carrot", 16)],
          deps=["arrival"], icon="minecraft:carved_pumpkin", size=1.5),

    quest("own_portal", 0, 7.5, "&5Ein eigenes Endportal",
          subtitle="Zwölf Enderaugen und eine Festung.",
          description=[
              "Endportale stehen in &6Festungen&r tief unter der Erde. Auf Kronwerke sind das die größeren Festungen von &eYUNG's Better Strongholds&r.",
              "",
              "&eSo findest du eine:&r Wirf ein &6Enderauge&r (Enderperle und Lohenstaub) in die Luft. Es fliegt in Richtung der nächsten Festung. Geh hinterher, wirf das nächste, und wenn es nach unten zeigt, grab dich hinunter. Ab und zu zerbricht ein Auge.",
              "",
              "&eDas Portal:&r Ein Rahmen aus zwölf Portalrahmen-Blöcken. In jeden gehört ein Enderauge, dann öffnet es sich.",
              "",
              "Das Portal vom Event reicht für alle. Ein eigenes lohnt sich, wenn deine Basis weit weg liegt.",
          ],
          tasks=[task_item("minecraft:ender_eye", 12)],
          rewards=[reward_item("minecraft:ender_pearl", 8), reward_xp(10)],
          deps=["arrival"], icon="minecraft:ender_eye", optional=True),

    # ---- Der Drache ----------------------------------------------------------
    quest("crystals", 5, 2.5, "&dDie Endkristalle",
          subtitle="Erst die Kristalle, dann der Drache.",
          description=[
              "Auf jeder &6Obsidiansäule&r sitzt ein &dEndkristall&r. Solange einer davon steht, heilt sich der Drache über einen Strahl daran.",
              "",
              "&eDie offenen Kristalle&r schießt du mit dem Bogen ab. Ein getroffener Kristall explodiert, also nicht danebenstehen.",
              "",
              "&eDie Käfige:&r Zwei Kristalle sind von &6Eisengittern&r umgeben. Da kommen Pfeile nicht durch. Bau dir eine Säule nach oben, brich ein Gitter auf und zerstöre den Kristall dann aus sicherer Entfernung, zum Beispiel mit einem Pfeil durch das Loch.",
              "",
              "&eTipp:&r Sprecht euch ab, wer welche Säule nimmt. Zu zehnt geht das in wenigen Minuten.",
          ],
          tasks=[task_checkmark("Die Kristalle sind zerstört")],
          rewards=[reward_item("minecraft:arrow", 32), reward_xp(5)],
          deps=["prepare"], icon="minecraft:end_crystal"),

    quest("dragon", 7.5, 4.5, "&5&lDer Enderdrache",
          subtitle="Der erste gemeinsame Boss.",
          description=[
              "Sind die Kristalle weg, geht es dem &5Enderdrachen&r an den Kragen.",
              "",
              "&eIm Flug&r triffst du ihn mit Pfeilen. Er speit Feuerbälle aus Drachenatem, die eine violette Wolke hinterlassen. Raus da.",
              "",
              "&eAuf dem Portal:&r Ab und zu landet er auf dem Brunnen in der Mitte. Das ist die Gelegenheit für das Schwert. Pass auf: Wenn er dich mit dem Kopf erwischt, fliegst du weit, im schlimmsten Fall über den Rand.",
              "",
              "&eBetten:&r Im End explodieren Betten genauso wie im Nether. Manche legen ein Bett neben den gelandeten Drachen und klicken es an. Das macht großen Schaden, trifft aber auch dich und alle anderen in der Nähe. Nur mit Rüstung, Abstand und Absprache.",
              "",
              "&eWas er fallen lässt:&r Viel Erfahrung, und dank &6Draconic Evolution&r ein &6Drachenherz&r und einen Haufen &6Draconiumstaub&r. Danach erscheint in der Mitte das Ausgangsportal und am Rand das erste &5Transitportal&r.",
              "",
              "&eKronwerke:&r Hak die Quest ab, wenn du beim Kampf dabei warst. Den letzten Schlag landet sowieso nur einer.",
          ],
          tasks=[task_checkmark("Beim Kampf gegen den Drachen dabei")],
          rewards=[reward_table("s4_uncommon"), reward_xp(30)],
          deps=["crystals"], icon="minecraft:dragon_head", size=2.5, shape="gear"),

    quest("breath", 5, 6.8, "&dDrachenatem",
          subtitle="In Flaschen abgefüllt.",
          description=[
              "Die violetten Wolken, die der Drache hinterlässt, kannst du mit einer leeren &6Glasflasche&r einsammeln. Das gibt &dDrachenatem&r.",
              "",
              "&eWofür:&r",
              "&6Verweiltränke:&r Drachenatem im Braustand macht aus einem Wurftrank einen Verweiltrank, der als Wolke liegen bleibt.",
              "&6Ars Nouveau:&r Die Glyphen &eLinger&r und &eWall&r brauchen ihn.",
              "&6Occultism:&r Mehrere Marid-Rituale wollen Drachenatem, zum Beispiel der Schmelz-Marid und der Drachenkristallstaub. Auch das Ritual für den &6Besessenen Shulker&r (siehe Shulker-Quest).",
              "",
              "&eTipp:&r Sammle schon beim ersten Kampf. Später musst du den Drachen dafür neu beschwören.",
          ],
          tasks=[task_item("minecraft:dragon_breath", 4)],
          rewards=[reward_item("minecraft:glass_bottle", 16), reward_xp(10)],
          deps=["dragon"], icon="minecraft:dragon_breath"),

    quest("heart", 10, 2.5, "&cDas Drachenherz",
          subtitle="Für den, der zuerst zugreift.",
          description=[
              "Mit &6Draconic Evolution&r lässt jeder besiegte Drache ein &cDrachenherz&r fallen. Es gibt pro Kampf nur eines, also klärt vorher, wer es bekommt.",
              "",
              "&eWofür:&r In &eStufe 4&r baust du daraus das Modul &6Wyvern-Schildsteuerung&r für die Wyvern-Ausrüstung. In &eStufe 5&r steckt in jedem Fusionsrezept für &6Erweckte Draconiumblöcke&r ein Drachenherz.",
              "",
              "&eRezept auf Kronwerke:&r Beim erweckten Draconium werden zwei der sechs Draconiumkerne durch &dGaia-Geistbarren&r ersetzt. Das Drachenherz bleibt drin. Wer Herzen sammelt, hilft also schon jetzt beim Finale.",
          ],
          tasks=[task_item("draconicevolution:dragon_heart", 1)],
          rewards=[reward_item("draconicevolution:draconium_ingot", 4), reward_xp(10)],
          deps=["dragon"], icon="draconicevolution:dragon_heart", optional=True),

    quest("egg", 10, 6.5, "&5Das Drachenei",
          subtitle="Es will nicht angefasst werden.",
          description=[
              "Nach dem Sieg erscheint das &5Drachenei&r oben auf dem Ausgangsportal.",
              "",
              "&eDas Problem:&r Klickst du es an, teleportiert es sich ein Stück weg. Abbauen geht so nicht.",
              "",
              "&eSo geht es:&r Stell eine &6Fackel&r unter den Block, auf dem das Ei liegt, und bau diesen Block dann ab. Das Ei fällt auf die Fackel und wird zum Item. Ein &6Kolben&r, der das Ei verschiebt, klappt auch.",
              "",
              "Das Ei ist eine Trophäe. Stell es dir in die Basis.",
          ],
          tasks=[task_item("minecraft:dragon_egg", 1)],
          rewards=[reward_xp(15)],
          deps=["dragon"], icon="minecraft:dragon_egg", optional=True),

    quest("respawn", 12.5, 4.5, "&dNoch einmal, bitte",
          subtitle="Vier Kristalle auf den Rand des Portals.",
          description=[
              "Der Drache lässt sich neu beschwören. Dafür brauchst du &6vier Endkristalle&r. Einen Kristall baust du an der Werkbank aus sieben &6Glas&r, einem &6Enderauge&r und einer &6Ghastträne&r.",
              "",
              "Leg die vier Kristalle auf den Rand des Ausgangsportals, an jede der vier Seiten einen. Die Säulen bauen sich neu auf, die Kristalle und Käfige kommen zurück, und der Drache erscheint. &eYUNG's Better End Island&r lässt dazu eine Glocke läuten und baut den Turm in der Mitte wieder auf.",
              "",
              "&eWarum sich das lohnt:&r Jeder Drache lässt wieder ein Drachenherz, Drachenatem und rund &e64 Draconiumstaub&r fallen. Und alle, die beim ersten Mal nicht den letzten Schlag hatten, bekommen hier ihre Chance.",
          ],
          tasks=[task_advancement("minecraft:end/respawn_dragon", "Den Drachen neu beschwören"), task_kill("minecraft:ender_dragon", 1)],
          rewards=[reward_item("minecraft:ghast_tear", 4), reward_table("s4_uncommon"), reward_xp(20)],
          deps=["dragon"], icon="minecraft:end_crystal", size=1.5),

    # ---- Die äußeren Inseln --------------------------------------------------
    quest("gateway", 5, 10.5, "&5Das Transitportal",
          subtitle="Eine Enderperle durch das Loch.",
          description=[
              "Nach jedem Sieg über den Drachen erscheint am Rand der Hauptinsel ein &5End-Transitportal&r. Es ist nur einen Block groß, und hinein kommst du am einfachsten, indem du eine &6Enderperle&r hineinwirfst.",
              "",
              "Auf der anderen Seite liegen die &eäußeren Inseln&r, etwa tausend Blöcke von der Mitte entfernt. Dort gibt es die Endsiedlungen, die Chorus-Wälder und viel mehr Platz.",
              "",
              "&eZurück:&r Neben deiner Landestelle entsteht ein Gegenstück. Merk dir die Stelle oder stell gleich einen Wegstein daneben.",
          ],
          tasks=[task_advancement("minecraft:end/enter_end_gateway", "Durch ein Transitportal reisen")],
          rewards=[reward_item("minecraft:ender_pearl", 16), reward_xp(10)],
          deps=["dragon"], icon="minecraft:ender_pearl", size=1.5),

    quest("end_city", 7.5, 10.5, "&dEndsiedlungen",
          subtitle="Lila Türme in der Leere.",
          description=[
              "Auf den äußeren Inseln stehen &dEndsiedlungen&r: hohe Türme aus &6Purpur&r und Endsteinziegeln mit Brücken und Räumen voller Truhen.",
              "",
              "&eDarin:&r Gute Beute, oft verzauberte Diamant- und Eisenausrüstung, Erze und Sättel. Und in den Wänden sitzen &dShulker&r.",
              "",
              "&eTipp:&r Die Türme sind hoch, und es geht nach allen Seiten in die Leere. Bau dir Geländer, wo du kämpfst.",
          ],
          tasks=[task_advancement("minecraft:end/find_end_city", "Eine Endsiedlung finden")],
          rewards=[reward_table("s4_common"), reward_xp(10)],
          deps=["gateway"], icon="minecraft:purpur_block"),

    quest("shulker", 10, 10.0, "&dShulker",
          subtitle="Kisten, die Kisten tragen.",
          description=[
              "&dShulker&r verstecken sich in Kästen an den Wänden der Endsiedlungen. Ihre Geschosse lassen dich schweben. Hoch oben über der Leere ist das gefährlich, denn wenn die Wirkung endet, fällst du.",
              "",
              "&eShulkerschalen:&r Zwei Schalen und eine Truhe ergeben eine &6Shulkerkiste&r. Die behält beim Abbauen ihren Inhalt, ein tragbares Lager.",
              "",
              "&eNachschub:&r Shulker kommen nicht wieder. Mit &6Occultism&r kannst du aber selbst welche machen: Das Afrit-Ritual &eBesessener Shulker&r braucht Drachenatem, Endstein und zwei lila glasierte Keramik und opfert einen Schleim oder Magmawürfel.",
          ],
          tasks=[task_item("minecraft:shulker_shell", 4), task_item("minecraft:shulker_box", 1)],
          rewards=[reward_item("minecraft:shulker_shell", 2), reward_xp(10)],
          deps=["end_city"], icon="minecraft:shulker_shell"),

    quest("elytra", 10, 12.2, "&5Elytren",
          subtitle="An der Wand eines Endschiffs.",
          description=[
              "Neben manchen Endsiedlungen schwebt ein &5Endschiff&r. Am Bug hängt ein Drachenkopf, und im Inneren hängen &5Elytren&r in einem Rahmen. Pro Schiff gibt es nur ein Paar.",
              "",
              "&eFliegen:&r Leg die Elytren in den Brustplatz, spring und drück im Fallen nochmal Springen. Mit &6Feuerwerksraketen&r in der Hand bekommst du Schub.",
              "",
              "&eReparatur:&r Am Amboss mit &6Phantomhaut&r, oder mit Reparatur verzaubern.",
              "",
              "&eDraconic Evolution:&r Das &6Wyvern-Flugmodul&r für die Wyvern-Ausrüstung braucht eine Elytra.",
          ],
          tasks=[task_item("minecraft:elytra", 1)],
          rewards=[reward_item("minecraft:firework_rocket", 32), reward_item("minecraft:phantom_membrane", 4), reward_xp(15)],
          deps=["end_city"], icon="minecraft:elytra", size=1.5),

    quest("chorus", 5, 13.2, "&dChorus und Purpur",
          subtitle="Die Pflanze, die teleportiert.",
          description=[
              "&dChoruspflanzen&r wachsen auf den äußeren Inseln. Brich sie unten ab, dann fällt die ganze Pflanze.",
              "",
              "&eChorusfrüchte&r kannst du essen. Sie teleportieren dich ein Stück zufällig weg, was über der Leere ein Glücksspiel ist.",
              "",
              "&eIm Ofen&r werden sie zu &6Geplatzten Chorusfrüchten&r. Vier davon ergeben vier &6Purpurblöcke&r. Mit einer Lohenrute wird aus einer geplatzten Frucht ein &6Endstab&r, eine schöne Lampe.",
              "",
              "&eAnbauen:&r Eine &6Chorusblüte&r wächst nur auf Endstein. Ein paar Blöcke Endstein in der Basis reichen für eine kleine Farm.",
          ],
          tasks=[task_item("minecraft:chorus_fruit", 16), task_item("minecraft:popped_chorus_fruit", 8)],
          rewards=[reward_item("minecraft:end_stone", 16), reward_xp(5)],
          deps=["gateway"], icon="minecraft:chorus_fruit"),

    quest("structures", 7.5, 13.2, "&6Mehr als Endsiedlungen",
          subtitle="Andere Mods bauen auch hier.",
          description=[
              "Auf den äußeren Inseln steht mehr als Purpur:",
              "",
              "&6L_Ender's Cataclysm&r setzt die &6Ruined Citadel&r in die Endhochländer. Darin wartet der &cEnder Guardian&r, ein großer Boss für eine ganze Gruppe. Dort laufen auch &6Ender Golems&r herum, die einen &6Void Core&r fallen lassen.",
              "",
              "&6When Dungeons Arise&r baut die &6Aviary&r, eine Anlage hoch über den Inseln, und auch seine schwebenden Himmelsbauten stehen hier.",
              "",
              "&eKronwerke:&r Wer eine Citadel findet, sagt im Chat Bescheid. So ein Boss ist ein guter Abend für den Stream.",
          ],
          tasks=[task_checkmark("Eine dieser Strukturen gefunden")],
          rewards=[reward_table("s4_common"), reward_xp(10)],
          deps=["gateway"], icon="minecraft:end_stone_bricks", optional=True),

    # ---- Für Technik und Magie -----------------------------------------------
    quest("draconium", 15, 4.5, "&5&lDraconium",
          subtitle="Gibt es nur noch im End.",
          description=[
              "&6Draconiumerz&r ist das Herz von &6Draconic Evolution&r. &eAuf Kronwerke&r wächst es nur im End: Die Erzadern in Oberwelt und Nether sind abgeschaltet.",
              "",
              "&eWo:&r Im Endstein zwischen Y 0 und 70, auf der Hauptinsel genauso wie auf den äußeren Inseln. Die Adern sind klein, aber es gibt mehrere pro Chunk.",
              "",
              "&eAbbauen:&r Ohne Behutsamkeit fallen &e2 bis 4 Draconiumstaub&r heraus, mit Glück mehr. Mit Behutsamkeit bekommst du das Erz, und das schmilzt nur zu einem Barren. Also lieber den Staub nehmen. Ein Staub im Ofen ergibt einen &6Draconiumbarren&r.",
              "",
              "Dazu kommen rund 64 Staub von jedem Drachen.",
              "",
              "&eKronwerke:&r Das Stufenziel will &e1 000 Draconiumbarren&r. Das ist viel Endstein.",
              "",
              img(item_texture("draconicevolution:draconium_dust"), 32, 32),
          ],
          tasks=[task_item("draconicevolution:draconium_dust", 32), task_item("draconicevolution:draconium_ingot", 16)],
          rewards=[reward_item("draconicevolution:draconium_ingot", 8), reward_table("s4_common"), reward_xp(10)],
          deps=["respawn"], icon="draconicevolution:draconium_ingot", size=2.0, shape="hexagon"),

    quest("elite_circuit", 17.5, 2.5, "&bElite-Schaltkreis",
          subtitle="Mekanism braucht das End.",
          description=[
              "Die Elite-Stufe von &6Mekanism&r ist mit Stufe 4 offen. Der Schlüssel ist der &6Elite-Schaltkreis&r.",
              "",
              "&eRezept auf Kronwerke:&r Zwei &6Fortgeschrittene Schaltkreise&r, zwei &6Verstärkte Legierungen&r (Reinforced Alloy) und ein &5Draconiumstaub&r an der Werkbank. Alle anderen Rezepte sind entfernt.",
              "",
              "Ohne das End also keine Elite-Maschinen, keine Elite-Leitungen und kein Weg zu den Ultimativen Schaltkreisen.",
              "",
              "&eKronwerke:&r Das Stufenziel will &e150 Elite-Schaltkreise&r. Bau dir dafür eine Linie: Draconiumstaub aus dem End, Verstärkte Legierung aus dem Metallurgischen Infusionierer.",
          ],
          tasks=[task_item("mekanism:elite_control_circuit", 4)],
          rewards=[reward_item("mekanism:alloy_reinforced", 4), reward_xp(10)],
          deps=["draconium"], icon="mekanism:elite_control_circuit"),

    quest("cells", 17.5, 6.5, "&bGroße Speicherzellen",
          subtitle="Draconium im Kern.",
          description=[
              "Die großen Zellen von &6Applied Energistics 2&r und &6MEGA Cells&r sind ab Stufe 4 offen, aber auch sie brauchen das End.",
              "",
              "&eRezept auf Kronwerke:&r In der Mitte jeder Zellkomponente sitzt ein Material ihrer Stufe. Die &6256k-Komponente&r und die MEGA-Komponenten für &61M&r und &64M&r brauchen je einen &5Draconiumbarren&r. Die 64k-Komponente will einen Himmelsbarren von Nature's Aura.",
              "",
              "Ab 16M brauchen die Komponenten erwecktes Draconium. Das kommt in Stufe 5.",
          ],
          tasks=[task_item("ae2:cell_component_256k", 1)],
          rewards=[reward_item("draconicevolution:draconium_ingot", 4), reward_xp(10)],
          deps=["draconium"], icon="ae2:cell_component_256k"),

    quest("supply", 20, 4.5, "&5&lLicht des Drachen",
          subtitle="Was das End für das Stufenziel hergibt.",
          description=[
              "Du kennst jetzt die Wege durch das End. Zeit, dass es für den Server arbeitet.",
              "",
              "&eKronwerke:&r Die Technik-Seite des Ziels &6Licht des Drachen&r will &e1 000 Draconiumbarren&r und &e150 Elite-Schaltkreise&r. Beides beginnt im Endstein. Die Magie-Seite sammelt &e128 Gaia-Geister&r und &e30 Mystic Staffs&r.",
              "",
              "Ein paar Leute mit Spitzhacke im End und eine Linie für die Schaltkreise zu Hause, dann füllt sich die Leiste. Bring die Barren und Schaltkreise zum Obelisken oder stell eine Truhe daneben.",
          ],
          tasks=[task_item("draconicevolution:draconium_ingot", 64), task_item("mekanism:elite_control_circuit", 8)],
          rewards=[reward_table("s4_rare"), reward_item("minecraft:ender_pearl", 16), reward_xp(25)],
          deps=["elite_circuit", "cells"], icon="minecraft:dragon_egg", size=2.5, shape="gear"),
]

images = [
    banner("the_end/title", "Das End", 9.5, -1.2, height=1.75, kind="title", colour="end"),
    banner("the_end/arrival", "Anreise", 1.25, 2.6, height=0.9, colour="end"),
    banner("the_end/dragon", "Der Drache", 7.5, 0.7, height=0.9, colour="end"),
    banner("the_end/islands", "Die äußeren Inseln", 7.5, 8.6, height=0.9, colour="end"),
    banner("the_end/tech", "Für Technik und Magie", 17.5, 0.7, height=0.9, colour="magic"),
]

chapter(C, "Das End", "minecraft:end_stone", "world", quests, shape="circle", order=32, stage=4,
        subtitle=["Stufe 4. Der Drache, die äußeren Inseln, Elytren und das Draconium für das Stufenziel."],
        images=images)
