"""Tips and tricks for people who have never played a modpack: how the quest book works
(rewards, pinned quests, chapter groups, veiled locked items), JEI and Jade, map, waystones,
claims and teams, the server rules of Kronwerke (STAGES.md), what to do about lag and crashes,
the keybinds that matter and their conflicts, death with the Corpse mod, and where to get help.
Checkmark quests only. Facts come from the server configs and the mod jars (key defaults were
read from the class files), nothing here needs an item."""
from ftbq import (chapter, quest, task_checkmark, reward_item, reward_table, reward_xp, banner)

C = "tips"

quests = [
    # ---- Einstieg --------------------------------------------------------------
    quest("welcome", 0, 0, "&6Tipps und Tricks",
          subtitle="Alles, was ein Modpack von Vanilla unterscheidet, auf einen Blick.",
          description=[
              "Noch nie ein Modpack gespielt? Dann ist dieses Kapitel für dich. Es erklärt die Dinge, die alle anderen Kapitel voraussetzen: das &6Questbuch&r, &6JEI&r, die &6Karte&r, &6Claims&r und &6Teams&r, die &6Regeln&r von Kronwerke und was du tust, wenn das Spiel hakt.",
              "",
              "Jede Quest hier ist ein kurzer Text und ein Haken. Lies, was dich interessiert, hak ab, hol dir die Belohnung. Fünf Reihen, von oben nach unten: &eQuestbuch&r, &eJEI und Jade&r, &eKarte und Team&r, &eRegeln&r, &eWenn es hakt&r.",
              "",
              "Wer Kronwerke schon kennt, überfliegt die Reihe &eRegeln&r und holt sich den Rest nebenbei.",
          ],
          tasks=[task_checkmark("Los geht's")],
          rewards=[reward_item("minecraft:torch", 16), reward_xp(2)],
          icon="ftbquests:book", size=2.5, shape="hexagon"),

    # ---- Das Questbuch -----------------------------------------------------------
    quest("q_open", 4.5, -8, "&6Öffne das Questbuch",
          subtitle="Das Buch oben links im Inventar.",
          description=[
              "Drück &eE&r für dein Inventar. Oben links sitzt ein kleines &6Buch&r, ein Klick darauf öffnet das Questbuch. Links stehen die Kapitel, in der Mitte die Quests, eine angeklickte Quest öffnet sich rechts als Text.",
              "",
              "Jede Quest hat &eAufgaben&r (unten links im Questfenster) und &eBelohnungen&r (unten rechts). Gegenstandsaufgaben erledigen sich von selbst, sobald der Gegenstand in deinem Inventar liegt. Er wird dir nicht weggenommen, außer die Quest sagt es ausdrücklich.",
              "",
              "&eTipp:&r Wer das Buch lieber per Taste öffnet, legt sich in den Steuerungseinstellungen unter &eFTB Quests&r eine fest. Standardmäßig ist dort keine belegt.",
          ],
          tasks=[task_checkmark("Buch geöffnet")],
          rewards=[reward_xp(2)],
          deps=["welcome"], icon="minecraft:book"),

    quest("q_claim", 6.5, -8, "&6Hol dir eine Belohnung",
          subtitle="Fertige Quests leuchten, bis du klickst.",
          description=[
              "Ist eine Quest erledigt, bekommst du oben rechts die Meldung &eQuest abgeschlossen!&r. Die Belohnung landet aber nicht von allein bei dir: Öffne die Quest und &eklicke die Belohnung&r unten rechts an.",
              "",
              "Hast du mehrere offen, nimm den Knopf &eAlle Belohnungen einfordern&r am unteren Rand des Buchs. Ist dein Inventar voll, fällt die Belohnung vor dir auf den Boden.",
              "",
              "Viele Quests geben &6Kisten&r: &7Steinkiste&r, &fEisenkiste&r und &6Goldkiste&r, in dieser Reihenfolge besser. Rechtsklick öffnet sie. Am Ende dieses Kapitels wartet eine Goldkiste.",
          ],
          tasks=[task_checkmark("Belohnung eingesammelt")],
          rewards=[reward_item("minecraft:bread", 8), reward_xp(2)],
          deps=["q_open"], icon="ftbquests:lootcrate"),

    quest("q_pin", 8.5, -8, "&6Fixiere eine Quest",
          subtitle="Dein Ziel bleibt am Bildschirmrand stehen.",
          description=[
              "Oben rechts im Questfenster gibt es den Knopf &eFixieren&r. Eine fixierte Quest wird dir mit ihren Aufgaben am Rand des Bildschirms eingeblendet, auch wenn das Buch zu ist.",
              "",
              "So siehst du beim Spielen, wie viele Barren noch fehlen, ohne das Buch zu öffnen. &eLösen&r nimmt sie wieder weg.",
              "",
              "&eTipp:&r Für Streamer ideal: Zuschauer sehen jederzeit, woran du gerade arbeitest.",
          ],
          tasks=[task_checkmark("Eine Quest fixiert")],
          rewards=[reward_xp(3)],
          deps=["q_claim"], icon="minecraft:item_frame"),

    quest("q_groups", 10.5, -8, "&6Finde dich in den Kapiteln zurecht",
          subtitle="Fünf Gruppen, ein Kapitel pro Mod.",
          description=[
              "Links im Buch sind die Kapitel in Gruppen sortiert: &6Start&r, &6Technik&r, &dMagie&r, &aWelt und Erkundung&r und &6Lager und Werkzeug&r. Ein Klick auf den Gruppennamen klappt sie ein und aus.",
              "",
              "Jedes Kapitel ist ein Mod oder ein Thema und beginnt mit dem einfachsten Schritt. Die Quests hängen über Linien zusammen: Was von einer Quest abhängt, wird erst sichtbar oder machbar, wenn sie erledigt ist.",
              "",
              "Kapitel späterer Stufen erscheinen, sobald die Stufe offen ist. In Stufe 1 sind es sieben Kapitel, am Ende der Season rund 45.",
          ],
          tasks=[task_checkmark("Gruppen angeschaut")],
          rewards=[reward_xp(3)],
          deps=["q_pin"], icon="minecraft:bookshelf"),

    quest("q_locked", 12.5, -8, "&cErkenne gesperrte Gegenstände",
          subtitle="Dunkles Feld, Fragezeichen, drei Zeilen Tooltip.",
          description=[
              "Gegenstände einer Stufe, die noch nicht offen ist, werden &everhüllt&r gezeichnet: ein dunkles Feld mit einem Fragezeichen, egal ob im Inventar, in einer Truhe oder in JEI. Der Tooltip sagt &7???&r, darunter &cÖffnet in Stufe 2 (Messingwerk).&r und &8Einstecken geht, benutzen noch nicht.&r",
              "",
              "Genau so ist es gemeint: Aufheben und lagern darfst du alles. In der Hand halten, anziehen, platzieren oder herstellen geht erst, wenn die Stufe offen ist. Landet so etwas in deiner Hand, wandert es von selbst zurück ins Inventar.",
              "",
              "Findest du Verhülltes in einer Truhe, nimm es mit. Am Tag der Stufenöffnung zeigt es seinen Namen und du kannst es sofort benutzen.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["q_groups"], icon="minecraft:barrier"),

    # ---- JEI und Jade ------------------------------------------------------------
    quest("j_recipe", 4.5, -4, "&6Schau ein Rezept nach",
          subtitle="R für das Rezept, U für die Verwendung.",
          description=[
              "Die Liste rechts in jedem Inventar ist &6JEI&r. Fahr mit der Maus über einen Gegenstand, egal ob in der Liste oder in deinem Inventar, und drück &eR&r: JEI zeigt dir alle Wege, ihn herzustellen. &eU&r zeigt dir alles, wofür er gebraucht wird.",
              "",
              "Oben im Rezeptfenster blätterst du durch die Arten: Werkbank, Ofen, Mahlstein, Manabecken und so weiter. Mit der &eRücktaste&r springst du zum vorigen Rezept zurück, &eEsc&r schließt das Fenster.",
              "",
              "&eTipp:&r Ein Rezept, bei dem die Zutaten durchwechseln, nimmt jede der gezeigten Zutaten. Kein Grund zur Verwirrung.",
          ],
          tasks=[task_checkmark("Ein Rezept nachgeschaut")],
          rewards=[reward_xp(2)],
          deps=["welcome"], icon="minecraft:knowledge_book"),

    quest("j_search", 6.5, -4, "&6Such etwas in JEI",
          subtitle="Suchfeld, Mod-Filter, Lesezeichen.",
          description=[
              "Mit &eStrg+F&r springst du ins Suchfeld unten rechts. Tipp einen Teil des Namens, die Liste filtert sofort. Mit &e@create&r siehst du alles aus einem Mod, zum Beispiel alle Blöcke von Create.",
              "",
              "&eA&r über einem Gegenstand setzt ein &eLesezeichen&r. Die Lesezeichen stehen links im Inventar und bleiben, bis du sie mit A wieder löschst. Praktisch für die Zutatenliste einer größeren Maschine.",
              "",
              "&eStrg+O&r blendet JEI komplett aus und wieder ein, falls du mal Platz brauchst.",
          ],
          tasks=[task_checkmark("Gesucht und gefunden")],
          rewards=[reward_xp(3)],
          deps=["j_recipe"], icon="minecraft:spyglass"),

    quest("j_transfer", 8.5, -4, "&6Lass JEI die Werkbank füllen",
          subtitle="Der Plus-Knopf legt die Zutaten hinein.",
          description=[
              "Steh an einer &6Werkbank&r, such das Rezept mit &eR&r heraus und klick auf das kleine &e+&r unten rechts im Rezept. JEI legt die Zutaten aus deinem Inventar an die richtigen Stellen. &eShift&r und Klick füllt gleich einen ganzen Stapel.",
              "",
              "Ist der Knopf rot, fehlt dir etwas. Fahr mit der Maus darüber, dann steht dort, was.",
              "",
              "Das klappt auch in vielen Maschinen mit Rezeptfenster, etwa im Ofen oder in der Infusionsanlage von Mekanism ab Stufe 2.",
          ],
          tasks=[task_checkmark("Einmal übertragen")],
          rewards=[reward_item("minecraft:oak_log", 16), reward_xp(3)],
          deps=["j_search"], icon="minecraft:crafting_table"),

    quest("j_next", 10.5, -4, "&6Sieh, was in der nächsten Stufe kommt",
          subtitle="Verhüllt, aber mit Rezept.",
          description=[
              "Die Gegenstände der &enächsten Stufe&r stehen schon in der JEI-Liste, verhüllt mit dem dunklen Feld und dem Fragezeichen. Mit &eR&r siehst du trotzdem ihr Rezept und kannst &evorausplanen&r: Zink für Messing lässt sich zum Beispiel schon in Stufe 1 abbauen und einlagern.",
              "",
              "Stufe 3 und alles danach bleibt unsichtbar, bis es an der Reihe ist. So siehst du immer, wie viel kommt, aber die Liste wird nicht von Dingen überschwemmt, die noch Wochen entfernt sind.",
              "",
              "Herstellen kannst du Verhülltes nicht, die Werkbank sagt dann &7Das kannst du noch nicht herstellen&r.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["j_transfer"], icon="minecraft:clock"),

    quest("j_jade", 12.5, -4, "&6Lies das Jade-Fenster",
          subtitle="Worauf du schaust, steht oben am Bildschirm.",
          description=[
              "&6Jade&r blendet oben in der Mitte ein, welchen Block oder welches Wesen du gerade ansiehst, und aus welchem Mod es stammt. Bei Öfen und Maschinen siehst du den Inhalt und den Fortschritt, bei Pflanzen den Wuchs, bei Tieren und Monstern die Herzen.",
              "",
              "Halte &eShift&r, dann zeigt Jade mehr Details. Mit &eZiffernblock 1&r blendest du das Fenster aus und wieder ein, &eZiffernblock 0&r öffnet die Einstellungen.",
              "",
              "&eTipp:&r Der Mod-Name im Fenster sagt dir, in welchem Kapitel des Questbuchs du nachlesen kannst.",
          ],
          tasks=[task_checkmark("Fenster gelesen")],
          rewards=[reward_xp(3)],
          deps=["j_next"], icon="minecraft:oak_sign"),

    quest("j_books", 14.5, -4, "&6Lies die Bücher der Mods",
          subtitle="Fast jeder große Mod bringt sein eigenes Handbuch mit.",
          description=[
              "Das Questbuch führt dich durch den Anfang jedes Mods. Für alles, was tiefer geht, haben die Mods eigene Bücher: die &6Lexica Botania&r (ein Buch und ein Setzling an der Werkbank), das &6Abgenutzte Notizbuch&r von Ars Nouveau, die &6Silent Gear Anleitung&r und das &6Dictionary of Spirits&r von Occultism.",
              "",
              "Create erklärt sich mit &6Ponder&r: Fahr im Inventar oder in JEI über einen Create-Block und halte &eW&r gedrückt. Eine kleine Szene zeigt dir, wie er funktioniert.",
              "",
              "Alle Bücher sind in JEI zu finden. Such nach dem Mod mit &e@&r, das Buch steht meist ganz vorn.",
          ],
          tasks=[task_checkmark("Ein Buch aufgeschlagen")],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["j_jade"], icon="botania:lexica_botania"),

    # ---- Karte, Claims und Team -----------------------------------------------
    quest("m_map", 4.5, 0, "&6Öffne die Karte",
          subtitle="M für FTB Chunks, J für JourneyMap.",
          description=[
              "Zwei Karten sind im Pack. &eM&r öffnet die große Karte von &6FTB Chunks&r, auf ihr beanspruchst du auch deine Chunks. &eJ&r öffnet &6JourneyMap&r mit der Minimap oben rechts. Beide zeichnen auf, was du gesehen hast.",
              "",
              "&eB&r setzt in JourneyMap einen &eWegpunkt&r an deiner Position. Aktivierte Wegsteine landen automatisch als Wegpunkte auf der Karte. Mit &eF3&r siehst du deine genauen Koordinaten.",
              "",
              "&eTipp:&r Ein Wegpunkt am Portal zur Minendimension und einer an deiner Basis ersparen dir die meisten Irrwege.",
          ],
          tasks=[task_checkmark("Karte geöffnet")],
          rewards=[reward_item("minecraft:map", 1), reward_xp(3)],
          deps=["welcome"], icon="minecraft:filled_map"),

    quest("m_waystone", 6.5, 0, "&6Aktiviere einen Wegstein",
          subtitle="Einmal anklicken, immer wieder hinreisen.",
          description=[
              "&6Wegsteine&r stehen in Dörfern und verstreut in der Wildnis. Ein &eRechtsklick&r aktiviert einen für dich, ab dann reist du von jedem Wegstein zu jedem anderen, den du schon kennst. Der am Spawn bringt dich mit einem Klick zum Obelisken.",
              "",
              "Die Reise kostet &eErfahrungslevel&r: etwa ein Level pro 100 Blöcke Luftlinie, höchstens 27. In eine andere Dimension sind es immer 27 Level. Globale Wegsteine, Warpplatten und Rückkehr-Schriftrollen kosten nichts. Was ein Ziel kostet, steht im Auswahlmenü daneben.",
              "",
              "Eigene Wegsteine, Warpsteine und Schriftrollen zeigt dir das Kapitel &aErkundung&r.",
          ],
          tasks=[task_checkmark("Einen Wegstein aktiviert")],
          rewards=[reward_item("waystones:warp_dust", 4), reward_xp(3)],
          deps=["m_map"], icon="waystones:waystone"),

    quest("m_claim", 8.5, 0, "&6Sichere deine Basis",
          subtitle="500 Chunks für dich, 25 davon dauerhaft geladen.",
          description=[
              "Öffne mit &eM&r die Karte und drück &eC&r für die Claim-Ansicht. &eLinke Maustaste&r ziehen beansprucht Chunks, &erechte Maustaste&r ziehen gibt sie frei. In deinen Chunks kann niemand außer deinem Team Blöcke abbauen, Truhen öffnen oder Tiere schlagen, und Creeper sprengen nichts.",
              "",
              "Du hast &e500 Chunks&r. Das ist viel, aber nicht das ganze Tal: Ein Chunk ist 16 mal 16 Blöcke, 500 reichen für eine große Basis mit Feldern und Fabrik.",
              "",
              "&eShift&r und linke Maustaste ziehen lädt Chunks &edauerhaft&r, bis zu &e25&r. Maschinen darin laufen weiter, während du anderswo bist, allerdings nur, solange jemand aus deinem Team online ist.",
          ],
          tasks=[task_checkmark("Basis gesichert")],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["m_waystone"], icon="minecraft:oak_fence"),

    quest("m_team", 10.5, 0, "&6Gründe ein Team",
          subtitle="Geteilte Claims, geteilter Fortschritt.",
          description=[
              "Im Inventar gibt es links den Knopf &eMein Team&r, oder du nimmst den Befehl &e/ftbteams party create <Name>&r. Mitspieler lädst du mit &e/ftbteams party invite <Spieler>&r ein. Die Teamgröße ist nicht begrenzt.",
              "",
              "Ein Team teilt sich die &eClaims&r (500 Chunks fürs ganze Team, nicht pro Kopf) und den &eQuestfortschritt&r: Was einer erledigt, ist für alle erledigt. Die Belohnung holt sich trotzdem jeder selbst ab.",
              "",
              "&eTipp:&r Mit &6Ping Wheel&r zeigst du deinem Team, wo es langgeht: &eMaustaste 5&r (eine Seitentaste) setzt einen Ping dort, wo du hinschaust, sichtbar für alle in der Nähe.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("minecraft:white_banner", 1), reward_xp(3)],
          deps=["m_claim"], icon="minecraft:white_banner"),

    # ---- Die Regeln von Kronwerke ------------------------------------------------
    quest("r_together", 4.5, 4, "&6Verstehe die Regel Nummer eins",
          subtitle="Eine Stufe öffnet für alle zugleich, oder gar nicht.",
          description=[
              "Kronwerke hat &efünf Stufen&r, und keine davon schaltet ein einzelner Spieler frei. Jede öffnet sich für den ganzen Server auf einmal, sobald das &eGemeinschaftsziel&r am Obelisken erfüllt ist.",
              "",
              "Jedes Ziel hat zwei Säulen, &6Technik&r und &dMagie&r, in Stufe 1 dazu &7Stein&r. Alle müssen voll werden. Ein Server, der nur Maschinen baut, kommt nicht weiter, einer, der nur zaubert, auch nicht.",
              "",
              "Nichts wird aus dem Pack entfernt, manches kommt nur später. Am Ende der Season ist jeder Mod erreichbar. Vanilla ist nicht gesperrt, außer dem &cNether&r (Stufe 2) und dem &dEnde&r (Stufe 4).",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(3)],
          deps=["welcome"], icon="minecraft:lodestone"),

    quest("r_obelisk", 6.5, 4, "&6Gib etwas am Obelisken ab",
          subtitle="Jeder Stapel zählt, auch der kleine.",
          description=[
              "Der &6Obelisk&r steht am Spawn. Halte einen Stapel in der Hand und mach einen &eRechtsklick&r darauf. &eSchleichen&r und Rechtsklick gibt alles aus deinem Inventar ab, was das Ziel gerade braucht. Der Ausweichweg ist &e/kw deposit&r.",
              "",
              "In Stufe 1 will das Ziel &6Bruchstein&r, &6Andesitlegierung&r und &6Quelljuwelen&r. Bruchstein hat jeder, also wirf ihn nicht weg. Wie weit es ist, siehst du an der &eBossleiste&r oben und mit &e/kw goals&r.",
              "",
              "Alles Weitere, Zubringer-Truhen und die Meilensteine, erklärt das Kapitel &6Hier geht's los&r.",
          ],
          tasks=[task_checkmark("Abgegeben")],
          rewards=[reward_xp(3)],
          deps=["r_together"], icon="minecraft:cobblestone"),

    quest("r_hold", 8.5, 4, "&cWarte auf das Finale",
          subtitle="Bei 98 Prozent ist Schluss, bis alle da sind.",
          description=[
              "Bei &e98 Prozent&r nimmt der Obelisk nichts mehr an. Dann legt das Team einen Termin fest, alle Streamer gehen gemeinsam live, und die letzten Gegenstände wandern zusammen hinein. In diesem Moment öffnet die nächste Stufe für alle.",
              "",
              "Niemand ist früher dran, niemand verpasst etwas, weil er gerade offline war. Den Termin erfährst du im &9Discord&r.",
              "",
              "&eTipp:&r Heb dir einen kleinen Stapel fürs Finale auf, dann wirfst du beim Event selbst etwas ein.",
          ],
          tasks=[task_checkmark("Ich bin dabei")],
          rewards=[reward_xp(5)],
          deps=["r_obelisk"], icon="minecraft:beacon"),

    quest("r_events", 10.5, 4, "&6Sei bei den Events dabei",
          subtitle="Vier Abende, an denen der Server zusammenkommt.",
          description=[
              "Zwei Stufen öffnen mit einem Event, das live auf allen Streams läuft: Mit Stufe 2 wird das &cNetherportal am Spawn&r entzündet, mit Stufe 4 das &dEndportal&r aktiviert. Der &5Enderdrache&r ist der erste Boss, den der Server gemeinsam bekämpft.",
              "",
              "Dazu kommen die Finale der Stufenziele, in Stufe 4 mehrere Kämpfe gegen die &aGaia-Wächterin&r, und ganz am Ende der Kampf gegen den &cChaos Guardian&r, der die Season beendet.",
              "",
              "Wer später einsteigt, bekommt die &6Starterpakete&r aller schon offenen Stufen und ist schnell dabei. Niemand fängt in Woche vier bei null an.",
          ],
          tasks=[task_checkmark("Gelesen")],
          rewards=[reward_table("s1_common"), reward_xp(3)],
          deps=["r_hold"], icon="minecraft:bell"),

    quest("r_fair", 12.5, 4, "&6Spiel fair",
          subtitle="Dreißig Leute, eine Welt, sieben Wochen.",
          description=[
              "Auf den Server kommst du über den &9Discord&r, und wer den Discord verlässt, fliegt auch von der Whitelist. Was dort an Regeln steht, gilt im Spiel.",
              "",
              "Ein paar Dinge versteht sich von selbst: Fremde Körper lässt du liegen (jeder kann sie öffnen, siehe unten). Truhen in Bauwerken haben dank &6Lootr&r für jeden Spieler eigenen Inhalt, es gibt also keinen Grund, sie leer zu räumen. Claims respektierst du, auch wenn irgendwo eine Lücke ist.",
              "",
              "Bei Fragen oder Ärger: nicht im Chat ausdiskutieren, sondern das Team im Discord ansprechen.",
          ],
          tasks=[task_checkmark("Einverstanden")],
          rewards=[reward_xp(5)],
          deps=["r_events"], icon="minecraft:shield"),

    # ---- Wenn es hakt --------------------------------------------------------------
    quest("h_lag", 4.5, 8, "&6Erkenne, woher das Ruckeln kommt",
          subtitle="Bei dir oder beim Server, das ist der Unterschied.",
          description=[
              "Drück &eF3&r. Oben links steht &eFPS&r, deine Bilder pro Sekunde. Sind sie niedrig, ruckelt es bei dir: Sichtweite in den Videoeinstellungen auf &e8 Chunks&r, Partikel auf &eVerringert&r, Wolken aus. Das bringt mehr als jede andere Einstellung.",
              "",
              "Laufen die FPS hoch, aber Blöcke kommen nach dem Abbauen zurück und Türen reagieren spät, ist es der &eServer&r. Dann hilft bei dir nichts, sag im Chat Bescheid, und das Team schaut nach, wessen Maschine gerade die Welt bremst.",
              "",
              "&eTipp:&r Riesige Create-Anlagen und viele Items auf dem Boden kosten den Server am meisten. Ein Trichter in eine Truhe statt ein Haufen Bruchstein auf dem Boden hilft allen.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_xp(2)],
          deps=["welcome"], icon="minecraft:redstone"),

    quest("h_memory", 6.5, 8, "&6Gib dem Spiel genug Speicher",
          subtitle="230 Mods brauchen mehr als Vanilla.",
          description=[
              "Hängt das Spiel beim Laden lange, ruckelt es alle paar Sekunden kurz oder stürzt es mit &7OutOfMemory&r ab, hat Minecraft zu wenig &eArbeitsspeicher&r. In &6Prism Launcher&r stellst du ihn unter &eInstanz bearbeiten, Einstellungen, Java&r ein, in der &6Modrinth App&r in den Optionen der Instanz unter &eJava und Speicher&r.",
              "",
              "Als Faustregel für dieses Pack: &e6 bis 8 GB&r, und nie mehr als die Hälfte von dem, was dein Rechner hat. Mehr hilft nicht, Minecraft nutzt es nicht besser.",
              "",
              "Das Pack braucht &eJava 21&r. Beide Launcher bringen es selbst mit, du musst nichts installieren.",
          ],
          tasks=[task_checkmark("Speicher geprüft")],
          rewards=[reward_xp(3)],
          deps=["h_lag"], icon="minecraft:hopper"),

    quest("h_crash", 8.5, 8, "&6Finde die Logdatei",
          subtitle="Ohne Log kann dir niemand helfen.",
          description=[
              "Stürzt das Spiel ab, öffne im Launcher den &eInstanzordner&r. Darin liegt &elogs/latest.log&r mit allem, was das Spiel zuletzt getan hat, und im Ordner &ecrash-reports&r eine Datei mit Datum und Uhrzeit des Absturzes.",
              "",
              "Schick die &eDatei&r in den Discord, nicht einen Screenshot davon. Dazu zwei Sätze: Was hast du gerade gemacht, und passiert es immer wieder? Die meisten Abstürze sind damit in Minuten geklärt.",
              "",
              "Für die Welt musst du dir keine Sorgen machen: &6FTB Backups&r sichert den Server alle &e2 Stunden&r, solange jemand online ist, und behält die letzten zwölf Sicherungen.",
          ],
          tasks=[task_checkmark("Weiß, wo das Log liegt")],
          rewards=[reward_item("minecraft:paper", 8), reward_xp(3)],
          deps=["h_memory"], icon="minecraft:paper"),

    quest("h_keys", 10.5, 8, "&6Prüf deine Tasten",
          subtitle="Ein paar Standardtasten liegen doppelt.",
          description=[
              "Die Tasten, die du brauchst: &eR&r und &eU&r Rezepte in JEI, &eM&r Karte und Claims, &eJ&r JourneyMap, &eB&r Wegpunkt, &eV&r Sprachchat-Menü, &eK&r Nachtsicht (Tiefgräber), &e`&r (links neben der 1) Ultimine, &eW&r gedrückt halten für Ponder, &eU&r außerhalb von Menüs die Todeshistorie.",
              "",
              "Einige davon sind &cdoppelt belegt&r, dann passiert beides auf einmal: &eV&r ist auch die erste Fähigkeit deiner Herkunft, &eG&r Sprachchat-Gruppen und die zweite Fähigkeit, &eH&r blendet Sprachchat-Symbole aus und ist die Rollen-Fähigkeit, &eM&r schaltet zusätzlich dein Mikrofon stumm, &eB&r sortiert außerdem das Inventar.",
              "",
              "Leg dir in den &eSteuerungseinstellungen&r die Sprachchat-Tasten (Kategorie Simple Voice Chat) und die Fähigkeitentasten (Kategorie NeoOrigins) auf freie Tasten, bevor dich der Mikrofon-Knopf mitten im Kampf überrascht.",
          ],
          tasks=[task_checkmark("Tasten geprüft")],
          rewards=[reward_xp(3)],
          deps=["h_crash"], icon="minecraft:lever"),

    quest("h_voice", 12.5, 8, "&6Richte den Sprachchat ein",
          subtitle="48 Blöcke weit hört man dich.",
          description=[
              "&eV&r öffnet das Menü von &6Simple Voice Chat&r. Dort wählst du dein Mikrofon, stellst die Lautstärke ein und entscheidest zwischen &eSprachaktivierung&r und &ePush-to-Talk&r. Die Push-to-Talk-Taste legst du in den Steuerungseinstellungen fest, standardmäßig ist keine belegt.",
              "",
              "Wer näher als &e48 Blöcke&r ist, hört dich, leiser mit der Entfernung. Flüstern reicht 24 Blöcke. Über das Menü legst du &eGruppen&r an, dann hört dich dein Team über jede Entfernung.",
              "",
              "Die Symbole unten zeigen dir, ob dein Mikrofon stumm ist. Wenn dich niemand hört, schau zuerst dort nach, meist war es die Taste &eM&r.",
          ],
          tasks=[task_checkmark("Eingerichtet")],
          rewards=[reward_xp(3)],
          deps=["h_keys"], icon="minecraft:note_block"),

    quest("h_origin", 14.5, 8, "&6Nutze deine Herkunft",
          subtitle="O zeigt dir, was du kannst.",
          description=[
              "Beim ersten Betreten hast du eine &6Herkunft&r und eine &6Rolle&r gewählt. Mit &eO&r öffnest du jederzeit die Übersicht deiner Kräfte, mit Stärken und Schwäche.",
              "",
              "Die meisten Kräfte wirken von allein. Aktive brauchen eine Taste: Der &eSternensprung&r des Sternensplitters liegt auf der ersten Fähigkeitentaste (&eV&r), die &ePacktasche&r des Händlers auf der Rollen-Taste (&eH&r), die Nachtsicht des Tiefgräbers auf &eK&r. Siehe die Quest zu den Tasten, wenn V bei dir das Sprachchat-Menü öffnet.",
              "",
              "Keine Herkunft kann fliegen oder überspringt eine Stufe. Passt deine Wahl gar nicht, sprich das Team an.",
          ],
          tasks=[task_checkmark("Übersicht angeschaut")],
          rewards=[reward_xp(3)],
          deps=["h_voice"], icon="minecraft:ender_pearl"),

    quest("h_death", 16.5, 8, "&cHol deine Sachen zurück",
          subtitle="Dein Körper wartet, wo du gefallen bist.",
          description=[
              "Stirbst du, bleibt dein &6Körper&r mit allem, was du dabeihattest, an Ort und Stelle liegen. Lauf zurück, &eRechtsklick&r auf den Körper, Sachen herausnehmen. Er verschwindet nie, solange etwas darin ist, und wird nach einer Stunde zum Skelett, mit Inhalt.",
              "",
              "Weißt du nicht mehr, wo das war: &eU&r öffnet die &eTodeshistorie&r mit Dimension, Position und Uhrzeit jedes Todes. Schreib dir die Koordinaten auf oder setz einen Wegpunkt.",
              "",
              "&cAchtung:&r Jeder kann deinen Körper öffnen. In der Minendimension und in tiefen Höhlen also lieber schnell zurück. Ein &6Bett&r setzt deinen Spawnpunkt, damit du nicht am Weltspawn aufwachst.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_item("minecraft:golden_apple", 1), reward_xp(3)],
          deps=["h_origin"], icon="minecraft:skeleton_skull"),

    # ---- Abschluss --------------------------------------------------------------
    quest("h_help", 20.5, 0, "&6Frag nach Hilfe",
          subtitle="Hier hilft man sich. Wirklich.",
          description=[
              "Du kennst jetzt das Buch, JEI, die Karte, die Regeln und die Tasten. Alles andere lernst du beim Spielen, und niemand erwartet, dass du 230 Mods kennst.",
              "",
              "Wenn du nicht weiterkommst: Erst &eR&r und &eU&r in JEI, dann das passende &eKapitel&r im Buch, dann der &eChat&r oder der &eSprachchat&r. Dreißig Leute auf dem Server, einer hat die Maschine garantiert schon gebaut. Für alles Technische (Absturz, Installation, Whitelist) ist der &9Discord&r da, auf &ekronwerke.elchi.dev&r stehen die häufigsten Fragen und der Stand des Obelisken.",
              "",
              "Und umgekehrt: Wenn dich jemand im Chat fragt, wie ein Wasserrad geht, antworte. So funktioniert Kronwerke.",
          ],
          tasks=[task_checkmark("Verstanden")],
          rewards=[reward_table("s1_rare"), reward_xp(10)],
          deps=["q_locked", "j_books", "m_team", "r_fair", "h_death"],
          icon="minecraft:recovery_compass", size=2.5, shape="gear"),
]

images = [
    banner("tips/title", "Tipps und Tricks", 0, -2.6, height=1.2, kind="title", colour="brass"),
    banner("tips/book", "Das Questbuch", 8.5, -9.8, height=0.9, colour="brass"),
    banner("tips/jei", "JEI und Jade", 9.5, -5.8, height=0.9, colour="water"),
    banner("tips/map", "Karte, Claims und Team", 7.5, -1.8, height=0.9, colour="nature"),
    banner("tips/rules", "Die Regeln von Kronwerke", 8.5, 2.2, height=0.9, colour="stone"),
    banner("tips/help", "Wenn es hakt", 10.5, 6.2, height=0.9, colour="magic"),
]

chapter(C, "Tipps und Tricks", "minecraft:knowledge_book", "start", quests, shape="circle", order=1,
        subtitle=["Questbuch, JEI, Karte, Claims, Regeln und Tasten. Für alle, die noch nie ein Modpack gespielt haben."],
        images=images)
